import {z} from 'zod';
import {companyRuntimeSelectInput,companyRuntimeRevokeInput} from './company-runtime-protocol';

type Schema=Record<string,unknown>;
const uuid:Schema={type:'string',format:'uuid'},date:Schema={type:'string',format:'date-time'};
const summary:Schema={type:'object',additionalProperties:false,required:['companyId','kind','configurationId','selectionRevision','state','enabled','configurationHash','phase','expiresAt','createdAt','createdBy','computeStarted','spendingApproved'],properties:{companyId:uuid,kind:{enum:['managed_agent','archive','gateway']},configurationId:uuid,selectionRevision:{type:'integer',minimum:1},state:{enum:['active','revoked']},enabled:{type:'boolean'},configurationHash:{type:'string',pattern:'^[a-f0-9]{64}$'},phase:{enum:['preflight','service']},expiresAt:date,createdAt:date,createdBy:uuid,computeStarted:{const:false},spendingApproved:{const:false}}};
export const companyRuntimeSchemas={CompanyRuntimeConfiguration:summary};
const response=(schema:Schema)=>({description:'Successful response',content:{'application/json':{schema}}});
function operation(operationId:string,summary:string,input?:z.ZodType){return {operationId,summary,description:'Requires a current database-administrator-issued platform operator grant AND current human company administrator membership. Agents and ordinary company administrators cannot configure deployment execution. Presets contain no secret fields; API responses never include raw bootstrap code. Selection never starts compute or approves charges. Lifetime CPU/inference reservations survive replacement and revocation. Revoked or expired selections disable new work without restoring legacy environment fallback; cleanup remains possible.',security:[{sessionCookie:[]}],'x-coatria-roles':['platform_runtime_operator_and_company_admin'],parameters:[{name:'companyId',in:'path',required:true,schema:uuid},{name:'kind',in:'path',required:true,schema:{enum:['managed_agent','archive','gateway']}},...input?[{name:'Origin',in:'header',required:true,schema:{type:'string',format:'uri'}}]:[]],...input?{requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(input,{io:'input',unrepresentable:'any'})}}}}:{},responses:{'200':response({type:'object',properties:{configuration:{anyOf:[{$ref:'#/components/schemas/CompanyRuntimeConfiguration'},{type:'null'}]},...input?{replayed:{type:'boolean'}}:{}},required:input?['configuration','replayed']:['configuration'],additionalProperties:false}),...operationId==='selectCompanyRuntimeConfiguration'?{'201':response({type:'object',properties:{configuration:{$ref:'#/components/schemas/CompanyRuntimeConfiguration'},replayed:{const:false}},required:['configuration','replayed'],additionalProperties:false})}:{},...Object.fromEntries(['400','401','403','404','409','413','415','500','503'].map(status=>[status,response({$ref:'#/components/schemas/Error'})]))}};}
export const companyRuntimePaths={
 '/api/operator/companies/{companyId}/runtime-configurations/{kind}':{
  get:operation('getCompanyRuntimeConfiguration','Read the safe summary of a company runtime selection'),
  post:operation('selectCompanyRuntimeConfiguration','Install an immutable reviewed configuration without starting compute',companyRuntimeSelectInput),
  patch:operation('revokeCompanyRuntimeConfiguration','Revoke an exact runtime selection while preserving cleanup',companyRuntimeRevokeInput),
 },
};
