/** Prepared-image reference control plane. All methods require a caller-owned
 * transaction; provider I/O must occur only after its intent has committed. */
import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {z} from 'zod';
import {ApiError,fail,hashToken,id} from './security';
import {authorizeProjectStorageActor} from './project-storage';
import {projectImagePreparationProvenance} from './project-image-preparation-provenance';
import {assertStudioTaskAction} from './studio';
import {managedAgentAuthoritySql} from './studio-hosting';
import {referencePreparationDispatch,createReferenceInspectionAuthority,referenceInspectionAuthorityHash,assertReferenceInspectionAuthority,assertReferenceInspectionTask,lockReferenceInspectionAuthority} from './higgsfield-reference-inspection-authority';
import {HIGGSFIELD_REFERENCE_PREPARATION_CAPABILITIES,HIGGSFIELD_REFERENCE_GENERATION_CAPABILITIES,HIGGSFIELD_REFERENCE_INSPECTION_LIMITS} from './higgsfield-references-protocol';
import {sealHiggsfieldSecret,openHiggsfieldSecret} from './higgsfield-secrets';
import type {HiggsfieldTool} from './higgsfield-mcp';
import type {HiggsfieldReferenceResolution,HiggsfieldReferenceSnapshot} from './higgsfield-references-protocol';
import {HIGGSFIELD_REFERENCE_POLICY,higgsfieldReferenceProposalInput,higgsfieldReferenceListInput,higgsfieldReferenceCandidatesInput,higgsfieldReferenceApproveInput,higgsfieldReferenceRevokeInput,type HiggsfieldReferenceActor,type HiggsfieldReference,type HiggsfieldReferencePage,type HiggsfieldReferenceCandidatePage,type HiggsfieldReferenceVersion,type HiggsfieldReferenceInspection,type HiggsfieldReferenceAvailability,type HiggsfieldReferenceLease,type HiggsfieldReferencePhase,type HiggsfieldReferencePhaseResult} from './higgsfield-references-protocol';

type Row=Record<string,any>;
export type HiggsfieldReferenceOptions={availability?:(db:PoolClient,companyId:string,projectId:string)=>Promise<HiggsfieldReferenceAvailability>};
const parse=<T>(schema:z.ZodType<T>,value:unknown):T=>{const p=schema.safeParse(value);if(!p.success)fail(400,'Use the exact prepared image, revisions, inspection and explicit sharing consent.','VALIDATION_ERROR');return p.data;};
const canonical=(value:unknown):string=>Array.isArray(value)?'['+value.map(canonical).join(',')+']':value&&typeof value==='object'?'{'+Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>JSON.stringify(key)+':'+canonical(item)).join(',')+'}':JSON.stringify(value);
export const higgsfieldReferenceDigest=(value:unknown)=>hashToken(canonical(value));
const iso=(value:Date|string|null)=>value?new Date(value).toISOString():null;
const projectSnapshot=(p:Row)=>{const {revision:_revision,updated_at:_updated,...semantic}=p;return JSON.parse(JSON.stringify(semantic)) as Row;};
const changed=(code='HIGGSFIELD_REFERENCE_AUTHORITY_CHANGED'):never=>fail(409,'The exact reference authority changed. Prepare and review a new reference.',code);
const transferStates=['queued','reading','allocating','allocated','uploading','uploaded','confirming'];
const mediaTypes=['image/png','image/jpeg','image/webp'];
const sha=z.string().regex(/^[a-f0-9]{64}$/);
export const higgsfieldReferencesUnavailable:HiggsfieldReferenceAvailability={enabled:false,code:'HIGGSFIELD_REFERENCE_WORKER_UNQUALIFIED',message:'Reference sharing requires a separately qualified worker, supported company upload catalog and active project storage. No external upload is available.',expiresAt:null,qualificationSha256:null,catalogSha256:null};
export async function higgsfieldReferenceAvailability(db:PoolClient,companyId:string,projectId:string,options:HiggsfieldReferenceOptions={}):Promise<HiggsfieldReferenceAvailability>{return options.availability?options.availability(db,companyId,projectId):{...higgsfieldReferencesUnavailable};}
async function ready(db:PoolClient,row:Row,options:HiggsfieldReferenceOptions){
 const value=await higgsfieldReferenceAvailability(db,row.company_id,row.project_id,options);
 if(value.enabled!==true||!sha.safeParse(value.qualificationSha256).success||value.catalogSha256!==row.catalog_sha256||!value.expiresAt||!(await db.query('SELECT $1::timestamptz>clock_timestamp() AS valid',[value.expiresAt])).rows[0]?.valid)fail(503,higgsfieldReferencesUnavailable.message,'HIGGSFIELD_REFERENCE_UNAVAILABLE');
 if(row.qualification_sha256&&value.qualificationSha256!==row.qualification_sha256)changed();return value;
}
async function actorAuthority(db:PoolClient,actor:HiggsfieldReferenceActor,admin=false,capabilities?:readonly string[]){
 if(!(await db.query("SELECT 1 FROM memberships WHERE company_id=$1 AND user_id=$2 AND role<>'removed' AND access_revoked_at IS NULL FOR SHARE",[actor.companyId,actor.userId])).rowCount)fail(403,'Your current company membership is required.','HIGGSFIELD_REFERENCE_MEMBERSHIP_REQUIRED');
 await authorizeProjectStorageActor(db,actor,'storage.read',admin);
 if(actor.agentId){
  // Five-grant metadata access belongs to the explicit new dispatch profile;
  // ordinary and historical agent contracts retain their six-grant check.
  const required=capabilities??((await db.query('SELECT 1 FROM studio_reference_preparation_dispatches WHERE company_id=$1 AND run_id=$2 AND authority_version=1',[actor.companyId,actor.runId])).rowCount?HIGGSFIELD_REFERENCE_PREPARATION_CAPABILITIES:HIGGSFIELD_REFERENCE_GENERATION_CAPABILITIES);
  const row=(await db.query('SELECT a.created_by,a.capabilities,r.capabilities AS run_capabilities FROM agents a JOIN agent_runs r ON r.company_id=a.company_id AND r.agent_id=a.id WHERE a.company_id=$1 AND a.id=$2 AND r.id=$3 AND r.requested_by=$4 FOR SHARE OF a,r',[actor.companyId,actor.agentId,actor.runId,actor.userId])).rows[0];
  if(!row||required.some(cap=>!row.capabilities.includes(cap)||!row.run_capabilities.includes(cap)))fail(403,'Reference work needs current creative, studio, task and storage grants on the authenticated run.','AGENT_CAPABILITY_REQUIRED');
  await admins(db,actor.companyId,[row.created_by,actor.userId]);
 }
}
async function admins(db:PoolClient,companyId:string,ids:string[]){const expected=[...new Set(ids)].sort(),rows=(await db.query("SELECT user_id FROM memberships WHERE company_id=$1 AND user_id=ANY($2::uuid[]) AND role IN ('owner','admin') AND access_revoked_at IS NULL ORDER BY user_id FOR SHARE",[companyId,expected])).rows;if(rows.length!==expected.length)changed('HIGGSFIELD_REFERENCE_SPONSOR_UNAVAILABLE');}
async function project(db:PoolClient,companyId:string,projectId:string){const p=(await db.query('SELECT * FROM studio_projects WHERE company_id=$1 AND id=$2 FOR UPDATE',[companyId,id(projectId)])).rows[0];if(!p)fail(404,'Project not found.');if(p.status==='delivered'||p.ai_policy!=='allowed'||p.production_path!=='higgsfield'||['brief','estimate','production'].some(g=>p.gates[g]?.decision!=='approved'))changed('HIGGSFIELD_REFERENCE_PROJECT_CHANGED');return p;}
async function work(db:PoolClient,actor:HiggsfieldReferenceActor,p:Row,workId:string,accepted=false,durable?:Row){
 await db.query('SELECT role_key FROM studio_role_bindings WHERE company_id=$1 ORDER BY role_key FOR SHARE',[actor.companyId]);
 const w=(await db.query('SELECT w.*,t.status,t.revision AS task_revision,t.title,t.description,t.agent_run_id,t.assignee_id,t.submitted_by,t.submitted_agent_id,t.submission_summary,t.submission_url,t.approved_by,t.approved_agent_id,t.machine_review_id,b.agent_id,b.human_id FROM studio_work_items w JOIN tasks t ON t.company_id=w.company_id AND t.id=w.task_id LEFT JOIN studio_role_bindings b ON b.company_id=w.company_id AND b.role_key=w.role_key WHERE w.company_id=$1 AND w.project_id=$2 AND w.id=$3 FOR SHARE OF t',[actor.companyId,p.id,id(workId)])).rows[0];
 if(!w)fail(404,'Reference task not found in this project.');if(!['references','generation'].includes(w.stage)||!['agent','creative'].includes(w.execution)||!(durable?['doing','review','done']:accepted?['todo','doing','done']:['todo','doing']).includes(w.status))changed('HIGGSFIELD_REFERENCE_WORK_CHANGED');
 if(durable){if(p.contract_version!==2||w.stage!=='references'||w.execution!=='agent')changed('HIGGSFIELD_REFERENCE_WORK_CHANGED');await assertReferenceInspectionTask(db,durable,w);}
 let agent:Row|undefined,run:Row|undefined;
 if(actor.agentId){if(w.agent_id!==actor.agentId||w.status!=='doing'||w.agent_run_id!==actor.runId)fail(403,'Reserve the assigned reference or generation task for this run first.','STUDIO_TASK_RESERVATION_REQUIRED');agent=(await db.query('SELECT * FROM agents WHERE company_id=$1 AND id=$2',[actor.companyId,actor.agentId])).rows[0];run=(await db.query('SELECT * FROM agent_runs WHERE company_id=$1 AND id=$2',[actor.companyId,actor.runId])).rows[0];}
 await assertStudioTaskAction(db,actor.companyId,w.task_id,'higgsfield_reference_propose',{},run,agent);
 return {workItemId:w.id,taskId:w.task_id,taskRevision:w.task_revision,stage:w.stage,shotId:w.shot_id,roleKey:w.role_key,roleAgentId:w.agent_id??null,roleHumanId:w.human_id??null,taskContentHash:higgsfieldReferenceDigest({title:w.title,description:w.description}),status:w.status};
}
async function storage(db:PoolClient,companyId:string,projectId:string){
 const b=(await db.query('SELECT b.*,c.revision AS connection_revision,c.status AS connection_status,c.created_by AS sponsor,c.secret_envelope IS NOT NULL AS credentials FROM project_storage_bindings b JOIN project_storage_connections c ON c.company_id=b.company_id AND c.id=b.connection_id WHERE b.company_id=$1 AND b.project_id=$2 FOR SHARE OF b,c',[companyId,projectId])).rows[0];
 if(!b||b.connection_status!=='configured'||!b.credentials)changed('HIGGSFIELD_REFERENCE_STORAGE_CHANGED');await admins(db,companyId,[b.sponsor]);return b;
}
async function version(db:PoolClient,companyId:string,projectId:string,versionId:string,bindingId:string){
 const v=(await db.query('SELECT v.*,f.name,f.binding_id,ok.sha256 AS verified_sha256,ok.provider_etag FROM project_storage_versions v JOIN project_storage_files f ON f.company_id=v.company_id AND f.project_id=v.project_id AND f.id=v.file_id JOIN project_storage_verifications ok ON ok.company_id=v.company_id AND ok.project_id=v.project_id AND ok.version_id=v.id AND ok.bytes=v.bytes AND (v.sha256 IS NULL OR v.sha256=ok.sha256) WHERE v.company_id=$1 AND v.project_id=$2 AND v.id=$3',[companyId,projectId,id(versionId)])).rows[0];
 if(!v||v.binding_id!==bindingId)fail(404,'Verified file version not found in this project.');return {versionId:v.id,fileId:v.file_id,name:v.name,version:v.version,bytes:Number(v.bytes),sha256:v.verified_sha256,contentType:v.content_type,objectKey:v.object_key,providerEtag:v.provider_etag};
}
const versionView=(v:Row):HiggsfieldReferenceVersion=>({versionId:v.versionId,fileId:v.fileId,name:v.name,version:v.version,bytes:Number(v.bytes),sha256:v.sha256,contentType:v.contentType});
async function provider(db:PoolClient,companyId:string){const c=(await db.query('SELECT id,revision,status,connected_by,tools FROM higgsfield_connections WHERE company_id=$1 FOR SHARE',[companyId])).rows[0];if(!c||c.status!=='connected')changed('HIGGSFIELD_REFERENCE_PROVIDER_CHANGED');await admins(db,companyId,[c.connected_by]);return {...c,catalogSha256:higgsfieldReferenceDigest(c.tools)};}
async function row(db:PoolClient,companyId:string,referenceId:string,lock=false){
 id(companyId);id(referenceId);
 // Match generation's project -> reference lock order. The project scope is
 // immutable; reread the exact reference after obtaining its parent lock.
 if(lock){const scope=(await db.query('SELECT * FROM higgsfield_references WHERE company_id=$1 AND id=$2',[companyId,referenceId])).rows[0];if(!scope)fail(404,'Reference not found.');await lockReferenceInspectionAuthority(db,scope);await db.query('SELECT id FROM studio_projects WHERE company_id=$1 AND id=$2 FOR UPDATE',[companyId,scope.project_id]);}
 const r=(await db.query(`SELECT * FROM higgsfield_references WHERE company_id=$1 AND id=$2${lock?' FOR UPDATE':''}`,[companyId,referenceId])).rows[0];if(!r)fail(404,'Reference not found.');return r;
}
async function inspection(db:PoolClient,r:Row):Promise<HiggsfieldReferenceInspection|null>{const i=(await db.query('SELECT * FROM higgsfield_reference_inspections WHERE company_id=$1 AND reference_id=$2 AND request_hash=$3',[r.company_id,r.id,r.request_hash])).rows[0];return i?{descriptor:i.descriptor,profileSha256:i.profile_sha256,inspectionHash:i.inspection_hash,inspectedAt:iso(i.inspected_at)!}:null;}
async function view(db:PoolClient,r:Row):Promise<HiggsfieldReference>{return {id:r.id,projectId:r.project_id,workItemId:r.work_item_id,projectRevision:r.project_revision,taskRevision:r.work_snapshot.taskRevision,role:r.role,purpose:r.purpose,status:r.status,revision:r.revision,requestHash:r.request_hash,proxy:versionView(r.proxy_snapshot),source:r.source_snapshot?versionView(r.source_snapshot):null,storageConnectionId:r.storage_connection_id,storageConnectionRevision:r.storage_connection_revision,bindingId:r.storage_binding_id,bindingRevision:r.storage_binding_revision,providerConnectionId:r.provider_connection_id,providerConnectionRevision:r.provider_connection_revision,inspection:await inspection(db,r),proposedBy:r.proposed_by,proposedAgentId:r.proposed_agent_id,createdAt:iso(r.created_at)!,approvedBy:r.approved_by,approvedAt:iso(r.approved_at),expiresAt:iso(r.expires_at),approvalHash:r.approval_hash,revokedAt:iso(r.revoked_at),diagnosticCode:r.diagnostic_code,providerConfirmed:r.status==='confirmed'&&!!(await db.query('SELECT 1 FROM higgsfield_reference_confirmations WHERE company_id=$1 AND reference_id=$2 AND request_hash=$3 AND approval_hash=$4',[r.company_id,r.id,r.request_hash,r.approval_hash])).rowCount,originalUploaded:false,bytesSharedUnchanged:true,metadataRemoved:false,...r.inspection_authority?{inspectionAuthorityMode:'prepared_image_v1',inspectionExpiresAt:iso(r.inspect_expires_at)!,inspectionAttempts:r.inspection_attempts}:{}};}
async function once(db:PoolClient,actor:HiggsfieldReferenceActor,clientId:string,operation:string,data:unknown,run:()=>Promise<Row>){const key=actor.agentId?'agent:'+actor.agentId:'human:'+actor.userId,hash=higgsfieldReferenceDigest({operation,data});await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`higgsfield-reference:${actor.companyId}:${key}:${clientId}`]);const old=(await db.query('SELECT request_hash,response FROM higgsfield_reference_requests WHERE company_id=$1 AND actor_key=$2 AND client_id=$3',[actor.companyId,key,clientId])).rows[0];if(old){if(old.request_hash!==hash)fail(409,'This reference operation ID was used for different details.','IDEMPOTENCY_CONFLICT');return {...old.response,replayed:true};}const result=await run();await db.query('INSERT INTO higgsfield_reference_requests(company_id,actor_key,client_id,request_hash,response) VALUES($1,$2,$3,$4,$5)',[actor.companyId,key,clientId,hash,JSON.stringify(result)]);return {...result,replayed:false};}
async function receipt(db:PoolClient,r:Row,actionId:string,operation:string,phase:string,detail:Row={}){await db.query('INSERT INTO higgsfield_reference_receipts(company_id,project_id,reference_id,action_id,operation,phase,detail) VALUES($1,$2,$3,$4,$5,$6,$7)',[r.company_id,r.project_id,r.id,actionId,operation,phase,JSON.stringify(detail)]);}
async function facts(db:PoolClient,r:Row,accepted=false){
 const p=await project(db,r.company_id,r.project_id);if(higgsfieldReferenceDigest(projectSnapshot(p))!==r.project_sha256||higgsfieldReferenceDigest(r.project_snapshot)!==r.project_sha256||!accepted&&p.revision!==r.project_revision)changed('HIGGSFIELD_REFERENCE_PROJECT_CHANGED');
 const c=await provider(db,r.company_id);if(c.id!==r.provider_connection_id||c.revision!==r.provider_connection_revision||c.connected_by!==r.provider_sponsor_id||c.catalogSha256!==r.catalog_sha256)changed('HIGGSFIELD_REFERENCE_PROVIDER_CHANGED');
 const b=await storage(db,r.company_id,r.project_id);if(b.id!==r.storage_binding_id||b.revision!==r.storage_binding_revision||b.connection_id!==r.storage_connection_id||b.connection_revision!==r.storage_connection_revision||b.sponsor!==r.storage_sponsor_id)changed('HIGGSFIELD_REFERENCE_STORAGE_CHANGED');
 const proxy=await version(db,r.company_id,r.project_id,r.proxy_version_id,b.id),source=r.source_version_id?await version(db,r.company_id,r.project_id,r.source_version_id,b.id):null;
 if(higgsfieldReferenceDigest(proxy)!==higgsfieldReferenceDigest(r.proxy_snapshot)||higgsfieldReferenceDigest(source)!==higgsfieldReferenceDigest(r.source_snapshot))changed('HIGGSFIELD_REFERENCE_SOURCE_CHANGED');
 const w=await work(db,{companyId:r.company_id,userId:r.proposed_by},p,r.work_item_id,accepted,r.inspection_authority?r:undefined),old=r.work_snapshot;
 const comparable=(v:Row)=>({...v,status:undefined,...r.inspection_authority||accepted&&v.stage==='references'&&w.status==='done'?{taskRevision:undefined}:{}});
 if(higgsfieldReferenceDigest(comparable(w))!==higgsfieldReferenceDigest(comparable(old)))changed('HIGGSFIELD_REFERENCE_WORK_CHANGED');
 if(!(await db.query("SELECT 1 FROM memberships WHERE company_id=$1 AND user_id=$2 AND role<>'removed' AND access_revoked_at IS NULL FOR SHARE",[r.company_id,r.proposed_by])).rowCount)changed('HIGGSFIELD_REFERENCE_SPONSOR_UNAVAILABLE');
 if(r.inspection_authority)await assertReferenceInspectionAuthority(db,r);
 else if(r.proposed_agent_id){const a=(await db.query(`SELECT a.capabilities,a.created_by,r.capabilities AS run_capabilities FROM agents a JOIN agent_runs r ON r.company_id=a.company_id AND r.agent_id=a.id WHERE a.company_id=$1 AND a.id=$2 AND r.id=$3 AND a.status='active' AND a.expires_at>clock_timestamp() AND ${managedAgentAuthoritySql('a')} FOR SHARE OF a,r`,[r.company_id,r.proposed_agent_id,r.proposed_run_id])).rows[0];if(!a||HIGGSFIELD_REFERENCE_GENERATION_CAPABILITIES.some(cap=>!a.capabilities.includes(cap)||!a.run_capabilities.includes(cap)))changed();await admins(db,r.company_id,[a.created_by,r.proposed_by]);}
 if(r.approved_by)await admins(db,r.company_id,[r.approved_by]);return {project:p,work:w,storage:b,provider:c};
}
/** Optional provenance is only enriched under the ordinary application role.
 * Dedicated inspection/transfer brokers retain their existing narrow grants. */
async function presentationView(db:PoolClient,r:Row):Promise<HiggsfieldReference>{
 const reference=await view(db,r),preparation=await projectImagePreparationProvenance(db,r.company_id,r.project_id,r.proxy_version_id);
 return {...reference,...preparation&&preparation.sourceVersionId===r.source_version_id?{preparation}:{}};
}
/** Preparation handoff retries revalidate the current proposal as well as the
 * original derivative. A stored request response is not continuing authority. */
export async function currentHiggsfieldReferenceHandoff(db:PoolClient,actor:HiggsfieldReferenceActor,referenceId:string){
 await actorAuthority(db,actor);
 const r=await row(db,actor.companyId,referenceId,true);
 if(r.proposed_by!==actor.userId||(r.proposed_agent_id??null)!==(actor.agentId??null)||(r.proposed_run_id??null)!==(actor.runId??null)||r.revoked_at||['revoked','blocked','failed','uncertain'].includes(r.status))changed('HIGGSFIELD_REFERENCE_HANDOFF_CHANGED');
 const current=await facts(db,r);
 await work(db,actor,current.project,r.work_item_id);
 return presentationView(db,r);
}
export async function proposeHiggsfieldReference(db:PoolClient,actor:HiggsfieldReferenceActor,input:unknown){const data=parse(higgsfieldReferenceProposalInput,input),prepared=await referencePreparationDispatch(db,actor,data.projectId,data.workItemId);await actorAuthority(db,actor,false,prepared?HIGGSFIELD_REFERENCE_PREPARATION_CAPABILITIES:HIGGSFIELD_REFERENCE_GENERATION_CAPABILITIES);return once(db,actor,data.clientId,'propose',data,async()=>{
 const derivation=await projectImagePreparationProvenance(db,actor.companyId,data.projectId,data.proxyVersionId);
 if(derivation&&data.sourceVersionId!==derivation.sourceVersionId)fail(409,'This prepared image has a recorded original. Use its preparation entry to preserve the exact provenance.','HIGGSFIELD_REFERENCE_DERIVATION_CHANGED');
 const p=await project(db,actor.companyId,data.projectId);if(p.revision!==data.projectRevision)changed('HIGGSFIELD_REFERENCE_PROJECT_CHANGED');const w=await work(db,actor,p,data.workItemId),b=await storage(db,actor.companyId,p.id),c=await provider(db,actor.companyId),proxy=await version(db,actor.companyId,p.id,data.proxyVersionId,b.id),source=data.sourceVersionId?await version(db,actor.companyId,p.id,data.sourceVersionId,b.id):null;
 if(proxy.bytes!==data.proxyBytes||proxy.sha256!==data.proxySha256)changed('HIGGSFIELD_REFERENCE_SOURCE_CHANGED');if(proxy.bytes>HIGGSFIELD_REFERENCE_POLICY.maxBytes||!mediaTypes.includes(proxy.contentType))fail(409,'Select one verified prepared PNG, JPEG or WebP no larger than 10 MiB.','HIGGSFIELD_REFERENCE_IMAGE_REQUIRED');
 await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`higgsfield-reference-cap:${actor.companyId}:${p.id}`]);if(Number((await db.query('SELECT count(*) FROM higgsfield_references WHERE company_id=$1 AND project_id=$2',[actor.companyId,p.id])).rows[0].count)>=500)fail(409,'This project reached its 500-reference limit.');
 const authority=await createReferenceInspectionAuthority(db,actor,p.id,w.workItemId),authorityHash=authority?referenceInspectionAuthorityHash(authority):null;
 if(authority&&Number((await db.query('SELECT count(*) FROM higgsfield_references WHERE company_id=$1 AND project_id=$2 AND work_item_id=$3 AND inspection_authority IS NOT NULL',[actor.companyId,p.id,w.workItemId])).rows[0].count)>=HIGGSFIELD_REFERENCE_INSPECTION_LIMITS.maxProposalsPerWork)fail(409,'This task reached its eight prepared-reference proposal limit. Reconcile its existing references.','HIGGSFIELD_REFERENCE_PREPARATION_LIMIT');
 const semantic=projectSnapshot(p),projectHash=higgsfieldReferenceDigest(semantic),hash=higgsfieldReferenceDigest({proposal:data,project:semantic,work:w,proxy,source,storage:{binding:b.id,revision:b.revision,connection:b.connection_id,connectionRevision:b.connection_revision,sponsor:b.sponsor},provider:{id:c.id,revision:c.revision,sponsor:c.connected_by,catalogSha256:c.catalogSha256},policy:HIGGSFIELD_REFERENCE_POLICY,...authority?{inspectionAuthoritySha256:authorityHash}:{}});
 const saved=(await db.query("INSERT INTO higgsfield_references(company_id,project_id,work_item_id,project_revision,work_snapshot,proxy_version_id,source_version_id,proxy_snapshot,source_snapshot,storage_binding_id,storage_binding_revision,storage_connection_id,storage_connection_revision,storage_sponsor_id,provider_connection_id,provider_connection_revision,provider_sponsor_id,catalog_sha256,role,purpose,request_hash,proposed_by,proposed_agent_id,proposed_run_id,project_snapshot,project_sha256,inspection_authority,inspection_authority_sha256,inspect_expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,COALESCE($29::timestamptz,clock_timestamp()+interval '1 hour')) RETURNING *",[actor.companyId,p.id,w.workItemId,p.revision,JSON.stringify(w),proxy.versionId,source?.versionId??null,JSON.stringify(proxy),source?JSON.stringify(source):null,b.id,b.revision,b.connection_id,b.connection_revision,b.sponsor,c.id,c.revision,c.connected_by,c.catalogSha256,data.role,data.purpose,hash,actor.userId,actor.agentId??null,actor.runId??null,JSON.stringify(semantic),projectHash,authority?JSON.stringify(authority):null,authorityHash,authority?.expiresAt??null])).rows[0];return {reference:await presentationView(db,saved)};
 });}
async function readProject(db:PoolClient,actor:HiggsfieldReferenceActor,projectId:string){
 const p=(await db.query('SELECT * FROM studio_projects WHERE company_id=$1 AND id=$2',[actor.companyId,id(projectId)])).rows[0];if(!p)fail(404,'Project not found.');
 // A generation agent must be able to inspect its predecessor's references.
 // Human history remains readable after a project or its tasks have closed.
 if(actor.agentId){const w=(await db.query("SELECT w.id FROM studio_work_items w JOIN tasks t ON t.company_id=w.company_id AND t.id=w.task_id JOIN studio_role_bindings b ON b.company_id=w.company_id AND b.role_key=w.role_key WHERE w.company_id=$1 AND w.project_id=$2 AND b.agent_id=$3 AND t.agent_run_id=$4 AND t.status='doing' AND w.stage IN ('references','generation') ORDER BY w.id LIMIT 1",[actor.companyId,projectId,actor.agentId,actor.runId])).rows[0];if(!w)fail(403,'Reserve the assigned reference or generation task for this run first.','STUDIO_TASK_RESERVATION_REQUIRED');await work(db,actor,p,w.id);}
}
export async function getHiggsfieldReference(db:PoolClient,actor:HiggsfieldReferenceActor,referenceId:string){await actorAuthority(db,actor);const r=await row(db,actor.companyId,referenceId);await readProject(db,actor,r.project_id);return {reference:await presentationView(db,r)};}
export async function listHiggsfieldReferences(db:PoolClient,actor:HiggsfieldReferenceActor,input:unknown):Promise<HiggsfieldReferencePage>{const d=parse(higgsfieldReferenceListInput,input);await actorAuthority(db,actor);await readProject(db,actor,d.projectId);if(d.after&&(await row(db,actor.companyId,d.after)).project_id!==d.projectId)fail(404,'Reference cursor not found.');const rows=(await db.query('SELECT * FROM higgsfield_references WHERE company_id=$1 AND project_id=$2 AND ($3::uuid IS NULL OR id>$3) ORDER BY id LIMIT $4',[actor.companyId,d.projectId,d.after??null,d.limit+1])).rows;const references=await Promise.all(rows.slice(0,d.limit).map(r=>presentationView(db,r)));return {references,hasMore:rows.length>d.limit,nextAfter:rows.length>d.limit?references.at(-1)!.id:null};}
export async function listHiggsfieldReferenceCandidates(db:PoolClient,actor:HiggsfieldReferenceActor,input:unknown):Promise<HiggsfieldReferenceCandidatePage>{const d=parse(higgsfieldReferenceCandidatesInput,input);await actorAuthority(db,actor);await readProject(db,actor,d.projectId);
 if(d.after&&!(await db.query('SELECT 1 FROM project_storage_versions WHERE company_id=$1 AND project_id=$2 AND id=$3 AND ($4::uuid IS NULL OR file_id=$4)',[actor.companyId,d.projectId,d.after,d.fileId??null])).rowCount)fail(404,'File version cursor not found.');
 const rows=(await db.query('SELECT v.*,f.name,ok.sha256 AS verified_sha256 FROM project_storage_versions v JOIN project_storage_files f ON f.company_id=v.company_id AND f.project_id=v.project_id AND f.id=v.file_id JOIN project_storage_verifications ok ON ok.company_id=v.company_id AND ok.project_id=v.project_id AND ok.version_id=v.id AND ok.bytes=v.bytes AND (v.sha256 IS NULL OR v.sha256=ok.sha256) WHERE v.company_id=$1 AND v.project_id=$2 AND ($3::uuid IS NULL OR v.file_id=$3) AND ($4::uuid IS NULL OR v.id>$4) ORDER BY v.id LIMIT $5',[actor.companyId,d.projectId,d.fileId??null,d.after??null,d.limit+1])).rows;const versions=rows.slice(0,d.limit).map(v=>({versionId:v.id,fileId:v.file_id,name:v.name,version:v.version,bytes:Number(v.bytes),sha256:v.verified_sha256,contentType:v.content_type}));return {versions,hasMore:rows.length>d.limit,nextAfter:rows.length>d.limit?versions.at(-1)!.versionId:null};}
export async function approveHiggsfieldReference(db:PoolClient,actor:HiggsfieldReferenceActor,referenceId:string,input:unknown,options:HiggsfieldReferenceOptions={}){const d=parse(higgsfieldReferenceApproveInput,input);await actorAuthority(db,actor,true);return once(db,actor,d.clientId,'approve:'+id(referenceId),d,async()=>{
 const r=await row(db,actor.companyId,referenceId,true);if(r.status!=='awaiting_approval'||r.revoked_at||r.revision!==d.revision||r.request_hash!==d.requestHash)changed('HIGGSFIELD_REFERENCE_REVIEW_CHANGED');await facts(db,r);const i=await inspection(db,r);if(!i||i.inspectionHash!==d.inspectionHash)changed('HIGGSFIELD_REFERENCE_INSPECTION_CHANGED');const availability=await ready(db,r,options),approvalHash=higgsfieldReferenceDigest({requestHash:r.request_hash,inspectionHash:i!.inspectionHash,approvedBy:actor.userId,consent:d,qualificationSha256:availability.qualificationSha256});
 const saved=(await db.query("WITH tick AS MATERIALIZED (SELECT clock_timestamp() AS at) UPDATE higgsfield_references SET status='queued',revision=revision+1,approved_by=$3,approved_at=tick.at,expires_at=LEAST(tick.at+make_interval(mins=>$4),$5::timestamptz),approval_hash=$6,qualification_sha256=$7,updated_at=tick.at FROM tick WHERE company_id=$1 AND id=$2 AND $5::timestamptz>tick.at RETURNING higgsfield_references.*",[actor.companyId,r.id,actor.userId,d.expiresInMinutes,availability.expiresAt,approvalHash,availability.qualificationSha256])).rows[0];if(!saved)changed('HIGGSFIELD_REFERENCE_UNAVAILABLE');await receipt(db,saved,d.clientId,'approve','returned',{requestHash:r.request_hash,inspectionHash:i!.inspectionHash,approvalHash,approvedBy:actor.userId,expiresAt:iso(saved.expires_at),allBytesSharedUnchanged:true,metadataRemoved:false});return {reference:await presentationView(db,saved)};
 });}
export async function revokeHiggsfieldReference(db:PoolClient,actor:HiggsfieldReferenceActor,referenceId:string,input:unknown){const d=parse(higgsfieldReferenceRevokeInput,input);await actorAuthority(db,actor,true);return once(db,actor,d.clientId,'revoke:'+id(referenceId),d,async()=>{const r=await row(db,actor.companyId,referenceId,true);if(r.revision!==d.revision||r.revoked_at)changed('HIGGSFIELD_REFERENCE_REVIEW_CHANGED');const saved=(await db.query("UPDATE higgsfield_references SET status='revoked',revision=revision+1,revoked_by=$3,revoked_at=clock_timestamp(),lease_id=NULL,lease_expires_at=NULL,diagnostic_code='HIGGSFIELD_REFERENCE_REVOKED',updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2 RETURNING *",[actor.companyId,r.id,actor.userId])).rows[0];await receipt(db,r,d.clientId,'revoke','revoked',{revokedBy:actor.userId,note:d.note,providerBytesDeleted:false,disclosureUndone:false});return {reference:await presentationView(db,saved),providerBytesDeleted:false,disclosureUndone:false};});}

/** Trusted runtime/worker methods below. No HTTP endpoint accepts these inputs. */
export async function authorizeHiggsfieldReference(db:PoolClient,lease:HiggsfieldReferenceLease,options:HiggsfieldReferenceOptions={}){
 const r=await row(db,lease.companyId,lease.referenceId,true);if(r.project_id!==lease.projectId||r.request_hash!==lease.requestHash||r.lease_id!==id(lease.leaseId)||r.revoked_at||!(lease.phase==='inspect'?r.status==='inspecting':transferStates.includes(r.status)))changed('HIGGSFIELD_REFERENCE_LEASE_ENDED');
 if(lease.role!==r.role||higgsfieldReferenceDigest(lease.proxy)!==higgsfieldReferenceDigest(versionView(r.proxy_snapshot))||higgsfieldReferenceDigest(lease.inspection)!==higgsfieldReferenceDigest(await inspection(db,r)))changed('HIGGSFIELD_REFERENCE_LEASE_ENDED');
 const deadline=async()=>{const valid=(await db.query('SELECT lease_expires_at>clock_timestamp() AND CASE WHEN approved_by IS NULL THEN inspect_expires_at ELSE expires_at END>clock_timestamp() AS valid FROM higgsfield_references WHERE company_id=$1 AND id=$2',[r.company_id,r.id])).rows[0]?.valid;if(valid!==true)changed('HIGGSFIELD_REFERENCE_LEASE_ENDED');if(lease.phase==='inspect'&&r.inspection_authority)await assertReferenceInspectionAuthority(db,r);};await deadline();await facts(db,r);await ready(db,r,options);if(lease.phase==='inspect'){if(!r.inspection_authority)await actorAuthority(db,{companyId:r.company_id,userId:r.proposed_by,...r.proposed_agent_id?{agentId:r.proposed_agent_id,runId:r.proposed_run_id}:{}},false,HIGGSFIELD_REFERENCE_GENERATION_CAPABILITIES);}else if(!r.approved_by||!r.approval_hash)changed();await deadline();return r;
}
async function leaseView(db:PoolClient,r:Row,phase:'inspect'|'transfer'):Promise<HiggsfieldReferenceLease>{return {companyId:r.company_id,projectId:r.project_id,referenceId:r.id,leaseId:r.lease_id,requestHash:r.request_hash,phase,expiresAt:iso(r.lease_expires_at)!,proxy:versionView(r.proxy_snapshot),role:r.role,inspection:await inspection(db,r)};}
export async function claimHiggsfieldReference(db:PoolClient,scope:{companyId:string;projectIds:readonly string[]},options:HiggsfieldReferenceOptions={}):Promise<HiggsfieldReferenceLease|null>{
 id(scope.companyId);if(!scope.projectIds.length||scope.projectIds.length>100)fail(400,'An exact worker project scope is required.');scope.projectIds.forEach(id);
 const candidate=(await db.query("SELECT * FROM higgsfield_references WHERE company_id=$1 AND project_id=ANY($2::uuid[]) AND status IN ('proposed','inspecting','queued','reading','allocating','allocated','uploading','uploaded','confirming') AND (lease_id IS NULL OR lease_expires_at<=clock_timestamp()) ORDER BY created_at,id LIMIT 1",[scope.companyId,scope.projectIds])).rows[0];if(!candidate)return null;
 await lockReferenceInspectionAuthority(db,candidate);
 if(!(await db.query('SELECT id FROM studio_projects WHERE company_id=$1 AND id=$2 FOR UPDATE SKIP LOCKED',[scope.companyId,candidate.project_id])).rowCount)return null;
 const r=(await db.query("SELECT * FROM higgsfield_references WHERE company_id=$1 AND project_id=$2 AND id=$3 AND status IN ('proposed','inspecting','queued','reading','allocating','allocated','uploading','uploaded','confirming') AND (lease_id IS NULL OR lease_expires_at<=clock_timestamp()) FOR UPDATE SKIP LOCKED",[scope.companyId,candidate.project_id,candidate.id])).rows[0];if(!r)return null;
 const prior=(await db.query("SELECT 1 FROM higgsfield_reference_receipts WHERE company_id=$1 AND reference_id=$2 AND operation IN ('allocate','put','confirm') AND phase='intent' LIMIT 1",[r.company_id,r.id])).rowCount;
 if(prior){await db.query("UPDATE higgsfield_references SET status='uncertain',diagnostic_code='HIGGSFIELD_REFERENCE_OUTCOME_UNKNOWN',lease_id=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2",[r.company_id,r.id]);await receipt(db,r,randomUUID(),'claim','uncertain',{code:'HIGGSFIELD_REFERENCE_OUTCOME_UNKNOWN'});return null;}
 const phase=r.approved_by?'transfer':'inspect';
 const block=async()=>{await db.query("UPDATE higgsfield_references SET status='blocked',diagnostic_code='HIGGSFIELD_REFERENCE_AUTHORITY_ENDED',lease_id=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2",[r.company_id,r.id]);await receipt(db,r,randomUUID(),'claim','blocked',{code:'HIGGSFIELD_REFERENCE_AUTHORITY_ENDED'});return null;};
 // Reconcile an expired/stale head before claiming more work. No provider
 // intent exists here; transient host/catalog readiness still leaves it queued.
 if(!(await db.query('SELECT CASE WHEN approved_by IS NULL THEN inspect_expires_at ELSE expires_at END>clock_timestamp() AS valid FROM higgsfield_references WHERE company_id=$1 AND id=$2',[r.company_id,r.id])).rows[0]?.valid)return block();
 if(phase==='inspect'&&r.inspection_authority&&r.inspection_attempts>=HIGGSFIELD_REFERENCE_INSPECTION_LIMITS.maxAttempts)return block();
 try{await facts(db,r);if(phase==='inspect'&&!r.inspection_authority)await actorAuthority(db,{companyId:r.company_id,userId:r.proposed_by,...r.proposed_agent_id?{agentId:r.proposed_agent_id,runId:r.proposed_run_id}:{}},false,HIGGSFIELD_REFERENCE_GENERATION_CAPABILITIES);}catch(error){if(error instanceof ApiError&&[403,404,409].includes(error.status))return block();throw error;}
 const runtime=await ready(db,r,options);
 if(phase==='inspect'&&r.inspection_authority)await assertReferenceInspectionAuthority(db,r);
 const saved=(await db.query("UPDATE higgsfield_references SET status=$3,lease_id=$4,inspection_attempts=inspection_attempts+CASE WHEN $3='inspecting' AND inspection_authority IS NOT NULL THEN 1 ELSE 0 END,lease_expires_at=LEAST(CASE WHEN approved_by IS NULL THEN inspect_expires_at ELSE expires_at END,$5::timestamptz,clock_timestamp()+interval '120 seconds'),updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2 AND CASE WHEN approved_by IS NULL THEN inspect_expires_at ELSE expires_at END>clock_timestamp() RETURNING *",[r.company_id,r.id,phase==='inspect'?'inspecting':'reading',randomUUID(),runtime.expiresAt])).rows[0];if(!saved)return block();return leaseView(db,saved,phase);
}
export async function renewHiggsfieldReferenceLease(db:PoolClient,lease:HiggsfieldReferenceLease,options:HiggsfieldReferenceOptions={}){const r=await authorizeHiggsfieldReference(db,lease,options),runtime=await ready(db,r,options);const saved=(await db.query("UPDATE higgsfield_references SET lease_expires_at=LEAST(CASE WHEN approved_by IS NULL THEN inspect_expires_at ELSE expires_at END,$3::timestamptz,clock_timestamp()+interval '120 seconds') WHERE company_id=$1 AND id=$2 RETURNING *",[r.company_id,r.id,runtime.expiresAt])).rows[0];return leaseView(db,saved,lease.phase);}
const descriptorSchema=z.object({kind:z.literal('image'),format:z.enum(['png','jpeg','webp']),contentType:z.enum(['image/png','image/jpeg','image/webp']),bytes:z.number().int().positive().max(HIGGSFIELD_REFERENCE_POLICY.maxBytes),sha256:sha,verification:z.literal('full_decode'),inspectionVersion:z.literal(1),width:z.number().int().positive().max(4096),height:z.number().int().positive().max(4096),codec:z.enum(['png','mjpeg','webp']),color:z.object({space:z.string().max(64).nullable(),primaries:z.string().max(64).nullable(),transfer:z.string().max(64).nullable(),range:z.string().max(64).nullable()}).strict()}).strict();
export async function recordHiggsfieldReferenceInspection(db:PoolClient,lease:HiggsfieldReferenceLease,input:{descriptor:unknown;profileSha256:string},options:HiggsfieldReferenceOptions={}){const r=await authorizeHiggsfieldReference(db,lease,options);if(lease.phase!=='inspect'||r.status!=='inspecting')changed();const descriptor=parse(descriptorSchema,input.descriptor),profileSha256=parse(sha,input.profileSha256),expected={png:['image/png','png'],jpeg:['image/jpeg','mjpeg'],webp:['image/webp','webp']}[descriptor.format];if(descriptor.width*descriptor.height>HIGGSFIELD_REFERENCE_POLICY.maxPixels||descriptor.bytes!==r.proxy_snapshot.bytes||descriptor.sha256!==r.proxy_snapshot.sha256||descriptor.contentType!==r.proxy_snapshot.contentType||descriptor.contentType!==expected[0]||descriptor.codec!==expected[1])changed('HIGGSFIELD_REFERENCE_INSPECTION_CHANGED');const inspectionHash=higgsfieldReferenceDigest({requestHash:r.request_hash,descriptor,profileSha256,policy:HIGGSFIELD_REFERENCE_POLICY});await db.query('INSERT INTO higgsfield_reference_inspections(company_id,project_id,reference_id,request_hash,profile_sha256,inspection_hash,descriptor) VALUES($1,$2,$3,$4,$5,$6,$7)',[r.company_id,r.project_id,r.id,r.request_hash,profileSha256,inspectionHash,JSON.stringify(descriptor)]);const saved=(await db.query("UPDATE higgsfield_references SET status='awaiting_approval',revision=revision+1,lease_id=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2 RETURNING *",[r.company_id,r.id])).rows[0];await receipt(db,r,randomUUID(),'inspect','returned',{inspectionHash,profileSha256,bytes:descriptor.bytes,sha256:descriptor.sha256});return {reference:await view(db,saved)};}
export async function beginHiggsfieldReferencePhase(db:PoolClient,lease:HiggsfieldReferenceLease,phase:HiggsfieldReferencePhase,options:HiggsfieldReferenceOptions={}){const r=await authorizeHiggsfieldReference(db,lease,options),expected={allocate:'reading',put:'allocated',confirm:'uploaded'}[phase];if(lease.phase!=='transfer'||!expected||r.status!==expected||r.action_id)changed('HIGGSFIELD_REFERENCE_PHASE_CONFLICT');const actionId=randomUUID();await receipt(db,r,actionId,phase,'intent',{requestHash:r.request_hash,approvalHash:r.approval_hash});await db.query('UPDATE higgsfield_references SET status=$3,action_id=$4,action_operation=$5,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2',[r.company_id,r.id,{allocate:'allocating',put:'uploading',confirm:'confirming'}[phase],actionId,phase]);return {actionId,phase};}
export async function completeHiggsfieldReferencePhase(db:PoolClient,lease:HiggsfieldReferenceLease,actionId:string,result:HiggsfieldReferencePhaseResult,options:HiggsfieldReferenceOptions={}){
 const r=await authorizeHiggsfieldReference(db,lease,options);if(r.action_id!==id(actionId)||r.action_operation!==result.phase||r.status!=={allocate:'allocating',put:'uploading',confirm:'confirming'}[result.phase])changed('HIGGSFIELD_REFERENCE_PHASE_CONFLICT');
 if(result.phase==='allocate'){const a=parse(z.object({mediaId:z.string().uuid(),uploadUrl:z.string().url().max(8192),expiresAt:z.iso.datetime()}).strict(),result.allocation),url=new URL(a.uploadUrl);if(url.protocol!=='https:'||url.username||url.password||url.hash||!(await db.query('SELECT $1::timestamptz>clock_timestamp() AS valid',[a.expiresAt])).rows[0]?.valid)changed('HIGGSFIELD_REFERENCE_TRANSPORT_REJECTED');const sealed=sealHiggsfieldSecret(a,{companyId:r.company_id,id:r.id,purpose:'reference-transport'});await db.query('INSERT INTO higgsfield_reference_transports(company_id,project_id,reference_id,media_id,sealed,expires_at) VALUES($1,$2,$3,$4,$5,$6)',[r.company_id,r.project_id,r.id,a.mediaId,JSON.stringify(sealed),a.expiresAt]);}
 else if(result.phase==='put'){if(result.httpStatus!==200||result.bytes!==r.proxy_snapshot.bytes||result.sha256!==r.proxy_snapshot.sha256)changed('HIGGSFIELD_REFERENCE_BYTES_CHANGED');}
 else {const transport=(await db.query('SELECT media_id FROM higgsfield_reference_transports WHERE company_id=$1 AND reference_id=$2',[r.company_id,r.id])).rows[0];if(result.confirmed!==true||!transport||result.mediaId!==transport.media_id)changed('HIGGSFIELD_REFERENCE_CONFIRMATION_CHANGED');await db.query('INSERT INTO higgsfield_reference_confirmations(company_id,project_id,reference_id,media_id,request_hash,approval_hash,bytes,sha256) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[r.company_id,r.project_id,r.id,result.mediaId,r.request_hash,r.approval_hash,r.proxy_snapshot.bytes,r.proxy_snapshot.sha256]);}
 const status={allocate:'allocated',put:'uploaded',confirm:'confirmed'}[result.phase];await receipt(db,r,actionId,result.phase,'returned',{status,bytes:r.proxy_snapshot.bytes,sha256:r.proxy_snapshot.sha256});const saved=(await db.query("UPDATE higgsfield_references SET status=$3,action_id=NULL,action_operation=NULL,lease_id=CASE WHEN $3='confirmed' THEN NULL ELSE lease_id END,lease_expires_at=CASE WHEN $3='confirmed' THEN NULL ELSE lease_expires_at END,revision=revision+1,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2 RETURNING *",[r.company_id,r.id,status])).rows[0];return {reference:await view(db,saved)};
}
export async function getHiggsfieldReferenceTransport(db:PoolClient,lease:HiggsfieldReferenceLease,options:HiggsfieldReferenceOptions={}){const r=await authorizeHiggsfieldReference(db,lease,options);if(lease.phase!=='transfer'||!['allocated','uploading','uploaded','confirming'].includes(r.status))changed();const t=(await db.query('SELECT * FROM higgsfield_reference_transports WHERE company_id=$1 AND reference_id=$2 AND expires_at>clock_timestamp()',[r.company_id,r.id])).rows[0];if(!t)changed('HIGGSFIELD_REFERENCE_TRANSPORT_EXPIRED');const a=openHiggsfieldSecret<{mediaId:string;uploadUrl:string;expiresAt:string}>(t.sealed,{companyId:r.company_id,id:r.id,purpose:'reference-transport'});if(a.mediaId!==t.media_id||iso(a.expiresAt)!==iso(t.expires_at))changed();return a;}
export async function getHiggsfieldReferenceProviderContext(db:PoolClient,lease:HiggsfieldReferenceLease,options:HiggsfieldReferenceOptions={}){
 const r=await authorizeHiggsfieldReference(db,lease,options);if(lease.phase!=='transfer'||!r.approved_by)changed();
 const c=await provider(db,r.company_id);return {companyId:r.company_id as string,referenceId:r.id as string,connectionId:c.id as string,connectionRevision:c.revision as number,catalogSha256:r.catalog_sha256 as string,tools:c.tools as HiggsfieldTool[],approvedBy:r.approved_by as string};
}
/** Private adapter binding, never exposed by session/agent metadata endpoints. */
export async function getHiggsfieldReferenceStorageContext(db:PoolClient,lease:HiggsfieldReferenceLease,options:HiggsfieldReferenceOptions={}){
 const r=await authorizeHiggsfieldReference(db,lease,options);return {companyId:r.company_id as string,projectId:r.project_id as string,connectionId:r.storage_connection_id as string,connectionRevision:r.storage_connection_revision as number,bindingId:r.storage_binding_id as string,bindingRevision:r.storage_binding_revision as number,versionId:r.proxy_version_id as string,objectKey:r.proxy_snapshot.objectKey as string,providerEtag:r.proxy_snapshot.providerEtag as string,bytes:r.proxy_snapshot.bytes as number,sha256:r.proxy_snapshot.sha256 as string};
}
const resolveInput=z.object({projectId:z.string().uuid(),workItemId:z.string().uuid(),referenceIds:z.array(z.string().uuid()).min(1).max(8).refine(v=>new Set(v).size===v.length)}).strict();
export async function resolveHiggsfieldReferences(db:PoolClient,actor:HiggsfieldReferenceActor,input:unknown,_options:HiggsfieldReferenceOptions={}):Promise<HiggsfieldReferenceResolution>{
 const data=parse(resolveInput,input);await actorAuthority(db,actor,false,HIGGSFIELD_REFERENCE_GENERATION_CAPABILITIES);const p=await project(db,actor.companyId,data.projectId),generation=await work(db,actor,p,data.workItemId);if(generation.stage!=='generation')changed('HIGGSFIELD_REFERENCE_GENERATION_REQUIRED');
 const references:HiggsfieldReferenceSnapshot['references']=[];
 for(const referenceId of data.referenceIds){
  const r=await row(db,actor.companyId,referenceId,true);if(r.project_id!==data.projectId||r.status!=='confirmed'||r.revoked_at||!r.approved_by||!r.approval_hash)changed('HIGGSFIELD_REFERENCE_NOT_CONFIRMED');
  if(!(await db.query('SELECT expires_at>clock_timestamp() AS valid FROM higgsfield_references WHERE company_id=$1 AND id=$2',[actor.companyId,r.id])).rows[0]?.valid)changed('HIGGSFIELD_REFERENCE_AUTHORITY_ENDED');
  const predecessor=r.work_item_id!==generation.workItemId&&r.work_snapshot.stage==='references'&&!!generation.shotId&&r.work_snapshot.shotId===generation.shotId&&!!(await db.query('SELECT 1 FROM studio_dependencies WHERE company_id=$1 AND project_id=$2 AND work_item_id=$3 AND predecessor_id=$4',[actor.companyId,data.projectId,generation.workItemId,r.work_item_id])).rowCount;
  // Only accepted same-shot direct reference prerequisites may survive a
  // bookkeeping revision bump; every project semantic field remains pinned.
  const current=await facts(db,r,predecessor);
  if(r.work_item_id!==generation.workItemId){
   if(!predecessor||current.work.stage!=='references'||current.work.status!=='done'||current.work.shotId!==generation.shotId)changed('HIGGSFIELD_REFERENCE_WORK_CHANGED');
  }
  const i=await inspection(db,r),c=(await db.query('SELECT * FROM higgsfield_reference_confirmations WHERE company_id=$1 AND reference_id=$2 AND request_hash=$3 AND approval_hash=$4',[actor.companyId,r.id,r.request_hash,r.approval_hash])).rows[0];
  if(!i||!c||Number(c.bytes)!==r.proxy_snapshot.bytes||c.sha256!==r.proxy_snapshot.sha256)changed('HIGGSFIELD_REFERENCE_NOT_CONFIRMED');
  references.push({referenceId:r.id,requestHash:r.request_hash,approvalHash:r.approval_hash,inspectionHash:i!.inspectionHash,role:r.role,mediaId:c.media_id,proxyVersionId:r.proxy_version_id,sha256:c.sha256,bytes:Number(c.bytes),providerConnectionId:r.provider_connection_id,providerConnectionRevision:r.provider_connection_revision});
 }
 if(Number((await db.query("SELECT count(*) AS n FROM higgsfield_references WHERE company_id=$1 AND id=ANY($2::uuid[]) AND status='confirmed' AND revoked_at IS NULL AND expires_at>clock_timestamp()",[actor.companyId,data.referenceIds])).rows[0].n)!==data.referenceIds.length)changed('HIGGSFIELD_REFERENCE_AUTHORITY_ENDED');
 // Consumption needs current approval and provenance, not a still-running upload worker.
 const snapshot:HiggsfieldReferenceSnapshot={version:1,companyId:actor.companyId,projectId:data.projectId,workItemId:data.workItemId,references};
 return {referenceIds:[...data.referenceIds],medias:references.map(r=>({role:r.role,value:r.mediaId})),snapshot,snapshotHash:higgsfieldReferenceDigest(snapshot)};
}
export async function revalidateHiggsfieldReferences(db:PoolClient,actor:HiggsfieldReferenceActor,snapshot:HiggsfieldReferenceSnapshot,options:HiggsfieldReferenceOptions={}):Promise<HiggsfieldReferenceResolution>{
 if(!snapshot||snapshot.version!==1||snapshot.companyId!==actor.companyId||!Array.isArray(snapshot.references))changed();
 const result=await resolveHiggsfieldReferences(db,actor,{projectId:snapshot.projectId,workItemId:snapshot.workItemId,referenceIds:snapshot.references.map(r=>r.referenceId)},options);if(higgsfieldReferenceDigest(snapshot)!==result.snapshotHash)changed('HIGGSFIELD_REFERENCE_BINDING_CHANGED');return result;
}
export async function failHiggsfieldReference(db:PoolClient,lease:HiggsfieldReferenceLease,code:'HIGGSFIELD_REFERENCE_WORKER_FAILED'|'HIGGSFIELD_REFERENCE_AUTHORITY_CHANGED'|'HIGGSFIELD_REFERENCE_MEDIA_REJECTED'|'HIGGSFIELD_REFERENCE_OUTCOME_UNKNOWN'){
 const allowed=['HIGGSFIELD_REFERENCE_WORKER_FAILED','HIGGSFIELD_REFERENCE_AUTHORITY_CHANGED','HIGGSFIELD_REFERENCE_MEDIA_REJECTED','HIGGSFIELD_REFERENCE_OUTCOME_UNKNOWN'];if(!allowed.includes(code))code='HIGGSFIELD_REFERENCE_WORKER_FAILED';const r=await row(db,lease.companyId,lease.referenceId,true);if(r.lease_id!==lease.leaseId||r.request_hash!==lease.requestHash)return {recorded:false};const uncertain=!!r.action_id||!!(await db.query("SELECT 1 FROM higgsfield_reference_receipts WHERE company_id=$1 AND reference_id=$2 AND phase='intent' AND operation IN ('allocate','put','confirm') LIMIT 1",[r.company_id,r.id])).rowCount,status=uncertain?'uncertain':'failed';await db.query('UPDATE higgsfield_references SET status=$3,diagnostic_code=$4,lease_id=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2',[r.company_id,r.id,status,uncertain?'HIGGSFIELD_REFERENCE_OUTCOME_UNKNOWN':code]);await receipt(db,r,randomUUID(),'claim',status,{code:uncertain?'HIGGSFIELD_REFERENCE_OUTCOME_UNKNOWN':code});return {recorded:true,status};
}
