import {z} from 'zod';
import {higgsfieldReferenceProposalInput,higgsfieldReferenceApproveInput,higgsfieldReferenceRevokeInput,referenceGenerationInspectionAdoptInput} from './higgsfield-references-protocol';
const parameter=(name:string,location='path',required=true)=>({name,in:location,required,schema:{type:'string',format:'uuid'}});
const company=[parameter('companyId')],reference=[...company,parameter('referenceId')];
const errors=Object.fromEntries([400,401,403,404,409,413,429,503].map(code=>[code,{description:'Invalid, unavailable, stale or unauthorized reference operation. Never repeat an uncertain provider upload.'}]));
function operation(summary:string,parameters:unknown[],input?:z.ZodType){return {summary,tags:['Higgsfield references'],security:[{sessionCookie:[]}],parameters:input?[...parameters,{name:'Origin',in:'header',required:true,schema:{type:'string',format:'uri'}}]:parameters,...input?{'x-coatria-roles':input===higgsfieldReferenceProposalInput?['owner','admin','member']:['owner','admin'],requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(input,{io:'input',unrepresentable:'any'})}}}}:{},responses:{'200':{description:'Company/project metadata with processing availability; no provider URL, OAuth, worker lease or file bytes.'},...input===higgsfieldReferenceProposalInput?{'201':{description:'Prepared exact reference proposal; not shared or approved.'}}:{},...errors}};}
export const higgsfieldReferencePaths={
 '/api/companies/{companyId}/higgsfield/references':{
  get:operation('Page reference proposals and transfer status for one project. Follow nextAfter. Processing is unavailable until the exact runtime, company catalog and storage path are qualified.',[...company,parameter('projectId','query'),parameter('after','query',false),{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:20}}]),
  post:operation('Propose one verified prepared PNG/JPEG/WebP version up to 10 MiB for inspection. Pins exact bytes, hash, task, role, project and connection revisions. Optional original is provenance only. This flow copies all bytes unchanged; it does not resize or strip metadata. Separate human approval is required for sharing.',company,higgsfieldReferenceProposalInput)},
 '/api/companies/{companyId}/higgsfield/references/candidates':{get:operation('Page exact verified project file versions, including older versions. Returns no download URL or storage capability. Verification is not image inspection or permission to share.',[...company,parameter('projectId','query'),parameter('fileId','query',false),parameter('after','query',false),{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:20}}])},
 '/api/companies/{companyId}/higgsfield/references/{referenceId}':{get:operation('Read exact reference, inspection, approval expiry and durable transfer outcome. Provider confirmed is not generated content, QC or client acceptance.',reference)},
 '/api/companies/{companyId}/higgsfield/references/{referenceId}/approve':{post:operation('Human administrator grants finite exact-byte sharing after inspection, with explicit rights, prepared-image, metadata and provider-sharing consent. Maximum 60 minutes, further bounded by runtime qualification. Agents cannot approve.',reference,higgsfieldReferenceApproveInput)},
 '/api/companies/{companyId}/higgsfield/references/{referenceId}/adopt-generation-inspection':{post:operation('Human administrator adopts one inspection attempt for the exact derived reference of a successfully completed generation specialist. Pins the reference revision, request and immutable handoff; expires within 60 minutes and never extends the original inspection deadline. Replay cannot renew consent. This grants no sharing, generation spend, new run or agent credential.',reference,referenceGenerationInspectionAdoptInput)},
 '/api/companies/{companyId}/higgsfield/references/{referenceId}/revoke':{post:operation('Human administrator revokes future transfer and managed generation use. This does not retract bytes already disclosed or delete media at the provider.',reference,higgsfieldReferenceRevokeInput)},
};
for(const[path,methods]of Object.entries(higgsfieldReferencePaths))for(const[method,definition]of Object.entries(methods))Object.assign(definition,{operationId:'higgsfield_reference_'+method+'_'+path.replace(/[^a-zA-Z0-9]+/g,'_')});
