import {z} from 'zod';
import {higgsfieldProposalInput,higgsfieldExecuteInput,higgsfieldEstimateInput,higgsfieldReadInput} from './higgsfield-protocol';
import {studioGenerationImportInput,studioStorageReferenceInput} from './studio-creative-assets-protocol';
const schema=(value:z.ZodType)=>z.toJSONSchema(value,{io:'input',unrepresentable:'any'});
const parameter=(name:string,where='path',required=true)=>({name,in:where,required,schema:{type:'string',format:'uuid'}});
const company=[parameter('companyId')],project=[...company,parameter('projectId')];
const errors=Object.fromEntries([400,401,403,404,409,413,429,502,503].map(code=>[String(code),{description:'Validation, company authority, revision, connection or bounded-provider error. Never retry a possibly sent generation automatically.'}]));
const output=z.object({id:z.string().uuid(),ordinal:z.number().int().min(0).max(7),kind:z.enum(['image','video','audio']),locatorIdentity:z.string().regex(/^[a-f0-9]{64}$/).describe('Derived URL identity; not a media ID, content hash or immutable object version.'),bytesVerified:z.literal(false)}).strict();
const job=z.object({id:z.string().uuid(),projectId:z.string().uuid(),requestId:z.string().uuid(),providerJobId:z.string().uuid(),kind:z.enum(['image','video','audio']),model:z.string().nullable(),status:z.enum(['queued','running','completed','failed','cancelled','unresolved','blocked','conflict']),diagnosticCode:z.string().nullable(),pollAttempts:z.number().int().min(0).max(1440),nextPollAt:z.iso.datetime().nullable(),createdAt:z.iso.datetime(),updatedAt:z.iso.datetime(),outputs:z.array(output).max(8)}).strict();
const jobsPage=z.object({jobs:z.array(job).max(50),hasMore:z.boolean(),nextAfter:z.string().uuid().nullable()}).strict();
function operation(summary:string,parameters:unknown[],input?:z.ZodType,extra:Record<string,unknown>={}){return {summary,tags:['Higgsfield production'],security:[{sessionCookie:[]}],parameters,...input?{requestBody:{required:true,content:{'application/json':{schema:schema(input)}}}}:{},responses:{'200':{description:'Company-scoped response. Imported generation reports and storage metadata do not verify actual media or delivery.'},...input?{'201':{description:'Created immutable request or reference.'}}:{},...errors},...extra};}
export const higgsfieldPaths={
 '/api/companies/{companyId}/higgsfield':{get:operation('Official MCP connection status and discovered supported tools; no credentials.',company)},
 '/api/companies/{companyId}/higgsfield/connect':{post:operation('Begin a ten-minute session-bound, single-use PKCE authorization with the official Higgsfield service. Administrator only; no generations.',company,z.object({}).strict())},
 '/api/companies/{companyId}/higgsfield/catalog':{post:operation('Refresh the official supported tool catalog without generating. Administrator only. A changed catalog advances connection revision and requires new review of unsent proposals.',company,z.object({}).strict())},
 '/api/companies/{companyId}/higgsfield/disconnect':{post:operation('Disconnect local company access and erase encrypted OAuth credentials. Existing provider jobs are not cancelled.',company,z.object({revision:z.number().int().positive()}).strict())},
 '/api/companies/{companyId}/higgsfield/read':{post:operation('Invoke an explicitly allowed discovered read tool using company credentials. Administrator only.',company,higgsfieldReadInput)},
 '/api/companies/{companyId}/higgsfield/jobs':{get:operation('Page durable provider job observations for exact human-approved requests. Follow nextAfter. Job completed means provider-reported completion only; output identities are not media/content hashes, URLs, verified file bytes or QC acceptance. Unsupported contract or revoked authority stops polling.',[...company,parameter('projectId','query'),parameter('requestId','query',false),parameter('after','query',false),{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:20}}],undefined,{responses:{'200':{description:'Bounded job metadata without private locators.',content:{'application/json':{schema:schema(jobsPage)}}},...errors}})},
 '/api/companies/{companyId}/higgsfield/requests':{
  get:operation('Page bounded request summaries or requestId for one exact sanitized receipt summary. Follow nextAfter; default 20, maximum 50.',[...company,parameter('projectId','query'),parameter('requestId','query',false),parameter('after','query',false),{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:20}}]),
  post:operation('Prepare a generation request. Does not spend credits. Pins project revision, connection identity and revision, exact tool and arguments. Higgsfield projects require an exact generation workItemId; the server additionally pins task revision and role assignment.',company,higgsfieldProposalInput)},
 '/api/companies/{companyId}/higgsfield/requests/{requestId}/execute':{post:operation('Administrator approves the exact argument hash and provider credit charge. Requires current project gates, unchanged task revision and role assignment. Dispatch intent is committed before tools/call; returned is a sanitized provider receipt with a response hash, not verified media. Recognized jobs are tracked with bounded read-only polling; uncertain is never replayed.',[...company,parameter('requestId')],higgsfieldExecuteInput)},
 '/api/companies/{companyId}/higgsfield/requests/{requestId}/estimate':{post:operation('Read-only cost preflight for the exact unsent request. Requires advertised get_cost:boolean support; server forces params.get_cost=true and rejects serialized params. Does not approve spending or guarantee a future price.',[...company,parameter('requestId')],higgsfieldEstimateInput)},
 '/api/higgsfield/callback':{get:operation('Official OAuth GET callback, bound to initiating administrator session and exact state. Codes are exchanged once; redirects to Plugins.',[{name:'state',in:'query',required:true,schema:{type:'string'}},{name:'code',in:'query',schema:{type:'string'}},{name:'iss',in:'query',schema:{type:'string'}},{name:'error',in:'query',schema:{type:'string'}}],undefined,{responses:{'303':{description:'Return to Plugins without exposing tokens.'},...errors}})},
 '/api/companies/{companyId}/studio/projects/{projectId}/creative-assets/generations':{
  get:operation('Page immutable imported generation identities and latest reported observations. Provider existence/media bytes are not verified.',[...project,parameter('after','query',false),{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:100,default:25}}]),
  post:operation('Import a job observation from the official Higgsfield plugin. Append-only provenance, no provider execution, media approval or delivery.',project,studioGenerationImportInput)},
 '/api/companies/{companyId}/studio/projects/{projectId}/creative-assets/generations/{generationId}':{get:operation('Exact imported generation with paged immutable observations.',[...project,parameter('generationId')])},
 '/api/companies/{companyId}/studio/projects/{projectId}/creative-assets/storage-references':{
  get:operation('Page immutable storage index snapshots and current unchanged/changed/missing/revoked status. No file bytes or mount access.',[...project,parameter('after','query',false)]),
  post:operation('Pin a same-company drive index path, expected size and mtime to the project. Does not upload or access the original.',project,studioStorageReferenceInput)},
 '/api/companies/{companyId}/studio/projects/{projectId}/creative-assets/storage-references/{referenceId}':{get:operation('Exact storage reference and current index status.',[...project,parameter('referenceId')])},
};
for(const [path,methods]of Object.entries(higgsfieldPaths))for(const [method,operation]of Object.entries(methods))Object.assign(operation,{operationId:'higgsfield_'+method+'_'+path.replace(/[^a-zA-Z0-9]+/g,'_')});
