import {createCipheriv,createDecipheriv,randomBytes,randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import type {z} from 'zod';
import {requireMembership} from './auth';
import {memberMutation} from './company';
import {managedAgentAuthoritySql,managedAgentAuthorityPrincipals} from './studio-hosting';
import {projectStoragePlanListInput} from './project-storage-protocol';
import {assertOrigin,body,fail,hashToken,id,json} from './security';
import {PROJECT_STORAGE_MAX_FOLDERS,PROJECT_STORAGE_MAX_PLAN_FOLDERS,projectStorageConnectionInput,projectStorageConnectionRevokeInput,projectStorageBindingInput,projectStorageListInput,projectStorageFolderInput,projectStorageFolderUpdateInput,projectStorageFolderPlanInput,projectStorageFolderPlanApplyInput,projectStorageUploadInput,projectStorageAccessInput,type ProjectStorageActor,type ProjectStorageConnection,type ProjectStorageBinding,type ProjectStorageListing,type ProjectStorageFolderPlan,type ProjectStorageTransferAvailability} from './project-storage-protocol';

type Row=Record<string,any>;
const parse=<T>(schema:z.ZodType<T>,value:unknown):T=>{const result=schema.safeParse(value);if(!result.success)fail(400,result.error.issues.map(issue=>issue.message).slice(0,3).join(' '),'VALIDATION_ERROR');return result.data;};
const canonical=(value:any):string=>Array.isArray(value)?'['+value.map(canonical).join(',')+']':value&&typeof value==='object'?'{'+Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>JSON.stringify(key)+':'+canonical(item)).join(',')+'}':JSON.stringify(value);
const digest=(value:unknown)=>hashToken(canonical(value));
const iso=(value:Date|string)=>new Date(value).toISOString();
const nameKey=(value:string)=>value.normalize('NFC').toLowerCase();
export const projectStorageTransfers={available:false,code:'STORAGE_GATEWAY_UNAVAILABLE',message:'File transfers require the authenticated storage gateway. Folder organization is available; no file bytes have been uploaded by this feature.'} as const;
export type ProjectStorageTransferIntegration={
 availability(client?:PoolClient,companyId?:string,projectId?:string):ProjectStorageTransferAvailability|Promise<ProjectStorageTransferAvailability>;
 reserveUpload(client:PoolClient,actor:ProjectStorageActor,projectId:string,binding:ProjectStorageBinding,input:z.infer<typeof projectStorageUploadInput>):Promise<Row>;
 accessVersion(client:PoolClient,actor:ProjectStorageActor,projectId:string,version:Row,input:z.infer<typeof projectStorageAccessInput>):Promise<Row>;
};
type Envelope={keyId:string;nonce:string;tag:string;ciphertext:string};
function keyring(){
 try{const value=JSON.parse(process.env.COATRIA_HOSTING_KEYRING||''),keys=new Map<string,Buffer>();if(!/^[\w-]{1,40}$/.test(value.activeKeyId)||!value.keys||Object.keys(value.keys).length>5)throw Error();for(const[k,v]of Object.entries(value.keys)){if(typeof v!=='string'||!/^[\w-]{1,40}$/.test(k))throw Error();const key=Buffer.from(v,'base64');if(key.length!==32||key.toString('base64')!==v)throw Error();keys.set(k,key);}if(!keys.has(value.activeKeyId))throw Error();return {id:value.activeKeyId as string,keys};}
 catch{fail(503,'The server storage credential vault is unavailable.','STORAGE_VAULT_UNAVAILABLE');}
}
const aad=(companyId:string,connectionId:string)=>Buffer.from(JSON.stringify(['coatria:project-storage:v1',companyId,connectionId]));
function sealCredentials(value:unknown,companyId:string,connectionId:string):Envelope{const ring=keyring(),nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',ring.keys.get(ring.id)!,nonce);cipher.setAAD(aad(companyId,connectionId));const ciphertext=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return {keyId:ring.id,nonce:nonce.toString('base64'),tag:cipher.getAuthTag().toString('base64'),ciphertext:ciphertext.toString('base64')};}
function openCredentials(value:Envelope,companyId:string,connectionId:string):{accessKeyId:string;secretAccessKey:string}{
 const key=keyring().keys.get(value.keyId);if(!key)fail(503,'The saved storage credential key is unavailable.','STORAGE_VAULT_UNAVAILABLE');
 try{const nonce=Buffer.from(value.nonce,'base64'),tag=Buffer.from(value.tag,'base64');if(nonce.length!==12||tag.length!==16||value.ciphertext.length>4096)throw Error();const decipher=createDecipheriv('aes-256-gcm',key,nonce);decipher.setAAD(aad(companyId,connectionId));decipher.setAuthTag(tag);const result=JSON.parse(Buffer.concat([decipher.update(Buffer.from(value.ciphertext,'base64')),decipher.final()]).toString('utf8'));if(!projectStorageConnectionInput.shape.accessKeyId.safeParse(result.accessKeyId).success||!projectStorageConnectionInput.shape.secretAccessKey.safeParse(result.secretAccessKey).success)throw Error();return result;}
 catch{fail(503,'Saved storage credentials failed their integrity check. Reconnect the storage.','STORAGE_VAULT_INTEGRITY');}
}
/** Service methods run inside a transaction. Agent callers must first prove the
 * lease with authorizeRunTool; this check then revalidates current authority. */
export async function authorizeProjectStorageActor(client:PoolClient,actor:ProjectStorageActor,capability:'storage.read'|'storage.write'|'storage.organize',humanOnly=false){
 id(actor.companyId);id(actor.userId);await client.query('SELECT id FROM companies WHERE id=$1 FOR KEY SHARE',[actor.companyId]);
 const principals=[actor.userId];
 if(actor.agentId){const preview=(await client.query('SELECT created_by FROM agents WHERE company_id=$1 AND id=$2',[actor.companyId,actor.agentId])).rows[0];if(!preview)fail(403,'This storage agent is unavailable.','AGENT_CAPABILITY_REQUIRED');principals.push(preview.created_by,...await managedAgentAuthorityPrincipals(client,actor.companyId,actor.agentId));}
 const members=(await client.query('SELECT user_id,role FROM memberships WHERE company_id=$1 AND user_id=ANY($2::uuid[]) ORDER BY user_id FOR SHARE',[actor.companyId,[...new Set(principals)].sort()])).rows;
 const write=capability!=='storage.read',member=members.find(row=>row.user_id===actor.userId&&row.role!=='removed');if(!member)fail(403,'Your company storage access has ended.');
 if((write||humanOnly)&&!['owner','admin'].includes(member.role))fail(403,'A current company administrator is required.');
 if(!actor.agentId){if(actor.runId)fail(403,'An agent run requires its authenticated agent.');return;}
 if(humanOnly)fail(403,'Only a human administrator can manage storage credentials and project bindings.');
 if(!actor.runId)fail(403,'Use a live leased agent run.','AGENT_RUN_REQUIRED');
 const row=(await client.query(`SELECT a.capabilities,r.capabilities AS run_capabilities FROM agents a JOIN agent_runs r ON r.company_id=a.company_id AND r.agent_id=a.id JOIN memberships sponsor ON sponsor.company_id=a.company_id AND sponsor.user_id=a.created_by WHERE a.company_id=$1 AND a.id=$2 AND r.id=$3 AND r.requested_by=$4 AND a.status='active' AND a.expires_at>clock_timestamp() AND ${managedAgentAuthoritySql('a')} AND sponsor.role IN ('owner','admin') AND (a.invocation_access='members' OR a.invocation_access='admins' AND $5::boolean) AND r.status='running' AND r.lease_token_hash IS NOT NULL AND r.lease_expires_at>clock_timestamp() FOR SHARE OF a,r,sponsor`,[actor.companyId,actor.agentId,actor.runId,actor.userId,['owner','admin'].includes(member.role)])).rows[0];
 if(!row||!row.capabilities.includes(capability)||!row.run_capabilities.includes(capability))fail(403,'The agent needs the explicitly approved storage capability and a live lease.','AGENT_CAPABILITY_REQUIRED');
}
async function once(client:PoolClient,actor:ProjectStorageActor,clientId:string,operation:string,data:unknown,run:()=>Promise<Row>):Promise<Row>{
 const actorKey=actor.agentId?'agent:'+actor.agentId:'human:'+actor.userId,requestHash=digest({operation,data});await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`project-storage:${actor.companyId}:${actorKey}:${clientId}`]);
 const previous=(await client.query('SELECT request_hash,response FROM project_storage_requests WHERE company_id=$1 AND actor_key=$2 AND client_id=$3',[actor.companyId,actorKey,clientId])).rows[0];if(previous){if(previous.request_hash!==requestHash)fail(409,'This storage request ID was already used for different data.','IDEMPOTENCY_CONFLICT');return {...previous.response,replayed:true};}
 const result=await run();await client.query('INSERT INTO project_storage_requests(company_id,actor_key,client_id,request_hash,response) VALUES($1,$2,$3,$4,$5)',[actor.companyId,actorKey,clientId,requestHash,JSON.stringify(result)]);return {...result,replayed:false};
}
const connectionColumns=`c.id,c.name,c.provider,c.region,c.volume_id AS "volumeId",c.status,c.revision,c.created_at AS "createdAt",c.secret_envelope IS NOT NULL AS "credentialsConfigured"`;
const connectionView=(row:Row):ProjectStorageConnection=>({...row,createdAt:iso(row.createdAt),providerVerified:false}) as ProjectStorageConnection;
async function connection(client:PoolClient,companyId:string,connectionId:string,active=false){
 const row=(await client.query(`SELECT ${connectionColumns},c.created_by AS sponsor FROM project_storage_connections c WHERE c.company_id=$1 AND c.id=$2`,[companyId,id(connectionId)])).rows[0];if(!row)fail(404,'Storage connection not found.');
 if(active){const sponsor=(await client.query("SELECT user_id FROM memberships WHERE company_id=$1 AND user_id=$2 AND role IN ('owner','admin') FOR SHARE",[companyId,row.sponsor])).rows[0];const current=(await client.query("SELECT id FROM project_storage_connections WHERE company_id=$1 AND id=$2 AND status='configured' FOR SHARE",[companyId,connectionId])).rows[0];if(!sponsor||!current)fail(409,'This connection is revoked or its sponsoring administrator no longer has access.','STORAGE_CONNECTION_UNAVAILABLE');}
 const{sponsor,...safe}=row;return connectionView(safe);
}
/** Server-only gateway integration point. Never serialize this return value. */
export async function openProjectStorageCredentials(client:PoolClient,companyId:string,connectionId:string){const safe=await connection(client,companyId,connectionId,true);const row=(await client.query('SELECT secret_envelope FROM project_storage_connections WHERE company_id=$1 AND id=$2',[companyId,connectionId])).rows[0];return {connection:safe,...openCredentials(row.secret_envelope,companyId,connectionId)};}
export async function listProjectStorageConnections(client:PoolClient,actor:ProjectStorageActor,transfer?:ProjectStorageTransferIntegration){await authorizeProjectStorageActor(client,actor,'storage.read');const rows=(await client.query(`SELECT ${connectionColumns} FROM project_storage_connections c WHERE c.company_id=$1 ORDER BY c.created_at,c.id LIMIT 50`,[actor.companyId])).rows;return {connections:rows.map(connectionView),transfers:projectStorageTransfers};}
export async function createProjectStorageConnection(client:PoolClient,actor:ProjectStorageActor,input:unknown){const data=parse(projectStorageConnectionInput,input);await authorizeProjectStorageActor(client,actor,'storage.organize',true);return once(client,actor,data.clientId,'connection-create',data,async()=>{
 await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`storage-connections:${actor.companyId}`]);if(Number((await client.query('SELECT count(*) FROM project_storage_connections WHERE company_id=$1',[actor.companyId])).rows[0].count)>=50)fail(409,'This company reached its 50-storage-connection limit.');
 const connectionId=randomUUID(),envelope=sealCredentials({accessKeyId:data.accessKeyId,secretAccessKey:data.secretAccessKey},actor.companyId,connectionId);await client.query('INSERT INTO project_storage_connections(id,company_id,name,region,volume_id,secret_envelope,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[connectionId,actor.companyId,data.name,data.region,data.volumeId,JSON.stringify(envelope),actor.userId]);return {connection:await connection(client,actor.companyId,connectionId),transfers:projectStorageTransfers};});}
export async function revokeProjectStorageConnection(client:PoolClient,actor:ProjectStorageActor,connectionId:string,input:unknown){const data=parse(projectStorageConnectionRevokeInput,input);await authorizeProjectStorageActor(client,actor,'storage.organize',true);return once(client,actor,data.clientId,'connection-revoke:'+id(connectionId),data,async()=>{const row=(await client.query('SELECT revision FROM project_storage_connections WHERE company_id=$1 AND id=$2 FOR UPDATE',[actor.companyId,connectionId])).rows[0];if(!row)fail(404,'Storage connection not found.');if(row.revision!==data.revision)fail(409,'The storage connection changed. Refresh it.','STORAGE_REVISION_CONFLICT');await client.query("UPDATE project_storage_connections SET status='revoked',secret_envelope=NULL,revision=revision+1 WHERE company_id=$1 AND id=$2",[actor.companyId,connectionId]);return {connection:await connection(client,actor.companyId,connectionId)};});}
async function project(client:PoolClient,companyId:string,projectId:string){if(!(await client.query('SELECT id FROM studio_projects WHERE company_id=$1 AND id=$2',[companyId,id(projectId)])).rowCount)fail(404,'Studio project not found.');}
async function binding(client:PoolClient,companyId:string,projectId:string,write=false):Promise<ProjectStorageBinding|null>{await project(client,companyId,projectId);let row=(await client.query('SELECT id,project_id AS "projectId",connection_id AS "connectionId",revision,created_at AS "createdAt" FROM project_storage_bindings WHERE company_id=$1 AND project_id=$2',[companyId,projectId])).rows[0];if(!row)return null;const c=await connection(client,companyId,row.connectionId,write);if(write)row=(await client.query('SELECT id,project_id AS "projectId",connection_id AS "connectionId",revision,created_at AS "createdAt" FROM project_storage_bindings WHERE company_id=$1 AND project_id=$2 FOR UPDATE',[companyId,projectId])).rows[0];return {...row,createdAt:iso(row.createdAt),connection:c} as ProjectStorageBinding;}
export async function getProjectStorage(client:PoolClient,actor:ProjectStorageActor,projectId:string,transfer?:ProjectStorageTransferIntegration){await authorizeProjectStorageActor(client,actor,'storage.read');return {binding:await binding(client,actor.companyId,projectId),transfers:await transfer?.availability(client,actor.companyId,projectId)??projectStorageTransfers};}
export async function bindProjectStorage(client:PoolClient,actor:ProjectStorageActor,projectId:string,input:unknown){const data=parse(projectStorageBindingInput,input);await authorizeProjectStorageActor(client,actor,'storage.organize',true);return once(client,actor,data.clientId,'binding:'+id(projectId),data,async()=>{
 await connection(client,actor.companyId,data.connectionId,true);await project(client,actor.companyId,projectId);await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`storage-binding:${actor.companyId}:${projectId}`]);const existing=await binding(client,actor.companyId,projectId,true);
 if((existing?.revision??0)!==data.revision)fail(409,'The project storage changed. Refresh it.','STORAGE_REVISION_CONFLICT');if(existing&&existing.connectionId!==data.connectionId)fail(409,'A project storage binding cannot be moved to a different volume. Create a separately reviewed migration.','STORAGE_BINDING_IMMUTABLE');if(!existing)await client.query('INSERT INTO project_storage_bindings(company_id,project_id,connection_id,created_by) VALUES($1,$2,$3,$4)',[actor.companyId,projectId,data.connectionId,actor.userId]);return {binding:await binding(client,actor.companyId,projectId),transfers:projectStorageTransfers};});}
async function writableBinding(client:PoolClient,actor:ProjectStorageActor,projectId:string,revision:number){const result=await binding(client,actor.companyId,projectId,true);if(!result)fail(409,'Connect this project to storage first.','STORAGE_BINDING_REQUIRED');if(result.revision!==revision)fail(409,'The folder catalog changed. Refresh before applying this edit.','STORAGE_REVISION_CONFLICT');return result;}
async function folders(client:PoolClient,companyId:string,projectId:string){return (await client.query('SELECT id,parent_id,name,name_key FROM project_storage_folders WHERE company_id=$1 AND project_id=$2 ORDER BY id LIMIT $3',[companyId,projectId,PROJECT_STORAGE_MAX_FOLDERS+1])).rows;}
function ancestors(rows:Row[],parentId:string|null,map=new Map(rows.map(row=>[row.id,row]))){const result:Row[]=[],seen=new Set<string>();let cursor=parentId;while(cursor){if(seen.has(cursor))fail(409,'The folder hierarchy is invalid.','STORAGE_FOLDER_CYCLE');seen.add(cursor);const row=map.get(cursor);if(!row)fail(404,'Folder not found in this project.');result.unshift(row);cursor=row.parent_id;if(result.length>12)fail(409,'The folder hierarchy exceeds its maximum depth.','STORAGE_FOLDER_DEPTH');}return result;}
async function nameAvailable(client:PoolClient,companyId:string,projectId:string,parentId:string|null,name:string,except?:string){const found=(await client.query('SELECT id FROM project_storage_folders WHERE company_id=$1 AND project_id=$2 AND parent_id IS NOT DISTINCT FROM $3::uuid AND name_key=$4 AND ($5::uuid IS NULL OR id<>$5) UNION ALL SELECT id FROM project_storage_files WHERE company_id=$1 AND project_id=$2 AND parent_id IS NOT DISTINCT FROM $3::uuid AND name_key=$4 LIMIT 1',[companyId,projectId,parentId,nameKey(name),except??null])).rows[0];if(found)fail(409,'An item with this name already exists in that folder.','STORAGE_NAME_CONFLICT');}
async function bumpBinding(client:PoolClient,companyId:string,projectId:string){await client.query('UPDATE project_storage_bindings SET revision=revision+1 WHERE company_id=$1 AND project_id=$2',[companyId,projectId]);return binding(client,companyId,projectId);}
const folderView=(row:Row)=>({kind:'folder' as const,id:row.id,parentId:row.parent_id,name:row.name,createdAt:iso(row.created_at)});
async function insertFolder(client:PoolClient,actor:ProjectStorageActor,projectId:string,bindingId:string,parentId:string|null,name:string){return (await client.query('INSERT INTO project_storage_folders(company_id,project_id,binding_id,parent_id,name,name_key,created_by,created_agent_id,run_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[actor.companyId,projectId,bindingId,parentId,name,nameKey(name),actor.userId,actor.agentId??null,actor.runId??null])).rows[0];}
export async function createProjectStorageFolder(client:PoolClient,actor:ProjectStorageActor,projectId:string,input:unknown){const data=parse(projectStorageFolderInput,input);await authorizeProjectStorageActor(client,actor,'storage.organize');return once(client,actor,data.clientId,'folder-create:'+id(projectId),data,async()=>{const b=await writableBinding(client,actor,projectId,data.revision),tree=await folders(client,actor.companyId,projectId);if(tree.length>=PROJECT_STORAGE_MAX_FOLDERS)fail(409,'The project reached its folder limit.');if(ancestors(tree,data.parentId).length>=12)fail(409,'Folders may be at most 12 levels deep.','STORAGE_FOLDER_DEPTH');await nameAvailable(client,actor.companyId,projectId,data.parentId,data.name);const folder=await insertFolder(client,actor,projectId,b.id,data.parentId,data.name);return {folder:folderView(folder),binding:await bumpBinding(client,actor.companyId,projectId)};});}
export async function updateProjectStorageFolder(client:PoolClient,actor:ProjectStorageActor,projectId:string,folderId:string,input:unknown){const data=parse(projectStorageFolderUpdateInput,input);await authorizeProjectStorageActor(client,actor,'storage.organize');return once(client,actor,data.clientId,'folder-update:'+id(projectId)+':'+id(folderId),data,async()=>{await writableBinding(client,actor,projectId,data.revision);const tree=await folders(client,actor.companyId,projectId),current=tree.find(row=>row.id===folderId);if(!current)fail(404,'Folder not found in this project.');if(data.parentId===folderId||ancestors(tree,data.parentId).some(row=>row.id===folderId))fail(409,'A folder cannot be placed inside itself or a descendant.','STORAGE_FOLDER_CYCLE');const changed=tree.map(row=>row.id===folderId?{...row,parent_id:data.parentId}:row),map=new Map(changed.map(row=>[row.id,row]));for(const row of changed)ancestors(changed,row.id,map);await nameAvailable(client,actor.companyId,projectId,data.parentId,data.name,folderId);const row=(await client.query('UPDATE project_storage_folders SET parent_id=$4,name=$5,name_key=$6 WHERE company_id=$1 AND project_id=$2 AND id=$3 RETURNING *',[actor.companyId,projectId,folderId,data.parentId,data.name,nameKey(data.name)])).rows[0];return {folder:folderView(row),binding:await bumpBinding(client,actor.companyId,projectId)};});}
export async function listProjectStorageFiles(client:PoolClient,actor:ProjectStorageActor,projectId:string,input:unknown={},transfer?:ProjectStorageTransferIntegration):Promise<ProjectStorageListing>{
 const page=parse(projectStorageListInput,input);await authorizeProjectStorageActor(client,actor,'storage.read');const b=await binding(client,actor.companyId,projectId),tree=b?await folders(client,actor.companyId,projectId):[],breadcrumbs=ancestors(tree,page.parentId??null).map(row=>({id:row.id,name:row.name}));
 if(page.after&&!(await client.query('SELECT id FROM project_storage_folders WHERE company_id=$1 AND project_id=$2 AND parent_id IS NOT DISTINCT FROM $3::uuid AND id=$4 UNION ALL SELECT id FROM project_storage_files WHERE company_id=$1 AND project_id=$2 AND parent_id IS NOT DISTINCT FROM $3::uuid AND id=$4',[actor.companyId,projectId,page.parentId??null,page.after])).rowCount)fail(404,'Page cursor not found in this folder.');
 const rows=(await client.query(`SELECT id,parent_id,name,created_at,'folder' AS kind,NULL::jsonb AS latest_version FROM project_storage_folders WHERE company_id=$1 AND project_id=$2 AND parent_id IS NOT DISTINCT FROM $3::uuid AND ($4::uuid IS NULL OR id>$4) UNION ALL SELECT f.id,f.parent_id,f.name,f.created_at,'file' AS kind,(SELECT jsonb_build_object('id',v.id,'version',v.version,'bytes',v.bytes::float8,'sha256',COALESCE(ok.sha256,v.sha256),'contentType',v.content_type,'verified',ok.version_id IS NOT NULL) FROM project_storage_versions v LEFT JOIN project_storage_verifications ok ON ok.company_id=v.company_id AND ok.version_id=v.id AND ok.bytes=v.bytes AND (v.sha256 IS NULL OR ok.sha256=v.sha256) WHERE v.company_id=f.company_id AND v.file_id=f.id ORDER BY version DESC LIMIT 1) AS latest_version FROM project_storage_files f WHERE company_id=$1 AND project_id=$2 AND parent_id IS NOT DISTINCT FROM $3::uuid AND ($4::uuid IS NULL OR id>$4) ORDER BY id LIMIT $5`,[actor.companyId,projectId,page.parentId??null,page.after??null,page.limit+1])).rows;
 const items=rows.slice(0,page.limit).map(row=>row.kind==='folder'?folderView(row):({...folderView(row),kind:'file' as const,latestVersion:row.latest_version}));return {binding:b,items,breadcrumbs,page:{limit:page.limit,hasMore:rows.length>page.limit,nextAfter:rows.length>page.limit?items.at(-1)!.id:null},transfers:await transfer?.availability(client,actor.companyId,projectId)??projectStorageTransfers};
}
async function planView(client:PoolClient,companyId:string,projectId:string,planId:string):Promise<ProjectStorageFolderPlan>{const row=(await client.query('SELECT p.*,EXISTS(SELECT 1 FROM project_storage_plan_applications a WHERE a.company_id=p.company_id AND a.plan_id=p.id) AS applied FROM project_storage_folder_plans p WHERE p.company_id=$1 AND p.project_id=$2 AND p.id=$3',[companyId,projectId,planId])).rows[0];if(!row)fail(404,'Folder plan not found.');return {id:row.id,projectId:row.project_id,bindingId:row.binding_id,bindingRevision:row.binding_revision,planHash:row.plan_hash,folders:row.folders,createdAt:iso(row.created_at),expiresAt:iso(row.expires_at),createsFolderCount:row.folders.filter((folder:Row)=>!folder.exists).length,applied:row.applied};}
export async function getProjectStorageFolderPlan(client:PoolClient,actor:ProjectStorageActor,projectId:string,planId:string){await authorizeProjectStorageActor(client,actor,'storage.read');await project(client,actor.companyId,projectId);return {plan:await planView(client,actor.companyId,projectId,id(planId))};}
export async function listProjectStorageFolderPlans(client:PoolClient,actor:ProjectStorageActor,projectId:string,input:unknown={}){const page=parse(projectStoragePlanListInput,input);await authorizeProjectStorageActor(client,actor,'storage.read');await project(client,actor.companyId,projectId);if(page.after)await planView(client,actor.companyId,projectId,page.after);const rows=(await client.query('SELECT id FROM project_storage_folder_plans WHERE company_id=$1 AND project_id=$2 AND ($3::uuid IS NULL OR id>$3) ORDER BY id LIMIT $4',[actor.companyId,projectId,page.after??null,page.limit+1])).rows,plans=[];for(const row of rows.slice(0,page.limit)){const{folders:_,...summary}=await planView(client,actor.companyId,projectId,row.id);plans.push(summary);}return {plans,page:{limit:page.limit,hasMore:rows.length>page.limit,nextAfter:rows.length>page.limit?plans.at(-1)!.id:null}};}
export async function updateProjectStorageFile(client:PoolClient,actor:ProjectStorageActor,projectId:string,fileId:string,input:unknown){const data=parse(projectStorageFolderUpdateInput,input);await authorizeProjectStorageActor(client,actor,'storage.organize');return once(client,actor,data.clientId,'file-update:'+id(projectId)+':'+id(fileId),data,async()=>{await writableBinding(client,actor,projectId,data.revision);ancestors(await folders(client,actor.companyId,projectId),data.parentId);const file=(await client.query('SELECT id FROM project_storage_files WHERE company_id=$1 AND project_id=$2 AND id=$3',[actor.companyId,projectId,fileId])).rows[0];if(!file)fail(404,'File not found in this project.');const collision=(await client.query('SELECT id FROM project_storage_folders WHERE company_id=$1 AND project_id=$2 AND parent_id IS NOT DISTINCT FROM $3::uuid AND name_key=$4 UNION ALL SELECT id FROM project_storage_files WHERE company_id=$1 AND project_id=$2 AND parent_id IS NOT DISTINCT FROM $3::uuid AND name_key=$4 AND id<>$5 LIMIT 1',[actor.companyId,projectId,data.parentId,nameKey(data.name),fileId])).rows[0];if(collision)fail(409,'An item with this name already exists in that folder.','STORAGE_NAME_CONFLICT');await client.query('UPDATE project_storage_files SET parent_id=$4,name=$5,name_key=$6 WHERE company_id=$1 AND project_id=$2 AND id=$3',[actor.companyId,projectId,fileId,data.parentId,data.name,nameKey(data.name)]);return {file:{id:fileId,parentId:data.parentId,name:data.name},binding:await bumpBinding(client,actor.companyId,projectId)};});}
function plannedFolders(tree:Row[],paths:string[]){const all=new Map<string,string>();for(const path of paths){let current='';for(const segment of path.split('/')){current=current?current+'/'+segment:segment;const key=nameKey(current),prior=all.get(key);if(prior&&prior!==current)fail(400,'Folder paths must use consistent capitalization.','VALIDATION_ERROR');all.set(key,current);}}if(all.size>PROJECT_STORAGE_MAX_PLAN_FOLDERS)fail(400,'This plan exceeds 200 folders including parents.','VALIDATION_ERROR');const map=new Map(tree.map(row=>[row.id,row])),existing=new Set(tree.map(row=>nameKey(ancestors(tree,row.id,map).map(part=>part.name).join('/'))));return [...all.values()].sort((a,b)=>a.split('/').length-b.split('/').length||a.localeCompare(b)).map(path=>({path,exists:existing.has(nameKey(path))}));}
export async function previewProjectStorageFolderPlan(client:PoolClient,actor:ProjectStorageActor,projectId:string,input:unknown){const data=parse(projectStorageFolderPlanInput,input);await authorizeProjectStorageActor(client,actor,'storage.organize');return once(client,actor,data.clientId,'folder-plan:'+id(projectId),data,async()=>{const b=await writableBinding(client,actor,projectId,data.revision),tree=await folders(client,actor.companyId,projectId),planned=plannedFolders(tree,data.paths);if(tree.length+planned.filter(row=>!row.exists).length>PROJECT_STORAGE_MAX_FOLDERS)fail(409,'This plan exceeds the project folder limit.');const planId=randomUUID(),planHash=digest({schemaVersion:1,companyId:actor.companyId,projectId,bindingId:b.id,bindingRevision:b.revision,folders:planned});await client.query("INSERT INTO project_storage_folder_plans(id,company_id,project_id,binding_id,binding_revision,plan_hash,folders,created_by,created_agent_id,run_id,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,clock_timestamp()+interval '1 hour')",[planId,actor.companyId,projectId,b.id,b.revision,planHash,JSON.stringify(planned),actor.userId,actor.agentId??null,actor.runId??null]);return {plan:await planView(client,actor.companyId,projectId,planId)};});}
export async function applyProjectStorageFolderPlan(client:PoolClient,actor:ProjectStorageActor,projectId:string,planId:string,input:unknown){const data=parse(projectStorageFolderPlanApplyInput,input);await authorizeProjectStorageActor(client,actor,'storage.organize');return once(client,actor,data.clientId,'folder-plan-apply:'+id(projectId)+':'+id(planId),data,async()=>{const b=await writableBinding(client,actor,projectId,data.revision),plan=await planView(client,actor.companyId,projectId,planId);if(plan.planHash!==data.planHash||plan.bindingId!==b.id)fail(409,'This plan does not match the reviewed project and folder structure.','STORAGE_PLAN_MISMATCH');if(plan.applied)fail(409,'This folder plan was already applied.','STORAGE_PLAN_APPLIED');if(plan.bindingRevision!==b.revision)fail(409,'The folder catalog changed after this preview.','STORAGE_REVISION_CONFLICT');if(new Date(plan.expiresAt).getTime()<=Date.now())fail(409,'This folder preview expired. Make a new preview.','STORAGE_PLAN_EXPIRED');const tree=await folders(client,actor.companyId,projectId);for(const entry of plan.folders){let parentId:string|null=null;for(const name of entry.path.split('/')){const existing=tree.find(row=>row.parent_id===parentId&&row.name_key===nameKey(name));if(existing){parentId=existing.id;continue;}await nameAvailable(client,actor.companyId,projectId,parentId,name);const created=await insertFolder(client,actor,projectId,b.id,parentId,name);tree.push(created);parentId=created.id;}}const updated=await bumpBinding(client,actor.companyId,projectId),result={createdFolderCount:plan.createsFolderCount,binding:updated};await client.query('INSERT INTO project_storage_plan_applications(company_id,project_id,plan_id,applied_by,applied_agent_id,run_id,result) VALUES($1,$2,$3,$4,$5,$6,$7)',[actor.companyId,projectId,planId,actor.userId,actor.agentId??null,actor.runId??null,JSON.stringify(result)]);return {...result,plan:await planView(client,actor.companyId,projectId,planId)};});}
/** Intentionally no session or grant is created until a real gateway is wired. */
export async function reserveProjectStorageUpload(client:PoolClient,actor:ProjectStorageActor,projectId:string,input:unknown,transfer?:ProjectStorageTransferIntegration):Promise<Row>{
 const data=parse(projectStorageUploadInput,input);await authorizeProjectStorageActor(client,actor,'storage.write');
 // A successful reservation changes the catalog revision. Permit its exact
 // existing session to reach the integration's immutable payload-hash check.
 const b=await binding(client,actor.companyId,projectId,true);if(!b)fail(409,'Connect this project to storage first.','STORAGE_BINDING_REQUIRED');
 const prior=(await client.query('SELECT id FROM project_storage_uploads WHERE company_id=$1 AND project_id=$2 AND actor_key=$3 AND client_id=$4',[actor.companyId,projectId,actor.agentId?'agent:'+actor.agentId:'human:'+actor.userId,data.clientId])).rows[0];
 if(!prior&&b.revision!==data.revision)fail(409,'The folder catalog changed. Refresh before uploading.','STORAGE_REVISION_CONFLICT');
 ancestors(await folders(client,actor.companyId,projectId),data.parentId);if(data.fileId&&!(await client.query('SELECT id FROM project_storage_files WHERE company_id=$1 AND project_id=$2 AND id=$3',[actor.companyId,projectId,data.fileId])).rowCount)fail(404,'File not found in this project.');if(!transfer||!(await transfer.availability(client,actor.companyId,projectId)).available)fail(503,projectStorageTransfers.message,projectStorageTransfers.code);return transfer.reserveUpload(client,actor,projectId,b,data);
}
export async function accessProjectStorageVersion(client:PoolClient,actor:ProjectStorageActor,projectId:string,versionId:string,input:unknown,transfer?:ProjectStorageTransferIntegration):Promise<Row>{const data=parse(projectStorageAccessInput,input);await authorizeProjectStorageActor(client,actor,'storage.read');const b=await binding(client,actor.companyId,projectId);if(!b)fail(404,'Project storage not found.');await connection(client,actor.companyId,b.connectionId,true);const row=(await client.query('SELECT v.*,ok.sha256 AS verified_sha256,ok.provider_etag FROM project_storage_versions v JOIN project_storage_verifications ok ON ok.company_id=v.company_id AND ok.version_id=v.id AND ok.bytes=v.bytes AND (v.sha256 IS NULL OR ok.sha256=v.sha256) WHERE v.company_id=$1 AND v.project_id=$2 AND v.id=$3',[actor.companyId,projectId,id(versionId)])).rows[0];if(!row)fail(404,'Verified file version not found in this project.');if(!transfer||!(await transfer.availability(client,actor.companyId,projectId)).available)fail(503,projectStorageTransfers.message,projectStorageTransfers.code);return transfer.accessVersion(client,actor,projectId,{...row,connectionId:b.connectionId,connectionRevision:b.connection.revision},data);}
export async function projectStorageRoute(request:Request,parts:string[],method:string,transfer?:ProjectStorageTransferIntegration):Promise<Response|null>{
 if(parts[0]!=='companies')return null;const connections=parts[2]==='storage-connections'&&parts.length<=4,projectRoute=parts[2]==='studio'&&parts[3]==='projects'&&['storage','files'].includes(parts[5]);if(!connections&&!projectRoute)return null;
 const companyId=id(parts[1]),write=method!=='GET',access=parts[6]==='versions'&&parts[8]==='access'&&method==='POST',member=await requireMembership(request,companyId,write&&!access),actor={companyId,userId:member.userId};if(write)assertOrigin(request);
 const read=(run:(client:PoolClient)=>Promise<unknown>)=>memberMutation(member,false,run),mutate=(run:(client:PoolClient)=>Promise<unknown>)=>memberMutation(member,true,run);
 if(connections){if(parts.length===3&&method==='GET')return json(await read(client=>listProjectStorageConnections(client,actor,transfer)));if(parts.length===3&&method==='POST'){const data=await body(request,projectStorageConnectionInput);const result=await mutate(client=>createProjectStorageConnection(client,actor,data)) as Row;return json(result,result.replayed?200:201);}if(parts.length===4&&method==='PATCH'){const data=await body(request,projectStorageConnectionRevokeInput);return json(await mutate(client=>revokeProjectStorageConnection(client,actor,parts[3],data)));}return null;}
 const projectId=id(parts[4]);if(parts.length===6&&parts[5]==='storage'){if(method==='GET')return json(await read(client=>getProjectStorage(client,actor,projectId,transfer)));if(method==='PUT'){const data=await body(request,projectStorageBindingInput);return json(await mutate(client=>bindProjectStorage(client,actor,projectId,data)));}}
 if(parts[5]!=='files')return null;
 if(parts.length===6&&method==='GET'){const params=new URL(request.url).searchParams,input={...(params.has('parentId')?{parentId:params.get('parentId')}:{}),...(params.has('after')?{after:params.get('after')}:{}),...(params.has('limit')?{limit:Number(params.get('limit'))}:{})};return json(await read(client=>listProjectStorageFiles(client,actor,projectId,input,transfer)));}
 if(parts[6]==='folders'&&parts.length===7&&method==='POST'){const data=await body(request,projectStorageFolderInput),result=await mutate(client=>createProjectStorageFolder(client,actor,projectId,data)) as Row;return json(result,result.replayed?200:201);}
 if(parts[6]==='folders'&&parts.length===8&&method==='PATCH'){const data=await body(request,projectStorageFolderUpdateInput);return json(await mutate(client=>updateProjectStorageFolder(client,actor,projectId,parts[7],data)));}
 if(parts[6]==='items'&&parts.length===8&&method==='PATCH'){const data=await body(request,projectStorageFolderUpdateInput);return json(await mutate(client=>updateProjectStorageFile(client,actor,projectId,parts[7],data)));}
 if(parts[6]==='folder-plans'&&parts.length===7&&method==='GET'){const params=new URL(request.url).searchParams,input={...(params.has('after')?{after:params.get('after')}:{}),...(params.has('limit')?{limit:Number(params.get('limit'))}:{})};return json(await read(client=>listProjectStorageFolderPlans(client,actor,projectId,input)));}
 if(parts[6]==='folder-plans'&&parts.length===8&&method==='GET')return json(await read(client=>getProjectStorageFolderPlan(client,actor,projectId,parts[7])));
 if(parts[6]==='folder-plans'&&parts.length===7&&method==='POST'){const data=await body(request,projectStorageFolderPlanInput),result=await mutate(client=>previewProjectStorageFolderPlan(client,actor,projectId,data)) as Row;return json(result,result.replayed?200:201);}
 if(parts[6]==='folder-plans'&&parts.length===9&&parts[8]==='apply'&&method==='POST'){const data=await body(request,projectStorageFolderPlanApplyInput);return json(await mutate(client=>applyProjectStorageFolderPlan(client,actor,projectId,parts[7],data)));}
 if(parts[6]==='uploads'&&parts.length===7&&method==='POST'){const data=await body(request,projectStorageUploadInput);return json(await mutate(client=>reserveProjectStorageUpload(client,actor,projectId,data,transfer)));}
 if(parts[6]==='versions'&&parts.length===9&&parts[8]==='access'&&method==='POST'){const data=await body(request,projectStorageAccessInput);return json(await read(client=>accessProjectStorageVersion(client,actor,projectId,parts[7],data,transfer)));}
 return null;
}
