import {z} from 'zod';
import {projectImagePreparationProposalInput,projectImagePreparationApproveInput,projectImagePreparationRevokeInput,projectImagePreparationReferenceInput} from './project-image-preparations-protocol';
const parameter=(name:string,location='path',required=true)=>({name,in:location,required,schema:{type:'string',format:'uuid'}});
const company=[parameter('companyId')],preparation=[...company,parameter('preparationId')];
const errors=Object.fromEntries([400,401,403,404,409,413,415,429,503].map(code=>[code,{description:'Invalid, unavailable, changed or unauthorized preparation. Unknown storage outcomes require reconciliation, never blind repetition.'}]));
function operation(summary:string,parameters:unknown[],input?:z.ZodType,admin=false){return {summary,tags:['Project image preparation'],security:[{sessionCookie:[]}],parameters:input?[...parameters,{name:'Origin',in:'header',required:true,schema:{type:'string',format:'uri'}}]:parameters,...input?{'x-coatria-roles':admin?['owner','admin']:['owner','admin','member'],requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(input,{io:'input',unrepresentable:'any'})}}}}:{},responses:{'200':{description:'Current safe company/project metadata. No byte transport, credentials, worker lease or execution endpoint.'},...input&&!admin?{'201':{description:'Proposal saved. No processing, external sharing, generation or acceptance authorized.'}}:{},...errors}};}
export const projectImagePreparationPaths={
 '/api/companies/{companyId}/image-preparations':{
  get:operation('Page original-image preparation metadata, provenance and trusted processor availability. Follow nextAfter. Availability does not grant permission to process.',[...company,parameter('projectId','query'),parameter('after','query',false),{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:20}}]),
  post:operation('Propose one exact verified original up to 32 MiB for a separate PNG derivative. Pins source hash/bytes, project, work and destination. Original bytes remain intact. submitted_plan_v1 is only valid for the current assigned reference agent; an ordinary browser proposal omits it.',company,projectImagePreparationProposalInput)},
 '/api/companies/{companyId}/image-preparations/{preparationId}':{get:operation('Read exact original, finite processing approval, durable status and independently verified derivative receipt. Ready is separate from reference sharing, media review and delivery.',preparation)},
 '/api/companies/{companyId}/image-preparations/{preparationId}/approve':{post:operation('Current human administrator adopts the exact proposal and grants finite processing and derivative writing to the server-qualified processor. Requires all three literal consents and the exact request/revision. Does not approve sharing to Higgsfield.',preparation,projectImagePreparationApproveInput,true)},
 '/api/companies/{companyId}/image-preparations/{preparationId}/revoke':{post:operation('Current human administrator stops future preparation actions. Historical originals, derivatives and uncertain provider outcomes remain preserved for reconciliation.',preparation,projectImagePreparationRevokeInput,true)},
 '/api/companies/{companyId}/image-preparations/{preparationId}/reference':{post:operation('Create a fresh ordinary reference proposal for a ready verified derivative and a current eligible task. Server owns output identity, source provenance and hash. Does not reuse an ended agent run or approve sharing. Higgsfield inspection and separate human sharing consent remain required.',preparation,projectImagePreparationReferenceInput)},
};
for(const[path,methods]of Object.entries(projectImagePreparationPaths))for(const[method,definition]of Object.entries(methods))Object.assign(definition,{operationId:'project_image_preparation_'+method+'_'+path.replace(/[^a-zA-Z0-9]+/g,'_')});
