import {z} from 'zod';
import {projectStorageConnectionInput,projectStorageConnectionRevokeInput,projectStorageConnectionReauthorizeInput,projectStorageBindingInput,projectStorageFolderInput,projectStorageFolderUpdateInput,projectStorageFolderPlanInput,projectStorageFolderPlanApplyInput,projectStorageUploadInput,projectStorageAccessInput} from './project-storage-protocol';
const param=(name:string)=>({name,in:'path',required:true,schema:{type:'string',format:'uuid'}});
const company=[param('companyId')],project=[...company,param('projectId')];
const json=(schema:unknown)=>({'application/json':{schema}});
const operation=(operationId:string,summary:string,parameters:unknown[],body?:z.ZodType)=>({operationId,summary,security:[{sessionCookie:[]}],parameters,...body?{requestBody:{required:true,content:json(z.toJSONSchema(body,{io:'input',unrepresentable:'any'}))}}:{},responses:{'200':{description:'Current scoped storage result; file transfers require the separate gateway.',content:json({type:'object'})},'201':{description:'Created logical folder, connection or reviewed plan.'},'403':{description:'Current company or explicitly granted agent authority is missing.'},'409':{description:'Catalog revision, exact request or file scope changed.'},'503':{description:'The authenticated storage transfer service is not configured. No file upload or download is issued.'}}});
const base='/api/companies/{companyId}/studio/projects/{projectId}';
export const projectStoragePaths={
 '/api/companies/{companyId}/storage-connections':{get:operation('listProjectStorageConnections','List configured and revoked Runpod storage connections without credentials.',company),post:operation('createProjectStorageConnection','Administrator: save encrypted S3 credentials for an existing Runpod volume. Does not purchase or verify the volume.',company,projectStorageConnectionInput)},
 '/api/companies/{companyId}/storage-connections/{connectionId}':{patch:operation('revokeProjectStorageConnection','Revoke the storage connection and destroy its saved credential envelope. Does not delete provider files.',[...company,param('connectionId')],projectStorageConnectionRevokeInput)},
 '/api/companies/{companyId}/storage-connections/{connectionId}/reauthorize':{post:operation('reauthorizeProjectStorageConnection','Human administrator: replace credentials on this exact storage identity using revision and idempotency guards. Retains folders, objects and history; old transfer grants and upload epochs remain invalid. Does not verify provider access or create resources.',[...company,param('connectionId')],projectStorageConnectionReauthorizeInput)},
 '/api/companies/{companyId}/storage-connections/{connectionId}/reauthorize/{clientId}':{get:operation('getProjectStorageReauthorization','Human administrator: read your exact credential-replacement receipt and current connection without keys. An absent receipt is not proof that an uncertain request cannot finish.',[...company,param('connectionId'),param('clientId')])},
 [base+'/storage']:{get:operation('getProjectStorageBinding','Read the immutable project-volume binding and transfer availability.',project),put:operation('bindProjectStorage','Administrator: bind a project to existing storage. Rebinding to another volume requires a separate migration.',project,projectStorageBindingInput)},
 [base+'/files']:{get:operation('listProjectFiles','Browse logical folders and versioned files using parentId, after and limit. Metadata is not content access.',project)},
 [base+'/files/folders']:{post:operation('createProjectFolder','Create one project folder against the current catalog revision.',project,projectStorageFolderInput)},
 [base+'/files/folders/{folderId}']:{patch:operation('moveProjectFolder','Rename or move a folder without changing file objects.',[...project,param('folderId')],projectStorageFolderUpdateInput)},
 [base+'/files/items/{fileId}']:{patch:operation('moveProjectFile','Rename or move a file without modifying its immutable version keys.',[...project,param('fileId')],projectStorageFolderUpdateInput)},
 [base+'/files/folder-plans']:{get:operation('listProjectFolderPlans','Read persisted additive folder-plan summaries with after and limit.',project),post:operation('previewProjectFolderPlan','Preview and save an additive folder structure for review.',project,projectStorageFolderPlanInput)},
 [base+'/files/folder-plans/{planId}']:{get:operation('getProjectFolderPlan','Read the exact saved folder plan and its hash.',[...project,param('planId')])},
 [base+'/files/folder-plans/{planId}/apply']:{post:operation('applyProjectFolderPlan','Apply an exact reviewed folder plan with optimistic catalog revision protection.',[...project,param('planId')],projectStorageFolderPlanApplyInput)},
 [base+'/files/uploads']:{post:operation('reserveProjectFileUpload','Reserve a version and temporary multipart capability. Bytes go to the separate gateway; ready requires server byte verification. Exact retries may renew access to the same upload.',project,projectStorageUploadInput)},
 [base+'/files/versions/{versionId}/access']:{post:operation('accessProjectFileVersion','Issue temporary authenticated download access for a verified version to a current company member. Always downloads as an attachment.',[...project,param('versionId')],projectStorageAccessInput)},
};
