import {z} from 'zod';
import {STUDIO_TEMPLATES} from './studio-protocol';

const uuid=z.string().uuid(),revision=z.number().int().min(1).max(2147483646);
export const studioCoordinationInput=z.object({
 clientId:uuid,revision:z.number().int().min(0).max(2147483646),coordinatorAgentId:uuid,
 allowedRoleKeys:z.array(z.string().refine(key=>STUDIO_TEMPLATES[0].roles.some(role=>role.key===key),'Choose a curated studio role.')).min(1).max(11).refine(keys=>new Set(keys).size===keys.length,'Roles must be unique.'),
 planningRework:z.boolean().optional().describe('Explicit finite estimate/breakdown corrections after completed changes_requested reviews, within the existing specialist allowance. No generation retry or approval authority.'),
 mediaRework:z.boolean().optional().describe('Default off. One same-work correction proposal per independently rejected generated artifact, within the existing lifetime run allowance and expiry. Every new paid request still requires exact human credit consent.'),
 generatedContinuations:z.boolean().optional(),
 referencePreparationProfile:z.literal('prepared_image_v1').optional().describe('Human-approved existing-image selection by a separate reference specialist. Current exact coordination policy remains required for later finite inspection. No transformation, sharing or generation authority.'),
 coordinatorGeneration:z.boolean().optional().describe('Explicit human-reviewed opt-in for a separate generation child on the coordinator identity, only for generated-media projects. Defaults to false. Does not permit nested delegation or spending.'),
 status:z.enum(['active','paused']),maxRuns:z.number().int().min(1).max(100),maxConcurrentRuns:z.number().int().min(1).max(3),expiresAt:z.string().datetime(),
}).strict();
export const studioCoordinationGetInput=z.object({projectId:uuid}).strict();
export const studioWorkDispatchInput=z.object({projectId:uuid,workItemId:uuid,policyRevision:revision,projectRevision:revision,executionJobId:uuid.optional(),planningReviewId:uuid.optional(),mediaReviewId:uuid.optional(),taskRevision:revision.optional()}).strict().refine(v=>[v.executionJobId,v.planningReviewId,v.mediaReviewId].filter(Boolean).length<=1,'Choose one exact continuation.').refine(v=>Boolean(v.mediaReviewId)===(v.taskRevision!==undefined),'Media correction requires its exact task revision.');
export type StudioCoordinationPolicy={mediaRework?:boolean;planningRework?:boolean;referencePreparationProfile?:'prepared_image_v1';generatedContinuations?:boolean;coordinatorGeneration?:boolean;projectId:string;coordinatorAgentId:string;allowedRoleKeys:string[];status:'active'|'paused';effectiveStatus:'active'|'paused'|'expired'|'approval_required'|'exhausted';blocker:string|null;revision:number;maxRuns:number;runsStarted:number;remainingRuns:number;maxConcurrentRuns:number;approvedBy:string;expiresAt:string;updatedAt:string;profileRevision:number};
export type StudioCoordinationDispatch={workItemId:string;parentRunId:string;childRunId:string;coordinatorAgentId:string;specialistAgentId:string;policyRevision:number;createdAt:string;status:string;executionJobId?:string|null;sourceChildRunId?:string|null;artifactId?:string|null;archiveId?:string|null;planningReviewId?:string|null;mediaReviewId?:string;artifactVersion?:number;taskRevision?:number;roundId?:string|null};
export type StudioMediaRework={projectId:string;workItemId:string;reviewId:string;taskId:string;taskRevision:number;artifactId:string;artifactVersion:number;manifestSha256:string;specSha256:string;roundId:string|null;sourceChildRunId:string;specialistAgentId:string;reviewedBy:string;reviewedAt:string;reviewNote:string};
export type StudioRenderFollowup={projectId:string;workItemId:string;executionJobId:string;sourceChildRunId:string;specialistAgentId:string;taskId:string;roleKey:string;executionManifestSha256:string;artifactId:string;artifactSha256:string};
export type StudioCoordinationSnapshot={policy:StudioCoordinationPolicy|null;dispatches:StudioCoordinationDispatch[];mediaReworks?:StudioMediaRework[];planningReworks?:{projectId:string;workItemId:string;reviewId:string;taskId:string;taskRevision:number;sourceChildRunId:string;specialistAgentId:string}[];renderFollowups?:StudioRenderFollowup[];budgetUnit:'specialist_runs';budgetScope:'coordinator_dispatched_runs_only';startsWorkers:false;startsInference:false};
