import {loadCompanyRuntimeConfiguration} from './company-runtime-config';
import {createCipheriv,createDecipheriv,randomBytes,randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {z} from 'zod';
import {parseStudioCpuPreset,runtimeConfigurationPin,sameRuntimeConfiguration,type RuntimeConfigurationPin,type PinnedStudioCpuPreset as PinnedPreset} from './company-runtime-preset';
export type {StudioCpuPreset} from './company-runtime-preset';
import {transaction} from './db';
import {lockMembership,type Membership} from './auth';
import {fail,hashToken,id} from './security';
import {registerStudioHost,enrollStudioHost,hostingEncryptionConfigured,revokeUnsubmittedStudioHostProvisionCredentials} from './studio-hosting';
import {studioInferenceReserved} from './studio-inference';
import {studioHostProvisionPlanInput,studioHostProvisionStartInput,studioHostProvisionStopInput,type StudioHostProvision,type StudioHostProvisionPlan,type StudioHostProvisionReadiness} from './studio-host-provisioning-protocol';

export const STUDIO_CPU_IMAGE='node@sha256:e5a8dee7bc1e6a215d224a7ef8206f7e77271bc3cabd5febf2beafac0674f174';
const providerBase='https://api.runpod.io/v2',safeProviderId=/^[A-Za-z0-9_-]{1,100}$/;
type Row=Record<string,any>;
type Sealed={keyId:string;nonce:string;tag:string;ciphertext:string};
const plain=<T>(value:T):T=>JSON.parse(JSON.stringify(value));
function canonical(value:unknown):string{return Array.isArray(value)?'['+value.map(canonical).join(',')+']':value&&typeof value==='object'?'{'+Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+':'+canonical(v)).join(',')+'}':JSON.stringify(value);}
const digest=(value:unknown)=>hashToken(canonical(value));
const parse=<T>(schema:z.ZodType<T>,input:unknown)=>{const result=schema.safeParse(input);if(!result.success)fail(400,'Review the required host provisioning fields.','VALIDATION_ERROR');return result.data;};

/** Server-owned preset only. No endpoint, volume, image or command comes from a request. */
export function studioCpuPreset(companyId:string,settings:NodeJS.ProcessEnv=process.env):PinnedPreset{
 let parsed:unknown;try{parsed=JSON.parse(settings.COATRIA_MANAGED_CPU_PRESET||'');}catch{fail(503,'A reviewed managed CPU preset is not installed.','CPU_PRESET_UNAVAILABLE');}
 return parseStudioCpuPreset(parsed,companyId);
}
export async function loadStudioCpuPreset(db:PoolClient,companyId:string,settings:NodeJS.ProcessEnv=process.env):Promise<{preset:PinnedPreset;runtimeConfiguration:RuntimeConfigurationPin|null}>{
 const selected=await loadCompanyRuntimeConfiguration(db,companyId,'managed_agent');
 if(!selected)return {preset:studioCpuPreset(companyId,settings),runtimeConfiguration:null};
 if(!selected.enabled)fail(409,'The company CPU configuration is disabled, revoked or expired.','CPU_CONFIGURATION_INACTIVE');
 return {preset:selected.preset as PinnedPreset,runtimeConfiguration:runtimeConfigurationPin(selected)};
}
function cpuReadiness(preset:PinnedPreset|undefined,settings:NodeJS.ProcessEnv):StudioHostProvisionReadiness{
 const reasons:string[]=[];if(!preset)reasons.push('Install an active reviewed CPU release and a private retained volume for this company.');
 if(!settings.MANAGED_RUNPOD_API_KEY)reasons.push('Configure the server-only Runpod lifecycle credential.');
 if(!preset?.inference&&(!settings.COATRIA_MANAGED_RUNPOD_INFERENCE_KEY||settings.COATRIA_MANAGED_RUNPOD_INFERENCE_KEY===settings.MANAGED_RUNPOD_API_KEY))reasons.push('Configure a separate restricted Runpod inference credential; the lifecycle credential is never copied to a host.');
 if(!hostingEncryptionConfigured())reasons.push('Configure the managed-host encryption keyring.');
 return {ready:reasons.length===0,reasons};
}
export async function companyStudioCpuReadiness(db:PoolClient,companyId:string,settings:NodeJS.ProcessEnv=process.env){let preset:PinnedPreset|undefined;try{preset=(await loadStudioCpuPreset(db,companyId,settings)).preset;}catch{}return cpuReadiness(preset,settings);}
export function studioCpuReadiness(companyId:string,settings:NodeJS.ProcessEnv=process.env):StudioHostProvisionReadiness{
 let preset:PinnedPreset|undefined;try{preset=studioCpuPreset(companyId,settings);}catch{}return cpuReadiness(preset,settings);
}
function encryptionKey(keyId?:string){
 try{const ring=JSON.parse(process.env.COATRIA_HOSTING_KEYRING||''),selected=keyId??ring.activeKeyId,key=Buffer.from(ring.keys[selected]||'','base64');if(!/^[a-zA-Z0-9_-]{1,40}$/.test(selected)||key.length!==32||key.toString('base64')!==ring.keys[selected])throw Error();return{keyId:selected as string,key};}catch{fail(503,'Managed host encryption is unavailable.','HOSTING_KEY_UNAVAILABLE');}
}
const aad=(row:Row)=>Buffer.from(canonical({purpose:'managed-cpu-host-token-v1',companyId:row.company_id,provisionId:row.id,hostId:row.host_id,planHash:row.plan_hash}));
function sealToken(token:string,row:Row):Sealed{const{keyId,key}=encryptionKey(),nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,nonce);cipher.setAAD(aad(row));const ciphertext=Buffer.concat([cipher.update(token),cipher.final()]);return{keyId,nonce:nonce.toString('base64'),tag:cipher.getAuthTag().toString('base64'),ciphertext:ciphertext.toString('base64')};}
function openToken(row:Row){const sealed=row.sealed_host_token as Sealed;if(!sealed)fail(503,'The host enrollment credential is unavailable.','CPU_HOST_CREDENTIAL_UNAVAILABLE');const{key}=encryptionKey(sealed.keyId);try{const nonce=Buffer.from(sealed.nonce,'base64'),tag=Buffer.from(sealed.tag,'base64');if(nonce.length!==12||tag.length!==16)throw Error();const cipher=createDecipheriv('aes-256-gcm',key,nonce);cipher.setAAD(aad(row));cipher.setAuthTag(tag);const token=Buffer.concat([cipher.update(Buffer.from(sealed.ciphertext,'base64')),cipher.final()]).toString();if(!/^ch_[A-Za-z0-9_-]{43}$/.test(token))throw Error();return token;}catch{fail(503,'The host enrollment credential failed integrity verification.','CPU_HOST_CREDENTIAL_INTEGRITY');}}
async function lockCompany(client:PoolClient,companyId:string){await client.query('SELECT id FROM companies WHERE id=$1 FOR KEY SHARE',[companyId]);await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`studio-cpu-control:${companyId}`]);}
async function rowFor(client:PoolClient,companyId:string,provisionId:string){const row=(await client.query('SELECT * FROM studio_host_provisions WHERE company_id=$1 AND id=$2 FOR UPDATE',[companyId,id(provisionId)])).rows[0];if(!row)fail(404,'Managed CPU request not found.');return row;}
async function project(client:PoolClient,row:Row):Promise<StudioHostProvision>{const readiness=await companyStudioCpuReadiness(client,row.company_id);if(row.phase==='planned'&&+new Date(row.plan.reviewExpiresAt)<=Date.now())readiness.reasons.push('This review expired. Create a fresh plan.');if(row.error_code==='CPU_INFERENCE_UNAVAILABLE')readiness.reasons.push('The approved inference endpoint is disabled or its configured server/provider credential cannot read health. An operator must enable inference and create a fresh plan; this action never starts GPU capacity.');if(row.plan.reservation.previouslyReservedMicrousd+row.plan.reservation.cpuMicrousd>row.plan.reservation.companyLifetimeAllowanceMicrousd)readiness.reasons.push('The company CPU allowance is fully reserved.');try{const selected=await loadStudioCpuPreset(client,row.company_id);if(!sameRuntimeConfiguration(row.plan.runtimeConfiguration,selected.runtimeConfiguration)||digest(selected.preset)!==row.plan.preset.hash)readiness.reasons.push('The reviewed preset changed. Create a fresh plan.');}catch{/* The configuration reason is already included. */}readiness.ready=readiness.reasons.length===0;return plain({id:row.id,companyId:row.company_id,revision:row.revision,phase:row.phase,planHash:row.plan_hash,plan:row.plan,hostId:row.host_id,podId:row.pod_id,providerStatus:row.provider_status,expiresAt:row.expires_at,stopRequestedAt:row.stop_requested_at,submittedAt:row.submitted_at,lastReconciledAt:row.last_reconciled_at,createdAt:row.created_at,errorCode:row.error_code,readiness,computeStopped:row.phase==='stopped',credentialsRevoked:row.host_id?Boolean((await client.query("SELECT h.status='revoked' AND NOT EXISTS(SELECT 1 FROM studio_host_credentials c WHERE c.company_id=h.company_id AND c.host_id=h.id AND c.revoked_at IS NULL) AS revoked FROM studio_managed_hosts h WHERE h.company_id=$1 AND h.id=$2",[row.company_id,row.host_id])).rows[0]?.revoked):false,billingVerified:false});}
export async function getStudioHostProvision(client:PoolClient,companyId:string,provisionId:string){const row=(await client.query('SELECT * FROM studio_host_provisions WHERE company_id=$1 AND id=$2',[companyId,id(provisionId)])).rows[0];if(!row)fail(404,'Managed CPU request not found.');return await project(client,row);}
export async function listStudioHostProvisions(client:PoolClient,companyId:string){const rows=(await client.query('SELECT * FROM studio_host_provisions WHERE company_id=$1 ORDER BY created_at DESC LIMIT 50',[companyId])).rows;const provisions=[];for(const row of rows)provisions.push(await project(client,row));return{provisions,readiness:await companyStudioCpuReadiness(client,companyId)};}
async function reserved(client:PoolClient,companyId:string){return Number((await client.query('SELECT COALESCE(sum(amount_microusd),0) AS amount FROM studio_host_compute_reservations WHERE company_id=$1',[companyId])).rows[0].amount);}
async function installations(client:PoolClient,companyId:string,selected:Array<{installationId:string;revision:number}>,preset:PinnedPreset){
 const rows=(await client.query('SELECT p.id,p.revision,p.agent_id,p.plugin_id,p.manifest_version,a.name,a.status,a.capabilities,a.invocation_access,a.conversation_access,p.runtime_config,p.character FROM plugin_installations p JOIN agents a ON a.company_id=p.company_id AND a.id=p.agent_id WHERE p.company_id=$1 AND p.id=ANY($2::uuid[]) ORDER BY p.id',[companyId,selected.map(item=>item.installationId)])).rows;
 if(rows.length!==selected.length||rows.some(r=>selected.find(i=>i.installationId===r.id)?.revision!==r.revision))fail(409,'Selected installations changed. Create a new reviewed plan.','CPU_INSTALLATION_CHANGED');
 for(const r of rows){const config=r.runtime_config;if(r.status==='revoked'||r.plugin_id!=='runpod'||config.providerId!=='runpod'||config.modelId!==preset.modelId||['maxSteps','maxOutputTokens','maxTotalTokens','timeoutSeconds'].some(key=>!Number.isInteger(config[key])||config[key]<1||config[key]>preset[key as keyof PinnedPreset]!))fail(409,'Selected installations must use the preset Runpod model within its reviewed limits.','CPU_RUNTIME_UNSUPPORTED');}
 return plain(rows.map(r=>({installationId:r.id,revision:r.revision,agentId:r.agent_id,name:r.name,pluginId:r.plugin_id,manifestVersion:r.manifest_version,capabilities:r.capabilities,invocationAccess:r.invocation_access,conversationAccess:r.conversation_access,runtimeConfig:r.runtime_config,character:r.character})));
}
export async function createStudioHostProvisionPlan(client:PoolClient,member:Membership,input:unknown){
 const data=parse(studioHostProvisionPlanInput,input);await lockCompany(client,member.companyId);await lockMembership(client,member,true);const requestHash=digest(data);
 const old=(await client.query('SELECT * FROM studio_host_provisions WHERE company_id=$1 AND created_by=$2 AND client_id=$3',[member.companyId,member.userId,data.clientId])).rows[0];if(old){if(old.request_hash!==requestHash)fail(409,'This request ID was already used.','IDEMPOTENCY_CONFLICT');return{provision:await project(client,old),replayed:true};}
 const configuration=await loadStudioCpuPreset(client,member.companyId),preset=configuration.preset;
 await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`company-runtime-volume:${preset.company.volumeId}`]);
 if((await client.query("SELECT company_id FROM company_runtime_configurations WHERE worker_volume_id=$1 AND company_id<>$2 UNION ALL SELECT company_id FROM studio_host_provisions WHERE preset->'company'->>'volumeId'=$1 AND company_id<>$2 LIMIT 1",[preset.company.volumeId,member.companyId])).rowCount)fail(409,'Worker state volumes cannot be reassigned across companies.','CPU_VOLUME_COMPANY_CONFLICT');
 if(configuration.runtimeConfiguration&&Date.parse(configuration.runtimeConfiguration.expiresAt)<=Date.now()+data.durationMinutes*60000)fail(409,'The requested host lifetime exceeds the reviewed company runtime deadline.','CPU_CONFIGURATION_EXPIRED');
 const selected=await installations(client,member.companyId,data.installations,preset),previous=await reserved(client,member.companyId);
 const inference=preset.inference?{...preset.inference,previouslyReservedMicrousd:await studioInferenceReserved(client,member.companyId),billingVerified:false as const}:undefined;
 const plan:StudioHostProvisionPlan={version:1,...configuration.runtimeConfiguration?{runtimeConfiguration:configuration.runtimeConfiguration}:{},...(inference?{inference}:{}),companyId:member.companyId,durationMinutes:data.durationMinutes,reviewExpiresAt:new Date(Date.now()+600000).toISOString(),installations:selected,preset:{id:preset.id,hash:digest(preset),releaseCommit:preset.releaseCommit,bootstrapHash:preset.bootstrapHash,image:STUDIO_CPU_IMAGE,cpuTypeId:'cpu3c',vcpuCount:2,memoryGb:4,dataCenterId:preset.company.dataCenterId,volumeId:preset.company.volumeId,concurrency:1,modelId:preset.modelId,maxHourlyMicrousd:preset.maxHourlyMicrousd},reservation:{cpuMicrousd:Math.ceil(preset.maxHourlyMicrousd*(data.durationMinutes+5)/60),companyLifetimeAllowanceMicrousd:preset.company.lifetimeAllowanceMicrousd,previouslyReservedMicrousd:previous,inferenceIncluded:false,storageIncluded:false,billingCapGuaranteed:false},effects:{activateAgents:true,rotateCredentials:true,cancelPreviousRuns:true,startCpu:true,startGpu:false,independentHumanReviewPreserved:true}};
 const provisionId=randomUUID(),row=(await client.query('INSERT INTO studio_host_provisions(id,company_id,created_by,client_id,request_hash,plan,plan_hash,preset,pod_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[provisionId,member.companyId,member.userId,data.clientId,requestHash,JSON.stringify(plan),digest(plan),JSON.stringify(preset),'coatria-cpu-'+provisionId])).rows[0];return{provision:await project(client,row),replayed:false};
}
async function replay(client:PoolClient,member:Membership,clientId:string,requestHash:string){const old=(await client.query('SELECT * FROM studio_host_provision_requests WHERE company_id=$1 AND user_id=$2 AND client_id=$3',[member.companyId,member.userId,clientId])).rows[0];if(old&&old.request_hash!==requestHash)fail(409,'This request ID was already used.','IDEMPOTENCY_CONFLICT');return old;}
async function receipt(client:PoolClient,member:Membership,row:Row,operation:string,clientId:string,requestHash:string){await client.query('INSERT INTO studio_host_provision_requests(company_id,user_id,client_id,provision_id,operation,request_hash,response) VALUES($1,$2,$3,$4,$5,$6,$7)',[member.companyId,member.userId,clientId,row.id,operation,requestHash,JSON.stringify({provisionId:row.id,hostId:row.host_id,acceptedRevision:row.revision})]);}
/** Transaction only. After commit the route must invoke reconcile; cron resumes it. */
export async function startStudioHostProvision(client:PoolClient,member:Membership,provisionId:string,input:unknown){
 const data=parse(studioHostProvisionStartInput,input),requestHash=digest({provisionId,...data});await lockCompany(client,member.companyId);await lockMembership(client,member,true);const old=await replay(client,member,data.clientId,requestHash);if(old)return{provision:await project(client,await rowFor(client,member.companyId,old.provision_id)),replayed:true};
 const row=await rowFor(client,member.companyId,provisionId);if(row.phase!=='planned'||row.revision!==data.revision||row.plan_hash!==data.planHash||digest(row.plan)!==row.plan_hash)fail(409,'The exact reviewed plan is required.','CPU_PLAN_CONFLICT');
 if(+new Date(row.plan.reviewExpiresAt)<=Date.now())fail(409,'This review expired. Create a fresh plan.','CPU_PLAN_EXPIRED');
 const configuration=await loadStudioCpuPreset(client,member.companyId),current=configuration.preset;if(!sameRuntimeConfiguration(row.plan.runtimeConfiguration,configuration.runtimeConfiguration)||digest(current)!==row.plan.preset.hash||digest(row.preset)!==row.plan.preset.hash)fail(409,'The approved compute preset changed. Create a fresh plan.','CPU_PRESET_CHANGED');
 const ready=await companyStudioCpuReadiness(client,member.companyId);if(!ready.ready)fail(503,ready.reasons.join(' '),'CPU_CONFIGURATION_REQUIRED');
 // Stabilize configuration in the same order used by host enrollment: host
 // control, sorted principals, sorted agents, then plugin configuration reads.
 await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`studio-host-control:${member.companyId}`]);
 const agentIds=row.plan.installations.map((item:any)=>item.agentId).sort();
 const sponsors=(await client.query('SELECT created_by FROM agents WHERE company_id=$1 AND id=ANY($2::uuid[])',[member.companyId,agentIds])).rows.map(item=>item.created_by);
 await client.query('SELECT user_id FROM memberships WHERE company_id=$1 AND user_id=ANY($2::uuid[]) ORDER BY user_id FOR SHARE',[member.companyId,[...new Set([member.userId,...sponsors])].sort()]);
 await client.query('SELECT id FROM agents WHERE company_id=$1 AND id=ANY($2::uuid[]) ORDER BY id FOR UPDATE',[member.companyId,agentIds]);
 const selected=await installations(client,member.companyId,row.plan.installations,current);if(digest(selected)!==digest(row.plan.installations))fail(409,'The reviewed agent configuration changed.','CPU_INSTALLATION_CHANGED');
 if((await client.query("SELECT id FROM studio_host_provisions WHERE company_id=$1 AND phase IN ('approved','submitting','uncertain','provisioning','running','stopping','needs_attention')",[member.companyId])).rowCount)fail(409,'Reconcile or stop the previous CPU host before starting another.','CPU_ALREADY_PENDING');
 if(await reserved(client,member.companyId)+row.plan.reservation.cpuMicrousd>current.company.lifetimeAllowanceMicrousd)fail(409,'The company CPU allowance is fully reserved. An operator must review actual charges before raising it.','CPU_ALLOWANCE_EXHAUSTED');
 if(current.inference){const minimumReservation=Math.ceil(current.inference.maxHourlyMicrousd*(Math.min(current.timeoutSeconds,...selected.map((item:any)=>Number(item.runtimeConfig.timeoutSeconds)))+60)/3600);if(await studioInferenceReserved(client,member.companyId)+minimumReservation>current.inference.lifetimeAllowanceMicrousd)fail(409,'The company inference allowance cannot reserve even the first model step. An operator must review usage before raising it.','INFERENCE_ALLOWANCE_EXHAUSTED');}
 const expiresAt=new Date(Date.now()+row.plan.durationMinutes*60000).toISOString();
 if(configuration.runtimeConfiguration&&Date.parse(expiresAt)>Date.parse(configuration.runtimeConfiguration.expiresAt))fail(409,'The host lifetime exceeds the reviewed company runtime deadline.','CPU_CONFIGURATION_EXPIRED');
 const registered=await registerStudioHost(client,member,{clientId:randomUUID(),name:'Managed CPU '+row.id.slice(0,8),maxAgents:selected.length,providerIds:['runpod'],expiresAt});if(!registered.hostToken)throw Error('Fresh host enrollment required.');
 await enrollStudioHost(client,member,registered.host.id,{clientId:randomUUID(),revision:registered.host.revision,activateAgents:true,installations:selected.map((item:any)=>({installationId:item.installationId,revision:item.revision}))});
 row.host_id=registered.host.id;const sealed=sealToken(registered.hostToken,row);
 await client.query('INSERT INTO studio_host_compute_reservations(company_id,provision_id,amount_microusd,approved_by) VALUES($1,$2,$3,$4)',[member.companyId,row.id,row.plan.reservation.cpuMicrousd,member.userId]);
 const saved=(await client.query("UPDATE studio_host_provisions SET phase='approved',host_id=$3,sealed_host_token=$4,expires_at=$5,revision=revision+1,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2 RETURNING *",[member.companyId,row.id,row.host_id,JSON.stringify(sealed),expiresAt])).rows[0];await receipt(client,member,saved,'start',data.clientId,requestHash);return{provision:await project(client,saved),replayed:false};
}
/** Stops paid compute independently. A failed, never-submitted start also
 * revokes its unused enrollment during reconciliation. Volumes are retained. */
export async function stopStudioHostProvision(client:PoolClient,member:Membership,provisionId:string,input:unknown){
 const data=parse(studioHostProvisionStopInput,input),requestHash=digest({provisionId,...data});await lockCompany(client,member.companyId);await lockMembership(client,member,true);const old=await replay(client,member,data.clientId,requestHash);if(old)return{provision:await project(client,await rowFor(client,member.companyId,old.provision_id)),replayed:true};const row=await rowFor(client,member.companyId,provisionId);
 if(row.revision!==data.revision)fail(409,'The CPU host changed. Reload before stopping it.','CPU_REVISION_CONFLICT');if(row.phase==='planned')fail(409,'This plan has not started compute.','CPU_NOT_STARTED');
 const saved=(await client.query("UPDATE studio_host_provisions SET stop_requested_at=COALESCE(stop_requested_at,clock_timestamp()),revision=revision+1,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2 RETURNING *",[member.companyId,provisionId])).rows[0];await receipt(client,member,saved,'stop',data.clientId,requestHash);return{provision:await project(client,saved),replayed:false};
}

async function currentConfiguration(client:PoolClient,row:Row){
 try{const selected=await loadStudioCpuPreset(client,row.company_id);return digest(row.plan)===row.plan_hash&&sameRuntimeConfiguration(row.plan.runtimeConfiguration,selected.runtimeConfiguration)&&digest(selected.preset)===row.plan.preset.hash&&digest(row.preset)===row.plan.preset.hash;}
 catch{return false;}
}
export type StudioCpuDependencies={fetch?:typeof fetch;now?:()=>number;transaction?:typeof transaction};
async function providerRequest(path:string,method:string,payload:unknown,transport:typeof fetch){
 const token=process.env.MANAGED_RUNPOD_API_KEY;if(!token)fail(503,'The server Runpod lifecycle credential is unavailable.','CPU_CONFIGURATION_REQUIRED');
 const response=await transport(providerBase+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(payload===undefined?{}:{body:JSON.stringify(payload)}),redirect:'error',cache:'no-store',signal:AbortSignal.timeout(10000)});
 return readProviderJson(response);
}
async function readProviderJson(response:Response){if(!response.ok)fail(503,'Runpod did not confirm the compute operation.','CPU_PROVIDER_UNCONFIRMED');const reader=response.body?.getReader();if(!reader)fail(503,'Runpod returned an empty result.','CPU_PROVIDER_UNCONFIRMED');const chunks:Uint8Array[]=[];let size=0;for(;;){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>2000000){void reader.cancel().catch(()=>{});fail(503,'Runpod returned an oversized result.','CPU_PROVIDER_UNCONFIRMED');}chunks.push(part.value);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{fail(503,'Runpod returned an invalid result.','CPU_PROVIDER_UNCONFIRMED');}}
async function preflight(p:PinnedPreset,transport:typeof fetch){
 const cpu=await providerRequest('/catalog/cpus/cpu3c','GET',undefined,transport),volume=await providerRequest('/network-volumes/'+p.company.volumeId,'GET',undefined,transport);
 if(cpu.id!=='cpu3c'||cpu.ramGbPerVcpu!==2||cpu.vcpu?.min>2||cpu.vcpu?.max<2||!Number.isFinite(cpu.price?.securePerVcpu)||cpu.price.securePerVcpu<=0||Math.ceil(cpu.price.securePerVcpu*2*1000000)>p.maxHourlyMicrousd)fail(409,'The fixed CPU SKU or current price does not match the reviewed ceiling.','CPU_CATALOG_CHANGED');
 if(volume.id!==p.company.volumeId||volume.dataCenter!==p.company.dataCenterId)fail(409,'The retained volume does not match this company and region.','CPU_VOLUME_CHANGED');
 // Read-only readiness. A CPU approval never changes the separately managed
 // GPU endpoint's worker floor/ceiling, and health does not submit inference.
 try{const endpoint=await providerRequest('/serverless/'+p.endpointId,'GET',undefined,transport);if(endpoint.id!==p.endpointId||!Number.isInteger(endpoint.workers?.max)||endpoint.workers.max<1)throw Error();const response=await transport('https://api.runpod.ai/v2/'+p.endpointId+'/health',{method:'GET',headers:{Authorization:'Bearer '+(p.inference?process.env.MANAGED_RUNPOD_API_KEY:process.env.COATRIA_MANAGED_RUNPOD_INFERENCE_KEY)},redirect:'error',cache:'no-store',signal:AbortSignal.timeout(10000)});const health=await readProviderJson(response);if(!health||typeof health.workers!=='object'||!health.workers)throw Error();}catch{fail(503,'The approved inference endpoint is disabled or its configured server/provider credential cannot read health.','CPU_INFERENCE_UNAVAILABLE');}
}
function payload(row:Row){const p=row.preset as PinnedPreset,inference=process.env.COATRIA_MANAGED_RUNPOD_INFERENCE_KEY;if(!p.inference&&(!inference||inference===process.env.MANAGED_RUNPOD_API_KEY))fail(503,'A separate restricted inference credential is required.','CPU_CONFIGURATION_REQUIRED');return{name:row.pod_name,cloud:'SECURE',image:STUDIO_CPU_IMAGE,args:p.bootstrapArgs,disk:10,cpu:{id:'cpu3c',vcpuCount:2},dataCenterIds:[p.company.dataCenterId],mounts:{network:[{volumeId:p.company.volumeId,path:'/state'}]},ports:[],startSsh:false,startJupyter:false,env:{COATRIA_HOST_TOKEN:openToken(row),COATRIA_URL:'https://coatria.com',COATRIA_HOST_ID:row.host_id,COATRIA_HOST_COMPANY_ID:row.company_id,COATRIA_HOST_MODEL_ID:p.modelId,COATRIA_HOST_CONCURRENCY:'1',COATRIA_HOST_EXPIRES_AT:new Date(row.expires_at).toISOString(),...(p.inference?{COATRIA_INFERENCE_MODE:'coatria_broker_v1'}:{RUNPOD_API_KEY:inference!,COATRIA_RUNPOD_ENDPOINT_ID:p.endpointId}),COATRIA_MAX_STEPS:String(p.maxSteps),COATRIA_MAX_OUTPUT_TOKENS:String(p.maxOutputTokens),COATRIA_MAX_TOTAL_TOKENS:String(p.maxTotalTokens),COATRIA_TIMEOUT_SECONDS:String(p.timeoutSeconds)}};}
const hostEnvironmentKeys=['COATRIA_HOST_TOKEN','COATRIA_URL','COATRIA_HOST_ID','COATRIA_HOST_COMPANY_ID','COATRIA_HOST_MODEL_ID','COATRIA_HOST_CONCURRENCY','COATRIA_HOST_EXPIRES_AT','RUNPOD_API_KEY','COATRIA_RUNPOD_ENDPOINT_ID','COATRIA_MAX_STEPS','COATRIA_MAX_OUTPUT_TOKENS','COATRIA_MAX_TOTAL_TOKENS','COATRIA_TIMEOUT_SECONDS'];
function verifyPod(row:Row,pod:Row){const p=row.preset as PinnedPreset,environment=row.expected_environment_hashes,expectedKeys=p.inference?[...hostEnvironmentKeys.filter(key=>!['RUNPOD_API_KEY','COATRIA_RUNPOD_ENDPOINT_ID'].includes(key)),'COATRIA_INFERENCE_MODE']:hostEnvironmentKeys;
 const envMatches=environment&&typeof environment==='object'&&Object.keys(environment).length===expectedKeys.length&&Object.keys(pod.env??{}).length===expectedKeys.length&&expectedKeys.every(key=>typeof pod.env?.[key]==='string'&&hashToken(pod.env[key])===environment[key]);
 if(!safeProviderId.test(pod.id)||row.pod_id&&pod.id!==row.pod_id||pod.name!==row.pod_name||pod.image!==STUDIO_CPU_IMAGE||hashToken(pod.args||'')!==p.bootstrapHash||pod.disk!==10||pod.cpu?.id!=='cpu3c'||pod.cpu?.vcpuCount!==2||pod.cpu?.memory!==4||pod.gpu||pod.cloud!=='SECURE'||pod.dataCenterId&&pod.dataCenterId!==p.company.dataCenterId||!Array.isArray(pod.ports)||pod.ports.length||pod.mounts?.persistent||pod.mounts?.network?.length!==1||pod.mounts.network[0].volumeId!==p.company.volumeId||pod.mounts.network[0].path!=='/state'||!envMatches||!['PROVISIONING','STARTING','RUNNING','EXITED','TERMINATED','ERROR'].includes(pod.status))fail(409,'Provider resource identity no longer matches this reviewed host. An operator must reconcile it.','CPU_IDENTITY_MISMATCH');return pod;}
async function discover(row:Row,transport:typeof fetch){
 let cursor:string|undefined;const matches:Row[]=[],seen=new Set<string>();for(let page=0;page<10;page++){const result=await providerRequest('/pods?limit=100'+(cursor?'&cursor='+encodeURIComponent(cursor):''),'GET',undefined,transport);if(!Array.isArray(result.pods)||typeof result.pagination?.hasNextPage!=='boolean')fail(503,'Runpod pod discovery was incomplete.','CPU_DISCOVERY_INCOMPLETE');matches.push(...result.pods.filter((pod:Row)=>pod.name===row.pod_name));if(!result.pagination.hasNextPage){if(matches.length>1)fail(409,'Multiple resources match the reserved identity. Operator reconciliation is required.','CPU_DUPLICATE_IDENTITY');return matches[0]?verifyPod(row,matches[0]):null;}cursor=result.pagination.nextCursor;if(typeof cursor!=='string'||!cursor||cursor.length>1000||seen.has(cursor))fail(503,'Runpod pod discovery was incomplete.','CPU_DISCOVERY_INCOMPLETE');seen.add(cursor);}fail(503,'Runpod pod discovery exceeded its bounded scan.','CPU_DISCOVERY_INCOMPLETE');
}
/** One bounded network step. The committed submitted_at fence is never reset:
 * an uncertain /pods create can only be discovered, never submitted a second time.
 */
export async function reconcileStudioHostProvision(provisionId:string,dependencies:StudioCpuDependencies={}){
 id(provisionId);const tx=dependencies.transaction??transaction,baseTransport=dependencies.fetch??fetch,now=dependencies.now??Date.now,leaseId=randomUUID(),deadline=AbortSignal.timeout(25000);
 const transport:typeof fetch=(url,init)=>baseTransport(url,{...init,signal:AbortSignal.any([deadline,...(init?.signal?[init.signal]:[])])});
 const row=await tx(async client=>{
  const found=(await client.query('SELECT company_id FROM studio_host_provisions WHERE id=$1',[provisionId])).rows[0];if(!found)fail(404,'Managed CPU request not found.');await lockCompany(client,found.company_id);const r=await rowFor(client,found.company_id,provisionId);
  if(['planned','stopped'].includes(r.phase)||r.lease_expires_at&&+new Date(r.lease_expires_at)>now())return null;
  if(r.phase==='failed'){
   // A failed preflight must never become a paid retry. Only the durable stop
   // request and both absence-of-submission fences permit local-only cleanup.
   if(!r.stop_requested_at||r.submitted_at||r.pod_id)return null;
   await revokeUnsubmittedStudioHostProvisionCredentials(client,r.company_id,r.id);
   await client.query("UPDATE studio_host_provisions SET phase='stopped',revision=revision+1,last_reconciled_at=clock_timestamp(),updated_at=clock_timestamp(),lease_id=NULL,lease_expires_at=NULL WHERE company_id=$1 AND id=$2",[r.company_id,r.id]);
   return {...r,cleanupCompleted:true};
  }
  const sponsor=(await client.query("SELECT user_id FROM memberships WHERE company_id=$1 AND user_id=$2 AND role IN ('owner','admin') FOR SHARE",[r.company_id,r.created_by])).rowCount,host=(await client.query('SELECT h.status,h.expires_at,m.role FROM studio_managed_hosts h LEFT JOIN memberships m ON m.company_id=h.company_id AND m.user_id=h.created_by WHERE h.company_id=$1 AND h.id=$2',[r.company_id,r.host_id])).rows[0];if(!sponsor||!host||!['owner','admin'].includes(host.role)||host.status!=='active'||+new Date(host.expires_at)<=now()||+new Date(r.expires_at)<=now()||!await currentConfiguration(client,r))r.stop_requested_at=r.stop_requested_at??new Date(now());await client.query('UPDATE studio_host_provisions SET lease_id=$3,lease_expires_at=clock_timestamp()+interval \'45 seconds\',stop_requested_at=$4 WHERE company_id=$1 AND id=$2',[r.company_id,r.id,leaseId,r.stop_requested_at]);return r;
 });
 if(!row)return{skipped:true};
 if(row.cleanupCompleted)return{provision:await tx(client=>getStudioHostProvision(client,row.company_id,row.id)),skipped:false};
 const save=async(changes:{phase:string;podId?:string;providerStatus?:string;errorCode?:string|null})=>tx(async client=>{await lockCompany(client,row.company_id);const r=await rowFor(client,row.company_id,row.id);if(r.lease_id!==leaseId)return{skipped:true};const saved=(await client.query('UPDATE studio_host_provisions SET phase=$3,pod_id=COALESCE($4,pod_id),provider_status=COALESCE($5,provider_status),error_code=$6,revision=revision+1,last_reconciled_at=clock_timestamp(),updated_at=clock_timestamp(),lease_id=NULL,lease_expires_at=NULL WHERE company_id=$1 AND id=$2 RETURNING *',[r.company_id,r.id,r.stop_requested_at&&changes.phase!=='stopped'?(r.submitted_at?'stopping':'stopped'):changes.phase,changes.podId??null,changes.providerStatus??null,changes.errorCode??null])).rows[0];return{provision:await project(client,saved),skipped:false};});
 const mustStop=()=>tx(async client=>{await lockCompany(client,row.company_id);const current=await rowFor(client,row.company_id,row.id);if(current.lease_id!==leaseId)fail(409,'The host reconciliation lease changed.','CPU_LEASE_CHANGED');const sponsor=(await client.query("SELECT user_id FROM memberships WHERE company_id=$1 AND user_id=$2 AND role IN ('owner','admin') FOR SHARE",[row.company_id,row.created_by])).rowCount;const host=(await client.query('SELECT h.status,h.expires_at,m.role FROM studio_managed_hosts h LEFT JOIN memberships m ON m.company_id=h.company_id AND m.user_id=h.created_by WHERE h.company_id=$1 AND h.id=$2',[row.company_id,row.host_id])).rows[0];const stop=!!current.stop_requested_at||!sponsor||!host||!['owner','admin'].includes(host.role)||host.status!=='active'||+new Date(host.expires_at)<=now()||+new Date(current.expires_at)<=now()||!await currentConfiguration(client,current);if(stop)await client.query('UPDATE studio_host_provisions SET stop_requested_at=COALESCE(stop_requested_at,clock_timestamp()) WHERE company_id=$1 AND id=$2',[row.company_id,row.id]);return stop;});
 const finishPod=async(pod:Row)=>{if(['EXITED','TERMINATED'].includes(pod.status))return save({phase:'stopped',podId:pod.id,providerStatus:pod.status});if(await mustStop()){if(!Array.isArray(pod.actions)||!pod.actions.includes('stop'))return save({phase:'stopping',podId:pod.id,providerStatus:pod.status,errorCode:'CPU_STOP_PENDING'});await providerRequest('/pods/'+pod.id+'/action','POST',{action:'stop'},transport);return save({phase:'stopping',podId:pod.id,providerStatus:pod.status});}return save({phase:pod.status==='RUNNING'?'running':pod.status==='ERROR'?'needs_attention':'provisioning',podId:pod.id,providerStatus:pod.status,errorCode:pod.status==='ERROR'?'CPU_PROVIDER_ERROR':null});};
 let submitted=Boolean(row.submitted_at);
 try{
  if(!submitted){
   if(row.stop_requested_at||+new Date(row.expires_at)<=now())return await save({phase:'stopped'});
   await tx(async client=>{await lockCompany(client,row.company_id);const current=await rowFor(client,row.company_id,row.id);if(!await currentConfiguration(client,current))fail(409,'The preset changed before compute submission.','CPU_PRESET_CHANGED');const ready=await companyStudioCpuReadiness(client,row.company_id);if(!ready.ready)fail(503,ready.reasons.join(' '),'CPU_CONFIGURATION_REQUIRED');});await preflight(row.preset,transport);const request=payload(row);
   row.expected_environment_hashes=Object.fromEntries(Object.entries(request.env).map(([key,value])=>[key,hashToken(value)]));
   const authorized=await tx(async client=>{await lockCompany(client,row.company_id);const r=await rowFor(client,row.company_id,row.id);if(r.lease_id!==leaseId||r.submitted_at)return false;const live=(await client.query("SELECT h.id FROM studio_managed_hosts h JOIN memberships m ON m.company_id=h.company_id AND m.user_id=h.created_by WHERE h.company_id=$1 AND h.id=$2 AND h.status='active' AND h.expires_at>clock_timestamp() AND m.role IN ('owner','admin') FOR SHARE OF h,m",[r.company_id,r.host_id])).rowCount;if(r.stop_requested_at||!live||+new Date(r.expires_at)<=now()||!await currentConfiguration(client,r))return false;const currentBindings=(await client.query("SELECT count(*)::int AS count FROM studio_host_credentials c JOIN plugin_installations p ON p.company_id=c.company_id AND p.id=c.installation_id AND p.agent_id=c.agent_id JOIN agents a ON a.company_id=c.company_id AND a.id=c.agent_id JOIN memberships m ON m.company_id=a.company_id AND m.user_id=a.created_by WHERE c.company_id=$1 AND c.host_id=$2 AND c.installation_id=ANY($3::uuid[]) AND c.revoked_at IS NULL AND c.expires_at>clock_timestamp() AND p.revision=c.installation_revision AND a.token_hash=c.token_hash AND a.status='active' AND a.expires_at>clock_timestamp() AND m.role IN ('owner','admin') AND p.runtime_config=c.configuration->'runtimeConfig' AND p.character=c.configuration->'character' AND a.capabilities=c.configuration->'capabilities' AND a.invocation_access=c.configuration->>'invocationAccess' AND a.conversation_access=c.configuration->>'conversationAccess'",[r.company_id,r.host_id,r.plan.installations.map((item:any)=>item.installationId)])).rows[0].count;if(currentBindings!==r.plan.installations.length)fail(409,'Enrolled agents changed before CPU submission. Review a fresh plan.','CPU_INSTALLATION_CHANGED');await client.query("UPDATE studio_host_provisions SET phase='submitting',submitted_at=clock_timestamp(),expected_environment_hashes=$3,revision=revision+1 WHERE company_id=$1 AND id=$2",[r.company_id,r.id,JSON.stringify(row.expected_environment_hashes)]);return true;});
   if(!authorized)return await save({phase:'stopped'});submitted=true;const pod=verifyPod(row,await providerRequest('/pods','POST',request,transport));return await finishPod(pod);
  }
  const pod=row.pod_id?verifyPod(row,await providerRequest('/pods/'+row.pod_id,'GET',undefined,transport)):await discover(row,transport);if(!pod)return await save({phase:'uncertain',errorCode:'CPU_CREATE_UNCERTAIN'});
  return await finishPod(pod);
 }catch(error){const code=typeof(error as any)?.code==='string'&&(error as any).code.startsWith('CPU_')?(error as any).code:'CPU_PROVIDER_UNCONFIRMED';return await save({phase:submitted?['CPU_IDENTITY_MISMATCH','CPU_DUPLICATE_IDENTITY'].includes(code)?'needs_attention':row.stop_requested_at?'stopping':'uncertain':'failed',errorCode:code});}
}
export async function reconcileStudioHostProvisions(limit=5,dependencies:StudioCpuDependencies={}){
 const tx=dependencies.transaction??transaction;
 // Shutdowns must not wait behind a fleet of ordinary polls. Within each class,
 // least-recently reconciled rows rotate first; UUID resolves timestamp ties.
 // A statement-stable clock gives every row the same expiry cutoff.
 const ids=await tx(async client=>(await client.query("SELECT id FROM studio_host_provisions WHERE (phase IN ('approved','submitting','uncertain','provisioning','running','stopping','needs_attention') OR (phase='failed' AND stop_requested_at IS NOT NULL AND submitted_at IS NULL AND pod_id IS NULL)) AND (lease_expires_at IS NULL OR lease_expires_at<=clock_timestamp()) ORDER BY CASE WHEN stop_requested_at IS NOT NULL OR expires_at<=statement_timestamp() THEN 0 ELSE 1 END,last_reconciled_at NULLS FIRST,id LIMIT $1",[Math.min(10,Math.max(1,limit))])).rows.map(row=>row.id));
 const results=[];for(const provisionId of ids)results.push(await reconcileStudioHostProvision(provisionId,dependencies));return{results};
}
