import {z} from 'zod';
import {studioHostProvisionPlanInput,studioHostProvisionStartInput,studioHostProvisionStopInput} from './studio-host-provisioning-protocol';
type Schema=Record<string,unknown>;
const str:Schema={type:'string'},uuid:Schema={type:'string',format:'uuid'},date:Schema={type:'string',format:'date-time'},integer:Schema={type:'integer'},bool:Schema={type:'boolean'},no:Schema={const:false},yes:Schema={const:true};
const object=(properties:Record<string,Schema>):Schema=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const array=(items:Schema,maxItems=100):Schema=>({type:'array',items,maxItems}),nullable=(item:Schema):Schema=>({anyOf:[item,{type:'null'}]}),ref=(name:string)=>({$ref:'#/components/schemas/'+name});
const readiness=object({ready:bool,reasons:array(str,10)});
const plan=object({version:{const:1},companyId:uuid,durationMinutes:{type:'integer',enum:[15,20,30,60]},reviewExpiresAt:date,installations:array(object({installationId:uuid,revision:integer,agentId:uuid,name:str,pluginId:str,manifestVersion:str,capabilities:array(str,50),invocationAccess:str,conversationAccess:{description:'Exact existing conversation grants preserved by enrollment.'},runtimeConfig:ref('PluginRuntimeConfig'),character:ref('AgentCharacter')}),11),preset:object({id:str,hash:str,releaseCommit:str,bootstrapHash:str,image:str,cpuTypeId:{const:'cpu3c'},vcpuCount:{const:2},memoryGb:{const:4},dataCenterId:str,volumeId:str,concurrency:{const:1},modelId:str,maxHourlyMicrousd:integer}),reservation:object({cpuMicrousd:integer,companyLifetimeAllowanceMicrousd:integer,previouslyReservedMicrousd:integer,inferenceIncluded:no,storageIncluded:no,billingCapGuaranteed:no}),effects:object({activateAgents:yes,rotateCredentials:yes,cancelPreviousRuns:yes,startCpu:yes,startGpu:no,independentHumanReviewPreserved:yes})});
plan.properties={...(plan.properties as Record<string,Schema>),inference:object({mode:{const:'coatria_broker_v1'},maxJobs:{type:'integer',minimum:1,maximum:100},maxHourlyMicrousd:integer,lifetimeAllowanceMicrousd:integer,previouslyReservedMicrousd:integer,billingVerified:no})};
const provision=object({id:uuid,companyId:uuid,revision:integer,phase:{type:'string',enum:['planned','approved','submitting','uncertain','provisioning','running','stopping','stopped','failed','needs_attention']},planHash:str,plan:ref('StudioHostProvisionPlan'),hostId:nullable(uuid),podId:nullable(str),providerStatus:nullable(str),expiresAt:nullable(date),stopRequestedAt:nullable(date),submittedAt:nullable(date),lastReconciledAt:nullable(date),createdAt:date,errorCode:nullable(str),readiness:ref('StudioHostProvisionReadiness'),computeStopped:bool,credentialsRevoked:no,billingVerified:no});
export const studioHostProvisioningSchemas:Record<string,Schema>={StudioHostProvisionPlan:plan,StudioHostProvision:provision,StudioHostProvisionReadiness:readiness};
const success=(schema:Schema)=>({description:'Reviewed operation and current provider observation; no secrets.',content:{'application/json':{schema}}});
function operation(operationId:string,summary:string,result:Schema,input?:z.ZodType,item=false,creation=false){return{operationId,summary,description:'Human owner or administrator only. A plan starts nothing. Start commits the exact reviewed plan, reserves a non-resetting company CPU allowance, enrolls and activates the selected agents, then reconciles one fixed Runpod CPU Pod. Submission uncertainty is discovered without a second create. Stop affects CPU compute only; host revocation is separate. CPU reservations exclude retained storage and inference. An optional exact coatria_broker_v1 plan adds a separate lifetime inference allowance and per-host model-step limit, without copying provider credentials into the CPU. These reservations are not a provider billing cap. No provider credentials, arbitrary commands, destinations, volumes or runtime configuration are accepted from a caller.',security:[{sessionCookie:[]}],'x-coatria-roles':['owner','admin'],parameters:[{name:'companyId',in:'path',required:true,schema:uuid},...(item?[{name:'provisionId',in:'path',required:true,schema:uuid}]:[]),...(input?[{name:'Origin',in:'header',required:true,schema:{type:'string',format:'uri'}}]:[])],...(input?{requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(input,{io:'input',unrepresentable:'any'})}}}}:{}),responses:{'200':success(result),...(creation?{'201':success(result)}:{}),...Object.fromEntries(['400','401','403','404','409','413','415','429','500','503'].map(status=>[status,{description:'Validation, authority, stale plan, budget, or configuration failure.',content:{'application/json':{schema:ref('Error')}}}]))}};}
const base='/api/companies/{companyId}/studio/host-provisions',single=object({provision:ref('StudioHostProvision')}),mutation=object({provision:ref('StudioHostProvision'),replayed:bool});
export const studioHostProvisioningPaths:Record<string,unknown>={
 [base]:{get:operation('listStudioHostProvisions','List the latest 50 managed CPU operations and current configuration readiness',object({provisions:array(ref('StudioHostProvision'),50),readiness:ref('StudioHostProvisionReadiness')})),post:operation('planStudioHostProvision','Review an exact bounded CPU host and selected agent configuration',mutation,studioHostProvisionPlanInput,false,true)},
 [base+'/{provisionId}']:{get:operation('getStudioHostProvision','Read the current state of an exact company CPU operation',single,undefined,true)},
 [base+'/{provisionId}/start']:{post:operation('startStudioHostProvision','Approve exact charges and agent activation, then submit a bounded CPU host',mutation,studioHostProvisionStartInput,true)},
 [base+'/{provisionId}/stop']:{post:operation('stopStudioHostProvision','Request and reconcile CPU stop without revoking host identity or deleting storage',mutation,studioHostProvisionStopInput,true)},
 [base+'/{provisionId}/reconcile']:{post:operation('reconcileStudioHostProvision','Check one provider operation without duplicating an uncertain create',single,z.object({clientId:z.string().uuid()}).strict(),true)},
};
