import {z} from 'zod';
import {studioHostProvisionPlanInput,studioHostProvisionStartInput,studioHostProvisionStopInput} from './studio-host-provisioning-protocol';
import {PROVIDER_READINESS_CODES} from './studio-host-readiness';
type Schema=Record<string,unknown>;
const str:Schema={type:'string'},uuid:Schema={type:'string',format:'uuid'},date:Schema={type:'string',format:'date-time'},integer:Schema={type:'integer'},bool:Schema={type:'boolean'},no:Schema={const:false},yes:Schema={const:true};
const object=(properties:Record<string,Schema>):Schema=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const array=(items:Schema,maxItems=100):Schema=>({type:'array',items,maxItems}),nullable=(item:Schema):Schema=>({anyOf:[item,{type:'null'}]}),ref=(name:string)=>({$ref:'#/components/schemas/'+name});
const readiness=object({ready:bool,reasons:array(str,10)});
const plan=object({version:{const:1},companyId:uuid,durationMinutes:{type:'integer',enum:[15,20,30,60]},reviewExpiresAt:date,installations:array(object({installationId:uuid,revision:integer,agentId:uuid,name:str,pluginId:str,manifestVersion:str,capabilities:array(str,50),invocationAccess:str,conversationAccess:{description:'Exact existing conversation grants preserved by enrollment.'},runtimeConfig:ref('PluginRuntimeConfig'),character:ref('AgentCharacter')}),11),preset:object({id:str,hash:str,releaseCommit:str,bootstrapHash:str,image:str,cpuTypeId:{const:'cpu3c'},vcpuCount:{const:2},memoryGb:{const:4},dataCenterId:str,volumeId:str,concurrency:{const:1},modelId:str,maxHourlyMicrousd:integer}),reservation:object({cpuMicrousd:integer,companyLifetimeAllowanceMicrousd:integer,previouslyReservedMicrousd:integer,inferenceIncluded:no,storageIncluded:no,billingCapGuaranteed:no}),effects:object({activateAgents:yes,rotateCredentials:yes,cancelPreviousRuns:yes,startCpu:yes,startGpu:no,independentHumanReviewPreserved:yes})});
plan.properties={...(plan.properties as Record<string,Schema>),inference:object({mode:{const:'coatria_broker_v1'},maxJobs:{type:'integer',minimum:1,maximum:100},maxHourlyMicrousd:integer,lifetimeAllowanceMicrousd:integer,previouslyReservedMicrousd:integer,billingVerified:no})};
plan.properties={...(plan.properties as Record<string,Schema>),runtimeConfiguration:object({configurationId:uuid,selectionRevision:{type:'integer',minimum:1},configurationHash:{type:'string',pattern:'^[a-f0-9]{64}$'},expiresAt:date})};
const provision=object({id:uuid,companyId:uuid,revision:integer,phase:{type:'string',enum:['planned','approved','submitting','uncertain','provisioning','running','stopping','stopped','failed','needs_attention']},planHash:str,plan:ref('StudioHostProvisionPlan'),hostId:nullable(uuid),podId:nullable(str),providerStatus:nullable(str),expiresAt:nullable(date),stopRequestedAt:nullable(date),submittedAt:nullable(date),lastReconciledAt:nullable(date),createdAt:date,errorCode:nullable(str),readiness:ref('StudioHostProvisionReadiness'),computeStopped:bool,credentialsRevoked:bool,billingVerified:no});
const fieldType:Schema={type:'string',enum:['missing','null','array','object','number','string','boolean','undefined']};
const providerCheck=object({stage:{type:'string',enum:['lifecycle','health']},ready:bool,code:{type:'string',enum:[...PROVIDER_READINESS_CODES]},httpStatus:nullable(integer)});
providerCheck.properties={...(providerCheck.properties as Record<string,Schema>),endpointIdMatches:bool,endpointType:{type:'string',enum:['QUEUE','LOAD_BALANCER','other','missing']},workersMax:nullable(integer),workersMaxType:fieldType,workersMin:nullable(integer),workersMinType:fieldType,workersType:fieldType,workerCounts:object(Object.fromEntries(['idle','initializing','ready','running','throttled','unhealthy'].map(key=>[key,nullable(integer)])))};
const providerReadiness=object({provisionId:uuid,checkedAt:date,readOnly:yes,authorizesStart:no,ready:bool,providerReady:bool,configuration:object({state:{type:'string',enum:['current','inactive','changed','unavailable']}}),checks:array(ref('StudioHostProviderCheck'),2)});
export const studioHostProvisioningSchemas:Record<string,Schema>={StudioHostProvisionPlan:plan,StudioHostProvision:provision,StudioHostProvisionReadiness:readiness,StudioHostProviderCheck:providerCheck,StudioHostProviderReadiness:providerReadiness};
const success=(schema:Schema)=>({description:'Reviewed operation and current provider observation; no secrets.',content:{'application/json':{schema}}});
function operation(operationId:string,summary:string,result:Schema,input?:z.ZodType,item=false,creation=false){return{operationId,summary,description:'Human owner or administrator only. A plan starts nothing. Start commits the exact reviewed plan, reserves a non-resetting company CPU allowance, enrolls and activates the selected agents, then reconciles one fixed Runpod CPU Pod. Submission uncertainty is discovered without a second create. Stop affects CPU compute only after provider submission; host revocation is separate. For a failed start proven never submitted, stop instead closes the failed provision and revokes its unused host enrollment in one database transaction without provider calls. CPU reservations exclude retained storage and inference. An optional exact coatria_broker_v1 plan adds a separate lifetime inference allowance and per-host model-step limit, without copying provider credentials into the CPU. These reservations are not a provider billing cap. No provider credentials, arbitrary commands, destinations, volumes or runtime configuration are accepted from a caller.',security:[{sessionCookie:[]}],'x-coatria-roles':['owner','admin'],parameters:[{name:'companyId',in:'path',required:true,schema:uuid},...(item?[{name:'provisionId',in:'path',required:true,schema:uuid}]:[]),...(input?[{name:'Origin',in:'header',required:true,schema:{type:'string',format:'uri'}}]:[])],...(input?{requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(input,{io:'input',unrepresentable:'any'})}}}}:{}),responses:{'200':success(result),...(creation?{'201':success(result)}:{}),...Object.fromEntries(['400','401','403','404','409','413','415','429','500','503'].map(status=>[status,{description:'Validation, authority, stale plan, budget, or configuration failure.',content:{'application/json':{schema:ref('Error')}}}]))}};}
const base='/api/companies/{companyId}/studio/host-provisions',single=object({provision:ref('StudioHostProvision')}),mutation=object({provision:ref('StudioHostProvision'),replayed:bool});
export const studioHostProvisioningPaths:Record<string,unknown>={
 [base]:{get:operation('listStudioHostProvisions','List the latest 50 managed CPU operations and current configuration readiness',object({provisions:array(ref('StudioHostProvision'),50),readiness:ref('StudioHostProvisionReadiness')})),post:operation('planStudioHostProvision','Review an exact bounded CPU host and selected agent configuration',mutation,studioHostProvisionPlanInput,false,true)},
 [base+'/{provisionId}']:{get:operation('getStudioHostProvision','Read the current state of an exact company CPU operation',single,undefined,true)},
 [base+'/{provisionId}/readiness']:{get:{...operation('getStudioHostProviderReadiness','Check the exact reviewed endpoint through read-only provider requests',object({readiness:ref('StudioHostProviderReadiness')}),undefined,true),description:'Current human company owner or administrator only, checked before and after network I/O. Makes at most two independent GET requests to fixed Runpod management and health origins using server-held credentials and the integrity-checked endpoint in this exact stored provision. Checks health even when max workers is zero or management access fails. Each request is limited to 10 seconds and 2 MiB, with no redirect following or retry. Historical diagnostics remain available after configuration revocation; configuration state is reported separately. Never starts inference or compute, changes provider settings, creates spending authority, or authorizes reuse of an old plan. Rejects query parameters. Limited to four checks per minute per company administrator. Responses are private/no-store and expose fixed status categories and bounded numeric facts only; no tokens, provider bodies, environments, URLs or raw errors.'}},
 [base+'/{provisionId}/start']:{post:operation('startStudioHostProvision','Approve exact charges and agent activation, then submit a bounded CPU host',mutation,studioHostProvisionStartInput,true)},
 [base+'/{provisionId}/stop']:{post:operation('stopStudioHostProvision','Request CPU stop or close an unsubmitted failed start, retaining storage',mutation,studioHostProvisionStopInput,true)},
 [base+'/{provisionId}/reconcile']:{post:operation('reconcileStudioHostProvision','Check one provider operation without duplicating an uncertain create',single,z.object({clientId:z.string().uuid()}).strict(),true)},
};
