import {z} from 'zod';
import {studioStaffingProposeInput,studioStaffingApplyInput,studioStaffingRejectInput} from './studio-staffing-protocol';
import {studioStaffingSchemas} from './studio-staffing-openapi';
import {executionConnectorInput,executionConnectorPatchInput,executionInputRegisterInput,executionSubmitInput,executionJobActionInput,executionClaimInput,executionLeaseInput,executionCompleteInput,executionFailureInput,executionProfileInput,executionManifestInput} from './studio-execution-protocol';
import {studioHostRegisterInput,studioHostEnrollInput,studioHostRevokeInput,studioHostCredentialsInput} from './studio-hosting-protocol';
import {studioMediaUploadInput,studioMediaVerifyInput,studioMediaPromoteInput,STUDIO_MEDIA_MAX_FILE_BYTES,STUDIO_MEDIA_UPLOAD_SECONDS,STUDIO_MEDIA_READ_SECONDS} from './studio-media-protocol';
import {studioSpecInput} from './studio-protocol';
import {studioCoordinationInput} from './studio-coordination-protocol';
import {studioReviewPolicyInput} from './studio-review-policy-protocol';

type Schema=Record<string,unknown>;
const uuid:Schema={type:'string',format:'uuid'},text:Schema={type:'string'},date:Schema={type:'string',format:'date-time'},integer:Schema={type:'integer'},nullable=(value:Schema):Schema=>({anyOf:[value,{type:'null'}]}),array=(value:Schema,max=100):Schema=>({type:'array',items:value,maxItems:max}),ref=(name:string):Schema=>({$ref:'#/components/schemas/'+name});
const object=(properties:Record<string,Schema>,required=Object.keys(properties)):Schema=>({type:'object',properties,required,additionalProperties:false});
const input=(value:z.ZodType)=>z.toJSONSchema(value,{io:'input',unrepresentable:'any'});
const output=(value:z.ZodType)=>z.toJSONSchema(value,{io:'output',unrepresentable:'any'});
const parameter=(name:string)=>({name,in:'path',required:true,schema:uuid});
const response=(schema:Schema)=>({description:'Successful response',content:{'application/json':{schema}}});
const failure=Object.fromEntries(['400','401','403','404','409','413','415','429','500','503'].map(status=>[status,response(ref('Error'))]));
const creationOperations=new Set(['proposeStudioStaffing','applyStudioStaffing','registerStudioExecutionConnector','registerStudioExecutionInput','proposeStudioExecution','registerStudioHost','enrollStudioHost','revokeStudioHost']);
function operation(id:string,summary:string,result:Schema,schema?:z.ZodType,ids:string[]=['companyId'],worker=false){return {operationId:id,summary,security:worker?[{executionBearer:[]}]:[{sessionCookie:[]}],parameters:[...ids.map(parameter),...schema&&!worker?[{name:'Origin',in:'header',required:true,schema:{type:'string',format:'uri'}}]:[]],...schema?{requestBody:{required:true,content:{'application/json':{schema:input(schema)}}}}:{},responses:{'200':response(result),...creationOperations.has(id)?{'201':response(result)}:{},...failure},...schema&&!worker?{'x-coatria-roles':['owner','admin']}:{},description:worker?'Company-scoped execution connector credential required. Jobs can run only after exact human approval. Completion is evidence reported by the connector, not server verification of stored bytes, studio task acceptance or client delivery.':'Current company membership required. Mutations require a human owner or administrator. Stable clientId and exact revisions protect retries; no endpoint accepts provider credentials or model-generated shell commands.'};}
const connector=object({id:uuid,companyId:uuid,name:text,profiles:array(output(executionProfileInput),8),status:{type:'string',enum:['active','paused','revoked']},revision:integer,createdBy:uuid,expiresAt:date,lastSeenAt:nullable(date),createdAt:date});
const inputReference=object({id:uuid,projectId:uuid,name:text,kind:{type:'string',enum:['scene','cache','image_sequence','media']},storageKey:text,sha256:text,bytes:integer,registeredBy:uuid,createdAt:date});
const status:Schema={type:'string',enum:['awaiting_approval','queued','running','succeeded','failed','failed_uncertain','cancelled']};
const jobProperties={id:uuid,companyId:uuid,projectId:uuid,workItemId:uuid,connectorId:uuid,requestedBy:uuid,requestedAgentId:nullable(uuid),requestedRunId:nullable(uuid),approvedBy:nullable(uuid),profile:output(executionProfileInput),spec:ref('StudioSpec'),inputReferences:array(inputReference,32),frameStart:integer,frameEnd:integer,outputKind:{type:'string',enum:['image_sequence','scene','cache','media']},status,revision:integer,workerId:nullable(text),startedAt:nullable(date),deadlineAt:nullable(date),leaseExpiresAt:nullable(date),leaseExpired:{type:'boolean',description:'Derived from the current lease and hard execution deadline. Expired running work is uncertain and is never automatically returned to the queue.'},effectiveStatus:status,finishedAt:nullable(date),failureReason:nullable(text),createdAt:date,updatedAt:date};
const {inputReferences:_,...summaryProperties}=jobProperties;
const job=object({...jobProperties,output:nullable(object({manifest:output(executionManifestInput),manifestHash:text,verificationSource:{const:'connector_reported'},createdAt:date})),independentlyReviewed:{const:false}});
const snapshot=object({connectors:array(connector),inputs:array(inputReference),jobs:array(object({...summaryProperties,inputReferenceCount:integer,exactDetailsAvailable:{const:true}})),page:object({kind:{type:'string',enum:['jobs','inputs','connectors']},after:nullable(uuid),limit:integer,hasMore:{type:'boolean'},nextAfter:nullable(uuid)}),verificationSource:{const:'connector_reported'},independentlyReviewed:{const:false}});
const jobResult=object({job:ref('StudioExecutionJob'),replayed:{type:'boolean'}});
const base='/api/companies/{companyId}/studio',jobs=base+'/execution/jobs',staff=base+'/staffing/proposals';
export const studioOperationsSchemas:Record<string,Schema>={...studioStaffingSchemas,StudioExecutionJob:job,StudioExecutionConnector:connector,StudioExecutionInput:inputReference,StudioExecutionSnapshot:snapshot};
export const studioOperationsPaths:Record<string,unknown>={
 [staff]:{
  get:{...operation('listStudioStaffingProposals','Read administrator-reviewed staffing proposals',object({proposals:array(ref('StudioStaffingProposal')),hasMore:{type:'boolean'},nextAfter:nullable(uuid)})),parameters:[parameter('companyId'),{name:'after',in:'query',schema:uuid},{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:25}}],'x-coatria-roles':['owner','admin']},
  post:operation('proposeStudioStaffing','Prepare a reviewable staffing plan without creating agents',object({proposal:ref('StudioStaffingProposal'),replayed:{type:'boolean'}}),studioStaffingProposeInput),
 },
 [staff+'/{proposalId}']:{get:{...operation('readStudioStaffingProposal','Read the exact company role and skill plan',object({proposal:ref('StudioStaffingProposal')}),undefined,['companyId','proposalId']),'x-coatria-roles':['owner','admin']}},
 [staff+'/{proposalId}/apply']:{post:operation('applyStudioStaffing','Apply the exact reviewed plan and create paused specialist identities',object({application:ref('StudioStaffingApplication'),proposal:ref('StudioStaffingProposal'),replayed:{type:'boolean'}}),studioStaffingApplyInput,['companyId','proposalId'])},
 [staff+'/{proposalId}/reject']:{post:operation('rejectStudioStaffing','Reject an exact staffing proposal',object({proposal:ref('StudioStaffingProposal')}),studioStaffingRejectInput,['companyId','proposalId'])},
 [base+'/execution']:{get:{...operation('listStudioExecution','Read one paginated resource: jobs, pinned inputs, or connectors',ref('StudioExecutionSnapshot')),parameters:[parameter('companyId'),{name:'projectId',in:'query',schema:uuid},{name:'kind',in:'query',schema:{type:'string',enum:['jobs','inputs','connectors'],default:'jobs'}},{name:'after',in:'query',schema:uuid},{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:100,default:25}}]}},
 [base+'/execution/connectors']:{post:operation('registerStudioExecutionConnector','Register approved profiles and issue one company-scoped renderer credential',object({connector:ref('StudioExecutionConnector'),token:nullable({type:'string','x-coatria-sensitive':true,description:'One-time ce_ credential returned only on initial registration; replay returns null. Never persist in application receipts or expose to models.'}),replayed:{type:'boolean'}}),executionConnectorInput)},
 [base+'/execution/connectors/{connectorId}']:{patch:operation('changeStudioExecutionConnector','Pause, resume or revoke a connector; pausing cancels pending jobs',object({connector:ref('StudioExecutionConnector'),replayed:{type:'boolean'}}),executionConnectorPatchInput,['companyId','connectorId'])},
 [base+'/execution/inputs']:{post:operation('registerStudioExecutionInput','Pin an existing storage reference by path, hash and byte length',object({input:ref('StudioExecutionInput'),replayed:{type:'boolean'}}),executionInputRegisterInput)},
 [base+'/execution/inputs/{inputId}']:{get:operation('readStudioExecutionInput','Read one exact pinned input in this company',object({input:ref('StudioExecutionInput')}),undefined,['companyId','inputId'])},
 [jobs]:{post:operation('proposeStudioExecution','Prepare a bounded job awaiting exact human approval',jobResult,executionSubmitInput)},
 [jobs+'/{jobId}']:{get:operation('readStudioExecutionJob','Read a job and its immutable connector-reported output manifest',object({job:ref('StudioExecutionJob')}),undefined,['companyId','jobId'])},
 [jobs+'/{jobId}/approve']:{post:operation('approveStudioExecution','Approve the exact work order and put it in the durable queue',jobResult,executionJobActionInput,['companyId','jobId'])},
 [jobs+'/{jobId}/cancel']:{post:operation('cancelStudioExecution','Cancel queued or running work and invalidate its lease',jobResult,executionJobActionInput,['companyId','jobId'])},
 '/api/execution/identity':{get:operation('readExecutionIdentity','Read the authenticated render connector',object({connector:ref('StudioExecutionConnector')}),undefined,[],true)},
 '/api/execution/jobs/claim':{post:{...operation('claimStudioExecution','Claim one approved job with a durable worker claim ID',{oneOf:[object({job:{type:'null'},replayed:{type:'boolean'}}),object({job:ref('StudioExecutionJob'),leaseToken:{type:'string',description:'Sensitive proof for this exact claim. Never disclose to models or logs.'},leaseExpiresAt:date,replayed:{type:'boolean'}})]},executionClaimInput,[],true),description:'A current company-scoped ce_ connector claims at most one approved job. Reuse the exact claimId and workerId after an uncertain response to recover the same live lease; idle responses contain no lease fields. Heartbeat the 60-second lease before expiry. Expired execution becomes failed_uncertain and is never automatically re-rendered.'}},
 '/api/execution/jobs/{jobId}/heartbeat':{post:operation('heartbeatStudioExecution','Renew the exact live execution lease',object({job:ref('StudioExecutionJob'),leaseExpiresAt:date}),executionLeaseInput,['jobId'],true)},
 '/api/execution/jobs/{jobId}/complete':{post:{...operation('completeStudioExecution','Commit one immutable connector-reported output manifest',jobResult,executionCompleteInput,['jobId'],true),description:'Requires the current connector authority and exact live lease. Server validation retains the exact approved input snapshot and checks output bounds, complete frame coverage and declared metadata; it does not read the rendered files. The exact clientId and unchanged body replay after success without another execution or manifest. Upload and private-media verification separately hash actual stored bytes. Independent technical and creative review remains required.'}},
 '/api/execution/jobs/{jobId}/fail':{post:operation('failStudioExecution','Record a failed execution without automatically re-rendering',jobResult,executionFailureInput,['jobId'],true)},
};

const host=object({id:uuid,companyId:uuid,name:text,status:{type:'string',enum:['active','revoked']},revision:integer,maxAgents:{type:'integer',minimum:1,maximum:11},providerIds:array(text,6),expiresAt:date,createdBy:uuid,createdAt:date,lastSeenAt:nullable(date),leaseEpoch:integer,leaseExpiresAt:nullable(date),bindingCount:integer},['id','companyId','name','status','revision','maxAgents','providerIds','expiresAt','createdBy','createdAt','lastSeenAt','leaseEpoch','leaseExpiresAt']);
const binding=object({agentId:uuid,installationId:uuid,name:text,credentialVersion:integer,installationRevision:integer,expiresAt:date,status:text,credentialState:text,capabilities:array(text,30),enrolledBy:uuid});
const hostCredential=object({agentId:uuid,installationId:uuid,name:text,credentialVersion:integer,installationRevision:integer,agentToken:{type:'string',description:'Sensitive scoped agent bearer token. Returned only to the authenticated host supervisor. Keep in memory; never log or expose to models.'},expiresAt:date,capabilities:array(text,30),runtime:object({pluginId:text,manifestVersion:text,runtimeConfig:ref('PluginRuntimeConfig'),character:ref('AgentCharacter')})});
const hostBase=base+'/hosts';
const hostWorker=(id:string,summary:string,result:Schema,schema?:z.ZodType)=>({...operation(id,summary,result,schema,[],true),security:[{hostBearer:[]}],description:'Company-scoped ch_ host credential. A live bounded host and current administrative sponsors are required. The server fences supervisors by lease epoch, encrypts agent credentials at rest, and issues no broader capabilities. Never log credential responses or cache them past the lease.'});
Object.assign(studioOperationsPaths,{
 [hostBase]:{
  get:{...operation('listStudioHosts','List company agent hosts without exposing credentials',object({hosts:array(host,50),encryptionConfigured:{type:'boolean'}})),'x-coatria-roles':['owner','admin']},
  post:operation('registerStudioHost','Register a bounded host identity with a one-time credential; no compute provisioning',object({host,hostToken:nullable(text),replayed:{type:'boolean'}}),studioHostRegisterInput),
 },
 [hostBase+'/{hostId}']:{get:{...operation('readStudioHost','Read host enrollment metadata',object({host,bindings:array(binding,11)}),undefined,['companyId','hostId']),'x-coatria-roles':['owner','admin']}},
 [hostBase+'/{hostId}/enroll']:{post:operation('enrollStudioHost','Activate exact reviewed installations and encrypt rotated credentials for one host',object({host,bindings:array(binding,11),startsWorkers:{const:false},startsInference:{const:false},replayed:{type:'boolean'}}),studioHostEnrollInput,['companyId','hostId'])},
 [hostBase+'/{hostId}/revoke']:{post:operation('revokeStudioHost','Revoke the host and invalidate its matching issued agent tokens and runs',object({host,invalidatedAgentCount:integer,replayed:{type:'boolean'}}),studioHostRevokeInput,['companyId','hostId'])},
 '/api/host/identity':{get:hostWorker('readStudioHostIdentity','Read the pinned host identity and server clock',object({host,serverTime:date}))},
 '/api/host/credentials':{post:hostWorker('leaseStudioHostCredentials','Acquire or renew the single supervisor lease and retrieve approved agent credentials',object({host,supervisor:object({id:uuid,epoch:integer,expiresAt:date}),credentials:array(hostCredential,11),unavailable:array(object({agentId:uuid,reason:text}),11),pollAfterSeconds:{const:20}}),studioHostCredentialsInput)},
});

const sha256:Schema={type:'string',pattern:'^[0-9a-f]{64}$'};
const signedUrl:Schema={type:'string',format:'uri',readOnly:true,'x-coatria-sensitive':true,description:'Temporary bearer URL for one private object and operation. Do not log, place in model context, persist in receipts, or forward the ce_ connector credential to this URL.'};
const mediaFile=object({id:uuid,projectId:uuid,jobId:uuid,path:text,kind:{type:'string',enum:['image','scene','cache','media','report']},frame:nullable({type:'integer',minimum:0}),sha256,bytes:{type:'integer',minimum:1,maximum:STUDIO_MEDIA_MAX_FILE_BYTES},contentType:text,createdAt:date,verifiedAt:nullable(date),verifiedState:{type:'string',enum:['awaiting_upload_or_verification','verified']},verificationSource:{type:'string',enum:['connector_reported','server_bytes']},independentlyReviewed:{const:false}});
const executionProvenance=object({jobId:uuid,connectorId:uuid,connectorSponsorId:uuid,producedBy:uuid,producedAgentId:nullable(uuid),agentSponsorId:nullable(uuid),runId:nullable(uuid),promotedBy:uuid,executionManifestSha256:sha256});
const mediaArtifact=object({id:uuid,version:{type:'integer',minimum:1},name:text,url:{type:'string',format:'uri',description:'Stable member-authenticated sequence manifest URL. Its exact canonical JSON bytes have the artifact SHA-256; it is not a single EXR or a temporary Blob URL.'},sha256,workItemId:uuid,...output(studioSpecInput).properties as Record<string,Schema>,frameStart:{type:'integer',minimum:0},frameEnd:{type:'integer',minimum:0},notes:text,executionProvenance:ref('StudioExecutionProvenance'),storageVerification:{const:'server_bytes'},referenceKind:{const:'image_sequence_manifest'},reviewStatus:{const:'pending'}});
const mediaSequence=object({schemaVersion:{const:1},kind:{const:'verified_image_sequence'},companyId:uuid,projectId:uuid,workItemId:uuid,jobId:uuid,spec:ref('StudioSpec'),frameStart:{type:'integer',minimum:0},frameEnd:{type:'integer',minimum:0},verificationSource:{const:'server_bytes'},independentlyReviewed:{const:false},provenance:ref('StudioExecutionProvenance'),frames:array(object({frame:{type:'integer',minimum:0},fileId:uuid,path:text,sha256,bytes:{type:'integer',minimum:1,maximum:STUDIO_MEDIA_MAX_FILE_BYTES},accessPath:{type:'string',description:'Relative member-authenticated file API path. Calling it issues a fresh short-lived private read URL.'}}),1000)});
Object.assign(studioOperationsSchemas,{StudioMediaFile:mediaFile,StudioExecutionProvenance:executionProvenance,StudioMediaArtifact:mediaArtifact,StudioMediaSequence:mediaSequence});

const mediaBase=base+'/media',jobMedia=jobs+'/{jobId}/media',connectorMedia='/api/execution/jobs/{jobId}/media';
Object.assign(studioOperationsPaths,{
 [connectorMedia+'/upload']:{post:{
  ...operation('prepareStudioMediaUpload','Authorize one exact completed output for a private write-once upload',object({file:ref('StudioMediaFile'),upload:nullable(object({url:signedUrl,method:{const:'PUT'},headers:object({'Content-Type':text,'x-content-type':text}),expiresAt:date})),replayed:{type:'boolean'}}),studioMediaUploadInput,['jobId'],true),
  description:`Requires the owning current ce_ connector and a succeeded job with immutable output evidence. The path must exactly match a declared output. The server creates the storage pathname and returns a PUT-only signed URL for at most ${STUDIO_MEDIA_UPLOAD_SECONDS} seconds, with no overwrite, no random suffix, exact expected maximum bytes and MIME type. The pilot limit is ${STUDIO_MEDIA_MAX_FILE_BYTES} bytes (20 MiB) per file. A verified file returns upload:null. Repeating clientId with unchanged data reuses the file record; any returned URL is newly issued and is never stored in the idempotency receipt. PUT the exact locally hashed bytes using both returned matching Content-Type and x-content-type headers; the latter selects the stored MIME type and the exact signed allowedContentTypes grant enforces it. Never send the ce_ credential to Blob, follow storage redirects, or treat a PUT response as verification. Call verify afterward. A native scene/cache upload remains a separate file and does not become image-sequence proof.`,
 }},
 [connectorMedia+'/verify']:{post:{
  ...operation('verifyStudioMediaUpload','Hash actual private stored bytes against the immutable completed output',object({file:ref('StudioMediaFile'),replayed:{type:'boolean'}}),studioMediaVerifyInput,['jobId'],true),
  description:`The fileId must belong to this completed job and current connector. The server reads only its own recorded private pathname, bypasses the storage cache, enforces exact size and the ${STUDIO_MEDIA_MAX_FILE_BYTES}-byte pilot bound, then compares SHA-256. Connector and source authority are checked again before an immutable verification receipt is inserted. No arbitrary URL is accepted. Missing, truncated, oversized or mismatched bytes fail without a verification receipt. Exact clientId/body replay returns the recorded result; a verified file can be reused without another transfer. server_bytes verifies stored size and checksum, not image decoding, color correctness, creative quality or client approval.`,
 }},
 [mediaBase]:{get:{
  ...operation('listStudioMedia','List paginated private output metadata and explicit verification state',object({files:array(ref('StudioMediaFile')),page:object({limit:{type:'integer',minimum:1,maximum:100},hasMore:{type:'boolean'},nextAfter:nullable(uuid)}),maxFileBytes:{const:STUDIO_MEDIA_MAX_FILE_BYTES}})),
  parameters:[parameter('companyId'),{name:'jobId',in:'query',required:true,schema:uuid},{name:'after',in:'query',schema:uuid},{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:100,default:25}}],
  description:'Current company membership required. Lists only registered files for one same-company execution job; before registration, a declared output may exist only in the execution manifest. Ascending file-ID pagination is complete through nextAfter. No storage credentials, storage pathnames or signed URLs are returned.',
 }},
 [mediaBase+'/{fileId}']:{get:{
  ...operation('readStudioMedia','Issue temporary private read access to one server-verified file',object({file:ref('StudioMediaFile'),access:object({url:signedUrl,expiresAt:date})}),undefined,['companyId','fileId']),
  description:`Requires current company membership and verified stored bytes. Returns JSON metadata with a GET-only signed URL lasting at most ${STUDIO_MEDIA_READ_SECONDS} seconds, not the file bytes or a redirect. Membership is rechecked after signing. Responses are private,no-store. The temporary URL is a bearer capability until expiry, so keep it out of logs, model context and permanent artifact references. This route works for EXR, PNG, native scene/cache and report files; it does not assert independent review.`,
 }},
 [jobMedia+'/promote']:{post:{
  ...operation('promoteStudioMedia','Register a fully verified sequence as a pending immutable studio version',object({artifact:ref('StudioMediaArtifact'),project:object({id:uuid,revision:{type:'integer',minimum:1}}),replayed:{type:'boolean'}}),studioMediaPromoteInput,['companyId','jobId']),
  description:'Requires a current human owner/administrator, exact current project revision, matching approved specification, permitted AI use, production gates and eligible DCC work. Every frame of the completed image sequence must have a server-byte verification receipt; one uploaded EXR is insufficient. Registers one immutable canonical sequence-manifest reference per job and preserves the original requester, producing agent, run and sponsors. Promotion does not impersonate the producer, accept the task, approve the artifact, transfer delivery or contact the client. The original producer and agent/connector sponsors cannot independently approve their output. Reuse exact clientId/body to recover an uncertain response; a different second promotion is rejected. Native scene/cache files cannot be promoted as image sequences.',
 }},
 [jobMedia+'/manifest']:{get:{
  ...operation('readStudioMediaSequence','Read exact immutable JSON bytes for a promoted private sequence',ref('StudioMediaSequence'),undefined,['companyId','jobId']),
  description:'Current company membership required. Returns the persisted canonical JSON text, without signed URLs. The SHA-256 of these exact UTF-8 response bytes equals the studio artifact checksum and X-Content-SHA256 header. Frames are ordered and each contains an exact verified file ID, hash, byte count and member-only access path. The manifest records storage verification and historical provenance; its independentlyReviewed:false value is immutable initial evidence. Consult current studio review receipts for later approval.',
  responses:{'200':{...response(ref('StudioMediaSequence')),headers:{'X-Content-SHA256':{required:true,description:'SHA-256 of the exact persisted canonical JSON response bytes.',schema:sha256},'Cache-Control':{required:true,schema:{const:'private, no-store'}}}},...failure},
 }},
});

const coordinationPolicy=object({projectId:uuid,coordinatorAgentId:uuid,allowedRoleKeys:array(text,11),status:{type:'string',enum:['active','paused']},effectiveStatus:{type:'string',enum:['active','paused','expired','approval_required','exhausted']},blocker:nullable(text),revision:integer,maxRuns:integer,runsStarted:integer,remainingRuns:integer,maxConcurrentRuns:integer,approvedBy:uuid,expiresAt:date,updatedAt:date,profileRevision:integer});
const planningPolicy=object({projectId:uuid,coordinatorAgentId:uuid,reviewerAgentId:uuid,allowedStages:array({type:'string',enum:['estimate','breakdown','ingest']},3),allowSharedSponsor:{type:'boolean'},maxReviews:integer,reviewsStarted:integer,remainingReviews:integer,status:{type:'string',enum:['active','paused']},effectiveStatus:{type:'string',enum:['active','paused','expired','approval_required','exhausted']},blocker:nullable(text),revision:integer,profileRevision:integer,approvedBy:uuid,expiresAt:date,updatedAt:date,reviewKind:{const:'machine_planning'}});
const planningReview=object({id:uuid,projectId:uuid,workItemId:uuid,taskId:uuid,taskRevision:integer,policyRevision:integer,parentRunId:uuid,reviewerRunId:uuid,reviewerAgentId:uuid,producerAgentId:uuid,producerRunId:uuid,submissionSha256:sha256,createdAt:date,runStatus:{type:'string',enum:['queued','running','succeeded','failed','cancelled']},decision:nullable(object({decision:{type:'string',enum:['approve','changes_requested','reject']},note:text,taskRevision:integer,decidedAt:date}))});
const planningSnapshotProperties={policy:nullable(ref('StudioReviewPolicy')),reviews:array(ref('StudioPlanningReview'),100),budgetUnit:{const:'reviewer_runs'},budgetScope:{const:'separate_from_specialist_and_coordinator_runs'},reviewKind:{const:'machine_planning'},independentHumanReview:{const:false},startsWorkers:{const:false},startsInference:{const:false}};
Object.assign(studioOperationsSchemas,{StudioReviewPolicy:planningPolicy,StudioPlanningReview:planningReview,StudioReviewPolicySnapshot:object(planningSnapshotProperties)});
Object.assign(studioOperationsPaths,{
 [base+'/projects/{projectId}/review-policy']:{
  get:{...operation('getStudioReviewPolicy','Read exact planning review approval and lifetime reviewer-run usage',ref('StudioReviewPolicySnapshot'),undefined,['companyId','projectId']),description:'Company membership required. Returns separately labeled machine reviews. The lifetime reviewer allowance excludes coordinator and specialist runs and is not a spending cap. Initial state has no machine-review authority.'},
  put:{...operation('saveStudioReviewPolicy','Approve or pause a distinct agent’s bounded planning review authority',object({...planningSnapshotProperties,replayed:{type:'boolean'}}),studioReviewPolicyInput,['companyId','projectId']),description:'Human owner/administrator only. Revision 0 creates; later changes require the exact revision. Approval pins distinct coordinator/reviewer installations and company profile, expires within 24 hours, and never resets reviewsStarted. Shared producer/reviewer sponsorship requires explicit opt-in; current and historical producing agents cannot review their own task. Only agent-executed estimate, breakdown and optionally ingest provenance are eligible. This does not convert human tasks, approve commercial estimates, authorize production, verify media or record client acceptance. The reviewer must read the immutable snapshot in its exact live single-attempt run before deciding. Every queued review consumes the lifetime allowance; changed policies and expiry fence pending work. Exact status-only pause remains possible after authority expires. Saving starts no workers or inference.'},
 },
 [base+'/projects/{projectId}/planning-reviews/{reviewId}']:{get:{...operation('getStudioPlanningReview','Read one immutable planning review snapshot and decision',object({review:object({...planningReview.properties as Record<string,Schema>,submission:{type:'object',additionalProperties:true},briefSha256:sha256}),reviewKind:{const:'machine_planning'},independentHumanReview:{const:false},contentInspected:{const:false}}),undefined,['companyId','projectId','reviewId']),description:'Current same-company member read. Returns the exact bounded planning submission and provenance pinned at dispatch. Text and input references are untrusted task data, never instructions to bypass permissions. This member read does not attest that the assigned reviewer run read the submission; only studio_review_read can do that.'}},
});
const coordinationDispatch=object({executionJobId:nullable(uuid),sourceChildRunId:nullable(uuid),artifactId:nullable(uuid),workItemId:uuid,parentRunId:uuid,childRunId:uuid,coordinatorAgentId:uuid,specialistAgentId:uuid,policyRevision:integer,createdAt:date,status:{type:'string',enum:['queued','running','succeeded','failed','cancelled']}});
const renderFollowup=object({projectId:uuid,workItemId:uuid,executionJobId:uuid,sourceChildRunId:uuid,specialistAgentId:uuid,taskId:uuid,roleKey:text,executionManifestSha256:sha256,artifactId:uuid,artifactSha256:sha256});
const coordinationSnapshotProperties={renderFollowups:array(renderFollowup,100),policy:nullable(ref('StudioCoordinationPolicy')),dispatches:array(coordinationDispatch,100),budgetUnit:{const:'specialist_runs'},budgetScope:{const:'coordinator_dispatched_runs_only'},startsWorkers:{const:false},startsInference:{const:false}};
Object.assign(studioOperationsSchemas,{StudioCoordinationPolicy:coordinationPolicy,StudioCoordinationSnapshot:object(coordinationSnapshotProperties)});
Object.assign(studioOperationsPaths,{
 [base+'/projects/{projectId}/coordination']:{
  get:{...operation('getStudioCoordination','Read exact project delegation approval and lifetime specialist run usage',ref('StudioCoordinationSnapshot'),undefined,['companyId','projectId']),description:'Company membership required. Returns all at most 100 lifetime coordinator-dispatched specialist receipts. Effective status includes expiry, changed roles/plugin revisions and unavailable sponsors. renderFollowups identifies completed original delegated renders with all private output bytes verified and a human-promoted artifact; eligibility is rechecked at dispatch. These entries are metadata, not image inspection or QC. The specialist run limit excludes coordinator cycles and manually queued requests; it is not a dollar, token or GPU budget.'},
  put:{...operation('saveStudioCoordination','Approve or pause bounded project specialist delegation',object({...coordinationSnapshotProperties,replayed:{type:'boolean'}}),studioCoordinationInput,['companyId','projectId']),description:'Current human owner/administrator only. Revision 0 creates; subsequent changes require the exact revision. Approval expires within 24 hours. The server pins current role assignments and exact active plugin installation revisions. Lifetime runsStarted never resets; failed and cancelled children remain counted. An exact status-only pause with unchanged existing settings works even if prior approval expired or an agent is unavailable. Policy changes, pause and expiry fence queued/running children at claim and subsequent heartbeat/tool authority checks; terminal receipts remain replayable. Saving does not queue work, change specialist grants, start workers or invoke inference. Only the approved coordinator can use studio_work_dispatch; each work item can receive one initial delegated child. Supplying executionJobId permits one exact post-render follow-up for a successful original child and approved completed job, after every output file is privately verified and a human promotes its artifact. That follow-up consumes the same lifetime/concurrency allowance, pins the manifest and latest artifact, removes renderer capability, and permits only exact evidence reads plus claiming/submitting its existing task. Every child has one inference attempt; failed or uncertain effects require explicit human reconciliation. Human business gates, execution approvals and independent review remain mandatory.'},
 },
});
