import {z} from 'zod';
import {studioClientDeliveryCreateInput,studioClientDeliveryRevokeInput,studioClientDeliveryAccessInput,studioClientDeliveryResponseInput} from './studio-client-delivery-protocol';

type Schema=Record<string,unknown>;
const uuid:Schema={type:'string',format:'uuid'},text:Schema={type:'string'},date:Schema={type:'string',format:'date-time'},integer:Schema={type:'integer'},boolean:Schema={type:'boolean'},sha:Schema={type:'string',pattern:'^[a-f0-9]{64}$'};
const nullable=(schema:Schema):Schema=>({anyOf:[schema,{type:'null'}]}),array=(items:Schema,maxItems:number):Schema=>({type:'array',items,maxItems}),ref=(name:string):Schema=>({$ref:'#/components/schemas/'+name});
const object=(properties:Record<string,Schema>,required=Object.keys(properties)):Schema=>({type:'object',properties,required,additionalProperties:false});
const file=object({fileId:uuid,artifactId:uuid,path:text,frame:nullable(integer),sha256:sha,bytes:{type:'integer',minimum:1,maximum:20971520},contentType:text});
const generatedFile=object({fileId:uuid,artifactId:uuid,path:text,frame:{type:'null'},sha256:sha,bytes:{type:'integer',minimum:1,maximum:107374182400},contentType:text,storageVersionId:uuid,mediaKind:{enum:['image','video','audio']},transport:{const:'project_storage'}});
const receipt=object({id:uuid,kind:{type:'string',enum:['portal_opened','download_access_issued','acknowledged','changes_requested','revoked']},actorUserId:uuid,fileId:nullable(uuid),note:nullable(text),packageSha256:sha,createdAt:date});
const share=object({id:uuid,projectId:uuid,deliveryId:uuid,recipientUserId:uuid,recipientName:text,identityBasis:{const:'account_confirmed_out_of_band'},emailVerifiedAtCreation:boolean,status:{type:'string',enum:['active','revoked']},revision:integer,expiresAt:date,createdAt:date,createdBy:uuid,packageSha256:sha,sourceManifestSha256:sha,response:{type:'string',enum:['awaiting_response','acknowledged','changes_requested']},invitationPath:{type:'string',pattern:'^/delivery/[0-9a-f-]{36}$'},fileCount:{type:'integer',minimum:1,maximum:2400},receiptSummary:object({portalOpened:integer,downloadAccessIssued:integer,clientAcknowledged:integer,changesRequested:integer}),transferStatus:{const:'not_observed'},expired:boolean});
const packageSchema=object({schemaVersion:{const:1},delivery:object({id:uuid,name:text,preparedAt:date}),project:object({id:uuid,name:text,clientName:text,spec:ref('StudioSpec')}),sourceManifestSha256:sha,reviewBasis:{const:'independently_approved'},artifacts:array(object({id:uuid,name:text,version:integer,sha256:sha}),100),files:array(ref('StudioClientDeliveryFile'),2400)});
const generatedPackage=object({...(packageSchema.properties as Record<string,Schema>),schemaVersion:{const:2},revisionRound:object({roundId:uuid,number:{type:'integer',minimum:1,maximum:20},planSha256:sha}),project:object({id:uuid,name:text,clientName:text,spec:ref('StudioGeneratedSpec')}),files:array(ref('StudioGeneratedClientDeliveryFile'),100)},Object.keys(packageSchema.properties as Record<string,Schema>));
const generatedAccess=object({transport:{const:'project_storage'},storageVersionId:uuid,gatewayOrigin:{type:'string',format:'uri'},url:{type:'string',format:'uri'},headers:object({Authorization:{type:'string',pattern:'^Bearer sct_[A-Za-z0-9_-]{43}$','x-coatria-sensitive':true}}),expiresAt:date,bytes:{type:'integer',minimum:1,maximum:107374182400},name:text,sha256:sha,contentType:text,status:{const:'download_access_issued'},bytesReceivedByClient:{const:'not_observed'}});
const page=object({hasMore:boolean,nextAfter:nullable(uuid),limit:{type:'integer',minimum:1,maximum:50}});
const identity=object({userId:uuid,name:text,emailVerified:boolean});
const detail=object({share:ref('StudioClientDeliveryShare'),package:ref('StudioReadableClientPackage'),receipts:array(ref('StudioClientDeliveryReceipt'),50),receiptPage:page,canRespond:boolean,responseBlockedReason:nullable(text),identity});
const response=(schema:Schema,description='Successful response')=>({description,headers:{'Cache-Control':{schema:{const:'private, no-store'}}},content:{'application/json':{schema}}});
const errors=Object.fromEntries(['400','401','403','404','409','410','415','429','500','503'].map(status=>[status,response(ref('Error'),'Authentication, grant, stale state, expiry, unavailable storage or validation error. No private file URL is included.')]));
const parameter=(name:string)=>({name,in:'path',required:true,schema:uuid});
const paging=[{name:'after',in:'query',schema:uuid},{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:20}}];
function operation(operationId:string,summary:string,result:Schema,ids:string[],options:{schema?:z.ZodType;client?:boolean;created?:boolean;paged?:boolean;description?:string}={}){
 return {operationId,summary,security:[{sessionCookie:[]}],parameters:[...ids.map(parameter),...options.paged?paging:[],...options.schema?[{name:'Origin',in:'header',required:true,schema:{type:'string',format:'uri'}},{name:'X-Coatria-User',in:'header',required:false,schema:uuid}]:[]],...options.schema?{requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(options.schema,{io:'input',unrepresentable:'any'})}}}}:{},responses:{'200':response(result),...options.created?{'201':response(result)}:{},...errors},'x-coatria-roles':options.client?['designated_authenticated_external_client']:options.schema?['owner','admin']:['owner','admin','member'],description:(options.client?'Requires the exact recipient’s current authenticated session and an active, unexpired, administrator-backed grant. A company member, package producer, sponsor, administrator or different client cannot substitute their own identity. The invitation UUID is a locator, not a bearer credential. ':'Requires current company membership; creation and revocation require a human administrator. Agents with studio.read may list receipt metadata through the corresponding scoped tool but cannot issue grants or act as a client. ')+(options.schema?'Reuse the same clientId and identical request data after an uncertain response; conflicting reuse returns409. Current authorization is checked before any replay. ':'')+(options.description??'')};
}
export const studioClientDeliverySchemas:Record<string,Schema>={
 StudioGeneratedClientDeliveryFile:generatedFile,StudioGeneratedClientPackage:generatedPackage,StudioReadableClientPackage:{oneOf:[ref('StudioClientPackage'),ref('StudioGeneratedClientPackage')]},StudioGeneratedClientAccess:generatedAccess,StudioReadableClientDeliveryAccess:{oneOf:[ref('StudioClientDeliveryAccess'),ref('StudioGeneratedClientAccess')]},
 StudioClientDeliveryFile:file,StudioClientDeliveryReceipt:receipt,StudioClientDeliveryShare:share,StudioClientPackage:packageSchema,StudioClientDeliveryDetail:detail,
 StudioClientDeliveryList:object({shares:array(ref('StudioClientDeliveryShare'),50),page}),
 StudioClientDeliveryIdentity:object({user:object({id:uuid,name:text,email:{type:'string',format:'email'},emailVerified:boolean}),identityBasis:{const:'authenticated_account'},instructions:text}),
 StudioClientDeliveryAccess:object({url:{type:'string',format:'uri','x-coatria-sensitive':true,description:'Sensitive private Blob read URL for exactly one approved file. Never persist, log, forward to agents, or expose to another account. Valid for at most60seconds, bounded by invitation expiry; already issued URLs can remain valid until expiry after revocation.'},expiresAt:date,status:{const:'download_access_issued'},bytesReceivedByClient:{const:'not_observed'}}),
};
const admin='/api/companies/{companyId}/studio/projects/{projectId}/client-deliveries',client='/api/client-deliveries/{shareId}',adminIds=['companyId','projectId'];
export const studioClientDeliveryPaths:Record<string,any>={
 [admin]:{
  get:operation('listStudioClientDeliveries','List package-bound client invitations and truthful receipt summaries',ref('StudioClientDeliveryList'),adminIds,{paged:true}),
  post:operation('createStudioClientDelivery','Grant one externally confirmed client account an exact approved private package',object({share:ref('StudioClientDeliveryShare'),replayed:boolean}),adminIds,{schema:studioClientDeliveryCreateInput,created:true,description:'Generated contractVersion:2 creates a schemaVersion2 external package bound to exact verified storage versions; authenticated recipients use the separate short-lived project_storage gateway transport. Legacy frame files remain schemaVersion1. revision is the current project revision. The administrator must confirm recipientUserId through a trusted existing channel. Email verification is not enabled; emailVerifiedAtCreation records actual account state without asserting legal identity. Expiry is at most30days. All tasks, including independent delivery handoff, must be accepted. Only exact independently approved artifacts backed by matching server-verified frame files or generated storage versions are eligible. Original package and client-visible canonical package have separate immutable SHA-256 hashes. Returns a copyable invitationPath; sends no message and records no transfer.'}),
 },
 [admin+'/{shareId}/revoke']:{post:operation('revokeStudioClientDelivery','Revoke future client access without deleting receipts',object({share:ref('StudioClientDeliveryShare'),replayed:boolean}),[...adminIds,'shareId'],{schema:studioClientDeliveryRevokeInput,description:'revision is the invitation revision. Revocation does not recall bytes already downloaded or previously issued read URLs; those expire within60seconds.'})},
 '/api/client-deliveries/identity':{get:operation('readClientDeliveryIdentity','Read your own authenticated account ID without joining a company',ref('StudioClientDeliveryIdentity'),[],{client:true,description:'This identity endpoint requires only your authenticated session, before any invitation exists. Share this account ID directly with the studio. It does not enumerate other users or verify an email address.'})},
 [client]:{get:operation('readClientDelivery','Read your approved exact package and access/response receipts',ref('StudioClientDeliveryDetail'),['shareId'],{client:true,paged:true,description:'Pagination applies to immutable receipts; package file metadata is an immutable bounded snapshot of at most2400 files. No raw storage pathname or signed URL is returned. GET alone does not create a portal-open receipt. canRespond is advisory; the write rechecks exact current approval and dependencies.'})},
 [client+'/open']:{post:operation('recordClientDeliveryOpen','Record an authenticated portal-open event',object({receipt:ref('StudioClientDeliveryReceipt'),replayed:boolean}),['shareId'],{client:true,schema:studioClientDeliveryAccessInput,description:'Records a logical portal-open request, not media transfer or client acceptance.'})},
 [client+'/files/{fileId}/access']:{post:operation('issueClientDeliveryFileAccess','Issue short-lived read access for one exact granted file',object({receipt:ref('StudioClientDeliveryReceipt'),replayed:boolean,access:ref('StudioReadableClientDeliveryAccess')}),['shareId','fileId'],{client:true,schema:studioClientDeliveryAccessInput,description:'Generated access returns a scoped gateway bearer token, exact version and byte facts for bounded Range GETs at /v1/client-files/{storageVersionId}. Tokens expire within 60 seconds. Authority is checked for each range, before its first chunk and every 5 seconds during active or stalled streaming, plus database check latency; the independent expiry timer remains absolute. Reuse the current short-lived token for successive ranges, then renew through this endpoint before its window expires. Never log or forward this token to an agent. Legacy storage signing occurs outside the database transaction; authorization is rechecked before returning the URL and recording the receipt. A retry can refresh the short-lived URL but retains one logical receipt for the same clientId. A download_access_issued receipt proves authorization and URL issuance, never that the client received bytes. Response is sensitive and no-store.'})},
 [client+'/responses']:{post:operation('respondToClientDelivery','Acknowledge or request changes to the exact package as its client',object({receipt:ref('StudioClientDeliveryReceipt'),share:ref('StudioClientDeliveryShare'),project:object({id:uuid,revision:integer,status:{type:'string',enum:['delivered','review']}}),replayed:boolean}),['shareId'],{client:true,schema:studioClientDeliveryResponseInput,created:true,description:'revision is the invitation revision. One immutable response is permitted per invitation. An acknowledgement is the client account’s explicit attestation, not measured download completion. It atomically records authenticated_external_client gate provenance and marks only this exact delivery acknowledged after rechecking current versions, production approval and completed tasks. Change requests preserve all versions and return the project to review; they do not reset work or authorize spending. Neither agents nor administrators can call this action as the client.'})},
};
const manifest=operation('downloadClientDeliveryManifest','Download the canonical immutable client-visible manifest',ref('StudioReadableClientPackage'),['shareId'],{client:true,description:'The exact response bytes hash to packageSha256. sourceManifestSha256 identifies the original internally prepared delivery manifest; its historical not_transferred field remains unchanged. This metadata download is not a media transfer receipt.'});
studioClientDeliveryPaths[client+'/manifest']={get:{...manifest,responses:{...manifest.responses,'200':{description:'Canonical JSON bytes of the exact client-visible package.',headers:{'Cache-Control':{schema:{const:'private, no-store'}},'X-Content-SHA256':{schema:sha},'Content-Disposition':{schema:{const:'attachment; filename="coatria-delivery-manifest.json"'}},'Referrer-Policy':{schema:{const:'no-referrer'}}},content:{'application/json':{schema:ref('StudioReadableClientPackage')}}}}}};
studioClientDeliveryPaths['/api/client-deliveries/identity'].get['x-coatria-roles']=['authenticated_user'];
studioClientDeliveryPaths['/api/client-deliveries/identity'].get.description='Any current authenticated user may read their own account ID before an invitation exists. No company membership or client grant is required for this identity-only endpoint. It does not enumerate other accounts or verify an email address. Give this exact account ID directly to the studio through an existing trusted communication channel.';
