import {createHash,randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {requireMembership,type Membership} from './auth';
import {memberMutation} from './company';
import {ApiError,body,fail,id,json} from './security';
import {managedAgentAuthoritySql,managedAgentAuthorityPrincipals} from './studio-hosting';
import {createAgentRunInTransaction} from './agent-runs';
import {assertStudioTaskAction} from './studio';
import {STUDIO_REVIEW_CAPABILITY,studioReviewPolicyInput,studioReviewPolicyGetInput,studioReviewDispatchInput,studioReviewReadInput,studioReviewDecideInput,type StudioReviewPolicy,type StudioReviewPolicySnapshot} from './studio-review-policy-protocol';

type Row=Record<string,any>;
export const canonicalStudioReview=(value:unknown):string=>Array.isArray(value)?'['+value.map(canonicalStudioReview).join(',')+']':value&&typeof value==='object'?'{'+Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>JSON.stringify(key)+':'+canonicalStudioReview(item)).join(',')+'}':JSON.stringify(value);
const digest=(value:unknown)=>createHash('sha256').update(canonicalStudioReview(value)).digest('hex');
const uuidFor=(text:string)=>{const b=createHash('sha256').update(text).digest().subarray(0,16);b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=b.toString('hex');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};
const policyColumns=`project_id AS "projectId",coordinator_agent_id AS "coordinatorAgentId",reviewer_agent_id AS "reviewerAgentId",approved_by AS "approvedBy",revision,status,allowed_stages AS "allowedStages",allow_shared_sponsor AS "allowSharedSponsor",authority_snapshot AS "authoritySnapshot",profile_revision AS "profileRevision",max_reviews AS "maxReviews",reviews_started AS "reviewsStarted",expires_at AS "expiresAt",updated_at AS "updatedAt"`;
async function policyRow(client:PoolClient,companyId:string,projectId:string,lock:''|'SHARE'|'UPDATE'=''){return (await client.query(`SELECT ${policyColumns} FROM studio_review_policies WHERE company_id=$1 AND project_id=$2${lock?' FOR '+lock:''}`,[companyId,projectId])).rows[0] as Row|undefined;}
async function configuration(client:PoolClient,companyId:string,coordinatorAgentId:string,reviewerAgentId:string,lock=false){
 const roles=(await client.query('SELECT role_key,agent_id FROM studio_role_bindings WHERE company_id=$1 ORDER BY role_key',[companyId])).rows;
 if(!roles.some(r=>['producer','coordinator'].includes(r.role_key)&&r.agent_id===coordinatorAgentId))fail(409,'Assign the coordinator to a producer or coordinator role.','REVIEW_ROLE_CHANGED');
 if(coordinatorAgentId===reviewerAgentId)fail(409,'The reviewer must be a separate agent.','REVIEW_SELF_APPROVAL');
 const agentIds=[coordinatorAgentId,reviewerAgentId].sort();
 if(lock){const previews=(await client.query('SELECT id,created_by FROM agents WHERE company_id=$1 AND id=ANY($2::uuid[]) ORDER BY id',[companyId,agentIds])).rows,principals:string[]=[];for(const a of previews)principals.push(a.created_by,...await managedAgentAuthorityPrincipals(client,companyId,a.id));await client.query('SELECT user_id FROM memberships WHERE company_id=$1 AND user_id=ANY($2::uuid[]) ORDER BY user_id FOR SHARE',[companyId,[...new Set(principals)].sort()]);}
 const agents=(await client.query(`SELECT a.id AS "agentId",a.created_by AS "sponsorId",a.status,a.capabilities,a.invocation_access AS "invocationAccess",i.id AS "installationId",i.revision AS "installationRevision",a.expires_at>clock_timestamp() AND ${managedAgentAuthoritySql('a')} AND EXISTS(SELECT 1 FROM memberships m WHERE m.company_id=a.company_id AND m.user_id=a.created_by AND m.role IN ('owner','admin')) AS live FROM agents a JOIN plugin_installations i ON i.company_id=a.company_id AND i.agent_id=a.id WHERE a.company_id=$1 AND a.id=ANY($2::uuid[]) ORDER BY a.id${lock?' FOR SHARE OF a,i':''}`,[companyId,agentIds])).rows;
 if(agents.length!==2||agents.some(a=>a.status!=='active'||!a.live||a.invocationAccess==='none'||(a.agentId===reviewerAgentId?['studio.read',STUDIO_REVIEW_CAPABILITY]:['studio.read','studio.write']).some(cap=>!a.capabilities.includes(cap))))fail(409,'The exact reviewer/coordinator plugin, scope, credential or sponsor is unavailable.','REVIEW_AGENT_UNAVAILABLE');
 const profile=(await client.query('SELECT revision FROM studio_profiles WHERE company_id=$1',[companyId])).rows[0];if(!profile)fail(409,'Studio setup is required.');
 return {profileRevision:profile.revision,coordinatorAgentId,reviewerAgentId,agents:agents.map(a=>({agentId:a.agentId,sponsorId:a.sponsorId,installationId:a.installationId,installationRevision:a.installationRevision}))};
}
async function effective(client:PoolClient,companyId:string,p:Row):Promise<Pick<StudioReviewPolicy,'effectiveStatus'|'blocker'>>{
 if(p.status!=='active')return {effectiveStatus:'paused',blocker:'Machine planning review is paused.'};
 if(+new Date(p.expiresAt)<=Date.now())return {effectiveStatus:'expired',blocker:'Machine review approval expired.'};
 if(!(await client.query("SELECT user_id FROM memberships WHERE company_id=$1 AND user_id=$2 AND role IN ('owner','admin')",[companyId,p.approvedBy])).rowCount)return {effectiveStatus:'approval_required',blocker:'The approving administrator no longer has authority.'};
 try{if(digest(await configuration(client,companyId,p.coordinatorAgentId,p.reviewerAgentId))!==digest(p.authoritySnapshot))return {effectiveStatus:'approval_required',blocker:'Role assignments or exact plugin settings changed. Review the policy again.'};}catch(error){if(!(error instanceof ApiError)||error.status>=500)throw error;return {effectiveStatus:'approval_required',blocker:'The approved reviewer/coordinator agent or sponsor is unavailable.'};}
 return p.reviewsStarted>=p.maxReviews?{effectiveStatus:'exhausted',blocker:'The lifetime reviewer-run limit is exhausted.'}:{effectiveStatus:'active',blocker:null};
}
const caseColumns=`v.id,v.project_id AS "projectId",v.work_item_id AS "workItemId",v.task_id AS "taskId",v.task_revision AS "taskRevision",v.policy_revision AS "policyRevision",v.parent_run_id AS "parentRunId",v.reviewer_run_id AS "reviewerRunId",v.reviewer_agent_id AS "reviewerAgentId",v.producer_agent_id AS "producerAgentId",v.producer_run_id AS "producerRunId",v.submission_sha256 AS "submissionSha256",v.created_at AS "createdAt",r.status AS "runStatus",CASE WHEN d.review_id IS NULL THEN NULL ELSE jsonb_build_object('decision',d.decision,'note',d.note,'taskRevision',d.task_revision,'decidedAt',d.decided_at) END AS decision`;
const caseJoin=`FROM studio_planning_reviews v JOIN agent_runs r ON r.company_id=v.company_id AND r.id=v.reviewer_run_id LEFT JOIN studio_planning_review_decisions d ON d.company_id=v.company_id AND d.review_id=v.id`;
export async function studioReviewPolicySnapshot(client:PoolClient,companyId:string,projectId:string):Promise<StudioReviewPolicySnapshot>{
 if(!(await client.query('SELECT id FROM studio_projects WHERE company_id=$1 AND id=$2',[companyId,projectId])).rowCount)fail(404,'Studio project not found.');
 const p=await policyRow(client,companyId,projectId);let policy:StudioReviewPolicy|null=null;
 if(p){const {authoritySnapshot:_,...fields}=p;policy={...fields,...await effective(client,companyId,p),remainingReviews:Math.max(0,p.maxReviews-p.reviewsStarted),reviewKind:'machine_planning',expiresAt:new Date(p.expiresAt).toISOString(),updatedAt:new Date(p.updatedAt).toISOString()} as StudioReviewPolicy;}
 const reviews=(await client.query(`SELECT ${caseColumns} ${caseJoin} WHERE v.company_id=$1 AND v.project_id=$2 ORDER BY v.created_at DESC,v.id DESC LIMIT 100`,[companyId,projectId])).rows;
 return {policy,reviews:reviews.map(r=>({...r,createdAt:new Date(r.createdAt).toISOString()})) as any,budgetUnit:'reviewer_runs',budgetScope:'separate_from_specialist_and_coordinator_runs',reviewKind:'machine_planning',independentHumanReview:false,startsWorkers:false,startsInference:false};
}
/** Keep model context bounded even when the human history contains long notes. */
export async function studioReviewAgentSnapshot(client:PoolClient,companyId:string,projectId:string,input:unknown){
 const data=studioReviewPolicyGetInput.parse(input);if(data.projectId!==projectId)fail(404,'Planning review project not found.');
 if(data.workItemId&&!(await client.query('SELECT id FROM studio_work_items WHERE company_id=$1 AND project_id=$2 AND id=$3',[companyId,projectId,data.workItemId])).rowCount)fail(404,'Planning work item not found.');
 if(data.after&&!(await client.query('SELECT id FROM studio_planning_reviews WHERE company_id=$1 AND project_id=$2 AND id=$3 AND ($4::uuid IS NULL OR work_item_id=$4)',[companyId,projectId,data.after,data.workItemId??null])).rowCount)fail(404,'Planning review cursor not found in this project and work filter.');
 const {reviews:humanReviews,...state}=await studioReviewPolicySnapshot(client,companyId,projectId),after=data.after?.toLowerCase(),workId=data.workItemId?.toLowerCase();
 const matching=humanReviews.filter(review=>(!workId||review.workItemId===workId)&&(!after||review.id>after)).sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0);
 const compact=matching.slice(0,data.limit).map(review=>{if(!review.decision)return {...review,noteTruncated:false};const points=Array.from(review.decision.note);return {...review,decision:{...review.decision,note:points.slice(0,160).join('')},noteTruncated:points.length>160};});
 const response=(reviews:typeof compact)=>({...state,reviews,page:{hasMore:matching.length>reviews.length,nextAfter:matching.length>reviews.length?reviews.at(-1)?.id??null:null,limit:data.limit,returned:reviews.length,workItemId:data.workItemId??null},projection:{kind:'compact_agent_reviews',noteMaxCodePoints:160,fullSubmissionsIncluded:false,maximumResponseBytes:32000,byteLimitApplied:reviews.length<compact.length}});
 const selected:typeof compact=[];for(const review of compact){if(Buffer.byteLength(JSON.stringify(response([...selected,review])))>32000)break;selected.push(review);}
 const result=response(selected);if(Buffer.byteLength(JSON.stringify(result))>32000||matching.length&&!selected.length)fail(413,'The planning review projection cannot fit its safe model context bound.','REVIEW_CONTEXT_LIMIT');return result;
}
export async function saveStudioReviewPolicy(client:PoolClient,member:Membership,projectId:string,input:unknown){
 const data=studioReviewPolicyInput.parse(input),requestHash=digest({kind:'machine_review_policy',projectId,...data}),actorKey='human:'+member.userId;
 await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`studio-request:${member.companyId}:${actorKey}:${data.clientId}`]);
 const previous=(await client.query('SELECT request_hash,response FROM studio_requests WHERE company_id=$1 AND actor_key=$2 AND client_id=$3',[member.companyId,actorKey,data.clientId])).rows[0];if(previous){if(previous.request_hash!==requestHash)fail(409,'This request key belongs to another operation.','IDEMPOTENCY_CONFLICT');return {...previous.response,replayed:true};}
 const preview=await policyRow(client,member.companyId,projectId),expires=Date.parse(data.expiresAt),exactPause=preview&&data.status==='paused'&&data.coordinatorAgentId===preview.coordinatorAgentId&&data.reviewerAgentId===preview.reviewerAgentId&&digest(data.allowedStages.slice().sort())===digest(preview.allowedStages)&&data.allowSharedSponsor===preview.allowSharedSponsor&&data.maxReviews===preview.maxReviews&&expires===+new Date(preview.expiresAt);
 const snapshot=exactPause?preview!.authoritySnapshot:await configuration(client,member.companyId,data.coordinatorAgentId,data.reviewerAgentId,true);
 await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`studio-review-policy:${member.companyId}:${projectId}`]);
 const old=await policyRow(client,member.companyId,projectId,'UPDATE');if((old?.revision??0)!==data.revision)fail(409,'The machine review policy changed. Refresh it.','REVIEW_POLICY_CONFLICT');
 const project=(await client.query('SELECT status FROM studio_projects WHERE company_id=$1 AND id=$2',[member.companyId,projectId])).rows[0];if(!project)fail(404,'Studio project not found.');if(project.status==='delivered'&&!exactPause)fail(409,'Delivered project work is immutable.');
 await client.query('SELECT role_key FROM studio_role_bindings WHERE company_id=$1 ORDER BY role_key FOR SHARE',[member.companyId]);
 if(!exactPause&&digest(snapshot)!==digest(await configuration(client,member.companyId,data.coordinatorAgentId,data.reviewerAgentId)))fail(409,'The approved configuration changed.','REVIEW_POLICY_CONFLICT');
 if(!exactPause&&(expires<=Date.now()||expires>Date.now()+86400000))fail(400,'Machine review approval must expire within the next 24 hours.');
 if(data.maxReviews<(old?.reviewsStarted??0))fail(409,'Completed, failed and cancelled reviewer runs remain counted.','REVIEW_BUDGET_USED');
 await client.query(`INSERT INTO studio_review_policies(company_id,project_id,coordinator_agent_id,reviewer_agent_id,approved_by,status,allowed_stages,allow_shared_sponsor,authority_snapshot,profile_revision,max_reviews,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(company_id,project_id) DO UPDATE SET coordinator_agent_id=EXCLUDED.coordinator_agent_id,reviewer_agent_id=EXCLUDED.reviewer_agent_id,approved_by=EXCLUDED.approved_by,status=EXCLUDED.status,allowed_stages=EXCLUDED.allowed_stages,allow_shared_sponsor=EXCLUDED.allow_shared_sponsor,authority_snapshot=EXCLUDED.authority_snapshot,profile_revision=EXCLUDED.profile_revision,max_reviews=EXCLUDED.max_reviews,expires_at=EXCLUDED.expires_at,revision=studio_review_policies.revision+1,updated_at=clock_timestamp()`,[member.companyId,projectId,data.coordinatorAgentId,data.reviewerAgentId,member.userId,data.status,JSON.stringify(data.allowedStages.slice().sort()),data.allowSharedSponsor,JSON.stringify(snapshot),snapshot.profileRevision,data.maxReviews,data.expiresAt]);
 const result=await studioReviewPolicySnapshot(client,member.companyId,projectId);await client.query('INSERT INTO studio_requests(company_id,actor_key,client_id,request_hash,response) VALUES($1,$2,$3,$4,$5)',[member.companyId,actorKey,data.clientId,requestHash,JSON.stringify(result)]);
 await client.query('INSERT INTO activity(company_id,actor_id,kind,description) VALUES($1,$2,$3,$4)',[member.companyId,member.userId,'studio.machine_review_policy','An administrator configured a finite machine planning review policy. This is not independent human review.']);return {...result,replayed:false};
}
function reviewerGrant(agent:Row,run:Row){if(!agent.capabilities?.includes(STUDIO_REVIEW_CAPABILITY)||!run.capabilities?.includes(STUDIO_REVIEW_CAPABILITY))fail(403,'A separately approved studio.review grant is required.','AGENT_CAPABILITY_REQUIRED');}
async function activePolicy(client:PoolClient,companyId:string,projectId:string,revision:number,lock:'SHARE'|'UPDATE'='SHARE'){
 const p=await policyRow(client,companyId,projectId,lock);if(!p)fail(404,'Machine review policy not found.');if(p.revision!==revision)fail(409,'Machine review approval changed.','REVIEW_POLICY_CONFLICT');const state=await effective(client,companyId,p);if(!['active','exhausted'].includes(state.effectiveStatus))fail(409,state.blocker!,'STUDIO_REVIEW_AUTHORITY_ENDED');return p;
}
async function nestedRun(client:PoolClient,companyId:string,runId:string){return Boolean((await client.query('SELECT child_run_id FROM studio_coordination_dispatches WHERE company_id=$1 AND child_run_id=$2 UNION ALL SELECT child_run_id FROM studio_coordination_followups WHERE company_id=$1 AND child_run_id=$2 UNION ALL SELECT child_run_id FROM studio_generated_followups WHERE company_id=$1 AND child_run_id=$2 UNION ALL SELECT reviewer_run_id FROM studio_planning_reviews WHERE company_id=$1 AND reviewer_run_id=$2',[companyId,runId])).rowCount);}
async function workSubmission(client:PoolClient,companyId:string,projectId:string,workItemId:string,policy:Row,taskRevision:number){
 const work=(await client.query('SELECT w.id,w.task_id,w.stage,w.execution,b.agent_id FROM studio_work_items w LEFT JOIN studio_role_bindings b ON b.company_id=w.company_id AND b.role_key=w.role_key WHERE w.company_id=$1 AND w.project_id=$2 AND w.id=$3',[companyId,projectId,workItemId])).rows[0];if(!work)fail(404,'Studio work item not found.');
 if(work.execution!=='agent'||!policy.allowedStages.includes(work.stage))fail(403,'This policy covers only its explicitly allowed agent-executed planning stages.','REVIEW_STAGE_REQUIRED');
 await assertStudioTaskAction(client,companyId,work.task_id,'human_update',{status:'done'});
 const task=(await client.query('SELECT t.*,a.created_by AS producer_sponsor,r.status AS source_status,r.agent_id AS source_agent FROM tasks t LEFT JOIN agents a ON a.company_id=t.company_id AND a.id=t.submitted_agent_id LEFT JOIN agent_runs r ON r.company_id=t.company_id AND r.id=t.agent_run_id WHERE t.company_id=$1 AND t.id=$2 FOR UPDATE OF t',[companyId,work.task_id])).rows[0];
 if(task.status!=='review'||task.revision!==taskRevision)fail(409,'The exact submitted task revision is no longer awaiting review.','REVIEW_SUBMISSION_CHANGED');
 if(!task.submitted_agent_id||task.submitted_by||task.assignee_id||!task.submission_summary||task.source_status!=='succeeded'||task.source_agent!==task.submitted_agent_id||work.agent_id!==task.submitted_agent_id)fail(409,'Machine review requires an unchanged completed agent submission by the assigned producer.','REVIEW_SOURCE_UNAVAILABLE');
 if((await client.query('SELECT id FROM studio_planning_reviews WHERE company_id=$1 AND project_id=$2 AND work_item_id=$3 AND producer_run_id=$4 AND task_revision<>$5 LIMIT 1',[companyId,projectId,workItemId,task.agent_run_id,taskRevision])).rowCount)fail(409,'A recorded review cannot be rerolled by editing a task revision. A new producer submission is required.','REVIEW_RESUBMISSION_REQUIRED');
 if([task.submitted_agent_id,task.created_agent_id].includes(policy.reviewerAgentId)||(await client.query('SELECT id FROM contributions WHERE company_id=$1 AND task_id=$2 AND agent_id=$3 LIMIT 1',[companyId,task.id,policy.reviewerAgentId])).rowCount)fail(403,'An agent cannot review its own current or historical work.','REVIEW_SELF_APPROVAL');
 const reviewerSponsor=policy.authoritySnapshot.agents.find((a:Row)=>a.agentId===policy.reviewerAgentId).sponsorId;
 if(!policy.allowSharedSponsor&&(task.producer_sponsor===reviewerSponsor||(await client.query('SELECT user_id FROM task_authors WHERE task_id=$1 AND user_id=$2',[task.id,reviewerSponsor])).rowCount))fail(403,'Shared sponsorship needs explicit machine review policy approval.','REVIEW_SHARED_SPONSOR');
 const p=(await client.query('SELECT id,name,brief,spec,ai_policy,gates FROM studio_projects WHERE company_id=$1 AND id=$2',[companyId,projectId])).rows[0];
 const brief={id:p.id,name:p.name,brief:p.brief,spec:p.spec,aiPolicy:p.ai_policy,approvedBrief:p.gates.brief};
 const inputs=work.stage==='ingest'?(await client.query('SELECT id,name,kind,storage_key AS "storageKey",sha256,bytes::text AS "sizeBytes" FROM studio_execution_inputs WHERE company_id=$1 AND project_id=$2 ORDER BY id LIMIT 33',[companyId,projectId])).rows:[];if(inputs.length>32)fail(413,'This ingest review exceeds its 32-reference bound. Use an administrator review.','REVIEW_CONTEXT_LIMIT');
 const submission={schemaVersion:1,reviewKind:'machine_planning',independentHumanReview:false,contentInspected:false,project:brief,work:{id:work.id,stage:work.stage,execution:work.execution},task:{id:task.id,revision:task.revision,title:task.title,description:task.description,summary:task.submission_summary,url:task.submission_url,producerAgentId:task.submitted_agent_id,producerRunId:task.agent_run_id},inputReferences:inputs};
 if(Buffer.byteLength(canonicalStudioReview(submission))>64000)fail(413,'The exact review snapshot exceeds 64 KB. Use administrator review.','REVIEW_CONTEXT_LIMIT');return {task,submission,briefSha256:digest(brief)};
}
export async function dispatchStudioReview(client:PoolClient,agent:Row,run:Row,input:unknown){
 const data=studioReviewDispatchInput.parse(input),companyId=agent.company_id;
 if(await nestedRun(client,companyId,run.id))fail(403,'A specialist or reviewer cannot schedule another reviewer.','REVIEW_NESTED_DISPATCH');
 const preview=await policyRow(client,companyId,data.projectId);if(!preview)fail(404,'Machine review policy not found.');if(preview.coordinatorAgentId!==agent.id)fail(403,'Only the explicitly approved coordinator can queue reviews.','REVIEW_COORDINATOR_REQUIRED');
 await client.query('SELECT user_id FROM memberships WHERE company_id=$1 AND user_id=$2 FOR SHARE',[companyId,preview.approvedBy]);await configuration(client,companyId,preview.coordinatorAgentId,preview.reviewerAgentId,true);
 await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`studio-review-policy:${companyId}:${data.projectId}`]);const policy=await activePolicy(client,companyId,data.projectId,data.policyRevision,'UPDATE');
 const prior=(await client.query('SELECT id,reviewer_run_id AS "reviewerRunId" FROM studio_planning_reviews WHERE company_id=$1 AND project_id=$2 AND work_item_id=$3 AND task_revision=$4',[companyId,data.projectId,data.workItemId,data.taskRevision])).rows[0];if(prior)return {reviewId:prior.id,reviewerRunId:prior.reviewerRunId,replayed:true};
 if(policy.reviewsStarted>=policy.maxReviews)fail(409,'The lifetime reviewer-run limit is exhausted.','REVIEW_RUN_BUDGET');
 const reviewId=randomUUID(),user=(await client.query('SELECT id,name,email,role_title AS "roleTitle",avatar_color AS "avatarColor",avatar_id AS "avatarId",(email_verified_at IS NOT NULL) AS "emailVerified" FROM users WHERE id=$1',[policy.approvedBy])).rows[0];
 const queued=await createAgentRunInTransaction(client,{companyId,userId:policy.approvedBy,role:'admin',user} as Membership,'commons',{clientId:uuidFor(`coatria-planning-review:${companyId}:${data.projectId}:${data.workItemId}:${data.taskRevision}`),agentId:policy.reviewerAgentId,prompt:`Perform the explicitly authorized machine planning review ${reviewId}. First call studio_review_read with reviewId ${reviewId}; review the exact immutable task submission and approved brief returned. This is machine review, not independent human review. Then call studio_review_decide with the returned policyRevision and submissionSha256, a specific evidence-based note, and approve, changes_requested, or reject. Approve only if the submitted planning contribution is supported and meets the brief. Do not execute or change the work, claim that media was decoded, approve commercial/production/client gates, approve rendered media or schedule any further agents. A missing input or uncertainty requires changes_requested or reject. Return only actual recorded review state.`});
 const current=await workSubmission(client,companyId,data.projectId,data.workItemId,policy,data.taskRevision);if((await effective(client,companyId,policy)).effectiveStatus!=='active')fail(409,'Machine review approval changed before dispatch committed.','STUDIO_REVIEW_AUTHORITY_ENDED');
 // This child reviews one pinned submission. Installation-wide studio reads
 // would add unrelated tool schemas and authority to every inference step.
 await client.query("UPDATE agent_runs SET max_attempts=1,capabilities='[\"studio.review\"]'::jsonb WHERE company_id=$1 AND id=$2",[companyId,queued.run.id]);
 await client.query('INSERT INTO studio_planning_reviews(id,company_id,project_id,work_item_id,task_id,task_revision,policy_revision,parent_run_id,reviewer_run_id,reviewer_agent_id,producer_agent_id,producer_run_id,submission,submission_sha256,brief_sha256) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)',[reviewId,companyId,data.projectId,data.workItemId,current.task.id,data.taskRevision,policy.revision,run.id,queued.run.id,policy.reviewerAgentId,current.task.submitted_agent_id,current.task.agent_run_id,JSON.stringify(current.submission),digest(current.submission),current.briefSha256]);
 await client.query('UPDATE studio_review_policies SET reviews_started=reviews_started+1 WHERE company_id=$1 AND project_id=$2',[companyId,data.projectId]);return {reviewId,reviewerRunId:queued.run.id,replayed:false};
}
async function exactCase(client:PoolClient,companyId:string,reviewId:string){const row=(await client.query(`SELECT ${caseColumns},v.submission,v.brief_sha256 AS "briefSha256" ${caseJoin} WHERE v.company_id=$1 AND v.id=$2`,[companyId,reviewId])).rows[0];if(!row)fail(404,'Planning review not found.');return row;}
export async function getStudioPlanningReview(client:PoolClient,companyId:string,projectId:string,reviewId:string){const review=await exactCase(client,companyId,reviewId);if(review.projectId!==projectId)fail(404,'Planning review not found in this project.');return {review,reviewKind:'machine_planning',independentHumanReview:false,contentInspected:false};}
async function ownedCase(client:PoolClient,agent:Row,run:Row,reviewId:string){reviewerGrant(agent,run);const review=await exactCase(client,agent.company_id,reviewId);if(review.reviewerAgentId!==agent.id||review.reviewerRunId!==run.id)fail(403,'Only the exact separately assigned reviewer run can read and decide this submission.','REVIEW_RUN_REQUIRED');return review;}
export async function readStudioPlanningReview(client:PoolClient,agent:Row,run:Row,input:unknown){
 const data=studioReviewReadInput.parse(input),review=await ownedCase(client,agent,run,data.reviewId);await activePolicy(client,agent.company_id,review.projectId,review.policyRevision);
 await client.query('INSERT INTO studio_planning_review_reads(company_id,review_id,run_id) VALUES($1,$2,$3) ON CONFLICT(company_id,review_id) DO NOTHING',[agent.company_id,review.id,run.id]);
 return {reviewId:review.id,policyRevision:review.policyRevision,submissionSha256:review.submissionSha256,submission:review.submission,reviewKind:'machine_planning',independentHumanReview:false,contentInspected:false};
}
export async function decideStudioPlanningReview(client:PoolClient,agent:Row,run:Row,input:unknown){
 const data=studioReviewDecideInput.parse(input),companyId=agent.company_id,review=await ownedCase(client,agent,run,data.reviewId),policy=await activePolicy(client,companyId,review.projectId,data.policyRevision);
 if(review.policyRevision!==data.policyRevision||data.submissionSha256!==review.submissionSha256)fail(409,'Use the exact policy and immutable submission checksum returned by the read tool.','REVIEW_SUBMISSION_CHANGED');
 if(!(await client.query('SELECT review_id FROM studio_planning_review_reads WHERE company_id=$1 AND review_id=$2 AND run_id=$3',[companyId,review.id,run.id])).rowCount)fail(409,'Read this exact immutable submission before deciding.','REVIEW_READ_REQUIRED');
 if(review.decision){if(review.decision.decision!==data.decision||review.decision.note!==data.note)fail(409,'This immutable review already has a different decision.','REVIEW_DECISION_EXISTS');return {reviewId:review.id,decision:review.decision,replayed:true,reviewKind:'machine_planning',independentHumanReview:false};}
 const current=await workSubmission(client,companyId,review.projectId,review.workItemId,policy,review.taskRevision);
 if(digest(current.submission)!==review.submissionSha256||current.briefSha256!==review.briefSha256)fail(409,'The submission or approved brief changed after the review snapshot.','REVIEW_SUBMISSION_CHANGED');
 const next=data.decision==='approve'?'done':data.decision==='changes_requested'?'todo':'review';
 const task=(await client.query('UPDATE tasks SET status=$3,review_note=$4,approved_by=NULL,approved_agent_id=$5,machine_review_id=$6,agent_run_id=CASE WHEN $3 IN (\'done\',\'todo\') THEN NULL ELSE agent_run_id END,revision=revision+1,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2 RETURNING id,status,revision,approved_by AS "approvedBy",approved_agent_id AS "approvedAgentId",machine_review_id AS "machineReviewId"',[companyId,review.taskId,next,`Machine planning review: ${data.note}`,data.decision==='approve'?agent.id:null,data.decision==='approve'?review.id:null])).rows[0];
 const decision=(await client.query('INSERT INTO studio_planning_review_decisions(company_id,review_id,decision,note,task_revision) VALUES($1,$2,$3,$4,$5) RETURNING decision,note,task_revision AS "taskRevision",decided_at AS "decidedAt"',[companyId,review.id,data.decision,data.note,task.revision])).rows[0];
 await client.query('UPDATE studio_projects SET revision=revision+1,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2',[companyId,review.projectId]);
 await client.query('INSERT INTO activity(company_id,kind,description) VALUES($1,$2,$3)',[companyId,'studio.machine_review_decided',`A separately assigned agent recorded ${data.decision} for one exact planning submission under an administrator-approved machine review policy. This was not independent human review.`]);
 return {reviewId:review.id,task,decision,replayed:false,reviewKind:'machine_planning',independentHumanReview:false};
}
/** Agent/run -> policy; never lock project across generic run completion. */
export async function studioReviewRunAuthority(client:PoolClient,companyId:string,run:Row):Promise<boolean>{
 if(!['queued','running'].includes(run.status))return true;
 const review=(await client.query('SELECT project_id,policy_revision FROM studio_planning_reviews WHERE company_id=$1 AND reviewer_run_id=$2',[companyId,run.id])).rows[0];if(!review)return true;
 const p=await policyRow(client,companyId,review.project_id,'SHARE');if(!p||p.revision!==review.policy_revision)return false;return ['active','exhausted'].includes((await effective(client,companyId,p)).effectiveStatus);
}
export const planningReviewRunAuthority=studioReviewRunAuthority;
export async function studioReviewPolicyRoute(request:Request,parts:string[],method:string):Promise<Response|null>{
 if(parts[0]!=='companies'||parts[2]!=='studio'||parts[3]!=='projects'||!((parts.length===6&&parts[5]==='review-policy'&&['GET','PUT'].includes(method))||(parts.length===7&&parts[5]==='planning-reviews'&&method==='GET')))return null;
 const member=await requireMembership(request,id(parts[1]),method==='PUT'),projectId=id(parts[4]);
 if(parts[5]==='planning-reviews')return json(await memberMutation(member,false,client=>getStudioPlanningReview(client,member.companyId,projectId,id(parts[6]))));
 if(method==='GET')return json(await memberMutation(member,false,client=>studioReviewPolicySnapshot(client,member.companyId,projectId)));
 const data=await body(request,studioReviewPolicyInput);return json(await memberMutation(member,true,client=>saveStudioReviewPolicy(client,member,projectId,data)));
}
