/** Exact immutable staffing snapshots; optional fields preserve previously saved v1 plans. */
type Schema=Record<string,unknown>;
const uuid:Schema={type:'string',format:'uuid'},text:Schema={type:'string'},date:Schema={type:'string',format:'date-time'},integer:Schema={type:'integer'},nullable=(value:Schema):Schema=>({anyOf:[value,{type:'null'}]}),array=(value:Schema,max=100):Schema=>({type:'array',items:value,maxItems:max}),ref=(name:string):Schema=>({$ref:'#/components/schemas/'+name});
const object=(properties:Record<string,Schema>,required=Object.keys(properties)):Schema=>({type:'object',properties,required,additionalProperties:false});
const provider=object({pluginId:text,manifestVersion:text,runtimeConfig:ref('PluginRuntimeConfig')});
const existing=object({agentId:uuid,installationId:uuid,installationRevision:integer,name:text,sponsorId:uuid,status:text,expiresAt:date,invocationAccess:text,conversationAccess:text,capabilities:array(text,30),pluginId:text,manifestVersion:text,runtimeConfig:ref('PluginRuntimeConfig'),character:ref('AgentCharacter')});
const specialist=object({key:text,name:text,roleKeys:array(text,10),skillKeys:array(text,30),skills:array(object({key:text,title:text,version:integer,instructions:text}),30),character:ref('AgentCharacter'),mode:{enum:['create','bind']},capabilities:array(text,30),invocationAccess:text,conversationAccess:text,provider,existing:nullable(existing)});
const reviewer:Schema={allOf:[ref('StudioStaffingSpecialist'),{type:'object',properties:{key:{const:'planning-reviewer'},roleKeys:{const:[]},mode:{const:'create'},existing:{type:'null'},capabilities:{const:['studio.read','studio.review']},invocationAccess:{const:'admins'},conversationAccess:{const:'none'}}}],description:'Optional distinct planning-review identity. Consumes one total team slot. No producing or human QC role. Versioned instructions are saved in its installation persona; no private-vault skill is created. Starts paused. Host enrollment and an exact finite project review policy, including shared-sponsor consent when applicable, are separate.'};
const appliedIdentity=object({key:text,name:text,roleKeys:array(text,10),agentId:uuid,installationId:uuid,mode:{enum:['create','bind']},status:text,connectionState:{enum:['unconnected','unverified']},credentialState:{enum:['not_issued','existing']},capabilities:array(text,30)});
const appliedReviewer:Schema={allOf:[ref('StudioStaffingAppliedIdentity'),{type:'object',properties:{key:{const:'planning-reviewer'},roleKeys:{const:[]},mode:{const:'create'},status:{const:'paused'},connectionState:{const:'unconnected'},credentialState:{const:'not_issued'},capabilities:{const:['studio.read','studio.review']}}}],description:'Creation receipt for the separate reviewer, not its later live enrollment or policy state. No plaintext credential.'};
const applicationProperties={proposalId:uuid,profileRevision:integer,specialists:array(ref('StudioStaffingAppliedIdentity'),11),planningReviewer:appliedReviewer,reviewerHumanId:nullable(uuid),startsWorkers:{const:false},startsInference:{const:false},credentialDelivery:{const:'not_issued'}};
const application=object(applicationProperties,Object.keys(applicationProperties).filter(key=>key!=='planningReviewer'));
const planProperties={version:{const:1},templateId:{const:'vfx-boutique'},templateVersion:{const:1},brief:text,requestedAgentCount:{type:'integer',minimum:1,maximum:11},actualAgentCount:{type:'integer',minimum:1,maximum:11},newAgentCount:{type:'integer',minimum:0,maximum:11},disciplines:array(text,7),reviewer:nullable(object({humanId:uuid,name:text,role:{enum:['owner','admin']}})),profileRevision:integer,specialists:array(ref('StudioStaffingSpecialist'),11),planningReviewer:reviewer,unassignedRoleKeys:array(text,10),warnings:array(text,20),startsWorkers:{const:false},startsInference:{const:false},copiesPrivateSkills:{const:false},newIdentityStatus:{const:'paused'},credentialDelivery:{const:'not_issued'}};
const plan:Schema={...object(planProperties,Object.keys(planProperties).filter(key=>key!=='planningReviewer')),description:'Immutable plan hash covers exact production groups, optional separate planning reviewer, human QC assignment, saved instructions, provider settings and grants. Omitted planningReviewer remains omitted for existing v1 plans. No credentials, policy activation or compute.'};
const proposal=object({id:uuid,companyId:uuid,revision:integer,status:{enum:['pending','applied','rejected']},plan:ref('StudioStaffingPlan'),planHash:{type:'string',pattern:'^[a-f0-9]{64}$'},profileRevision:integer,createdBy:uuid,createdAgentId:nullable(uuid),runId:nullable(uuid),createdAt:date,expiresAt:date,appliedBy:nullable(uuid),appliedAt:nullable(date),result:nullable(ref('StudioStaffingApplication')),rejectionNote:nullable(text)});
export const studioStaffingSchemas:Record<string,Schema>={StudioStaffingPlan:plan,StudioStaffingSpecialist:specialist,StudioStaffingAppliedIdentity:appliedIdentity,StudioStaffingApplication:application,StudioStaffingProposal:proposal};
