import {z} from 'zod';

const uuid=z.string().uuid(), text=(n:number)=>z.string().trim().min(1).max(n);
export const STUDIO_DISCIPLINES=['prep','matchmove','layout','animation','fx','lighting','compositing'] as const;
export const STUDIO_SKILLS=[
 {key:'client-discovery',title:'Client discovery & scope',version:1,instructions:'Capture the client objective, delivery specification, references, deadline, rights and AI-use restrictions. Separate confirmed requirements from assumptions. Identify missing information before estimating. Never promise a price, deadline or rights clearance on the client’s behalf.'},
 {key:'production-planning',title:'Shot breakdown & scheduling',version:1,instructions:'Break the approved brief into sequences and shots. Identify disciplines, inputs, dependencies, milestones and accountable roles. Use the current studio API state. Estimate effort as ranges with assumptions; require human estimate and production approval. Reuse existing work IDs and never duplicate a shot or accepted task.'},
 {key:'vfx-supervision',title:'VFX supervision',version:1,instructions:'Define a shot-specific creative target and measurable acceptance criteria. Identify plate, camera, lens, lighting and reference requirements. Distinguish creative approval, technical QC and client acceptance. Inspect actual versioned outputs; a model report cannot prove image quality.'},
 {key:'media-ingest',title:'Media ingest & provenance',version:1,instructions:'Verify source authorization, checksums, frame ranges, handles, resolution, rational frame rate and color configuration. Keep originals on approved storage. Register immutable versions and provenance. A file listing is not access to the media; block work if the approved media connector is unavailable.'},
 {key:'tracking-prep',title:'Prep, roto & matchmove',version:1,instructions:'Use approved plates and calibrated lens/camera data. Record tool versions, frame ranges and output references. Publish reproducible tracking/prep outputs and known limitations. Do not claim roto, camera solves or cleanup were executed unless an artist or connected DCC actually produced the files.'},
 {key:'cg-production',title:'Layout, assets & animation',version:1,instructions:'Use a versioned scene description, consistent units, approved assets and camera conventions. Preserve source dependencies and license provenance. Publish actual geometry, scene or animation artifacts with tool versions. Use OpenUSD where the pipeline supports it; never assume DCC interoperability without validation.'},
 {key:'fx-simulation',title:'FX simulation',version:1,instructions:'Define a bounded simulation test, cache naming, deterministic seeds where possible and storage/render estimates. Check approved tools and compute budget before execution. Register actual caches and preview versions. Escalate missing DCC licenses or unavailable execution connectors.'},
 {key:'lighting-render',title:'Lighting & rendering',version:1,instructions:'Check scene, camera, shading, color management, AOVs and render settings. Submit only to an approved render connector with a job receipt and budget. A queued job is not a successful render. Validate the complete expected frame range and publish checksummed artifacts.'},
 {key:'compositing',title:'Compositing & finishing',version:1,instructions:'Work from approved plates and upstream versions. Preserve an explicit OCIO/color-space convention and delivery spec. Record Nuke/other DCC version and source dependencies. Review actual rendered frames for edges, grain, color and temporal defects; never substitute a written summary for an image sequence.'},
 {key:'technical-qc',title:'Independent technical QC',version:1,instructions:'Independently inspect exact published versions, frame continuity, handles, dimensions, frame rate, color, channels, naming and checksums. Distinguish metadata assertions from verified media. Record failures and evidence. The producing agent or its sponsor cannot approve its own artifact.'},
 {key:'delivery-management',title:'Delivery & change control',version:1,instructions:'Package exact approved versions and checksums in a manifest with client/project specification and review receipts. Preparing a manifest does not upload or deliver the media. Record transfer and client acceptance only from actual evidence supplied by an authorized human. Preserve prior deliveries and route changes into new work.'},
] as const;

const role=(key:string,title:string,department:string,skills:string[],reportsTo:string|null)=>({key,title,department,skills,reportsTo});
export const STUDIO_TEMPLATES=[{
 id:'vfx-boutique',version:1,name:'AI + VFX production studio',description:'A supervised studio from client brief to versioned delivery, with specialist AI roles and explicit artist, client and compute handoffs.',
 roles:[role('producer','Executive producer','Client & business',['client-discovery'],'studio-owner'),role('coordinator','Production coordinator','Production',['production-planning'],'producer'),role('supervisor','VFX supervisor','Creative supervision',['vfx-supervision'],'producer'),role('ingest','Media & pipeline coordinator','Pipeline',['media-ingest'],'coordinator'),role('prep','Prep & tracking specialist','VFX',['tracking-prep'],'supervisor'),role('cg','CG & animation specialist','CG',['cg-production'],'supervisor'),role('fx','FX specialist','CG',['fx-simulation'],'supervisor'),role('lighting','Lighting & render specialist','CG',['lighting-render'],'supervisor'),role('comp','Compositing specialist','VFX',['compositing'],'supervisor'),role('qc','Independent quality reviewer','Quality',['technical-qc'],'studio-owner'),role('delivery','Delivery producer','Delivery',['delivery-management'],'producer')],
 stages:['Client intake','Scope & estimate','Shot breakdown','Media ingest','VFX / CG production','Creative & technical review','Delivery manifest','Client acceptance'],
 gates:[{key:'brief',title:'Client brief agreed'},{key:'estimate',title:'Scope & estimate approved'},{key:'production',title:'Production authorized'},{key:'client_acceptance',title:'Client acceptance recorded'}],
 integrations:[{key:'storage',title:'Approved media storage',requiredFor:'Original plates and heavy media; current infrastructure indexes metadata only.'},{key:'dcc',title:'Artist or DCC execution connector',requiredFor:'Nuke, Blender, Houdini and other actual scene/image processing; licenses and execution are separate.'},{key:'render',title:'Render queue',requiredFor:'Approved compute, frame/job receipts and actual outputs.'},{key:'transfer',title:'Client delivery transport',requiredFor:'Media transfer and receipt; manifest export alone is not delivery.'}],
}] as const;

export const studioCompanyPlanInput=z.object({templateId:z.literal('vfx-boutique').default('vfx-boutique'),teamSize:z.number().int().min(1).max(100).optional()}).strict();
export function planStudioCompany(input:unknown){const data=studioCompanyPlanInput.parse(input);return {template:STUDIO_TEMPLATES[0],skills:STUDIO_SKILLS,requestedTeamSize:data.teamSize??null,rolesAreAssignments:true,createsWorkers:false,requiresAdministratorApplication:true};}
export const studioAssignmentInput=z.object({roleKey:text(60),agentId:uuid.nullable().default(null),humanId:uuid.nullable().default(null)}).strict().refine(v=>!(v.agentId&&v.humanId),'Choose a person or an agent for a role, not both.');
export const studioSetupInput=z.object({clientId:uuid,templateId:z.literal('vfx-boutique'),templateVersion:z.literal(1),revision:z.number().int().min(0),assignments:z.array(studioAssignmentInput).max(30).default([])}).strict().refine(v=>new Set(v.assignments.map(a=>a.roleKey)).size===v.assignments.length,'Role assignments must be unique.');
export const studioSpecInput=z.object({width:z.number().int().min(16).max(32768),height:z.number().int().min(16).max(32768),fpsNumerator:z.number().int().min(1).max(120000),fpsDenominator:z.number().int().min(1).max(1001),format:z.enum(['exr','mov','mp4']),colorSpace:text(120)}).strict();
export const studioShotInput=z.object({code:z.string().trim().regex(/^[A-Za-z0-9][A-Za-z0-9_-]{0,39}$/),description:text(2000),frameStart:z.number().int().min(0).max(10000000),frameEnd:z.number().int().min(0).max(10000000),handles:z.number().int().min(0).max(1000).default(8),disciplines:z.array(z.enum(STUDIO_DISCIPLINES)).min(1).max(7)}).strict().refine(v=>v.frameEnd>=v.frameStart&&v.frameEnd-v.frameStart<=100000,'Use a valid shot frame range.').refine(v=>new Set(v.disciplines).size===v.disciplines.length,'Shot disciplines must be unique.');
export const studioProjectPlanInput=z.object({name:text(160),clientName:text(160),brief:text(12000),dueDate:z.string().date().nullable().default(null),spec:studioSpecInput,aiPolicy:z.enum(['unknown','allowed','restricted']).default('unknown'),shots:z.array(studioShotInput).min(1).max(100)}).strict().refine(v=>new Set(v.shots.map(s=>s.code.toLowerCase())).size===v.shots.length,'Shot codes must be unique.');
export const studioProjectInput=studioProjectPlanInput.safeExtend({clientId:uuid});
export const studioProjectPatchInput=z.object({clientId:uuid,revision:z.number().int().min(1),aiPolicy:z.enum(['unknown','allowed','restricted']).optional(),brief:text(12000).optional(),dueDate:z.string().date().nullable().optional()}).strict().refine(v=>v.aiPolicy!==undefined||v.brief!==undefined||v.dueDate!==undefined,'Provide a project change.');
export const studioDispatchInput=z.object({clientId:uuid,revision:z.number().int().min(1),workItemId:uuid}).strict();
export const studioArtifactRegisterInput=z.object({revision:z.number().int().min(1),workItemId:uuid,name:text(160),url:z.string().url().max(2048).refine(v=>{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password&&!u.hash;},'Use an HTTPS artifact reference without embedded credentials.'),sha256:z.string().regex(/^[a-fA-F0-9]{64}$/).transform(v=>v.toLowerCase()),frameStart:z.number().int().min(0),frameEnd:z.number().int().min(0),width:z.number().int().min(16).max(32768),height:z.number().int().min(16).max(32768),fpsNumerator:z.number().int().min(1).max(120000),fpsDenominator:z.number().int().min(1).max(1001),colorSpace:text(120),format:z.enum(['exr','mov','mp4']),notes:z.string().trim().max(4000).default('')}).strict().refine(v=>v.frameEnd>=v.frameStart,'Use a valid artifact frame range.');
export const studioArtifactInput=studioArtifactRegisterInput.safeExtend({clientId:uuid});
export const studioGateInput=z.object({clientId:uuid,revision:z.number().int().min(1),gate:z.enum(['brief','estimate','production','client_acceptance']),decision:z.enum(['approved','changes_requested']),note:text(4000),deliveryId:uuid.optional()}).strict().refine(v=>v.gate!=='client_acceptance'||v.decision!=='approved'||Boolean(v.deliveryId),'Select the exact delivery package the client accepted.').refine(v=>v.deliveryId===undefined||v.gate==='client_acceptance'&&v.decision==='approved','A delivery reference applies only to recorded client acceptance.');
export const studioReviewInput=z.object({clientId:uuid,revision:z.number().int().min(1),artifactId:uuid,decision:z.enum(['approved','changes_requested']),note:text(4000),technicalQc:z.boolean()}).strict();
export const studioDeliveryInput=z.object({clientId:uuid,revision:z.number().int().min(1),name:text(160),artifactIds:z.array(uuid).min(1).max(100),note:text(4000)}).strict().refine(v=>new Set(v.artifactIds).size===v.artifactIds.length,'Artifact IDs must be unique.');
export type StudioRole={key:string;title:string;department:string;skills:string[];reportsTo:string|null;agentId:string|null;humanId:string|null;agentName?:string|null;humanName?:string|null;connectionState?:string|null};
export type StudioProject={id:string;name:string;clientName:string;brief:string;dueDate:string|null;spec:z.infer<typeof studioSpecInput>;aiPolicy:'unknown'|'allowed'|'restricted';revision:number;status:string;gates:Record<string,{decision:string;note:string;recordedBy:string;at:string;deliveryId?:string;source?:'authenticated_external_client';clientDeliveryId?:string;clientReceiptId?:string;packageSha256?:string}>;createdAt:string;updatedAt:string;shotCount?:number;workCount?:number;acceptedCount?:number};
export type StudioShot={id:string;code:string;description:string;frameStart:number;frameEnd:number;handles:number;disciplines:string[]};
export type StudioWorkItem={id:string;taskId:string;title:string;stage:string;roleKey:string;shotId:string|null;dependencies:string[];status:'todo'|'doing'|'review'|'done';readiness:'blocked'|'ready'|'queued'|'running'|'review'|'accepted';blockedReason:string|null;revision:number;execution:'agent'|'dcc'|'human';agentId:string|null;humanId:string|null;submissionSummary?:string;approvedBy?:string|null;approvedAgentId?:string|null;machineReviewId?:string|null;runId?:string|null;runStatus?:string|null};
export type StudioArtifact={id:string;workItemId:string;name:string;version:number;url:string;sha256:string;frameStart:number;frameEnd:number;width:number;height:number;fpsNumerator:number;fpsDenominator:number;colorSpace:string;format:string;notes:string;reviewStatus:'pending'|'approved'|'changes_requested';createdAt:string;producedBy:string;producedAgentId:string|null};
export type StudioReview={id:string;artifactId:string;decision:string;note:string;technicalQc:boolean;reviewedBy:string;createdAt:string};
export type StudioDelivery={id:string;name:string;status:'prepared'|'acknowledged';manifest:Record<string,unknown>;note:string;createdAt:string};
export type StudioSnapshot={templates:typeof STUDIO_TEMPLATES;skills:typeof STUDIO_SKILLS;profile:null|{templateId:string;revision:number;roles:StudioRole[]};projects:StudioProject[];hasMore:boolean;nextAfter:string|null};
export type StudioProjectDetail={project:StudioProject;shots:StudioShot[];workItems:StudioWorkItem[];artifacts:StudioArtifact[];reviews:StudioReview[];deliveries:StudioDelivery[];roles:StudioRole[];skills:typeof STUDIO_SKILLS};
