/** Bounded, server-owned archive/gateway CPU provisioning. No agent enrollment,
 * credential projection, generic container parameters or provider create retry. */
import {randomUUID} from 'node:crypto';
import {Pool,type PoolClient} from 'pg';
import {transaction} from './db';
import {lockMembership,type Membership} from './auth';
import {fail,hashToken,id} from './security';
import {trustedServicePlanInput,trustedServiceStartInput,trustedServiceStopInput,type TrustedServiceKind} from './trusted-service-protocol';
import {TRUSTED_SERVICE_IMAGE,TRUSTED_SERVICE_DATABASE_ROLES,trustedServicePreset,trustedServiceHash,trustedServiceEnvironment,trustedServiceReadiness,type TrustedServicePreset} from './trusted-service-config';
import {assertHiggsfieldArchiveDatabase} from './higgsfield-archive-preflight';
import {assertProjectStorageGatewayDatabase} from './project-storage-preflight';

type Row=Record<string,any>;
type Dependencies={fetch?:typeof fetch;transaction?:typeof transaction;verifyDatabase?:(service:TrustedServiceKind,url:string,companyId:string)=>Promise<void>};
const active=['approved','submitting','uncertain','provisioning','running','stopping','needs_attention'],stopped=new Set(['EXITED','TERMINATED']);
const parse=<T>(schema:{safeParse:(value:unknown)=>{success:boolean;data?:T}},value:unknown):T=>{const result=schema.safeParse(value);if(!result.success)fail(400,'Review the required service fields.','VALIDATION_ERROR');return result.data!;};
async function control(db:PoolClient,companyId:string){await db.query('SELECT id FROM companies WHERE id=$1 FOR KEY SHARE',[companyId]);await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`trusted-service-control:${companyId}`]);}
async function rowFor(db:PoolClient,companyId:string,provisionId:string){const row=(await db.query('SELECT * FROM trusted_service_provisions WHERE company_id=$1 AND id=$2 FOR UPDATE',[companyId,id(provisionId)])).rows[0];if(!row)fail(404,'Trusted service request not found.');return row;}
async function dbNow(db:PoolClient){return +new Date((await db.query('SELECT clock_timestamp() AS now')).rows[0].now);}
async function reserved(db:PoolClient,companyId:string,service:string){return Number((await db.query('SELECT COALESCE(sum(amount_microusd),0) amount FROM trusted_service_reservations WHERE company_id=$1 AND service=$2',[companyId,service])).rows[0].amount);}
function project(row:Row){return {id:row.id,companyId:row.company_id,service:row.service,revision:row.revision,phase:row.phase,plan:row.plan,planHash:row.plan_hash,podId:row.pod_id,providerStatus:row.provider_status,expiresAt:row.expires_at,stopRequestedAt:row.stop_requested_at,submittedAt:row.submitted_at,lastReconciledAt:row.last_reconciled_at,errorCode:row.error_code,createdAt:row.created_at,computeStopped:row.phase==='stopped',serviceVerified:false,billingVerified:false,credentialsRevoked:false,readiness:trustedServiceReadiness(row.company_id,row.service)};}
export async function listTrustedServiceProvisions(db:PoolClient,companyId:string){return {provisions:(await db.query('SELECT * FROM trusted_service_provisions WHERE company_id=$1 ORDER BY created_at DESC LIMIT 50',[companyId])).rows.map(project),readiness:{archive:trustedServiceReadiness(companyId,'archive'),gateway:trustedServiceReadiness(companyId,'gateway')}};}
export async function getTrustedServiceProvision(db:PoolClient,companyId:string,provisionId:string){return project(await rowFor(db,companyId,provisionId));}
export async function planTrustedService(db:PoolClient,member:Membership,input:unknown){
 const data=parse(trustedServicePlanInput,input);await control(db,member.companyId);await lockMembership(db,member,true);const requestHash=trustedServiceHash(data);
 const old=(await db.query('SELECT * FROM trusted_service_provisions WHERE company_id=$1 AND created_by=$2 AND client_id=$3',[member.companyId,member.userId,data.clientId])).rows[0];if(old){if(old.request_hash!==requestHash)fail(409,'This request ID was used for different details.','IDEMPOTENCY_CONFLICT');return {provision:project(old),replayed:true};}
 const preset=trustedServicePreset(member.companyId,data.service),now=await dbNow(db),remaining=Date.parse(preset.expiresAt)-now;if(remaining<60000||remaining>86400000)fail(409,'Install a reviewed service deadline between one minute and 24 hours away.','SERVICE_PRESET_EXPIRED');
 const prior=await reserved(db,member.companyId,data.service),amount=Math.ceil(preset.maxHourlyMicrousd*(remaining+300000)/3600000);
 const plan={version:1,companyId:member.companyId,service:data.service,expiresAt:preset.expiresAt,reviewExpiresAt:new Date(Math.min(now+600000,Date.parse(preset.expiresAt))).toISOString(),preset:{id:preset.id,hash:trustedServiceHash(preset),releaseCommit:preset.releaseCommit,bootstrapHash:preset.bootstrapHash,configurationHash:preset.configurationHash,image:TRUSTED_SERVICE_IMAGE,cpuTypeId:'cpu3c',vcpuCount:2,memoryGb:4,dataCenterId:preset.dataCenterId,databaseRole:TRUSTED_SERVICE_DATABASE_ROLES[data.service]},reservation:{cpuMicrousd:amount,previouslyReservedMicrousd:prior,lifetimeAllowanceMicrousd:preset.lifetimeAllowanceMicrousd,storageIncluded:false,decoderIncluded:false,inferenceIncluded:false,billingCapGuaranteed:false},effects:{startCpu:true,activateAgents:false,startGpu:false,serviceVerified:false}};
 const provisionId=randomUUID(),row=(await db.query('INSERT INTO trusted_service_provisions(id,company_id,service,created_by,client_id,request_hash,preset,plan,plan_hash,pod_name,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[provisionId,member.companyId,data.service,member.userId,data.clientId,requestHash,JSON.stringify(preset),JSON.stringify(plan),trustedServiceHash(plan),'coatria-'+data.service+'-'+provisionId,preset.expiresAt])).rows[0];return {provision:project(row),replayed:false};
}
async function replay(db:PoolClient,member:Membership,clientId:string,hash:string){const old=(await db.query('SELECT * FROM trusted_service_requests WHERE company_id=$1 AND user_id=$2 AND client_id=$3',[member.companyId,member.userId,clientId])).rows[0];if(old&&old.request_hash!==hash)fail(409,'This request ID was used for different details.','IDEMPOTENCY_CONFLICT');return old;}
async function receipt(db:PoolClient,member:Membership,row:Row,operation:string,clientId:string,hash:string){await db.query('INSERT INTO trusted_service_requests(company_id,user_id,client_id,provision_id,operation,request_hash) VALUES($1,$2,$3,$4,$5,$6)',[member.companyId,member.userId,clientId,row.id,operation,hash]);}
export async function startTrustedService(db:PoolClient,member:Membership,provisionId:string,input:unknown){
 const data=parse(trustedServiceStartInput,input),hash=trustedServiceHash({provisionId,...data});await control(db,member.companyId);await lockMembership(db,member,true);const old=await replay(db,member,data.clientId,hash);if(old)return {provision:project(await rowFor(db,member.companyId,old.provision_id)),replayed:true};
 const row=await rowFor(db,member.companyId,provisionId),now=await dbNow(db);if(row.phase!=='planned'||row.revision!==data.revision||row.plan_hash!==data.planHash||trustedServiceHash(row.plan)!==row.plan_hash)fail(409,'The exact current service plan is required.','SERVICE_PLAN_CONFLICT');
 if(+new Date(row.plan.reviewExpiresAt)<=now||+new Date(row.expires_at)<=now+60000)fail(409,'The reviewed service deadline has ended.','SERVICE_PRESET_EXPIRED');
 const preset=trustedServicePreset(member.companyId,row.service);if(trustedServiceHash(preset)!==row.plan.preset.hash||trustedServiceHash(row.preset)!==row.plan.preset.hash)fail(409,'The reviewed service preset changed.','SERVICE_PRESET_CHANGED');
 if(!trustedServiceReadiness(member.companyId,row.service).configured)fail(503,'Trusted service credentials or configuration are not ready.','SERVICE_CONFIGURATION_REQUIRED');
 if((await db.query('SELECT id FROM trusted_service_provisions WHERE company_id=$1 AND service=$2 AND phase=ANY($3::text[])',[member.companyId,row.service,active])).rowCount)fail(409,'Reconcile or stop the existing service before starting another.','SERVICE_ALREADY_PENDING');
 if(await reserved(db,member.companyId,row.service)+row.plan.reservation.cpuMicrousd>preset.lifetimeAllowanceMicrousd)fail(409,'The reviewed service CPU allowance is exhausted.','SERVICE_ALLOWANCE_EXHAUSTED');
 await db.query('INSERT INTO trusted_service_reservations(company_id,provision_id,service,amount_microusd,approved_by) VALUES($1,$2,$3,$4,$5)',[member.companyId,row.id,row.service,row.plan.reservation.cpuMicrousd,member.userId]);
 const saved=(await db.query("UPDATE trusted_service_provisions SET phase='approved',revision=revision+1,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2 RETURNING *",[member.companyId,row.id])).rows[0];await receipt(db,member,saved,'start',data.clientId,hash);return {provision:project(saved),replayed:false};
}
export async function stopTrustedService(db:PoolClient,member:Membership,provisionId:string,input:unknown){
 const data=parse(trustedServiceStopInput,input),hash=trustedServiceHash({provisionId,...data});await control(db,member.companyId);await lockMembership(db,member,true);const old=await replay(db,member,data.clientId,hash);if(old)return {provision:project(await rowFor(db,member.companyId,old.provision_id)),replayed:true};
 const row=await rowFor(db,member.companyId,provisionId);if(row.revision!==data.revision)fail(409,'The service changed. Refresh before stopping.','SERVICE_PLAN_CONFLICT');
 const saved=(await db.query("UPDATE trusted_service_provisions SET stop_requested_at=COALESCE(stop_requested_at,clock_timestamp()),phase=CASE WHEN submitted_at IS NULL OR phase='stopped' THEN 'stopped' ELSE 'stopping' END,revision=revision+1,updated_at=clock_timestamp() WHERE company_id=$1 AND id=$2 RETURNING *",[member.companyId,row.id])).rows[0];await receipt(db,member,saved,'stop',data.clientId,hash);return {provision:project(saved),replayed:false};
}
async function verifyDatabase(service:TrustedServiceKind,url:string,companyId:string){
 const pool=new Pool({connectionString:url,max:1,connectionTimeoutMillis:5000,statement_timeout:15000});pool.on('error',()=>{});
 try{if(service==='archive')await assertHiggsfieldArchiveDatabase(pool);else{const client=await pool.connect();try{await assertProjectStorageGatewayDatabase(client);}finally{client.release();}}if(!(await pool.query('SELECT id FROM companies WHERE id=$1',[companyId])).rowCount)throw Error();}
 catch{fail(503,'The dedicated service LOGIN and grants were not verified.','SERVICE_DATABASE_UNCONFIRMED');}finally{await pool.end();}
}
async function provider(path:string,method:string,payload:unknown,transport:typeof fetch){
 const key=process.env.MANAGED_RUNPOD_API_KEY;if(!key)fail(503,'The server lifecycle credential is unavailable.','SERVICE_PROVIDER_UNAVAILABLE');
 const response=await transport('https://api.runpod.io/v2'+path,{method,headers:{Authorization:'Bearer '+key,...payload===undefined?{}:{'Content-Type':'application/json'}},...payload===undefined?{}:{body:JSON.stringify(payload)},redirect:'error',cache:'no-store',signal:AbortSignal.timeout(10000)});
 if(!response.ok){void response.body?.cancel().catch(()=>{});fail(503,'The provider operation was not confirmed.','SERVICE_PROVIDER_UNCONFIRMED');}
 const reader=response.body?.getReader();if(!reader)fail(503,'The provider response was empty.','SERVICE_PROVIDER_UNCONFIRMED');const chunks:Uint8Array[]=[];let size=0;
 try{for(;;){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>2000000)fail(503,'The provider response exceeded the bound.','SERVICE_PROVIDER_UNCONFIRMED');chunks.push(part.value);}return JSON.parse(Buffer.concat(chunks).toString('utf8')) as Row;}catch{void reader.cancel().catch(()=>{});fail(503,'The provider response was invalid.','SERVICE_PROVIDER_UNCONFIRMED');}
}
const ports=(service:string)=>service==='gateway'?['4190/http']:[];
function verifyPod(row:Row,pod:Row){
 const p=row.preset as TrustedServicePreset,expected=row.expected_environment_hashes,keys=Object.keys(expected??{}),env=pod?.env;
 if(!pod||typeof pod.id!=='string'||!/^[A-Za-z0-9_-]{1,100}$/.test(pod.id)||row.pod_id&&pod.id!==row.pod_id||pod.name!==row.pod_name||pod.image!==TRUSTED_SERVICE_IMAGE||hashToken(pod.args??'')!==p.bootstrapHash||pod.disk!==10||pod.cpu?.id!=='cpu3c'||pod.cpu?.vcpuCount!==2||pod.cpu?.memory!==4||pod.gpu||pod.cloud!=='SECURE'||pod.dataCenterId!==p.dataCenterId||JSON.stringify(pod.ports)!==JSON.stringify(ports(p.service))||pod.mounts?.persistent||pod.mounts?.network!=null&&(!Array.isArray(pod.mounts.network)||pod.mounts.network.length!==0)||!keys.length||!env||Object.keys(env).length!==keys.length||keys.some(key=>typeof env[key]!=='string'||hashToken(env[key])!==expected[key])||!['PROVISIONING','STARTING','RUNNING','EXITED','TERMINATED','ERROR'].includes(pod.status))fail(409,'Provider identity differs from the reviewed trusted service.','SERVICE_IDENTITY_MISMATCH');return pod;
}
async function discover(row:Row,transport:typeof fetch){let cursor:string|undefined;const matches:Row[]=[],seen=new Set<string>();for(let page=0;page<10;page++){const result=await provider('/pods?limit=100'+(cursor?'&cursor='+encodeURIComponent(cursor):''),'GET',undefined,transport);if(!Array.isArray(result.pods)||typeof result.pagination?.hasNextPage!=='boolean')fail(503,'Provider discovery was incomplete.','SERVICE_DISCOVERY_INCOMPLETE');matches.push(...result.pods.filter((pod:Row)=>pod.name===row.pod_name));if(!result.pagination.hasNextPage){if(matches.length>1)fail(409,'Multiple Pods match the reserved service identity.','SERVICE_DUPLICATE_IDENTITY');return matches[0]?verifyPod(row,matches[0]):null;}cursor=result.pagination.nextCursor;if(typeof cursor!=='string'||!cursor||cursor.length>1000||seen.has(cursor))fail(503,'Provider discovery was incomplete.','SERVICE_DISCOVERY_INCOMPLETE');seen.add(cursor);}fail(503,'Provider discovery exceeded its bound.','SERVICE_DISCOVERY_INCOMPLETE');}
export async function reconcileTrustedService(provisionId:string,dependencies:Dependencies={}){
 id(provisionId);const tx=dependencies.transaction??transaction,base=dependencies.fetch??fetch,deadline=AbortSignal.timeout(25000),lease=randomUUID();const transport:typeof fetch=(url,init)=>base(url,{...init,signal:AbortSignal.any([deadline,...init?.signal?[init.signal]:[]])});
 const row=await tx(async db=>{const found=(await db.query('SELECT company_id FROM trusted_service_provisions WHERE id=$1',[provisionId])).rows[0];if(!found)fail(404,'Trusted service request not found.');await control(db,found.company_id);const r=await rowFor(db,found.company_id,provisionId),now=await dbNow(db);if(['planned','stopped','failed'].includes(r.phase)||r.lease_expires_at&&+new Date(r.lease_expires_at)>now)return null;const owner=(await db.query("SELECT user_id FROM memberships WHERE company_id=$1 AND user_id=$2 AND role IN ('owner','admin') FOR SHARE",[r.company_id,r.created_by])).rowCount;if(!owner||+new Date(r.expires_at)<=now)r.stop_requested_at=r.stop_requested_at??new Date(now);await db.query("UPDATE trusted_service_provisions SET lease_id=$3,lease_expires_at=clock_timestamp()+interval '45 seconds',stop_requested_at=$4 WHERE company_id=$1 AND id=$2",[r.company_id,r.id,lease,r.stop_requested_at]);return r;});
 if(!row)return {skipped:true};
 const save=(patch:{phase:string;podId?:string;status?:string;error?:string})=>tx(async db=>{await control(db,row.company_id);const r=await rowFor(db,row.company_id,row.id);if(r.lease_id!==lease)return {skipped:true};const phase=r.stop_requested_at&&patch.phase!=='stopped'?(r.submitted_at?'stopping':'stopped'):patch.phase;const saved=(await db.query('UPDATE trusted_service_provisions SET phase=$3,pod_id=COALESCE($4,pod_id),provider_status=COALESCE($5,provider_status),error_code=$6,revision=revision+1,last_reconciled_at=clock_timestamp(),updated_at=clock_timestamp(),lease_id=NULL,lease_expires_at=NULL WHERE company_id=$1 AND id=$2 RETURNING *',[r.company_id,r.id,phase,patch.podId??null,patch.status??null,patch.error??null])).rows[0];return {provision:project(saved),skipped:false};});
 // Provider I/O does not hold database locks. Re-read durable stop intent and
 // authority after that I/O so a stop accepted during create/read is respected.
 const mustStop=()=>tx(async db=>{await control(db,row.company_id);const r=await rowFor(db,row.company_id,row.id);if(r.lease_id!==lease)fail(409,'The service reconciliation lease changed.','SERVICE_LEASE_CHANGED');const owner=(await db.query("SELECT user_id FROM memberships WHERE company_id=$1 AND user_id=$2 AND role IN ('owner','admin') FOR SHARE",[r.company_id,r.created_by])).rowCount;const stop=Boolean(r.stop_requested_at)||!owner||+new Date(r.expires_at)<=await dbNow(db);if(stop)await db.query('UPDATE trusted_service_provisions SET stop_requested_at=COALESCE(stop_requested_at,clock_timestamp()) WHERE company_id=$1 AND id=$2',[r.company_id,r.id]);return stop;});
 const finishPod=async(pod:Row)=>{if(stopped.has(pod.status))return save({phase:'stopped',podId:pod.id,status:pod.status});if(await mustStop()){if(!Array.isArray(pod.actions)||!pod.actions.includes('stop'))return save({phase:'stopping',podId:pod.id,status:pod.status,error:'SERVICE_STOP_PENDING'});await provider('/pods/'+pod.id+'/action','POST',{action:'stop'},transport);return save({phase:'stopping',podId:pod.id,status:pod.status});}return save({phase:pod.status==='RUNNING'?'running':pod.status==='ERROR'?'needs_attention':'provisioning',podId:pod.id,status:pod.status,...pod.status==='ERROR'?{error:'SERVICE_PROVIDER_ERROR'}:{}});};
 let submitted=Boolean(row.submitted_at);
 try{
  if(!submitted){
   if(row.stop_requested_at)return await save({phase:'stopped'});const preset=trustedServicePreset(row.company_id,row.service);if(trustedServiceHash(preset)!==row.plan.preset.hash||trustedServiceHash(row.preset)!==row.plan.preset.hash)fail(409,'The reviewed service preset changed.','SERVICE_PRESET_CHANGED');
   const env=trustedServiceEnvironment(preset);await (dependencies.verifyDatabase??verifyDatabase)(row.service,env.DATABASE_URL,row.company_id);deadline.throwIfAborted();
   const cpu=await provider('/catalog/cpus/cpu3c','GET',undefined,transport);
   if(cpu.id!=='cpu3c'||cpu.ramGbPerVcpu!==2||!Number.isInteger(cpu.vcpu?.min)||!Number.isInteger(cpu.vcpu?.max)||cpu.vcpu.min<1||cpu.vcpu.min>2||cpu.vcpu.max<2||!Number.isFinite(cpu.price?.securePerVcpu)||cpu.price.securePerVcpu<=0||Math.ceil(cpu.price.securePerVcpu*2*1000000)>preset.maxHourlyMicrousd)fail(409,'The CPU price or resource changed.','SERVICE_CATALOG_CHANGED');
   const request={name:row.pod_name,cloud:'SECURE',image:TRUSTED_SERVICE_IMAGE,args:preset.bootstrapArgs,disk:10,cpu:{id:'cpu3c',vcpuCount:2},dataCenterIds:[preset.dataCenterId],ports:ports(row.service),startSsh:false,startJupyter:false,env};row.expected_environment_hashes=Object.fromEntries(Object.entries(env).map(([key,value])=>[key,hashToken(value)]));
   const allowed=await tx(async db=>{await control(db,row.company_id);const current=await rowFor(db,row.company_id,row.id),now=await dbNow(db);if(current.lease_id!==lease||current.submitted_at||current.stop_requested_at||+new Date(current.expires_at)<=now)return false;if(!(await db.query("SELECT user_id FROM memberships WHERE company_id=$1 AND user_id=$2 AND role IN ('owner','admin') FOR SHARE",[row.company_id,row.created_by])).rowCount)return false;await db.query("UPDATE trusted_service_provisions SET phase='submitting',submitted_at=clock_timestamp(),expected_environment_hashes=$3,revision=revision+1 WHERE company_id=$1 AND id=$2",[row.company_id,row.id,JSON.stringify(row.expected_environment_hashes)]);return true;});
   if(!allowed)return await save({phase:'stopped'});submitted=true;const pod=verifyPod(row,await provider('/pods','POST',request,transport));return await finishPod(pod);
  }
  const pod=row.pod_id?verifyPod(row,await provider('/pods/'+row.pod_id,'GET',undefined,transport)):await discover(row,transport);if(!pod)return await save({phase:'uncertain',error:'SERVICE_CREATE_UNCERTAIN'});
  return await finishPod(pod);
 }catch(error){const code=typeof(error as {code?:unknown})?.code==='string'&&(error as {code:string}).code.startsWith('SERVICE_')?(error as {code:string}).code:'SERVICE_PROVIDER_UNCONFIRMED';return await save({phase:submitted?['SERVICE_IDENTITY_MISMATCH','SERVICE_DUPLICATE_IDENTITY'].includes(code)?'needs_attention':row.stop_requested_at?'stopping':'uncertain':'failed',error:code});}
}
export async function reconcileTrustedServices(limit=2,dependencies:Dependencies={}){const tx=dependencies.transaction??transaction,ids=await tx(async db=>(await db.query('SELECT id FROM trusted_service_provisions WHERE phase=ANY($1::text[]) AND (lease_expires_at IS NULL OR lease_expires_at<=clock_timestamp()) ORDER BY (stop_requested_at IS NOT NULL OR expires_at<=clock_timestamp()) DESC,last_reconciled_at NULLS FIRST,id LIMIT $2',[active,Math.max(1,Math.min(2,limit))])).rows.map(row=>row.id));const results=[];for(const id of ids)results.push(await reconcileTrustedService(id,dependencies));return {results};}
