import {test,expect,type Page,type Route} from '@playwright/test';
import {conversationFixture} from './conversation-fixture';
import type {AgentRun} from '../../src/lib/agent-run-protocol';
import type {User,Agent,Workspace} from '../../src/lib/client';
const user:User={id:'10000000-0000-4000-8000-000000000881',name:'Request Reviewer',email:'agent-runs@example.invalid',roleTitle:'Designer',avatarColor:'#617651',avatarId:null};
const companies=[{id:'20000000-0000-4000-8000-000000000881',name:'Request Studio',slug:'request-studio',template:'blank',role:'owner'},{id:'20000000-0000-4000-8000-000000000882',name:'Second Request Studio',slug:'second-request-studio',template:'blank',role:'owner'}];
const agent:Agent={id:'40000000-0000-4000-8000-000000000881',name:'Atlas',harness:'custom',description:'Reviews shared plans.',status:'active',createdBy:user.id,lastSeenAt:null,conversationAccess:'none',invocationAccess:'members',capabilities:['workspace.read','layout.propose'],expiresAt:null};
const rootMessage='50000000-0000-4000-8000-000000000881';
const json=(route:Route,body:unknown,status=200)=>route.fulfill({status,json:body});
async function fixture(page:Page,role='owner'){
 const workspaces=new Map(companies.map(value=>{const company={...value,role};const w:Workspace={company,members:[{...user,userId:user.id,role:'owner'}],rooms:[],agents:[{...agent}],presence:[],tasks:[],activity:[],drives:[],openings:[],applications:[],layout:[],messages:[{id:rootMessage,roomId:null,body:'Review the next studio plan.',createdAt:new Date().toISOString(),userId:user.id,authorName:user.name}]};return[company.id,w];}));
 const runs=new Map<string,AgentRun>(),writes:{path:string;body:any}[]=[],receipts=new Map<string,AgentRun>(),proposals:any[]=[];let uncertain=false,hold=false,held:{route:Route;run:AgentRun}|null=null;const unexpected:string[]=[],errors:string[]=[];
 const messaging=conversationFixture(id=>workspaces.get(id),()=>user);page.on('pageerror',error=>errors.push(error.message));
 await page.addInitScript(()=>{(window as any).CoatriaOfficeRuntime={createCharacterLibrary:()=>({dispose(){}}),createOfficeAssetLibrary:()=>({dispose(){}}),mount(host:HTMLElement){const canvas=document.createElement('canvas');canvas.style.cssText='display:block;width:100%;height:300px';host.replaceChildren(canvas);return{dispose(){canvas.remove();},updateSnapshot(){},get diagnostics(){return{position:{x:0,z:3}};}};}};});
 await page.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url()),path=url.pathname,method=request.method(),body=method==='GET'?null:request.postDataJSON();
  if(path==='/api/session')return json(route,{user,companies:[...workspaces.values()].map(w=>w.company),configured:true});
  const workspaceMatch=path.match(/^\/api\/companies\/([^/]+)\/(workspace|presence)$/);if(workspaceMatch){const workspace=workspaces.get(workspaceMatch[1])!;if(workspaceMatch[2]==='presence'&&method==='POST')workspace.presence=[{userId:user.id,name:user.name,avatarColor:user.avatarColor,avatarId:user.avatarId,roomId:null,x:0,z:3,status:'available',...body,updatedAt:new Date().toISOString()}];return json(route,workspaceMatch[2]==='workspace'?workspace:{presence:workspace.presence});}
  if(path.includes('/agent-proposals')){if(method==='GET')return json(route,{items:proposals,hasMore:false,nextAfter:null});writes.push({path,body});const id=path.split('/').at(-2),proposal=proposals.find(item=>item.id===id);if(proposal.kind==='layout'&&path.endsWith('/approve'))return json(route,{error:'The office layout changed. Create a proposal using the current revision.'},409);proposal.status=path.endsWith('/approve')?'applied':'rejected';return json(route,{item:proposal});}
  const channelMatch=path.match(/^\/api\/companies\/([^/]+)\/conversations\/([^/]+)\/runs$/);
  if(channelMatch){const [,companyId,channel]=channelMatch;if(method==='GET')return json(route,{runs:[...runs.values()].filter(run=>run.companyId===companyId&&run.channel===channel).reverse()});writes.push({path,body});let run=receipts.get(body.clientId);if(!run){const now=new Date().toISOString();run={id:crypto.randomUUID(),companyId,channel,conversationId:crypto.randomUUID(),parentId:body.parentId||null,prompt:body.prompt,requestedBy:user.id,requesterName:user.name,agentId:body.agentId,agentName:'Atlas',status:'queued',attempts:0,maxAttempts:3,availableAt:now,leaseExpiresAt:null,deadlineAt:new Date(Date.now()+1800000).toISOString(),createdAt:now,updatedAt:now,startedAt:null,finishedAt:null,result:'',error:'',artifactUrl:null,resultMessageId:null,capabilities:['workspace.read']};runs.set(run.id,run);receipts.set(body.clientId,run);}if(hold){hold=false;held={route,run};return;}if(uncertain){uncertain=false;return json(route,{error:'Request response was interrupted.'},503);}return json(route,{run,replayed:receipts.has(body.clientId)},201);}
  const detail=path.match(/^\/api\/companies\/([^/]+)\/agent-runs(?:\/([^/]+)(?:\/(cancel))?)?$/);if(detail){if(!detail[2])return json(route,{runs:[...runs.values()].filter(run=>run.companyId===detail[1]&&(!url.searchParams.has('agentId')||run.agentId===url.searchParams.get('agentId'))).reverse()});const run=runs.get(detail[2]);if(!run||run.companyId!==detail[1])return json(route,{error:'Missing request'},404);if(method==='POST'){writes.push({path,body});Object.assign(run,{status:'cancelled',updatedAt:new Date().toISOString()});}return json(route,{run,actions:[{requestId:'receipt-1',tool:'tasks.create',createdAt:run.updatedAt}]});}
  const access=path.match(/^\/api\/companies\/([^/]+)\/agents\/([^/]+)$/);if(access&&method==='PATCH'){writes.push({path,body});const value=workspaces.get(access[1])!.agents.find(value=>value.id===access[2])!;Object.assign(value,body);return json(route,{agent:value});}
  if(await messaging.handle(route))return;unexpected.push(path);return json(route,{error:'Unexpected fixture '+path},501);
 });
 return{workspaces,runs,writes,proposals,unexpected,errors,uncertain(){uncertain=true;},hold(){hold=true;},get held(){return held;},async release(){if(held)await json(held.route,{run:held.run,replayed:false},201).catch(()=>{});}};
}
const button=(page:Page,name:string)=>page.getByRole('button',{name,exact:true});
const ask=(page:Page)=>page.getByRole('dialog',{name:'Ask an agent',exact:true});
async function openAsk(page:Page){await expect(button(page,'Ask agent')).toBeEnabled();await button(page,'Ask agent').click();await expect(ask(page)).toBeVisible();}
async function queue(page:Page,prompt='Review the studio plan'){await openAsk(page);await ask(page).getByRole('textbox',{name:'What should the agent do?',exact:true}).fill(prompt);await ask(page).getByRole('button',{name:'Queue request',exact:true}).click();await expect(ask(page)).toHaveCount(0);}
test.beforeEach(({baseURL})=>test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Local synthetic fixtures only.'));

test('explicit requests show server queued, running, overdue and delivered states without broad chat permission',async({page})=>{
 const state=await fixture(page);await page.goto('/#chat');await queue(page);const shelf=page.getByRole('complementary',{name:'Agent requests',exact:true});await expect(shelf).toContainText('Queued');expect(state.writes[0].body).toMatchObject({agentId:agent.id,prompt:'Review the studio plan'});const run=[...state.runs.values()][0];await shelf.getByRole('button').filter({hasText:'Atlas'}).click();const detail=page.getByRole('dialog',{name:'Request to Atlas',exact:true});await expect(detail).toContainText('Waiting for a connected worker.');Object.assign(run,{status:'running',attempts:1,leaseExpiresAt:new Date(Date.now()+60000).toISOString(),updatedAt:new Date(Date.now()+10).toISOString()});await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(detail).toContainText('A connected worker has claimed');Object.assign(run,{leaseExpiresAt:new Date(Date.now()-1000).toISOString(),updatedAt:new Date(Date.now()+20).toISOString()});await expect(detail).toContainText('Worker connection overdue');Object.assign(run,{status:'succeeded',result:'The three priorities are wayfinding, meeting access, and keyboard controls.',artifactUrl:'javascript:alert(1)',updatedAt:new Date(Date.now()+30).toISOString()});await expect(detail).toContainText('Response delivered');await expect(detail).toContainText('three priorities');await expect(detail.getByRole('link',{name:'Open result artifact',exact:true})).toHaveCount(0);await expect(detail).toContainText('not an approval');await detail.getByText('Committed actions · 1',{exact:true}).click();await expect(detail).toContainText('tasks.create');await expect(detail).toContainText('Read-only queries are not included.');expect(state.errors).toEqual([]);expect(state.unexpected).toEqual([]);
});

test('uncertain request retries keep their UUID through dialog close and dock/full changes',async({page})=>{
 const state=await fixture(page);await page.goto('/#chat');state.uncertain();await openAsk(page);await ask(page).getByRole('textbox',{name:'What should the agent do?',exact:true}).fill('One durable request');await ask(page).getByRole('button',{name:'Queue request',exact:true}).click();await expect(ask(page).getByRole('alert')).toContainText('unconfirmed');await ask(page).getByRole('button',{name:'Close',exact:true}).click();await button(page,'Dock conversation').click();await openAsk(page);await expect(ask(page).getByRole('textbox',{name:'What should the agent do?',exact:true})).toHaveValue('One durable request');await ask(page).getByRole('button',{name:'Retry original request',exact:true}).click();await expect(ask(page)).toHaveCount(0);expect(state.writes).toHaveLength(2);expect(state.writes[1].body.clientId).toBe(state.writes[0].body.clientId);expect(state.runs.size).toBe(1);
});

test('message requests anchor to the thread, cancellation is explicit, and reload restores server history',async({page})=>{
 const state=await fixture(page);await page.goto('/#chat');await page.locator('[data-message-id="'+rootMessage+'"]').getByRole('button',{name:'Ask agent about this message',exact:true}).click();await expect(ask(page)).toContainText('Review the next studio plan.');await ask(page).getByRole('textbox',{name:'What should the agent do?',exact:true}).fill('Review this message');await ask(page).getByRole('button',{name:'Queue request',exact:true}).click();await expect(ask(page)).toHaveCount(0);expect(state.writes[0].body.parentId).toBe(rootMessage);await page.reload();const shelf=page.getByRole('complementary',{name:'Agent requests',exact:true});await expect(shelf).toContainText('Review this message');await shelf.getByRole('button').filter({hasText:'Atlas'}).click();const detail=page.getByRole('dialog',{name:'Request to Atlas',exact:true});await detail.getByRole('button',{name:'Cancel request',exact:true}).click();expect(state.writes).toHaveLength(1);await expect(detail).toContainText('Work already performed');await detail.getByRole('button',{name:'Cancel request',exact:true}).click();await expect(detail).toContainText('Cancelled');expect(state.writes.at(-1)?.path).toMatch(/\/cancel$/);
});

test('company switching aborts pending UI work and discards request drafts',async({page})=>{
 const state=await fixture(page);await page.goto('/#chat');state.hold();await openAsk(page);await ask(page).getByRole('textbox',{name:'What should the agent do?',exact:true}).fill('First-company prompt');await ask(page).getByRole('button',{name:'Queue request',exact:true}).click();await expect.poll(()=>!!state.held).toBe(true);await ask(page).getByRole('button',{name:'Close',exact:true}).click();await button(page,'Switch to Second Request Studio').click();await button(page,'Open conversation panel').click();await openAsk(page);await expect(ask(page).getByRole('textbox',{name:'What should the agent do?',exact:true})).toHaveValue('');await state.release();await expect(ask(page)).not.toContainText('First-company prompt');await expect(ask(page).getByRole('button',{name:'Queue request',exact:true})).toBeDisabled();expect(state.writes).toHaveLength(1);
});

test('members cannot invoke admin-only agents and granular administrator grants save separately from conversation access',async({page})=>{
 const state=await fixture(page,'member');state.workspaces.get(companies[0].id)!.agents[0].invocationAccess='admins';await page.goto('/#chat');await openAsk(page);await expect(ask(page)).toContainText('No agents can accept');await expect(ask(page).getByRole('option',{name:'Atlas · Administrators only',exact:true})).toBeDisabled();await expect(ask(page).getByRole('button',{name:'Queue request',exact:true})).toBeDisabled();await ask(page).getByRole('button',{name:'Close',exact:true}).click();state.workspaces.get(companies[0].id)!.company.role='owner';await page.reload();await page.goto('/#agents');await page.getByRole('button').filter({has:page.getByRole('heading',{name:'Atlas',exact:true})}).click();const modal=page.getByRole('dialog',{name:'Atlas',exact:true});await modal.getByRole('combobox',{name:'Who can ask this agent',exact:true}).selectOption('members');await modal.getByRole('checkbox',{name:'Create and prepare tasks for independent human review',exact:true}).check();await modal.getByRole('checkbox',{name:'Propose floor changes for administrator review',exact:true}).uncheck();await modal.getByRole('button',{name:'Save request permissions',exact:true}).click();await expect.poll(()=>state.writes.length).toBe(1);expect(state.writes[0].body).toEqual({invocationAccess:'members',capabilities:['workspace.read','tasks.write']});expect(state.workspaces.get(companies[0].id)!.agents[0].conversationAccess).toBe('none');
});

test('390px request dialog and active-run shelf preserve a usable composer',async({page})=>{
 await fixture(page);await page.setViewportSize({width:390,height:844});await page.goto('/#chat');await openAsk(page);const prompt=ask(page).getByRole('textbox',{name:'What should the agent do?',exact:true});expect(await prompt.evaluate(element=>parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(16);await prompt.fill('A concise mobile request');await ask(page).getByRole('button',{name:'Queue request',exact:true}).click();await expect(ask(page)).toHaveCount(0);const send=await button(page,'Send').boundingBox();expect(send!.y+send!.height).toBeLessThanOrEqual(844);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await expect(page.getByRole('textbox',{name:'Your message',exact:true})).toBeVisible();
});

test('a request timeout unlocks safe retry with the same idempotency UUID',async({page})=>{
 const state=await fixture(page);await page.clock.install();await page.goto('/#chat');state.hold();await openAsk(page);await ask(page).getByRole('textbox',{name:'What should the agent do?',exact:true}).fill('Bounded request');await ask(page).getByRole('button',{name:'Queue request',exact:true}).click();await expect.poll(()=>!!state.held).toBe(true);await page.clock.fastForward(21000);await expect(ask(page).getByRole('alert')).toContainText('timed out');await ask(page).getByRole('button',{name:'Retry original request',exact:true}).click();await expect(ask(page)).toHaveCount(0);expect(state.writes[1].body.clientId).toBe(state.writes[0].body.clientId);expect(state.runs.size).toBe(1);
});

test('administrator proposals require an exact apply action, support rejection and preserve layout conflicts',async({page})=>{
 const state=await fixture(page);await page.goto('/#chat');await queue(page);const run=[...state.runs.values()][0],base={agentName:'Atlas',runId:run.id,status:'pending',expiresAt:new Date(Date.now()+3600000).toISOString(),createdAt:new Date().toISOString(),result:null};state.proposals.push({...base,id:'room-proposal',kind:'room',data:{name:'Review nook',kind:'meeting',capacity:4}},{...base,id:'opening-proposal',kind:'opening',data:{title:'Studio researcher',description:'Prepare documented research.',type:'either',compensation:'volunteer'}},{...base,id:'layout-proposal',kind:'layout',data:{floor:{width:20,depth:16},revision:0,layout:[{id:'desk',label:'Review desk',type:'desk',x:10,y:10,w:10,h:10,rotation:0}]}});await page.getByRole('complementary',{name:'Agent requests',exact:true}).getByRole('button').filter({hasText:'Atlas'}).click();const proposals=page.getByRole('region',{name:'Proposed workspace changes',exact:true});await expect(proposals).toContainText('Review nook');const room=proposals.locator('article').filter({hasText:'Review nook'});await room.getByRole('button',{name:'Review and apply',exact:true}).click();expect(state.writes).toHaveLength(1);await room.getByRole('button',{name:'Confirm and apply',exact:true}).click();await expect(room).toContainText('applied');expect(state.writes.at(-1)?.path).toMatch(/room-proposal\/approve$/);const opening=proposals.locator('article').filter({hasText:'Studio researcher'});await opening.getByRole('button',{name:'Reject proposal',exact:true}).click();await expect(opening).toContainText('rejected');const layout=proposals.locator('article').filter({hasText:'Office floor'});await expect(layout.getByRole('img')).toHaveAttribute('aria-label','Proposed floor with 1 objects');await layout.getByRole('button',{name:'Review and apply',exact:true}).click();await layout.getByRole('button',{name:'Confirm and apply',exact:true}).click();await expect(proposals.getByRole('alert')).toContainText('office layout changed');expect(state.proposals[2].status).toBe('pending');expect(state.workspaces.get(companies[0].id)!.layout).toEqual([]);expect(state.errors).toEqual([]);
});


test('disabled requests stay explicit and do not imply a connected worker',async({page})=>{
 const state=await fixture(page);state.workspaces.get(companies[0].id)!.agents[0].invocationAccess='none';await page.goto('/#chat');await openAsk(page);await expect(ask(page)).toContainText('No agents can accept your requests yet.');await expect(ask(page).getByRole('option',{name:'Atlas · Requests disabled',exact:true})).toBeDisabled();await expect(ask(page).getByRole('button',{name:'Queue request',exact:true})).toBeDisabled();expect(state.writes).toEqual([]);
});
