import {test,expect,type Page,type Route} from '@playwright/test';
import type {Agent,Company,User,Workspace} from '../../src/lib/client';

const user:User={id:'autopilot-owner',name:'Autopilot owner',email:'autopilot@example.invalid',roleTitle:'Producer',avatarColor:'#607850',avatarId:null};
const company:Company={id:'autopilot-company',name:'Studio North',slug:'studio-north',template:'blank',role:'owner'};
const agent:Agent={id:'operations-agent',name:'Operations lead',harness:'codex',description:'Reviewable company progress',status:'active',createdBy:user.id,invocationAccess:'admins',capabilities:['workspace.read','tasks.write'],lastSeenAt:null};
const mission=(overrides:Record<string,unknown>={})=>({id:'mission-one',agentId:agent.id,name:'Company operations',objective:'Prepare documented next steps from company work.',intervalMinutes:60,maxCycles:3,cyclesStarted:0,status:'paused',revision:1,nextRunAt:null,lastRunId:null,lastRunStatus:null,pauseReason:'',createdAt:'2026-09-16T00:00:00Z',...overrides});
type Mission=ReturnType<typeof mission>;
function fixture(){const workspace:Workspace={company,rooms:[],members:[{...user,userId:user.id,role:'owner'}],agents:[agent],tasks:[],messages:[],presence:[],activity:[],drives:[],openings:[],applications:[],layout:[]};return {user,companies:[company],workspace,missions:[] as Mission[],cycles:[] as unknown[],handler:undefined as ((route:Route,path:string)=>Promise<boolean>)|undefined};}
async function mock(page:Page,state:ReturnType<typeof fixture>){await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;if(await state.handler?.(route,path))return;const data=path==='/api/session'?{user:state.user,companies:state.companies,configured:true}:path.endsWith('/autonomy/missions')?{missions:state.missions,hasMore:false}:path.endsWith('/runs')?{cycles:state.cycles,hasMore:false}:path.endsWith('/workspace')?state.workspace:path.endsWith('/presence')?{presence:[{userId:state.user.id,name:state.user.name,avatarColor:state.user.avatarColor,avatarId:null,roomId:null,x:0,z:3,status:'available',updatedAt:new Date().toISOString()}]}:null;await route.fulfill({status:data?200:501,json:data||{error:'Unexpected fixture '+path}});});}
const card=(page:Page,title='Company operations')=>page.getByRole('button').filter({has:page.getByRole('heading',{name:title,exact:true})});
test.beforeEach(({baseURL})=>{test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Fixtures use a local origin.');});

test('new missions start paused and active work requires explicit recurring authorization',async({page})=>{
 const state=fixture();let body:Record<string,unknown>|undefined;state.handler=async(route,path)=>{if(path.endsWith('/autonomy/missions')&&route.request().method()==='POST'){body=route.request().postDataJSON();state.missions=[mission(body)];await route.fulfill({status:201,json:{mission:state.missions[0],replayed:false}});return true;}return false;};await mock(page,state);await page.goto('/#autopilot');await page.getByRole('button',{name:'New mission',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Mission state')).toHaveValue('paused');await dialog.getByLabel('Mission name').fill('Morning operations');await dialog.getByLabel('Business objective').fill('Inspect current company tasks and record the next useful priority.');await dialog.getByLabel('Mission state').selectOption('active');await expect(dialog.getByRole('button',{name:'Create mission',exact:true})).toBeDisabled();await dialog.getByRole('checkbox',{name:/I authorize these recurring requests/}).check();await dialog.getByRole('button',{name:'Create mission',exact:true}).click();await expect(dialog).toHaveCount(0);expect(body).toMatchObject({agentId:agent.id,name:'Morning operations',intervalMinutes:60,maxCycles:3,status:'active'});expect(body?.clientId).toMatch(/^[a-f0-9-]{36}$/);await expect(card(page,'Morning operations')).toBeVisible();
});

test('an uncertain create retries the same logical mission rather than a duplicate',async({page})=>{
 const state=fixture(),payloads:Record<string,unknown>[]=[];state.handler=async(route,path)=>{if(path.endsWith('/autonomy/missions')&&route.request().method()==='POST'){payloads.push(route.request().postDataJSON());if(payloads.length===1)await route.fulfill({status:503,json:{error:'The connection was interrupted. Retry the same mission.'}});else{state.missions=[mission(payloads[1])];await route.fulfill({json:{mission:state.missions[0],replayed:true}});}return true;}return false;};await mock(page,state);await page.goto('/#autopilot');await page.getByRole('button',{name:'Use this mission'}).first().click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Create mission',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('connection was interrupted');await expect(dialog.getByLabel('Mission name')).toHaveValue('Company operations');await dialog.getByRole('button',{name:'Create mission',exact:true}).click();await expect(dialog).toHaveCount(0);expect(payloads).toHaveLength(2);expect(payloads[1]).toEqual(payloads[0]);expect(payloads[0].status).toBe('paused');
});

test('mission conflict keeps the draft and does not claim a saved revision',async({page})=>{
 const state=fixture();state.missions=[mission()];let saved:unknown;state.handler=async(route,path)=>{if(path.endsWith('/mission-one')&&route.request().method()==='PATCH'){saved=route.request().postDataJSON();await route.fulfill({status:409,json:{error:'Another administrator changed this mission. Reload it.'}});return true;}return false;};await mock(page,state);await page.goto('/#autopilot');await card(page).click();await page.getByRole('dialog').getByRole('button',{name:'Edit mission'}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Mission name').fill('Reviewed operations');await dialog.getByRole('button',{name:'Save mission'}).click();await expect(dialog.getByRole('alert')).toContainText('Another administrator changed');await expect(dialog.getByLabel('Mission name')).toHaveValue('Reviewed operations');expect(saved).toMatchObject({revision:1,name:'Reviewed operations'});await expect(page.getByText('Company mission saved.',{exact:true})).toHaveCount(0);
});

test('members can read actual cycle results but cannot schedule or dispatch work',async({page})=>{
 const state=fixture();state.companies=[{...company,role:'member'}];state.workspace.company=state.companies[0];state.missions=[mission({status:'active',cyclesStarted:1,lastRunId:'run-one',lastRunStatus:'succeeded'})];state.cycles=[{ordinal:1,trigger:'scheduled',createdAt:'2026-09-16T12:00:00Z',run:{id:'run-one',agentName:agent.name,status:'succeeded',result:'Prepared a documented task for review.',error:null}}];await mock(page,state);await page.goto('/#autopilot');await expect(page.getByRole('button',{name:'New mission'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Use this mission'}).first()).toBeDisabled();await card(page).click();const dialog=page.getByRole('dialog');await expect(dialog).toContainText('Prepared a documented task for review.');await expect(dialog.getByRole('button',{name:'Edit mission'})).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Run next cycle now'})).toHaveCount(0);await expect(dialog).toContainText('Successful execution means the agent returned a result.');
});

test('a manual cycle shows queued work and pauses through the real mutation boundary',async({page})=>{
 const state=fixture();state.missions=[mission({status:'active'})];const sent:unknown[]=[];state.handler=async(route,path)=>{if(path.endsWith('/run-now')){sent.push(route.request().postDataJSON());state.missions=[mission({status:'active',cyclesStarted:1,lastRunId:'run-one',lastRunStatus:'queued',revision:2})];state.cycles=[{ordinal:1,trigger:'manual',createdAt:'2026-09-16T12:00:00Z',run:{id:'run-one',agentName:agent.name,status:'queued',result:null,error:null}}];await route.fulfill({status:201,json:{run:{id:'run-one',status:'queued'}}});return true;}if(path.endsWith('/mission-one')&&route.request().method()==='PATCH'){expect(route.request().postDataJSON()).toEqual({revision:2,status:'paused'});state.missions=[mission({status:'paused',cyclesStarted:1,lastRunId:'run-one',lastRunStatus:'cancelled',revision:3})];await route.fulfill({json:{mission:state.missions[0]}});return true;}return false;};await mock(page,state);await page.goto('/#autopilot');await card(page).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Run next cycle now'}).click();await expect(dialog).toContainText('Waiting for an available worker.');await expect(dialog.getByRole('button',{name:'Run next cycle now'})).toBeDisabled();expect(sent).toHaveLength(1);await dialog.getByRole('button',{name:'Pause mission'}).click();await expect(dialog.getByRole('button',{name:'Pause mission'})).toHaveCount(0);await expect(dialog).toContainText('Scheduling paused or completed');
});

test('sponsor-offboarded agents cannot be assigned to a new mission',async({page})=>{
 const state=fixture();state.workspace.agents=[{...agent,createdBy:'former-admin',name:'Former sponsor agent'}];state.workspace.members.push({...user,id:'former-admin',userId:'former-admin',role:'member'});await mock(page,state);await page.goto('/#autopilot');await page.getByRole('button',{name:'New mission'}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('option',{name:/Former sponsor agent/})).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Create mission',exact:true})).toBeDisabled();await expect(dialog).toContainText('Install an agent and enable administrator requests');
});

test('switching company drops an old in-flight mission response',async({page})=>{
 const state=fixture();let release=()=>{},requested=false;const gate=new Promise<void>(resolve=>{release=resolve;});state.handler=async(route,path)=>{if(path.endsWith('/autonomy/missions')&&route.request().method()==='POST'){requested=true;await gate;await route.fulfill({status:201,json:{mission:mission({name:'Old company confidential mission'})}});return true;}return false;};await mock(page,state);await page.goto('/#autopilot');await page.getByRole('button',{name:'Use this mission'}).first().click();await page.getByRole('dialog').getByRole('button',{name:'Create mission',exact:true}).click();await expect.poll(()=>requested).toBe(true);const second={...company,id:'other-company',name:'Studio South'};state.companies=[second];state.workspace={...state.workspace,company:second};await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(page.getByRole('dialog')).toHaveCount(0);release();await expect(page.locator('body')).not.toContainText('Old company confidential mission');await expect(page.getByText('Company mission saved.',{exact:true})).toHaveCount(0);
});

test('mobile autopilot and history remain within the viewport',async({page})=>{
 const state=fixture();state.missions=[mission({cyclesStarted:1,lastRunStatus:'failed',pauseReason:'The worker failed; review its result.'})];state.cycles=[{ordinal:1,trigger:'scheduled',createdAt:'2026-09-16T12:00:00Z',run:{id:'run-one',status:'failed',result:null,error:'Provider request failed.'}}];await page.setViewportSize({width:390,height:844});await mock(page,state);await page.goto('/#autopilot');await expect(card(page)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'C:/CODEX/Agent002/output/autopilot-mobile.png',fullPage:true});await card(page).click();const dialog=page.getByRole('dialog');await expect(dialog).toContainText('Provider request failed.');expect(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth)).toBe(true);await page.screenshot({path:'C:/CODEX/Agent002/output/autopilot-mobile-history.png'});
});
