import {test,expect,type Page} from '@playwright/test';
import {readFileSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {AVATAR_CATALOG} from '../../src/lib/avatar-catalog';
import {OFFICE_CATALOG} from '../../src/lib/office-catalog';
import {getOfficeSeats} from '../../src/lib/office-seating';
import type {LayoutItem} from '../../src/lib/floor-plan';

const user={id:'10000000-0000-4000-8000-000000008001',name:'Interaction Viewer',avatarId:'city-023'},remote={id:'10000000-0000-4000-8000-000000008002',name:'Interaction Teammate',avatarId:'city-025'},floor={width:20,depth:16};
const layout:LayoutItem[]=['office-chair-001','office-chair-009','office-chair-012','office-chair-006'].flatMap((id,index)=>[0,90,180,270].map((rotation,row)=>{const asset=OFFICE_CATALOG.find(item=>item.id===id)!,width=rotation%180?asset.depth:asset.width,depth=rotation%180?asset.width:asset.depth,x=-4+index*4,z=-4.5+row*3;return{id:`seat-${index}-${rotation}`,type:'asset',assetId:id,label:asset.name,rotation:rotation as 0|90|180|270,x:(x-width/2+10)/20*100,y:(z-depth/2+8)/16*100,w:width/20*100,h:depth/16*100};}));
const seats=getOfficeSeats(layout,floor);
async function fixture(page:Page,initialSeat?:typeof seats[number]){
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/character-interaction-fixture',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/spatial/office-scene.css"><style>body{margin:0;font-family:Arial}#office{height:100vh;width:100vw}</style></head><body><main id="office"></main><script type="module">import "/spatial/bootstrap.js";import * as THREE from "/spatial/vendor/three.module.js";window.interactions={THREE,runtime:window.CoatriaOfficeRuntime};</script></body></html>'}));
  await page.route('**/api/avatars',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({avatars:AVATAR_CATALOG})}));
  for(const kind of ['avatars','office-assets'])await page.route(`**/api/${kind}/*/model`,route=>{const id=new URL(route.request().url()).pathname.split('/')[3];return route.fulfill({contentType:'model/gltf-binary',body:readFileSync(join(process.cwd(),'.runtime-assets',kind==='avatars'?'city-characters':'office-models',id+'.glb'))});});
  await page.goto('/character-interaction-fixture');await expect.poll(()=>page.evaluate(()=>typeof (window as any).interactions?.runtime?.mount)).toBe('function');
  await page.evaluate(({user,remote,floor,layout,seats,catalog,initialSeat})=>{
    const h=(window as any).interactions;h.user=user;h.remote=remote;h.seats=seats;h.moves=[];h.commands=[];h.delayMs=0;h.rejectSeat=false;
    h.own={userId:user.id,name:user.name,x:6,z:4,status:'available',seatId:null,seat:null,updatedAt:new Date().toISOString()};if(initialSeat)h.own={...h.own,x:initialSeat.x,z:initialSeat.z,seatId:initialSeat.id,seat:initialSeat};h.remotePresence={userId:remote.id,name:remote.name,x:6,z:-5,status:'available',updatedAt:new Date().toISOString()};
    h.characters=h.runtime.createCharacterLibrary({userId:user.id,selectAvatar:(_:string,id:string,catalog:any[])=>catalog.find(item=>item.id===id)||catalog[0]});h.furniture=h.runtime.createOfficeAssetLibrary({userId:user.id,catalog});
    h.snapshot=()=>({user,members:[user,remote],agents:[],presence:[h.own,h.remotePresence]});
    h.scene=h.runtime.mount(document.getElementById('office'),{customLayout:true,floor,layout,seats,officeCatalog:catalog,loadCharacter:h.characters.loadCharacter,loadOfficeAsset:h.furniture.loadAsset,state:{user,spatialPosition:{x:6,z:4}},...h.snapshot(),onMove:(position:any)=>{h.moves.push(position);h.own={...h.own,...position,seatId:null,seat:null,updatedAt:new Date().toISOString()};},onInteraction:async(command:any)=>{h.commands.push(command);if(h.delayMs)await new Promise(resolve=>setTimeout(resolve,h.delayMs));if(command.seatId&&h.rejectSeat)throw new Error('That chair is already occupied.');if(command.seatId){const seat=h.seats.find((seat:any)=>seat.id===command.seatId);h.own={...h.own,seatId:seat.id,seat:{x:seat.x,z:seat.z,yaw:seat.yaw,seatHeight:seat.seatHeight},x:seat.x,z:seat.z,updatedAt:new Date().toISOString()};}if(command.interaction)h.own={...h.own,interaction:{...command.interaction,id:'interaction-'+h.commands.length,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+8000).toISOString()}};return h.own;}});
  },{user,remote,floor,layout,seats,catalog:OFFICE_CATALOG,initialSeat});
  await expect.poll(async()=>(await stats(page)).loadedCharacterModels,{timeout:30000}).toBe(2);await expect.poll(async()=>(await stats(page)).officeAssets.filter((asset:any)=>asset.modelLoaded).length).toBe(layout.length);return errors;
}
const stats=(page:Page)=>page.evaluate(()=>(window as any).interactions.scene.diagnostics);
const player=async(page:Page)=>(await stats(page)).occupants.find((person:any)=>person.id===user.id);
async function project(page:Page,x:number,z:number,y=.08){return page.evaluate(({x,z,y})=>{const h=(window as any).interactions,canvas=h.scene.renderer.domElement,rect=canvas.getBoundingClientRect(),q=new h.THREE.Vector3(x,y,z).project(h.scene.camera);return{x:rect.left+(q.x*.5+.5)*rect.width,y:rect.top+(-q.y*.5+.5)*rect.height};},{x,z,y});}
async function dispose(page:Page){await page.evaluate(()=>{const h=(window as any).interactions;h.scene.dispose();h.characters.dispose();h.furniture.dispose();});}
test.beforeEach(({baseURL})=>{test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Licensed local renderer fixtures only.');test.skip(!existsSync(join(process.cwd(),'.runtime-assets/city-characters/city-023.glb')),'Install private licensed runtime assets.');});

test('faster walk, double-left run, double-right ground teleport, and pan remain separate',async({page})=>{
  const errors=await fixture(page);await page.evaluate(()=>(window as any).interactions.scene.walkTo(6,-1));await expect.poll(async()=>(await player(page)).speed).toBeGreaterThan(2);const target=await project(page,-6,4);await page.mouse.dblclick(target.x,target.y,{delay:60});await expect.poll(async()=>(await player(page)).motionMode).toBe('run');await expect.poll(async()=>(await player(page)).speed).toBeGreaterThan(3);expect((await stats(page)).interaction.hasRunClip).toBe(true);await expect.poll(async()=>(await player(page)).runWeight).toBeGreaterThan(.9);
  const teleport=await project(page,-6,-5);await page.mouse.dblclick(teleport.x,teleport.y,{button:'right',delay:60});await expect.poll(async()=>(await player(page)).motionMode).toBe('teleport');expect((await player(page)).x).toBeCloseTo(-6,4);expect((await player(page)).z).toBeCloseTo(-5,4);expect((await stats(page)).pathLength).toBe(0);
  const chair=seats[0];expect(await page.evaluate(({x,z})=>(window as any).interactions.scene.teleportTo(x,z),chair)).toBe(false);expect((await player(page)).x).toBeCloseTo(-6,4);
  const center=await project(page,6,2);await page.mouse.move(center.x,center.y);await page.mouse.down({button:'right'});await page.mouse.move(center.x+65,center.y+25,{steps:7});await page.mouse.up({button:'right'});expect((await player(page)).x).toBeCloseTo(-6,4);expect((await player(page)).z).toBeCloseTo(-5,4);expect(errors).toEqual([]);await dispose(page);
});

test('touch and keyboard equivalents expose movement, actual emotes and reactions',async({page})=>{
  await fixture(page);await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.getElementById('office')!.style.height='510px';});await page.getByRole('button',{name:'Character actions',exact:true}).click();await expect(page.getByRole('button',{name:'Wave',exact:true})).toBeEnabled();expect((await page.locator('.cs-character-menu').boundingBox())!.y).toBeGreaterThanOrEqual((await page.locator('#office').boundingBox())!.y);await page.getByRole('button',{name:'React with heart',exact:true}).click();await expect(page.getByRole('status',{name:'Interaction Viewer reacts with heart',exact:true})).toBeVisible();await page.getByRole('button',{name:'Teleport',exact:true}).click();await page.keyboard.press('ArrowUp');expect((await player(page)).motionMode).toBe('teleport');expect((await player(page)).x).toBeCloseTo(6,4);expect((await player(page)).z).toBeCloseTo(2,4);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.getByRole('button',{name:'Character actions',exact:true}).click();await page.getByRole('button',{name:'Wave',exact:true}).click();await expect.poll(async()=>(await player(page)).emoteWeight).toBeGreaterThan(.8);await page.evaluate(()=>(window as any).interactions.scene.walkTo(6,7));await expect.poll(async()=>(await player(page)).emoteWeight).toBeLessThan(.05);await dispose(page);
});

test('seating uses real Sit hips on every supported chair and rotation; stand returns to the safe aisle',async({page},testInfo)=>{
  test.setTimeout(90000);await fixture(page);
  for(const seat of seats){await page.evaluate(seat=>{const h=(window as any).interactions;h.scene.camera.zoom=1;h.scene.camera.updateProjectionMatrix();h.scene.teleportTo(seat.approach.x,seat.approach.z);h.scene.requestSeat(seat.id);},seat);await expect.poll(async()=>(await player(page)).seatId).toBe(seat.id);await expect.poll(async()=>(await player(page)).currentMotion).toBe('sit');await page.waitForTimeout(350);const current=await player(page);expect(current.x).toBeCloseTo(seat.x,5);expect(current.z).toBeCloseTo(seat.z,5);expect(current.rotation).toBeCloseTo(seat.yaw,5);expect(current.seatedHip[1]).toBeCloseTo(seat.seatHeight+.12,1);expect(Math.abs(current.seatedHip[0]-seat.x)).toBeLessThan(.1);expect(Math.abs(current.seatedHip[2]-seat.z)).toBeLessThan(.1);
    if(seat.id.endsWith('-0')){await page.evaluate(()=>{const s=(window as any).interactions.scene;s.camera.zoom=1.6;s.camera.updateProjectionMatrix();});await page.waitForTimeout(250);await page.screenshot({path:testInfo.outputPath('seated-'+seat.id+'.png')});}
    await page.evaluate(()=>(window as any).interactions.scene.stand());expect((await player(page)).seatId).toBe(null);expect((await player(page)).x).toBeCloseTo(seat.approach.x,5);expect((await player(page)).z).toBeCloseTo(seat.approach.z,5);
  }
  await dispose(page);
});

test('chair approach precedes claim, conflict leaves the aisle free, and late ack cannot resurrect a cancelled sit',async({page})=>{
  await fixture(page);const seat=seats[11];await page.evaluate(seat=>{const h=(window as any).interactions;h.scene.teleportTo(seat.approach.x,seat.approach.z-1.5);h.scene.requestSeat(seat.id);},seat);expect((await stats(page)).interaction.pendingSeatId).toBe(seat.id);expect(await page.evaluate(()=>(window as any).interactions.commands.length)).toBe(0);await expect.poll(async()=>(await player(page)).seatId).toBe(seat.id);await page.evaluate(()=>{const h=(window as any).interactions;h.scene.stand();h.rejectSeat=true;h.scene.requestSeat(h.seats[11].id);});await expect(page.locator('.cs-scene-status')).toHaveText('That chair is already occupied.');expect((await player(page)).seatId).toBe(null);
  await page.evaluate(()=>{const h=(window as any).interactions;h.rejectSeat=false;h.delayMs=300;h.scene.requestSeat(h.seats[11].id);h.scene.walkTo(7,7);});await page.waitForTimeout(500);expect((await player(page)).seatId).toBe(null);await dispose(page);
});

test('remote seats, running, and transient reactions synchronize without replaying heartbeat IDs',async({page})=>{
  await fixture(page);const seat=seats[0];await page.evaluate(seat=>{const h=(window as any).interactions;h.remotePresence={...h.remotePresence,x:seat.x,z:seat.z,seatId:seat.id,seat,updatedAt:new Date().toISOString()};h.scene.updateSnapshot(h.snapshot());},seat);await expect.poll(async()=>(await stats(page)).occupants.find((p:any)=>p.id===remote.id).seatId).toBe(seat.id);expect(await page.evaluate(id=>(window as any).interactions.scene.requestSeat(id),seat.id)).toBe(false);
  await page.evaluate(()=>{const h=(window as any).interactions;h.remotePresence={...h.remotePresence,seatId:null,seat:null,x:6,z:2,motionMode:'run',updatedAt:new Date().toISOString(),interaction:{id:'remote-reaction',type:'reaction',value:'celebrate',createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+250).toISOString()}};h.scene.updateSnapshot(h.snapshot());});await expect(page.getByRole('status',{name:'Interaction Teammate reacts with celebrate',exact:true})).toBeVisible();await page.waitForTimeout(400);await expect(page.getByRole('status',{name:'Interaction Teammate reacts with celebrate',exact:true})).toHaveCount(0);await page.evaluate(()=>{const h=(window as any).interactions;h.remotePresence.interaction.expiresAt=new Date(Date.now()+8000).toISOString();h.remotePresence.updatedAt=new Date().toISOString();h.scene.updateSnapshot(h.snapshot());});await expect(page.getByRole('status',{name:'Interaction Teammate reacts with celebrate',exact:true})).toHaveCount(0);await dispose(page);
});

test('adult and senior rigs use the exported Run and Dance clips, with an authored seated senior pose',async({page},testInfo)=>{
  await fixture(page);expect((await stats(page)).interaction.availableEmotes).toEqual(['wave','dance']);await page.evaluate(()=>{const h=(window as any).interactions;h.scene.emote('dance');h.remotePresence={...h.remotePresence,updatedAt:new Date().toISOString(),interaction:{id:'senior-dance',type:'emote',value:'dance',createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+8000).toISOString()}};h.scene.updateSnapshot(h.snapshot());});await expect.poll(async()=>(await stats(page)).occupants.every((person:any)=>person.currentMotion==='dance'&&person.emoteWeight>.8)).toBe(true);
  const pose=()=>page.evaluate(()=>{const h=(window as any).interactions,hips:number[][]=[];h.scene.scene.traverse((node:any)=>{if(node.name==='Hips')hips.push(node.getWorldPosition(new h.THREE.Vector3()).toArray());});return hips;});const before=await pose();await page.waitForTimeout(300);const after=await pose();expect(before).toHaveLength(2);for(let index=0;index<2;index++)expect(Math.hypot(...before[index].map((value,axis)=>value-after[index][axis]))).toBeGreaterThan(.001);
  await page.evaluate(()=>{const h=(window as any).interactions;h.scene.walkTo(6,-2,'run');h.remotePresence={...h.remotePresence,x:6,z:2,motionMode:'run',interaction:null,updatedAt:new Date().toISOString()};h.scene.updateSnapshot(h.snapshot());});await expect.poll(async()=>(await stats(page)).occupants.every((person:any)=>person.runWeight>.8)).toBe(true);
  const seat=seats[8];await page.evaluate(seat=>{const h=(window as any).interactions;h.scene.teleportTo(2,2);h.remotePresence={...h.remotePresence,seatId:seat.id,seat,x:seat.x,z:seat.z,updatedAt:new Date().toISOString()};h.scene.updateSnapshot(h.snapshot());h.scene.camera.zoom=1.6;h.scene.camera.updateProjectionMatrix();},seat);await expect.poll(async()=>(await stats(page)).occupants.find((person:any)=>person.id===remote.id).currentMotion).toBe('sit');await page.waitForTimeout(350);const senior=(await stats(page)).occupants.find((person:any)=>person.id===remote.id);expect(senior.seatedHip[1]).toBeCloseTo(seat.seatHeight+.12,1);await page.screenshot({path:testInfo.outputPath('senior-seated.png')});await dispose(page);
});

test('teleport ray uses the ground plane below a chair projection; single-click still selects furniture',async({page})=>{
  await fixture(page);const seat=seats[0],point=await project(page,seat.x,seat.z,1.8);const expected=await page.evaluate(point=>{const h=(window as any).interactions,rect=h.scene.renderer.domElement.getBoundingClientRect(),ray=new h.THREE.Raycaster();ray.setFromCamera(new h.THREE.Vector2((point.x-rect.left)/rect.width*2-1,-(point.y-rect.top)/rect.height*2+1),h.scene.camera);const hit=ray.ray.intersectPlane(new h.THREE.Plane(new h.THREE.Vector3(0,1,0),-.08),new h.THREE.Vector3());return{x:hit.x,z:hit.z};},point);await page.mouse.dblclick(point.x,point.y,{button:'right',delay:80});expect((await player(page)).x).toBeCloseTo(expected.x,4);expect((await player(page)).z).toBeCloseTo(expected.z,4);expect(Math.abs(expected.x-seat.x)).toBeGreaterThan(1);
  const furniture=await project(page,seat.x,seat.z,.55);await page.mouse.click(furniture.x,furniture.y);await expect(page.getByRole('button',{name:'Sit in this chair',exact:true})).toBeVisible();expect((await player(page)).x).toBeCloseTo(expected.x,4);await dispose(page);
});

test('initial seated presence waits for the rig, survives avatar replacement, and pending Stand sends a release',async({page})=>{
  await fixture(page,seats[0]);expect((await player(page)).seatId).toBe(seats[0].id);expect(await page.evaluate(()=>(window as any).interactions.commands.length)).toBe(0);await page.evaluate(()=>{const h=(window as any).interactions;h.user.avatarId='city-025';h.scene.updateSnapshot(h.snapshot());});await expect.poll(async()=>(await player(page)).avatarId).toBe('city-025');expect((await player(page)).seatId).toBe(seats[0].id);
  expect(await page.evaluate(()=>(window as any).interactions.scene.react('__proto__'))).toBe(false);expect(await page.evaluate(()=>(window as any).interactions.scene.emote('constructor'))).toBe(false);await page.evaluate(()=>{const h=(window as any).interactions,snapshot=JSON.parse(JSON.stringify(h.snapshot()));delete snapshot.presence[0].seatId;delete snapshot.presence[0].seat;snapshot.presence[0].updatedAt=new Date().toISOString();h.scene.updateSnapshot(snapshot);});expect((await player(page)).seatId).toBe(seats[0].id);
  await page.evaluate(()=>{const h=(window as any).interactions;h.scene.stand();h.delayMs=300;h.scene.requestSeat(h.seats[0].id);h.moves=[];h.scene.stand();});expect(await page.evaluate(()=>(window as any).interactions.moves.at(-1)?.seatId)).toBe(null);await page.waitForTimeout(500);expect((await player(page)).seatId).toBe(null);await dispose(page);
});
