import {test,expect,type Page,type Route} from '@playwright/test';
import {conversationFixture} from './conversation-fixture';
import type {Workspace,User} from '../../src/lib/client';
const user:User={id:'10000000-0000-4000-8000-000000000271',name:'Message Reviewer',email:'messages@example.invalid',roleTitle:'Designer',avatarColor:'#607851',avatarId:null};
const peer={...user,id:'10000000-0000-4000-8000-000000000272',name:'Ari Rivera'};
const company={id:'20000000-0000-4000-8000-000000000271',name:'Conversation Pipeline Studio',slug:'conversation-pipeline',template:'blank',role:'owner'};
const room={id:'30000000-0000-4000-8000-000000000271',name:'Review room',kind:'meeting',capacity:8};
const legacy=(id:string,body:string,extra={})=>({id,body,roomId:null,createdAt:new Date().toISOString(),userId:peer.id,authorName:peer.name,...extra});
const json=(route:Route,data:unknown,status=200,headers?:Record<string,string>)=>route.fulfill({status,headers,contentType:'application/json',body:JSON.stringify(data)});
async function fixture(page:Page,count=80){
 const data:Workspace={company,members:[{...user,userId:user.id,role:'owner'},{...peer,userId:peer.id,role:'member'}],rooms:[room],presence:[],agents:[],tasks:[],messages:Array.from({length:count},(_,i)=>legacy('message-'+i,'Message '+i+' — a detailed update for the studio.')),activity:[],drives:[],openings:[],applications:[],layout:[]};
 const requests:{path:string;method:string;body:any;time:number;url:string}[]=[],errors:string[]=[];let uncertain=false,gap=false,throttled=false,throttledList=false,rejection=0,hangSend=false,holdRead=false,heldRead:Route|null=null,holdThread=false,heldThread:{route:Route;body:unknown}|null=null;
 const adapter=conversationFixture(id=>id===company.id?data:undefined,()=>user,async send=>{if(hangSend){hangSend=false;return true;}if(rejection){const status=rejection;rejection=0;await json(send.route,{error:'The message was rejected before acceptance.'},status);return true;}if(uncertain){uncertain=false;send.publish();await json(send.route,{error:'The response was interrupted after acceptance.'},503);return true;}return false;});
 page.on('pageerror',error=>errors.push(error.message));
 await page.route('**/api/**',async route=>{
  const request=route.request(),url=new URL(request.url()),path=url.pathname;requests.push({path,url:url.href,method:request.method(),body:request.postData()?request.postDataJSON():null,time:Date.now()});
  if(path==='/api/session')return json(route,{user,companies:[company],configured:true});
  if(path.endsWith('/workspace'))return json(route,{...data,messages:[legacy('forbidden-workspace-message','This old workspace message must never become chat history.')]});
  if(path.endsWith('/presence'))return json(route,{presence:[]});
  if(path.endsWith('/conversations')&&throttledList){throttledList=false;return json(route,{error:'Please wait before requesting conversations.'},429,{'retry-after':'3'});}
  if(path.endsWith('/read')&&holdRead){holdRead=false;heldRead=route;return;}
  if(path.endsWith('/messages')&&url.searchParams.has('parentId')&&holdThread){holdThread=false;const ledger=adapter.reconcile(company.id,'commons');heldThread={route,body:structuredClone({conversation:adapter.summary(company.id,'commons'),messages:[...ledger.messages.values()].filter(message=>message.parentId===url.searchParams.get('parentId')),hasMore:false,nextBefore:null})};return;}
  if(path.endsWith('/events')&&throttled){throttled=false;return json(route,{error:'Please wait before requesting more updates.'},429,{'retry-after':'3'});}
  if(path.endsWith('/events')&&gap){gap=false;const ledger=adapter.reconcile(company.id,'commons'),message=[...ledger.messages.values()].at(-1)!;return json(route,{events:[{sequence:String(BigInt(url.searchParams.get('after')!)+BigInt(2)),type:'message.created',messageId:message.id,message,createdAt:new Date().toISOString()}],cursor:String(ledger.sequence),lastSequence:String(ledger.sequence),hasMore:false,resetRequired:false});}
  if(await adapter.handle(route))return;return json(route,{error:'Unexpected fixture request: '+path},501);
 });
 return{data,adapter,requests,errors,uncertain(){uncertain=true;},reject(status=400){rejection=status;},gap(){gap=true;},throttle(){throttled=true;},throttleList(){throttledList=true;},hangSend(){hangSend=true;},holdRead(){holdRead=true;},get heldRead(){return heldRead;},holdThread(){holdThread=true;},get heldThread(){return heldThread;}};
}
const composer=(page:Page)=>page.getByRole('textbox',{name:'Your message',exact:true});
const log=(page:Page)=>page.getByRole('log',{name:'Conversation messages',exact:true});
const row=(page:Page,id:string)=>page.locator('[data-message-id="'+id+'"] article');
test.beforeEach(({baseURL})=>test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Local intercepted fixtures only.'));

test('dedicated history pages preserve the reading anchor and never use workspace message samples',async({page})=>{
 const state=await fixture(page);await page.goto('/#chat');await expect(page.locator('.message')).toHaveCount(50);await expect(log(page)).not.toContainText('old workspace message');
 await log(page).evaluate(element=>{element.scrollTop=0;element.dispatchEvent(new Event('scroll'));});const before=await row(page,'message-30').boundingBox();
 await page.getByRole('button',{name:'Load older messages',exact:true}).click();await expect(page.locator('.message')).toHaveCount(80);const after=await row(page,'message-30').boundingBox();expect(Math.abs(after!.y-before!.y)).toBeLessThan(4);await expect(page.getByRole('button',{name:'Load older messages',exact:true})).toHaveCount(0);expect(state.requests.some(request=>new URL(request.url).searchParams.has('before'))).toBe(true);expect(state.errors).toEqual([]);
});

test('an uncertain committed send retries the same UUID and preserves a newer draft without duplicating',async({page})=>{
 const state=await fixture(page,3);await page.goto('/#chat');await expect(composer(page)).toBeEnabled();state.uncertain();await composer(page).fill('One committed message');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('#main').getByRole('alert')).toContainText('Delivery is unconfirmed');
 await composer(page).fill('A newer draft');await page.getByRole('button',{name:'Retry original message',exact:true}).click();await expect(page.getByText('Message posted',{exact:true})).toBeVisible();await expect(composer(page)).toHaveValue('A newer draft');await expect(log(page).getByText('One committed message',{exact:true})).toHaveCount(1);
 const sends=state.requests.filter(request=>request.path.endsWith('/messages')&&request.method==='POST');expect(sends).toHaveLength(2);expect(sends[0].body.clientId).toMatch(/^[0-9a-f-]{36}$/);expect(sends[1].body).toEqual(sends[0].body);expect(state.data.messages.filter(message=>message.body==='One committed message')).toHaveLength(1);
});

test('ordered event pages catch up a backlog and read markers do not acknowledge their own events',async({page})=>{
 const state=await fixture(page,4);await page.goto('/#chat');await expect(page.locator('.message')).toHaveCount(4);await expect.poll(()=>state.requests.filter(request=>request.path.endsWith('/read')).length).toBe(1);
 for(let i=0;i<160;i++)state.data.messages.push(legacy('burst-'+i,'Catch-up update '+i));await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(log(page)).toContainText('Catch-up update 159');await expect(page.locator('.message')).toHaveCount(164);
 const queries=state.requests.filter(request=>request.path.endsWith('/events')).map(request=>BigInt(new URL(request.url).searchParams.get('after')!));expect(queries.some((value,index)=>index>0&&value-queries[index-1]>=BigInt(100))).toBe(true);
 await page.waitForTimeout(4300);const reads=state.requests.filter(request=>request.path.endsWith('/read'));expect(reads.length).toBeLessThanOrEqual(3);expect(reads.at(-1)!.body.sequence).toBe(state.adapter.reconcile(company.id,'commons').messages.get('burst-159')!.sequence);expect(state.errors).toEqual([]);
});

test('a cursor gap reloads a consistent history snapshot without duplicate messages',async({page})=>{
 const state=await fixture(page,3);await page.goto('/#chat');await expect(page.locator('.message')).toHaveCount(3);state.data.messages.push(legacy('gap-message','Recovered after a cursor gap'));state.gap();await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(log(page)).toContainText('Recovered after a cursor gap');expect(state.requests.filter(request=>request.path.endsWith('/messages')&&request.method==='GET').length).toBeGreaterThanOrEqual(2);await expect(page.locator('.message')).toHaveCount(4);
});

test('agent identities, threaded replies, reaction sets, message edits and tombstones stay explicit',async({page})=>{
 const state=await fixture(page,0);state.data.messages.push(legacy('agent-message','An agent prepared the review.',{actor:{kind:'agent',id:'40000000-0000-4000-8000-000000000271',name:'Review agent',avatarColor:null},userId:null,authorName:'Review agent'}) as any);state.data.messages.push(legacy('own-message','My editable message',{userId:user.id,authorName:user.name}));await page.goto('/#chat');
 await expect(row(page,'agent-message').getByText('AI agent',{exact:true})).toBeVisible();await expect(row(page,'agent-message').getByRole('button',{name:'Edit message',exact:true})).toHaveCount(0);
 await row(page,'agent-message').getByRole('button',{name:'Reply',exact:true}).click();await expect(page.getByRole('button',{name:'Back to conversation',exact:true})).toBeVisible();await expect(composer(page)).toBeEnabled();await composer(page).fill('A human follow-up');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(log(page)).toContainText('A human follow-up');await page.getByRole('button',{name:'Back to conversation',exact:true}).click();await expect(row(page,'agent-message').getByRole('button',{name:'1 reply',exact:true})).toBeVisible();await expect(log(page).getByText('A human follow-up',{exact:true})).toHaveCount(0);
 const own=row(page,'own-message');await own.getByRole('button',{name:'Add reaction',exact:true}).click();await own.getByRole('button',{name:'React with thumbsup',exact:true}).click();await expect(own.getByRole('button',{name:'thumbsup: 1 reactions',exact:true})).toHaveAttribute('aria-pressed','true');await own.getByRole('button',{name:'thumbsup: 1 reactions',exact:true}).click();await expect(own.getByRole('button',{name:'thumbsup: 1 reactions',exact:true})).toHaveCount(0);
 await own.getByRole('button',{name:'Edit message',exact:true}).click();await own.getByRole('textbox',{name:'Edit message text',exact:true}).fill('Edited with revision control');await own.getByRole('button',{name:'Save changes',exact:true}).click();await expect(own.getByText('Edited with revision control',{exact:true})).toBeVisible();await expect(own.getByText('edited',{exact:true})).toBeVisible();await own.getByRole('button',{name:'Delete message',exact:true}).click();await own.getByRole('button',{name:'Delete message',exact:true}).last().click();await expect(own.getByText('Message deleted',{exact:true})).toBeVisible();expect(state.errors).toEqual([]);
});

test('429 Retry-After pauses automatic conversation polling',async({page})=>{
 const state=await fixture(page,3);await page.goto('/#chat');await expect(page.locator('.message')).toHaveCount(3);state.throttle();await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(page.locator('#main').getByRole('alert')).toContainText('Please wait before requesting more updates.');const last=state.requests.filter(request=>request.path.endsWith('/events')).at(-1)!;
 await page.waitForTimeout(1800);expect(state.requests.filter(request=>request.path.endsWith('/events')).at(-1)!.time).toBe(last.time);await expect.poll(()=>state.requests.filter(request=>request.path.endsWith('/events')).at(-1)!.time,{timeout:6000}).toBeGreaterThan(last.time);const next=state.requests.filter(request=>request.path.endsWith('/events')&&request.time>last.time)[0];expect(next.time-last.time).toBeGreaterThanOrEqual(2900);
});

test('a definite initial rejection unlocks an edited draft but an earlier uncertain UUID stays protected',async({page})=>{
 const state=await fixture(page,0);await page.goto('/#chat');await expect(composer(page)).toBeEnabled();state.reject(400);await composer(page).fill('Rejected original');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('#main').getByRole('alert')).toContainText('Message not sent');await expect(page.getByRole('button',{name:'Retry original message',exact:true})).toHaveCount(0);await composer(page).fill('Corrected message');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(log(page)).toContainText('Corrected message');
 state.uncertain();await composer(page).fill('Uncertain accepted original');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.getByRole('button',{name:'Retry original message',exact:true})).toBeVisible();state.reject(400);await page.getByRole('button',{name:'Retry original message',exact:true}).click();await expect(page.locator('#main').getByRole('alert')).toContainText('Delivery is unconfirmed');await composer(page).fill('Kept separately');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('#main').getByRole('alert')).toContainText('Retry the earlier message first');const sends=state.requests.filter(request=>request.method==='POST'&&request.path.endsWith('/messages'));expect(sends).toHaveLength(4);expect(sends[3].body.clientId).toBe(sends[2].body.clientId);expect(sends[1].body.clientId).not.toBe(sends[0].body.clientId);
});

test('a failed older read request retains the newer marker queued while it was in flight',async({page})=>{
 const state=await fixture(page,4);state.holdRead();await page.goto('/#chat');await expect.poll(()=>!!state.heldRead).toBe(true);state.data.messages.push(legacy('newer-read','A newer visible message'));await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(log(page)).toContainText('A newer visible message');await json(state.heldRead!,{error:'Temporary read-marker failure'},503);await expect.poll(()=>state.requests.filter(request=>request.path.endsWith('/read')).at(-1)?.body.sequence,{timeout:10000}).toBe(state.adapter.reconcile(company.id,'commons').messages.get('newer-read')!.sequence);expect(state.requests.filter(request=>request.path.endsWith('/read'))).toHaveLength(2);
});

test('reading thread replies never acknowledges an unseen top-level message',async({page})=>{
 const state=await fixture(page,1);await page.goto('/#chat');await expect(row(page,'message-0')).toBeVisible();await expect.poll(()=>state.requests.filter(request=>request.path.endsWith('/read')).length).toBe(1);await row(page,'message-0').getByRole('button',{name:'Reply',exact:true}).click();await expect(composer(page)).toBeEnabled();const reads=state.requests.filter(request=>request.path.endsWith('/read')).length;state.data.messages.push(legacy('unseen-root','A different conversation update'));state.data.messages.push(legacy('thread-only','A reply visible in this thread',{parentId:'message-0'}));await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(log(page)).toContainText('A reply visible in this thread');await expect(log(page)).not.toContainText('A different conversation update');await page.waitForTimeout(2200);expect(state.requests.filter(request=>request.path.endsWith('/read'))).toHaveLength(reads);await page.getByRole('button',{name:'Back to conversation',exact:true}).click();await expect(log(page)).toContainText('A different conversation update');await expect.poll(()=>state.requests.filter(request=>request.path.endsWith('/read')).at(-1)?.body.sequence).toBe(state.adapter.reconcile(company.id,'commons').messages.get('unseen-root')!.sequence);
});

test('a root history reset invalidates an inactive cached thread so missed replies load on reopen',async({page})=>{
 const state=await fixture(page,1);state.data.messages.push(legacy('old-reply','An earlier reply',{parentId:'message-0'}));await page.goto('/#chat');await row(page,'message-0').getByRole('button',{name:'1 reply',exact:true}).click();await expect(log(page)).toContainText('An earlier reply');await page.getByRole('button',{name:'Back to conversation',exact:true}).click();state.data.messages.push(legacy('recovered-reply','A reply committed during recovery',{parentId:'message-0'}));state.gap();await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect.poll(()=>state.requests.filter(request=>request.method==='GET'&&request.path.endsWith('/messages')&&!new URL(request.url).searchParams.has('parentId')).length).toBe(2);await row(page,'message-0').getByRole('button',{name:'2 replies',exact:true}).click();await expect(log(page)).toContainText('A reply committed during recovery');await expect(log(page)).toContainText('An earlier reply');
});

test('a pre-reset thread response cannot restore stale loaded state after root recovery',async({page})=>{
 const state=await fixture(page,0);state.data.messages.push(legacy('own-parent','Initial root version',{userId:user.id,authorName:user.name}));state.data.messages.push(legacy('old-reply','Old thread response',{parentId:'own-parent'}));await page.goto('/#chat');await expect(row(page,'own-parent')).toBeVisible();state.holdThread();await row(page,'own-parent').getByRole('button',{name:'1 reply',exact:true}).click();await expect.poll(()=>!!state.heldThread).toBe(true);await page.getByRole('button',{name:'Back to conversation',exact:true}).click();const parent=row(page,'own-parent');await parent.getByRole('button',{name:'Edit message',exact:true}).click();const remote=state.adapter.reconcile(company.id,'commons').messages.get('own-parent')!;remote.body='Remote root revision';remote.revision++;state.data.messages.push(legacy('new-reply','Fresh thread reply',{parentId:'own-parent'}));await parent.getByRole('textbox',{name:'Edit message text',exact:true}).fill('A conflicting local change');await parent.getByRole('button',{name:'Save changes',exact:true}).click();await expect(parent.getByRole('alert')).toContainText('changed by another request');await parent.getByRole('button',{name:'Cancel',exact:true}).click();await json(state.heldThread!.route,state.heldThread!.body);await parent.getByRole('button',{name:'2 replies',exact:true}).click();await expect(log(page)).toContainText('Fresh thread reply');await expect(page.locator('.message')).toHaveCount(3);
});

test('a hung send times out, releases Sending state and retries its original idempotency UUID',async({page})=>{
 const state=await fixture(page,0);await page.clock.install();await page.goto('/#chat');await expect(composer(page)).toBeEnabled();state.hangSend();await composer(page).fill('A request with a bounded lifetime');await page.getByRole('button',{name:'Send',exact:true}).click();await expect.poll(()=>state.requests.filter(request=>request.method==='POST'&&request.path.endsWith('/messages')).length).toBe(1);await page.clock.fastForward(21000);await expect(page.locator('#main').getByRole('alert')).toContainText('request timed out');await expect(page.getByRole('button',{name:'Sending…',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Retry original message',exact:true}).click();await expect(log(page)).toContainText('A request with a bounded lifetime');const sends=state.requests.filter(request=>request.method==='POST'&&request.path.endsWith('/messages'));expect(sends).toHaveLength(2);expect(sends[1].body.clientId).toBe(sends[0].body.clientId);
});

test('a rate-limited list stops the rest of that automatic polling cycle',async({page})=>{
 const state=await fixture(page,3);state.throttleList();await page.goto('/#chat');await expect(page.locator('#workspace-navigation').getByRole('alert')).toContainText('Please wait before requesting conversations.');await page.waitForTimeout(1800);expect(state.requests.filter(request=>request.path.endsWith('/events')||request.path.endsWith('/messages'))).toHaveLength(0);await expect(page.locator('.message')).toHaveCount(3);const listing=state.requests.find(request=>request.path.endsWith('/conversations'))!,history=state.requests.find(request=>request.path.endsWith('/messages'))!;expect(history.time-listing.time).toBeGreaterThanOrEqual(2900);
});
