import type {Route} from '@playwright/test';
import type {User,Workspace} from '../../src/lib/client';
import type {ConversationEvent,ConversationMessage,ConversationSummary} from '../../src/lib/conversation-protocol';
type Ledger={sequence:number;messages:Map<string,ConversationMessage>;events:ConversationEvent[];reads:Map<string,string>};
type Send={route:Route;companyId:string;channel:string;body:any;author:User;publish:()=>ConversationMessage};
export function conversationFixture(workspace:(id:string)=>Workspace|undefined,user:()=>User,onSend?:(send:Send)=>Promise<boolean>|boolean){
 const ledgers=new Map<string,Ledger>(),json=(route:Route,value:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});
 const key=(companyId:string,channel:string)=>companyId+':'+channel;
 function raw(companyId:string,channel:string){const id=key(companyId,channel);if(!ledgers.has(id))ledgers.set(id,{sequence:0,messages:new Map(),events:[],reads:new Map()});return ledgers.get(id)!;}
 function event(ledger:Ledger,type:ConversationEvent['type'],message:ConversationMessage|null,read?:ConversationEvent['read']){const sequence=String(++ledger.sequence);if(message)message.lastEventSequence=sequence;const parent=message?.parentId?ledger.messages.get(message.parentId):undefined;if(parent){parent.replyCount=[...ledger.messages.values()].filter(value=>value.parentId===parent.id&&!value.deletedAt).length;parent.lastEventSequence=sequence;}ledger.events.push({sequence,type,messageId:message?.id||null,message:message?structuredClone(message):null,parentMessage:parent?structuredClone(parent):undefined,read,createdAt:new Date().toISOString()});}
 function materialize(companyId:string,channel:string,legacy:any){const ledger=raw(companyId,channel),sequence=String(ledger.sequence+1),author=legacy.actor||{kind:'human',id:legacy.userId,name:legacy.authorName,avatarColor:null};const message:ConversationMessage={id:legacy.id,conversationId:key(companyId,channel),roomId:channel==='commons'?null:channel,parentId:legacy.parentId||null,sequence,lastEventSequence:sequence,clientId:legacy.clientId||null,body:legacy.body,createdAt:legacy.createdAt||new Date().toISOString(),editedAt:null,deletedAt:null,revision:1,userId:author.kind==='human'?author.id:null,agentId:author.kind==='agent'?author.id:null,authorName:author.name,actor:author,reactions:[],replyCount:0};ledger.messages.set(message.id,message);event(ledger,'message.created',message);return message;}
 function reconcile(companyId:string,channel:string){const ledger=raw(companyId,channel);for(const message of workspace(companyId)?.messages||[])if((message.roomId||'commons')===channel&&!ledger.messages.has(message.id))materialize(companyId,channel,message);return ledger;}
 function summary(companyId:string,channel:string):ConversationSummary{const ledger=reconcile(companyId,channel),readSequence=ledger.reads.get(user().id)||'0';return{id:key(companyId,channel),channel,roomId:channel==='commons'?null:channel,name:channel==='commons'?'Company commons':workspace(companyId)?.rooms.find(room=>room.id===channel)?.name||'Unavailable',lastSequence:String(ledger.sequence),readSequence,unreadCount:[...ledger.messages.values()].filter(message=>!message.parentId&&BigInt(message.sequence)>BigInt(readSequence)&&message.actor.id!==user().id&&!message.deletedAt).length};}
 function publish(companyId:string,channel:string,body:any,author:User){const ledger=reconcile(companyId,channel),old=[...ledger.messages.values()].find(message=>message.clientId===body.clientId&&message.actor.id===author.id);if(old)return structuredClone(old);const legacy={id:'posted-'+crypto.randomUUID(),roomId:channel==='commons'?null:channel,parentId:body.parentId||null,body:body.body,clientId:body.clientId,createdAt:new Date().toISOString(),userId:author.id,authorName:author.name};workspace(companyId)!.messages.push(legacy);return structuredClone(materialize(companyId,channel,legacy));}
 async function handle(route:Route){
  const request=route.request(),url=new URL(request.url()),match=url.pathname.match(/^\/api\/companies\/([^/]+)\/conversations(?:\/([^/]+)(?:\/(messages|events|read)(?:\/([^/]+)(?:\/(reactions))?)?)?)?$/);if(!match)return false;
  const [,companyId,channel,kind,messageId,reactions]=match,current=workspace(companyId);if(!current){await json(route,{error:'Missing company'},404);return true;}
  if(!channel){await json(route,{conversations:['commons',...current.rooms.map(room=>room.id)].map(value=>summary(companyId,value))});return true;}
  const ledger=reconcile(companyId,channel),method=request.method(),body=method==='GET'?null:request.postDataJSON();
  if(kind==='messages'&&method==='GET'){const limit=Number(url.searchParams.get('limit')||50),before=url.searchParams.get('before'),parentId=url.searchParams.get('parentId');const eligible=[...ledger.messages.values()].filter(message=>message.parentId===parentId&&(!before||BigInt(message.sequence)<BigInt(before))).sort((a,b)=>Number(BigInt(a.sequence)-BigInt(b.sequence))),messages=eligible.slice(-limit);await json(route,{conversation:summary(companyId,channel),messages,nextBefore:eligible.length>limit?messages[0].sequence:null,hasMore:eligible.length>limit});return true;}
  if(kind==='events'){const after=BigInt(url.searchParams.get('after')||'0'),limit=Number(url.searchParams.get('limit')||100),remaining=ledger.events.filter(value=>BigInt(value.sequence)>after),events=remaining.slice(0,limit).map(value=>({...value,message:value.messageId?ledger.messages.get(value.messageId):null,parentMessage:value.parentMessage?ledger.messages.get(value.parentMessage.id):undefined,read:value.read?.actor.id===user().id?value.read:undefined}));await json(route,{events,cursor:events.at(-1)?.sequence||String(after),lastSequence:String(ledger.sequence),hasMore:remaining.length>limit,resetRequired:false});return true;}
  if(kind==='read'){const old=ledger.reads.get(user().id)||'0';if(BigInt(body.sequence)>BigInt(old)){ledger.reads.set(user().id,body.sequence);event(ledger,'read.updated',null,{actor:{kind:'human',id:user().id,name:user().name,avatarColor:null},sequence:body.sequence});}await json(route,{conversation:summary(companyId,channel)});return true;}
  if(kind==='messages'&&method==='POST'){const author=user(),send={route,companyId,channel,body,author,publish:()=>publish(companyId,channel,body,author)};if(onSend&&await onSend(send))return true;await json(route,{message:send.publish(),replayed:false},201);return true;}
  const message=ledger.messages.get(messageId);if(!message){await json(route,{error:'Message not found'},404);return true;}
  if(!reactions&&body.revision!==message.revision){await json(route,{error:'This message was changed by another request.',code:'MESSAGE_CONFLICT'},409);return true;}
  if(reactions){const previous=message.reactions.find(reaction=>reaction.emoji===body.emoji);message.reactions=message.reactions.filter(reaction=>reaction.emoji!==body.emoji);if(body.active)message.reactions.push({emoji:body.emoji,count:previous?.count||1,mine:true});event(ledger,'reaction.changed',message);}
  else if(method==='PATCH'){message.body=body.body;message.editedAt=new Date().toISOString();message.revision++;event(ledger,'message.edited',message);}
  else if(method==='DELETE'){message.body='';message.deletedAt=new Date().toISOString();message.revision++;event(ledger,'message.deleted',message);}
  await json(route,{message:structuredClone(message)});return true;
 }
 return {handle,ledgers,reconcile,publish,summary};
}
