import {test,expect,type Locator,type Page} from '@playwright/test';
import type {Workspace,LayoutItem} from '../../src/lib/client';

// Opt in only when the loopback application points to a disposable local DB.
// This case deliberately creates one account/company using real authenticated
// HTTP APIs through the product UI. It never intercepts or replaces API calls.
test.beforeEach(({baseURL})=>{
 test.skip(process.env.COATRIA_FLOOR_REAL_DB!=='1','Set COATRIA_FLOOR_REAL_DB=1 for the isolated local persistence check.');
 test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Real fixture creation is restricted to a loopback application.');
});

const button=(page:Page,name:string)=>page.getByRole('button',{name,exact:true});
const field=(page:Page,name:string)=>page.getByLabel(name,{exact:true});
async function number(page:Page,name:string){return Number(await field(page,name).inputValue());}
async function editNumber(page:Page,name:string,value:number){await field(page,name).fill(String(value));await field(page,name).press('Tab');}
async function bounds(locator:Locator){const box=await locator.boundingBox();expect(box).not.toBeNull();return box!;}
async function drag(page:Page,locator:Locator,dx:number,dy:number){const box=await bounds(locator),x=box.x+box.width/2,y=box.y+box.height/2;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+dx,y+dy,{steps:12});await page.mouse.up();}

test('a real blank workplace persists a moved and resized floor into the 3D office',async({page,context})=>{
 const suffix=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),name='Floor Persistence QA',errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/');await field(page,'Full name').fill(name);await field(page,'Email address').fill(`floor-${suffix}@example.invalid`);await field(page,'Password').fill(`Floor persistence passphrase ${suffix}`);const signupResponse=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/auth/signup');await button(page,'Create your account').click();expect((await signupResponse).ok(),'The real local signup request must succeed.').toBe(true);
 await field(page,'Company name').fill('Floor Persistence Studio');await field(page,'Workspace address').fill('floor-'+suffix);await button(page,'Choose your space').click();await page.getByRole('button',{name:/A blank canvas/}).click();const creationResponse=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/companies');await button(page,'Create your workplace').click();expect((await creationResponse).ok(),'The real local company request must succeed.').toBe(true);await expect(button(page,'Edit space')).toBeVisible();
 const sessionResponse=await context.request.get('/api/session');expect(sessionResponse.ok()).toBe(true);const session=await sessionResponse.json();expect(session.user.name).toBe(name);expect(session.companies).toHaveLength(1);const companyId:string=session.companies[0].id;
 const beforeResponse=await context.request.get(`/api/companies/${companyId}/workspace`);expect(beforeResponse.ok()).toBe(true);const before=await beforeResponse.json() as Workspace;expect(before.company.template).toBe('blank');expect(before.layout).toHaveLength(0);

 await button(page,'Edit space').click();await button(page,'Workstation').click();const object=page.locator('[data-object-id]').first(),floor=await bounds(page.getByTestId('floor-plan'));const originalLeft=await number(page,'Left (m)'),originalTop=await number(page,'Top (m)');await drag(page,object,-floor.width*.15,-floor.height*.125);expect(await number(page,'Left (m)')).toBeLessThan(originalLeft-2);expect(await number(page,'Top (m)')).toBeLessThan(originalTop-1);
 const originalWidth=await number(page,'Width (m)');await drag(page,button(page,'Resize East'),floor.width/20,0);expect(await number(page,'Width (m)')).toBeGreaterThan(originalWidth+.5);await field(page,'Label').fill('Persisted editorial station');await editNumber(page,'Floor width (m)',24);await editNumber(page,'Floor depth (m)',18);
 const physical={x:await number(page,'Left (m)'),y:await number(page,'Top (m)'),w:await number(page,'Width (m)'),h:await number(page,'Depth (m)')};const savedResponse=page.waitForResponse(r=>r.request().method()==='PATCH'&&new URL(r.url()).pathname===`/api/companies/${companyId}/layout`);await button(page,'Save shared floor plan').click();const response=await savedResponse;expect(response.ok()).toBe(true);const submitted=response.request().postDataJSON(),accepted=await response.json();expect(submitted.floor).toEqual({width:24,depth:18});expect(submitted.revision).toBe(before.layoutRevision||0);expect(accepted.layoutRevision).toBe((before.layoutRevision||0)+1);await expect(page.getByText('Shared floor plan is up to date',{exact:true})).toBeVisible();

 await page.reload();await button(page,'Select Persisted editorial station').click();expect(await number(page,'Floor width (m)')).toBe(24);expect(await number(page,'Floor depth (m)')).toBe(18);for(const [key,label] of [['x','Left (m)'],['y','Top (m)'],['w','Width (m)'],['h','Depth (m)']] as const)expect(await number(page,label)).toBeCloseTo(physical[key],2);await expect(button(page,'Save shared floor plan')).toBeDisabled();
 const persistedResponse=await context.request.get(`/api/companies/${companyId}/workspace`);expect(persistedResponse.ok()).toBe(true);const persisted=await persistedResponse.json() as Workspace;expect(persisted.floor).toEqual({width:24,depth:18});expect(persisted.layoutRevision).toBe(accepted.layoutRevision);expect(persisted.layout).toHaveLength(1);const stored:LayoutItem=persisted.layout[0];expect(stored.label).toBe('Persisted editorial station');expect(stored.x*24/100).toBeCloseTo(physical.x,2);expect(stored.y*18/100).toBeCloseTo(physical.y,2);expect(stored.w*24/100).toBeCloseTo(physical.w,2);expect(stored.h*18/100).toBeCloseTo(physical.h,2);

 await button(page,'Back to the office').click();await expect(page.locator('canvas')).toBeVisible();await expect.poll(()=>page.evaluate(()=>(window as any).CoatriaScene?.instance?.diagnostics.floor)).toEqual({width:24,depth:18});const scene=await page.evaluate(()=>(window as any).CoatriaScene.instance.diagnostics);expect(scene.objects).toHaveLength(1);expect(scene.floorBounds).toEqual({minX:-12,maxX:12,minZ:-9,maxZ:9});const rendered=scene.objects[0];expect(rendered.id).toBe(stored.id);expect(rendered.width).toBeCloseTo(stored.w*24/100,5);expect(rendered.depth).toBeCloseTo(stored.h*18/100,5);expect(rendered.x).toBeCloseTo((stored.x+stored.w/2)*24/100-12,5);expect(rendered.z).toBeCloseTo((stored.y+stored.h/2)*18/100-9,5);expect(rendered.meshBounds.minX).toBeGreaterThanOrEqual(rendered.bounds.minX-.0001);expect(rendered.meshBounds.maxX).toBeLessThanOrEqual(rendered.bounds.maxX+.0001);expect(rendered.meshBounds.minZ).toBeGreaterThanOrEqual(rendered.bounds.minZ-.0001);expect(rendered.meshBounds.maxZ).toBeLessThanOrEqual(rendered.bounds.maxZ+.0001);expect(errors).toEqual([]);
});
