import {test,expect,type Page,type Route} from '@playwright/test';
import {STUDIO_TEMPLATES,STUDIO_SKILLS,type StudioReadableProjectDetail,type StudioGeneratedShot} from '../../src/lib/studio-protocol';
import type {HiggsfieldRequest} from '../../src/lib/higgsfield-protocol';
import type {HiggsfieldArchive} from '../../src/lib/higgsfield-archive-protocol';

const ids={company:'11111111-1111-4111-8111-111111111111',project:'22222222-2222-4222-8222-222222222222',job:'33333333-3333-4333-8333-333333333333',output:'44444444-4444-4444-8444-444444444444',binding:'55555555-5555-4555-8555-555555555555',connection:'66666666-6666-4666-8666-666666666666',archive:'77777777-7777-4777-8777-777777777777',user:'88888888-8888-4888-8888-888888888888',folder:'99999999-9999-4999-8999-999999999999'};
const date='2026-09-20T00:00:00Z';
function fixture(admin=true,enabled=true,kind?:'image'|'video'|'audio'){
 const role=admin?'owner':'member',user={id:ids.user,name:'Archive reviewer',email:'archive@example.invalid',roleTitle:'Producer',avatarColor:'#607850',avatarId:null},company={id:ids.company,name:'Archive studio',slug:'archive-studio',template:'blank',role};
 const template=STUDIO_TEMPLATES.find(item=>item.id==='ai-production')!,roles=template.roles.map(item=>({...item,humanId:null,agentId:null}));
 const common={id:ids.project,name:'Archive campaign',clientName:'Synthetic client',brief:'Synthetic archive browser fixture.',productionPath:'higgsfield' as const,dueDate:null,aiPolicy:'allowed' as const,revision:7,status:'planning' as const,gates:{},createdAt:date,updatedAt:date};
 const project:StudioReadableProjectDetail['project']=kind?{...common,contractVersion:2,spec:kind==='image'?{kind,format:'png',width:1024,height:1024,color:{mode:'not_required'}}:kind==='video'?{kind,format:'mp4',width:1920,height:1080,codec:'h264',color:{mode:'not_required'},frameRate:{mode:'constant',numerator:24,denominator:1},audio:{mode:'none'}}:{kind,format:'wav',codec:'pcm_s16le',sampleRateHz:48000,channels:1}}:{...common,spec:{width:1920,height:1080,fpsNumerator:24,fpsDenominator:1,format:'mp4',colorSpace:'Rec.709'}};
 const workItems:StudioReadableProjectDetail['workItems']=kind?[{id:ids.folder,taskId:ids.output,shotId:ids.binding,stage:'generation',roleKey:'gen_artists',execution:'creative',title:'Generate hero '+kind,status:'todo',revision:3,submissionSummary:'',approvedBy:null,agentId:null,humanId:ids.user,dependencies:[],readiness:'ready',blockedReason:null}]:[];
 const shots:StudioReadableProjectDetail['shots']=kind?[{id:ids.binding,kind,code:'D010',description:'Approved hero media',...kind==='image'?{}:{durationMs:{min:1999,max:2001}}} as StudioGeneratedShot]:[];
 const connection={id:ids.connection,name:'Production volume',provider:'runpod',region:'US-NC-2',volumeId:'synthetic-volume',status:'configured',revision:2,createdAt:date,credentialsConfigured:true,providerVerified:false};
 const binding={id:ids.binding,projectId:ids.project,connectionId:ids.connection,revision:4,createdAt:date,connection};
 const archive:HiggsfieldArchive={id:ids.archive,projectId:ids.project,requestId:ids.job,jobId:ids.job,outputId:ids.output,outputIdentity:'a'.repeat(64),kind:'image',status:'proposed',revision:1,requestHash:'b'.repeat(64),projectRevision:7,bindingId:ids.binding,bindingRevision:4,storageConnectionId:ids.connection,storageConnectionRevision:2,destination:{parentId:null,fileId:null,name:'output-44444444',ancestors:[]},maxBytes:256*1024**2,sourceAttribution:{requestedBy:ids.user,agentId:null,runId:null,agentSponsorId:null,approvedBy:ids.user},proposedBy:ids.user,proposedAgentId:null,createdAt:date,approvedBy:null,approvedAt:null,expiresAt:null,revokedAt:null,approvedProjectRevision:null,approvedBindingRevision:null,uploadId:null,versionId:null,diagnosticCode:null,fetched:null,bytesVerified:false};
 return {user,company,roles,project,workItems,shots,kind,binding,archive,archives:[] as HiggsfieldArchive[],requests:[] as HiggsfieldRequest[],projectReads:[] as string[],enabled,writes:[] as {path:string;body:any}[],handler:undefined as ((route:Route,url:URL)=>Promise<boolean>)|undefined};
}
async function mock(page:Page,state:ReturnType<typeof fixture>){await page.route('**/api/**',async route=>{
 const url=new URL(route.request().url()),path=url.pathname,method=route.request().method();if(method==='GET'&&path.endsWith('/studio/projects/'+ids.project))state.projectReads.push(url.search);if(method!=='GET'&&path.includes('/higgsfield/'))state.writes.push({path,body:route.request().postDataJSON()});if(await state.handler?.(route,url))return;
 let data:unknown;
 if(path==='/api/session')data={user:state.user,companies:[state.company],configured:true};
 else if(path.endsWith('/workspace'))data={company:state.company,rooms:[],members:[{...state.user,userId:ids.user,role:state.company.role}],agents:[],tasks:[],messages:[],presence:[],activity:[],drives:[],openings:[],applications:[],layout:[]};
 else if(path.endsWith('/presence'))data={presence:[]};
 else if(path.endsWith('/studio'))data={templates:STUDIO_TEMPLATES,skills:STUDIO_SKILLS,profile:{templateId:'ai-production',revision:1,roles:state.roles},projects:[state.project],hasMore:false,nextAfter:null};
 else if(path.endsWith('/'+ids.project))data={project:state.project,roles:state.roles,skills:STUDIO_SKILLS,workItems:state.workItems,shots:state.shots,artifacts:[],reviews:[],deliveries:[]};
 else if(path.endsWith('/higgsfield'))data={status:'connected',revision:1,officialEndpoint:'https://higgsfield.ai/mcp',toolCount:3,tools:['generate_image','generate_video','generate_audio'].map(name=>({name,description:'Fixture tool',inputSchema:{}}))};
 else if(path.endsWith('/higgsfield/requests')){if(method==='POST'){const body=route.request().postDataJSON();const request:HiggsfieldRequest={id:ids.job,projectId:ids.project,workItemId:body.workItemId,taskRevision:3,tool:body.tool,arguments:body.arguments,note:body.note,requestHash:'c'.repeat(64),status:'proposed',createdAt:date};state.requests=[request];data={request,replayed:false};}else data={requests:state.requests,nextAfter:null};}
 else if(path.endsWith('/higgsfield/jobs'))data={jobs:[{id:ids.job,projectId:ids.project,requestId:ids.job,kind:'image',model:'fixture',status:'completed',diagnosticCode:null,pollAttempts:1,nextPollAt:null,createdAt:date,updatedAt:date,outputs:[{id:ids.output,ordinal:0,kind:'image',locatorIdentity:'a'.repeat(64),bytesVerified:false,url:'https://private.invalid/?secret=do-not-render'}]}],hasMore:false,nextAfter:null};
 else if(path.endsWith('/files'))data={binding:state.binding,items:url.searchParams.has('parentId')?[]:[{kind:'folder',id:ids.folder,name:'References',parentId:null,createdAt:date}],breadcrumbs:url.searchParams.has('parentId')?[{id:ids.folder,name:'References'}]:[],page:{limit:50,hasMore:false,nextAfter:null},transfers:{available:false,code:'STORAGE_GATEWAY_UNAVAILABLE',message:'Not deployed in this fixture.'}};
 else if(path.endsWith('/higgsfield/archives')){
  if(method==='GET')data={archives:state.archives,hasMore:false,nextAfter:null,processing:{enabled:state.enabled,message:state.enabled?'Archive processing is enabled.':'Archive processing is not enabled for this deployment.'}};
  else{const body=route.request().postDataJSON();state.archive={...state.archive,destination:{...state.archive.destination,name:body.name,parentId:body.parentId,ancestors:body.parentId?[{id:ids.folder,name:'References'}]:[]},maxBytes:body.maxBytes};state.archives=[state.archive];data={archive:state.archive,replayed:false};}
 }else if(path.endsWith('/archives/'+ids.archive))data={archive:state.archive};
 else if(path.endsWith('/'+ids.archive+'/approve')){state.archive={...state.archive,status:'queued',approvedBy:ids.user,approvedAt:date,expiresAt:'2026-09-20T02:00:00Z',revision:2};state.archives=[state.archive];data={archive:state.archive,replayed:false};}
 else if(path.endsWith('/'+ids.archive+'/revoke')){state.archive={...state.archive,status:'cancelled',revokedAt:date,revision:2};state.archives=[state.archive];data={archive:state.archive};}
 await route.fulfill({status:data?200:501,json:data||{error:'Unexpected fixture '+path}});
});}
async function open(page:Page){await page.goto('/#studio');await page.getByRole('button').filter({has:page.getByRole('heading',{name:'Archive campaign',exact:true})}).click();await page.getByRole('tab',{name:'Generations & references',exact:true}).click();await page.getByRole('button',{name:'Save image output 1 to project files',exact:true}).click();return page.getByRole('region',{name:'Project file archives',exact:true});}
test.beforeEach(({baseURL})=>{test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Use local fixture origin.');});

test('member prepares an exact folder destination, never approves or receives source URLs',async({page},testInfo)=>{
 const state=fixture(false);await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'References',exact:true}).click();await expect(panel.getByRole('navigation',{name:'Archive destination'})).toContainText('References');await panel.getByLabel('File name',{exact:true}).fill('storyboard-reference');await panel.getByRole('button',{name:'Prepare archive destination',exact:true}).click();
 await expect(panel.getByRole('region',{name:'Review archive approval'})).toContainText('An administrator can approve');await expect(panel.getByRole('button',{name:'Approve archive transfer',exact:true})).toHaveCount(0);await expect(panel.getByRole('button',{name:'Revoke archive approval',exact:true})).toHaveCount(0);
 expect(state.writes.filter(item=>item.path.includes('archives'))).toHaveLength(1);expect(state.writes[0].body).toMatchObject({projectRevision:7,bindingRevision:4,outputIdentity:'a'.repeat(64),parentId:ids.folder,name:'storyboard-reference',maxBytes:256*1024**2});expect(await panel.innerText()).not.toContain('private.invalid');await expect(panel.getByRole('link')).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});await panel.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);await page.screenshot({path:testInfo.outputPath('archive-member-mobile.png'),fullPage:true});
});

test('administrator explicitly approves exact source, destination hash and bounded expiry',async({page},testInfo)=>{
 const state=fixture();await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Prepare archive destination',exact:true}).click();const review=panel.getByRole('region',{name:'Review archive approval'}),approve=review.getByRole('button',{name:'Approve archive transfer'});await expect(approve).toBeDisabled();await review.getByLabel('Approval expires after').selectOption('6');await review.getByRole('checkbox').check();await expect(approve).toBeEnabled();await page.screenshot({path:testInfo.outputPath('archive-approval-desktop.png'),fullPage:true});await approve.click();await expect(panel).toContainText('Approved · waiting for worker');
 const writes=state.writes.filter(item=>item.path.includes('archives'));expect(writes).toHaveLength(2);expect(writes[1].body).toMatchObject({revision:1,requestHash:'b'.repeat(64),projectRevision:7,bindingRevision:4,expiresInHours:6,archiveConsent:true});expect(writes.some(item=>item.path.includes('/execute'))).toBe(false);
});

test('disabled processing remains explicit and stale approval clears consent without retry',async({page})=>{
 const state=fixture(true,false);state.archives=[state.archive];await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Review archive',exact:true}).click();await expect(panel).toContainText('Archive processing is not enabled');await expect(panel.getByRole('button',{name:'Approve archive transfer'})).toBeDisabled();await expect(panel.getByRole('checkbox')).toBeDisabled();expect(state.writes).toHaveLength(0);
 state.enabled=true;await panel.getByRole('button',{name:'Refresh archives'}).click();await panel.getByRole('button',{name:'Review archive',exact:true}).click();state.handler=async(route,url)=>{if(!url.pathname.endsWith('/approve'))return false;await route.fulfill({status:409,json:{error:'The reviewed destination changed.',code:'HIGGSFIELD_ARCHIVE_DESTINATION_CHANGED'}});return true;};await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'Approve archive transfer'}).click();await expect(panel.getByRole('alert')).toContainText('destination changed');await expect(panel.getByRole('checkbox')).not.toBeChecked();expect(state.writes).toHaveLength(1);
});

test('partial bytes never become verified and history pagination deduplicates',async({page})=>{
 const state=fixture(false);state.archive={...state.archive,status:'verifying',fetched:{bytes:1048576,sha256:'c'.repeat(64)}};state.archives=[state.archive];state.handler=async(route,url)=>{if(!url.pathname.endsWith('/higgsfield/archives')||route.request().method()!=='GET')return false;await route.fulfill({json:{archives:[state.archive],hasMore:!url.searchParams.has('after'),nextAfter:url.searchParams.has('after')?null:ids.archive,processing:{enabled:true,message:'Archive processing is enabled.'}}});return true;};await mock(page,state);const panel=await open(page);await expect(panel).toContainText('The stored version is not yet verified');await panel.getByRole('button',{name:'Load more archives'}).click();await expect(panel.getByRole('article')).toHaveCount(1);expect(await panel.innerText()).not.toContain('Stored bytes verified.');expect(state.writes).toHaveLength(0);
});

test('reviewing another archive preserves the chosen folder and existing file version',async({page})=>{
 const state=fixture();state.archives=[state.archive];state.handler=async(route,url)=>{if(!url.pathname.endsWith('/files')||!url.searchParams.has('parentId'))return false;await route.fulfill({json:{binding:state.binding,items:[{kind:'file',id:ids.output,name:'existing-reference',parentId:ids.folder,createdAt:date,latestVersion:null}],breadcrumbs:[{id:ids.folder,name:'References'}],page:{limit:50,hasMore:false,nextAfter:null},transfers:{available:false,code:'STORAGE_GATEWAY_UNAVAILABLE',message:'Not deployed.'}}});return true;};await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'References',exact:true}).click();await panel.getByLabel('Save as',{exact:true}).selectOption(ids.output);await panel.getByRole('button',{name:'Review archive',exact:true}).click();
 await expect(panel.getByLabel('Save as',{exact:true})).toHaveValue(ids.output);await expect(panel.getByLabel('File name',{exact:true})).toHaveValue('existing-reference');await expect(panel.getByRole('navigation',{name:'Archive destination'})).toContainText('References');await panel.getByRole('button',{name:'Prepare archive destination',exact:true}).click();expect(state.writes[0].body).toMatchObject({fileId:ids.output,parentId:ids.folder,name:'existing-reference'});
});

for(const kind of['image','video','audio'] as const)test(`v2 ${kind} generation negotiates typed requirements and keeps the exact work association`,async({page},testInfo)=>{
 const state=fixture(true,true,kind);await mock(page,state);await page.goto('/#studio');await page.getByRole('button').filter({has:page.getByRole('heading',{name:'Archive campaign',exact:true})}).click();await page.getByRole('tab',{name:'Generations & references',exact:true}).click();const panel=page.getByRole('region',{name:'Higgsfield production plugin',exact:true}),requirements=panel.getByRole('region',{name:'Generated media requirements',exact:true});
 await expect(requirements).toContainText('Required '+kind+' output');await expect(panel.getByLabel('Official generation tool',{exact:true})).toHaveValue('generate_'+kind);await expect(panel.getByRole('button',{name:'Prepare request',exact:true})).toBeDisabled();await panel.getByLabel('Generation task',{exact:true}).selectOption(ids.folder);
 await expect(requirements).toContainText('D010 · Approved hero media');if(kind==='image'){await expect(requirements).toContainText('1024 × 1024 pixels');await expect(requirements).not.toContainText('Duration:');await expect(requirements).not.toContainText('fps');}else{await expect(requirements).toContainText('1,999–2,001 ms');if(kind==='audio'){await expect(requirements).toContainText('48,000 Hz');await expect(requirements).not.toContainText('pixels');await expect(requirements).not.toContainText('fps');}else await expect(requirements).toContainText('24 / 1 fps (constant)');}
 const exact={params:{model:'fixture-'+kind,prompt:'Approved hero media only'}};await panel.getByLabel('Production purpose',{exact:true}).fill('Hero '+kind);await panel.getByLabel('Exact tool arguments',{exact:true}).fill(JSON.stringify(exact));await panel.getByRole('button',{name:'Prepare request',exact:true}).click();await expect(panel.getByRole('button',{name:'Send once to Higgsfield',exact:true})).toBeDisabled();
 const proposal=state.writes.find(write=>write.path.endsWith('/higgsfield/requests'));expect(proposal?.body).toMatchObject({projectId:ids.project,projectRevision:7,workItemId:ids.folder,tool:'generate_'+kind,arguments:exact,note:'Hero '+kind});expect(proposal?.body.clientId).toMatch(/^[a-f0-9-]{36}$/);expect(JSON.stringify(proposal?.body)).not.toMatch(/frameStart|frameEnd|handles/);expect(state.writes.some(write=>write.path.endsWith('/execute'))).toBe(false);expect(state.projectReads.length).toBeGreaterThanOrEqual(3);expect(state.projectReads.every(query=>new URLSearchParams(query).get('contractVersion')==='2')).toBe(true);
 if(kind==='audio'){await page.setViewportSize({width:390,height:844});await requirements.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);await page.screenshot({path:testInfo.outputPath('generated-audio-requirements-mobile.png')});}
});

test('v2 archive refresh and review negotiate version 2 without changing transfer approval',async({page})=>{
 const state=fixture(true,true,'image');state.archives=[state.archive];await mock(page,state);const panel=await open(page);await expect(panel).toContainText('This project requires image in PNG format');await panel.getByRole('button',{name:'Review archive',exact:true}).click();await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'Approve archive transfer',exact:true}).click();await expect(panel).toContainText('Approved · waiting for worker');expect(state.projectReads.length).toBeGreaterThanOrEqual(4);expect(state.projectReads.every(query=>new URLSearchParams(query).get('contractVersion')==='2')).toBe(true);expect(state.writes).toHaveLength(1);expect(state.writes[0].body).toMatchObject({revision:1,requestHash:'b'.repeat(64),projectRevision:7,bindingRevision:4,expiresInHours:2,archiveConsent:true});
});

test('failed v2 project refresh removes credit consent and blocks stale generation proposals',async({page})=>{
 const state=fixture(true,true,'image');state.requests=[{id:ids.job,projectId:ids.project,workItemId:ids.folder,taskRevision:3,tool:'generate_image',arguments:{params:{model:'fixture-image',prompt:'Synthetic'}},note:'Reviewed hero',requestHash:'c'.repeat(64),status:'proposed',createdAt:date}];await mock(page,state);await page.goto('/#studio');await page.getByRole('button').filter({has:page.getByRole('heading',{name:'Archive campaign',exact:true})}).click();await page.getByRole('tab',{name:'Generations & references',exact:true}).click();const panel=page.getByRole('region',{name:'Higgsfield production plugin',exact:true});await panel.getByRole('checkbox').check();await expect(panel.getByRole('button',{name:'Send once to Higgsfield',exact:true})).toBeEnabled();
 state.handler=async(route,url)=>{if(!url.pathname.endsWith('/studio/projects/'+ids.project))return false;await route.fulfill({json:{project:{...state.project,id:ids.output},roles:state.roles,skills:STUDIO_SKILLS,workItems:state.workItems,shots:state.shots,artifacts:[],reviews:[],deliveries:[]}});return true;};await panel.getByRole('button',{name:'Refresh',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('changed scope');await expect(panel.getByRole('checkbox')).not.toBeChecked();await expect(panel.getByRole('checkbox')).toBeDisabled();await expect(panel.getByRole('button',{name:'Prepare request',exact:true})).toBeDisabled();await expect(panel.getByRole('button',{name:'Send once to Higgsfield',exact:true})).toBeDisabled();expect(state.writes).toHaveLength(0);
});
