import {test,expect,type Page,type Route} from '@playwright/test';
import {STUDIO_TEMPLATES,STUDIO_SKILLS,type StudioProjectDetail} from '../../src/lib/studio-protocol';
import type {HiggsfieldRequest} from '../../src/lib/higgsfield-protocol';
import type {Company,User,Workspace} from '../../src/lib/client';

const user:User={id:'tracking-member',name:'Production artist',email:'tracking@example.invalid',roleTitle:'Artist',avatarColor:'#607850',avatarId:null};
const company:Company={id:'tracking-company',name:'Generation tracking studio',slug:'generation-tracking-studio',template:'blank',role:'member'};
const request=(id:string,status:HiggsfieldRequest['status']='returned'):HiggsfieldRequest=>({id,projectId:'tracking-project',tool:'generate_image',arguments:{params:{model:'fixture-model',prompt:'A synthetic browser test.'}},note:id==='request-one'?'Storyboard direction':'Lighting study',requestHash:'a'.repeat(64),status,createdAt:'2026-09-20T00:00:00Z'});
const job=(id:string,status='running')=>({id,projectId:'tracking-project',requestId:'request-one',providerJobId:'provider-'+id,kind:'image',model:'fixture-model',status,diagnosticCode:null as string|null,pollAttempts:2,nextPollAt:null,createdAt:'2026-09-20T00:00:00Z',updatedAt:'2026-09-20T00:01:00Z',outputs:[] as {id:string;ordinal:number;kind:string;locatorIdentity:string;bytesVerified:false;url?:string}[]});
function fixture(){
 const workspace:Workspace={company:{...company},rooms:[],members:[{...user,id:user.id,userId:user.id,role:'member'}],agents:[],tasks:[],messages:[],presence:[],activity:[],drives:[],openings:[],applications:[],layout:[]};
 const template=STUDIO_TEMPLATES.find(item=>item.id==='ai-production')!,roles=template.roles.map(role=>({...role,humanId:null,agentId:null}));
 const project:StudioProjectDetail['project']={id:'tracking-project',name:'Tracking campaign',clientName:'Synthetic client',brief:'Prepare a reference campaign.',productionPath:'higgsfield',dueDate:null,spec:{width:1920,height:1080,fpsNumerator:24,fpsDenominator:1,format:'mp4',colorSpace:'Rec.709'},aiPolicy:'allowed',revision:1,status:'planning',gates:{},createdAt:'2026-09-20T00:00:00Z',updatedAt:'2026-09-20T00:00:00Z'};
 return {workspace,roles,project,requests:[request('request-one'),request('request-two','proposed')],jobs:[job('job-one')],handler:undefined as ((route:Route,url:URL)=>Promise<boolean>)|undefined,writes:[] as string[],trackingReads:[] as string[]};
}
async function mock(page:Page,state:ReturnType<typeof fixture>){await page.route('**/api/**',async route=>{
 const url=new URL(route.request().url()),path=url.pathname;if(route.request().method()!=='GET')state.writes.push(path);if(path.endsWith('/higgsfield/jobs'))state.trackingReads.push(url.search);
 if(await state.handler?.(route,url))return;
 const data=path==='/api/session'?{user,companies:[state.workspace.company],configured:true}:path.endsWith('/workspace')?state.workspace:path.endsWith('/presence')?{presence:[]}:path.endsWith('/studio')?{templates:STUDIO_TEMPLATES,skills:STUDIO_SKILLS,profile:{templateId:'ai-production',revision:1,roles:state.roles},projects:[state.project],hasMore:false,nextAfter:null}:path.endsWith('/tracking-project')?{project:state.project,roles:state.roles,skills:STUDIO_SKILLS,workItems:[],shots:[],artifacts:[],reviews:[],deliveries:[]}:path.endsWith('/higgsfield')?{status:'connected',revision:1,officialEndpoint:'https://higgsfield.ai/mcp',toolCount:1,tools:[{name:'generate_image',description:'Fixture tool',inputSchema:{}}]}:path.endsWith('/higgsfield/requests')?{requests:state.requests,nextAfter:null}:path.endsWith('/higgsfield/jobs')?{jobs:state.jobs,hasMore:false,nextAfter:null}:null;
 await route.fulfill({status:data?200:501,json:data||{error:'Unexpected fixture '+path}});
});}
async function openTracking(page:Page){await page.goto('/#studio');await page.getByRole('button').filter({has:page.getByRole('heading',{name:'Tracking campaign',exact:true})}).click();await page.getByRole('tab',{name:'Generations & references',exact:true}).click();return page.getByRole('region',{name:'Generation tracking',exact:true});}
test.beforeEach(({baseURL})=>{test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Fixtures use a local origin.');});

test('members can inspect provider completion without archive, QC or download claims',async({page},testInfo)=>{
 const state=fixture();state.jobs=[job('job-one','completed')];state.jobs[0].outputs=[{id:'output-one',ordinal:0,kind:'image',locatorIdentity:'b'.repeat(64),bytesVerified:false,url:'https://private.example.invalid/output?secret=fixture-only'}];await mock(page,state);const tracking=await openTracking(page);
 await expect(tracking.getByText('Provider completed',{exact:true})).toBeVisible();await expect(tracking).toContainText('This tracking record does not verify or archive bytes');await expect(tracking).toContainText('check archive history for verified files');await expect(tracking.getByRole('link')).toHaveCount(0);await expect(page.getByRole('button',{name:'Prepare request',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Send once to Higgsfield',exact:true})).toHaveCount(0);
 await tracking.getByText('Tracking identifiers and evidence',{exact:true}).click();await expect(tracking).toContainText('not a verified file or content checksum');expect(await tracking.innerText()).not.toContain('private.example.invalid');expect(state.writes.filter(path=>path.includes('/higgsfield'))).toEqual([]);
 await page.setViewportSize({width:390,height:844});await tracking.getByText('Provider completed',{exact:true}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);await page.screenshot({path:testInfo.outputPath('generation-tracking-mobile.png')});
});

test('tracking reads once per scope, refreshes explicitly and paginates without duplicates',async({page})=>{
 const state=fixture();state.handler=async(route,url)=>{if(!url.pathname.endsWith('/higgsfield/jobs'))return false;const filter=url.searchParams.get('requestId');await route.fulfill({json:filter?{jobs:[{...job('filtered-job','completed'),requestId:filter}],hasMore:false,nextAfter:null}:url.searchParams.has('after')?{jobs:[job('job-one'),job('job-two')],hasMore:false,nextAfter:null}:{jobs:[job('job-one')],hasMore:true,nextAfter:'page-two'}});return true;};await mock(page,state);const tracking=await openTracking(page);await expect(tracking.getByRole('article')).toHaveCount(1);expect(state.trackingReads).toHaveLength(1);expect(new URLSearchParams(state.trackingReads[0]).get('limit')).toBe('20');
 await tracking.getByRole('button',{name:'Load more tracked jobs',exact:true}).click();await expect(tracking.getByRole('article')).toHaveCount(2);expect(new URLSearchParams(state.trackingReads[1]).get('after')).toBe('page-two');await tracking.getByRole('button',{name:'Refresh tracking',exact:true}).click();await expect(tracking.getByRole('article')).toHaveCount(1);expect(state.trackingReads).toHaveLength(3);expect(new URLSearchParams(state.trackingReads[2]).has('after')).toBe(false);
 await tracking.getByLabel('Track generation request',{exact:true}).selectOption('request-two');await expect(tracking.getByText('Provider completed',{exact:true})).toBeVisible();expect(state.trackingReads).toHaveLength(4);expect(new URLSearchParams(state.trackingReads[3]).get('requestId')).toBe('request-two');await page.clock.install();await page.clock.fastForward(60_000);expect(state.trackingReads).toHaveLength(4);expect(state.writes.filter(path=>path.includes('/higgsfield'))).toEqual([]);
});

test('uncertain requests retain their warning while unresolved tracking never retries generation',async({page})=>{
 const state=fixture();state.requests=[request('request-one','uncertain')];state.jobs=[{...job('job-one','unresolved'),diagnosticCode:'HIGGSFIELD_UNSUPPORTED_SHAPE'}];await mock(page,state);const tracking=await openTracking(page);await expect(tracking.getByText('Status unresolved',{exact:true})).toBeVisible();await expect(page.getByText('The provider may have started this work.',{exact:false})).toBeVisible();await expect(page.getByText('Coatria will not send this request again.',{exact:false})).toBeVisible();await expect(tracking).toContainText('does not authorize another generation');await tracking.getByRole('button',{name:'Refresh tracking',exact:true}).click();await expect(tracking.getByRole('button',{name:'Refresh tracking',exact:true})).toBeEnabled();expect(state.writes.filter(path=>path.includes('/higgsfield'))).toEqual([]);
});

test('failed refresh keeps prior evidence and scope changes discard a late response',async({page})=>{
 const state=fixture();let fail=false,late:Route|undefined;state.handler=async(route,url)=>{if(!url.pathname.endsWith('/higgsfield/jobs'))return false;if(url.searchParams.get('requestId')==='request-one'){late=route;return true;}if(url.searchParams.get('requestId')==='request-two'){await route.fulfill({json:{jobs:[{...job('current-job','completed'),requestId:'request-two'}],hasMore:false,nextAfter:null}});return true;}if(fail){await route.fulfill({status:503,json:{error:'Tracking temporarily unavailable.'}});return true;}return false;};await mock(page,state);const tracking=await openTracking(page);await expect(tracking.getByText('Provider running',{exact:true})).toBeVisible();fail=true;await tracking.getByRole('button',{name:'Refresh tracking',exact:true}).click();await expect(tracking.getByRole('alert')).toContainText('Previously loaded jobs remain below');await expect(tracking.getByText('Provider running',{exact:true})).toBeVisible();
 await tracking.getByLabel('Track generation request',{exact:true}).selectOption('request-one');await expect.poll(()=>Boolean(late)).toBe(true);await tracking.getByLabel('Track generation request',{exact:true}).selectOption('request-two');await expect(tracking.getByText('Provider completed',{exact:true})).toBeVisible();await late!.fulfill({json:{jobs:[job('stale-job','failed')],hasMore:false,nextAfter:null}}).catch(()=>{});await expect(tracking.getByText('Provider failed',{exact:true})).toHaveCount(0);await expect(tracking.getByRole('article')).toHaveCount(1);expect(state.writes.filter(path=>path.includes('/higgsfield'))).toEqual([]);
});
