import {test,expect,type Page,type Route} from '@playwright/test';
import {PLUGIN_CATALOG,PLUGIN_CATALOG_VERSION} from '../../src/lib/plugin-catalog';
import type {Company,User,Workspace} from '../../src/lib/client';

const user:User={id:'plugin-user',name:'Company owner',email:'owner@example.invalid',roleTitle:'Owner',avatarColor:'#607850',avatarId:null};
const company:Company={id:'plugin-company',name:'Studio North',slug:'studio-north',template:'blank',role:'owner'};
const installation=(overrides:Record<string,unknown>={})=>({id:'installed-one',pluginId:'openai',manifestVersion:'1.0.0',agentId:'agent-one',name:'Astra coordinator',revision:1,runtimeConfig:{providerId:'openai',modelId:'gpt-6-astra',maxSteps:8,maxOutputTokens:2048,maxTotalTokens:24000,timeoutSeconds:180},character:{roleTitle:'Project coordinator',persona:'Prepare documented contributions.',workStyle:'collaborative'},status:'active',invocationAccess:'admins',capabilities:['workspace.read'],lastSeenAt:null,expiresAt:'2027-01-01T00:00:00Z',createdAt:'2026-09-16T00:00:00Z',...overrides});
type Installed=ReturnType<typeof installation>;
function fixture(){const workspace:Workspace={company,rooms:[],members:[{...user,userId:user.id,role:'owner'}],agents:[],tasks:[],messages:[],presence:[],activity:[],drives:[],openings:[],applications:[],layout:[]};return {user,companies:[company],workspace,installations:[] as Installed[],handler:undefined as ((route:Route,path:string)=>Promise<boolean>)|undefined};}
async function mock(page:Page,state:ReturnType<typeof fixture>){await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;if(await state.handler?.(route,path))return;const data=path==='/api/session'?{user:state.user,companies:state.companies,configured:true}:path==='/api/plugins/catalog'?{plugins:PLUGIN_CATALOG,version:PLUGIN_CATALOG_VERSION}:path.endsWith('/plugin-installations')?{installations:state.installations,hasMore:false,nextAfter:null}:path.endsWith('/installed-one')?{installation:state.installations.find(item=>item.id==='installed-one')}:path.endsWith('/workspace')?state.workspace:path.endsWith('/presence')?{presence:[{userId:state.user.id,name:state.user.name,avatarColor:state.user.avatarColor,avatarId:null,roomId:null,x:0,z:3,status:'available',updatedAt:new Date().toISOString()}]}:null;await route.fulfill({status:data?200:501,json:data||{error:'Unexpected fixture '+path}});});}
const card=(page:Page,title:string)=>page.getByRole('button').filter({has:page.getByRole('heading',{name:title,exact:true})});
test.beforeEach(({baseURL})=>{test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Fixtures use a local origin.');});

test('catalog filters and installation disclose permissions and protect the one-time token',async({page})=>{
 const state=fixture();let sent:Record<string,unknown>|undefined;const token='ca_'+'marketplace-local-fixture';state.handler=async(route,path)=>{if(path.endsWith('/plugin-installations')&&route.request().method()==='POST'){sent=route.request().postDataJSON();const item=installation({...sent,pluginId:'openai'});state.installations=[item];await route.fulfill({status:201,json:{installation:item,token,replayed:false}});return true;}return false;};await mock(page,state);await page.goto('/#plugins');
 await expect(page.getByRole('heading',{name:'Make room for your agents.'})).toBeVisible();await page.getByLabel('Provider',{exact:true}).selectOption('Anthropic');await expect(card(page,'Claude Code')).toBeVisible();await expect(card(page,'Codex')).toHaveCount(0);await page.getByLabel('Provider',{exact:true}).selectOption('all');await page.getByLabel('Search plugins').fill('astra');await card(page,'Astra & OpenAI').click();const dialog=page.getByRole('dialog');await expect(dialog.getByText('Know where company data goes.')).toBeVisible();await expect(dialog.getByLabel('Who can ask this agent')).toHaveValue('admins');await expect(dialog.getByRole('checkbox',{checked:true})).toHaveCount(0);await dialog.getByLabel('Agent name',{exact:true}).fill('Astra coordinator');await dialog.getByLabel('Start from a role').selectOption('coordinator');await dialog.getByRole('checkbox',{name:/Read company workspace/}).check();await expect(dialog.getByRole('button',{name:'Install bridge',exact:true})).toBeDisabled();await dialog.getByRole('checkbox',{name:/I reviewed the selected permissions/}).check();await dialog.getByRole('button',{name:'Install bridge',exact:true}).click();await expect(dialog.getByRole('textbox',{name:'Connection token'})).toHaveValue(token);expect(sent).toMatchObject({pluginId:'openai',manifestVersion:'1.0.0',capabilities:['workspace.read'],invocationAccess:'admins',character:{roleTitle:'Project coordinator'}});expect(sent?.clientId).toMatch(/^[a-f0-9-]{36}$/);await expect(dialog.getByRole('link',{name:'provider-adapter.mjs',exact:true})).toHaveAttribute('href','/downloads/provider-adapter.mjs');await expect(dialog).toContainText('--adapter ./provider-adapter.mjs');await dialog.getByRole('button',{name:'Close dialog'}).click();await expect(dialog.getByRole('alert')).toContainText('This token cannot be shown again');await dialog.getByRole('checkbox',{name:'I saved this token in a private location.'}).check();await dialog.getByRole('button',{name:'Done',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(value=>Object.values(localStorage).some(entry=>entry.includes(value))||Object.values(sessionStorage).some(entry=>entry.includes(value))||location.href.includes(value),token)).toBe(false);
});

test('members browse installations without editable grants or provider-key fields',async({page})=>{
 const state=fixture();state.companies=[{...company,role:'member'}];state.workspace.company=state.companies[0];state.installations=[installation()];await mock(page,state);await page.goto('/#plugins');await page.getByRole('button',{name:/^Installed /}).click();await card(page,'Astra coordinator').click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Agent name',{exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'Save bridge settings'})).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Rotate connection token'})).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Run connection test'})).toHaveCount(0);await expect(dialog.getByRole('textbox',{name:/API key/i})).toHaveCount(0);await expect(dialog).toContainText('API contact confirms a worker reached Coatria; it does not verify a model response.');
});

test('failed saves keep a visible draft without claiming success and concurrent revisions require reload',async({page})=>{
 const state=fixture();state.installations=[installation()];let body:Record<string,unknown>|undefined;state.handler=async(route,path)=>{if(path.endsWith('/installed-one')&&route.request().method()==='PATCH'){body=route.request().postDataJSON();await route.fulfill({status:409,json:{error:'This installation changed. Reload its current revision.'}});return true;}return false;};await mock(page,state);await page.goto('/#plugins');await page.getByRole('button',{name:/^Installed /}).click();await card(page,'Astra coordinator').click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Company role').fill('Careful researcher');await dialog.getByRole('checkbox',{name:/I reviewed the updated role/}).check();await dialog.getByRole('button',{name:'Save bridge settings'}).click();await expect(dialog.getByRole('alert')).toContainText('This installation changed');await expect(dialog.getByLabel('Company role')).toHaveValue('Careful researcher');expect(body).toMatchObject({revision:1,character:{roleTitle:'Careful researcher'}});state.installations=[installation({revision:2})];await dialog.getByRole('button',{name:'Refresh connection'}).click();await expect(dialog.getByText('These settings changed since you opened them.')).toBeVisible();await expect(dialog.getByRole('button',{name:'Save bridge settings'})).toBeDisabled();await dialog.getByRole('button',{name:'Reload latest settings'}).click();await expect(dialog.getByLabel('Company role')).toHaveValue('Project coordinator');
});

test('connection tests show waiting and actual result distinctly',async({page})=>{
 const state=fixture();state.installations=[installation({lastSeenAt:new Date().toISOString()})];let done=false;state.handler=async(route,path)=>{if(path.endsWith('/connection-test')){await route.fulfill({status:201,json:{run:{id:'run-test',status:'queued'},replayed:false}});done=true;return true;}if(path.endsWith('/agent-runs/run-test')){await route.fulfill({json:{run:{id:'run-test',status:done?'succeeded':'queued',result:'Coatria model bridge ready.'}}});return true;}return false;};await mock(page,state);await page.goto('/#plugins');await page.getByRole('button',{name:/^Installed /}).click();await card(page,'Astra coordinator').click();const dialog=page.getByRole('dialog');await expect(dialog).toContainText('may incur charges');await dialog.getByRole('button',{name:'Run connection test'}).click();await expect(dialog).toContainText('Queued — waiting for your worker');await expect(dialog.getByRole('button',{name:'Connection test in progress'})).toBeDisabled();await expect(dialog).toContainText('Model response received');await expect(dialog).toContainText('Coatria model bridge ready.');
});

test('CLI bridges hide unenforced API budgets and custom inference requires a model ID',async({page})=>{
 await mock(page,fixture());await page.goto('/#plugins');await card(page,'Codex').click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Maximum model steps')).toHaveCount(0);await expect(dialog.getByLabel('Total token allowance')).toHaveCount(0);await expect(dialog.getByLabel('Timeout in seconds')).toBeVisible();await expect(dialog).toContainText('Token and step budgets are not enforced here');await dialog.getByRole('button',{name:'Close dialog'}).click();await card(page,'Your Runpod inference').click();await expect(dialog.getByLabel('Custom model ID')).toHaveValue('');await dialog.getByRole('checkbox',{name:/I reviewed the selected permissions/}).check();await expect(dialog.getByRole('button',{name:'Install bridge'})).toBeDisabled();await dialog.getByLabel('Custom model ID').fill('Qwen/operator-approved');await expect(dialog.getByRole('button',{name:'Install bridge'})).toBeDisabled();await dialog.getByRole('checkbox',{name:/I reviewed the selected permissions/}).check();await expect(dialog.getByRole('button',{name:'Install bridge'})).toBeEnabled();
});

test('losing administrator access discards an in-flight installation token',async({page})=>{
 const state=fixture();let release=()=>{},requested=false;const gate=new Promise<void>(resolve=>{release=resolve;});const token='ca_'+'late-plugin-fixture';state.handler=async(route,path)=>{if(path.endsWith('/plugin-installations')&&route.request().method()==='POST'){requested=true;await gate;await route.fulfill({status:201,json:{installation:installation(),token}});return true;}return false;};await mock(page,state);await page.goto('/#plugins');await card(page,'Astra & OpenAI').click();await page.getByRole('checkbox',{name:/I reviewed the selected permissions/}).check();await page.getByRole('button',{name:'Install bridge'}).click();await expect.poll(()=>requested).toBe(true);state.companies=[{...company,role:'member'}];state.workspace.company=state.companies[0];await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(page.getByRole('dialog')).toHaveCount(0);release();await expect(page.getByRole('textbox',{name:'Connection token'})).toHaveCount(0);await expect(page.locator('body')).not.toContainText(token);
});

test('token rotation requires an explicit choice and protects the replacement',async({page})=>{
 const state=fixture();state.installations=[installation()];let rotated=false;state.handler=async(route,path)=>{if(path.endsWith('/rotate')){expect(route.request().postDataJSON()).toEqual({revision:1});rotated=true;state.installations=[installation({revision:2})];await route.fulfill({json:{installation:state.installations[0],token:'ca_'+'replacement-fixture'}});return true;}return false;};await mock(page,state);await page.goto('/#plugins');await page.getByRole('button',{name:/^Installed /}).click();await card(page,'Astra coordinator').click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Rotate connection token'}).click();expect(rotated).toBe(false);await expect(dialog.getByRole('alert')).toContainText('The current token will stop working');await dialog.getByRole('button',{name:'Replace token',exact:true}).click();await expect(dialog.getByRole('textbox',{name:'Connection token'})).toHaveValue('ca_'+'replacement-fixture');await dialog.getByRole('button',{name:'Close dialog'}).click();await expect(dialog.getByRole('alert')).toContainText('This token cannot be shown again');
});

test('mobile marketplace and character setup fit the viewport',async({page})=>{
 await page.setViewportSize({width:390,height:844});await mock(page,fixture());await page.goto('/#plugins');await expect(card(page,'Codex')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'C:/CODEX/Agent002/output/plugins-mobile.png',fullPage:true});await card(page,'Astra & OpenAI').click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Start from a role').selectOption('reviewer');await expect(dialog.getByLabel('Company role')).toHaveValue('Technical reviewer');expect(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth)).toBe(true);await page.screenshot({path:'C:/CODEX/Agent002/output/plugins-mobile-detail.png'});
});

test('managed agent identities lead to Plugins instead of legacy permission controls',async({page})=>{
 const state=fixture();state.workspace.agents=[{id:'managed-agent',name:'Managed colleague',harness:'custom',description:'Company bridge',status:'active',createdBy:user.id,lastSeenAt:null,pluginInstallationId:'installed-one'}];await mock(page,state);await page.goto('/#agents');await card(page,'Managed colleague').click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('link',{name:'Manage in Plugins'})).toHaveAttribute('href','#plugins');await expect(dialog.getByLabel('Conversation access')).toHaveCount(0);await dialog.getByRole('link',{name:'Manage in Plugins'}).click();await expect(page.getByRole('heading',{name:'Make room for your agents.'})).toBeVisible();
});

test('pause and revoke preserve a clear request boundary and permanent confirmation',async({page})=>{
 const state=fixture();state.installations=[installation()];const writes:unknown[]=[];state.handler=async(route,path)=>{if(path.endsWith('/installed-one')&&route.request().method()==='PATCH'){const payload=route.request().postDataJSON();writes.push(payload);state.installations=[installation({status:payload.status,revision:Number(payload.revision)+1})];await route.fulfill({json:{installation:state.installations[0]}});return true;}return false;};await mock(page,state);await page.goto('/#plugins');await page.getByRole('button',{name:/^Installed /}).click();await card(page,'Astra coordinator').click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Pause bridge'}).click();await expect(dialog.getByRole('button',{name:'Resume bridge'})).toBeVisible();await expect(dialog.getByRole('button',{name:'Run connection test'})).toBeDisabled();await dialog.getByRole('button',{name:'Revoke bridge',exact:true}).click();expect(writes).toEqual([{revision:1,status:'paused'}]);await expect(dialog.getByRole('alert')).toContainText('token will stop working');await dialog.getByRole('button',{name:'Permanently revoke'}).click();await expect(dialog).toContainText('This installation is permanently revoked.');expect(writes).toEqual([{revision:1,status:'paused'},{revision:2,status:'revoked'}]);await expect(dialog.getByRole('button',{name:'Save bridge settings'})).toHaveCount(0);
});

test('installed pagination can open and refresh a bridge beyond the first page',async({page})=>{
 const state=fixture();state.installations=[installation()];state.handler=async(route,path)=>{if(path.endsWith('/plugin-installations')){const after=new URL(route.request().url()).searchParams.get('after');await route.fulfill({json:after?{installations:[installation({id:'installed-two',name:'Second colleague'})],hasMore:false,nextAfter:null}:{installations:state.installations,hasMore:true,nextAfter:'installed-one'}});return true;}if(path.endsWith('/installed-two')){await route.fulfill({json:{installation:installation({id:'installed-two',name:'Second colleague',revision:2})}});return true;}return false;};await mock(page,state);await page.goto('/#plugins');await page.getByRole('button',{name:/^Installed /}).click();await page.getByRole('button',{name:'Load more installed bridges'}).click();await card(page,'Second colleague').click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Refresh connection'}).click();await expect(dialog.getByText('These settings changed since you opened them.')).toBeVisible();await expect(dialog.getByLabel('Agent name',{exact:true})).toHaveValue('Second colleague');
});

test('desktop directory presents the complete provider selection without overflow',async({page})=>{
 await mock(page,fixture());await page.goto('/#plugins');await expect(card(page,'Qwen on Fireworks')).toBeVisible();await expect(card(page,'Qwen on Together')).toBeVisible();await expect(card(page,'Grok')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'C:/CODEX/Agent002/output/plugins-desktop.png',fullPage:true});
});
