import {test,expect,type Page,type Route} from '@playwright/test';
import {generatedFixture,mockGenerated,openGenerated,ids,uuid,noOverflow} from './studio-generated-fixture';
import {projectStorageConnectionRevokeInput,type ProjectStorageConnection} from '../../src/lib/project-storage-protocol';

function connection(n:number,name:string,revision:number):ProjectStorageConnection{return {id:uuid(n),name,provider:'runpod',region:'US-NC-2',volumeId:'synthetic-volume-'+n,status:'configured',revision,createdAt:'2026-09-20T00:00:00Z',credentialsConfigured:true,providerVerified:false};}
async function setup(page:Page,options:{role?:string;handler?:(route:Route,path:string)=>Promise<boolean>}={}){
 const state=generatedFixture();state.company.role=options.role??'owner';const rows=[connection(70,'Shared media library',3),connection(71,'Pilot storage to revoke',8)];
 state.handler=async(route,url)=>{const path=url.pathname;if(await options.handler?.(route,path))return true;
  if(path.includes('/storage-connections')){expect(route.request().method()).toBe('GET');await route.fulfill({json:{connections:rows}});return true;}
  if(path.endsWith('/files')){await route.fulfill({json:{binding:{id:uuid(72),projectId:ids.project,connectionId:rows[0].id,revision:4,createdAt:'2026-09-20T00:00:00Z',connection:rows[0]},items:[],breadcrumbs:[],page:{limit:50,hasMore:false,nextAfter:null},transfers:{available:false,code:'STORAGE_GATEWAY_UNAVAILABLE',message:'No provider is used in this fixture.'}}});return true;}
  if(path.endsWith('/files/folder-plans')){await route.fulfill({json:{plans:[],page:{nextAfter:null}}});return true;}return false;
 };
 await mockGenerated(page,state);await openGenerated(page,state);await page.getByRole('tab',{name:'Project files',exact:true}).click();await expect(page.getByRole('heading',{name:'A place for every project file.'})).toBeVisible();return {state,rows};
}
async function open(page:Page,id=uuid(71)){await page.getByRole('button',{name:'Manage connection',exact:true}).click();await page.getByLabel('Company storage connection').selectOption(id);await page.getByRole('button',{name:'Revoke saved connection',exact:true}).click();return page.getByRole('dialog');}
test.beforeEach(({baseURL})=>test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Only local synthetic browser fixtures.'));

test('owner explicitly revokes the selected company connection with its own revision and exact scope',async({page},info)=>{
 const patches:{path:string;body:any}[]=[];const {rows,state}=await setup(page,{handler:async(route,path)=>{if(route.request().method()!=='PATCH')return false;const body=projectStorageConnectionRevokeInput.parse(route.request().postDataJSON());patches.push({path,body});expect(path).toBe(`/api/companies/${ids.company}/storage-connections/${uuid(71)}`);expect(body.revision).toBe(8);rows[1]={...rows[1],status:'revoked',credentialsConfigured:false,revision:9};await route.fulfill({json:{connection:rows[1]}});return true;}});
 let dialog=await open(page);await expect(dialog).toContainText('Pilot storage to revoke');await expect(dialog).toContainText('synthetic-volume-71');await expect(dialog).toContainText(ids.company);await expect(dialog).toContainText(uuid(71));await expect(dialog).toContainText('every linked project');await expect(dialog).toContainText('does not delete the Runpod volume');await expect(dialog.getByRole('button',{name:'Confirm revocation'})).toBeDisabled();expect(patches).toHaveLength(0);
 await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();expect(patches).toHaveLength(0);dialog=await open(page);await expect(dialog.getByRole('checkbox')).not.toBeChecked();
 await page.setViewportSize({width:390,height:844});await noOverflow(page);await page.screenshot({path:info.outputPath('storage-revoke-mobile.png')});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:info.outputPath('storage-revoke-desktop.png')});
 await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Confirm revocation'}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('status').filter({hasText:'Saved connection'})).toContainText('revoked');expect(patches).toHaveLength(1);expect(rows[0].status).toBe('configured');expect(state.writes.filter(write=>write.path.includes('/storage-connections'))).toHaveLength(1);await page.getByRole('button',{name:'Manage connection',exact:true}).click();await expect(page.getByLabel('Company storage connection').locator('option')).toHaveCount(3);expect(state.unexpected).toEqual([]);
});

test('a stale connection revision blocks retries until fresh details are read and explicitly confirmed',async({page})=>{
 const patches:any[]=[];const {rows}=await setup(page,{handler:async(route,path)=>{if(route.request().method()!=='PATCH')return false;expect(path.endsWith(uuid(71))).toBe(true);const body=projectStorageConnectionRevokeInput.parse(route.request().postDataJSON());patches.push(body);if(patches.length===1){rows[1]={...rows[1],name:'Changed pilot connection',revision:9};await route.fulfill({status:409,json:{error:'The storage connection changed. Refresh it.',code:'STORAGE_REVISION_CONFLICT'}});}else{expect(body.revision).toBe(9);rows[1]={...rows[1],status:'revoked',credentialsConfigured:false,revision:10};await route.fulfill({json:{connection:rows[1]}});}return true;}});
 const dialog=await open(page);await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Confirm revocation'}).click();await expect(dialog.getByRole('alert')).toContainText('storage connection changed');await expect(dialog.getByRole('button',{name:'Confirm revocation'})).toBeDisabled();await expect(dialog.getByRole('checkbox')).not.toBeChecked();
 await dialog.getByRole('button',{name:'Check saved connection'}).click();await expect(dialog).toContainText('Changed pilot connection');await expect(dialog).toContainText('revision 9');await expect(dialog.getByRole('checkbox')).not.toBeChecked();await expect(dialog.getByRole('button',{name:'Confirm revocation'})).toBeDisabled();expect(patches).toHaveLength(1);await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Confirm revocation'}).click();await expect(dialog).toHaveCount(0);expect(patches).toHaveLength(2);expect(patches[1].clientId).not.toBe(patches[0].clientId);
});

test('lost revocation response resolves by a read without another mutation and disables a revoked project binding',async({page})=>{
 let patches=0;const {rows}=await setup(page,{handler:async(route,path)=>{if(route.request().method()!=='PATCH')return false;expect(path.endsWith(uuid(70))).toBe(true);expect(projectStorageConnectionRevokeInput.parse(route.request().postDataJSON()).revision).toBe(3);patches++;rows[0]={...rows[0],status:'revoked',credentialsConfigured:false,revision:4};await route.abort('failed');return true;}});
 const dialog=await open(page,uuid(70));await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Confirm revocation'}).click();await expect(dialog.getByRole('alert')).toContainText('revocation has not been confirmed');await expect(dialog.getByRole('button',{name:'Confirm revocation'})).toBeDisabled();await expect(dialog.getByRole('checkbox')).toBeDisabled();await dialog.getByRole('button',{name:'Check saved connection'}).click();await expect(dialog).toHaveCount(0);expect(patches).toBe(1);await expect(page.getByText('Connection revoked',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'New folder',exact:true})).toBeDisabled();await expect(page.getByRole('status').filter({hasText:'Saved connection'})).toContainText('provider key itself is unchanged');
});

test('unavailable status reads never claim success or silently repeat an uncertain revocation',async({page})=>{
 let unknown=false,patches=0;await setup(page,{handler:async(route,path)=>{if(!path.includes('/storage-connections'))return false;if(route.request().method()==='PATCH'){patches++;unknown=true;await route.abort('failed');return true;}if(unknown){await route.fulfill({status:403,json:{error:'Connection access is unavailable.'}});return true;}return false;}});
 const dialog=await open(page);await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Confirm revocation'}).click();await expect(dialog.getByRole('alert')).toContainText('revocation has not been confirmed');await dialog.getByRole('button',{name:'Check saved connection'}).click();await expect(dialog.getByRole('alert')).toContainText('access is unavailable');await expect(dialog.getByRole('button',{name:'Confirm revocation'})).toBeDisabled();await expect(dialog.getByRole('checkbox')).toBeDisabled();expect(patches).toBe(1);await expect(page.getByRole('status').filter({hasText:'Saved connection'})).toHaveCount(0);
});

test('ordinary company members cannot manage or revoke saved storage connections',async({page})=>{const {state}=await setup(page,{role:'member'});await expect(page.getByRole('button',{name:'Manage connection',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Revoke saved connection',exact:true})).toHaveCount(0);expect(state.reads.filter(url=>url.pathname.includes('/storage-connections'))).toHaveLength(0);expect(state.writes.filter(write=>write.path.includes('/storage-connections'))).toHaveLength(0);});
