import {createHash} from 'node:crypto';
import {test,expect,type Page,type Route} from '@playwright/test';
import {generatedFixture,mockGenerated,ids,uuid,date,noOverflow} from './studio-generated-fixture';
import type {ProjectImagePreparation,ProjectImagePreparationProcessor} from '../../src/lib/project-image-preparations-protocol';
import type {HiggsfieldReference,HiggsfieldReferenceVersion} from '../../src/lib/higgsfield-references-protocol';

// Browser metadata fixtures only. Actual transformations and persisted byte
// proofs are covered by project-image-preparation-worker.test.ts.
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGPoXdjyHwAGIwKyeWvUQwAAAABJRU5ErkJggg==','base64'),sha256=createHash('sha256').update(png).digest('hex');
const original:HiggsfieldReferenceVersion={versionId:uuid(201),fileId:uuid(202),name:'private-original.png',version:3,bytes:21*1024**2,sha256:'1'.repeat(64),contentType:'image/png'};
const output:HiggsfieldReferenceVersion={versionId:uuid(203),fileId:uuid(204),name:'product-reference.png',version:1,bytes:png.length,sha256,contentType:'image/png'};
const folder=uuid(205),preparationId=uuid(206),referenceId=uuid(207);
function fixture(){
 const app=generatedFixture();app.detail.workItems[0].humanId=ids.user;
 const processor:ProjectImagePreparationProcessor={id:uuid(208),location:'Qualified processing · Frankfurt, Germany',qualificationSha256:'a'.repeat(64),releaseSha256:'b'.repeat(64),profileSha256:'c'.repeat(64),sourceCommit:'d'.repeat(40),closureSha256:'e'.repeat(64),transport:'linux_binary_v1',recipeSha256:'f'.repeat(64),expiresAt:new Date(Date.now()+600_000).toISOString()};
 const row:ProjectImagePreparation={id:preparationId,projectId:ids.project,workItemId:ids.work,projectRevision:7,status:'proposed',revision:1,requestHash:'2'.repeat(64),purpose:'Product shape reference',source:original,destinationFolderId:folder,destinationName:output.name,bindingId:ids.binding,bindingRevision:1,storageConnectionId:ids.storage,storageConnectionRevision:1,recipeSha256:processor.recipeSha256,proposedBy:ids.user,proposedAgentId:null,createdAt:date,updatedAt:date,approval:null,attempt:0,claimedAt:null,cleanupConfirmedAt:null,revokedAt:null,diagnosticCode:null,derivation:null,continuationMode:'exact_task_v1'};
 return {app,processor,row,rows:[row],enabled:true,refs:[] as HiggsfieldReference[],reads:[] as URL[],writes:[] as {path:string;body:any}[],handler:undefined as ((route:Route,url:URL)=>Promise<boolean>)|undefined};
}
function ready(state:ReturnType<typeof fixture>){state.row={...state.row,status:'ready',revision:8,claimedAt:date,cleanupConfirmedAt:date,attempt:1,derivation:{sourceVersionId:original.versionId,outputFileId:output.fileId,outputVersionId:output.versionId,uploadId:uuid(209),recipeSha256:state.processor.recipeSha256,sourceSha256:original.sha256,sourceBytes:original.bytes,outputSha256:sha256,outputBytes:png.length,outputWidth:1,outputHeight:1,receiptSha256:'3'.repeat(64),createdAt:date}};state.rows=[state.row];}
async function mock(page:Page,state:ReturnType<typeof fixture>){
 const processing=()=>({enabled:state.enabled,message:state.enabled?'Qualified image processing is available for administrator approval.':'Image processing is unavailable. No qualified processor is active.',processor:state.enabled?state.processor:null});
 const sharing=()=>({enabled:false,code:'WORKER_UNAVAILABLE',message:'Reference sharing requires separate worker qualification and permission.',expiresAt:null,qualificationSha256:null,catalogSha256:null});
 state.app.handler=async(route,url)=>{
  const path=url.pathname,method=route.request().method();state.reads.push(url);if(method!=='GET')state.writes.push({path,body:route.request().postDataJSON()});if(await state.handler?.(route,url))return true;let data:unknown;
  if(path.endsWith('/image-preparations')){
   if(method==='POST'){const body=route.request().postDataJSON();state.row={...state.row,status:'proposed',revision:1,source:original,destinationFolderId:body.destinationFolderId,destinationName:body.destinationName,workItemId:body.workItemId,purpose:body.purpose,projectRevision:body.projectRevision};state.rows=[state.row];data={preparation:state.row,processing:processing()};}
   else data={preparations:state.rows,hasMore:false,nextAfter:null,processing:processing()};
  }else if(path.endsWith('/image-preparations/'+preparationId))data={preparation:state.row,processing:processing()};
  else if(path.endsWith('/image-preparations/'+preparationId+'/approve')){const body=route.request().postDataJSON();state.row={...state.row,status:'queued',revision:2,approval:{approvedBy:ids.user,approvedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+body.expiresInMinutes*60_000).toISOString(),approvalHash:'4'.repeat(64),processor:state.processor,maxCostMicrousd:body.maxCostMicrousd,processingConsent:true,derivativeWriteConsent:true,adoptionConsent:true}};state.rows=[state.row];data={preparation:state.row,processing:processing()};}
  else if(path.endsWith('/image-preparations/'+preparationId+'/revoke')){state.row={...state.row,status:'revoked',revision:state.row.revision+1,revokedAt:new Date().toISOString()};state.rows=[state.row];data={preparation:state.row,processing:processing()};}
  else if(path.endsWith('/image-preparations/'+preparationId+'/reference')){
   const body=route.request().postDataJSON(),reference:HiggsfieldReference={id:referenceId,projectId:ids.project,workItemId:body.workItemId,projectRevision:body.projectRevision,taskRevision:1,role:body.role,purpose:body.purpose,status:'proposed',revision:1,requestHash:'5'.repeat(64),proxy:output,source:original,storageConnectionId:ids.storage,storageConnectionRevision:1,bindingId:ids.binding,bindingRevision:2,providerConnectionId:uuid(210),providerConnectionRevision:1,inspection:null,proposedBy:ids.user,proposedAgentId:null,createdAt:date,approvedBy:null,approvedAt:null,expiresAt:null,approvalHash:null,revokedAt:null,diagnosticCode:null,providerConfirmed:false,originalUploaded:false,bytesSharedUnchanged:true,metadataRemoved:false,preparation:{id:preparationId,sourceVersionId:original.versionId,outputVersionId:output.versionId,recipeSha256:state.processor.recipeSha256,receiptSha256:'3'.repeat(64),metadataRemoved:true,outputWidth:1,outputHeight:1}};state.refs=[reference];data={reference,processing:sharing()};
  }else if(path.endsWith('/higgsfield/references'))data={references:state.refs,hasMore:false,nextAfter:null,processing:sharing()};
  else if(path.endsWith('/files'))data={binding:{id:ids.binding,projectId:ids.project,revision:1,connectionId:ids.storage,connection:{id:ids.storage,status:'configured',revision:1,name:'Synthetic project volume'}},items:url.searchParams.has('parentId')?[]:[{kind:'folder',id:folder,name:'References',parentId:null,createdAt:date},...[original,output].map(value=>({kind:'file',id:value.fileId,name:value.name,parentId:null,createdAt:date,latestVersion:{id:value.versionId,version:value.version,bytes:value.bytes,sha256:value.sha256,contentType:value.contentType,verified:true}}))],breadcrumbs:url.searchParams.has('parentId')?[{id:folder,name:'References'}]:[],page:{limit:20,hasMore:false,nextAfter:null},transfers:{available:true,gatewayOrigin:url.origin,maxFileBytes:32*1024**2,partBytes:1024}};
  else if(path.endsWith('/references/candidates'))data={versions:url.searchParams.get('fileId')===original.fileId?[original]:[output],hasMore:false,nextAfter:null};
  else if(path.endsWith('/versions/'+output.versionId+'/access'))data={access:{url:url.origin+'/api/image-preparation-preview',headers:{Authorization:'Bearer synthetic_derivative_only'},expiresAt:new Date(Date.now()+60_000).toISOString(),bytes:png.length,sha256,contentType:'image/png',name:output.name}};
  else if(path==='/api/image-preparation-preview'){expect(route.request().headers().authorization).toBe('Bearer synthetic_derivative_only');await route.fulfill({body:png,headers:{'Content-Type':'image/png','Content-Length':String(png.length)}});return true;}
  else return false;
  await route.fulfill({json:data});return true;
 };
 await mockGenerated(page,state.app);
}
async function open(page:Page){await page.goto('/#studio');await page.getByRole('button').filter({has:page.getByRole('heading',{name:'Image campaign',exact:true})}).click();await page.getByRole('tab',{name:'Generations & references',exact:true}).click();await page.getByRole('button',{name:'Prepare an original image',exact:true}).click();return page.getByRole('region',{name:'Prepare original image',exact:true});}
async function selectOriginal(panel:ReturnType<Page['getByRole']>){await panel.getByRole('button',{name:'Choose original image',exact:true}).click();const picker=panel.getByRole('region',{name:'Choose original for preparation',exact:true});await picker.getByRole('button',{name:'Choose version of '+original.name}).click();await picker.getByRole('button',{name:'Use version 3',exact:true}).click();}
test.beforeEach(({baseURL})=>test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Use local fixture origin.'));

test('unavailable runtime still permits a21MiB original proposal and an actual destination folder without reading its bytes',async({page})=>{
 const state=fixture();state.rows=[];state.enabled=false;await mock(page,state);const panel=await open(page);await selectOriginal(panel);await panel.getByRole('button',{name:'Choose derivative folder'}).click();const picker=panel.getByRole('region',{name:'Choose prepared image destination'});await picker.getByRole('button',{name:'Open References',exact:true}).click();await picker.getByRole('button',{name:'Use this folder'}).click();await panel.getByLabel('Prepared PNG filename',{exact:true}).fill(output.name);await panel.getByLabel('Image preparation task',{exact:true}).selectOption(ids.work);await panel.getByLabel('Image preparation purpose',{exact:true}).fill('Smaller product reference');await panel.getByRole('button',{name:'Propose image preparation'}).click();await expect(panel).toContainText('Original proposed. No processing or external sharing has been approved.');await expect(panel.getByRole('button',{name:'Approve exact image processing'})).toBeDisabled();await expect(panel).toContainText('No qualified image processor');
 const proposal=state.writes.find(value=>value.path.endsWith('/image-preparations'))!;expect(proposal.body).toMatchObject({projectId:ids.project,workItemId:ids.work,projectRevision:7,sourceVersionId:original.versionId,sourceSha256:original.sha256,sourceBytes:original.bytes,destinationFolderId:folder,destinationName:output.name,purpose:'Smaller product reference'});expect(proposal.body).not.toHaveProperty('continuation');expect(state.writes.filter(value=>value.path.endsWith('/access')||value.path.endsWith('/approve')||value.path.endsWith('/reference'))).toHaveLength(0);
});
test('administrator separately consents to processor location, derivative write and finite cost',async({page},testInfo)=>{
 const state=fixture();await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Review preparation',exact:true}).click();const review=panel.getByRole('region',{name:'Review image preparation'});await expect(review).toContainText('Frankfurt, Germany');const approve=review.getByRole('button',{name:'Approve exact image processing'});await expect(approve).toBeDisabled();await review.getByLabel('Processing permission expires after',{exact:true}).selectOption('10');await review.getByLabel('Maximum processing cost (USD)',{exact:true}).fill('0.02');for(const box of await review.getByRole('checkbox').all())await box.check();await expect(approve).toBeEnabled();await page.setViewportSize({width:390,height:844});await review.scrollIntoViewIfNeeded();await noOverflow(page);await review.screenshot({path:testInfo.outputPath('image-processing-consent-mobile.png')});await approve.click();await expect(review).toContainText('Approved · queued');expect(state.writes.find(value=>value.path.endsWith('/approve'))?.body).toMatchObject({revision:1,requestHash:state.row.requestHash,processorId:state.processor.id,qualificationSha256:state.processor.qualificationSha256,expiresInMinutes:10,maxCostMicrousd:20_000,processingConsent:true,derivativeWriteConsent:true,adoptionConsent:true});expect(state.writes.filter(value=>value.path.endsWith('/access')||value.path.endsWith('/reference'))).toHaveLength(0);
});
test('ready derivative is previewed exactly then proposed for separate sharing on current open work',async({page})=>{
 const state=fixture();ready(state);state.row={...state.row,workItemId:uuid(220),continuationMode:'submitted_plan_v1'};state.rows=[state.row];state.app.detail.workItems.push({...state.app.detail.workItems[0],id:uuid(220),taskId:uuid(221),title:'Accepted reference plan',stage:'references',status:'done'});await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Review preparation'}).click();const review=panel.getByRole('region',{name:'Review image preparation'});await expect(review).toContainText('does not resume or impersonate');await expect(review.getByRole('button',{name:'Prepare sharing review'})).toBeDisabled();await review.getByRole('button',{name:'Preview exact prepared image'}).click();await expect(review.getByRole('img')).toBeVisible();await review.getByLabel('Prepared image reference task',{exact:true}).selectOption(ids.work);await expect(review.getByLabel('Prepared image reference task').locator('option[value="'+uuid(220)+'"]')).toBeDisabled();await review.getByLabel('Prepared image sharing purpose',{exact:true}).fill('Approved product shape');await review.getByRole('button',{name:'Prepare sharing review'}).click();await expect(page.getByRole('region',{name:'Review reference sharing'})).toContainText('Prepared derivative: 1 × 1 PNG');await expect(page.getByRole('region',{name:'Review reference sharing'})).toContainText('No trusted image inspection recorded yet');const body=state.writes.find(value=>value.path.endsWith('/reference'))!.body;expect(body).toMatchObject({revision:8,projectRevision:7,workItemId:ids.work,role:'image',purpose:'Approved product shape'});expect(Object.keys(body).sort()).toEqual(['clientId','projectRevision','purpose','revision','role','workItemId']);expect(state.writes.filter(value=>value.path.endsWith('/access'))).toHaveLength(1);expect(state.writes.filter(value=>value.path.includes(original.versionId)||value.path.endsWith('/approve'))).toHaveLength(0);
});
test('submitted-plan approval can adopt an accepted completed task while a new human proposal still needs open work',async({page})=>{
 const state=fixture();state.row={...state.row,continuationMode:'submitted_plan_v1'};state.rows=[state.row];state.app.detail.workItems[0].status='done';await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Review preparation'}).click();const review=panel.getByRole('region',{name:'Review image preparation'});await expect(review).toContainText('server rechecks the accepted plan');for(const box of await review.getByRole('checkbox').all())await box.check();await expect(review.getByRole('button',{name:'Approve exact image processing'})).toBeEnabled();await expect(panel.getByLabel('Image preparation task').locator('option[value="'+ids.work+'"]')).toBeDisabled();
});
for(const [mode,currentRevision,allowed] of [['submitted_plan_v1',8,true],['exact_task_v1',8,false],['submitted_plan_v1',9,false]] as const)test(`preparation revision eligibility: ${mode} source7/current${currentRevision} ${allowed?'enables':'disables'} consent`,async({page})=>{
 const state=fixture();state.row={...state.row,continuationMode:mode};state.rows=[state.row];state.app.detail.project.revision=currentRevision;
 // Leave exact-task work open so only the changed project revision blocks it.
 if(mode==='submitted_plan_v1')state.app.detail.workItems[0].status='done';
 await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Review preparation'}).click();const review=panel.getByRole('region',{name:'Review image preparation'}),approve=review.getByRole('button',{name:'Approve exact image processing'});
 await expect(approve).toBeDisabled();await expect(review.getByRole('checkbox')).toHaveCount(3);
 for(const box of await review.getByRole('checkbox').all())if(allowed){await expect(box).toBeEnabled();await box.check();}else await expect(box).toBeDisabled();
 if(allowed)await expect(approve).toBeEnabled();else await expect(approve).toBeDisabled();
 expect(state.row.projectRevision).toBe(7);expect(state.writes.filter(value=>value.path.endsWith('/approve'))).toHaveLength(0);
});
test('uncertain processing and missing cleanup never offer derivative preview, retry or sharing',async({page})=>{
 const state=fixture();state.row={...state.row,status:'uncertain',revision:4,attempt:1,claimedAt:date,diagnosticCode:'PREPARATION_CLEANUP_FAILED'};state.rows=[state.row];await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Review preparation'}).click();const review=panel.getByRole('region',{name:'Review image preparation'});await expect(review).toContainText('cleanup are not yet confirmed');await expect(review).toContainText('do not create a replacement');await expect(review.getByRole('button',{name:'Prepare sharing review'})).toHaveCount(0);await expect(review.getByRole('button',{name:'Preview exact prepared image'})).toHaveCount(0);expect(state.writes.filter(value=>value.path.includes('/image-preparations')||value.path.endsWith('/access'))).toHaveLength(0);
});
test('foreign preparation scope and changed exact identity cannot open processing approval',async({page})=>{
 const state=fixture();state.handler=async(route,url)=>{if(!url.pathname.endsWith('/image-preparations/'+preparationId))return false;await route.fulfill({json:{preparation:{...state.row,id:uuid(299)},processing:{enabled:true,message:'Synthetic',processor:state.processor}}});return true;};await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Review preparation'}).click();await expect(panel.getByRole('alert')).toContainText('identity changed');await expect(panel.getByRole('button',{name:'Approve exact image processing'})).toHaveCount(0);state.handler=undefined;state.rows=[{...state.row,projectId:uuid(298)}];await panel.getByRole('button',{name:'Refresh preparations'}).click();await expect(panel.getByRole('alert')).toContainText('project or file scope');expect(state.writes.filter(value=>value.path.includes('/image-preparations')||value.path.endsWith('/access'))).toHaveLength(0);
});
test('unconfirmed proposal retry keeps one idempotency identity and unmount ignores a late response',async({page})=>{
 const state=fixture();state.rows=[];let failed=false;state.handler=async(route,url)=>{if(!url.pathname.endsWith('/image-preparations')||route.request().method()!=='POST'||failed)return false;failed=true;await route.fulfill({status:503,json:{error:'Synthetic response not confirmed. Refresh saved status.'}});return true;};await mock(page,state);const panel=await open(page);await selectOriginal(panel);await panel.getByLabel('Image preparation task',{exact:true}).selectOption(ids.work);await panel.getByLabel('Image preparation purpose',{exact:true}).fill('Same finite proposal');await panel.getByRole('button',{name:'Propose image preparation'}).click();await expect(panel.getByRole('alert')).toContainText('not confirmed');await panel.getByRole('button',{name:'Propose image preparation'}).click();await expect(panel).toContainText('Original proposed');const writes=state.writes.filter(value=>value.path.endsWith('/image-preparations'));expect(writes).toHaveLength(2);expect(writes[0].body.clientId).toBe(writes[1].body.clientId);
 let finish!:(value:unknown)=>void;const delayed=new Promise(resolve=>{finish=resolve;});state.handler=async(route,url)=>{if(!url.pathname.endsWith('/image-preparations/'+preparationId))return false;await delayed;await route.fulfill({json:{preparation:state.row,processing:{enabled:true,message:'Late synthetic response',processor:state.processor}}}).catch(()=>{});return true;};await panel.getByRole('button',{name:'Review preparation'}).click();await page.getByRole('button',{name:'Close original image preparation'}).click();finish(undefined);await expect(panel).toHaveCount(0);await expect(page.getByRole('region',{name:'Review reference sharing'})).toHaveCount(0);
});
test('original-size mode does not expand the existing10MiB sharing picker and members cannot consent',async({page})=>{
 const state=fixture();state.app.company.role='member';await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Review preparation'}).click();await expect(panel).toContainText('A human administrator must approve');await expect(panel.getByRole('button',{name:'Approve exact image processing'})).toHaveCount(0);await expect(panel.getByRole('button',{name:'Revoke processing permission'})).toHaveCount(0);await page.getByRole('button',{name:'Close original image preparation'}).click();await page.getByRole('button',{name:'Choose prepared image',exact:true}).click();const picker=page.getByRole('region',{name:'Choose prepared reference image'});await picker.getByRole('button',{name:'Choose version of '+original.name}).click();await expect(picker).toContainText('smaller than 10 MiB');await expect(picker.getByRole('button',{name:'Use version 3'})).toBeDisabled();
});
test('original picker rejects oversize and unsupported image formats before any proposal',async({page})=>{
 const state=fixture();state.rows=[];state.handler=async(route,url)=>{if(!url.pathname.endsWith('/references/candidates'))return false;await route.fulfill({json:{versions:[{...original,version:4,bytes:33*1024**2},{...original,versionId:uuid(250),version:5,contentType:'image/gif',bytes:1000}],hasMore:false,nextAfter:null}});return true;};await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Choose original image'}).click();const picker=panel.getByRole('region',{name:'Choose original for preparation'});await picker.getByRole('button',{name:'Choose version of '+original.name}).click();await expect(picker).toContainText('at most 32 MiB');await expect(picker).toContainText('supports PNG, JPEG or WebP');await expect(picker.getByRole('button',{name:'Use version 4'})).toBeDisabled();await expect(picker.getByRole('button',{name:'Use version 5'})).toBeDisabled();expect(state.writes.filter(value=>value.path.endsWith('/image-preparations')||value.path.endsWith('/access'))).toHaveLength(0);
});
test('processor expiry disables already checked processing consent without posting an approval',async({page})=>{
 const start=Date.parse('2026-10-01T12:00:00Z');await page.clock.install({time:new Date(start)});await page.clock.pauseAt(new Date(start+1000));
 const state=fixture();state.processor.expiresAt=new Date(start+61_000).toISOString();await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Review preparation'}).click();
 const review=panel.getByRole('region',{name:'Review image preparation'}),consents=review.getByRole('checkbox'),approve=review.getByRole('button',{name:'Approve exact image processing'});
 // The review loads asynchronously; locator.all() alone can return no controls.
 await expect(consents).toHaveCount(3);for(const box of await consents.all()){await box.check();await expect(box).toBeChecked();}
 await expect(approve).toBeEnabled();await page.clock.fastForward(61_000);await expect(panel).toContainText('processor qualification has expired');await expect(approve).toBeDisabled();expect(state.writes.filter(value=>value.path.endsWith('/approve'))).toHaveLength(0);
});
test('a reference handoff with substituted provenance never prefills the sharing review',async({page})=>{
 const state=fixture();ready(state);state.handler=async(route,url)=>{if(!url.pathname.endsWith('/image-preparations/'+preparationId+'/reference'))return false;const body=route.request().postDataJSON();await route.fulfill({json:{reference:{projectId:ids.project,projectRevision:7,workItemId:body.workItemId,purpose:body.purpose,role:body.role,proxy:output,source:original,preparation:{id:preparationId,sourceVersionId:original.versionId,outputVersionId:output.versionId,recipeSha256:state.processor.recipeSha256,receiptSha256:'0'.repeat(64),metadataRemoved:true,outputWidth:1,outputHeight:1}},processing:{enabled:false,message:'Synthetic'}}});return true;};await mock(page,state);const panel=await open(page);await panel.getByRole('button',{name:'Review preparation'}).click();const review=panel.getByRole('region',{name:'Review image preparation'});await review.getByRole('button',{name:'Preview exact prepared image'}).click();await expect(review.getByRole('img')).toBeVisible();await review.getByRole('button',{name:'Prepare sharing review'}).click();await expect(panel.getByRole('alert')).toContainText('exact preparation receipt');await expect(page.getByRole('region',{name:'Review reference sharing'})).toHaveCount(0);expect(state.writes.filter(value=>value.path.endsWith('/approve'))).toHaveLength(0);
});
