import {expect,type Page,type Route} from '@playwright/test';
import {createHash} from 'node:crypto';
import {STUDIO_TEMPLATES,STUDIO_SKILLS,studioReviewInput,studioDeliveryInput,type StudioGeneratedProjectDetail,type StudioGeneratedArtifact,type StudioReadableSnapshot,type StudioProject} from '../../src/lib/studio-protocol';
import {studioGeneratedProjectInput,studioGeneratedArtifactRegisterInput,type GeneratedProjectSpec,type GeneratedObservedMedia} from '../../src/lib/studio-generated-protocol';
import type {HiggsfieldArchive} from '../../src/lib/higgsfield-archive-protocol';

export const uuid=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
export const ids={company:uuid(1),user:uuid(2),producer:uuid(3),project:uuid(4),unit:uuid(5),work:uuid(6),task:uuid(7),archive:uuid(8),request:uuid(9),job:uuid(10),output:uuid(11),storage:uuid(12),binding:uuid(13),version:uuid(14),artifact:uuid(15),providerSponsor:uuid(16),registrar:uuid(17),qc:uuid(18),qcTask:uuid(19),deliveryWork:uuid(20),deliveryTask:uuid(21)};
export const date='2026-09-20T00:00:00.000Z';
export const bytes=Buffer.from('Synthetic file download fixture. No provider or client media.');
const hash=createHash('sha256').update(bytes).digest('hex');
export function generatedFixture(kind:'image'|'video'|'audio'='image'){
 const user={id:ids.user,name:'Independent reviewer',email:'reviewer@example.invalid',roleTitle:'Producer',avatarColor:'#607850',avatarId:null};
 const company={id:ids.company,name:'Generated media studio',slug:'generated-media-studio',template:'blank',role:'owner'};
 const spec:GeneratedProjectSpec=kind==='image'?{kind,format:'png',width:1280,height:720,color:{mode:'not_required'}}:kind==='video'?{kind,format:'mp4',codec:'h264',width:1280,height:720,color:{mode:'not_required'},frameRate:{mode:'constant',numerator:24,denominator:1},audio:{mode:'none'}}:{kind,format:'wav',codec:'pcm_s16le',sampleRateHz:48000,channels:2};
 const template=STUDIO_TEMPLATES.find(t=>t.id==='ai-production')!,roles=template.roles.map(r=>({...r,agentId:null,humanId:r.key==='qc'?ids.user:ids.producer}));
 const project:StudioGeneratedProjectDetail['project']={contractVersion:2,id:ids.project,name:`${kind[0].toUpperCase()+kind.slice(1)} campaign`,clientName:'Synthetic client',brief:'Create the approved campaign deliverable and keep its verified source evidence.',productionPath:'higgsfield',dueDate:null,spec,aiPolicy:'allowed',revision:7,status:'production',gates:Object.fromEntries(['brief','estimate','production'].map(gate=>[gate,{decision:'approved',note:'Synthetic approval.',recordedBy:ids.user,at:date}])),createdAt:date,updatedAt:date,shotCount:1};
 const work:StudioGeneratedProjectDetail['workItems'][number]={id:ids.work,taskId:ids.task,title:'D010 · Higgsfield generation',stage:'generation',roleKey:'comp',shotId:ids.unit,dependencies:[],status:'doing',readiness:'running',blockedReason:null,revision:1,execution:'creative',agentId:null,humanId:ids.producer};
 const detail:StudioGeneratedProjectDetail={project,roles,skills:STUDIO_SKILLS,shots:[kind==='image'?{id:ids.unit,kind,code:'D010',description:'Approved campaign image'}:{id:ids.unit,kind,code:'D010',description:`Approved campaign ${kind}`,durationMs:{min:999,max:1001}}],workItems:[work,{...work,id:ids.qc,taskId:ids.qcTask,title:'D010 · Independent QC',stage:'qc',roleKey:'qc',dependencies:[ids.work],status:'todo',readiness:'blocked',execution:'human',humanId:ids.user},{...work,id:ids.deliveryWork,taskId:ids.deliveryTask,title:'Package & delivery handoff',stage:'delivery',roleKey:'delivery',shotId:null,dependencies:[ids.qc],status:'todo',readiness:'blocked',execution:'human',humanId:ids.user}],artifacts:[],reviews:[],deliveries:[]};
 const common={bytes:bytes.length,sha256:hash,verification:'full_decode' as const,inspectionVersion:1 as const},color={space:null,primaries:null,transfer:null,range:null};
 const media:GeneratedObservedMedia=kind==='image'?{...common,kind,format:'png',contentType:'image/png',codec:'png',width:1280,height:720,color}:kind==='video'?{...common,kind,format:'mp4',contentType:'video/mp4',codec:'h264',width:1280,height:720,color,durationMs:1000,frameRate:{numerator:24,denominator:1},averageFrameRate:{numerator:24,denominator:1},vfr:false,frameCount:24,audio:null}:{...common,kind,format:'wav',contentType:'audio/wav',codec:'pcm_s16le',sampleRateHz:48000,channels:2,durationMs:1000,decodedSamples:48000};
 const artifact:StudioGeneratedArtifact={contractVersion:2,kind:'verified_generated_media',mediaKind:kind,id:ids.artifact,workItemId:ids.work,name:'Campaign master',version:1,url:`/api/companies/${ids.company}/studio/projects/${ids.project}/generated-artifacts/${ids.artifact}/manifest`,sha256:'b'.repeat(64),notes:'Verified fixture.',reviewStatus:'pending',createdAt:date,producedBy:ids.producer,producedAgentId:null,media,file:{bytes:bytes.length,sha256:hash,contentType:media.contentType},source:{requestedBy:ids.producer,agentId:null,runId:null,agentSponsorId:null,providerSponsorId:ids.providerSponsor},provenance:{archiveId:ids.archive,archiveApprovedBy:ids.user,requestId:ids.request,jobId:ids.job,outputId:ids.output,storageVersionId:ids.version,registeredBy:ids.registrar,registeredAgentId:null,registeredRunId:null},specSha256:'c'.repeat(64),manifestSha256:'b'.repeat(64),limitations:kind==='image'?['COLOR_METADATA_NOT_REQUIRED']:kind==='video'?['COLOR_METADATA_NOT_REQUIRED','VIDEO_DURATION_ROUNDED_TO_MS']:[]};
 const archive:HiggsfieldArchive={id:ids.archive,projectId:ids.project,requestId:ids.request,jobId:ids.job,outputId:ids.output,outputIdentity:'d'.repeat(64),kind,status:'verified',revision:3,requestHash:'e'.repeat(64),projectRevision:7,bindingId:ids.binding,bindingRevision:1,storageConnectionId:ids.storage,storageConnectionRevision:1,destination:{parentId:null,fileId:null,name:'campaign-master.'+spec.format,ancestors:[]},maxBytes:256*1024**2,sourceAttribution:{requestedBy:ids.producer,agentId:null,runId:null,agentSponsorId:null,approvedBy:ids.user},proposedBy:ids.producer,proposedAgentId:null,createdAt:date,approvedBy:ids.user,approvedAt:date,expiresAt:'2026-09-19T00:00:00Z',revokedAt:null,approvedProjectRevision:7,approvedBindingRevision:1,uploadId:uuid(22),versionId:ids.version,diagnosticCode:null,fetched:{bytes:bytes.length,sha256:hash},bytesVerified:true};
 const legacy:StudioProject={id:uuid(30),name:'Existing VFX film',clientName:'Existing client',brief:'Retained frame-based project.',productionPath:'vfx',dueDate:null,spec:{width:1920,height:1080,format:'exr',fpsNumerator:24,fpsDenominator:1,colorSpace:'Linear Rec.709'},aiPolicy:'unknown',revision:1,status:'intake',gates:{},createdAt:date,updatedAt:date};
 const snapshot:StudioReadableSnapshot={templates:STUDIO_TEMPLATES,skills:STUDIO_SKILLS,profile:{templateId:'ai-production',revision:1,roles},projects:[project,legacy],hasMore:false,nextAfter:null};
 return {user,company,detail,artifact,archive,archives:[archive],snapshot,legacy,reads:[] as URL[],writes:[] as {path:string;body:any}[],unexpected:[] as string[],handler:undefined as ((route:Route,url:URL)=>Promise<boolean>)|undefined};
}
export type GeneratedFixture=ReturnType<typeof generatedFixture>;
export async function mockGenerated(page:Page,state:GeneratedFixture){
 await page.route('https://**',route=>route.abort());
 await page.route('**/api/**',async route=>{
  const url=new URL(route.request().url()),path=url.pathname,method=route.request().method();
  if(method==='GET')state.reads.push(url);else state.writes.push({path,body:route.request().postDataJSON()});
  if(await state.handler?.(route,url))return;
  let data:unknown;
  if(path==='/api/session')data={user:state.user,companies:[state.company],configured:true};
  else if(path.endsWith('/workspace'))data={company:state.company,rooms:[],members:[{...state.user,userId:state.user.id,role:state.company.role},...[[ids.producer,'Generation producer'],[ids.registrar,'File registrar'],[ids.providerSponsor,'Provider sponsor']].map(([id,name])=>({...state.user,id,userId:id,name,role:'admin'}))],agents:[],tasks:[],messages:[],presence:[],activity:[],drives:[],openings:[],applications:[],layout:[]};
  else if(path.endsWith('/presence'))data={presence:[{userId:state.user.id,name:state.user.name,avatarColor:state.user.avatarColor,avatarId:null,roomId:null,x:0,z:0,status:'available',updatedAt:new Date().toISOString()}]};
  else if(path.endsWith('/studio')){expect(url.searchParams.get('contractVersion')).toBe('2');data=state.snapshot;}
  else if(path.endsWith('/projects')&&method==='POST'){
   const body=studioGeneratedProjectInput.parse(route.request().postDataJSON());state.detail.project={...state.detail.project,...body,shotCount:body.shots.length};state.detail.shots=body.shots.map((unit,i)=>({...unit,id:uuid(100+i)}));state.snapshot.projects.unshift(state.detail.project);data={project:state.detail.project};
  }else if(path.endsWith('/'+ids.project)){expect(url.searchParams.get('contractVersion')).toBe('2');data=state.detail;}
  else if(path.endsWith('/'+state.legacy.id))data={project:state.legacy,roles:state.detail.roles,skills:STUDIO_SKILLS,shots:[{id:uuid(31),code:'SH010',description:'Legacy shot',frameStart:1001,frameEnd:1024,handles:8,disciplines:['compositing']}],workItems:[],artifacts:[],reviews:[],deliveries:[]};
  else if(path.endsWith('/higgsfield'))data={status:'connected',revision:1,officialEndpoint:'https://higgsfield.ai/mcp',toolCount:3,tools:['image','video','audio'].map(kind=>({name:'generate_'+kind,description:'Synthetic generation tool',inputSchema:{}}))};
  else if(path.endsWith('/higgsfield/requests')){const request={id:ids.request,projectId:ids.project,workItemId:ids.work,taskRevision:1,tool:'generate_'+state.detail.project.spec.kind,arguments:{prompt:'Synthetic approved request'},note:'Synthetic fixture',requestHash:'e'.repeat(64),status:'returned',createdAt:date};data=url.searchParams.has('requestId')?{request}:{requests:[request],hasMore:false,nextAfter:null};}
  else if(path.endsWith('/higgsfield/jobs'))data={jobs:[{id:ids.job,projectId:ids.project,requestId:ids.request,kind:state.detail.project.spec.kind,model:'fixture',status:'completed',diagnosticCode:null,pollAttempts:1,nextPollAt:null,createdAt:date,updatedAt:date,outputs:[{id:ids.output,ordinal:0,kind:state.detail.project.spec.kind,locatorIdentity:'d'.repeat(64),bytesVerified:false}]}],hasMore:false,nextAfter:null};
  else if(path.endsWith('/higgsfield/archives'))data={archives:state.archives,hasMore:false,nextAfter:null,processing:{enabled:false,message:'No worker is enabled in this browser fixture.'}};
  else if(path.endsWith('/archives/'+ids.archive))data={archive:state.archive};
  else if(path.endsWith('/generated-artifacts')&&method==='POST'){const body=studioGeneratedArtifactRegisterInput.parse(route.request().postDataJSON());expect(body.archiveId).toBe(ids.archive);expect(body.workItemId).toBe(ids.work);state.artifact={...state.artifact,name:body.name,notes:body.notes,provenance:{...state.artifact.provenance,registeredBy:state.user.id}};state.detail.artifacts=[state.artifact];state.detail.project.revision++;data={artifact:state.artifact,project:state.detail.project,replayed:false};}
  else if(path.endsWith('/reviews')&&method==='POST'){const body=studioReviewInput.parse(route.request().postDataJSON());state.artifact.reviewStatus=body.decision;state.detail.project.revision++;state.detail.reviews.unshift({...body,id:uuid(40),contractVersion:2,reviewedBy:state.user.id,createdAt:date,specSha256:state.artifact.specSha256,manifestSha256:state.artifact.manifestSha256,attestationVersion:1,technicalMatch:{matches:true,issues:[],limitations:state.artifact.limitations}});data={review:state.detail.reviews[0]};}
  else if(path.endsWith('/deliveries')&&method==='POST'){const body=studioDeliveryInput.parse(route.request().postDataJSON());const delivery={id:uuid(41),name:body.name,note:body.note,status:'prepared' as const,createdAt:date,manifest:{schemaVersion:2,kind:'generated_media_package',transportStatus:'not_transferred',artifacts:[state.artifact],reviewReceipts:state.detail.reviews}};state.detail.deliveries=[delivery];state.detail.project.revision++;data={delivery};}
  else if(path.endsWith('/files'))data={binding:null,items:[],breadcrumbs:[],page:{limit:50,hasMore:false,nextAfter:null},transfers:{available:false,code:'STORAGE_GATEWAY_UNAVAILABLE',message:'Storage is offline in this fixture.'}};
  else if(path.endsWith('/coordination'))data={policy:null,dispatches:[]};
  else if(path.endsWith('/review-policy'))data={policy:null,reviews:[]};
  if(!data)state.unexpected.push(method+' '+path);
  await route.fulfill({status:data?200:501,json:data||{error:'Unmatched synthetic fixture request: '+path}});
 });
}
export async function openGenerated(page:Page,state:GeneratedFixture){await page.goto('/#studio');await page.reload();await page.getByRole('button').filter({has:page.getByRole('heading',{name:state.detail.project.name,exact:true})}).click();await expect(page.getByRole('heading',{name:state.detail.project.name,exact:true,level:1})).toBeVisible();}
export async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual((await page.viewportSize())!.width+1);for(const dialog of await page.getByRole('dialog').all())expect(await dialog.evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1);}
