import {test,expect,type Page} from '@playwright/test';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {studioClientDeliveryCreateInput,studioClientDeliveryResponseInput,type StudioClientDeliveryDetail,type StudioClientDeliveryShare,type StudioGeneratedClientDeliveryFile} from '../../src/lib/studio-client-delivery-protocol';
import {GENERATED_CLIENT_PART_BYTES} from '../../src/lib/generated-client-download';
import {generatedFixture,mockGenerated,openGenerated,noOverflow,ids,uuid,date,bytes} from './studio-generated-fixture';
test.beforeEach(({baseURL})=>test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Synthetic fixtures require a local origin.'));
const clientId=uuid(90),shareId=uuid(91),deliveryId=uuid(92);
function portalFixture(kind:'image'|'video'|'audio'='image',payload:Buffer=bytes){
 const state=generatedFixture(kind),hash=createHash('sha256').update(payload).digest('hex');
 const file:StudioGeneratedClientDeliveryFile={fileId:ids.version,artifactId:ids.artifact,path:'campaign-master.'+state.detail.project.spec.format,frame:null,sha256:hash,bytes:payload.length,contentType:state.artifact.file.contentType,storageVersionId:ids.version,mediaKind:kind,transport:'project_storage'};
 const share:StudioClientDeliveryShare={id:shareId,projectId:ids.project,deliveryId,recipientUserId:clientId,recipientName:'External client',identityBasis:'account_confirmed_out_of_band',emailVerifiedAtCreation:false,status:'active',revision:1,expiresAt:'2027-01-01T00:00:00.000Z',createdAt:date,createdBy:ids.user,packageSha256:'f'.repeat(64),sourceManifestSha256:'e'.repeat(64),response:'awaiting_response',invitationPath:'/delivery/'+shareId,fileCount:1,receiptSummary:{portalOpened:0,downloadAccessIssued:0,clientAcknowledged:0,changesRequested:0},transferStatus:'not_observed',expired:false};
 const detail:StudioClientDeliveryDetail={share,package:{schemaVersion:2,delivery:{id:deliveryId,name:'Approved campaign package',preparedAt:date},project:{id:ids.project,name:state.detail.project.name,clientName:'Synthetic client',spec:state.detail.project.spec},sourceManifestSha256:share.sourceManifestSha256,reviewBasis:'independently_approved',artifacts:[{id:ids.artifact,name:'Campaign master',version:1,sha256:state.artifact.sha256}],files:[file]},receipts:[],receiptPage:{hasMore:false,nextAfter:null,limit:20},canRespond:true,responseBlockedReason:null,identity:{userId:clientId,name:'External client',emailVerified:false}};
 return {state,file,share,detail,payload,userId:clientId,accessCalls:[] as Record<string,unknown>[],ranges:[] as string[],rangeAuthorizations:[] as string[],responses:[] as Record<string,unknown>[],tamper:false,mismatch:false,denyRenewal:false,advanceFirstRange:false,hold:null as (()=>void)|null,holdRange:false,rangeEntered:false,unexpected:[] as string[]};
}
async function mockPortal(page:Page,f:ReturnType<typeof portalFixture>){
 await page.route('https://**',route=>route.abort());
 await page.route('**/api/**',async route=>{
  const path=new URL(route.request().url()).pathname,method=route.request().method();let data:unknown,status=200;
  if(path==='/api/session')data={user:{...f.state.user,id:f.userId,name:'External client'},companies:[],configured:true};
  else if(path.endsWith('/identity'))data={user:{id:f.userId,name:'External client',email:'external@example.invalid',emailVerified:false}};
  else if(f.userId!==clientId){status=403;data={error:'This invitation belongs to another account.'};}
  else if(path==='/api/client-deliveries/'+shareId)data=f.detail;
  else if(path.endsWith('/open'))data={receipt:{id:uuid(93)}};
  else if(path.endsWith('/access')){f.accessCalls.push(route.request().postDataJSON());if(f.denyRenewal&&f.accessCalls.length>1){status=403;data={error:'Client access revoked.'};}else data={access:{transport:'project_storage',storageVersionId:f.mismatch?uuid(99):ids.version,gatewayOrigin:new URL(route.request().url()).origin,url:new URL(route.request().url()).origin+'/v1/client-files/'+ids.version,headers:{Authorization:'Bearer sct_'+String(f.accessCalls.length).repeat(43)},expiresAt:new Date(Date.now()+60_000).toISOString(),bytes:f.file.bytes,name:f.file.path,sha256:f.file.sha256,contentType:f.file.contentType,status:'download_access_issued',bytesReceivedByClient:'not_observed'}};}
  else if(path.endsWith('/responses')){const body=studioClientDeliveryResponseInput.parse(route.request().postDataJSON());f.responses.push(body);f.share.response=body.decision;f.detail.canRespond=false;f.detail.responseBlockedReason='Your exact-package response is preserved.';f.detail.receipts.push({id:uuid(94),kind:body.decision,actorUserId:clientId,fileId:null,note:body.note,createdAt:date,packageSha256:f.share.packageSha256});data={receipt:f.detail.receipts[0]};}
  else if(path.endsWith('/manifest')){await route.fulfill({contentType:'application/json',body:JSON.stringify(f.detail.package)});return;}
  else{f.unexpected.push(method+' '+path);status=501;data={error:'Unmatched synthetic request'};}
  await route.fulfill({status,json:data});
 });
 await page.route('**/v1/client-files/**',async route=>{
  const headers={'Access-Control-Allow-Origin':new URL(page.url()).origin,'Access-Control-Allow-Headers':'Authorization, Range','Access-Control-Expose-Headers':'Content-Length, Content-Range, X-Content-SHA256'};
  if(route.request().method()==='OPTIONS'){await route.fulfill({status:204,headers});return;}
  f.rangeEntered=true;if(f.holdRange)await new Promise<void>(resolve=>{f.hold=resolve;});
  const range=route.request().headers().range;f.ranges.push(range);const [,start,end]=/^bytes=(\d+)-(\d+)$/.exec(range)!;const payload=Buffer.from(f.payload.subarray(Number(start),Number(end)+1));if(f.tamper)payload[0]^=1;
  f.rangeAuthorizations.push(route.request().headers().authorization);if(f.advanceFirstRange&&f.ranges.length===1)await page.evaluate(()=>(window as any).advanceGrantClock());
  await route.fulfill({status:206,headers:{...headers,'Content-Length':String(payload.length),'Content-Range':`bytes ${start}-${end}/${f.file.bytes}`,'X-Content-SHA256':f.file.sha256},body:payload});
 });
}
async function openPortal(page:Page,f:ReturnType<typeof portalFixture>){await mockPortal(page,f);await page.goto('/delivery/'+shareId);await expect(page.getByRole('heading',{name:'Your files',exact:true})).toBeVisible();}

test('generated invitation waits for accepted handoff, preserves reviewed retry and shows authenticated provenance',async({page},testInfo)=>{
 const state=generatedFixture(),f=portalFixture();state.detail.deliveries=[{id:deliveryId,name:'Approved campaign package',note:'Synthetic reviewed package.',status:'prepared',createdAt:date,manifest:{schemaVersion:2,transportStatus:'not_transferred'}}];let attempts=0;const shares:StudioClientDeliveryShare[]=[];
 state.handler=async(route,url)=>{if(!url.pathname.endsWith('/client-deliveries'))return false;if(route.request().method()==='POST'){const input=studioClientDeliveryCreateInput.parse(route.request().postDataJSON());expect(input.recipientUserId).toBe(clientId);if(++attempts===1){await route.fulfill({status:503,json:{error:'Synthetic uncertain invitation.'}});return true;}shares.push(f.share);}await route.fulfill({json:{shares,page:{hasMore:false,nextAfter:null,limit:20}}});return true;};
 await mockGenerated(page,state);await openGenerated(page,state);await page.getByRole('tab',{name:/^Review & delivery/}).click();await expect(page.getByRole('button',{name:'Create client invitation',exact:true})).toBeDisabled();await expect(page.getByRole('region',{name:'Client delivery portal'})).toContainText('Accept every production, QC and delivery-handoff task');
 state.detail.workItems=state.detail.workItems.map(work=>({...work,status:'done',readiness:'accepted'}));await openGenerated(page,state);await page.getByRole('tab',{name:/^Review & delivery/}).click();await page.getByRole('button',{name:'Create client invitation',exact:true}).click();await page.getByLabel('Client’s Coatria account ID',{exact:true}).fill(clientId);await page.getByRole('checkbox',{name:/I confirmed this exact account/}).check();await page.getByRole('button',{name:'Review invitation',exact:true}).click();await expect(page.locator('form')).toContainText(clientId);await expect(page.locator('form')).toContainText('Exact expiry');
 await page.getByRole('button',{name:'Create invitation',exact:true}).click();await expect(page.getByRole('region',{name:'Client delivery portal'}).getByRole('alert')).toContainText('Synthetic uncertain');await page.getByRole('button',{name:'Create invitation',exact:true}).click();await expect(page.getByRole('button',{name:'Copy invitation',exact:true})).toBeVisible();const writes=state.writes.filter(write=>write.path.endsWith('/client-deliveries'));expect(writes[0].body).toEqual(writes[1].body);await expect(page.getByText('Not transferred',{exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});await noOverflow(page);await page.screenshot({path:testInfo.outputPath('generated-client-invitation-mobile.png'),fullPage:true});
 state.detail.project.gates.client_acceptance={decision:'approved',note:'The actual external account acknowledged this package.',recordedBy:clientId,at:date,source:'authenticated_external_client',clientDeliveryId:shareId,clientReceiptId:uuid(94),packageSha256:f.share.packageSha256};state.detail.project.status='delivered';await openGenerated(page,state);await expect(page.getByRole('region',{name:'Authenticated client response'})).toContainText('designated client acknowledged');await page.getByText('Authenticated response provenance',{exact:true}).click();await expect(page.getByRole('region',{name:'Authenticated client response'})).toContainText(clientId);await expect(page.getByRole('button',{name:'Record client acceptance',exact:true})).toHaveCount(0);expect(state.unexpected).toEqual([]);
});

for(const kind of ['image','video','audio'] as const)test(`${kind} client verifies download bytes and responds separately`,async({page},testInfo)=>{
 const f=portalFixture(kind,kind==='image'?Buffer.alloc(GENERATED_CLIENT_PART_BYTES+31,7):bytes);await page.addInitScript(()=>Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true}));await openPortal(page,f);
 await expect(page.getByRole('region',{name:'Package files'})).toContainText(kind);const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download verified file',exact:true}).click();const downloaded=await pending;expect(await readFile((await downloaded.path())!)).toEqual(f.payload);await expect(page.getByRole('status')).toContainText('does not acknowledge');expect(f.responses).toHaveLength(0);expect(f.accessCalls).toHaveLength(1);expect(f.ranges).toEqual(kind==='image'?[`bytes=0-${GENERATED_CLIENT_PART_BYTES-1}`,`bytes=${GENERATED_CLIENT_PART_BYTES}-${f.file.bytes-1}`]:[`bytes=0-${f.file.bytes-1}`]);expect(new Set(f.rangeAuthorizations).size).toBe(1);
 await page.getByLabel('Note to the studio',{exact:true}).fill('Reviewed and acknowledged this exact synthetic package.');await page.getByRole('checkbox',{name:/I am responding as the intended client/}).check();await page.getByRole('button',{name:'Record acknowledgement',exact:true}).click();await expect(page.getByRole('heading',{name:'Your response is on record.',exact:true})).toBeVisible();expect(f.responses).toHaveLength(1);expect(f.responses[0].decision).toBe('acknowledged');
 await page.screenshot({path:testInfo.outputPath(kind+'-client-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await noOverflow(page);await page.screenshot({path:testInfo.outputPath(kind+'-client-mobile.png'),fullPage:true});expect(f.unexpected).toEqual([]);
});

test('range renewal shares one logical receipt and same-length tamper prevents disk commit',async({page})=>{
 const f=portalFixture('image',Buffer.alloc(GENERATED_CLIENT_PART_BYTES+31,7));f.tamper=true;f.advanceFirstRange=true;await page.addInitScript(()=>{const events:string[]=[];let elapsed=0;const now=performance.now.bind(performance);Object.defineProperty(performance,'now',{configurable:true,value:()=>now()+elapsed});(window as any).advanceGrantClock=()=>{elapsed+=30_000;};(window as any).saveEvents=events;Object.defineProperty(window,'showSaveFilePicker',{configurable:true,value:async()=>({createWritable:async()=>({async write(){events.push('write');},async close(){events.push('close');},async abort(){events.push('abort');}})})});});await openPortal(page,f);await page.getByRole('button',{name:'Download verified file',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'checksum differs'})).toBeVisible();expect(f.accessCalls).toHaveLength(2);expect(f.accessCalls[0]).toEqual(f.accessCalls[1]);expect(f.ranges).toHaveLength(2);expect(new Set(f.rangeAuthorizations).size).toBe(2);const events=await page.evaluate(()=>(window as any).saveEvents);expect(events).toContain('abort');expect(events).not.toContain('close');expect(f.responses).toHaveLength(0);
});

test('mismatched exact version blocks transport and wrong client receives no file metadata',async({page})=>{
 const f=portalFixture();f.mismatch=true;await page.addInitScript(()=>Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true}));await openPortal(page,f);await page.getByRole('button',{name:'Download verified file',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'does not match'})).toBeVisible();expect(f.ranges).toHaveLength(0);
 f.userId=uuid(95);await page.evaluate(()=>window.dispatchEvent(new Event('coatria:session-changed')));await expect(page.getByRole('alert').filter({hasText:'another account'})).toBeVisible();await expect(page.getByRole('heading',{name:'Your files',exact:true})).toHaveCount(0);
});

test('account switch during a staged range aborts the save and does not publish old account success',async({page})=>{
 const f=portalFixture();f.holdRange=true;await page.addInitScript(()=>{const events:string[]=[];(window as any).saveEvents=events;Object.defineProperty(window,'showSaveFilePicker',{configurable:true,value:async()=>({createWritable:async()=>({async write(){events.push('write');},async close(){events.push('close');},async abort(){events.push('abort');}})})});});await openPortal(page,f);await page.getByRole('button',{name:'Download verified file',exact:true}).click();await expect.poll(()=>f.rangeEntered).toBe(true);f.userId=uuid(95);await page.evaluate(()=>window.dispatchEvent(new Event('coatria:session-changed')));f.hold?.();await expect(page.getByRole('alert').filter({hasText:'another account'})).toBeVisible();await expect.poll(async()=>await page.evaluate(()=>(window as any).saveEvents)).toContain('abort');expect(await page.evaluate(()=>(window as any).saveEvents)).not.toContain('close');await expect(page.getByText(/This browser verified the exact file checksum/)).toHaveCount(0);expect(f.responses).toHaveLength(0);
});
