import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {generatedFixture,mockGenerated,openGenerated,noOverflow,ids,uuid,bytes,date,type GeneratedFixture} from './studio-generated-fixture';

test.beforeEach(({baseURL})=>{test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Synthetic fixtures require a local origin.');});
async function reviewPage(page:Page,state:GeneratedFixture){await openGenerated(page,state);await page.getByRole('tab',{name:/^Review & delivery/}).click();}
async function registration(page:Page){await page.getByRole('button',{name:'Register verified output',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('radio').check();return dialog;}

for(const kind of ['image','video','audio'] as const)test(`${kind}: register, independently review and prepare an exact internal package`,async({page},testInfo)=>{
 const state=generatedFixture(kind);await mockGenerated(page,state);await reviewPage(page,state);
 const dialog=await registration(page);await expect(dialog).toContainText(ids.version);await dialog.getByLabel('Output name',{exact:true}).fill('Approved campaign master');await dialog.getByLabel('Registration notes',{exact:true}).fill('Archive registered for independent inspection.');
 await dialog.getByRole('button',{name:'Register verified output',exact:true}).click();await expect(dialog).toHaveCount(0);
 await expect(page.getByRole('heading',{name:'Approved campaign master',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Review version',exact:true})).toHaveCount(0);
 await expect(page.getByRole('region',{name:'Registered generated outputs'})).toContainText('A different administrator must review');
 const registered=state.writes.filter(write=>write.path.endsWith('/generated-artifacts'));expect(registered).toHaveLength(1);expect(registered[0].body).toMatchObject({revision:7,workItemId:ids.work,archiveId:ids.archive,name:'Approved campaign master'});expect(Object.keys(registered[0].body).sort()).toEqual(['archiveId','clientId','name','notes','revision','workItemId']);
 // A different authorized human signs in; registration never approves their own work.
 state.user={...state.user,id:uuid(24),name:'Independent QC lead'};await reviewPage(page,state);
 await page.getByRole('button',{name:'Review version',exact:true}).click();const review=page.getByRole('dialog');
 await expect(review).toContainText('Approved target');await expect(review).toContainText(kind==='audio'?'48000 Hz':'1280 × 720');
 await expect(review.getByRole('button',{name:'Record review decision',exact:true})).toBeDisabled();await review.getByLabel('Findings & evidence',{exact:true}).fill('Inspected the actual archived file against the brief and exact technical requirements.');
 await expect(review.getByRole('button',{name:'Record review decision',exact:true})).toBeDisabled();await review.getByRole('checkbox').check();
 await page.setViewportSize({width:390,height:844});await noOverflow(page);await page.screenshot({path:testInfo.outputPath(kind+'-independent-review-mobile.png'),fullPage:true});
 await review.getByRole('button',{name:'Record review decision',exact:true}).click();await expect(review).toHaveCount(0);await expect(page.getByRole('heading',{name:'Independent review history'})).toBeVisible();
 expect(state.detail.reviews[0]).toMatchObject({artifactId:ids.artifact,decision:'approved',technicalQc:true,reviewedBy:uuid(24),specSha256:state.artifact.specSha256,manifestSha256:state.artifact.manifestSha256});
 await expect(page.getByRole('button',{name:'Prepare internal package',exact:true})).toBeDisabled();expect(state.detail.workItems[0].status).toBe('doing');
 // The work-board acceptance is separate from a review. Simulate its later server snapshot.
 state.detail.workItems=state.detail.workItems.map(work=>work.stage==='delivery'?work:{...work,status:'done',readiness:'accepted'});await reviewPage(page,state);
 await page.getByRole('button',{name:'Prepare internal package',exact:true}).click();const pack=page.getByRole('dialog');await expect(pack).toContainText(ids.version);await expect(pack).toContainText(state.artifact.file.sha256);
 await pack.getByLabel('Package name',{exact:true}).fill('Campaign internal handoff');await pack.getByLabel('Internal handoff notes',{exact:true}).fill('Exact approved master for the delivery owner. External transfer has not happened.');await expect(pack.getByRole('button',{name:'Prepare internal package',exact:true})).toBeDisabled();await pack.getByRole('checkbox').check();await pack.getByRole('button',{name:'Prepare internal package',exact:true}).click();await expect(pack).toHaveCount(0);
 await expect(page.getByText('Not transferred',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/Record client acceptance|Invite client|Create client delivery/})).toHaveCount(0);
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download package JSON',exact:true}).click();const download=await downloadPromise;const manifest=JSON.parse(await readFile((await download.path())!,'utf8'));expect(manifest.transportStatus).toBe('not_transferred');expect(manifest.artifacts[0].provenance.storageVersionId).toBe(ids.version);expect(manifest.reviewReceipts[0].reviewedBy).toBe(uuid(24));
 await noOverflow(page);await page.screenshot({path:testInfo.outputPath(kind+'-package-mobile.png'),fullPage:true});expect(state.unexpected).toEqual([]);
});

test('registration retries preserve exact source and revision after an uncertain response',async({page})=>{
 const state=generatedFixture();let attempts=0;state.handler=async(route,url)=>{if(!url.pathname.endsWith('/generated-artifacts')||route.request().method()!=='POST'||++attempts>1)return false;await route.fulfill({status:503,json:{error:'Synthetic uncertain registration.'}});return true;};
 await mockGenerated(page,state);await reviewPage(page,state);const dialog=await registration(page);await dialog.getByRole('button',{name:'Register verified output',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Synthetic uncertain registration');await expect(dialog.getByLabel('Output name',{exact:true})).toBeDisabled();await expect(dialog.getByRole('radio')).toBeDisabled();
 await dialog.getByRole('button',{name:'Retry exact registration',exact:true}).click();await expect(dialog).toHaveCount(0);const writes=state.writes.filter(write=>write.path.endsWith('/generated-artifacts'));expect(writes).toHaveLength(2);expect(writes[0].body).toEqual(writes[1].body);expect(state.detail.artifacts).toHaveLength(1);
});

test('registration reads later archive pages and rejects a mismatched exact request',async({page})=>{
 const state=generatedFixture();let loadedMore=false;state.handler=async(route,url)=>{
  if(url.pathname.endsWith('/higgsfield/archives')){if(!url.searchParams.has('after')){await route.fulfill({json:{archives:[],hasMore:true,nextAfter:uuid(90)}});return true;}expect(url.searchParams.get('after')).toBe(uuid(90));loadedMore=true;return false;}
  if(url.pathname.endsWith('/higgsfield/requests')&&url.searchParams.has('requestId')){await route.fulfill({json:{request:{id:uuid(91),projectId:ids.project,workItemId:ids.work,tool:'generate_image',status:'returned'}}});return true;}return false;
 };
 await mockGenerated(page,state);await reviewPage(page,state);await page.getByRole('button',{name:'Register verified output',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Load more archives',exact:true}).click();await expect(dialog.getByRole('radio')).toBeDisabled();await expect(dialog).toContainText('The exact generation request could not be verified');await expect(dialog.getByRole('button',{name:'Register verified output',exact:true})).toBeDisabled();expect(loadedMore).toBe(true);expect(state.writes.filter(write=>write.path.endsWith('/generated-artifacts'))).toHaveLength(0);
});

test('mismatched media can be sent back with findings but cannot be approved',async({page})=>{
 const state=generatedFixture('video');if(state.artifact.media.kind==='video')state.artifact.media.durationMs=9000;state.detail.artifacts=[state.artifact];await mockGenerated(page,state);await reviewPage(page,state);await page.getByRole('button',{name:'Review version',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Findings & evidence',{exact:true}).fill('The clip runs nine seconds against a one-second target.');await dialog.getByRole('checkbox').check();await expect(dialog.getByRole('button',{name:'Record review decision',exact:true})).toBeDisabled();await expect(dialog).toContainText('Request changes instead');await dialog.getByLabel('Review decision',{exact:true}).selectOption('changes_requested');await dialog.getByRole('checkbox').uncheck();await dialog.getByRole('button',{name:'Record review decision',exact:true}).click();await expect(dialog).toHaveCount(0);expect(state.writes.find(write=>write.path.endsWith('/reviews'))?.body).toMatchObject({decision:'changes_requested',technicalQc:false});
});

test('downloading from a completed review form never submits its decision',async({page})=>{
 const state=generatedFixture();state.detail.artifacts=[state.artifact];await page.addInitScript(()=>{Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true});});await mockGenerated(page,state);await reviewPage(page,state);await page.getByRole('button',{name:'Review version',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Findings & evidence',{exact:true}).fill('Inspected this exact version and completed the independent review.');await dialog.getByRole('checkbox').check();await expect(dialog.getByRole('button',{name:'Record review decision',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'Download exact media',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Storage is offline');expect(state.writes.filter(write=>write.path.endsWith('/reviews'))).toHaveLength(0);await expect(dialog).toBeVisible();
});

for(const owner of ['producer','agent sponsor','provider sponsor','registrar','member'] as const)test(`${owner} cannot independently approve a generated output`,async({page})=>{
 const state=generatedFixture();state.detail.artifacts=[state.artifact];if(owner==='producer')state.user.id=ids.producer;if(owner==='agent sponsor')state.artifact.source.agentSponsorId=ids.user;if(owner==='provider sponsor')state.user.id=ids.providerSponsor;if(owner==='registrar')state.user.id=ids.registrar;if(owner==='member')state.company.role='member';await mockGenerated(page,state);await reviewPage(page,state);await expect(page.getByRole('button',{name:'Review version',exact:true})).toHaveCount(0);if(owner==='member'){await expect(page.getByRole('button',{name:'Register verified output',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Prepare internal package',exact:true})).toHaveCount(0);}expect(state.writes.filter(write=>write.path.endsWith('/reviews'))).toHaveLength(0);
});

test('media downloads use the immutable version and exact file metadata; unavailable storage remains explicit',async({page,baseURL})=>{
 const state=generatedFixture();state.detail.artifacts=[state.artifact];await page.addInitScript(()=>{Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true});});await mockGenerated(page,state);await reviewPage(page,state);
 await page.getByRole('button',{name:'Download exact media',exact:true}).click();await expect(page.getByRole('region',{name:'Registered generated outputs'}).getByRole('alert')).toContainText('Storage is offline in this fixture');expect(state.writes.filter(write=>write.path.endsWith('/access'))).toHaveLength(0);
 let fetched=0;state.handler=async(route,url)=>{if(url.pathname.endsWith('/files')){await route.fulfill({json:{transfers:{available:true,gatewayOrigin:baseURL}}});return true;}if(url.pathname.endsWith('/access')){expect(url.pathname).toBe(`/api/companies/${ids.company}/studio/projects/${ids.project}/files/versions/${ids.version}/access`);await route.fulfill({json:{access:{url:`${baseURL}/v1/files/${ids.version}`,headers:{Authorization:'Bearer synthetic_test_ticket'},expiresAt:new Date(Date.now()+60_000).toISOString(),bytes:bytes.length,sha256:state.artifact.file.sha256,contentType:state.artifact.file.contentType,name:'campaign-master.png'}}});return true;}return false;};
 await page.route('**/v1/files/**',async route=>{fetched++;expect(new URL(route.request().url()).pathname).toBe('/v1/files/'+ids.version);expect(route.request().headers()['authorization']).toBe('Bearer synthetic_test_ticket');expect(route.request().headers()['cookie']).toBeUndefined();await route.fulfill({headers:{'Content-Type':'image/png','Content-Length':String(bytes.length)},body:bytes});});
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download exact media',exact:true}).click();const download=await downloadPromise;expect(await readFile((await download.path())!)).toEqual(bytes);expect(fetched).toBe(1);await expect(page.getByRole('status').filter({hasText:'Saved this exact archived file version'})).toBeVisible();
 await expect(page.getByRole('link',{name:'View manifest',exact:true})).toHaveAttribute('href',`/api/companies/${ids.company}/studio/projects/${ids.project}/generated-artifacts/${ids.artifact}/manifest`);expect(state.unexpected).toEqual([]);
});

for(const mismatch of ['version','checksum','size'] as const)test(`a download ${mismatch} mismatch is rejected before contacting storage`,async({page,baseURL})=>{
 const state=generatedFixture();state.detail.artifacts=[state.artifact];await page.addInitScript(()=>{Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true});});state.handler=async(route,url)=>{if(url.pathname.endsWith('/files')){await route.fulfill({json:{transfers:{available:true,gatewayOrigin:baseURL}}});return true;}if(url.pathname.endsWith('/access')){await route.fulfill({json:{access:{url:`${baseURL}/v1/files/${mismatch==='version'?uuid(99):ids.version}`,headers:{Authorization:'Bearer synthetic_test_ticket'},expiresAt:new Date(Date.now()+60_000).toISOString(),bytes:bytes.length+(mismatch==='size'?1:0),sha256:mismatch==='checksum'?'0'.repeat(64):state.artifact.file.sha256,contentType:state.artifact.file.contentType,name:'campaign-master.png'}}});return true;}return false;};let fetched=0;await page.route('**/v1/files/**',route=>{fetched++;return route.abort();});await mockGenerated(page,state);await reviewPage(page,state);await page.getByRole('button',{name:'Download exact media',exact:true}).click();await expect(page.getByRole('region',{name:'Registered generated outputs'}).getByRole('alert')).toContainText('does not match this registered file version');expect(fetched).toBe(0);
});

test('same-length corrupted media aborts the disk write and never reports a saved file',async({page,baseURL})=>{
 const state=generatedFixture();state.detail.artifacts=[state.artifact];await page.addInitScript(()=>{const events:string[]=[];(window as unknown as {downloadEvents:string[]}).downloadEvents=events;Object.defineProperty(window,'showSaveFilePicker',{configurable:true,value:async()=>({createWritable:async()=>({write:async()=>{events.push('write');},close:async()=>{events.push('close');},abort:async()=>{events.push('abort');}})})});});
 state.handler=async(route,url)=>{if(url.pathname.endsWith('/files')){await route.fulfill({json:{transfers:{available:true,gatewayOrigin:baseURL}}});return true;}if(url.pathname.endsWith('/access')){await route.fulfill({json:{access:{url:`${baseURL}/v1/files/${ids.version}`,headers:{Authorization:'Bearer synthetic_test_ticket'},expiresAt:new Date(Date.now()+60_000).toISOString(),bytes:bytes.length,sha256:state.artifact.file.sha256,contentType:state.artifact.file.contentType,name:'campaign-master.png'}}});return true;}return false;};
 let fetched=0;await page.route('**/v1/files/**',async route=>{fetched++;const corrupted=Buffer.from(bytes);corrupted[0]^=1;await route.fulfill({headers:{'Content-Length':String(bytes.length)},body:corrupted});});await mockGenerated(page,state);await reviewPage(page,state);await page.getByRole('button',{name:'Download exact media',exact:true}).click();await expect(page.getByRole('region',{name:'Registered generated outputs'}).getByRole('alert')).toContainText('checksum differs');const events=await page.evaluate(()=>(window as unknown as {downloadEvents:string[]}).downloadEvents);expect(events).toContain('abort');expect(events).not.toContain('close');expect(fetched).toBe(1);await expect(page.getByText(/Saved this exact archived file version/)).toHaveCount(0);
});

test('a package retry displays the same reviewed versions despite a newer project snapshot',async({page})=>{
 const state=generatedFixture();state.artifact.reviewStatus='approved';state.detail.artifacts=[state.artifact];state.detail.workItems=state.detail.workItems.map(work=>work.stage==='delivery'?work:{...work,status:'done',readiness:'accepted'});state.detail.reviews=[{id:uuid(40),contractVersion:2,artifactId:ids.artifact,decision:'approved',note:'Inspected the exact file.',technicalQc:true,reviewedBy:ids.user,createdAt:date,specSha256:state.artifact.specSha256,manifestSha256:state.artifact.manifestSha256,attestationVersion:1,technicalMatch:{matches:true,issues:[],limitations:[]}}];
 let attempts=0;state.handler=async(route,url)=>{if(!url.pathname.endsWith('/deliveries')||route.request().method()!=='POST')return false;attempts++;await route.fulfill({status:503,json:{error:'Synthetic uncertain package response.'}});return true;};await page.clock.install();await mockGenerated(page,state);await reviewPage(page,state);await page.getByRole('button',{name:'Prepare internal package',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Internal handoff notes',{exact:true}).fill('Exact campaign master for handoff.');await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Prepare internal package',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Synthetic uncertain package');
 const reads=state.reads.filter(url=>url.pathname.endsWith('/'+ids.project)).length;state.detail.project.revision++;state.detail.artifacts=[{...state.artifact,id:uuid(80),version:2,name:'Newer unreviewed output',reviewStatus:'pending',provenance:{...state.artifact.provenance,storageVersionId:uuid(81)}}];await page.clock.fastForward(10_001);await expect.poll(()=>state.reads.filter(url=>url.pathname.endsWith('/'+ids.project)).length).toBeGreaterThan(reads);
 await expect(dialog).toContainText('Campaign master · v1');await expect(dialog).toContainText(ids.version);await expect(dialog).not.toContainText('Newer unreviewed output');await expect(dialog.getByLabel('Package name',{exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'Retry exact package',exact:true}).click();await expect.poll(()=>attempts).toBe(2);const writes=state.writes.filter(write=>write.path.endsWith('/deliveries'));expect(writes[0].body).toEqual(writes[1].body);expect(writes[1].body.artifactIds).toEqual([ids.artifact]);
});
