import {test,expect,type Page,type Route} from '@playwright/test';
import type {Workspace,LayoutItem} from '../../src/lib/client';
import {OFFICE_50_PRESET} from '../../src/lib/office-presets';
import type {ConnectionReport} from '../../src/lib/office-simulation';

// These are UI/wiring tests, not a rendering benchmark. The actual OfficeScene
// React wrapper receives a small runtime spy; separate tests load paid GLBs.
const user={id:'10000000-0000-4000-8000-000000000191',name:'Lab Reviewer',email:'lab@example.invalid',roleTitle:'Administrator',avatarColor:'#617e54',avatarId:null};
const company={id:'20000000-0000-4000-8000-000000000191',name:'Lab Fixture Studio',slug:'lab-fixture',template:'blank',role:'owner'};
const copy=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const json=(route:Route,data:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGPoXdjyHwAGIwKyeWvUQwAAAABJRU5ErkJggg==','base64');
const button=(page:Page,name:string)=>page.getByRole('button',{name,exact:true});
const field=(page:Page,name:string)=>page.getByLabel(name,{exact:true});
const tab=(page:Page,name:string)=>page.getByRole('tab',{name,exact:true});
const progress=(page:Page)=>page.getByRole('progressbar',{name:'Visual test progress'});
const metric=(page:Page,label:string)=>page.getByText(label,{exact:true}).locator('..').locator('strong');
async function scene(page:Page){return page.evaluate(()=>(window as any).__labScene.current?.latest);}
async function runtime(page:Page){await page.addInitScript(()=>{
 const state={current:null as any,mounts:[] as any[],diagnosticOverrides:{} as any};(window as any).__labScene=state;
 (window as any).CoatriaOfficeRuntime={createCharacterLibrary:()=>({dispose(){},loadCharacter:async()=>{throw new Error('Not used by the UI runtime spy.');}}),createOfficeAssetLibrary:()=>({dispose(){},loadAsset:async()=>{throw new Error('Not used by the UI runtime spy.');}}),mount(host:HTMLElement,options:any){
  const canvas=document.createElement('canvas');canvas.style.cssText='display:block;width:100%;height:360px';canvas.dataset.testid='lab-runtime-canvas';host.replaceChildren(canvas);const entry={options,latest:options,disposed:false,resets:0,selectedId:null as string|null};state.current=entry;state.mounts.push(entry);
  return {dispose(){entry.disposed=true;canvas.remove();},updateSnapshot(snapshot:any){entry.latest={...entry.latest,...snapshot};},selectEntity(id:string){entry.selectedId=id;return true;},resetPerformance(){entry.resets++;},get diagnostics(){return {position:entry.options.state.spatialPosition||{x:0,z:3},performance:{state:'active',fps:60,sampleCount:60,renderedSampleCount:60,frameMs:{p50:16,p95:18,max:20},drawCalls:100,triangles:50000},resources:{loadedCharacterModels:entry.latest.presence.length},animation:{fullRateHumans:12},officeAssets:entry.options.layout.map((item:any)=>({id:item.id,assetId:item.assetId,status:'ready',modelLoaded:true})),...state.diagnosticOverrides};}};
 }};
 });}
async function fixture(page:Page,role='owner'){
 await runtime(page);const data:Workspace={company:{...company,role},members:[{...user,userId:user.id,role}],rooms:[],agents:[],tasks:[],messages:[],presence:[],activity:[],drives:[],openings:[],applications:[],layout:[],floor:{width:20,depth:16},layoutRevision:0};const requests:{path:string;method:string;body:any}[]=[];
 await page.route('**/api/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname,method=request.method(),body=request.postData()?request.postDataJSON():null;requests.push({path,method,body});
  if(path==='/api/session')return json(route,{user,companies:[data.company],configured:true});
  if(path===`/api/companies/${company.id}/workspace`)return json(route,data);
  if(path===`/api/companies/${company.id}/presence`)return json(route,{presence:data.presence});
  if(/^\/api\/office-assets\/[^/]+\/(preview|plan)$/.test(path))return route.fulfill({status:200,contentType:'image/png',body:png});
  if(path===`/api/companies/${company.id}/layout`&&method==='PATCH'){data.layout=copy(body.layout);data.floor=copy(body.floor);data.layoutRevision=(data.layoutRevision||0)+1;return json(route,{layout:data.layout,floor:data.floor,layoutRevision:data.layoutRevision});}
  return json(route,{error:'Unexpected test-lab fixture request.'},501);
 });return {data,requests};
}
async function clock(page:Page){await page.clock.install({time:new Date('2026-09-10T12:00:00Z')});await page.clock.pauseAt(new Date('2026-09-10T12:00:01Z'));}
async function visibility(page:Page,visible:boolean){await page.evaluate(value=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>!value});Object.defineProperty(document,'visibilityState',{configurable:true,get:()=>value?'visible':'hidden'});document.dispatchEvent(new Event('visibilitychange'));},visible);}
const validReport:ConnectionReport={schemaVersion:1,kind:'coatria-connections',generatedAt:'2026-09-10T12:00:00Z',summary:{clients:50,durationSeconds:60,requests:2500,errorRate:0,p50Ms:12,p95Ms:45,maxMs:90,requestsPerSecond:41.7,bytesReceived:100000,passed:true,unexpectedErrors:0},checks:[{id:'presence',label:'Fifty sessions receive shared presence',passed:true,detail:'Isolated fixture result.'}],environment:{applicationMode:'production',database:'PostgreSQL',isolated:true,origin:'http://127.0.0.1:4180',databasePoolMax:10,limitations:['Local network only; no global latency claim.']},cleanup:{verified:true,remainingUsers:0,remainingCompanies:0}};
async function importFile(page:Page,value:unknown){await field(page,'Import connection report').setInputFiles({name:'connection-report.json',mimeType:'application/json',buffer:Buffer.from(typeof value==='string'?value:JSON.stringify(value))});}
async function visualReport(page:Page){const pending=page.waitForEvent('download');await button(page,'Export visual report').click();const stream=await (await pending).createReadStream();expect(stream).not.toBeNull();const chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
test.beforeEach(({baseURL})=>{test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'Test-lab fixtures only run on a loopback origin.');});

for(const role of ['owner','admin'])test(`${role} can open the separate test lab with fifty local identities`,async({page})=>{
 const state=await fixture(page,role);await page.goto('/#tester');await expect(button(page,'Test lab')).toBeVisible();await expect(page.getByRole('heading',{name:'Make room for fifty.',exact:true})).toBeVisible();await expect.poll(async()=>(await scene(page))?.members.length).toBe(50);const current=await scene(page);expect(current.layout).toHaveLength(148);expect(current.floor).toEqual({width:30,depth:20});expect(current.members[0].userId).toBe(user.id);expect(current.members.slice(1).every((member:any)=>member.userId.startsWith('lab-person-'))).toBe(true);await page.evaluate(()=>(window as any).__labScene.current.options.onMove({x:8,z:7}));
 expect(state.requests.filter(request=>request.method!=='GET').every(request=>request.path===`/api/companies/${company.id}/presence`)).toBe(true);expect(state.requests.some(request=>JSON.stringify(request).includes('lab-person-')||request.path.includes('coatria-test-lab'))).toBe(false);expect(state.data.layout).toEqual([]);
});

test('members cannot find or open the administrator test lab',async({page})=>{
 await fixture(page,'member');await page.goto('/#tester');await expect(page.getByRole('heading',{name:'The test lab is for administrators',exact:true})).toBeVisible();await expect(button(page,'Test lab')).toHaveCount(0);await expect(button(page,'Start visual test')).toHaveCount(0);await button(page,'Search navigation').click();await page.getByRole('combobox',{name:'Search navigation'}).fill('test lab');await expect(page.getByRole('option',{name:/Test lab/})).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__labScene.mounts.length)).toBe(0);
});

test('test-lab seating and reactions stay local through heartbeats, movement and reset',async({page})=>{
 await clock(page);const state=await fixture(page);await page.goto('/#tester');await expect.poll(async()=>(await scene(page))?.members.length).toBe(50);
 const seated=await page.evaluate(async()=>{const options=(window as any).__labScene.current.options;return options.onInteraction({seatId:options.seats[0].id});});
 expect(seated.seatId).toBeTruthy();await expect.poll(async()=>(await scene(page)).presence.find((row:any)=>row.userId===user.id).seatId).toBe(seated.seatId);
 await page.clock.runFor(16000);expect((await scene(page)).presence.find((row:any)=>row.userId===user.id).seatId).toBe(seated.seatId);
 await page.evaluate(()=>{const options=(window as any).__labScene.current.options;options.onMove({x:8,z:7,motionMode:'run',seatId:null});});
 await expect.poll(async()=>(await scene(page)).presence.find((row:any)=>row.userId===user.id).seatId).toBe(null);
 await page.evaluate(()=>(window as any).__labScene.current.options.onInteraction({interaction:{type:'reaction',value:'heart'}}));
 expect((await scene(page)).presence.find((row:any)=>row.userId===user.id).interaction.value).toBe('heart');
 await button(page,'Reset visual test').click();await expect.poll(async()=>(await scene(page)).presence.find((row:any)=>row.userId===user.id).interaction).toBeUndefined();
 expect(state.requests.some(request=>request.body?.interaction||request.body?.seatId||request.path.includes('coatria-test-lab')||JSON.stringify(request.body).includes('lab-person-'))).toBe(false);
});

test('visual controls start, pause, resume and reset without writing simulated identities',async({page})=>{
 await clock(page);const state=await fixture(page);await page.goto('/#tester');await expect.poll(async()=>(await scene(page))?.members.length).toBe(50);await button(page,'Start visual test').click();for(const name of ['Test people','Scenario','Run length'])await expect(field(page,name)).toBeDisabled();await page.clock.runFor(12500);await expect(progress(page)).toHaveAttribute('value',/1[2-3](\.\d+)?/);await button(page,'Pause test').click();const paused=await progress(page).getAttribute('value');await page.clock.runFor(5000);await expect(progress(page)).toHaveAttribute('value',paused!);await button(page,'Resume test').click();await page.clock.runFor(3000);expect(Number(await progress(page).getAttribute('value'))).toBeGreaterThan(Number(paused)+2);await button(page,'Reset visual test').click();await expect(progress(page)).toHaveAttribute('value','0');await expect(button(page,'Start visual test')).toBeVisible();await expect(button(page,'Export visual report')).toBeDisabled();await field(page,'Test people').selectOption('25');await expect.poll(async()=>(await scene(page))?.members.length).toBe(25);
 expect(state.requests.filter(request=>request.method!=='GET').every(request=>request.path===`/api/companies/${company.id}/presence`)).toBe(true);expect(state.requests.some(request=>JSON.stringify(request).includes('lab-person-'))).toBe(false);
});

test('disconnect-and-return changes local presence and hidden tabs pause the measurement clock',async({page})=>{
 await clock(page);await fixture(page);await page.goto('/#tester');await field(page,'Scenario').selectOption('reconnect');await button(page,'Start visual test').click();await page.clock.runFor(20500);await expect(metric(page,'People in the scene')).toHaveText('41');await expect.poll(async()=>(await scene(page))?.presence.length).toBe(41);await visibility(page,false);await expect(button(page,'Resume test')).toBeVisible();const paused=await progress(page).getAttribute('value');await page.clock.runFor(15000);await expect(progress(page)).toHaveAttribute('value',paused!);await expect(page.getByText('Paused when the tab was hidden. Resume to continue measuring visible frames.',{exact:true})).toBeVisible();await visibility(page,true);await button(page,'Resume test').click();await page.clock.runFor(10500);await expect(metric(page,'People in the scene')).toHaveText('50');await expect.poll(async()=>(await scene(page))?.presence.length).toBe(50);
});

test('paused simulated people stay fresh and the roster and tabs work with keyboard controls',async({page})=>{
 await clock(page);await fixture(page);await page.goto('/#tester');await expect.poll(async()=>(await scene(page))?.presence.length).toBe(50);const before=Date.parse((await scene(page)).presence[0].updatedAt);await page.clock.runFor(46000);expect(Date.parse((await scene(page)).presence[0].updatedAt)).toBeGreaterThan(before+30000);await expect(progress(page)).toHaveAttribute('value','0');await page.getByText('Test people · accessible list (50)',{exact:true}).click();await field(page,'Find a test teammate').fill('Taylor');const person=page.getByRole('button',{name:/Taylor · 04/});await person.focus();await page.keyboard.press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).__labScene.current.selectedId)).toBe('lab-person-3');await expect(page.getByText('Taylor · 04 selected · simulated teammate',{exact:true})).toBeVisible();await tab(page,'Visual test').focus();await page.keyboard.press('ArrowRight');await expect(tab(page,'The 50-person plan')).toBeFocused();await expect(tab(page,'The 50-person plan')).toHaveAttribute('aria-selected','true');await page.keyboard.press('End');await expect(tab(page,'Connection results')).toBeFocused();await expect(tab(page,'Connection results')).toHaveAttribute('aria-selected','true');await page.keyboard.press('Home');await expect(tab(page,'Visual test')).toBeFocused();
});

for(const missing of ['characters','furniture'] as const)test(`a fast run with missing ${missing} cannot receive or export a successful visual verdict`,async({page})=>{
 await clock(page);await fixture(page);await page.goto('/#tester');await expect.poll(async()=>(await scene(page))?.members.length).toBe(50);await page.evaluate(kind=>{const state=(window as any).__labScene;state.diagnosticOverrides=kind==='characters'?{resources:{loadedCharacterModels:0}}:{officeAssets:state.current.options.layout.map((item:any,index:number)=>({id:item.id,assetId:item.assetId,status:index?'ready':'failed',modelLoaded:index!==0}))};},missing);await field(page,'Run length').selectOption('30');await button(page,'Start visual test').click();await page.clock.runFor(30500);await expect(page.getByRole('heading',{name:'Run complete',exact:true})).toBeVisible();await expect(button(page,'Export visual report')).toBeEnabled();await expect(page.getByText('Meets the visual target on this device.',{exact:true})).toHaveCount(0);const report=await visualReport(page);expect(report.summary.assetsComplete).toBe(false);expect(report.summary.meetsVisualTarget).toBe(false);
});

test('a complete fast UI-fixture run exports its qualification and measurement limitations',async({page})=>{
 await clock(page);await fixture(page);await page.goto('/#tester');await expect.poll(async()=>(await scene(page))?.members.length).toBe(50);await field(page,'Run length').selectOption('30');await button(page,'Start visual test').click();await page.clock.runFor(30500);await expect(page.getByText('Meets the visual target on this device.',{exact:true})).toBeVisible();const report=await visualReport(page);expect(report).toMatchObject({schemaVersion:1,kind:'coatria-visual',people:50,complete:true,warmupSeconds:10});expect(report.summary.assetsComplete).toBe(true);expect(report.summary.meetsVisualTarget).toBe(true);expect(report.summary.samples).toBeGreaterThanOrEqual(5);expect(report.limitations.join(' ')).toContain('no server load or network latency measurement');
});

test('connection reports validate their format and file size while rendering imported values as text',async({page})=>{
 const state=await fixture(page);await page.goto('/#tester');await tab(page,'Connection results').click();await importFile(page,validReport);await expect(page.getByText('Checks passed',{exact:true})).toBeVisible();await expect(metric(page,'Authenticated sessions')).toHaveText('50');await expect(page.getByText(validReport.checks[0].label,{exact:true})).toBeVisible();await expect(page.getByText('Fixture cleanup: verified.',{exact:true})).toBeVisible();await button(page,'Clear report').click();await importFile(page,'{"broken":');await expect(page.locator('main').getByRole('alert')).toBeVisible();await expect(page.getByText('Checks passed',{exact:true})).toHaveCount(0);
 await importFile(page,{...validReport,summary:{...validReport.summary,clients:101}});await expect(page.locator('main').getByRole('alert')).toHaveText('This file does not match the supported connection-test report format.');await field(page,'Import connection report').setInputFiles({name:'too-large.json',mimeType:'application/json',buffer:Buffer.alloc(1024*1024+1,32)});await expect(page.locator('main').getByRole('alert')).toHaveText('Choose a JSON report smaller than 1 MB.');
 const label='<img src=x onerror="window.reportInjected=true">';await importFile(page,{...validReport,checks:[{...validReport.checks[0],label}]});await expect(page.getByText(label,{exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).reportInjected)).toBeUndefined();expect(state.requests.filter(request=>request.method!=='GET').every(request=>request.path.endsWith('/presence'))).toBe(true);
});

test('the plan and all test-lab views fit a390px screen with usable controls',async({page})=>{
 await page.setViewportSize({width:390,height:844});await fixture(page);await page.goto('/#tester');for(const label of ['Test people','Scenario','Run length']){await expect(field(page,label)).toBeVisible();expect(await field(page,label).evaluate(element=>parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(16);}for(const label of ['Visual test','The 50-person plan','Connection results']){await tab(page,label).click();await expect(tab(page,label)).toHaveAttribute('aria-selected','true');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}await tab(page,'The 50-person plan').click();const diagram=page.getByRole('img',{name:'50-person office plan with five team neighborhoods, a project lounge, and shared commons'});await expect(diagram).toBeVisible();expect(await diagram.locator('rect').count()).toBe(150);await expect(page.getByText('50 dedicated workstations',{exact:true})).toBeVisible();
});

test('the furnished template opens as an undoable draft and only Save publishes its148 objects',async({page})=>{
 const state=await fixture(page);await page.goto('/#layout');await button(page,'Office templates').click();const dialog=page.getByRole('dialog',{name:'Office templates',exact:true});await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:'Use 50-person studio',exact:true}).click();await expect(page.locator('[data-object-id]')).toHaveCount(148);await expect(field(page,'Floor width (m)')).toHaveValue('30');await expect(field(page,'Floor depth (m)')).toHaveValue('20');expect(state.requests.filter(request=>request.method==='PATCH')).toHaveLength(0);await button(page,'Undo').click();await expect(page.locator('[data-object-id]')).toHaveCount(0);await expect(field(page,'Floor width (m)')).toHaveValue('20');await button(page,'Redo').click();await button(page,'Save shared floor plan').click();await expect(page.getByText('Shared floor plan is up to date',{exact:true})).toBeVisible();const writes=state.requests.filter(request=>request.method==='PATCH');expect(writes).toHaveLength(1);expect(writes[0].body).toEqual({layout:OFFICE_50_PRESET.layout,floor:OFFICE_50_PRESET.floor,revision:0});await page.reload();await expect(page.locator('[data-object-id]')).toHaveCount(148);expect(state.data.layoutRevision).toBe(1);
});
