import {test,expect} from '@playwright/test';

test('a person creates a real workplace, saves work and keeps a private skill',async({page,context,baseURL})=>{
  test.skip(!baseURL||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname),'This fixture runs only against the local development service.');
  const suffix=Date.now().toString(36),name='Alex Coatria QA',email=`alex-${suffix}@example.invalid`;
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/');
  await page.getByLabel('Full name',{exact:true}).fill(name);
  await page.getByLabel('Email address',{exact:true}).fill(email);
  await page.getByLabel('Password',{exact:false}).fill(`Coatria QA passphrase ${suffix}`);
  await page.getByRole('button',{name:'Create your account',exact:true}).click();
  await page.getByLabel('Company name',{exact:true}).fill('Coatria QA Studio');
  await page.getByLabel('Workspace address',{exact:false}).fill(`qa-${suffix}`);
  await page.getByRole('button',{name:'Choose your space',exact:true}).click();
  await page.getByRole('button',{name:'Create your workplace',exact:true}).click();
  await expect(page.locator('canvas')).toBeVisible();
  await expect(page.getByRole('heading',{name:'Welcome in, Alex.',exact:true})).toBeVisible();
  const session=await (await context.request.get('/api/session')).json();
  expect(session.user.name).toBe(name);expect(session.companies).toHaveLength(1);
  const companyId=session.companies[0].id;
  const workspace=await (await context.request.get(`/api/companies/${companyId}/workspace`)).json();
  expect(workspace.members).toHaveLength(1);expect(workspace.agents).toHaveLength(0);expect(workspace.rooms).toHaveLength(4);
  await page.getByRole('button',{name:'Work board',exact:true}).click();
  await page.getByRole('button',{name:'Create a task',exact:true}).click();
  await page.getByLabel('Task title',{exact:true}).fill('Review the first office experience');
  await page.getByLabel('Description / acceptance criteria',{exact:true}).fill('Walk into the office and verify that changes persist after reload.');
  await page.getByRole('button',{name:'Create task',exact:true}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button',{name:'Close dialog',exact:true}).click();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Review the first office experience',exact:true})).toBeVisible();
  await page.getByRole('button',{name:/^My skill vault/}).click();
  await page.getByRole('button',{name:'Add a skill',exact:true}).click();
  await page.getByLabel('Skill title',{exact:true}).fill('My review checklist');
  await page.getByLabel('Short description',{exact:true}).fill('A method I own.');
  await page.getByLabel('Instructions, process or knowledge',{exact:true}).fill('Define the outcome, inspect the artifact, verify the result.');
  await page.getByRole('button',{name:'Save to my vault',exact:true}).click();
  await expect(page.getByRole('heading',{name:'My review checklist',exact:true})).toBeVisible();
  const exported=await (await context.request.get('/api/vault/export')).json();
  expect(exported.skills.some((s:{title:string})=>s.title==='My review checklist')).toBeTruthy();
  expect(exported).not.toHaveProperty('company');
  await page.getByRole('button',{name:'The office',exact:true}).click();
  await expect(page.locator('canvas')).toBeVisible();
  await page.screenshot({path:'test-results/coatria-office-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'test-results/coatria-office-mobile.png',fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);
  expect(overflow).toBe(false);expect(errors).toEqual([]);
});
