/** Synthetic retained identities exercise filesystem/control semantics only;
 * these fixtures are not installed-host or real decoder qualification evidence. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,mkdir,readFile,readdir,rm,unlink,writeFile,link,symlink,rename,lstat,chmod,chown} from 'node:fs/promises';
import {join,dirname,basename,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn,spawnSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {setTimeout as delay} from 'node:timers/promises';
import {createImagePreparationEnrollmentStore,withImagePreparationEnrollmentLock,makeImagePreparationEnrollmentIntent,assertImagePreparationEnrollmentPending,executeImagePreparationHostEnrollment,enrollmentBytesHash as hash,imagePreparationEnrollmentRequestFromHost,imagePreparationEnrollmentTokenHash,ImagePreparationHostEnrollmentError} from '../scripts/hosting/image-preparation-host-enrollment.mjs';
import {deriveImagePreparationRunnerConfiguration,imagePreparationRunnerConfigurationHash,parseImagePreparationRunnerToken} from '../scripts/hosting/image-preparation-runner-configuration.mjs';
import {imagePreparationEnrollmentHash} from '../src/lib/project-image-preparation-enrollment-contract.mjs';
import {IMAGE_PREPARATION_RECIPE_HASH} from '../src/lib/higgsfield-image-preparation';
const json=(v:unknown)=>Buffer.from(JSON.stringify(v,null,2)+'\n');
function fixture(now=Date.now()){
 const serviceId=randomUUID(),companyId=randomUUID(),projectId=randomUUID(),bundleSha256='a'.repeat(64),release='/var/lib/coatria-image-preparation-releases/'+bundleSha256;
 const host={version:1 as const,bundleSha256,commit:'b'.repeat(40),tree:'c'.repeat(40),release,closureSha256:'d'.repeat(64),recipeSha256:IMAGE_PREPARATION_RECIPE_HASH,uid:65534,gid:65534,scope:{serviceId,companyId,projectIds:[projectId],origin:'https://coatria.example',location:'Synthetic isolated Linux host',expiresAt:new Date(now+30*60*1000).toISOString(),gateways:[{projectId,origin:'https://gateway.example'}]},profiles:{real:{profilePath:`/etc/coatria-image-preparation/${serviceId}/real.json`,expectedProfileSha256:'e'.repeat(64)},conformance:{profilePath:`/etc/coatria-image-preparation/${serviceId}/conformance.json`,expectedProfileSha256:'f'.repeat(64)}},worker:{path:release+'/worker/runtime.mjs',sha256:'1'.repeat(64)},qualifier:{path:release+'/qualifier/runtime.mjs',sha256:'2'.repeat(64)},node:{path:release+'/runtime/node',sha256:'3'.repeat(64)},units:Object.fromEntries(['qualify','preflight','worker'].map(mode=>[mode,{name:`coatria-image-preparation-${serviceId}-${mode}.service`,sha256:hash(mode)}]))} as any;
 const hostBytes=json(host),configuration=deriveImagePreparationRunnerConfiguration(host,hash(hostBytes),'0'.repeat(64));
 const receipt={version:1,kind:'coatria-image-preparation-qualification-v1',serviceId,companyId,projectIds:[projectId],sourceCommit:host.commit,sourceTree:host.tree,bundleSha256,releaseSha256:host.worker.sha256,closureSha256:host.closureSha256,recipeSha256:host.recipeSha256,qualifierSha256:host.qualifier.sha256,configurationSha256:imagePreparationRunnerConfigurationHash(configuration),hostConfigurationSha256:hash(hostBytes),profileSha256:host.profiles.real.expectedProfileSha256,conformanceProfileSha256:host.profiles.conformance.expectedProfileSha256,bootId:randomUUID(),uid:host.uid,gid:host.gid,expiresAt:host.scope.expiresAt,units:host.units,qualifierInvocationId:'4'.repeat(32),serviceRoot:'/sys/fs/cgroup/system.slice/'+host.units.qualify.name,evidenceSha256:'5'.repeat(64),reportSha256:'6'.repeat(64),acceptedAt:new Date(now-1000).toISOString(),qualified:true,checks:{isolation:true,resourceLimits:true,descendantCleanup:true,imagePreparation:true}};
 const receiptBytes=json(receipt),qualified={host,hostBytes,receipt,receiptBytes,qualificationSha256:hash(receiptBytes)},scope={version:1,enrolledBy:randomUUID(),enroller:{role:'owner',joinedAt:new Date(now-10000).toISOString().replace(/\.(\d{3})Z$/,'.$1000Z')},projects:[{projectId,projectRevision:1,storageBindingId:randomUUID(),storageBindingRevision:1,storageConnectionId:randomUUID(),storageConnectionRevision:1,gateway:{bindingId:randomUUID(),provisionId:randomUUID(),configurationSha256:'7'.repeat(64),origin:'https://gateway.example',expiresAt:host.scope.expiresAt}}]},token='ips_'+'x'.repeat(43),scopeSha256=hash(json(scope)),registrarBundleSha256='8'.repeat(64),requestId=randomUUID();
 const request=imagePreparationEnrollmentRequestFromHost(qualified,scope,requestId,imagePreparationEnrollmentTokenHash(token),{allowExpired:true});
 const intent=now<Date.now()-60000?{version:1,kind:'coatria-image-preparation-enrollment-intent',request,requestHash:imagePreparationEnrollmentHash(request),tokenHash:request.tokenHash,hostConfigurationSha256:hash(hostBytes),qualificationSha256:hash(receiptBytes),configurationSha256:receipt.configurationSha256,scopeSha256,registrarBundleSha256,createdAt:new Date(now).toISOString()}:makeImagePreparationEnrollmentIntent(qualified,scope,{requestId,token,scopeSha256,registrarBundleSha256});
 return {qualified,scope,token,intent,scopeSha256,registrarBundleSha256,configuration};
}
async function prepared(t:test.TestContext,options:{old?:boolean,root?:string,trusted?:boolean}={}){const root=options.root??await mkdtemp(join(tmpdir(),'coatria-image-enrollment-'));if(!options.root)t.after(()=>{assert.equal(dirname(resolve(root)),resolve(tmpdir()));assert(basename(root).startsWith('coatria-image-enrollment-'));return rm(resolve(root),{recursive:true,force:true});});const f=fixture(options.old?Date.now()-3600000:undefined),store=createImagePreparationEnrollmentStore(root,{trusted:options.trusted??false}),pending=await store.prepare({intent:f.intent,token:f.token,hostBytes:f.qualified.hostBytes,receiptBytes:f.qualified.receiptBytes});assert(pending);return {...f,root,store,pending};}
type Fixture=Awaited<ReturnType<typeof prepared>>;
const outcome=(f:Fixture,status:'absent'|'committed',active=false)=>({status,active,serviceId:f.intent.request.serviceId,requestId:f.intent.request.requestId,requestHash:f.intent.requestHash});
const run=(f:Fixture,overrides:Record<string,unknown>={})=>executeImagePreparationHostEnrollment({mode:'reconcile',store:f.store,pending:f.pending,verifyLocal:async()=>{},enroll:async()=>{throw Error('No synthetic SQL submission expected');},reconcile:async()=>outcome(f,'committed',true),...overrides});

test('request/intent pin the exact host, accepted receipt, finite scope and derived runner configuration',()=>{
 const f=fixture();assert.equal(f.intent.request.tokenHash,imagePreparationEnrollmentTokenHash(f.token));assert.equal(f.intent.request.qualificationSha256,hash(f.qualified.receiptBytes));assert.equal(f.intent.configurationSha256,imagePreparationRunnerConfigurationHash(f.configuration));
 for(const mutate of [(s:typeof f.scope)=>{s.projects[0].projectId=randomUUID();},(s:typeof f.scope)=>{s.projects[0].gateway.origin='https://other.example';},(s:typeof f.scope)=>{Object.assign(s,{recipeSha256:'f'.repeat(64)});},(s:typeof f.scope)=>{s.enroller.joinedAt=new Date().toISOString();}]){const scope=structuredClone(f.scope);mutate(scope);assert.throws(()=>imagePreparationEnrollmentRequestFromHost(f.qualified,scope,f.intent.request.requestId,f.intent.tokenHash));}
 for(const key of ['hostBytes','receiptBytes'] as const)assert.throws(()=>imagePreparationEnrollmentRequestFromHost({...f.qualified,[key]:Buffer.concat([f.qualified[key],Buffer.from(' ')])},f.scope,f.intent.request.requestId,f.intent.tokenHash));
});
test('complete pending survives fresh store instances and exact scope/registrar pins cannot change',async t=>{
 const f=await prepared(t),again=await createImagePreparationEnrollmentStore(f.root,{trusted:false}).read();assert(again);assert.equal(again.token,f.token);assert.equal(again.submission,null);assert.equal(assertImagePreparationEnrollmentPending(again).requestId,f.intent.request.requestId);
 for(const pins of [{scopeSha256:'0'.repeat(64)},{registrarBundleSha256:'0'.repeat(64)}])assert.throws(()=>assertImagePreparationEnrollmentPending(again,pins));await assert.rejects(f.store.prepare({intent:f.intent,token:f.token,hostBytes:f.qualified.hostBytes,receiptBytes:f.qualified.receiptBytes}),/PENDING_EXISTS/);
});
test('fixed submit is durable before callback and prevents every later submission across fresh engine/store instances',async t=>{
 const f=await prepared(t);let submits=0,reads=0;
 await assert.rejects(run(f,{mode:'enroll',enroll:async()=>{submits++;assert.equal(JSON.parse(await readFile(join(f.store.root,'submit.json'),'utf8')).requestHash,f.intent.requestHash);throw Error('PRIVATE_COMMIT_TRANSPORT');},reconcile:async()=>{if(++reads===1)return outcome(f,'absent');throw Error('PRIVATE_RECONCILE_TRANSPORT');}}),/OUTCOME_UNKNOWN/);
 const retained=await readFile(join(f.store.root,'submit.json'));
 for(let n=0;n<2;n++){const store=createImagePreparationEnrollmentStore(f.root,{trusted:false}),pending=await store.read();const result=await run(f,{mode:'enroll',store,pending,verifyLocal:async()=>{assert.fail('Submitted absence needs no current local qualification');},enroll:async()=>{submits++;},reconcile:async()=>outcome(f,'absent')});assert.equal(result.credentialReady,false);assert.equal(result.status,'absent');}
 assert.equal(submits,1);assert((await readFile(join(f.store.root,'submit.json'))).equals(retained));assert.equal((await f.store.read())!.token,f.token);await assert.rejects(readFile(join(f.root,'service-token.json')));
 const text=(await Promise.all((await readdir(f.store.root)).filter(n=>n.startsWith('event-')).map(n=>readFile(join(f.store.root,n),'utf8')))).join('');assert(!text.includes(f.token));assert(!text.includes('PRIVATE_'));
});
test('lost commit acknowledgment resolves to exact active history and publishes current runner JSON without activation',async t=>{
 const f=await prepared(t);let submissions=0,reads=0,local=0;
 const result=await run(f,{mode:'enroll',verifyLocal:async()=>{local++;},enroll:async()=>{submissions++;throw Error('PRIVATE_SQL_SECRET');},reconcile:async()=>++reads===1?outcome(f,'absent'):outcome(f,'committed',true)});
 assert.equal(submissions,1);assert(reads>=4&&local>=3);assert.equal(result.credentialReady,true);assert.equal(result.workerEnabled,false);const bytes=await readFile(join(f.root,'service-token.json')),value=JSON.parse(bytes.toString());assert.equal(parseImagePreparationRunnerToken(value,f.configuration),f.token);assert(!JSON.stringify(result).includes(f.token));await assert.rejects(readFile(join(f.root,'worker-enabled')));
 const again=await run(f,{mode:'enroll',store:createImagePreparationEnrollmentStore(f.root,{trusted:false}),enroll:async()=>{submissions++;}});assert.equal(again.credentialReady,true);assert.equal(submissions,1);assert((await readFile(join(f.root,'service-token.json'))).equals(bytes));
});
test('local qualification changed while persisting the submit fence prevents SQL and permanently consumes submission',async t=>{
 const f=await prepared(t);let local=0,submits=0;await assert.rejects(run(f,{mode:'enroll',verifyLocal:async()=>{if(++local===2)throw Error('Synthetic qualification changed during fsync');},enroll:async()=>{submits++;},reconcile:async()=>outcome(f,'absent')}),/OUTCOME_UNKNOWN/);assert((await f.store.read())!.submission);assert.equal(submits,0);
 const store=createImagePreparationEnrollmentStore(f.root,{trusted:false});const result=await run(f,{mode:'enroll',store,pending:await store.read(),verifyLocal:async()=>{assert.fail();},enroll:async()=>{submits++;},reconcile:async()=>outcome(f,'absent')});assert.equal(result.status,'absent');assert.equal(submits,0);
});
test('outcome journal accepts only fixed sanitized fields and has a finite retained size',async t=>{
 const f=await prepared(t),event={version:1,kind:'outcome',requestId:f.intent.request.requestId,requestHash:f.intent.requestHash,status:'absent',active:false,reason:null,createdAt:new Date().toISOString()};await assert.rejects(f.store.recordOutcome({...event,token:f.token}));await assert.rejects(f.store.recordOutcome({...event,reason:'PRIVATE_ERROR'}));
 for(let n=0;n<256;n++)await writeFile(join(f.store.root,'event-'+randomUUID()+'.json'),json(event),{mode:0o600});await assert.rejects(f.store.recordOutcome(event),/JOURNAL_FULL/);assert.equal((await readdir(f.store.root)).filter(n=>n.startsWith('event-')).length,256);
});
test('historical reconcile works after expiry or reboot but cannot publish or submit',async t=>{
 for(const old of [true,false]){const f=await prepared(t,{old});let submits=0,reads=0;const result=await run(f,{verifyLocal:async()=>{throw Error('Synthetic reboot or changed accepted receipt');},enroll:async()=>{submits++;},reconcile:async()=>{reads++;return {...outcome(f,'committed',!old),...old?{reason:'expired'}:{}};}});assert.equal(result.status,'committed');assert.equal(result.active,false);assert.equal(result.credentialReady,false);assert.equal(submits,0);assert(reads>0);await assert.rejects(readFile(join(f.root,'service-token.json')));}
});
test('absent reconcile is read-only and foreign tuples or inconsistent authority never publish',async t=>{
 const f=await prepared(t);let submits=0;const absent=await run(f,{enroll:async()=>{submits++;},verifyLocal:async()=>{assert.fail();},reconcile:async()=>outcome(f,'absent')});assert.equal(absent.status,'absent');assert.equal(submits,0);assert.equal((await f.store.read())!.submission,null);
 for(const change of [{requestId:randomUUID()},{requestHash:'0'.repeat(64)},{serviceId:randomUUID()},{status:'absent'},{reason:'revoked'},{extra:'PRIVATE'}])await assert.rejects(run(f,{reconcile:async()=>({...outcome(f,'committed',true),...change})}),/RECONCILIATION_INVALID/);await assert.rejects(readFile(join(f.root,'service-token.json')));
});
test('fresh local and database authority after private filesystem writes prevents credential readiness',async t=>{
 for(const change of ['local','database'] as const){const f=await prepared(t);let local=0,reads=0;const result=await run(f,{verifyLocal:async()=>{if(++local===2&&change==='local')throw Error('Current boot changed during durable write');},reconcile:async()=>{reads++;return change==='database'&&reads>=3?{...outcome(f,'committed'),reason:'revoked'}:outcome(f,'committed',true);}});assert.equal(result.active,false);assert.equal(result.credentialReady,false);const state=await lstat(join(f.root,'service-token.json'));if(process.platform==='linux')assert.equal(state.mode&0o777,0o600);await assert.rejects(readFile(join(f.root,'worker-enabled')));}
});
test('partial pending, submit and publication files remain stop conditions without repair',async t=>{
 for(const name of ['token','intent.json','submit.json']){const f=await prepared(t);await writeFile(join(f.store.root,name),'{');const before=await readFile(join(f.store.root,name));await assert.rejects(f.store.read());await assert.rejects(f.store.prepare({intent:f.intent,token:f.token,hostBytes:f.qualified.hostBytes,receiptBytes:f.qualified.receiptBytes}));assert((await readFile(join(f.store.root,name))).equals(before));}
 const f=await prepared(t);await writeFile(join(f.root,'service-token.json'),'{');await assert.rejects(run(f),/CREDENTIAL_CONFLICT/);assert.equal(await readFile(join(f.root,'service-token.json'),'utf8'),'{');
});
test('hardlinks, substituted directories and mismatched complete submit fences are rejected',async t=>{
 const f=await prepared(t);await link(join(f.store.root,'token'),join(f.root,'linked'));await assert.rejects(f.store.read());await unlink(join(f.root,'linked'));await f.store.claimSubmission(f.pending);const submit=JSON.parse(await readFile(join(f.store.root,'submit.json'),'utf8'));submit.requestHash='0'.repeat(64);await writeFile(join(f.store.root,'submit.json'),json(submit));await assert.rejects(run(f,{mode:'enroll',enroll:async()=>{assert.fail();}}),/SUBMIT_INVALID/);
 const g=await prepared(t);await rename(g.store.root,join(g.root,'retained-original'));await mkdir(g.store.root);await assert.rejects(g.store.read());assert.equal(await readFile(join(g.root,'retained-original','token'),'utf8'),g.token);
});
test('symlink pending and publication substitutions never supply or overwrite a credential',{skip:process.platform==='win32'},async t=>{
 const f=await prepared(t);await unlink(join(f.store.root,'token'));await writeFile(join(f.root,'elsewhere'),f.token);await symlink(join(f.root,'elsewhere'),join(f.store.root,'token'));await assert.rejects(f.store.read());
 const g=await prepared(t);await writeFile(join(g.root,'target'),'unchanged');await symlink(join(g.root,'target'),join(g.root,'service-token.json'));await assert.rejects(run(g));assert.equal(await readFile(join(g.root,'target'),'utf8'),'unchanged');
});
test('worker activation marker blocks publication while historical inactive reconciliation stays available',async t=>{
 const f=await prepared(t);await writeFile(join(f.root,'worker-enabled'),'existing');await assert.rejects(run(f),/ACTIVATION_PRESENT/);const result=await run(f,{reconcile:async()=>({...outcome(f,'committed'),reason:'revoked'})});assert.equal(result.status,'committed');assert.equal(result.active,false);await assert.rejects(readFile(join(f.root,'service-token.json')));assert.equal(await readFile(join(f.root,'worker-enabled'),'utf8'),'existing');
});
test('post-publication journal failure is sanitized and restart acknowledges only identical bytes',async t=>{
 const f=await prepared(t);const store={...f.store,recordOutcome:async(event:any)=>{if(event.kind==='complete')throw Error('PRIVATE_FILESYSTEM_SECRET');return f.store.recordOutcome(event);}};await assert.rejects(run(f,{store}),error=>error instanceof ImagePreparationHostEnrollmentError&&error.code==='IMAGE_PREPARATION_HOST_ENROLLMENT_OUTCOME_UNKNOWN'&&!String(error).includes('PRIVATE'));
 const bytes=await readFile(join(f.root,'service-token.json'));assert.equal((await run(f,{store:createImagePreparationEnrollmentStore(f.root,{trusted:false})})).credentialReady,true);assert((await readFile(join(f.root,'service-token.json'))).equals(bytes));
});
test('publication notices config directory replacement during current-authority wait',async t=>{
 const f=await prepared(t);let moved=false;await assert.rejects(run(f,{verifyLocal:async()=>{if(!moved){moved=true;await rename(f.store.root,join(f.root,'original'));await mkdir(f.store.root);}}}));assert.equal(await readFile(join(f.root,'original','token'),'utf8'),f.token);await assert.rejects(readFile(join(f.root,'service-token.json')));
});
test('current authority lost after publication is reported inactive without claiming credential readiness',async t=>{
 const f=await prepared(t);let calls=0;const result=await run(f,{reconcile:async()=>++calls>=4?{...outcome(f,'committed'),reason:'revoked'}:outcome(f,'committed',true)});assert.equal(result.status,'committed');assert.equal(result.active,false);assert.equal(result.credentialReady,false);assert.equal(result.reason,'revoked');assert.equal(parseImagePreparationRunnerToken(JSON.parse(await readFile(join(f.root,'service-token.json'),'utf8')),f.configuration),f.token);await assert.rejects(readFile(join(f.root,'worker-enabled')));
});
test('a killed enrollment process leaves a permanent fence consumed by a fresh process on restart',{timeout:20000},async t=>{
 const f=await prepared(t),moduleUrl=pathToFileURL(join(process.cwd(),'scripts/hosting/image-preparation-host-enrollment.mjs')).href;
 const source=(first:boolean)=>`import{createImagePreparationEnrollmentStore,executeImagePreparationHostEnrollment}from${JSON.stringify(moduleUrl)};const store=createImagePreparationEnrollmentStore(${JSON.stringify(f.root)},{trusted:false}),pending=await store.read();const absent={status:'absent',active:false,serviceId:pending.intent.request.serviceId,requestId:pending.intent.request.requestId,requestHash:pending.intent.requestHash};const result=await executeImagePreparationHostEnrollment({mode:'enroll',store,pending,verifyLocal:async()=>{${first?'':'throw Error("Restart must not verify a new submission")'}},enroll:async()=>{process.send({event:'submission'});${first?'await new Promise(()=>setInterval(()=>{},1000));':'throw Error("Replacement submission forbidden")'}},reconcile:async()=>absent});process.send({event:'result',status:result.status,credentialReady:result.credentialReady},()=>process.disconnect());`;
 const child=spawn(process.execPath,['--import','tsx','--input-type=module','-e',source(true)],{stdio:['ignore','ignore','ignore','ipc'],env:{PATH:process.env.PATH,NODE_ENV:'test'}});t.after(()=>child.kill('SIGKILL'));
 const seen=new Promise<void>((res,rej)=>{child.once('message',message=>{assert.deepEqual(message,{event:'submission'});res();});child.once('error',rej);child.once('exit',()=>rej(Error('Submission process exited early')));});await Promise.race([seen,delay(5000,undefined,{ref:false}).then(()=>{throw Error('Submission callback not observed');})]);const retained=await readFile(join(f.store.root,'submit.json')),ended=new Promise<void>(res=>child.once('exit',()=>res()));child.kill('SIGKILL');await ended;
 const restart=spawn(process.execPath,['--import','tsx','--input-type=module','-e',source(false)],{stdio:['ignore','ignore','ignore','ipc'],env:{PATH:process.env.PATH,NODE_ENV:'test'}});t.after(()=>restart.kill('SIGKILL'));const messages:unknown[]=[];restart.on('message',message=>messages.push(message));const completion=new Promise<void>((res,rej)=>{restart.once('error',rej);restart.once('exit',code=>{try{assert.equal(code,0);res();}catch(error){rej(error);}});});await Promise.race([completion,delay(5000,undefined,{ref:false}).then(()=>{throw Error('Restart did not reconcile');})]);assert.deepEqual(messages,[{event:'result',status:'absent',credentialReady:false}]);assert((await readFile(join(f.store.root,'submit.json'))).equals(retained));assert.equal((await f.store.read())!.token,f.token);
});
test('Linux flock contention and SIGKILL after fsynced submit never permit a replacement submission',{skip:process.platform!=='linux',timeout:20000},async t=>{
 const f=await prepared(t),moduleUrl=pathToFileURL(join(process.cwd(),'scripts/hosting/image-preparation-host-enrollment.mjs')).href;
 const script=`import{withImagePreparationEnrollmentLock,createImagePreparationEnrollmentStore}from${JSON.stringify(moduleUrl)};await withImagePreparationEnrollmentLock(${JSON.stringify(f.root)},async()=>{const s=createImagePreparationEnrollmentStore(${JSON.stringify(f.root)},{trusted:false});await s.claimSubmission(await s.read());process.send({submitted:true});await new Promise(()=>setInterval(()=>{},1000));},{trusted:false});`;
 const child=spawn(process.execPath,['--import','tsx','--input-type=module','-e',script],{stdio:['ignore','ignore','ignore','ipc'],env:{PATH:process.env.PATH,NODE_ENV:'test'}});t.after(()=>child.kill('SIGKILL'));
 const ready=new Promise<void>((res,rej)=>{child.once('message',()=>res());child.once('error',rej);child.once('exit',()=>rej(Error('Holder exited before fence')));});await Promise.race([ready,delay(5000,undefined,{ref:false}).then(()=>{throw Error('Fence was not observed');})]);await assert.rejects(withImagePreparationEnrollmentLock(f.root,async()=>{assert.fail();},{trusted:false}),/BUSY/);const ended=new Promise<void>(res=>child.once('exit',()=>res()));child.kill('SIGKILL');await ended;
 let submits=0;await withImagePreparationEnrollmentLock(f.root,async()=>{const store=createImagePreparationEnrollmentStore(f.root,{trusted:false}),pending=await store.read();const result=await run(f,{mode:'enroll',store,pending,enroll:async()=>{submits++;},reconcile:async()=>outcome(f,'absent')});assert.equal(result.status,'absent');},{trusted:false});assert.equal(submits,0);assert((await f.store.read())!.submission);
});
test('Linux root publication has exact runner ownership, mode, no ACLs and no activation',{skip:process.platform!=='linux'||process.getuid?.()!==0,timeout:20000},async t=>{
 const f=fixture(),parent='/etc/coatria-image-preparation',root=join(parent,f.qualified.host.scope.serviceId);await mkdir(parent,{recursive:true,mode:0o755});await mkdir(root,{mode:0o750});t.after(()=>{assert.equal(dirname(resolve(root)),parent);assert.equal(basename(root),f.qualified.host.scope.serviceId);assert(/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(basename(root)));return rm(resolve(root),{recursive:true,force:true});});const store=createImagePreparationEnrollmentStore(root,{trusted:true}),pending=await store.prepare({intent:f.intent,token:f.token,hostBytes:f.qualified.hostBytes,receiptBytes:f.qualified.receiptBytes});assert(pending);const v={...f,root,store,pending};assert.equal((await run(v)).credentialReady,true);
 const path=join(root,'service-token.json'),stat=await lstat(path);assert.equal(stat.uid,0);assert.equal(stat.gid,f.qualified.host.gid);assert.equal(stat.mode&0o7777,0o640);assert.equal(stat.nlink,1);const {readImagePreparationRunnerToken}=await import('../scripts/hosting/run-image-preparation-worker.mjs');assert.equal(await readImagePreparationRunnerToken(f.configuration),f.token);
 await chmod(path,0o600);await assert.rejects(run(v));await chmod(path,0o640);await chown(path,0,0);await assert.rejects(run(v));await chown(path,0,f.qualified.host.gid);
 const acl=spawnSync('/usr/bin/setfacl',['-m','u:1:r',path]);assert.equal(acl.status,0);await assert.rejects(run(v));await assert.rejects(readFile(join(root,'worker-enabled')));
});
