import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {copyFile,link,mkdir,mkdtemp,readFile,readdir,rm,symlink,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {IMAGE_PREPARATION_RECIPE_HASH} from '../src/lib/higgsfield-image-preparation';
import {preparationServiceOrigin,preparationServiceUuid} from '../src/lib/project-image-preparation-service-protocol';
import {parseImagePreparationHostConfiguration as parseRunnerHostConfiguration} from '../scripts/hosting/image-preparation-runner-configuration.mjs';
import test from 'node:test';
import {ARCHIVE_RUNTIME_EMPTY_DIRECTORIES,archiveHostHash,parseArchiveRuntime,createArchiveEmptyDirectories,copyArchiveFiles} from '../scripts/hosting/archive-host-package.mjs';
import {IMAGE_PREPARATION_HOST_RECIPE_SHA256,IMAGE_PREPARATION_HOST_PINS,IMAGE_PREPARATION_HOST_SOURCE_FILES,parseImagePreparationHostBundle,parseImagePreparationHostScope,parseImagePreparationServiceBundle,imagePreparationHostUnit,imagePreparationHostUnitName,imagePreparationHostProfiles,imagePreparationHostInstallPlan,createImagePreparationHostConfiguration,parseImagePreparationHostConfiguration,inspectImagePreparationHostBundle} from '../scripts/hosting/image-preparation-host-package.mjs';
import {assertImagePreparationHostUnloadedUnit,assertImagePreparationHostUnitsAbsent,assertImagePreparationHostVacantBase,claimImagePreparationHostInstallation,installImagePreparationHost,readImagePreparationInstallScope} from '../scripts/hosting/install-image-preparation-host.mjs';
import {buildImagePreparationHostBundle} from '../scripts/hosting/build-image-preparation-host-bundle.mjs';
const git=(cwd:string,args:string[])=>{const r=spawnSync('git',['-c','core.autocrlf=false','-c','user.name=Reference Fixture','-c','user.email=reference@example.invalid','-C',cwd,...args],{encoding:'utf8',timeout:10000,maxBuffer:1024*1024});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};
const id='10000000-0000-4000-8000-000000000001';
const scopeInput=()=>({version:1,serviceId:id,companyId:'20000000-0000-4000-8000-000000000001',projectIds:['30000000-0000-4000-8000-000000000001'],origin:'https://coatria.example',expiresAt:new Date(Date.now()+3500000).toISOString(),location:'Synthetic offline package fixture',gateways:[{projectId:'30000000-0000-4000-8000-000000000001',origin:'https://gateway.example.invalid'}]});
async function fixture(){
 const temp=await mkdtemp(join(tmpdir(),'coatria-image-preparation-package-')),repo=join(temp,'repo'),runtime=join(temp,'runtime'),worker=join(temp,'worker'),qualifier=join(temp,'qualifier');for(const path of [repo,runtime,worker,qualifier])await mkdir(path);
 const source=new Map<string,Buffer>();for(const path of [...IMAGE_PREPARATION_HOST_SOURCE_FILES,'scripts/hosting/run-image-preparation-worker.mts','scripts/hosting/qualify-image-preparation-host.mts'])source.set(path,Buffer.from('Original synthetic offline packaging fixture: '+path+'\n'));
 source.set('package.json',Buffer.from('{"name":"reference-package-fixture"}\n'));source.set('package-lock.json',Buffer.from(JSON.stringify({lockfileVersion:3,packages:{'node_modules/esbuild':{version:'0.28.2',integrity:'sha512-b3JpZ2luYWxmaXh0dXJl'}}})+'\n'));
 for(const[path,bytes]of source){await mkdir(dirname(join(repo,path)),{recursive:true});await writeFile(join(repo,path),bytes);}git(repo,['init','--quiet']);git(repo,['add','.']);git(repo,['commit','--quiet','-m','Original offline reference package fixture']);const commit=git(repo,['rev-parse','HEAD']),tree=git(repo,['rev-parse','HEAD^{tree}']);
 const entries=[];for(const path of ['node','media-sandbox-launch','media/real/bin/ffmpeg','media/real/bin/ffprobe','media/conformance/bin/ffmpeg','media/conformance/bin/ffprobe','node_modules/tsx/package.json','node_modules/pg/package.json','node_modules/undici/index.js']){const bytes=Buffer.from(path.includes('conformance')?'Original synthetic conformance program':path+' synthetic non-runtime bytes'),mode=path.startsWith('node_modules/')?0o444:0o555;await mkdir(dirname(join(runtime,path)),{recursive:true});await writeFile(join(runtime,path),bytes);entries.push({path,bytes:bytes.length,sha256:archiveHostHash(bytes),mode});}
 await createArchiveEmptyDirectories(runtime,ARCHIVE_RUNTIME_EMPTY_DIRECTORIES);
 const rt=parseArchiveRuntime({version:1,platform:'linux-x64',pins:IMAGE_PREPARATION_HOST_PINS,sourceHashes:{launcher:archiveHostHash(source.get('scripts/hosting/media-sandbox-launch.c')!),probe:archiveHostHash(source.get('scripts/hosting/media-sandbox-probe.c')!)},packageLockSha256:archiveHostHash(source.get('package-lock.json')!),bubblewrapSha256:'a'.repeat(64),files:entries,emptyDirectories:ARCHIVE_RUNTIME_EMPTY_DIRECTORIES}),raw=JSON.stringify(rt)+'\n';await writeFile(join(runtime,'runtime-manifest.json'),raw);
 const parts:any={};for(const [service,path,entry]of [['image-preparation',worker,'scripts/hosting/run-image-preparation-worker.mts'],['image-preparation-qualification',qualifier,'scripts/hosting/qualify-image-preparation-host.mts']]){const program=Buffer.from('export const syntheticPackagingFixture = '+JSON.stringify(service)+';\n'),dependency=entries.find(f=>f.path==='node_modules/undici/index.js')!,b={version:1,kind:'coatria-trusted-service-bundle',service,sourceCommit:commit,sourceTree:tree,image:IMAGE_PREPARATION_HOST_PINS.nodeImage,nodeVersion:IMAGE_PREPARATION_HOST_PINS.nodeVersion,compiler:{name:'esbuild',version:'0.28.2',packageIntegrity:'sha512-b3JpZ2luYWxmaXh0dXJl'},packageLockSha256:rt.packageLockSha256,inputs:[{path:entry,bytes:source.get(entry)!.length,sha256:archiveHostHash(source.get(entry)!),kind:'source'},{path:dependency.path,bytes:dependency.bytes,sha256:dependency.sha256,kind:'dependency'}],runtime:{path:'runtime.mjs',bytes:program.length,sha256:archiveHostHash(program)},deployable:true,qualified:false},bytes=JSON.stringify(b,null,2)+'\n';await writeFile(join(path,'runtime.mjs'),program);await writeFile(join(path,'bundle.json'),bytes);parts[service]={bundle:b,sha256:archiveHostHash(bytes)};}
 const input={sourceRoot:repo,commit,runtimeRoot:runtime,runtimeManifestSha256:archiveHostHash(raw),workerBundlePath:worker,workerBundleSha256:parts['image-preparation'].sha256,qualifierBundlePath:qualifier,qualifierBundleSha256:parts['image-preparation-qualification'].sha256};return {temp,repo,runtime,worker,qualifier,commit,tree,source,rt,parts,input};
}
test('image preparation package copies exact Git/source/native bytes and standalone programs without node_modules or qualified claims',async t=>{
 const f=await fixture();t.after(async()=>{assert.equal(dirname(resolve(f.temp)),resolve(tmpdir()));assert.match(f.temp.split(/[\\/]/).at(-1)!,/^coatria-image-preparation-package-/);await rm(f.temp,{recursive:true,force:true});});await writeFile(join(f.repo,'src/lib/higgsfield-reference-worker.ts'),'Uncommitted source must not enter release');await writeFile(join(f.repo,'.env.private'),'Excluded synthetic private material');
 const result=await buildImagePreparationHostBundle({...f.input,output:join(f.temp,'bundle')}),bundle=await inspectImagePreparationHostBundle(result.output,result.bundleSha256,{trusted:false});assert.equal(result.qualified,false);assert.equal(result.providerCalls,false);assert.equal(result.servicesEnabled,false);assert.equal(bundle.commit,f.commit);assert.equal(bundle.tree,f.tree);assert.equal(bundle.files.some((e:{path:string})=>e.path.includes('node_modules/')||e.path.includes('.env')),false);assert.equal(bundle.runtime.files.length,6);assert.equal(bundle.files.filter((e:{path:string})=>e.path.startsWith('source/tests/fixtures/media/')).length,7);assert.notEqual(bundle.worker.bundleSha256,bundle.worker.bundle.runtime.sha256);assert.deepEqual(await readFile(join(result.output,'source/src/lib/higgsfield-reference-worker.ts')),f.source.get('src/lib/higgsfield-reference-worker.ts'));
 const target=join(f.temp,'installed-copy');await mkdir(target);await copyArchiveFiles(result.output,target,bundle.files,{emptyDirectories:bundle.emptyDirectories});await writeFile(join(target,'bundle.json'),await readFile(join(result.output,'bundle.json')));await inspectImagePreparationHostBundle(target,result.bundleSha256,{trusted:false});for(const directory of bundle.emptyDirectories)assert.deepEqual(await readdir(join(target,directory.path)),[]);
 await writeFile(join(target,'unexpected.env'),'Excluded');await assert.rejects(inspectImagePreparationHostBundle(target,result.bundleSha256,{trusted:false}));
});
test('composition rejects reviewed digest, provenance, service and output containment mismatches before creating output',async t=>{
 const f=await fixture();t.after(async()=>{assert.equal(dirname(resolve(f.temp)),resolve(tmpdir()));assert.match(f.temp.split(/[\\/]/).at(-1)!,/^coatria-image-preparation-package-/);await rm(f.temp,{recursive:true,force:true});});for(const output of [join(f.repo,'out'),join(f.runtime,'out'),join(f.worker,'out'),join(f.qualifier,'out')])await assert.rejects(buildImagePreparationHostBundle({...f.input,output}));
 for(const change of [{runtimeManifestSha256:'0'.repeat(64)},{workerBundleSha256:'0'.repeat(64)},{qualifierBundleSha256:'0'.repeat(64)},{workerBundlePath:f.qualifier,workerBundleSha256:f.parts['image-preparation-qualification'].sha256}])await assert.rejects(buildImagePreparationHostBundle({...f.input,...change,output:join(f.temp,'rejected')}));
 const bad=structuredClone(f.parts['image-preparation'].bundle);bad.sourceTree='b'.repeat(40);const raw=JSON.stringify(bad,null,2)+'\n';await writeFile(join(f.worker,'bundle.json'),raw);await assert.rejects(buildImagePreparationHostBundle({...f.input,workerBundleSha256:archiveHostHash(raw),output:join(f.temp,'wrong-tree')}));
});
test('dependency byte provenance is checked against full pinned exporter input even though modules are not installed',async t=>{
 const f=await fixture();t.after(async()=>{assert.equal(dirname(resolve(f.temp)),resolve(tmpdir()));assert.match(f.temp.split(/[\\/]/).at(-1)!,/^coatria-image-preparation-package-/);await rm(f.temp,{recursive:true,force:true});});const bad=structuredClone(f.parts['image-preparation'].bundle);bad.inputs[1].sha256='b'.repeat(64);const raw=JSON.stringify(bad,null,2)+'\n';await writeFile(join(f.worker,'bundle.json'),raw);await assert.rejects(buildImagePreparationHostBundle({...f.input,workerBundleSha256:archiveHostHash(raw),output:join(f.temp,'wrong-dependency')}));
});
test('native manifest and program parser reject injected files, permissions, wrong compiler and disallowed credential drivers',async t=>{
 const f=await fixture();t.after(async()=>{assert.equal(dirname(resolve(f.temp)),resolve(tmpdir()));assert.match(f.temp.split(/[\\/]/).at(-1)!,/^coatria-image-preparation-package-/);await rm(f.temp,{recursive:true,force:true});});const result=await buildImagePreparationHostBundle({...f.input,output:join(f.temp,'bundle')}),bundle=await inspectImagePreparationHostBundle(result.output,result.bundleSha256,{trusted:false});
 for(const mutate of [(v:any)=>v.runtime.files.push({path:'node_modules/pg/index.js',bytes:1,sha256:'1'.repeat(64),mode:0o444}),(v:any)=>v.runtime.files[0].path='../node',(v:any)=>v.runtime.files[0].mode=0o444,(v:any)=>v.files.push({...v.files[0]}),(v:any)=>v.emptyDirectories.pop(),(v:any)=>v.credentials={},(v:any)=>v.worker.bundle.qualified=true,(v:any)=>v.worker.bundle.compiler.version='latest']){const b=structuredClone(bundle);mutate(b);assert.throws(()=>parseImagePreparationHostBundle(b));}
 for(const path of ['node_modules/pg/index.js','node_modules/@aws-sdk/client-s3/index.js','src/.env.private']){const b=structuredClone(f.parts['image-preparation'].bundle);b.inputs.push({path,bytes:1,sha256:'1'.repeat(64),kind:path.startsWith('node_modules/')?'dependency':'source'});assert.throws(()=>parseImagePreparationServiceBundle(b,'image-preparation'));}
 await link(join(f.runtime,'node'),join(f.temp,'hardlink'));await assert.rejects(buildImagePreparationHostBundle({...f.input,output:join(f.temp,'linked')}));
});
test('Git replacement objects cannot alter the selected exact source and symlink blobs cannot enter the package',async t=>{
 const f=await fixture();t.after(async()=>{assert.equal(dirname(resolve(f.temp)),resolve(tmpdir()));assert.match(f.temp.split(/[\\/]/).at(-1)!,/^coatria-image-preparation-package-/);await rm(f.temp,{recursive:true,force:true});});await writeFile(join(f.repo,'src/lib/higgsfield-reference-worker.ts'),'Alternate original synthetic fixture\n');git(f.repo,['add','.']);git(f.repo,['commit','--quiet','-m','Alternate original source']);git(f.repo,['replace',f.commit,git(f.repo,['rev-parse','HEAD'])]);const result=await buildImagePreparationHostBundle({...f.input,output:join(f.temp,'original')});assert.deepEqual(await readFile(join(result.output,'source/src/lib/higgsfield-reference-worker.ts')),f.source.get('src/lib/higgsfield-reference-worker.ts'));
 const blob=git(f.repo,['rev-parse','HEAD:scripts/hosting/media-sandbox-launch.c']);git(f.repo,['update-index','--cacheinfo','120000,'+blob+',scripts/hosting/media-sandbox-launch.c']);git(f.repo,['commit','--quiet','-m','Synthetic source symlink']);await assert.rejects(buildImagePreparationHostBundle({...f.input,commit:git(f.repo,['rev-parse','HEAD']),output:join(f.temp,'symlink-source')}));
});
test('finite reviewed scope rejects arbitrary origins, wildcards, duplicate authority and extra credential fields',()=>{
 const now=Date.now(),value=scopeInput();assert.equal(parseImagePreparationHostScope(value,now).serviceId,id);
 for(const change of [{expiresAt:new Date(now).toISOString()},{expiresAt:new Date(now+3600001).toISOString()},{origin:'https://127.0.0.1'},{origin:'https://user:pass@example.invalid'},{origin:'https://coatria.example/path'},{origin:'https://coatria.example:443'},{gateways:[{projectId:value.projectIds[0],origin:'https://127.0.0.1'}]},{gateways:[]},{gateways:[{projectId:id,origin:'https://gateway.example.invalid'}]},{projectIds:[value.projectIds[0],value.projectIds[0]]},{gateways:[...value.gateways,...value.gateways]},{token:'synthetic-value'}])assert.throws(()=>parseImagePreparationHostScope({...value,...change},now));
});
test('active qualifier retains only its exact preflight and worker history without pulling either into a start job',()=>{
 const bundle='a'.repeat(64),release='/var/lib/coatria-image-preparation-releases/'+bundle;
 const qualify=imagePreparationHostUnit('qualify',release,bundle,id);
 const lines=qualify.split('\n').filter(line=>line.startsWith('Before='));
 assert.deepEqual(lines,['Before='+['preflight','worker'].map(mode=>imagePreparationHostUnitName(id,mode)).join(' ')]);
 assert.match(qualify,/^RemainAfterExit=yes$/m);
 for(const mode of ['qualify','preflight','worker']){
  const unit=imagePreparationHostUnit(mode,release,bundle,id);
  assert.doesNotMatch(unit,/^(?:Wants|Requires|Requisite|BindsTo|Upholds|PartOf|WantedBy|RequiredBy|UpheldBy)=/m);
  if(mode!=='qualify'){assert.doesNotMatch(unit,/^Before=|^RemainAfterExit=yes$/m);assert.match(unit,/^ConditionPathExists=.*\/qualified\.json$/m);}
 }
});
test('units are exact, disabled, finite and credential-free during qualification; host config pins every derived profile and unit',async t=>{
 const f=await fixture();t.after(async()=>{assert.equal(dirname(resolve(f.temp)),resolve(tmpdir()));assert.match(f.temp.split(/[\\/]/).at(-1)!,/^coatria-image-preparation-package-/);await rm(f.temp,{recursive:true,force:true});});const result=await buildImagePreparationHostBundle({...f.input,output:join(f.temp,'bundle')}),bundle=await inspectImagePreparationHostBundle(result.output,result.bundleSha256,{trusted:false}),scope=parseImagePreparationHostScope(scopeInput()),plan=imagePreparationHostInstallPlan(bundle,result.bundleSha256,scope),host=createImagePreparationHostConfiguration(bundle,result.bundleSha256,scope,{uid:1001,gid:1001});assert.deepEqual(parseImagePreparationHostConfiguration(host,bundle),host);assert.deepEqual(parseRunnerHostConfiguration(host),host);assert.equal(host.recipeSha256,IMAGE_PREPARATION_RECIPE_HASH);assert.equal(plan.qualified,false);assert.equal(plan.credentialsIncluded,false);
 for(const mode of ['qualify','preflight','worker']){const unit=imagePreparationHostUnit(mode,plan.release,result.bundleSha256,id);assert.match(unit,/^User=coatria-image-preparation$/m);assert.match(unit,/^DelegateSubgroup=supervisor$/m);assert.match(unit,/^KillMode=control-group$/m);assert.match(unit,/^Restart=no$/m);assert.match(unit,/^TimeoutStopSec=45$/m);assert.match(unit,/^SendSIGKILL=yes$/m);assert.doesNotMatch(unit,/^\[Install\]|^WantedBy=|^StateDirectory=|^ExecStart=.*(?:npm|curl|wget|sudo)|--sha256/m);assert.ok(unit.includes('--host /etc/coatria-image-preparation/'+id+'/host.json --bundle '+result.bundleSha256));}
 assert.doesNotMatch(plan.units[0].content,/^EnvironmentFile=/m);assert.match(plan.units[0].content,/^RemainAfterExit=yes$/m);assert.match(plan.units[1].content,/--preflight$/m);assert.match(plan.units[2].content,/^RuntimeMaxSec=3600$/m);assert.doesNotMatch(plan.units[2].content,/^EnvironmentFile=/m);assert.equal(host.closureSha256,bundle.runtimeInputSha256);assert.equal(host.node.sha256,bundle.runtime.files.find((f:any)=>f.path==='node').sha256);assert.equal(host.worker.sha256,bundle.worker.bundle.runtime.sha256);assert.equal(host.profiles.real.expectedProfileSha256,archiveHostHash(JSON.stringify(imagePreparationHostProfiles(bundle,plan.release).real,null,2)+'\n'));
 for(const mutate of [(v:any)=>v.uid=0,(v:any)=>v.tree='a'.repeat(40),(v:any)=>v.scope.projectIds.push(id),(v:any)=>v.worker.sha256='b'.repeat(64),(v:any)=>v.profiles.real.profilePath='/tmp/untrusted',(v:any)=>v.units.worker.sha256='c'.repeat(64)]){const changed=structuredClone(host);mutate(changed);assert.throws(()=>parseImagePreparationHostConfiguration(changed,bundle));}
});
test('disabled installer checks masks, drop-ins, enabled links and loaded manager state without deleting them',async t=>{
 const temp=await mkdtemp(join(tmpdir(),'coatria-image-preparation-unit-test-'));t.after(async()=>{assert.equal(dirname(resolve(temp)),resolve(tmpdir()));assert.match(temp.split(/[\\/]/).at(-1)!,/^coatria-image-preparation-/);await rm(temp,{recursive:true,force:true});});const names=['qualify','preflight','worker'].map(m=>imagePreparationHostUnitName(id,m));await assertImagePreparationHostUnitsAbsent(names,[temp]);
 for(const relative of [names[0],names[0]+'.d','service.d','coatria-image-preparation-.service.d','multi-user.target.wants/'+names[0],'coatria-image-preparation-20000000-0000-4000-8000-000000000002-worker.service']){const path=join(temp,relative);await mkdir(dirname(path),{recursive:true});await writeFile(path,'preserved fixture');await assert.rejects(assertImagePreparationHostUnitsAbsent(names,[temp]));assert.equal(await readFile(path,'utf8'),'preserved fixture');await rm(path);}
 const state={LoadState:'not-found',ActiveState:'inactive',FragmentPath:'',DropInPaths:'',UnitFileState:''},raw=(v:Record<string,string>)=>Object.entries(v).map(([k,v])=>k+'='+v).join('\n');assert.doesNotThrow(()=>assertImagePreparationHostUnloadedUnit(raw(state)));for(const change of [{LoadState:'loaded'},{ActiveState:'active'},{FragmentPath:'/tmp/foreign'},{DropInPaths:'/tmp/dropin'},{UnitFileState:'enabled'}])assert.throws(()=>assertImagePreparationHostUnloadedUnit(raw({...state,...change})));
 const empty=join(temp,'empty');await mkdir(empty);await assertImagePreparationHostVacantBase(empty);const linked=join(temp,'linked');await symlink(empty,linked,process.platform==='win32'?'junction':'dir');await assert.rejects(assertImagePreparationHostVacantBase(linked));await rm(linked);await writeFile(join(empty,'prior-private-evidence'),'preserve');await assert.rejects(assertImagePreparationHostVacantBase(empty));assert.equal(await readFile(join(empty,'prior-private-evidence'),'utf8'),'preserve');
});
test('scope file requires its exact reviewed digest and non-root-platform installation performs no writes',async t=>{
 const temp=await mkdtemp(join(tmpdir(),'coatria-image-preparation-install-test-'));t.after(async()=>{assert.equal(dirname(resolve(temp)),resolve(tmpdir()));assert.match(temp.split(/[\\/]/).at(-1)!,/^coatria-image-preparation-/);await rm(temp,{recursive:true,force:true});});const path=join(temp,'scope.json'),raw=JSON.stringify(scopeInput())+'\n';await writeFile(path,raw);assert.equal((await readImagePreparationInstallScope(path,archiveHostHash(raw))).serviceId,id);await assert.rejects(readImagePreparationInstallScope(path,'a'.repeat(64)));if(process.platform!=='linux'||process.getuid?.()!==0){await assert.rejects(installImagePreparationHost(temp,'a'.repeat(64),path,archiveHostHash(raw)));assert.deepEqual(await readdir(temp),['scope.json']);}
});
test('concurrent installation claims retain one service identity and reject all later claims without overwriting',async t=>{
 const temp=await mkdtemp(join(tmpdir(),'coatria-image-preparation-claim-test-'));t.after(async()=>{assert.equal(dirname(resolve(temp)),resolve(tmpdir()));assert.match(temp.split(/[\\/]/).at(-1)!,/^coatria-image-preparation-/);await rm(temp,{recursive:true,force:true});});const ids=[id,'20000000-0000-4000-8000-000000000001'];
 // Windows cannot fsync an open directory, but wx still determines the single
 // winner before that platform-only failure; the Linux CI proves durable sync.
 const results=await Promise.allSettled(ids.map(serviceId=>claimImagePreparationHostInstallation(temp,serviceId,'a'.repeat(64))));assert.equal(results.filter(r=>r.status==='rejected'&&(r.reason as NodeJS.ErrnoException).code==='EEXIST').length,1);if(process.platform!=='win32')assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
 const original=await readFile(join(temp,'installation.json')),claim=JSON.parse(original.toString());assert.ok(ids.includes(claim.serviceId));assert.equal(claim.bundleSha256,'a'.repeat(64));await assert.rejects(claimImagePreparationHostInstallation(temp,id,'b'.repeat(64)));assert.deepEqual(await readFile(join(temp,'installation.json')),original);await assert.rejects(assertImagePreparationHostVacantBase(temp));
});


test('plain Node builder and installer plan run from four source modules without loaders or application dependencies',async t=>{
 const f=await fixture();t.after(async()=>{assert.equal(dirname(resolve(f.temp)),resolve(tmpdir()));assert.match(f.temp.split(/[\\/]/).at(-1)!,/^coatria-image-preparation-package-/);await rm(f.temp,{recursive:true,force:true});});
 const tools=join(f.temp,'standalone-tools');await mkdir(tools);
 for(const name of ['archive-host-package.mjs','image-preparation-host-package.mjs','build-image-preparation-host-bundle.mjs','install-image-preparation-host.mjs'])await copyFile(fileURLToPath(new URL('../scripts/hosting/'+name,import.meta.url)),join(tools,name));
 // The copied tree contains neither TypeScript source, package.json nor dependencies.
 assert.equal((await readdir(tools)).length,4);
 const run=(entry:string,args:string[])=>spawnSync(process.execPath,[join(tools,entry),...args],{cwd:tools,env:{...process.env,NODE_OPTIONS:'',NODE_PATH:''},encoding:'utf8',timeout:30000,windowsHide:true});
 const output=join(f.temp,'plain-node-bundle'),build=run('build-image-preparation-host-bundle.mjs',[f.repo,f.commit,f.runtime,f.input.runtimeManifestSha256,f.worker,f.input.workerBundleSha256,f.qualifier,f.input.qualifierBundleSha256,output]);
 assert.equal(build.error,undefined);assert.equal(build.status,0,build.stderr);assert.equal(build.stderr,'');const result=JSON.parse(build.stdout);assert.equal(result.qualified,false);assert.equal(result.providerCalls,false);assert.equal(result.servicesEnabled,false);
 const scope=join(f.temp,'plain-node-scope.json'),raw=JSON.stringify(scopeInput())+'\n';await writeFile(scope,raw);
 const plan=run('install-image-preparation-host.mjs',['plan',output,result.bundleSha256,scope,archiveHostHash(raw)]);assert.equal(plan.error,undefined);assert.equal(plan.status,0,plan.stderr);assert.equal(plan.stderr,'');const parsed=JSON.parse(plan.stdout);
 assert.equal(parsed.bundleSha256,result.bundleSha256);assert.equal(parsed.qualified,false);assert.equal(parsed.credentialsIncluded,false);assert.equal(parsed.servicesStarted,false);assert.equal(parsed.servicesEnabled,false);
 for(const [entry,message] of [['build-image-preparation-host-bundle.mjs','IMAGE_PREPARATION_HOST_BUILD_REJECTED'],['install-image-preparation-host.mjs','IMAGE_PREPARATION_HOST_INSTALL_REJECTED: no service was enabled or started.']]){const invalid=run(entry,[]);assert.equal(invalid.status,1);assert.equal(invalid.stdout,'');assert.equal(invalid.stderr.trim(),message);}
});

test('dependency-free packaging pin and scope validators match native recipe and strict protocol origins and UUIDs',()=>{
 assert.equal(IMAGE_PREPARATION_HOST_RECIPE_SHA256,IMAGE_PREPARATION_RECIPE_HASH,'A changed native recipe requires explicit review of the source-only installer pin.');
 const origins:unknown[]=['https://coatria.example','https://gateway.example.invalid','https://xn--bcher-kva.example','http://coatria.example','https://COATRIA.example','https://coatria.example/','https://coatria.example/path','https://coatria.example?x=1','https://coatria.example#fragment','https://user:pass@coatria.example','https://coatria.example:443','https://coatria.example:8443','https://127.0.0.1','https://2130706433','https://0x7f000001','https://[::1]','https://localhost','https://app.localhost','https://coatria.example.','https://bad_name.example','https://-bad.example','https://bad-.example','https://a..example','https://bücher.example',' https://coatria.example','https://coatria.example\n','https://'+('a'.repeat(63)+'.').repeat(7)+'example','https://'+('a'.repeat(63)+'.').repeat(8)+'example','https://'+'a'.repeat(64)+'.example',null,0,{}];
 for(const origin of origins){const expected=preparationServiceOrigin.safeParse(origin).success;for(const gateway of [false,true]){const raw=scopeInput();if(gateway)(raw.gateways[0] as {origin:unknown}).origin=origin;else (raw as {origin:unknown}).origin=origin;let accepted=false;try{parseImagePreparationHostScope(raw);accepted=true;}catch{}assert.equal(accepted,expected,JSON.stringify({origin,gateway}));}}
 const ids=['10000000-0000-4000-8000-000000000001','00000000-0000-0000-0000-000000000000','ffffffff-ffff-ffff-ffff-ffffffffffff',...Array.from({length:10},(_,n)=>'10000000-0000-'+n+'000-8000-000000000001'),'10000000-0000-4000-7000-000000000001','10000000-0000-4000-c000-000000000001','10000000-0000-4000-A000-000000000001','10000000-0000-4000-8000-000000000001\n','not-a-uuid'];
 for(const value of ids)for(const field of ['service','company','project']){const raw=scopeInput();if(field==='service')raw.serviceId=value;else if(field==='company')raw.companyId=value;else{raw.projectIds=[value];raw.gateways[0].projectId=value;}let accepted=false;try{parseImagePreparationHostScope(raw);accepted=true;}catch{}assert.equal(accepted,preparationServiceUuid.safeParse(value).success,JSON.stringify({value,field}));}
});
