/** Real handlers/SQL/HTTPS/signing/local decode; synthetic enrollment/storage.
 * These portable checks are not installed-systemd or production acceptance. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {crc32,deflateSync} from 'node:zlib';
import {mkdtemp,readFile,readdir,rm,mkdir,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,dirname,basename} from 'node:path';
import {spawnSync} from 'node:child_process';
import {request as httpsRequest} from 'node:https';
import {fileURLToPath} from 'node:url';
import {openImagePreparationServiceDatabase,imagePreparationServiceFixture} from './fixtures/image-preparation-service';
import {enrollImagePreparationService} from '../src/lib/project-image-preparation-enrollment';
import {resolveProjectImagePreparationProcessor} from '../src/lib/project-image-preparation-service-authority';
import {createImagePreparationServiceClient} from '../src/lib/project-image-preparation-service-client';
import {createProjectImagePreparationWorkerCore} from '../src/lib/project-image-preparation-worker-core';
import {prepareReferenceImage} from '../src/lib/higgsfield-image-preparation';
import {createImagePreparationInstalledFixture,type InstalledImagePreparationFixtureOptions} from '../scripts/hosting/image-preparation-installed-fixture.mjs';
const hash=(v:Uint8Array)=>createHash('sha256').update(v).digest('hex'),origin='https://imagepreparationci1-4190.proxy.runpod.net';
function originalPng(){const header=Buffer.alloc(13),rows=Buffer.alloc(16*65);header.writeUInt32BE(16);header.writeUInt32BE(16,4);header[8]=8;header[9]=6;for(let y=0;y<16;y++)for(let x=0;x<16;x++){const i=y*65+x*4+1;rows[i]=x*16;rows[i+1]=y*16;rows[i+2]=100;rows[i+3]=255;}const chunk=(name:string,data:Buffer)=>{const length=Buffer.alloc(4),type=Buffer.from(name),crc=Buffer.alloc(4);length.writeUInt32BE(data.length);crc.writeUInt32BE(crc32(Buffer.concat([type,data])));return Buffer.concat([length,type,data,crc]);};return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('tEXt',Buffer.from('Comment\0synthetic confidential original')),chunk('IDAT',deflateSync(rows)),chunk('IEND',Buffer.alloc(0))]);}
async function temp(t:test.TestContext){const root=await realpath(await mkdtemp(join(tmpdir(),'coatria-installed-fixture-')));t.after(async()=>{assert.equal(dirname(resolve(root)),resolve(await realpath(tmpdir())));assert(basename(root).startsWith('coatria-installed-fixture-'));await rm(resolve(root),{recursive:true,force:true});});return root;}
async function seed(database:Awaited<ReturnType<typeof openImagePreparationServiceDatabase>>,{approve=true}={}){const bytes=originalPng(),f=await database.tx(db=>imagePreparationServiceFixture(db,{enroll:false,sourceBytes:bytes}));const enrollment=structuredClone(f.enrollment);enrollment.projects[0].gateway.origin=origin;await database.tx(async db=>{await db.query("UPDATE trusted_service_provisions SET pod_id='imagepreparationci1' WHERE id=$1",[f.gateway.provisionId]);await db.query('UPDATE project_gateway_bindings SET origin=$2 WHERE id=$1',[f.gateway.bindingId,origin]);await enrollImagePreparationService(db,enrollment);if(approve)await f.approve(db);});const processor=await database.tx(db=>resolveProjectImagePreparationProcessor(db,f.companyId,f.projectId,f.serviceId));assert(processor);const options:InstalledImagePreparationFixtureOptions={transaction:database.tx,identity:{serviceId:f.serviceId,companyId:f.companyId,projectIds:[f.projectId],origin:enrollment.origin,expiresAt:enrollment.expiresAt,processor,token:f.token},gateway:{origin,provisionId:f.gateway.provisionId,configurationHash:f.gateway.configurationHash,sourceCommit:'b'.repeat(40),expiresAt:f.gateway.expiresAt},storageKeyring:f.storageKeyring,sources:[{projectId:f.projectId,versionId:f.versionId,bytes,etag:'synthetic-source-etag'}]};return {f,bytes,options};}
async function certificates(root:string){const openssl=process.env.COATRIA_TEST_OPENSSL_PATH??(process.platform==='win32'?'C:/Program Files/Git/usr/bin/openssl.exe':'/usr/bin/openssl'),key=join(root,'key.pem'),cert=join(root,'cert.pem');const result=spawnSync(openssl,['req','-x509','-newkey','rsa:2048','-nodes','-keyout',key,'-out',cert,'-days','1','-subj','/CN=coatria.com','-addext','subjectAltName=DNS:coatria.com,DNS:imagepreparationci1-4190.proxy.runpod.net'],{encoding:'utf8',shell:false,windowsHide:true,timeout:15000,maxBuffer:32768});assert.equal(result.status,0,'Local OpenSSL must generate the disposable test certificate');return {key:await readFile(key),cert:await readFile(cert)};}
function localHttps(port:number,cert:Buffer):typeof fetch{return async(input,init)=>{const url=new URL(String(input));assert(['coatria.com','imagepreparationci1-4190.proxy.runpod.net'].includes(url.hostname));return new Promise<Response>((res,rej)=>{const headers=new Headers(init?.headers);headers.set('host',url.hostname);const request=httpsRequest({host:'127.0.0.1',port,servername:url.hostname,ca:cert,method:init?.method,path:url.pathname+url.search,headers:Object.fromEntries(headers),signal:init?.signal??undefined,agent:false},response=>{const chunks:Buffer[]=[];response.on('data',chunk=>chunks.push(Buffer.from(chunk)));response.on('error',rej);response.on('end',()=>res(new Response(new Uint8Array(Buffer.concat(chunks)),{status:response.statusCode,headers:response.headers as HeadersInit})));});request.on('error',rej);if(init?.body!==undefined&&init.body!==null){assert(typeof init.body==='string'||init.body instanceof Uint8Array);request.write(init.body);}request.end();});};}

test('installed fixture runs actual handlers, cryptographic SDK signing and native transform through local HTTPS',{timeout:120000},async t=>{
 const database=await openImagePreparationServiceDatabase(),root=await temp(t);t.after(()=>database.close());const {f,bytes,options}=await seed(database),fixture=await createImagePreparationInstalledFixture(options),restore=fixture.installSyntheticS3Fetch();
 const tls=await certificates(root),server=await fixture.startServer({tls,host:'127.0.0.1',port:0}),scratch=join(root,'scratch');await mkdir(scratch);const ffmpegPath=await realpath(process.env.COATRIA_TEST_FFMPEG_PATH??'C:/Users/pecem/AppData/Local/Microsoft/WinGet/Links/ffmpeg.exe'),ffmpegSha256=hash(await readFile(ffmpegPath));const client=createImagePreparationServiceClient({...options.identity,gateways:[{projectId:f.projectId,origin}]},{fetch:localHttps(server.address.port,tls.cert)});let transforms=0;
 try{
  await client.readiness();const worker=createProjectImagePreparationWorkerCore({scope:{companyId:f.companyId,projectIds:[f.projectId]},scratchRoot:scratch,createPorts:()=>client,transform:async(input,context)=>{transforms++;assert.doesNotMatch(JSON.stringify(context),/objectKey|secretAccess|rps_|user_synthetic/);return prepareReferenceImage(input,{nativeTestMode:true,ffmpegPath,ffmpegSha256});}});const result=await worker.runNext();assert.equal(result.status,'ready',JSON.stringify({result,audit:fixture.audit()}));assert.equal(transforms,1);
  const audit=fixture.audit();assert.equal(audit.counts.signatureVerified,5);assert.equal(audit.counts.readSource,1);assert.equal(audit.counts.initiate,1);assert.equal(audit.counts.part,1);assert.equal(audit.counts.complete,1);assert.equal(audit.counts.readOutput,1);assert.equal(audit.counts.transportRejected,0);assert(audit.counts.metadata>8);assert.equal(audit.counts.bytes,5);assert.equal(audit.outputs.length,1);
  const objects=fixture.objects();assert(objects.sources[0].bytes.equals(bytes));assert.notEqual(objects.outputs[0].versionId,f.versionId);assert(!objects.outputs[0].bytes.includes(Buffer.from('confidential')));assert.equal(hash(objects.outputs[0].bytes),audit.outputs[0].sha256);objects.sources[0].bytes.fill(0);assert(fixture.objects().sources[0].bytes.equals(bytes));assert.deepEqual(await readdir(scratch),[]);
  const state=(await database.db.query('SELECT status,cleanup_confirmed_at FROM project_image_preparations WHERE id=$1',[f.proposed!.id])).rows[0];assert.equal(state.status,'ready');assert(state.cleanup_confirmed_at);assert.equal((await database.db.query('SELECT count(*)::int AS n FROM project_image_preparation_derivations WHERE preparation_id=$1',[f.proposed!.id])).rows[0].n,1);
  for(const secret of [f.token,'rps_synthetic','user_synthetic','synthetic-upload-',options.storageKeyring,'confidential'])assert(!JSON.stringify(audit).includes(secret));
 }finally{client.close();await client.drain();fixture.close();try{await fixture.drain();}finally{restore();}}
});

test('lost initiation and changed readback retain uncertain real SQL state without retries',{timeout:120000},async t=>{
 const root=await temp(t),ffmpegPath=await realpath(process.env.COATRIA_TEST_FFMPEG_PATH??'C:/Users/pecem/AppData/Local/Microsoft/WinGet/Links/ffmpeg.exe'),ffmpegSha256=hash(await readFile(ffmpegPath));
 for(const scenario of ['lost-initiation-response','changed-readback'] as const)await t.test(scenario,async st=>{const database=await openImagePreparationServiceDatabase();st.after(()=>database.close());const {f,options}=await seed(database),fixture=await createImagePreparationInstalledFixture({...options,scenario}),restore=fixture.installSyntheticS3Fetch(),scratch=join(root,scenario);await mkdir(scratch);const client=createImagePreparationServiceClient({...options.identity,gateways:[{projectId:f.projectId,origin}]},{fetch:async(input,init)=>fixture.handle(new Request(input,init))});
  try{const worker=createProjectImagePreparationWorkerCore({scope:{companyId:f.companyId,projectIds:[f.projectId]},scratchRoot:scratch,createPorts:()=>client,transform:input=>prepareReferenceImage(input,{nativeTestMode:true,ffmpegPath,ffmpegSha256})});const result=await worker.runNext();assert.equal(result.status,'uncertain',JSON.stringify({result,audit:fixture.audit()}));const state=(await database.db.query('SELECT status,cleanup_confirmed_at FROM project_image_preparations WHERE id=$1',[f.proposed!.id])).rows[0];assert.equal(state.status,'uncertain');assert.equal(state.cleanup_confirmed_at,null);assert.equal((await database.db.query('SELECT count(*)::int AS n FROM project_image_preparation_derivations WHERE preparation_id=$1',[f.proposed!.id])).rows[0].n,0);assert.equal(fixture.audit().counts.initiate,1);assert.equal(fixture.audit().counts[scenario==='lost-initiation-response'?'lostInitiation':'changedReadback'],1);const freshClient=createImagePreparationServiceClient({...options.identity,gateways:[{projectId:f.projectId,origin}]},{fetch:async(input,init)=>fixture.handle(new Request(input,init))});try{const freshWorker=createProjectImagePreparationWorkerCore({scope:{companyId:f.companyId,projectIds:[f.projectId]},scratchRoot:scratch,createPorts:()=>freshClient,transform:async()=>{assert.fail('Uncertain job must not transform again');}});const next=await freshWorker.runNext();assert.equal(next.status,'idle');}finally{freshClient.close();await freshClient.drain();}assert.equal(fixture.audit().counts.initiate,1);assert.deepEqual(await readdir(scratch),[]);
  }finally{client.close();await client.drain();fixture.close();try{await fixture.drain();}finally{restore();}}
 });
});

test('fixture rejects mismatched installed authority, source facts, every non-S3 destination and unsigned transport',{timeout:60000},async t=>{
 const database=await openImagePreparationServiceDatabase();t.after(()=>database.close());const {f,options}=await seed(database);
 await assert.rejects(createImagePreparationInstalledFixture({...options,identity:{...options.identity,token:'ips_'+'x'.repeat(43)}}));await assert.rejects(createImagePreparationInstalledFixture({...options,sources:[{...options.sources[0],bytes:Buffer.from('incorrect')}]}));
 const fixture=await createImagePreparationInstalledFixture(options);assert.equal((await fixture.handle(new Request(options.identity.origin+'/api/internal/image-preparation-services/'+f.serviceId+'/readiness'))).status,503);assert.equal(fixture.audit().counts.metadata,0);const restore=fixture.installSyntheticS3Fetch();try{
  const init={method:'GET',headers:{'accept-encoding':'identity'},signal:new AbortController().signal,redirect:'error' as const,cache:'no-store' as const};await assert.rejects(fetch('https://coatria.com/',init),/SYNTHETIC_TRANSPORT_REJECTED/);await assert.rejects(fetch(`https://s3api-us-ca-2.runpod.io/synthetic-volume/coatria/companies/${f.companyId}/projects/${f.projectId}/objects/${f.versionId}?x-id=GetObject`,init),/SYNTHETIC_TRANSPORT_REJECTED/);assert.equal(fixture.audit().counts.signatureVerified,0);assert.equal(fixture.audit().counts.rejectedEgress,1);assert.equal((await fixture.handle(new Request('https://external.example/path'))).status,421);await assert.rejects(fixture.addSource(options.sources[0]));assert.throws(()=>fixture.setScenario('unreviewed' as never));
 }finally{fixture.close();try{await fixture.drain();}finally{restore();}}
});

test('TLS SNI and Host must agree before request construction or real control execution',{timeout:60000},async t=>{
 const database=await openImagePreparationServiceDatabase(),root=await temp(t);t.after(()=>database.close());const {options}=await seed(database),fixture=await createImagePreparationInstalledFixture(options),restore=fixture.installSyntheticS3Fetch(),tls=await certificates(root),server=await fixture.startServer({tls,port:0});
 try{const status=await new Promise<number>((res,rej)=>{const request=httpsRequest({host:'127.0.0.1',port:server.address.port,servername:'coatria.com',ca:tls.cert,headers:{host:'imagepreparationci1-4190.proxy.runpod.net'},agent:false},response=>{response.resume();response.on('end',()=>res(response.statusCode!));});request.on('error',rej);request.end();});assert.equal(status,421);assert.equal(fixture.audit().counts.metadata,0);assert.equal(fixture.audit().counts.bytes,0);assert.equal(fixture.audit().counts.httpRejected,1);assert.throws(()=>restore(),/FIXTURE_REJECTED/);
 }finally{fixture.close();try{await fixture.drain();}finally{restore();}}
});

test('real readiness and idle claim work before processing consent; server drain owns stalled request',{timeout:60000},async t=>{
 const database=await openImagePreparationServiceDatabase(),root=await temp(t);t.after(()=>database.close());const {f,options}=await seed(database,{approve:false}),fixture=await createImagePreparationInstalledFixture(options),restore=fixture.installSyntheticS3Fetch(),tls=await certificates(root),server=await fixture.startServer({tls,port:0});const client=createImagePreparationServiceClient({...options.identity,gateways:[{projectId:f.projectId,origin}]},{fetch:localHttps(server.address.port,tls.cert)});
 try{await client.readiness();const scratch=join(root,'scratch');await mkdir(scratch);const worker=createProjectImagePreparationWorkerCore({scope:{companyId:f.companyId,projectIds:[f.projectId]},scratchRoot:scratch,createPorts:()=>client,transform:async()=>assert.fail('Unapproved work must not transform')});assert.equal((await worker.runNext()).status,'idle');assert.equal(fixture.audit().counts.signatureVerified,0);
  const before=fixture.audit().counts.metadata;const request=httpsRequest({host:'127.0.0.1',port:server.address.port,servername:'coatria.com',ca:tls.cert,method:'POST',path:'/api/internal/image-preparation-services/'+f.serviceId+'/readiness',headers:{host:'coatria.com',authorization:'Bearer '+f.token,'content-type':'application/json',accept:'application/json','accept-encoding':'identity','content-length':'1000'},agent:false});const disconnected=new Promise<void>(res=>{request.once('error',()=>res());request.once('close',()=>res());});request.write('{');
  const end=Date.now()+2000;while(fixture.audit().counts.metadata===before&&Date.now()<end)await new Promise(res=>setTimeout(res,10));assert.equal(fixture.audit().counts.metadata,before+1);fixture.close();await fixture.drain();await disconnected;assert.equal(fixture.audit().activeOperations,0);
 }finally{client.close();await client.drain();fixture.close();try{await fixture.drain();}finally{restore();}}
});

test('failed HTTPS cleanup permanently denies fixture transport restoration',{timeout:60000},async t=>{
 if(process.env.COATRIA_FIXTURE_FAILED_DRAIN_CHILD!=='1'){
  const env:NodeJS.ProcessEnv={...process.env,COATRIA_FIXTURE_FAILED_DRAIN_CHILD:'1'};delete env.NODE_TEST_CONTEXT;const child=spawnSync(process.execPath,['--import','tsx','--test','--test-reporter=tap','--test-name-pattern','^failed HTTPS cleanup permanently denies fixture transport restoration$',fileURLToPath(import.meta.url)],{env,encoding:'utf8',shell:false,windowsHide:true,timeout:45000,maxBuffer:65536});assert.equal(child.status,0,child.stdout+child.stderr);assert.match(child.stdout,/pass 1/);return;
 }
 // Run in a real separate process: intentionally poisoned fixture ownership is
 // never bypassed merely to make a later test able to install another hook.
 const database=await openImagePreparationServiceDatabase(),root=await temp(t);t.after(()=>database.close());const {f,options}=await seed(database,{approve:false}),fixture=await createImagePreparationInstalledFixture(options),restore=fixture.installSyntheticS3Fetch(),tls=await certificates(root),server=await fixture.startServer({tls,port:0});const original=ReadableStreamDefaultReader.prototype.cancel;
 ReadableStreamDefaultReader.prototype.cancel=function(){return Promise.reject(Error('SYNTHETIC_RESPONSE_CLEANUP_FAILED'));};
 try{const response=await localHttps(server.address.port,tls.cert)(options.identity.origin+'/api/internal/image-preparation-services/'+f.serviceId+'/readiness',{method:'POST',headers:{authorization:'Bearer '+f.token,'content-type':'application/json',accept:'application/json','accept-encoding':'identity'},body:JSON.stringify({requestId:crypto.randomUUID(),deadlineAt:new Date(Date.now()+25000).toISOString()})});assert.equal(response.status,503);fixture.close();await assert.rejects(fixture.drain(),/DRAIN_FAILED/);ReadableStreamDefaultReader.prototype.cancel=original;await assert.rejects(fixture.drain(),/DRAIN_FAILED/);assert.throws(()=>restore(),/FIXTURE_REJECTED/);assert.equal(fixture.audit().activeOperations,0);assert.equal(fixture.audit().counts.signatureVerified,0);
 }finally{ReadableStreamDefaultReader.prototype.cancel=original;fixture.close();}
});
