import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {parseMediaServiceQualification,mediaQualificationJournal} from '../scripts/hosting/qualify-vercel-media-service.mjs';
import {VERCEL_MEDIA_IMAGE,type VercelMediaIntent} from '../src/lib/higgsfield-vercel-media-sandbox';
function raw(){const id=randomUUID();return {version:1,purpose:'qualification-only',sourceCommit:'a'.repeat(40),backendSha256:'abd4b274c4a4fb9d46cbbd4dbb8d7caa3db9fb34a1205c17e15c247175af36b9',bundleManifestPath:'/opt/coatria/qualification/bundle.json',bundleManifestSha256:'b'.repeat(64),reservation:{id,globalMaximum:64,ordinals:[59,60,61]},expiresAt:new Date(Date.now()+3600000).toISOString(),teamId:'team_synthetic',projectId:'prj_synthetic',region:'iad1',limits:{maxInputBytes:16777216,maxClosureBytes:268435456,timeoutMs:120000,maxOutputBytes:2097152,maxStderrBytes:65536},closure:{root:'/opt/coatria/qualification/closure',files:[{path:'bin/ffmpeg',bytes:1,sha256:'c'.repeat(64)},{path:'bin/ffprobe',bytes:1,sha256:'d'.repeat(64)}]},qualification:{receiptPath:'/opt/coatria/qualification/receipt.json',sha256:'e'.repeat(64)},input:{path:'/opt/coatria/qualification/input.png',bytes:12586943,sha256:'49c5ff2929aecbf4d576b1986c1060605a6edb007fc08239c6e1cf7cdf34ab5a'},outputDirectory:'/var/lib/coatria-media-qualification/'+id};}
function intent(config:ReturnType<typeof parseMediaServiceQualification>,tool:'ffmpeg'|'ffprobe'):VercelMediaIntent{const id=randomUUID();return Object.freeze({id,name:'coatria-media-'+id,teamId:config.teamId,projectId:config.projectId,region:'iad1',image:VERCEL_MEDIA_IMAGE,closureSha256:'a'.repeat(64),inputSha256:config.input.sha256,inputBytes:config.input.bytes,tool,ttlMs:120000,vcpus:2,memoryMiB:4096});}
test('qualification config permits only reviewed PNGs, fixed input profiles and three existing global slots',()=>{
 const input=raw(),config=parseMediaServiceQualification(input);input.reservation.ordinals[0]=1;assert.deepEqual(config.reservation.ordinals,[59,60,61]);assert.ok(Object.isFrozen(config.reservation.ordinals));
 for(const change of [(v:any)=>v.purpose='production',(v:any)=>v.reservation.ordinals=[63,64,65],(v:any)=>v.reservation.ordinals=[1,1,2],(v:any)=>v.reservation.globalMaximum=65,(v:any)=>v.input.sha256='f'.repeat(64),(v:any)=>v.input.bytes=111,(v:any)=>v.limits.maxInputBytes=1048576,(v:any)=>v.limits.maxInputBytes=33554432,(v:any)=>v.backendSha256='f'.repeat(64),(v:any)=>v.outputDirectory='/tmp/public',(v:any)=>v.credential='secret']){const value=raw();change(value);assert.throws(()=>parseMediaServiceQualification(value));}
});
test('qualification journal admits exactly three sequential tools and requires terminal evidence before the next',async()=>{
 const config=parseMediaServiceQualification(raw()),events:any[]=[],control=new AbortController(),state=mediaQualificationJournal(config,async event=>{events.push(event);},control.signal);
 for(const [index,tool] of (['ffprobe','ffmpeg','ffprobe'] as const).entries()){const call=intent(config,tool);await state.journal.reserve(call);assert.equal(events.at(-1).globalOrdinal,59+index);await state.journal.authorize(call);await assert.rejects(state.journal.reserve(intent(config,tool)),/RESERVATION_REJECTED/);await state.journal.record({type:'created',intentId:call.id,name:call.name,sessionId:'sbx_'+index});await assert.rejects(state.journal.record({type:'terminal',intentId:call.id,name:call.name,sessionId:'sbx_foreign',status:'stopped'}),/JOURNAL_CONFLICT/);await state.journal.record({type:'terminal',intentId:call.id,name:call.name,sessionId:'sbx_'+index,status:'stopped'});await state.journal.authorize(call);}
 assert.equal(state.snapshot().createsReserved,3);assert.equal(state.snapshot().terminalSessions.length,3);assert.equal(state.snapshot().unresolvedIntent,null);await assert.rejects(state.journal.reserve(intent(config,'ffprobe')),/RESERVATION_REJECTED/);
});
test('failed durable reserve, aborted authority and identity drift cannot permit additional launch',async()=>{
 const config=parseMediaServiceQualification(raw()),control=new AbortController(),state=mediaQualificationJournal(config,async()=>{throw Error('journal unavailable');},control.signal),call=intent(config,'ffprobe');await assert.rejects(state.journal.reserve(call),/journal unavailable/);assert.equal(state.snapshot().unresolvedIntent,call.id);await assert.rejects(state.journal.reserve(intent(config,'ffprobe')),/RESERVATION_REJECTED/);
 const events:unknown[]=[],other=mediaQualificationJournal(config,async event=>{events.push(event);},control.signal);await assert.rejects(other.journal.reserve({...call,inputBytes:111}),/RESERVATION_REJECTED/);await assert.rejects(other.journal.reserve({...call,image:'node:latest'}),/RESERVATION_REJECTED/);await assert.rejects(other.journal.reserve(intent(config,'ffmpeg')),/RESERVATION_REJECTED/);control.abort();await assert.rejects(other.journal.reserve(call));assert.deepEqual(events,[]);
});
