import test from 'node:test';
import assert from 'node:assert/strict';
import {chromium,type Page} from '@playwright/test';
import {storageReauthorizationFixture,storageIds} from './fixtures/storage-reauthorization-ui';

test('storage credential recovery uses the actual project files UI and safe local HTTP fixtures',{timeout:120000},async t=>{
 const fixture=await storageReauthorizationFixture(),{state,origin}=fixture,browser=await chromium.launch({headless:true});const errors:string[]=[];
 async function open(page:Page){await page.goto(origin);await page.getByRole('button',{name:'Manage connection',exact:true}).click();await page.getByRole('button',{name:state.connection.status==='revoked'?'Restore access':'Replace credentials',exact:true}).click();await page.getByRole('heading',{name:state.connection.status==='revoked'?'Restore storage access':'Replace storage credentials',exact:true}).waitFor();}
 async function fill(page:Page){await page.getByLabel('New S3 access key ID',{exact:true}).fill('user_browserfixture');await page.getByLabel('New S3 secret access key',{exact:true}).fill('rps_browser-fixture-key');await page.getByRole('checkbox').check();}
 async function page(){const p=await browser.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));return p;}
 try{
  await t.test('revoked binding can restore exact identity with readable company confirmation and no new connection',async()=>{state.reset();const p=await page();try{await open(p);const modal=p.getByRole('dialog');assert.match(await modal.innerText(),/Aster Film Studio/);assert.match(await modal.innerText(),/fixture-retained-volume/);assert(!await modal.getByText(storageIds.connection,{exact:true}).isVisible());assert(await p.getByRole('button',{name:'Save new credentials'}).isDisabled());await fill(p);await p.getByRole('button',{name:'Save new credentials'}).click();await p.getByRole('status').filter({hasText:'Credentials saved'}).waitFor();assert.equal(state.connection.id,storageIds.connection);assert.equal(state.connection.revision,3);assert.equal(state.requests.filter(r=>r.method==='POST').length,1);assert(state.requests.filter(r=>r.method==='POST').every(r=>r.path.endsWith('/'+storageIds.connection+'/reauthorize')));assert(await p.getByRole('button',{name:'New folder',exact:true}).isEnabled());assert.equal(await p.getByText('01_Brief',{exact:true}).count(),1);const storage=await p.evaluate(()=>JSON.stringify({session:{...sessionStorage},local:{...localStorage}}));assert(!storage.includes('browserfixture'));assert(!storage.includes('browser-fixture-key'));}finally{await p.close();}});
  await t.test('configured connection rotates credentials with fresh explicit confirmation',async()=>{state.reset();state.connection={...state.connection,status:'configured',credentialsConfigured:true};const p=await page();try{await open(p);await fill(p);await p.getByLabel('New S3 secret access key',{exact:true}).fill('rps_browser-second-key');assert(!await p.getByRole('checkbox').isChecked());await p.getByRole('checkbox').check();await p.getByRole('button',{name:'Save new credentials'}).click();await p.getByRole('status').filter({hasText:'Credentials saved'}).waitFor();assert.equal(state.connection.revision,3);}finally{await p.close();}});
  await t.test('lost response survives reload and resolves exact receipt by GET without resending secrets',async()=>{state.reset();state.mode='lost';const p=await page();try{await open(p);await fill(p);await p.getByRole('button',{name:'Save new credentials'}).click();await p.getByRole('alert').filter({hasText:'has not been confirmed'}).waitFor();const saved=await p.evaluate(()=>JSON.stringify({...sessionStorage}));assert(saved.includes('clientId'));assert(!saved.includes('browserfixture'));assert(!saved.includes('secretAccessKey'));await open(p);await p.getByRole('button',{name:'Check credential change'}).waitFor();assert.equal(await p.getByRole('button',{name:'Save new credentials'}).count(),0);await p.getByRole('button',{name:'Check credential change'}).click();await p.getByRole('status').filter({hasText:'Credentials saved'}).waitFor();assert.equal(state.requests.filter(r=>r.method==='POST').length,1);assert.equal(await p.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('coatria:storage-credentials:')).length),0);}finally{await p.close();}});
  await t.test('unavailable status remains fenced; explicit revocation ends an unrecorded pending revision',async()=>{state.reset();state.mode='absent';const p=await page();try{await open(p);await fill(p);await p.getByRole('button',{name:'Save new credentials'}).click();await p.getByRole('alert').waitFor();state.readStatus=403;await p.getByRole('button',{name:'Check credential change'}).click();await p.getByRole('alert').filter({hasText:'Status access'}).waitFor();await open(p);await p.getByRole('button',{name:'Check credential change'}).waitFor();assert.equal(await p.getByRole('button',{name:'Save new credentials'}).count(),0);state.readStatus=200;await p.getByRole('button',{name:'Check credential change'}).click();await p.getByRole('status').filter({hasText:'No completed replacement'}).waitFor();await p.getByRole('checkbox').check();await p.getByRole('button',{name:'Revoke connection and end pending change'}).click();await p.getByRole('status').filter({hasText:'connection is revoked'}).waitFor();assert.equal(state.requests.filter(r=>r.method==='POST').length,1);assert.equal(state.requests.filter(r=>r.method==='PATCH').length,1);assert.equal(state.connection.status,'revoked');assert.equal(state.connection.revision,3);}finally{await p.close();}});
  await t.test('stale revision does not silently restore, and a later revocation is never reported as configured',async()=>{state.reset();state.mode='conflict';const p=await page();try{await open(p);await fill(p);await p.getByRole('button',{name:'Save new credentials'}).click();await p.getByRole('alert').waitFor();await p.getByRole('button',{name:'Check credential change'}).click();await p.getByRole('status').filter({hasText:'connection is revoked'}).waitFor();assert.equal(state.requests.filter(r=>r.method==='POST').length,1);state.mode='lost';await open(p);await fill(p);await p.getByRole('button',{name:'Save new credentials'}).click();await p.getByRole('alert').waitFor();state.connection={...state.connection,revision:5,status:'revoked',credentialsConfigured:false};await p.getByRole('button',{name:'Check credential change'}).click();await p.getByRole('status').filter({hasText:'connection is revoked'}).waitFor();assert.equal(state.requests.filter(r=>r.method==='POST').length,2);assert.equal(await p.getByRole('status').filter({hasText:'Credentials saved'}).count(),0);}finally{await p.close();}});
  await t.test('mobile dialog stays within viewport and ordinary members have no credential controls',async()=>{state.reset();const p=await page();try{await p.setViewportSize({width:390,height:844});await open(p);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.getByRole('button',{name:'Close',exact:true}).click();await p.goto(origin+'/?role=member');await p.getByText('01_Brief',{exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Manage connection',exact:true}).count(),0);assert.equal(state.requests.filter(r=>r.method!=='GET').length,0);}finally{await p.close();}});
  assert.deepEqual(errors,[]);
 }finally{await browser.close();await fixture.close();}
});
