import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {parseReferenceHostQualificationArguments,assertReferenceHostQualificationEnvironment,referenceHostQualificationState,referenceHostQualificationInvocation,REFERENCE_QUALIFIER_STATE_PROPERTIES,referenceHostJournalProof,makeReferenceHostEvidence,makeReferenceHostReceipt,referenceHostReceiptReplacement,referenceHostQualificationHash,assertReferenceHostDetailedReport,acceptReferenceHostQualification} from '../scripts/hosting/reference-host-qualification.mjs';
import {deriveReferenceRunnerConfiguration,referenceRunnerConfigurationHash} from '../scripts/hosting/reference-runner-identity.mjs';

const hash=referenceHostQualificationHash,json=(v:unknown)=>JSON.stringify(v,null,2)+'\n';
function fixture(){
 const id=randomUUID(),companyId=randomUUID(),projectIds=[randomUUID()],release='/var/lib/coatria-reference-releases/'+'a'.repeat(64),now=Date.now();
 const host={version:1 as const,bundleSha256:'a'.repeat(64),commit:'b'.repeat(40),tree:'c'.repeat(40),release,uid:1234,gid:1234,scope:{serviceId:id,companyId,projectIds,origin:'https://coatria.example',expiresAt:new Date(now+30*60*1000).toISOString(),uploadHosts:['upload.example']},profiles:{real:{profilePath:`/etc/coatria-reference/${id}/real.json`,expectedProfileSha256:'d'.repeat(64)},conformance:{profilePath:`/etc/coatria-reference/${id}/conformance.json`,expectedProfileSha256:'e'.repeat(64)}},worker:{path:release+'/worker/runtime.mjs',sha256:'f'.repeat(64)},qualifier:{path:release+'/qualifier/runtime.mjs',sha256:'1'.repeat(64)},units:Object.fromEntries(['qualify','preflight','worker'].map(mode=>[mode,{name:`coatria-reference-${id}-${mode}.service`,sha256:hash(mode)}])) as Record<'qualify'|'preflight'|'worker',{name:string;sha256:string}>};
 const sourcePaths=['scripts/hosting/media-sandbox-launch.c','scripts/hosting/media-sandbox-probe.c','scripts/hosting/prepare-media-sandbox-ci.mjs','scripts/hosting/run-media-sandbox-ci.mjs','scripts/hosting/media-sandbox-linux-canary.mts','scripts/hosting/media-sandbox-startup-diagnostic.mts','scripts/hosting/prepare-media-apparmor-ci.mjs','scripts/hosting/collect-media-apparmor-ci.mjs','src/lib/higgsfield-media-sandbox.ts','src/lib/higgsfield-media-inspection.ts','scripts/hosting/reference-worker-linux-canary.mts','scripts/hosting/media-sandbox-cgroup-observer.mjs','src/lib/higgsfield-reference-worker.ts','src/lib/higgsfield-references-protocol.ts','src/lib/higgsfield-reference-transport.ts'];
 const bundle={files:sourcePaths.map(path=>({path:'source/'+path,sha256:hash(path)}))};
 // Synthetic contract fixture only. Native Linux proof is required separately.
 const report={qualified:true,runpodQualified:false,noProviderCalls:true,profiles:host.profiles,aggregateParentLimits:{'memory.max':'2147483648','memory.swap.max':'0','pids.max':'256','cpu.max':'200000 100000'},tests:['boundary','file-descriptor-cap','pids-aggregate-cap','memory-aggregate-cap','aggregate-cpu-bandwidth','normal-exit-descendant-cleanup','deadline-kills-descendants','abort-kills-descendants','supervisor-sigkill-descendant-cleanup','invalid-pin-and-writable-input-denied'].map(name=>({name,passed:true})),realFormats:['png','jpeg','webp','mp4','mov','wav','mp3'].map(format=>({format,verification:'full_decode'})),realDecoderEvents:Array.from({length:23},()=>({drained:true})),sourceHashes:Object.fromEntries(sourcePaths.map(path=>[path,hash(path)])),referenceWorkerIntegration:{version:1,kind:'reference-worker-synthetic-linux-integration',passed:true,productionQualified:false,installedServiceQualified:false,enrollmentExercised:false,providerCalls:0,syntheticAuthority:true,syntheticStorage:true,actualLinuxInspector:true,unchangedPreparedImages:true,cases:['png','jpeg','webp','wrong-kind','corrupt-png','cancel-native'].map((name,index)=>({name,passed:true,drainedAtReturn:true,scratchEmptyAtReturn:true,scratchHandlesClosedAtReturn:true,sourceUnchanged:true,nativeExecutions:[3,3,3,0,1,1][index],nativeEvidence:Array.from({length:[3,3,3,0,1,1][index]},()=>({drained:true})),status:index<3?'awaiting_approval':'failed',inspectionRecorded:index<3,cancelledDuringNativeRun:index===5,observedProcesses:index===3?0:1}))}};
 const observed={bootId:randomUUID(),invocationId:'2'.repeat(32),uid:host.uid,gid:host.gid,serviceRoot:'/sys/fs/cgroup/system.slice/'+host.units.qualify.name};
 const state={LoadState:'loaded',ActiveState:'active',SubState:'exited',MainPID:'0',ExecMainPID:'4321',ControlPID:'0',Result:'success',ExecMainStatus:'0',InvocationID:observed.invocationId,FragmentPath:'/etc/systemd/system/'+host.units.qualify.name,DropInPaths:'',NeedDaemonReload:'no',Transient:'no',UnitFileState:'static',User:'coatria-reference',Group:'coatria-reference'};
 const rawState=(value:Record<string,string>=state)=>REFERENCE_QUALIFIER_STATE_PROPERTIES.split(',').map(key=>key+'='+value[key]).join('\n');
 const hostBytes=json(host),reportBytes=json(report),evidence=()=>makeReferenceHostEvidence(host,hostBytes,bundle,reportBytes,observed),receipt=()=>makeReferenceHostReceipt(host,hostBytes,bundle,json(evidence()),reportBytes,observed,now);
 const expected={evidencePath:`/var/lib/coatria-reference-worker/${id}/evidence/qualification-${randomUUID()}/host-evidence.json`,evidenceSha256:hash(json(evidence())),reportPath:'/fixed/qualification.json',reportSha256:hash(reportBytes)};
 const journal={_SYSTEMD_INVOCATION_ID:observed.invocationId,_SYSTEMD_UNIT:host.units.qualify.name,_PID:state.ExecMainPID,_UID:String(host.uid),_GID:String(host.gid),_EXE:release+'/runtime/node',_TRANSPORT:'stdout',MESSAGE:JSON.stringify({event:'reference-host-qualified',...expected,qualified:true,enrolled:false,workerEnabled:false})};
 return {host,hostBytes,bundle,report,reportBytes,observed,now,evidence,receipt,state,rawState,expected,journal};
}
test('qualification environment rejects credentials and process/network injection without reading their values',()=>{
 assert.doesNotThrow(()=>assertReferenceHostQualificationEnvironment({LANG:'C',NODE_ENV:'production',INVOCATION_ID:'2'.repeat(32)}));
 for(const key of ['DATABASE_URL','COATRIA_REFERENCE_SERVICE_TOKEN','COATRIA_HOSTING_KEYRING','AWS_SECRET_ACCESS_KEY','NODE_OPTIONS','NODE_PATH','NODE_EXTRA_CA_CERTS','NODE_USE_ENV_PROXY','SSL_CERT_FILE','SSL_CERT_DIR','HTTP_PROXY','HTTPS_PROXY','ALL_PROXY','http_proxy','https_proxy','all_proxy','LD_PRELOAD','LD_LIBRARY_PATH'])assert.throws(()=>assertReferenceHostQualificationEnvironment({[key]:'private-value'}),error=>error instanceof Error&&error.message==='REFERENCE_HOST_QUALIFICATION_REJECTED');
});
test('installed CLI accepts only exact distinct qualification, crash-child or reviewed root acceptance shapes',()=>{
 const f=fixture(),hostPath=`/etc/coatria-reference/${f.host.scope.serviceId}/host.json`,normal=['--host',hostPath,'--bundle',f.host.bundleSha256],accept=['--accept-qualification',...normal,'--evidence',f.expected.evidencePath,'--sha256',f.expected.evidenceSha256];
 assert.deepEqual(parseReferenceHostQualificationArguments(normal),{mode:'qualify',hostPath,bundleSha256:f.host.bundleSha256});assert.deepEqual(parseReferenceHostQualificationArguments(['--supervisor-crash-child']),{mode:'crash-child'});
 assert.deepEqual(parseReferenceHostQualificationArguments(accept),{mode:'accept',hostPath,bundleSha256:f.host.bundleSha256,evidencePath:f.expected.evidencePath,evidenceSha256:f.expected.evidenceSha256});assert.equal((parseReferenceHostQualificationArguments([...accept,'--previous','1'.repeat(64)]) as {previousReceiptSha256:string}).previousReceiptSha256,'1'.repeat(64));
 for(const args of [[],normal.slice(0,3),[...normal,'--preflight'],['--supervisor-crash-child',...normal],[...accept,'--previous','invalid'],[...accept,'--yes'],accept.map(v=>v===hostPath?'/tmp/host.json':v),accept.map(v=>v===f.expected.evidencePath?v.replace(f.host.scope.serviceId,randomUUID()):v),accept.map(v=>v==='--sha256'?'--token':v),[...accept,'--previous','1'.repeat(64),'--previous','2'.repeat(64)]])assert.throws(()=>parseReferenceHostQualificationArguments(args));
});
test('only successful retained exact qualification invocation is acceptable',()=>{
 const f=fixture();assert.equal(referenceHostQualificationInvocation(f.rawState(),f.host),f.observed.invocationId);assert.equal(referenceHostQualificationState(f.rawState(),f.host).ExecMainPID,'4321');
 for(const patch of [{ActiveState:'inactive'},{SubState:'dead'},{MainPID:'4321'},{ControlPID:'12'},{ExecMainPID:'0'},{ExecMainPID:'NaN'},{Result:'exit-code'},{ExecMainStatus:'1'},{InvocationID:'0'.repeat(32)},{FragmentPath:'/tmp/qualify.service'},{DropInPaths:'/etc/override.conf'},{NeedDaemonReload:'yes'},{Transient:'yes'},{UnitFileState:'enabled'},{User:'root'},{Group:'root'}])assert.throws(()=>referenceHostQualificationState(f.rawState({...f.state,...patch}),f.host));
 assert.throws(()=>referenceHostQualificationState(f.rawState(),f.host,'3'.repeat(32)));assert.throws(()=>referenceHostQualificationState(f.rawState()+'\nMainPID=0',f.host));assert.throws(()=>referenceHostQualificationState(f.rawState().replace('MainPID=0\n',''),f.host));
});
test('trusted journal record pins exact completed main process and both reviewed hashes',()=>{
 const f=fixture(),proof=referenceHostJournalProof(json(f.journal).trim().replace(/\n/g,''),f.host,f.state,f.expected);assert.equal(proof.evidenceSha256,f.expected.evidenceSha256);assert.equal(proof.invocationId,f.observed.invocationId);assert.equal(proof.enrolled,false);assert.equal(proof.workerEnabled,false);
 const unrelated={MESSAGE:'private-other-log'};assert.equal(referenceHostJournalProof(JSON.stringify(unrelated)+'\n'+JSON.stringify(f.journal),f.host,f.state,f.expected).reportSha256,f.expected.reportSha256);assert(!JSON.stringify(proof).includes('private-other-log'));
 for(const patch of [{_SYSTEMD_INVOCATION_ID:'3'.repeat(32)},{_SYSTEMD_UNIT:f.host.units.worker.name},{_PID:'4322'},{_UID:'0'},{_GID:'0'},{_EXE:'/usr/bin/node'},{_TRANSPORT:'journal'},{MESSAGE:JSON.stringify({...JSON.parse(f.journal.MESSAGE),reportSha256:'0'.repeat(64)})},{MESSAGE:JSON.stringify({...JSON.parse(f.journal.MESSAGE),workerEnabled:true})}])assert.throws(()=>referenceHostJournalProof(JSON.stringify({...f.journal,...patch}),f.host,f.state,f.expected));
 for(const raw of ['',JSON.stringify(f.journal)+'\n'+JSON.stringify(f.journal),'not-json',JSON.stringify({_SYSTEMD_INVOCATION_ID:f.observed.invocationId,MESSAGE:'qualified=true'}),'x'.repeat(1024**2+1)])assert.throws(()=>referenceHostJournalProof(raw,f.host,f.state,f.expected));
});
test('full report requires exact native cases, rejected inputs and cleanup proof',()=>{
 const f=fixture();assert.deepEqual(assertReferenceHostDetailedReport(f.report,f.host,f.bundle),{isolation:true,resourceLimits:true,descendantCleanup:true,preparedImages:true});
 const mutate=[(r:typeof f.report)=>{r.tests.pop();},(r:typeof f.report)=>{r.tests[0].passed=false;},(r:typeof f.report)=>{r.realFormats[0].verification='header';},(r:typeof f.report)=>{r.realDecoderEvents[0].drained=false;},(r:typeof f.report)=>{r.sourceHashes['src/lib/higgsfield-reference-worker.ts']='0'.repeat(64);},(r:typeof f.report)=>{r.referenceWorkerIntegration.providerCalls=1;},(r:typeof f.report)=>{r.referenceWorkerIntegration.installedServiceQualified=true;},(r:typeof f.report)=>{r.referenceWorkerIntegration.cases[0].nativeExecutions=0;},(r:typeof f.report)=>{r.referenceWorkerIntegration.cases[3].inspectionRecorded=true;},(r:typeof f.report)=>{r.referenceWorkerIntegration.cases[5].cancelledDuringNativeRun=false;},(r:typeof f.report)=>{r.referenceWorkerIntegration.cases[5].nativeEvidence[0].drained=false;},(r:typeof f.report)=>{r.referenceWorkerIntegration.cases[5].nativeExecutions=4;r.referenceWorkerIntegration.cases[5].nativeEvidence=Array.from({length:4},()=>({drained:true}));}];
 for(const count of [1,2,3]){const report=structuredClone(f.report);for(const index of [4,5]){report.referenceWorkerIntegration.cases[index].nativeExecutions=count;report.referenceWorkerIntegration.cases[index].nativeEvidence=Array.from({length:count},()=>({drained:true}));}assert.doesNotThrow(()=>assertReferenceHostDetailedReport(report,f.host,f.bundle));}
 for(const change of mutate){const report=structuredClone(f.report);change(report);assert.throws(()=>assertReferenceHostDetailedReport(report,f.host,f.bundle));}
 for(const key of ['drainedAtReturn','scratchEmptyAtReturn','scratchHandlesClosedAtReturn','sourceUnchanged']){const report=structuredClone(f.report);Object.assign(report.referenceWorkerIntegration.cases[0],{[key]:false});assert.throws(()=>assertReferenceHostDetailedReport(report,f.host,f.bundle));}
});
test('evidence binds immutable installation and separately observed qualifier cgroup',async()=>{
 const f=fixture(),evidence=f.evidence(),receipt=f.receipt(),configuration=deriveReferenceRunnerConfiguration(f.host,'0'.repeat(64));
 assert.equal(evidence.hostConfigurationSha256,hash(f.hostBytes));assert.equal(evidence.configurationSha256,referenceRunnerConfigurationHash(configuration));assert.equal(evidence.serviceRoot,f.observed.serviceRoot);assert.equal(configuration.cgroupRoot,`/sys/fs/cgroup/system.slice/${f.host.units.worker.name}/decoders`);assert.notEqual(evidence.serviceRoot+'/decoders',configuration.cgroupRoot);
 const modulePath='../scripts/hosting/reference-runner-configuration.mts';const {assertReferenceRunnerReceipt}=await import(modulePath);assert.doesNotThrow(()=>assertReferenceRunnerReceipt(receipt,configuration,{...f.observed,host:f.host,hostConfigurationSha256:hash(f.hostBytes)},f.now));
 for(const patch of [{uid:f.host.uid+1},{gid:f.host.gid+1},{bootId:'invalid'},{invocationId:'0'.repeat(32)},{serviceRoot:'/sys/fs/cgroup/system.slice/'+f.host.units.worker.name}])assert.throws(()=>makeReferenceHostEvidence(f.host,f.hostBytes,f.bundle,f.reportBytes,{...f.observed,...patch}));
});
test('receipt rejects stale boot/invocation, bytes, profile, unit, scope and expired authority',()=>{
 const f=fixture(),evidenceBytes=json(f.evidence());
 for(const patch of [{bootId:randomUUID()},{invocationId:'3'.repeat(32)}])assert.throws(()=>makeReferenceHostReceipt(f.host,f.hostBytes,f.bundle,evidenceBytes,f.reportBytes,{...f.observed,...patch},f.now));
 assert.throws(()=>makeReferenceHostReceipt(f.host,f.hostBytes+' ',f.bundle,evidenceBytes,f.reportBytes,f.observed,f.now));assert.throws(()=>makeReferenceHostReceipt(f.host,f.hostBytes,f.bundle,evidenceBytes,f.reportBytes+' ',f.observed,f.now));
 for(const modify of [(h:typeof f.host)=>{h.scope.projectIds=[randomUUID()];},(h:typeof f.host)=>{h.tree='0'.repeat(40);},(h:typeof f.host)=>{h.worker.sha256='0'.repeat(64);},(h:typeof f.host)=>{h.qualifier.sha256='0'.repeat(64);},(h:typeof f.host)=>{h.units.qualify.sha256='0'.repeat(64);},(h:typeof f.host)=>{h.profiles.real.expectedProfileSha256='0'.repeat(64);}]){const host=structuredClone(f.host);modify(host);assert.throws(()=>makeReferenceHostReceipt(host,f.hostBytes,f.bundle,evidenceBytes,f.reportBytes,f.observed,f.now));}
 assert.throws(()=>makeReferenceHostReceipt(f.host,f.hostBytes,f.bundle,evidenceBytes,f.reportBytes,f.observed,Date.parse(f.host.scope.expiresAt)));assert.throws(()=>makeReferenceHostReceipt(f.host,f.hostBytes,f.bundle,evidenceBytes,f.reportBytes,f.observed,f.now-3600000));
});
test('receipt replacement is exact CAS with explicit same-evidence replay and no legacy receipt acceptance',()=>{
 const f=fixture(),receipt=f.receipt(),prior=json(receipt);assert.deepEqual(referenceHostReceiptReplacement(undefined,receipt),{replayed:false,previousSha256:null});assert.throws(()=>referenceHostReceiptReplacement(undefined,receipt,'0'.repeat(64)));
 const replay=referenceHostReceiptReplacement(prior,{...receipt,acceptedAt:new Date(f.now+1000).toISOString()});assert.equal(replay.replayed,true);assert.deepEqual(replay.receipt,receipt);
 const newer={...receipt,qualifierInvocationId:'3'.repeat(32)};assert.throws(()=>referenceHostReceiptReplacement(prior,newer));assert.throws(()=>referenceHostReceiptReplacement(prior,newer,'0'.repeat(64)));assert.deepEqual(referenceHostReceiptReplacement(prior,newer,hash(prior)),{replayed:false,previousSha256:hash(prior)});assert.throws(()=>referenceHostReceiptReplacement(prior,receipt,'0'.repeat(64)));assert.throws(()=>referenceHostReceiptReplacement('{"version":1,"qualified":true}',receipt));
});
test('acceptance fails before file access on unsupported platform or unreviewed hash',async()=>{
 await assert.rejects(acceptReferenceHostQualification('/private/nonexistent','a'.repeat(64),'/private/evidence','invalid'));
 if(process.platform!=='linux')await assert.rejects(acceptReferenceHostQualification('/private/nonexistent','a'.repeat(64),'/private/evidence','b'.repeat(64)),/REFERENCE_HOST_QUALIFICATION_REJECTED/);
});
test('qualification acceptance is importable by plain Node tooling without source TypeScript runtime imports',async()=>{
 const source=await readFile(new URL('../scripts/hosting/reference-host-qualification.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/from ['"][^'"]+\.mts['"]/);assert.doesNotMatch(source,/from ['"][^'"]*(?:installer|run-reference-worker)/);
});
