import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {link,mkdir,mkdtemp,readFile,readdir,rm,symlink,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {dirname,join} from 'node:path';
import test from 'node:test';
import {ARCHIVE_RUNTIME_EMPTY_DIRECTORIES,archiveHostHash,parseArchiveRuntime,createArchiveEmptyDirectories,copyArchiveFiles} from '../scripts/hosting/archive-host-package.mjs';
import {REFERENCE_HOST_PINS,REFERENCE_HOST_SOURCE_FILES,parseReferenceHostBundle,parseReferenceHostScope,parseReferenceServiceBundle,referenceHostUnit,referenceHostUnitName,referenceHostProfiles,referenceHostInstallPlan,createReferenceHostConfiguration,parseReferenceHostConfiguration,inspectReferenceHostBundle} from '../scripts/hosting/reference-host-package.mjs';
import {buildReferenceHostBundle} from '../scripts/hosting/build-reference-host-bundle.mjs';
import {assertReferenceHostUnloadedUnit,assertReferenceHostUnitsAbsent,assertReferenceHostVacantBase,claimReferenceHostInstallation,installReferenceHost,readReferenceInstallScope} from '../scripts/hosting/install-reference-host.mjs';
const git=(cwd:string,args:string[])=>{const r=spawnSync('git',['-c','core.autocrlf=false','-c','user.name=Reference Fixture','-c','user.email=reference@example.invalid','-C',cwd,...args],{encoding:'utf8',timeout:10000,maxBuffer:1024*1024});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};
const id='10000000-0000-4000-8000-000000000001';
const scopeInput=()=>({version:1,serviceId:id,companyId:'20000000-0000-4000-8000-000000000001',projectIds:['30000000-0000-4000-8000-000000000001'],origin:'https://coatria.example',expiresAt:new Date(Date.now()+3500000).toISOString(),uploadHosts:['uploads.example.invalid']});
async function fixture(){
 const temp=await mkdtemp(join(tmpdir(),'coatria-reference-package-')),repo=join(temp,'repo'),runtime=join(temp,'runtime'),worker=join(temp,'worker'),qualifier=join(temp,'qualifier');for(const path of [repo,runtime,worker,qualifier])await mkdir(path);
 const source=new Map<string,Buffer>();for(const path of [...REFERENCE_HOST_SOURCE_FILES,'scripts/hosting/run-reference-worker.mts','scripts/hosting/qualify-reference-host.mts'])source.set(path,Buffer.from('Original synthetic offline packaging fixture: '+path+'\n'));
 source.set('package.json',Buffer.from('{"name":"reference-package-fixture"}\n'));source.set('package-lock.json',Buffer.from(JSON.stringify({lockfileVersion:3,packages:{'node_modules/esbuild':{version:'0.28.2',integrity:'sha512-b3JpZ2luYWxmaXh0dXJl'}}})+'\n'));
 for(const[path,bytes]of source){await mkdir(dirname(join(repo,path)),{recursive:true});await writeFile(join(repo,path),bytes);}git(repo,['init','--quiet']);git(repo,['add','.']);git(repo,['commit','--quiet','-m','Original offline reference package fixture']);const commit=git(repo,['rev-parse','HEAD']),tree=git(repo,['rev-parse','HEAD^{tree}']);
 const entries=[];for(const path of ['node','media-sandbox-launch','media/real/bin/ffmpeg','media/real/bin/ffprobe','media/conformance/bin/ffmpeg','media/conformance/bin/ffprobe','node_modules/tsx/package.json','node_modules/pg/package.json','node_modules/undici/index.js']){const bytes=Buffer.from(path.includes('conformance')?'Original synthetic conformance program':path+' synthetic non-runtime bytes'),mode=path.startsWith('node_modules/')?0o444:0o555;await mkdir(dirname(join(runtime,path)),{recursive:true});await writeFile(join(runtime,path),bytes);entries.push({path,bytes:bytes.length,sha256:archiveHostHash(bytes),mode});}
 await createArchiveEmptyDirectories(runtime,ARCHIVE_RUNTIME_EMPTY_DIRECTORIES);
 const rt=parseArchiveRuntime({version:1,platform:'linux-x64',pins:REFERENCE_HOST_PINS,sourceHashes:{launcher:archiveHostHash(source.get('scripts/hosting/media-sandbox-launch.c')!),probe:archiveHostHash(source.get('scripts/hosting/media-sandbox-probe.c')!)},packageLockSha256:archiveHostHash(source.get('package-lock.json')!),bubblewrapSha256:'a'.repeat(64),files:entries,emptyDirectories:ARCHIVE_RUNTIME_EMPTY_DIRECTORIES}),raw=JSON.stringify(rt)+'\n';await writeFile(join(runtime,'runtime-manifest.json'),raw);
 const parts:any={};for(const [service,path,entry]of [['reference',worker,'scripts/hosting/run-reference-worker.mts'],['reference-qualification',qualifier,'scripts/hosting/qualify-reference-host.mts']]){const program=Buffer.from('export const syntheticPackagingFixture = '+JSON.stringify(service)+';\n'),dependency=entries.find(f=>f.path==='node_modules/undici/index.js')!,b={version:1,kind:'coatria-trusted-service-bundle',service,sourceCommit:commit,sourceTree:tree,image:REFERENCE_HOST_PINS.nodeImage,nodeVersion:REFERENCE_HOST_PINS.nodeVersion,compiler:{name:'esbuild',version:'0.28.2',packageIntegrity:'sha512-b3JpZ2luYWxmaXh0dXJl'},packageLockSha256:rt.packageLockSha256,inputs:[{path:entry,bytes:source.get(entry)!.length,sha256:archiveHostHash(source.get(entry)!),kind:'source'},{path:dependency.path,bytes:dependency.bytes,sha256:dependency.sha256,kind:'dependency'}],runtime:{path:'runtime.mjs',bytes:program.length,sha256:archiveHostHash(program)},deployable:true,qualified:false},bytes=JSON.stringify(b,null,2)+'\n';await writeFile(join(path,'runtime.mjs'),program);await writeFile(join(path,'bundle.json'),bytes);parts[service]={bundle:b,sha256:archiveHostHash(bytes)};}
 const input={sourceRoot:repo,commit,runtimeRoot:runtime,runtimeManifestSha256:archiveHostHash(raw),workerBundlePath:worker,workerBundleSha256:parts.reference.sha256,qualifierBundlePath:qualifier,qualifierBundleSha256:parts['reference-qualification'].sha256};return {temp,repo,runtime,worker,qualifier,commit,tree,source,rt,parts,input};
}
test('reference package copies exact Git/source/native bytes and standalone programs without node_modules or qualified claims',async t=>{
 const f=await fixture();t.after(()=>rm(f.temp,{recursive:true,force:true}));await writeFile(join(f.repo,'src/lib/higgsfield-reference-worker.ts'),'Uncommitted source must not enter release');await writeFile(join(f.repo,'.env.private'),'Excluded synthetic private material');
 const result=await buildReferenceHostBundle({...f.input,output:join(f.temp,'bundle')}),bundle=await inspectReferenceHostBundle(result.output,result.bundleSha256,{trusted:false});assert.equal(result.qualified,false);assert.equal(result.providerCalls,false);assert.equal(result.servicesEnabled,false);assert.equal(bundle.commit,f.commit);assert.equal(bundle.tree,f.tree);assert.equal(bundle.files.some((e:{path:string})=>e.path.includes('node_modules/')||e.path.includes('.env')),false);assert.equal(bundle.runtime.files.length,6);assert.equal(bundle.files.filter((e:{path:string})=>e.path.startsWith('source/tests/fixtures/media/')).length,7);assert.notEqual(bundle.worker.bundleSha256,bundle.worker.bundle.runtime.sha256);assert.deepEqual(await readFile(join(result.output,'source/src/lib/higgsfield-reference-worker.ts')),f.source.get('src/lib/higgsfield-reference-worker.ts'));
 const target=join(f.temp,'installed-copy');await mkdir(target);await copyArchiveFiles(result.output,target,bundle.files,{emptyDirectories:bundle.emptyDirectories});await writeFile(join(target,'bundle.json'),await readFile(join(result.output,'bundle.json')));await inspectReferenceHostBundle(target,result.bundleSha256,{trusted:false});for(const directory of bundle.emptyDirectories)assert.deepEqual(await readdir(join(target,directory.path)),[]);
 await writeFile(join(target,'unexpected.env'),'Excluded');await assert.rejects(inspectReferenceHostBundle(target,result.bundleSha256,{trusted:false}));
});
test('composition rejects reviewed digest, provenance, service and output containment mismatches before creating output',async t=>{
 const f=await fixture();t.after(()=>rm(f.temp,{recursive:true,force:true}));for(const output of [join(f.repo,'out'),join(f.runtime,'out'),join(f.worker,'out'),join(f.qualifier,'out')])await assert.rejects(buildReferenceHostBundle({...f.input,output}));
 for(const change of [{runtimeManifestSha256:'0'.repeat(64)},{workerBundleSha256:'0'.repeat(64)},{qualifierBundleSha256:'0'.repeat(64)},{workerBundlePath:f.qualifier,workerBundleSha256:f.parts['reference-qualification'].sha256}])await assert.rejects(buildReferenceHostBundle({...f.input,...change,output:join(f.temp,'rejected')}));
 const bad=structuredClone(f.parts.reference.bundle);bad.sourceTree='b'.repeat(40);const raw=JSON.stringify(bad,null,2)+'\n';await writeFile(join(f.worker,'bundle.json'),raw);await assert.rejects(buildReferenceHostBundle({...f.input,workerBundleSha256:archiveHostHash(raw),output:join(f.temp,'wrong-tree')}));
});
test('dependency byte provenance is checked against full pinned exporter input even though modules are not installed',async t=>{
 const f=await fixture();t.after(()=>rm(f.temp,{recursive:true,force:true}));const bad=structuredClone(f.parts.reference.bundle);bad.inputs[1].sha256='b'.repeat(64);const raw=JSON.stringify(bad,null,2)+'\n';await writeFile(join(f.worker,'bundle.json'),raw);await assert.rejects(buildReferenceHostBundle({...f.input,workerBundleSha256:archiveHostHash(raw),output:join(f.temp,'wrong-dependency')}));
});
test('native manifest and program parser reject injected files, permissions, wrong compiler and disallowed credential drivers',async t=>{
 const f=await fixture();t.after(()=>rm(f.temp,{recursive:true,force:true}));const result=await buildReferenceHostBundle({...f.input,output:join(f.temp,'bundle')}),bundle=await inspectReferenceHostBundle(result.output,result.bundleSha256,{trusted:false});
 for(const mutate of [(v:any)=>v.runtime.files.push({path:'node_modules/pg/index.js',bytes:1,sha256:'1'.repeat(64),mode:0o444}),(v:any)=>v.runtime.files[0].path='../node',(v:any)=>v.runtime.files[0].mode=0o444,(v:any)=>v.files.push({...v.files[0]}),(v:any)=>v.emptyDirectories.pop(),(v:any)=>v.credentials={},(v:any)=>v.worker.bundle.qualified=true,(v:any)=>v.worker.bundle.compiler.version='latest']){const b=structuredClone(bundle);mutate(b);assert.throws(()=>parseReferenceHostBundle(b));}
 for(const path of ['node_modules/pg/index.js','node_modules/@aws-sdk/client-s3/index.js','src/.env.private']){const b=structuredClone(f.parts.reference.bundle);b.inputs.push({path,bytes:1,sha256:'1'.repeat(64),kind:path.startsWith('node_modules/')?'dependency':'source'});assert.throws(()=>parseReferenceServiceBundle(b,'reference'));}
 await link(join(f.runtime,'node'),join(f.temp,'hardlink'));await assert.rejects(buildReferenceHostBundle({...f.input,output:join(f.temp,'linked')}));
});
test('Git replacement objects cannot alter the selected exact source and symlink blobs cannot enter the package',async t=>{
 const f=await fixture();t.after(()=>rm(f.temp,{recursive:true,force:true}));await writeFile(join(f.repo,'src/lib/higgsfield-reference-worker.ts'),'Alternate original synthetic fixture\n');git(f.repo,['add','.']);git(f.repo,['commit','--quiet','-m','Alternate original source']);git(f.repo,['replace',f.commit,git(f.repo,['rev-parse','HEAD'])]);const result=await buildReferenceHostBundle({...f.input,output:join(f.temp,'original')});assert.deepEqual(await readFile(join(result.output,'source/src/lib/higgsfield-reference-worker.ts')),f.source.get('src/lib/higgsfield-reference-worker.ts'));
 const blob=git(f.repo,['rev-parse','HEAD:scripts/hosting/media-sandbox-launch.c']);git(f.repo,['update-index','--cacheinfo','120000,'+blob+',scripts/hosting/media-sandbox-launch.c']);git(f.repo,['commit','--quiet','-m','Synthetic source symlink']);await assert.rejects(buildReferenceHostBundle({...f.input,commit:git(f.repo,['rev-parse','HEAD']),output:join(f.temp,'symlink-source')}));
});
test('finite reviewed scope rejects arbitrary origins, wildcards, duplicate authority and extra credential fields',()=>{
 const now=Date.now(),value=scopeInput();assert.equal(parseReferenceHostScope(value,now).serviceId,id);
 for(const change of [{expiresAt:new Date(now).toISOString()},{expiresAt:new Date(now+3600001).toISOString()},{origin:'https://127.0.0.1'},{origin:'https://user:pass@example.invalid'},{origin:'https://coatria.example/path'},{origin:'https://coatria.example:443'},{uploadHosts:['*.example.invalid']},{uploadHosts:['127.0.0.1']},{uploadHosts:['UPPER.example']},{projectIds:[value.projectIds[0],value.projectIds[0]]},{uploadHosts:['uploads.example.invalid','uploads.example.invalid']},{token:'synthetic-value'}])assert.throws(()=>parseReferenceHostScope({...value,...change},now));
});
test('units are exact, disabled, finite and credential-free during qualification; host config pins every derived profile and unit',async t=>{
 const f=await fixture();t.after(()=>rm(f.temp,{recursive:true,force:true}));const result=await buildReferenceHostBundle({...f.input,output:join(f.temp,'bundle')}),bundle=await inspectReferenceHostBundle(result.output,result.bundleSha256,{trusted:false}),scope=parseReferenceHostScope(scopeInput()),plan=referenceHostInstallPlan(bundle,result.bundleSha256,scope),host=createReferenceHostConfiguration(bundle,result.bundleSha256,scope,{uid:1001,gid:1001});assert.deepEqual(parseReferenceHostConfiguration(host,bundle),host);assert.equal(plan.qualified,false);assert.equal(plan.credentialsIncluded,false);
 for(const mode of ['qualify','preflight','worker']){const unit=referenceHostUnit(mode,plan.release,result.bundleSha256,id);assert.match(unit,/^User=coatria-reference$/m);assert.match(unit,/^DelegateSubgroup=supervisor$/m);assert.match(unit,/^KillMode=control-group$/m);assert.match(unit,/^Restart=no$/m);assert.match(unit,/^TimeoutStopSec=45$/m);assert.match(unit,/^SendSIGKILL=yes$/m);assert.doesNotMatch(unit,/^\[Install\]|^WantedBy=|^StateDirectory=|^ExecStart=.*(?:npm|curl|wget|sudo)|--sha256/m);assert.ok(unit.includes('--host /etc/coatria-reference/'+id+'/host.json --bundle '+result.bundleSha256));}
 assert.doesNotMatch(plan.units[0].content,/^EnvironmentFile=/m);assert.match(plan.units[0].content,/^RemainAfterExit=yes$/m);assert.match(plan.units[1].content,/--preflight$/m);assert.match(plan.units[2].content,/^RuntimeMaxSec=3600$/m);assert.match(plan.units[2].content,/^EnvironmentFile=.*\/worker.env$/m);assert.equal(host.worker.sha256,bundle.worker.bundle.runtime.sha256);assert.equal(host.profiles.real.expectedProfileSha256,archiveHostHash(JSON.stringify(referenceHostProfiles(bundle,plan.release).real,null,2)+'\n'));
 for(const mutate of [(v:any)=>v.uid=0,(v:any)=>v.tree='a'.repeat(40),(v:any)=>v.scope.projectIds.push(id),(v:any)=>v.worker.sha256='b'.repeat(64),(v:any)=>v.profiles.real.profilePath='/tmp/untrusted',(v:any)=>v.units.worker.sha256='c'.repeat(64)]){const changed=structuredClone(host);mutate(changed);if(changed.scope.projectIds.length>1){assert.doesNotThrow(()=>parseReferenceHostConfiguration(changed,bundle),'host scope authority is the separately pinned reviewed root JSON');}else assert.throws(()=>parseReferenceHostConfiguration(changed,bundle));}
});
test('disabled installer checks masks, drop-ins, enabled links and loaded manager state without deleting them',async t=>{
 const temp=await mkdtemp(join(tmpdir(),'coatria-reference-unit-test-'));t.after(()=>rm(temp,{recursive:true,force:true}));const names=['qualify','preflight','worker'].map(m=>referenceHostUnitName(id,m));await assertReferenceHostUnitsAbsent(names,[temp]);
 for(const relative of [names[0],names[0]+'.d','service.d','coatria-reference-.service.d','multi-user.target.wants/'+names[0],'coatria-reference-20000000-0000-4000-8000-000000000002-worker.service']){const path=join(temp,relative);await mkdir(dirname(path),{recursive:true});await writeFile(path,'preserved fixture');await assert.rejects(assertReferenceHostUnitsAbsent(names,[temp]));assert.equal(await readFile(path,'utf8'),'preserved fixture');await rm(path);}
 const state={LoadState:'not-found',ActiveState:'inactive',FragmentPath:'',DropInPaths:'',UnitFileState:''},raw=(v:Record<string,string>)=>Object.entries(v).map(([k,v])=>k+'='+v).join('\n');assert.doesNotThrow(()=>assertReferenceHostUnloadedUnit(raw(state)));for(const change of [{LoadState:'loaded'},{ActiveState:'active'},{FragmentPath:'/tmp/foreign'},{DropInPaths:'/tmp/dropin'},{UnitFileState:'enabled'}])assert.throws(()=>assertReferenceHostUnloadedUnit(raw({...state,...change})));
 const empty=join(temp,'empty');await mkdir(empty);await assertReferenceHostVacantBase(empty);const linked=join(temp,'linked');await symlink(empty,linked,process.platform==='win32'?'junction':'dir');await assert.rejects(assertReferenceHostVacantBase(linked));await rm(linked);await writeFile(join(empty,'prior-private-evidence'),'preserve');await assert.rejects(assertReferenceHostVacantBase(empty));assert.equal(await readFile(join(empty,'prior-private-evidence'),'utf8'),'preserve');
});
test('scope file requires its exact reviewed digest and non-root-platform installation performs no writes',async t=>{
 const temp=await mkdtemp(join(tmpdir(),'coatria-reference-install-test-'));t.after(()=>rm(temp,{recursive:true,force:true}));const path=join(temp,'scope.json'),raw=JSON.stringify(scopeInput())+'\n';await writeFile(path,raw);assert.equal((await readReferenceInstallScope(path,archiveHostHash(raw))).serviceId,id);await assert.rejects(readReferenceInstallScope(path,'a'.repeat(64)));if(process.platform!=='linux'||process.getuid?.()!==0){await assert.rejects(installReferenceHost(temp,'a'.repeat(64),path,archiveHostHash(raw)));assert.deepEqual(await readdir(temp),['scope.json']);}
});
test('concurrent installation claims retain one service identity and reject all later claims without overwriting',async t=>{
 const temp=await mkdtemp(join(tmpdir(),'coatria-reference-claim-test-'));t.after(()=>rm(temp,{recursive:true,force:true}));const ids=[id,'20000000-0000-4000-8000-000000000001'];
 // Windows cannot fsync an open directory, but wx still determines the single
 // winner before that platform-only failure; the Linux CI proves durable sync.
 const results=await Promise.allSettled(ids.map(serviceId=>claimReferenceHostInstallation(temp,serviceId,'a'.repeat(64))));assert.equal(results.filter(r=>r.status==='rejected'&&(r.reason as NodeJS.ErrnoException).code==='EEXIST').length,1);if(process.platform!=='win32')assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
 const original=await readFile(join(temp,'installation.json')),claim=JSON.parse(original.toString());assert.ok(ids.includes(claim.serviceId));assert.equal(claim.bundleSha256,'a'.repeat(64));await assert.rejects(claimReferenceHostInstallation(temp,id,'b'.repeat(64)));assert.deepEqual(await readFile(join(temp,'installation.json')),original);await assert.rejects(assertReferenceHostVacantBase(temp));
});
