import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,readdir,mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {database,query,transaction} from '../src/lib/db';
import {hashToken,errorResponse} from '../src/lib/security';
import {setupStudio,createStudioProject,studioProjectDetail} from '../src/lib/studio';
import {handleApi} from '../src/lib/api';
import {canonicalStudioMedia,type StudioMediaProvider} from '../src/lib/studio-media';
import {studioClientDeliveryRoute} from '../src/lib/studio-client-delivery';
import {studioClientDeliveryCreateInput,studioClientDeliveryResponseInput} from '../src/lib/studio-client-delivery-protocol';
import {EXECUTION_BUILTIN_PROFILES} from '../src/lib/studio-execution-protocol';
import {studioClientDeliveryPaths,studioClientDeliverySchemas} from '../src/lib/studio-client-delivery-openapi';

type Row=Record<string,any>;
test('client delivery protocol accepts exact account confirmation and rejects bearer identity or arbitrary access',()=>{
 const valid={clientId:randomUUID(),revision:1,deliveryId:randomUUID(),recipientUserId:randomUUID(),identityConfirmation:'confirmed_out_of_band',expiresAt:new Date(Date.now()+3600000).toISOString()};
 assert(studioClientDeliveryCreateInput.safeParse(valid).success);
 for(const extra of[{recipientEmail:'pretend@example.invalid'},{identityConfirmation:'email_verified'},{token:'any-bearer'},{files:[randomUUID()]},{expiresAt:'2026-01-01'},{revision:0}])assert(!studioClientDeliveryCreateInput.safeParse({...valid,...extra}).success);
 assert(!studioClientDeliveryResponseInput.safeParse({clientId:randomUUID(),revision:1,decision:'acknowledged',note:'Confirmed',actorUserId:randomUUID()}).success);
});
test('client delivery API documentation exposes distinct account auth, package checksums and non-transfer receipts',()=>{
 const response=studioClientDeliveryPaths['/api/client-deliveries/{shareId}/responses'].post;
 assert.deepEqual(response.security,[{sessionCookie:[]}]);assert.deepEqual(response['x-coatria-roles'],['designated_authenticated_external_client']);assert.match(response.description,/Neither agents nor administrators/);
 assert((studioClientDeliverySchemas.StudioClientDeliveryAccess as Row).properties.url['x-coatria-sensitive']);assert.equal((studioClientDeliverySchemas.StudioClientDeliveryAccess as Row).properties.bytesReceivedByClient.const,'not_observed');
 assert(studioClientDeliveryPaths['/api/client-deliveries/{shareId}/manifest'].get.responses['200'].headers['X-Content-SHA256']);
});

const emulate=process.env.COATRIA_TEST_EMULATOR==='1',connection=process.env.COATRIA_INTEGRATION_DATABASE_URL;
test('authenticated client delivery enforces immutable package, external authority and truthful receipts',{skip:!emulate&&!connection,timeout:240000},async t=>{
 process.env.DATABASE_URL=connection;process.env.DATABASE_POOL_MAX='4';let stop:(()=>Promise<void>)|undefined;
 if(emulate){const{PGlite}=await import('@electric-sql/pglite');const{PGLiteSocketServer}=await import('@electric-sql/pglite-socket');const db=await PGlite.create();for(const file of(await readdir('database')).filter(file=>/^\d.*\.sql$/.test(file)).sort())await db.exec(await readFile('database/'+file,'utf8'));const server=new PGLiteSocketServer({db,host:'127.0.0.1',port:0,maxConnections:4});await server.start();process.env.DATABASE_URL=`postgresql://postgres:postgres@${server.getServerConn()}/postgres`;stop=async()=>{await server.stop();await db.close();};}
 const companies=[randomUUID(),randomUUID()],users={owner:randomUUID(),reviewer:randomUUID(),member:randomUUID(),client:randomUUID(),otherClient:randomUUID(),foreignOwner:randomUUID()},sessions=Object.fromEntries(Object.keys(users).map(key=>[key,randomUUID()])),origin='http://localhost:4180';
 const spec={width:128,height:128,fpsNumerator:24000,fpsDenominator:1001,format:'exr',colorSpace:'Linear Rec.709'},profile=EXECUTION_BUILTIN_PROFILES[0];let connectorId='',signed=0,onSign:(()=>Promise<void>)|null=null;
 const provider:StudioMediaProvider={signUpload:async()=>{throw new Error('No uploads in this synthetic authority fixture.');},read:async()=>null,signRead:async()=>{signed++;if(onSign)await onSign();return 'https://fixture.invalid/private?temporary=signature';}};
 async function request(path:string,method='GET',payload?:unknown,actor='owner',extraHeaders:Record<string,string>={}){const headers:Record<string,string>={Origin:origin,...actor!=='anonymous'?{Cookie:'coatria_session='+sessions[actor]}:{},...payload!==undefined?{'Content-Type':'application/json'}:{},...extraHeaders};const req=new Request(origin+'/api/'+path,{method,headers,body:payload===undefined?undefined:JSON.stringify(payload)});try{return await studioClientDeliveryRoute(req,path.split('?')[0].split('/'),method,provider)??await handleApi(req,path.split('?')[0].split('/'));}catch(e){return errorResponse(e);}}
 async function call(path:string,method='GET',payload?:unknown,actor='owner',expected=200){const res=await request(path,method,payload,actor),text=await res.text();assert.equal(res.status,expected,`${method} ${path}: ${text}`);return JSON.parse(text);}
 const adminPath=(p:Row)=>`companies/${companies[0]}/studio/projects/${p.projectId}/client-deliveries`;
 const clientPath=(share:Row)=>'client-deliveries/'+share.id;
 async function detail(projectId:string){return transaction(client=>studioProjectDetail(client,companies[0],projectId));}
 async function fresh(){
  const made=await transaction(client=>createStudioProject(client,{companyId:companies[0],userId:users.owner},{clientId:randomUUID(),name:'Synthetic client handoff '+randomUUID().slice(0,8),clientName:'Synthetic QA client',brief:'Isolated authority fixture. No actual rendered media or client decision.',spec,aiPolicy:'allowed',shots:[{code:'SH010',description:'Synthetic frames for protocol tests.',frameStart:1,frameEnd:2,handles:0,disciplines:['compositing']}]})),projectId=made.project.id;
  await query("UPDATE tasks SET status='done' WHERE id IN(SELECT task_id FROM studio_work_items WHERE company_id=$1 AND project_id=$2)",[companies[0],projectId]);
  await query('UPDATE studio_projects SET gates=$3 WHERE company_id=$1 AND id=$2',[companies[0],projectId,JSON.stringify({brief:{decision:'approved'},estimate:{decision:'approved'},production:{decision:'approved'}})]);
  const work=(await query("SELECT id FROM studio_work_items WHERE company_id=$1 AND project_id=$2 AND execution='dcc'",[companies[0],projectId])).rows[0];
  const job=(await query("INSERT INTO studio_execution_jobs(company_id,project_id,work_item_id,connector_id,requested_by,approved_by,profile,spec,input_snapshot,frame_start,frame_end,output_kind,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'[]',1,2,'image_sequence','succeeded') RETURNING id",[companies[0],projectId,work.id,connectorId,users.owner,users.reviewer,JSON.stringify(profile),JSON.stringify(spec)])).rows[0];
  const files=[];for(let frame=1;frame<=2;frame++){const fileId=randomUUID(),bytes=Buffer.from('synthetic-frame-'+frame),sha256=hashToken(bytes.toString()),path=`${job.id}/frames/${frame}.exr`;
   await query("INSERT INTO studio_media_files(id,company_id,project_id,job_id,output_path,kind,frame,sha256,bytes,blob_pathname,content_type) VALUES($1,$2,$3,$4,$5,'image',$6,$7,$8,$9,'image/x-exr')",[fileId,companies[0],projectId,job.id,path,frame,sha256,bytes.length,`studio/${companies[0]}/${job.id}/${sha256}/${fileId}.exr`]);
   await query('INSERT INTO studio_media_verifications(company_id,file_id,etag,sha256,bytes) VALUES($1,$2,$3,$4,$5)',[companies[0],fileId,'synthetic-'+frame,sha256,bytes.length]);files.push({fileId,frame,path,sha256,bytes:bytes.length});}
  const sequence=canonicalStudioMedia({schemaVersion:1,kind:'verified_image_sequence',companyId:companies[0],projectId,jobId:job.id,frameStart:1,frameEnd:2,spec,frames:files}),sha256=hashToken(sequence);
  const artifact=(await query('INSERT INTO studio_artifacts(company_id,project_id,work_item_id,name,version,url,sha256,metadata,produced_by) VALUES($1,$2,$3,$4,1,$5,$6,$7,$8) RETURNING id',[companies[0],projectId,work.id,'Synthetic approved sequence','https://fixture.invalid/immutable-manifest',sha256,JSON.stringify({...spec,frameStart:1,frameEnd:2,notes:'Synthetic fixture only.'}),users.owner])).rows[0];
  await query('INSERT INTO studio_media_promotions(company_id,project_id,job_id,artifact_id,manifest_text,manifest_sha256,promoted_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[companies[0],projectId,job.id,artifact.id,sequence,sha256,users.owner]);
  await query("INSERT INTO studio_reviews(company_id,project_id,artifact_id,decision,note,technical_qc,reviewed_by) VALUES($1,$2,$3,'approved','Synthetic metadata fixture only.',true,$4)",[companies[0],projectId,artifact.id,users.reviewer]);
  const packages=[];for(const name of['Package A','Package B']){const current=await detail(projectId);const result=await call(`companies/${companies[0]}/studio/projects/${projectId}/deliveries`,'POST',{clientId:randomUUID(),revision:current.project.revision,name,artifactIds:[artifact.id],note:'Synthetic package, no real business delivery.'},'owner',201);packages.push(result.delivery);}
  return {projectId,files,artifactId:artifact.id,jobId:job.id,packages,revision:(await detail(projectId)).project.revision};
 }
 async function share(p:Row,extra:Row={},actor='owner',expected=201){return call(adminPath(p),'POST',{clientId:randomUUID(),revision:p.revision,deliveryId:p.packages[0].id,recipientUserId:users.client,identityConfirmation:'confirmed_out_of_band',expiresAt:new Date(Date.now()+3600000).toISOString(),...extra},actor,expected);}
 try{
  for(const [name,userId]of Object.entries(users)){await query('INSERT INTO users(id,name,email,password_hash) VALUES($1,$2,$3,$4)',[userId,name,userId+'@example.invalid','fixture']);await query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '1 hour')",[hashToken(sessions[name]),userId]);}
  for(const companyId of companies)await query("INSERT INTO companies(id,name,slug,template) VALUES($1,'Client portal fixture',$2,'blank')",[companyId,companyId]);
  await query("INSERT INTO memberships(company_id,user_id,role) VALUES($1,$2,'owner'),($1,$3,'admin'),($1,$4,'member'),($5,$6,'owner')",[companies[0],users.owner,users.reviewer,users.member,companies[1],users.foreignOwner]);
  await transaction(client=>setupStudio(client,{companyId:companies[0],userId:users.owner},{clientId:randomUUID(),templateId:'vfx-boutique',templateVersion:1,revision:0,assignments:[]}));
  connectorId=(await query("INSERT INTO studio_execution_connectors(company_id,name,token_hash,profiles,created_by,expires_at) VALUES($1,'Synthetic portal fixture',$2,$3,$4,now()+interval '1 day') RETURNING id",[companies[0],hashToken(randomUUID()),JSON.stringify([profile]),users.owner])).rows[0].id;
  await t.test('creation requires an administrator, exact external account and independently completed handoff',async()=>{
   const p=await fresh();await share(p,{},'member',403);await share(p,{recipientUserId:users.owner},'owner',403);await share(p,{recipientUserId:users.member},'owner',403);await share(p,{recipientUserId:randomUUID()},'owner',403);await share(p,{revision:p.revision+1},'owner',409);await share(p,{expiresAt:new Date(Date.now()+31*86400000).toISOString()},'owner',400);
   await query("UPDATE tasks SET status='todo' WHERE id IN(SELECT task_id FROM studio_work_items WHERE project_id=$1 AND stage='delivery')",[p.projectId]);await share(p,{},'owner',409);await query("UPDATE tasks SET status='done' WHERE id IN(SELECT task_id FROM studio_work_items WHERE project_id=$1 AND stage='delivery')",[p.projectId]);
   const identity=await call('client-deliveries/identity','GET',undefined,'client');assert.equal(identity.user.id,users.client);assert.equal(identity.user.emailVerified,false);assert.equal(identity.identityBasis,'authenticated_account');
   const data={clientId:randomUUID(),expiresAt:new Date(Date.now()+3600000).toISOString()},first=await share(p,data),replay=await share(p,data,'owner',200);assert.equal(first.share.id,replay.share.id);assert.equal(replay.replayed,true);assert.equal(first.share.emailVerifiedAtCreation,false);assert.equal(first.share.transferStatus,'not_observed');assert.equal(first.share.receiptSummary.downloadAccessIssued,0);
   await share(p,{...data,recipientUserId:users.otherClient},'owner',409);assert.equal((await call(adminPath(p))).shares.length,1);await call(adminPath(p)+'?after='+randomUUID(),'GET',undefined,'owner',404);
  });
  await t.test('unverified or external-reference artifacts cannot become client-deliverable by metadata alone',async()=>{
   const p=await fresh();await query('DELETE FROM studio_media_verifications WHERE file_id=$1',[p.files[0].fileId]);await share(p,{},'owner',409);
   const q=await fresh();await query('DELETE FROM studio_media_promotions WHERE project_id=$1',[q.projectId]);await share(q,{},'owner',409);
  });
  await t.test('an invitation is a locator, never a credential; package exposes only exact verified files',async()=>{
   const p=await fresh(),s=(await share(p)).share,foreign=await fresh();
   for(const actor of['owner','reviewer','otherClient','foreignOwner'])await call(clientPath(s),'GET',undefined,actor,404);await call(clientPath(s),'GET',undefined,'anonymous',401);
   const wrongSession=await request(clientPath(s),'GET',undefined,'client',{'X-Coatria-User':users.otherClient});assert.equal(wrongSession.status,409);
   const d=await call(clientPath(s),'GET',undefined,'client');assert.equal(d.package.files.length,2);assert.equal(d.identity.userId,users.client);assert.equal(hashToken(canonicalStudioMedia(d.package)),s.packageSha256);assert(!JSON.stringify(d.package).includes('blob_pathname'));assert(!JSON.stringify(d.package).includes('fixture.invalid'));
   const raw=await request(clientPath(s)+'/manifest','GET',undefined,'client'),text=await raw.text();assert.equal(hashToken(text),raw.headers.get('X-Content-SHA256'));assert.equal(raw.headers.get('Cache-Control'),'private, no-store');assert.equal(raw.headers.get('Referrer-Policy'),'no-referrer');
   await call(clientPath(s)+`/files/${foreign.files[0].fileId}/access`,'POST',{clientId:randomUUID()},'client',404);
   const clientId=randomUUID(),access=await call(clientPath(s)+`/files/${p.files[0].fileId}/access`,'POST',{clientId},'client');assert.equal(access.receipt.actorUserId,users.client);assert.equal(access.receipt.kind,'download_access_issued');assert.equal(access.access.bytesReceivedByClient,'not_observed');assert(Date.parse(access.access.expiresAt)-Date.now()<=60000);
   assert.equal((await call(clientPath(s)+`/files/${p.files[0].fileId}/access`,'POST',{clientId},'client')).replayed,true);assert.equal((await call(clientPath(s),'GET',undefined,'client')).share.receiptSummary.downloadAccessIssued,1);
   const opened=randomUUID();await call(clientPath(s)+'/open','POST',{clientId:opened},'client');await call(clientPath(s)+'/open','POST',{clientId:opened},'client');assert.equal((await call(clientPath(s),'GET',undefined,'client')).share.receiptSummary.portalOpened,1);
   const privateRows=JSON.stringify((await query('SELECT response FROM studio_client_delivery_requests WHERE company_id=$1',[companies[0]])).rows);assert(!privateRows.includes('signature'));assert(!privateRows.includes('fixture.invalid'));assert(!privateRows.includes(sessions.client));
   const otherShare=(await share(foreign)).share,foreignReceipt=await call(clientPath(otherShare)+'/open','POST',{clientId:randomUUID()},'client');await call(clientPath(s)+'?after='+foreignReceipt.receipt.id,'GET',undefined,'client',404);
  });
  await t.test('revocation, expiry, changed membership and removed sponsor fence subsequent file access',async()=>{
   const p=await fresh(),s=(await share(p)).share;
   onSign=async()=>{await call(adminPath(p)+'/'+s.id+'/revoke','POST',{clientId:randomUUID(),revision:1});};await call(clientPath(s)+`/files/${p.files[0].fileId}/access`,'POST',{clientId:randomUUID()},'client',410);onSign=null;
   assert.equal((await call(adminPath(p))).shares[0].receiptSummary.downloadAccessIssued,0);await call(clientPath(s),'GET',undefined,'client',410);await call(clientPath(s)+'/responses','POST',{clientId:randomUUID(),revision:1,decision:'acknowledged',note:'Should be denied'},'client',410);
   const q=await fresh(),expired=(await share(q)).share;await query("UPDATE studio_client_deliveries SET created_at=now()-interval '2 hours',expires_at=now()-interval '1 hour' WHERE id=$1",[expired.id]);await call(clientPath(expired),'GET',undefined,'client',410);
   const r=await fresh(),active=(await share(r)).share;await query("UPDATE memberships SET role='member' WHERE company_id=$1 AND user_id=$2",[companies[0],users.owner]);await call(clientPath(active),'GET',undefined,'client',403);await query("UPDATE memberships SET role='owner' WHERE company_id=$1 AND user_id=$2",[companies[0],users.owner]);
   await query("INSERT INTO memberships(company_id,user_id,role) VALUES($1,$2,'member')",[companies[0],users.client]);await call(clientPath(active),'GET',undefined,'client',403);await query('DELETE FROM memberships WHERE company_id=$1 AND user_id=$2',[companies[0],users.client]);
  });
  await t.test('client requests changes with authentic provenance; response is immutable and retry-safe',async()=>{
   const p=await fresh(),s=(await share(p)).share,payload={clientId:randomUUID(),revision:1,decision:'changes_requested',note:'Synthetic client asks for a revision to frame 2.'};
   await call(clientPath(s)+'/responses','POST',{...payload,revision:2},'client',409);const result=await call(clientPath(s)+'/responses','POST',payload,'client',201);assert.equal(result.receipt.actorUserId,users.client);assert.equal(result.share.response,'changes_requested');assert.equal(result.project.status,'review');assert.equal((await call(clientPath(s)+'/responses','POST',payload,'client')).replayed,true);
   await call(clientPath(s)+'/responses','POST',{...payload,clientId:randomUUID(),revision:2,decision:'acknowledged'},'client',409);const current=await detail(p.projectId);assert.equal(current.project.gates.client_acceptance.decision,'changes_requested');assert.equal((current.project.gates.client_acceptance as Row).source,'authenticated_external_client');assert.equal(current.deliveries.filter(d=>d.status==='acknowledged').length,0);
  });
  await t.test('acknowledgement closes only the chosen exact package and never rewrites transfer evidence',async()=>{
   const p=await fresh(),s=(await share(p,{deliveryId:p.packages[1].id})).share,payload={clientId:randomUUID(),revision:1,decision:'acknowledged',note:'Synthetic client account explicitly reviewed package B.'};
   await call(clientPath(s)+'/responses','POST',payload,'owner',404);const first=await call(clientPath(s)+'/responses','POST',payload,'client',201);assert.equal(first.receipt.packageSha256,s.packageSha256);assert.equal((await call(clientPath(s)+'/responses','POST',payload,'client')).replayed,true);
   const d=await detail(p.projectId);assert.equal(d.project.status,'delivered');assert.equal(d.deliveries.find(item=>item.id===p.packages[0].id)!.status,'prepared');assert.equal(d.deliveries.find(item=>item.id===p.packages[1].id)!.status,'acknowledged');assert(d.deliveries.every(item=>item.manifest.transportStatus==='not_transferred'));assert.equal(d.project.gates.client_acceptance.recordedBy,users.client);assert.equal((d.project.gates.client_acceptance as Row).clientReceiptId,first.receipt.id);
   const persisted=(await query('SELECT source_manifest_hash,package_hash,package_snapshot FROM studio_client_deliveries WHERE id=$1',[s.id])).rows[0];assert.equal(persisted.package_hash,s.packageSha256);assert.equal(hashToken(canonicalStudioMedia(persisted.package_snapshot)),s.packageSha256);assert.equal((await call(clientPath(s),'GET',undefined,'client')).canRespond,false);
  });
  await t.test('superseded approval cannot be acknowledged as the current completed project',async()=>{
   const p=await fresh(),s=(await share(p)).share;await query("UPDATE tasks SET status='todo' WHERE id IN(SELECT task_id FROM studio_work_items WHERE project_id=$1 AND stage='delivery')",[p.projectId]);await call(clientPath(s)+'/responses','POST',{clientId:randomUUID(),revision:1,decision:'acknowledged',note:'Must wait for review'},'client',409);assert.equal((await call(clientPath(s),'GET',undefined,'client')).share.receiptSummary.clientAcknowledged,0);
  });
  await t.test('access receipt ceiling cannot prevent a final client response or administrator revocation',async()=>{
   const p=await fresh(),s=(await share(p)).share;await query("INSERT INTO studio_client_delivery_receipts(company_id,share_id,actor_user_id,kind,package_hash) SELECT $1,$2,$3,'portal_opened',$4 FROM generate_series(1,5000)",[companies[0],s.id,users.client,s.packageSha256]);
   await call(clientPath(s)+'/open','POST',{clientId:randomUUID()},'client',409);
   await call(clientPath(s)+'/responses','POST',{clientId:randomUUID(),revision:1,decision:'changes_requested',note:'Final client response remains possible at the access ceiling.'},'client',201);
   const revoked=await call(adminPath(p)+'/'+s.id+'/revoke','POST',{clientId:randomUUID(),revision:2});assert.equal(revoked.share.status,'revoked');assert.equal(revoked.share.receiptSummary.changesRequested,1);
  });
  await t.test('published artifact references cannot be individually deleted while a client grant exists',async()=>{
   const p=await fresh();await share(p);await assert.rejects(()=>transaction(async client=>{await client.query('DELETE FROM studio_artifacts WHERE id=$1',[p.artifactId]);}), (error:Row)=>error.code==='23503');
   assert.equal((await query('SELECT count(*)::int count FROM studio_artifacts WHERE id=$1',[p.artifactId])).rows[0].count,1);
  });
  await t.test('concurrent identical client responses produce one authentic receipt',{skip:emulate,timeout:15000},async()=>{
   const p=await fresh(),s=(await share(p)).share,payload={clientId:randomUUID(),revision:1,decision:'acknowledged',note:'Concurrent synthetic acknowledgement.'};const results=await Promise.all([request(clientPath(s)+'/responses','POST',payload,'client'),request(clientPath(s)+'/responses','POST',payload,'client')]);assert.deepEqual(results.map(r=>r.status).sort(),[200,201]);assert.equal((await query("SELECT count(*)::int count FROM studio_client_delivery_receipts WHERE share_id=$1 AND kind='acknowledged'",[s.id])).rows[0].count,1);
  });
  await t.test('real React client portal and administrator invitation browser workflow',{skip:process.env.COATRIA_CLIENT_DELIVERY_BROWSER!=='1',timeout:90000},async()=>{
   const p=await fresh(),directory=resolve('.devdata/client-delivery-browser');await mkdir(directory,{recursive:true});const passed:string[]=[],pageErrors:string[]=[];
   const {build}=await import('esbuild'),{chromium}=await import('@playwright/test'),{createServer}=await import('node:http');
   const entry=`import React from 'react';import{createRoot}from'react-dom/client';import{StudioClientPortal,StudioClientDeliveries}from'../src/components/StudioClientDeliveries';import{setClientIdentity}from'../src/lib/client';import '../src/app/globals.css';const owner=${JSON.stringify(users.owner)},p=${JSON.stringify(p)},deliveries=${JSON.stringify((await detail(p.projectId)).deliveries)};if(location.pathname==='/admin'){setClientIdentity(owner);createRoot(document.getElementById('root')!).render(<StudioClientDeliveries companyId=${JSON.stringify(companies[0])} projectId={p.projectId} projectRevision={p.revision} deliveries={deliveries} admin/>)}else createRoot(document.getElementById('root')!).render(<StudioClientPortal shareId={location.pathname.split('/')[2]||undefined}/>);`;
   const entryPath=resolve('.devdata/client-delivery-browser-entry.tsx');await writeFile(entryPath,entry);await build({entryPoints:[entryPath],bundle:true,outdir:directory,entryNames:'portal',jsx:'automatic',platform:'browser',format:'esm',loader:{'.css':'css'},define:{'process.env.NODE_ENV':'"development"'}});
   const server=createServer(async(req,res)=>{try{const url=new URL(req.url!,'http://'+req.headers.host);if(url.pathname.startsWith('/api/')){const chunks=[];for await(const c of req)chunks.push(c);const method=req.method!,headers=new Headers();for(const [name,value]of Object.entries(req.headers))if(value)headers.set(name,Array.isArray(value)?value.join(','):value);const request=new Request(url,{method,headers,...['GET','HEAD'].includes(method)?{}:{body:Buffer.concat(chunks)}}),response=await studioClientDeliveryRoute(request,url.pathname.slice(5).split('/'),method,provider)??await handleApi(request,url.pathname.slice(5).split('/'));res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));return;}if(url.pathname==='/portal.js'||url.pathname==='/portal.css'){res.setHeader('Content-Type',url.pathname.endsWith('.js')?'text/javascript':'text/css');res.end(await readFile(resolve(directory,url.pathname.slice(1))));return;}res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/portal.css"></head><body><div id="root"></div><script type="module" src="/portal.js"></script></body></html>');}catch(e){res.statusCode=500;res.end(String(e));}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const liveOrigin='http://127.0.0.1:'+(server.address() as {port:number}).port,browser=await chromium.launch({headless:true});
   try{const contexts:any={};for(const actor of['owner','client','otherClient']){contexts[actor]=await browser.newContext({viewport:{width:1365,height:960}});await contexts[actor].addCookies([{name:'coatria_session',value:sessions[actor],url:liveOrigin,httpOnly:true,sameSite:'Lax'}]);}const admin=await contexts.owner.newPage(),client=await contexts.client.newPage(),wrong=await contexts.otherClient.newPage();for(const page of[admin,client,wrong]){page.setDefaultTimeout(15000);page.on('pageerror',(e:Error)=>pageErrors.push(e.message));}
    await client.goto(liveOrigin+'/delivery');await client.getByRole('button',{name:'Copy account ID',exact:true}).waitFor();assert((await client.locator('main').innerText()).includes(users.client));passed.push('External account enters a standalone portal without company onboarding');
    await admin.goto(liveOrigin+'/admin');await admin.getByRole('button',{name:/Create client invitation/}).click();await admin.getByLabel('Client’s Coatria account ID',{exact:true}).fill(users.client);await admin.getByRole('checkbox').check();await admin.getByRole('button',{name:'Review invitation',exact:true}).click();assert((await admin.locator('form').innerText()).includes(users.client));await admin.getByRole('button',{name:'Create invitation',exact:true}).click();await admin.getByRole('button',{name:'Copy invitation',exact:true}).waitFor();const s=(await call(adminPath(p))).shares[0];assert.equal(s.recipientUserId,users.client);assert.equal(s.receiptSummary.portalOpened,0);passed.push('Admin reviews exact recipient/package and creates a persisted invitation without sending it');
    await wrong.goto(liveOrigin+'/delivery/'+s.id);await wrong.getByRole('alert').waitFor();assert.equal(await wrong.getByRole('heading',{name:'Your files',exact:true}).count(),0);passed.push('A different authenticated client receives no package or file metadata');
    await client.goto(liveOrigin+'/delivery/'+s.id);await client.getByRole('heading',{name:'Your files',exact:true}).waitFor();await client.getByRole('button',{name:/Get download link/}).first().click();await client.getByRole('link',{name:/Open file/}).waitFor();assert.equal((await call(clientPath(s),'GET',undefined,'client')).share.receiptSummary.downloadAccessIssued,1);passed.push('Client obtains a real scoped API access receipt; no byte receipt is inferred');
    await client.getByRole('radio',{name:'Request changes',exact:true}).check();await client.getByLabel('Note to the studio',{exact:true}).fill('Synthetic browser client requests a lighter background in frame 2.');await client.getByRole('checkbox').check();await client.getByRole('button',{name:'Send change request',exact:true}).click();await client.getByRole('heading',{name:'Your response is on record.',exact:true}).waitFor();await client.reload();await client.getByRole('heading',{name:'Your response is on record.',exact:true}).waitFor();assert.equal((await detail(p.projectId)).project.status,'review');passed.push('Authentic client change request survives reload with exact-package provenance');
    await client.screenshot({path:resolve(directory,'client-delivery-desktop.png'),fullPage:true});await client.setViewportSize({width:390,height:844});await client.screenshot({path:resolve(directory,'client-delivery-mobile.png'),fullPage:true});assert(await client.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    await admin.reload();await admin.getByRole('button',{name:'Revoke access',exact:true}).click();await admin.getByText('Revoked',{exact:true}).waitFor();await client.reload();await client.getByRole('alert').waitFor();assert.equal(await client.getByRole('heading',{name:'Your files',exact:true}).count(),0);passed.push('Revocation removes fresh client access; mobile has no document overflow');assert.deepEqual(pageErrors,[]);
    await writeFile(resolve(directory,'evidence.json'),JSON.stringify({scope:'Local real React + handleApi + isolated database. Synthetic account/media fixtures only; no provider/cloud writes or real client acceptance.',passed,pageErrors},null,2));
   }finally{await browser.close();await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
  });
  assert(signed>0);
 }finally{try{await query('DELETE FROM companies WHERE id=ANY($1::uuid[])',[companies]);await query('DELETE FROM users WHERE id=ANY($1::uuid[])',[Object.values(users)]);}finally{await database().end();delete(globalThis as any).coatriaPool;await stop?.();}}
});
