import {currentTaskPatchForFixture} from './task-fixture-revision';
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {database,query} from '../src/lib/db';
import {hashToken} from '../src/lib/security';
import {studioReviewPolicyInput,studioReviewDecideInput} from '../src/lib/studio-review-policy-protocol';
import {AGENT_TOOLS} from '../src/lib/agent-tools';
import {studioReviewAgentSnapshot} from '../src/lib/studio-review-policy';

const expires=()=>new Date(Date.now()+3600000).toISOString();
const emulate=process.env.COATRIA_TEST_EMULATOR==='1',integrationUrl=process.env.COATRIA_INTEGRATION_DATABASE_URL;
test('planning corrections bind completed review decisions without expanding authority',{skip:!emulate&&!integrationUrl,timeout:120000},async t=>{
 const {handleApi}=await import('../src/lib/api'),prior={DATABASE_URL:process.env.DATABASE_URL,DATABASE_POOL_MAX:process.env.DATABASE_POOL_MAX};process.env.DATABASE_URL=integrationUrl;process.env.DATABASE_POOL_MAX=emulate?'1':'10';let stop:(()=>Promise<void>)|undefined;
 if(emulate){const {PGlite}=await import('@electric-sql/pglite'),{PGLiteSocketServer}=await import('@electric-sql/pglite-socket'),db=await PGlite.create();for(const f of(await readdir('database')).filter(f=>/^\d.*\.sql$/.test(f)).sort())await db.exec(await readFile('database/'+f,'utf8'));const server=new PGLiteSocketServer({db,host:'127.0.0.1',port:0,maxConnections:1});await server.start();const url=new URL('postgresql://'+server.getServerConn()+'/postgres');url.username='postgres';url.password='postgres';process.env.DATABASE_URL=url.href;stop=async()=>{await server.stop();await db.close();};}
 const company=randomUUID(),foreign=randomUUID(),owner=randomUUID(),admin=randomUUID(),member=randomUUID(),outsider=randomUUID(),ids={owner,admin,member,outsider},sessions={owner:randomUUID(),admin:randomUUID(),member:randomUUID(),outsider:randomUUID()},origin='http://localhost:4180',agents:Record<string,{id:string;token:string}>={};let parent:any;
 async function call(path:string,method='GET',payload?:unknown,actor='owner',expected:number|number[]=200){payload=await currentTaskPatchForFixture(path,method,payload);
    const headers:Record<string,string>={Origin:origin};if(agents[actor])headers.Authorization='Bearer '+agents[actor].token;else if(actor in sessions)headers.Cookie='coatria_session='+sessions[actor as keyof typeof sessions];if(payload!==undefined)headers['Content-Type']='application/json';const response=await handleApi(new Request(origin+'/api/'+path,{method,headers,...payload!==undefined?{body:JSON.stringify(payload)}:{}}),path.split('?')[0].split('/'));const result=await response.json();assert((Array.isArray(expected)?expected:[expected]).includes(response.status),`${method} ${path}: ${response.status} ${result.code??''} ${result.error??''}`);return {...result,__httpStatus:response.status};}
 const base=`companies/${company}/studio`,policyPath=(pid:string)=>`${base}/projects/${pid}/review-policy`;
 async function tool(name:string,args:any,actor='coordinator',lease=parent,expected=200,extra:Record<string,unknown>={}){return call('agent/tools/'+name,'POST',{runId:lease.run.id,leaseToken:lease.leaseToken,requestId:randomUUID(),arguments:args,...extra},actor,expected);}
 const generatedProjects=new Set<string>();
 async function projectDetail(pid:string){return call(`${base}/projects/${pid}${generatedProjects.has(pid)?'?contractVersion=2':''}`);}
 async function project(patch:Record<string,unknown>={}){const created=await call(base+'/projects','POST',{clientId:randomUUID(),name:'Synthetic planning review',clientName:'Fixture',brief:'Prepare a bounded estimate and breakdown for a synthetic internal VFX shot. Identify assumptions and unresolved cost inputs.',aiPolicy:'allowed',spec:{width:128,height:128,fpsNumerator:24,fpsDenominator:1,format:'exr',colorSpace:'Linear Rec.709'},shots:[{code:'SH010',description:'Synthetic shot',frameStart:1,frameEnd:2,handles:0,disciplines:['compositing']}],...patch},'owner',201);if(patch.contractVersion===2)generatedProjects.add(created.project.id);await call(`${base}/projects/${created.project.id}/gates`,'POST',{clientId:randomUUID(),revision:1,gate:'brief',decision:'approved',note:'Synthetic approved brief.'},'owner',201);return projectDetail(created.project.id);}
 async function submitted(projectPatch:Record<string,unknown>={},summary?:string){let d=await project(projectPatch),w=d.workItems.find((w:any)=>w.stage==='estimate');const queued=await call(`${base}/projects/${d.project.id}/dispatch`,'POST',{clientId:randomUUID(),revision:d.project.revision,workItemId:w.id},'owner',201),lease=await call('agent/runs/claim','POST',{workerId:'review-producer',claimId:randomUUID()},'producer');assert.equal(lease.run.id,queued.run.id);const claimed=(await tool('tasks_claim',{taskId:w.taskId,revision:w.revision},'producer',lease)).result;await tool('tasks_submit',{taskId:w.taskId,revision:claimed.revision,summary:summary??'Planning estimate: two synthetic frames at 128 square. Deliverables are EXR frames and a preview. Renderer execution and client pricing require separate approval. Cost inputs and source assets are unresolved; no actual cost promise or media work was performed.'},'producer',lease);await call(`agent/runs/${lease.run.id}/complete`,'POST',{clientId:randomUUID(),leaseToken:lease.leaseToken,result:'Submitted the exact synthetic planning estimate for review.'},'producer');d=await projectDetail(d.project.id);return {d,w:d.workItems.find((x:any)=>x.id===w.id),producerRunId:lease.run.id};}
 async function approve(pid:string,patch:Record<string,unknown>={}){const old=(await call(policyPath(pid))).policy;return call(policyPath(pid),'PUT',{clientId:randomUUID(),revision:old?.revision??0,coordinatorAgentId:agents.coordinator.id,reviewerAgentId:agents.reviewer.id,allowedStages:['estimate','breakdown'],allowSharedSponsor:true,status:'active',maxReviews:2,expiresAt:expires(),...patch});}
 async function dispatch(s:any,expected=200,extra:Record<string,unknown>={}){const p=(await call(policyPath(s.d.project.id))).policy;return tool('studio_review_dispatch',{projectId:s.d.project.id,workItemId:s.w.id,taskRevision:s.w.revision,policyRevision:p.revision,...extra},'coordinator',parent,expected);}
 async function reviewClaim(s:any){const r=(await dispatch(s)).result,lease=await call('agent/runs/claim','POST',{workerId:'reviewer-fixture',claimId:randomUUID()},'reviewer');assert.equal(lease.run.id,r.reviewerRunId);return {r,lease};}
 const note='The pinned contribution identifies scope, assumptions and unresolved inputs; it makes no execution or commercial approval claim.';
 async function decide(r:any,lease:any,decision='approve',expected=200,extra:Record<string,unknown>={}){const read=(await tool('studio_review_read',{reviewId:r.reviewId},'reviewer',lease)).result;return tool('studio_review_decide',{reviewId:r.reviewId,policyRevision:read.policyRevision,submissionSha256:read.submissionSha256,decision,note,...extra},'reviewer',lease,expected);}
 async function finish(lease:any){return call(`agent/runs/${lease.run.id}/complete`,'POST',{clientId:randomUUID(),leaseToken:lease.leaseToken,result:'The exact machine planning review state was recorded.'},'reviewer');}
 try{
  for(const [name,userId]of Object.entries(ids))await query('INSERT INTO users(id,name,email,password_hash) VALUES($1,$2,$3,$4)',[userId,'Planning '+name,userId+'@example.invalid','fixture']);for(const c of [company,foreign])await query("INSERT INTO companies(id,name,slug,template) VALUES($1,'Planning fixture',$2,'blank')",[c,c]);await query("INSERT INTO memberships(company_id,user_id,role) VALUES($1,$2,'owner'),($1,$3,'admin'),($1,$4,'member'),($5,$6,'owner')",[company,owner,admin,member,foreign,outsider]);for(const [name,userId]of Object.entries(ids))await query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '1 hour')",[hashToken(sessions[name as keyof typeof sessions]),userId]);
  for(const name of ['coordinator','producer','reviewer']){const capabilities=name==='reviewer'?['studio.read','studio.review']:['studio.read','studio.write','tasks.write'];const result=await call(`companies/${company}/plugin-installations`,'POST',{clientId:randomUUID(),pluginId:'runpod',manifestVersion:'1.0.0',name,invocationAccess:'admins',capabilities,runtimeConfig:{providerId:'runpod',modelId:'Qwen/Qwen3.8-27B-FP8',maxSteps:8,maxOutputTokens:2048,maxTotalTokens:24000,timeoutSeconds:180}},'owner',201);agents[name]={id:result.installation.agentId,token:result.token};}
  await call(base+'/setup','POST',{clientId:randomUUID(),templateId:'vfx-boutique',templateVersion:1,revision:0,assignments:[{roleKey:'coordinator',agentId:agents.coordinator.id},{roleKey:'producer',agentId:agents.producer.id},{roleKey:'ingest',agentId:agents.producer.id},{roleKey:'qc',humanId:admin}]},'owner',201);const queued=await call(`companies/${company}/conversations/commons/runs`,'POST',{clientId:randomUUID(),agentId:agents.coordinator.id,prompt:'Coordinate bounded synthetic planning reviews.'},'owner',201);parent=await call('agent/runs/claim','POST',{workerId:'review-coordinator',claimId:randomUUID()},'coordinator');assert.equal(parent.run.id,queued.run.id);

  async function coordination(pid:string,patch:Record<string,unknown>={}){const path=`${base}/projects/${pid}/coordination`,old=(await call(path)).policy;return call(path,'PUT',{clientId:randomUUID(),revision:old?.revision??0,coordinatorAgentId:agents.coordinator.id,allowedRoleKeys:['producer'],planningRework:true,status:'active',maxRuns:2,maxConcurrentRuns:1,expiresAt:expires(),...patch});}
  async function ready(decision='changes_requested',complete=true,projectPatch:Record<string,unknown>={}){await call(`agent/runs/${parent.run.id}/heartbeat`,'POST',{leaseToken:parent.leaseToken},'coordinator');const s=await submitted(projectPatch);await approve(s.d.project.id);const {r,lease}=await reviewClaim(s);await decide(r,lease,decision);if(complete)await finish(lease);await coordination(s.d.project.id);return {...s,reviewId:r.reviewId,reviewLease:lease};}
  async function correction(s:any,expected=200,patch:Record<string,unknown>={}){const d=await projectDetail(s.d.project.id),p=(await call(`${base}/projects/${s.d.project.id}/coordination`)).policy;return tool('studio_work_dispatch',{projectId:d.project.id,projectRevision:d.project.revision,workItemId:s.w.id,policyRevision:p.revision,planningReviewId:s.reviewId,...patch},'coordinator',parent,expected);}
  async function cancel(runId:string){await call(`companies/${company}/agent-runs/${runId}/cancel`,'POST',{});}
  await t.test('actual direct producer → changes requested → one fresh correction → new review; business gates stay closed',async()=>{
   const s=await ready(),snapshot=await call(`${base}/projects/${s.d.project.id}/coordination`);assert.equal(snapshot.planningReworks[0].reviewId,s.reviewId);
   const a=(await correction(s)).result,b=(await correction(s)).result;assert.equal(a.childRunId,b.childRunId);assert.notEqual(a.childRunId,s.producerRunId);assert.equal(b.replayed,true);
   const row=(await query('SELECT max_attempts,capabilities,prompt FROM agent_runs WHERE id=$1',[a.childRunId])).rows[0];assert.equal(row.max_attempts,1);assert.deepEqual(row.capabilities,['studio.read','studio.write','tasks.write']);assert.match(row.prompt,/untrusted feedback/);
   assert.equal((await call(`${base}/projects/${s.d.project.id}/coordination`)).policy.runsStarted,1);
   const lease=await call('agent/runs/claim','POST',{workerId:'planning-correction',claimId:randomUUID()},'producer');assert.equal(lease.run.id,a.childRunId);
   await tool('studio_get',{projectId:s.d.project.id},'producer',lease,403);
   await tool('tasks_update',{taskId:s.w.taskId,revision:s.w.revision,title:'Invent a new objective'},'producer',lease,403);
   const context=(await tool('studio_get',{projectId:s.d.project.id,workItemId:s.w.id},'producer',lease)).result;
   const claimed=(await tool('tasks_claim',{taskId:s.w.taskId,revision:context.workItem.revision},'producer',lease)).result;
   await tool('tasks_submit',{taskId:s.w.taskId,revision:claimed.revision,summary:'Corrected estimate: retain exactly the approved deliverable. Any paid generation needs separate explicit approval. No technical retry is promised. Independent reviewer eligibility is unresolved and must be confirmed; the sponsor cannot act as independent reviewer.'},'producer',lease);
   await call(`agent/runs/${lease.run.id}/complete`,'POST',{clientId:randomUUID(),leaseToken:lease.leaseToken,result:'Submitted the exact correction for a fresh review.'},'producer');
   const d=await projectDetail(s.d.project.id),next={...s,d,w:d.workItems.find((w:any)=>w.id===s.w.id)},{r,lease:reviewLease}=await reviewClaim(next);assert.notEqual(r.reviewId,s.reviewId);await decide(r,reviewLease,'approve');await finish(reviewLease);
   const accepted=await projectDetail(s.d.project.id);assert.equal(accepted.workItems.find((w:any)=>w.id===s.w.id).status,'done');assert.equal(accepted.project.gates.estimate,undefined);assert.equal(accepted.project.gates.production,undefined);await correction(s,409);
   await assert.rejects(query("UPDATE studio_planning_rework_dispatches SET task_revision=task_revision+1 WHERE company_id=$1 AND review_id=$2",[company,s.reviewId]));
   await assert.rejects(query('UPDATE studio_dispatches SET planning_rework_review_id=NULL WHERE company_id=$1 AND run_id=$2',[company,a.childRunId]));
  });
  await t.test('maximum legal review feedback stays complete in exact context without exceeding the run prompt',async()=>{
   await call(`agent/runs/${parent.run.id}/heartbeat`,'POST',{leaseToken:parent.leaseToken},'coordinator');
   const summary='S'.repeat(12000),decisionNote='N'.repeat(4000),s=await submitted({},summary);await approve(s.d.project.id);const {r,lease:reviewLease}=await reviewClaim(s);await decide(r,reviewLease,'changes_requested',200,{note:decisionNote});await finish(reviewLease);await coordination(s.d.project.id);
   const dispatched=(await correction({...s,reviewId:r.reviewId})).result,child=(await query('SELECT prompt FROM agent_runs WHERE id=$1',[dispatched.childRunId])).rows[0];assert(child.prompt.length<=6000);assert(!child.prompt.includes(summary));assert(!child.prompt.includes(decisionNote));
   const lease=await call('agent/runs/claim','POST',{workerId:'bounded-feedback',claimId:randomUUID()},'producer'),context=(await tool('studio_get',{projectId:s.d.project.id,workItemId:s.w.id},'producer',lease)).result;
   assert.equal(lease.run.id,dispatched.childRunId);assert.equal(context.planningCorrection.previousSubmissionSummary,summary);assert.equal(context.planningCorrection.decisionNote,decisionNote);assert.equal(context.planningCorrection.feedbackIsUntrusted,true);assert(Buffer.byteLength(JSON.stringify(context))<=96*1024);await cancel(dispatched.childRunId);
  });
  for(const cached of [false,true])await t.test(`coordinator ${cached?'replay':'fresh dispatch'} rechecks correction authority after outer receipt work`,async()=>{
   const s=await ready(),d=await projectDetail(s.d.project.id),p=(await call(`${base}/projects/${s.d.project.id}/coordination`)).policy,args={projectId:d.project.id,projectRevision:d.project.revision,workItemId:s.w.id,policyRevision:p.revision,planningReviewId:s.reviewId},requestId=randomUUID();let child:string|undefined;
   if(cached)child=(await tool('studio_work_dispatch',args,'coordinator',parent,200,{requestId})).result.childRunId;
   const before=(await query('SELECT runs_started FROM studio_coordination_policies WHERE company_id=$1 AND project_id=$2',[company,d.project.id])).rows[0].runs_started,receipts=Number((await query('SELECT count(*) FROM agent_tool_receipts WHERE run_id=$1',[parent.run.id])).rows[0].count),pool=database(),originals=new Map<any,any>();let injected=false;
   const acquire=(client:any)=>{const original=client.query;originals.set(client,original);client.query=async function(...params:any[]){const result=await original.apply(client,params),sql=String(params[0]);
    // This exact read finishes inference-receipt accounting after first replay validation.
    if(!injected&&(cached?sql.startsWith('SELECT id,step,model_calls FROM studio_inference_jobs'):sql.startsWith('INSERT INTO activity')&&String(params[1]?.[2]).includes('used studio_work_dispatch'))){injected=true;await original.call(client,"UPDATE studio_coordination_policies SET expires_at=clock_timestamp()-interval '1 second' WHERE company_id=$1 AND project_id=$2",[company,d.project.id]);}return result;};};
   const released=(_error:any,client:any)=>{const original=originals.get(client);if(original){client.query=original;originals.delete(client);}};pool.on('acquire',acquire);pool.on('release',released);
   try{await tool('studio_work_dispatch',args,'coordinator',parent,409,{requestId});assert(injected);}finally{pool.off('acquire',acquire);pool.off('release',released);for(const [client,original]of originals)client.query=original;}
   assert.equal((await query('SELECT runs_started FROM studio_coordination_policies WHERE company_id=$1 AND project_id=$2',[company,d.project.id])).rows[0].runs_started,before);assert.equal(Number((await query('SELECT count(*) FROM agent_tool_receipts WHERE run_id=$1',[parent.run.id])).rows[0].count),receipts);assert.equal(Number((await query('SELECT count(*) FROM studio_planning_rework_dispatches WHERE company_id=$1 AND review_id=$2',[company,s.reviewId])).rows[0].count),cached?1:0);if(child)await cancel(child);
  });
  await t.test('default-off approval, incompatible selectors and rejected or unfinished reviews never queue',async()=>{
   const s=await ready();await coordination(s.d.project.id,{planningRework:false});assert.equal((await correction(s,403)).code,'PLANNING_REWORK_APPROVAL_REQUIRED');await coordination(s.d.project.id);await correction(s,400,{executionJobId:randomUUID()});
   const rejected=await ready('reject');await correction(rejected,409);
   const unfinished=await ready('changes_requested',false);await correction(unfinished,409);await finish(unfinished.reviewLease);const valid=(await correction(unfinished)).result;await cancel(valid.childRunId);
  });
  await t.test('semantic edits, stale task revision, reassignment and forged completion fail before reservation',async()=>{
   const s=await ready();
   for(const [change,restore]of [["UPDATE tasks SET title=title||' changed' WHERE id=$1","UPDATE tasks SET title=left(title,length(title)-8) WHERE id=$1"],["UPDATE tasks SET revision=revision+1 WHERE id=$1","UPDATE tasks SET revision=revision-1 WHERE id=$1"]]){await query(change,[s.w.taskId]);await correction(s,409);await query(restore,[s.w.taskId]);}
   await query('UPDATE studio_role_bindings SET agent_id=$2 WHERE company_id=$1 AND role_key=\'producer\'',[company,agents.coordinator.id]);await correction(s,409);await query('UPDATE studio_role_bindings SET agent_id=$2 WHERE company_id=$1 AND role_key=\'producer\'',[company,agents.producer.id]);
   const saved=(await query("DELETE FROM agent_run_receipts WHERE company_id=$1 AND run_id=$2 AND kind='complete' RETURNING *",[company,s.reviewLease.run.id])).rows[0];await correction(s,409);
   await query('INSERT INTO agent_run_receipts(company_id,run_id,client_id,kind,payload_hash,lease_token_hash,response,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[saved.company_id,saved.run_id,saved.client_id,saved.kind,saved.payload_hash,saved.lease_token_hash,JSON.stringify(saved.response),saved.created_at]);
   assert.equal((await call(`${base}/projects/${s.d.project.id}/coordination`)).policy.runsStarted,0);
  });
  await t.test('queued correction loses authority on pause; cancelled runs retain reservation and cannot be replaced',async()=>{
   const s=await ready(),r=(await correction(s)).result;await coordination(s.d.project.id,{status:'paused'});const lease=await call('agent/runs/claim','POST',{workerId:'paused-correction',claimId:randomUUID()},'producer');assert.equal(lease.run,null);assert.equal((await query('SELECT status FROM agent_runs WHERE id=$1',[r.childRunId])).rows[0].status,'cancelled');await correction(s,409);
   await coordination(s.d.project.id);await correction(s,409);assert.equal((await call(`${base}/projects/${s.d.project.id}/coordination`)).policy.runsStarted,1);
  });
  await t.test('same transport receipt rechecks expiry rather than replaying a revoked dispatch',async()=>{
   const s=await ready(),d=await projectDetail(s.d.project.id),p=(await call(`${base}/projects/${d.project.id}/coordination`)).policy,args={projectId:d.project.id,projectRevision:d.project.revision,workItemId:s.w.id,policyRevision:p.revision,planningReviewId:s.reviewId},requestId=randomUUID();
   const r=(await tool('studio_work_dispatch',args,'coordinator',parent,200,{requestId})).result;await query("UPDATE studio_coordination_policies SET expires_at=clock_timestamp()-interval '1 second' WHERE company_id=$1 AND project_id=$2",[company,d.project.id]);await tool('studio_work_dispatch',args,'coordinator',parent,409,{requestId});await cancel(r.childRunId);
  });
  await t.test('a second changes-requested decision cannot exceed the shared lifetime specialist budget',async()=>{
   const s=await ready();await coordination(s.d.project.id,{maxRuns:1});const r=(await correction(s)).result;
   const lease=await call('agent/runs/claim','POST',{workerId:'budget-correction',claimId:randomUUID()},'producer');assert.equal(lease.run.id,r.childRunId);
   const d=await projectDetail(s.d.project.id),w=d.workItems.find((x:any)=>x.id===s.w.id),claimed=(await tool('tasks_claim',{taskId:w.taskId,revision:w.revision},'producer',lease)).result;
   await tool('tasks_submit',{taskId:w.taskId,revision:claimed.revision,summary:'Revised planning contribution retains the brief and identifies outstanding pricing and independent-reviewer inputs. Separate business and provider approvals remain required.'},'producer',lease);
   await call(`agent/runs/${lease.run.id}/complete`,'POST',{clientId:randomUUID(),leaseToken:lease.leaseToken,result:'Submitted the bounded correction.'},'producer');
   const detail=await projectDetail(s.d.project.id),next={...s,d:detail,w:detail.workItems.find((x:any)=>x.id===s.w.id)},{r:review,lease:reviewLease}=await reviewClaim(next);await decide(review,reviewLease,'changes_requested');await finish(reviewLease);
   assert.equal((await correction({...s,reviewId:review.reviewId},409)).code,'COORDINATION_RUN_BUDGET');assert.equal((await call(`${base}/projects/${s.d.project.id}/coordination`)).policy.runsStarted,1);
  });
  await t.test('timestamp-only sponsor revocation prevents a fresh correction without a role downgrade',async()=>{
   await query('UPDATE agents SET created_by=$2 WHERE id=$1',[agents.producer.id,admin]);const s=await ready();await query('UPDATE memberships SET access_revoked_at=clock_timestamp() WHERE company_id=$1 AND user_id=$2',[company,admin]);
   try{const current=await projectDetail(s.d.project.id);const response=await handleApi(new Request(origin+'/api/agent/tools/studio_work_dispatch',{method:'POST',headers:{Origin:origin,Authorization:'Bearer '+agents.coordinator.token,'Content-Type':'application/json'},body:JSON.stringify({runId:parent.run.id,leaseToken:parent.leaseToken,requestId:randomUUID(),arguments:{projectId:s.d.project.id,projectRevision:current.project.revision,workItemId:s.w.id,policyRevision:1,planningReviewId:s.reviewId}})}),['agent','tools','studio_work_dispatch']);assert.equal(response.status,409);assert.equal((await response.json()).code,'COORDINATION_AGENT_UNAVAILABLE');assert.equal(Number((await query('SELECT count(*) FROM studio_planning_rework_dispatches WHERE company_id=$1 AND review_id=$2',[company,s.reviewId])).rows[0].count),0);}finally{await query('UPDATE memberships SET access_revoked_at=NULL WHERE company_id=$1 AND user_id=$2',[company,admin]);await query('UPDATE agents SET created_by=$2 WHERE id=$1',[agents.producer.id,owner]);}
  });
  for(const cached of [false,true])await t.test(`final correction authority rejects ${cached?'cached replay':'new mutation'} expiry after initial admission`,async()=>{
   const s=await ready(),r=(await correction(s)).result,lease=await call('agent/runs/claim','POST',{workerId:'late-expiry',claimId:randomUUID()},'producer');assert.equal(lease.run.id,r.childRunId);
   const d=await projectDetail(s.d.project.id),w=d.workItems.find((x:any)=>x.id===s.w.id),args={taskId:w.taskId,revision:w.revision},requestId=randomUUID();
   if(cached)await tool('tasks_claim',args,'producer',lease,200,{requestId});
   const before=(await query('SELECT status,revision,agent_run_id FROM tasks WHERE id=$1',[w.taskId])).rows[0],count=Number((await query('SELECT count(*) FROM agent_tool_receipts WHERE run_id=$1',[lease.run.id])).rows[0].count),pool=database(),originals=new Map<any,any>();let injected=false;
   const acquire=(client:any)=>{const original=client.query;originals.set(client,original);client.query=async function(...params:any[]){const result=await original.apply(client,params),sql=String(params[0]);if(!injected&&(cached?sql.startsWith('SELECT request_hash,response FROM agent_tool_receipts'):sql.startsWith('INSERT INTO agent_tool_receipts'))){injected=true;await original.call(client,"UPDATE studio_coordination_policies SET expires_at=clock_timestamp()-interval '1 second' WHERE company_id=$1 AND project_id=$2",[company,s.d.project.id]);}return result;};};
   const released=(_error:any,client:any)=>{const original=originals.get(client);if(original){client.query=original;originals.delete(client);}};pool.on('acquire',acquire);pool.on('release',released);
   try{const result=await tool('tasks_claim',args,'producer',lease,409,{requestId});assert.equal(result.code,'PLANNING_REWORK_AUTHORITY_ENDED');assert(injected);}finally{pool.off('acquire',acquire);pool.off('release',released);for(const [client,original]of originals)client.query=original;}
   assert.deepEqual((await query('SELECT status,revision,agent_run_id FROM tasks WHERE id=$1',[w.taskId])).rows[0],before);assert.equal(Number((await query('SELECT count(*) FROM agent_tool_receipts WHERE run_id=$1',[lease.run.id])).rows[0].count),count);await cancel(r.childRunId);
  });
  await t.test('native PostgreSQL distinct parent leases reserve exactly one correction',{skip:emulate},async()=>{
   const s=await ready(),other=(await call(`companies/${company}/conversations/commons/runs`,'POST',{clientId:randomUUID(),agentId:agents.coordinator.id,prompt:'Second finite coordinator cycle for exact correction deduplication.'},'owner',201)).run,leaseToken=randomUUID()+randomUUID();
   await query("UPDATE agent_runs SET status='running',attempts=1,worker_id='second-correction-coordinator',lease_token_hash=$2,lease_expires_at=clock_timestamp()+interval '1 minute',started_at=clock_timestamp() WHERE id=$1",[other.id,hashToken(leaseToken)]);
   const d=await projectDetail(s.d.project.id),p=(await call(`${base}/projects/${s.d.project.id}/coordination`)).policy,args={projectId:d.project.id,projectRevision:d.project.revision,workItemId:s.w.id,policyRevision:p.revision,planningReviewId:s.reviewId};
   const results=await Promise.all([parent,{run:other,leaseToken}].map(lease=>tool('studio_work_dispatch',args,'coordinator',lease)));assert.equal(results[0].result.childRunId,results[1].result.childRunId);assert.equal((await call(`${base}/projects/${s.d.project.id}/coordination`)).policy.runsStarted,1);await cancel(results[0].result.childRunId);await cancel(other.id);
  });
  await t.test('generated continuation admission shares the queued correction concurrency slot',async()=>{
   const s=await ready('changes_requested',true,{contractVersion:2,productionPath:'higgsfield',spec:{kind:'image',width:128,height:128,format:'png',color:{mode:'not_required'}},shots:[{kind:'image',code:'D010',description:'Synthetic original still'}]});await coordination(s.d.project.id,{generatedContinuations:true});const r=(await correction(s)).result,d=await projectDetail(s.d.project.id),p=(await call(`${base}/projects/${s.d.project.id}/coordination`)).policy;
   // The shared capacity gate must run before source lookup or any child write.
   const result=await tool('studio_generated_followup_dispatch',{projectId:d.project.id,workItemId:s.w.id,archiveId:randomUUID(),projectRevision:d.project.revision,policyRevision:p.revision},'coordinator',parent,409);assert.equal(result.code,'COORDINATION_CONCURRENCY');assert.equal((await call(`${base}/projects/${s.d.project.id}/coordination`)).policy.runsStarted,1);await cancel(r.childRunId);
  });
  await t.test('hosted coordinator expiry during final source reads rolls back the correction mutation',async()=>{
   const s=await ready(),r=(await correction(s)).result,lease=await call('agent/runs/claim','POST',{workerId:'host-expiry-correction',claimId:randomUUID()},'producer'),hostId=randomUUID();assert.equal(lease.run.id,r.childRunId);
   // Synthetic authority metadata only: no credential decryption or host starts.
   const installation=(await query('SELECT id,revision FROM plugin_installations WHERE agent_id=$1',[agents.coordinator.id])).rows[0],tokenHash=hashToken(agents.coordinator.token);
   await query("INSERT INTO studio_managed_hosts(id,company_id,created_by,client_id,request_hash,token_hash,name,max_agents,provider_ids,expires_at,lease_owner,lease_epoch,lease_expires_at) VALUES($1,$2,$3,$4,$5,$6,'Synthetic authority only',1,'[\"runpod\"]',clock_timestamp()+interval '1 hour',$4,1,clock_timestamp()+interval '1 hour')",[hostId,company,owner,randomUUID(),'a'.repeat(64),'b'.repeat(64)]);
   await query("INSERT INTO studio_host_credentials(company_id,agent_id,host_id,installation_id,version,installation_revision,host_epoch,token_hash,key_id,nonce,auth_tag,ciphertext,configuration,configuration_hash,enrolled_by,expires_at) VALUES($1,$2,$3,$4,1,$5,1,$6,'synthetic','synthetic','synthetic','synthetic','{}',$7,$8,clock_timestamp()+interval '1 hour')",[company,agents.coordinator.id,hostId,installation.id,installation.revision,tokenHash,'c'.repeat(64),owner]);await query('UPDATE agents SET managed_token_hash=token_hash WHERE id=$1',[agents.coordinator.id]);
   const d=await projectDetail(s.d.project.id),w=d.workItems.find((x:any)=>x.id===s.w.id),pool=database(),originals=new Map<any,any>();let armed=false,injected=false;
   const acquire=(client:any)=>{const original=client.query;originals.set(client,original);client.query=async function(...params:any[]){const result=await original.apply(client,params),sql=String(params[0]);if(sql.startsWith('SELECT t.id FROM tasks t')&&sql.endsWith('FOR SHARE NOWAIT'))armed=true;if(armed&&!injected&&sql.startsWith('SELECT r.*,EXISTS')){injected=true;await original.call(client,"UPDATE studio_managed_hosts SET lease_expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[hostId]);}return result;};};
   const released=(_error:any,client:any)=>{const original=originals.get(client);if(original){client.query=original;originals.delete(client);}};pool.on('acquire',acquire);pool.on('release',released);
   try{assert.equal((await tool('tasks_claim',{taskId:w.taskId,revision:w.revision},'producer',lease,409)).code,'PLANNING_REWORK_AUTHORITY_ENDED');assert(injected);}finally{pool.off('acquire',acquire);pool.off('release',released);for(const [client,original]of originals)client.query=original;await query('UPDATE agents SET managed_token_hash=NULL WHERE id=$1',[agents.coordinator.id]);await query('DELETE FROM studio_host_credentials WHERE host_id=$1',[hostId]);await query('DELETE FROM studio_managed_hosts WHERE id=$1',[hostId]);}
   assert.equal((await query('SELECT status FROM tasks WHERE id=$1',[w.taskId])).rows[0].status,'todo');await cancel(r.childRunId);
  });
 }finally{try{await query('DELETE FROM companies WHERE id=ANY($1::uuid[])',[[company,foreign]]);await query('DELETE FROM users WHERE id=ANY($1::uuid[])',[[owner,admin,member,outsider]]);}finally{await database().end();delete(globalThis as any).coatriaPool;await stop?.();for(const [key,value]of Object.entries(prior)){if(value===undefined)delete process.env[key];else process.env[key]=value;}}}
});
