import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {database,query} from '../src/lib/db';
import {hashToken} from '../src/lib/security';
import {studioReviewPolicyInput,studioReviewDecideInput} from '../src/lib/studio-review-policy-protocol';
import {AGENT_TOOLS} from '../src/lib/agent-tools';
import {studioReviewAgentSnapshot} from '../src/lib/studio-review-policy';

const expires=()=>new Date(Date.now()+3600000).toISOString();
test('machine planning review requires explicit finite configuration and a dedicated attested scope',()=>{
 const body={clientId:randomUUID(),revision:0,coordinatorAgentId:randomUUID(),reviewerAgentId:randomUUID(),allowedStages:['estimate','breakdown'],allowSharedSponsor:false,maxReviews:2,status:'paused',expiresAt:expires()};
 assert(studioReviewPolicyInput.safeParse(body).success);
 for(const patch of [{reviewerAgentId:body.coordinatorAgentId},{allowedStages:['compositing']},{allowedStages:['estimate','estimate']},{maxReviews:0},{maxReviews:101},{reviewsStarted:0},{command:'render'},{status:'automatic'}])assert(!studioReviewPolicyInput.safeParse({...body,...patch}).success);
 assert(!studioReviewDecideInput.safeParse({reviewId:randomUUID(),policyRevision:1,submissionSha256:'a'.repeat(64),decision:'approve',note:'ok'}).success);
 assert.equal(AGENT_TOOLS.studio_review_read.capability,'studio.review');assert.equal(AGENT_TOOLS.studio_review_read.mutating,true);assert.equal(AGENT_TOOLS.studio_review_decide.capability,'studio.review');
});

const emulate=process.env.COATRIA_TEST_EMULATOR==='1',integrationUrl=process.env.COATRIA_INTEGRATION_DATABASE_URL;
test('machine review pins independent identities, immutable submissions and bounded human authority',{skip:!emulate&&!integrationUrl,timeout:120000},async t=>{
 const {handleApi}=await import('../src/lib/api'),prior={DATABASE_URL:process.env.DATABASE_URL,DATABASE_POOL_MAX:process.env.DATABASE_POOL_MAX};process.env.DATABASE_URL=integrationUrl;process.env.DATABASE_POOL_MAX=emulate?'1':'10';let stop:(()=>Promise<void>)|undefined;
 if(emulate){const {PGlite}=await import('@electric-sql/pglite'),{PGLiteSocketServer}=await import('@electric-sql/pglite-socket'),db=await PGlite.create();for(const f of(await readdir('database')).filter(f=>/^\d.*\.sql$/.test(f)).sort())await db.exec(await readFile('database/'+f,'utf8'));const server=new PGLiteSocketServer({db,host:'127.0.0.1',port:0,maxConnections:1});await server.start();const url=new URL('postgresql://'+server.getServerConn()+'/postgres');url.username='postgres';url.password='postgres';process.env.DATABASE_URL=url.href;stop=async()=>{await server.stop();await db.close();};}
 const company=randomUUID(),foreign=randomUUID(),owner=randomUUID(),admin=randomUUID(),member=randomUUID(),outsider=randomUUID(),ids={owner,admin,member,outsider},sessions={owner:randomUUID(),admin:randomUUID(),member:randomUUID(),outsider:randomUUID()},origin='http://localhost:4180',agents:Record<string,{id:string;token:string}>={};let parent:any;
 async function call(path:string,method='GET',payload?:unknown,actor='owner',expected:number|number[]=200){const headers:Record<string,string>={Origin:origin};if(agents[actor])headers.Authorization='Bearer '+agents[actor].token;else if(actor in sessions)headers.Cookie='coatria_session='+sessions[actor as keyof typeof sessions];if(payload!==undefined)headers['Content-Type']='application/json';const response=await handleApi(new Request(origin+'/api/'+path,{method,headers,...payload!==undefined?{body:JSON.stringify(payload)}:{}}),path.split('?')[0].split('/'));const result=await response.json();assert((Array.isArray(expected)?expected:[expected]).includes(response.status),`${method} ${path}: ${response.status} ${result.code??''} ${result.error??''}`);return {...result,__httpStatus:response.status};}
 const base=`companies/${company}/studio`,policyPath=(pid:string)=>`${base}/projects/${pid}/review-policy`;
 async function tool(name:string,args:any,actor='coordinator',lease=parent,expected=200,extra:Record<string,unknown>={}){return call('agent/tools/'+name,'POST',{runId:lease.run.id,leaseToken:lease.leaseToken,requestId:randomUUID(),arguments:args,...extra},actor,expected);}
 async function project(){const created=await call(base+'/projects','POST',{clientId:randomUUID(),name:'Synthetic planning review',clientName:'Fixture',brief:'Prepare a bounded estimate and breakdown for a synthetic internal VFX shot. Identify assumptions and unresolved cost inputs.',aiPolicy:'allowed',spec:{width:128,height:128,fpsNumerator:24,fpsDenominator:1,format:'exr',colorSpace:'Linear Rec.709'},shots:[{code:'SH010',description:'Synthetic shot',frameStart:1,frameEnd:2,handles:0,disciplines:['compositing']}]},'owner',201);await call(`${base}/projects/${created.project.id}/gates`,'POST',{clientId:randomUUID(),revision:1,gate:'brief',decision:'approved',note:'Synthetic approved brief.'},'owner',201);return call(`${base}/projects/${created.project.id}`);}
 async function submitted(){let d=await project(),w=d.workItems.find((w:any)=>w.stage==='estimate');const queued=await call(`${base}/projects/${d.project.id}/dispatch`,'POST',{clientId:randomUUID(),revision:d.project.revision,workItemId:w.id},'owner',201),lease=await call('agent/runs/claim','POST',{workerId:'review-producer',claimId:randomUUID()},'producer');assert.equal(lease.run.id,queued.run.id);const claimed=(await tool('tasks_claim',{taskId:w.taskId,revision:w.revision},'producer',lease)).result;await tool('tasks_submit',{taskId:w.taskId,revision:claimed.revision,summary:'Planning estimate: two synthetic frames at 128 square. Deliverables are EXR frames and a preview. Renderer execution and client pricing require separate approval. Cost inputs and source assets are unresolved; no actual cost promise or media work was performed.'},'producer',lease);await call(`agent/runs/${lease.run.id}/complete`,'POST',{clientId:randomUUID(),leaseToken:lease.leaseToken,result:'Submitted the exact synthetic planning estimate for review.'},'producer');d=await call(`${base}/projects/${d.project.id}`);return {d,w:d.workItems.find((x:any)=>x.id===w.id),producerRunId:lease.run.id};}
 async function approve(pid:string,patch:Record<string,unknown>={}){const old=(await call(policyPath(pid))).policy;return call(policyPath(pid),'PUT',{clientId:randomUUID(),revision:old?.revision??0,coordinatorAgentId:agents.coordinator.id,reviewerAgentId:agents.reviewer.id,allowedStages:['estimate','breakdown'],allowSharedSponsor:true,status:'active',maxReviews:2,expiresAt:expires(),...patch});}
 async function dispatch(s:any,expected=200,extra:Record<string,unknown>={}){const p=(await call(policyPath(s.d.project.id))).policy;return tool('studio_review_dispatch',{projectId:s.d.project.id,workItemId:s.w.id,taskRevision:s.w.revision,policyRevision:p.revision,...extra},'coordinator',parent,expected);}
 async function reviewClaim(s:any){const r=(await dispatch(s)).result,lease=await call('agent/runs/claim','POST',{workerId:'reviewer-fixture',claimId:randomUUID()},'reviewer');assert.equal(lease.run.id,r.reviewerRunId);return {r,lease};}
 const note='The pinned contribution identifies scope, assumptions and unresolved inputs; it makes no execution or commercial approval claim.';
 async function decide(r:any,lease:any,decision='approve',expected=200,extra:Record<string,unknown>={}){const read=(await tool('studio_review_read',{reviewId:r.reviewId},'reviewer',lease)).result;return tool('studio_review_decide',{reviewId:r.reviewId,policyRevision:read.policyRevision,submissionSha256:read.submissionSha256,decision,note,...extra},'reviewer',lease,expected);}
 async function finish(lease:any){return call(`agent/runs/${lease.run.id}/complete`,'POST',{clientId:randomUUID(),leaseToken:lease.leaseToken,result:'The exact machine planning review state was recorded.'},'reviewer');}
 try{
  for(const [name,userId]of Object.entries(ids))await query('INSERT INTO users(id,name,email,password_hash) VALUES($1,$2,$3,$4)',[userId,'Planning '+name,userId+'@example.invalid','fixture']);for(const c of [company,foreign])await query("INSERT INTO companies(id,name,slug,template) VALUES($1,'Planning fixture',$2,'blank')",[c,c]);await query("INSERT INTO memberships(company_id,user_id,role) VALUES($1,$2,'owner'),($1,$3,'admin'),($1,$4,'member'),($5,$6,'owner')",[company,owner,admin,member,foreign,outsider]);for(const [name,userId]of Object.entries(ids))await query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '1 hour')",[hashToken(sessions[name as keyof typeof sessions]),userId]);
  for(const name of ['coordinator','producer','reviewer']){const capabilities=name==='reviewer'?['studio.read','studio.review']:['studio.read','studio.write','tasks.write'];const result=await call(`companies/${company}/plugin-installations`,'POST',{clientId:randomUUID(),pluginId:'runpod',manifestVersion:'1.0.0',name,invocationAccess:'admins',capabilities,runtimeConfig:{providerId:'runpod',modelId:'Qwen/Qwen3.8-27B-FP8',maxSteps:8,maxOutputTokens:2048,maxTotalTokens:24000,timeoutSeconds:180}},'owner',201);agents[name]={id:result.installation.agentId,token:result.token};}
  await call(base+'/setup','POST',{clientId:randomUUID(),templateId:'vfx-boutique',templateVersion:1,revision:0,assignments:[{roleKey:'coordinator',agentId:agents.coordinator.id},{roleKey:'producer',agentId:agents.producer.id},{roleKey:'qc',humanId:admin}]},'owner',201);const queued=await call(`companies/${company}/conversations/commons/runs`,'POST',{clientId:randomUUID(),agentId:agents.coordinator.id,prompt:'Coordinate bounded synthetic planning reviews.'},'owner',201);parent=await call('agent/runs/claim','POST',{workerId:'review-coordinator',claimId:randomUUID()},'coordinator');assert.equal(parent.run.id,queued.run.id);
  await t.test('policy writes require current tenant admin, finite expiry and exact revision without granting access',async()=>{const d=await project();assert.equal((await call(policyPath(d.project.id))).policy,null);await call(policyPath(d.project.id),'GET',undefined,'outsider',404);const body={clientId:randomUUID(),revision:0,coordinatorAgentId:agents.coordinator.id,reviewerAgentId:agents.reviewer.id,maxReviews:1,status:'active',expiresAt:expires()};await call(policyPath(d.project.id),'PUT',body,'member',403);await call(policyPath(d.project.id),'PUT',body,'coordinator',401);await call(policyPath(d.project.id),'PUT',{...body,expiresAt:new Date(Date.now()+90000000).toISOString()},'owner',400);const saved=await call(policyPath(d.project.id),'PUT',body);assert.equal(saved.policy.allowSharedSponsor,false);assert.equal(saved.independentHumanReview,false);assert.equal(saved.startsInference,false);assert.equal(saved.startsWorkers,false);assert.equal((await call(policyPath(d.project.id),'PUT',body)).replayed,true);await call(policyPath(d.project.id),'PUT',{...body,clientId:randomUUID()},'owner',409);assert.deepEqual((await query('SELECT capabilities FROM agents WHERE id=$1',[agents.reviewer.id])).rows[0].capabilities,['studio.read','studio.review']);});
  await t.test('shared sponsorship requires explicit approval; exact self/history review stays forbidden',async()=>{const s=await submitted();await approve(s.d.project.id,{allowSharedSponsor:false});assert.equal((await dispatch(s,403)).code,'REVIEW_SHARED_SPONSOR');assert.equal((await call(policyPath(s.d.project.id))).policy.reviewsStarted,0);await approve(s.d.project.id);await query('UPDATE contributions SET agent_id=$3 WHERE company_id=$1 AND task_id=$2',[company,s.w.taskId,agents.reviewer.id]);assert.equal((await dispatch(s,403)).code,'REVIEW_SELF_APPROVAL');await query('UPDATE contributions SET agent_id=$3 WHERE company_id=$1 AND task_id=$2',[company,s.w.taskId,agents.producer.id]);await dispatch(s,409,{taskRevision:s.w.revision-1});await dispatch(s,404,{workItemId:randomUUID()});assert.equal((await call(policyPath(s.d.project.id))).policy.reviewsStarted,0);});
  await t.test('one exact reviewer must read the immutable version before machine acceptance unlocks planning only',async()=>{const s=await submitted();await approve(s.d.project.id,{maxReviews:1});const {r,lease}=await reviewClaim(s);assert.equal((await dispatch(s)).result.reviewerRunId,r.reviewerRunId);const snap=await call(policyPath(s.d.project.id));assert.equal(snap.policy.effectiveStatus,'exhausted');assert.equal(snap.policy.reviewsStarted,1);assert.equal((await query('SELECT max_attempts FROM agent_runs WHERE id=$1',[lease.run.id])).rows[0].max_attempts,1);const review=snap.reviews[0];const args={reviewId:r.reviewId,policyRevision:review.policyRevision,submissionSha256:review.submissionSha256,decision:'approve',note};assert.equal((await tool('studio_review_decide',args,'reviewer',lease,409)).code,'REVIEW_READ_REQUIRED');await tool('studio_review_read',{reviewId:r.reviewId},'coordinator',parent,403);await tool('studio_review_read',{reviewId:randomUUID()},'reviewer',lease,404);const read=(await tool('studio_review_read',{reviewId:r.reviewId},'reviewer',lease)).result;assert.equal(read.submission.task.producerRunId,s.producerRunId);assert.equal(read.contentInspected,false);await tool('studio_review_decide',{...args,submissionSha256:'0'.repeat(64)},'reviewer',lease,409);const result=(await tool('studio_review_decide',args,'reviewer',lease)).result;assert.equal(result.task.status,'done');assert.equal(result.task.approvedBy,null);assert.equal(result.task.approvedAgentId,agents.reviewer.id);assert.equal(result.task.machineReviewId,r.reviewId);assert.equal((await tool('studio_review_decide',args,'reviewer',lease)).result.replayed,true);await tool('studio_review_decide',{...args,decision:'reject'},'reviewer',lease,409);const d=await call(`${base}/projects/${s.d.project.id}`);assert.equal(d.workItems.find((w:any)=>w.stage==='breakdown').readiness,'ready');assert.equal(d.project.gates.estimate,undefined);assert.equal(d.project.gates.production,undefined);assert.equal(d.project.gates.client_acceptance,undefined);await call(`${base}/projects/${s.d.project.id}/planning-reviews/${r.reviewId}`,'GET',undefined,'outsider',404);const exact=await call(`${base}/projects/${s.d.project.id}/planning-reviews/${r.reviewId}`);assert.equal(exact.review.submissionSha256,read.submissionSha256);await finish(lease);});
  for(const decision of ['changes_requested','reject'])await t.test(`${decision} records an immutable outcome without accepting the task or dependencies`,async()=>{const s=await submitted();await approve(s.d.project.id);const {r,lease}=await reviewClaim(s),result=(await decide(r,lease,decision)).result;assert.equal(result.task.status,decision==='changes_requested'?'todo':'review');assert.equal(result.task.approvedAgentId,null);const d=await call(`${base}/projects/${s.d.project.id}`);assert.notEqual(d.workItems.find((w:any)=>w.stage==='breakdown').readiness,'ready');assert.equal((await call(policyPath(s.d.project.id))).reviews[0].decision.decision,decision);if(decision==='reject'){assert.equal((await dispatch({...s,w:d.workItems.find((w:any)=>w.id===s.w.id)},409)).code,'REVIEW_RESUBMISSION_REQUIRED');assert.equal((await call(policyPath(s.d.project.id))).policy.reviewsStarted,1);}await finish(lease);});
  await t.test('the provider bridge can read and decide a genuinely authorized reviewer run with real API receipts',async()=>{
   const {createProviderExecutor}=await import('../public/downloads/provider-adapter.mjs');const s=await submitted();await approve(s.d.project.id);const {r,lease}=await reviewClaim(s);
   const contextPath=['agent','runs',lease.run.id,'context'],contextResponse=await handleApi(new Request(origin+'/api/'+contextPath.join('/'),{headers:{Authorization:'Bearer '+agents.reviewer.token,'X-Coatria-Run-Lease':lease.leaseToken}}),contextPath);assert.equal(contextResponse.status,200);const context=await contextResponse.json();assert(context.capabilities.includes('studio.review'));assert.match(lease.run.prompt,/explicitly authorized machine planning review/);
   let steps=0;const receipts:{name:string;result:any}[]=[];
   const execute=createProviderExecutor({settings:{NODE_ENV:'test',RUNPOD_API_KEY:'fixture-provider-key',COATRIA_RUNPOD_ENDPOINT_ID:'fixture-endpoint'},fetch:(async(_url,init)=>{
    const body=JSON.parse(String(init?.body)).input.openai_input,policy=body.messages[0].content,names=body.tools.map((definition:any)=>definition.function.name);assert(names.includes('studio_review_read'));assert(names.includes('studio_review_decide'));assert.match(policy,/may first read the pinned submission and then decide approve, changes_requested, or reject/);assert.match(policy,/successful server receipt/);assert.match(policy,/Machine acceptance is not independent human review/);
    assert(!String(init?.body).includes(agents.reviewer.token));assert(!String(init?.body).includes(lease.leaseToken));
    let name:string|undefined,args:unknown;
    if(steps===0){name='studio_review_read';args={reviewId:r.reviewId};assert.equal(receipts.length,0);}
    else if(steps===1){assert.equal(receipts.length,1);assert.equal(receipts[0].name,'studio_review_read');const read=JSON.parse(body.messages.at(-1).content);assert.equal(read.submission.task.producerRunId,s.producerRunId);assert.equal(read.contentInspected,false);name='studio_review_decide';args={reviewId:r.reviewId,policyRevision:read.policyRevision,submissionSha256:read.submissionSha256,decision:'approve',note};}
    else {assert.equal(receipts.length,2);assert.equal(receipts[1].result.task.approvedAgentId,agents.reviewer.id);assert.equal(receipts[1].result.task.status,'done');}
    const output={usage:{prompt_tokens:100,completion_tokens:50},choices:[{finish_reason:name?'tool_calls':'stop',message:{role:'assistant',content:name?null:'The server recorded machine planning acceptance; human commercial and client gates remain unchanged.',...(name?{tool_calls:[{id:'review_step_'+steps,type:'function',function:{name,arguments:JSON.stringify(args)}}]}:{})}}]};steps++;return new Response(JSON.stringify({id:'fixture-review-'+steps,status:'COMPLETED',output:[output]}),{status:200,headers:{'Content-Type':'application/json'}});
   }) as typeof fetch});
   const result=await execute({run:lease.run,context,tools:{list:()=>call('agent/tools','GET',undefined,'reviewer'),key:()=>randomUUID(),call:async(name:string,args:unknown)=>{const response=await tool(name,args,'reviewer',lease);receipts.push({name,result:response.result});return response.result;}},signal:new AbortController().signal,recovering:false});
   assert.match(result.result,/server recorded machine planning acceptance/);assert.equal(steps,3);assert.deepEqual(receipts.map(receipt=>receipt.name),['studio_review_read','studio_review_decide']);const d=await call(`${base}/projects/${s.d.project.id}`),accepted=d.workItems.find((item:any)=>item.id===s.w.id);assert.equal(accepted.status,'done');assert.equal(d.project.gates.estimate,undefined);assert.equal(d.project.gates.production,undefined);assert.equal(d.project.gates.client_acceptance,undefined);assert.equal((await call(policyPath(s.d.project.id))).reviews[0].decision.decision,'approve');await finish(lease);
  });
  await t.test('a changed approved brief or submitted task version cannot use a historical snapshot',async()=>{const s=await submitted();await approve(s.d.project.id);const {r,lease}=await reviewClaim(s);await tool('studio_review_read',{reviewId:r.reviewId},'reviewer',lease);await query('UPDATE tasks SET revision=revision+1 WHERE company_id=$1 AND id=$2',[company,s.w.taskId]);assert.equal((await decide(r,lease,'approve',409)).code,'REVIEW_SUBMISSION_CHANGED');assert.equal(Number((await query('SELECT count(*) FROM studio_planning_review_decisions WHERE review_id=$1',[r.reviewId])).rows[0].count),0);await finish(lease);});
  await t.test('missing dedicated review scope and changed plugin approval fence queued work before inference',async()=>{const s=await submitted();await approve(s.d.project.id);const r=(await dispatch(s)).result;await query('UPDATE plugin_installations SET revision=revision+1 WHERE company_id=$1 AND agent_id=$2',[company,agents.reviewer.id]);assert.equal((await call(policyPath(s.d.project.id))).policy.effectiveStatus,'approval_required');assert.equal((await call('agent/runs/claim','POST',{workerId:'reviewer-fixture',claimId:randomUUID()},'reviewer')).run,null);assert.equal((await query('SELECT status FROM agent_runs WHERE id=$1',[r.reviewerRunId])).rows[0].status,'cancelled');assert.equal((await call(policyPath(s.d.project.id))).policy.reviewsStarted,1);await query("UPDATE agents SET capabilities='[\"studio.read\"]'::jsonb WHERE company_id=$1 AND id=$2",[company,agents.reviewer.id]);await approve(s.d.project.id).then(()=>assert.fail('Missing explicit review scope'),error=>assert.match(String(error),/REVIEW_AGENT_UNAVAILABLE/));await query("UPDATE agents SET capabilities='[\"studio.read\",\"studio.review\"]'::jsonb WHERE company_id=$1 AND id=$2",[company,agents.reviewer.id]);});
  await t.test('failed or expired-lease review attempts remain counted and never automatically requeue',async()=>{for(const mode of ['failed','expired']){const s=await submitted();await approve(s.d.project.id,{maxReviews:1});const {r,lease}=await reviewClaim(s);if(mode==='failed')await call(`agent/runs/${lease.run.id}/fail`,'POST',{clientId:randomUUID(),leaseToken:lease.leaseToken,error:'Synthetic uncertain inference outcome.'},'reviewer');else await query("UPDATE agent_runs SET lease_expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[lease.run.id]);assert.equal((await call('agent/runs/claim','POST',{workerId:'reviewer-fixture',claimId:randomUUID()},'reviewer')).run,null);assert.equal((await query('SELECT status FROM agent_runs WHERE id=$1',[r.reviewerRunId])).rows[0].status,'failed');assert.equal((await dispatch(s)).result.reviewerRunId,r.reviewerRunId);await approve(s.d.project.id,{maxReviews:2});assert.equal((await call(policyPath(s.d.project.id))).policy.reviewsStarted,1);}});
  await t.test('exact safety pause works after expiry and revoked agent; active heartbeat is fenced',async()=>{const s=await submitted();await approve(s.d.project.id);const {lease}=await reviewClaim(s);await query("UPDATE studio_review_policies SET expires_at=clock_timestamp()-interval '1 second' WHERE company_id=$1 AND project_id=$2",[company,s.d.project.id]);assert.equal((await call(`agent/runs/${lease.run.id}/heartbeat`,'POST',{leaseToken:lease.leaseToken},'reviewer',409)).code,'STUDIO_REVIEW_AUTHORITY_ENDED');await query("UPDATE agents SET status='paused' WHERE id=$1",[agents.reviewer.id]);const p=(await call(policyPath(s.d.project.id))).policy,body={clientId:randomUUID(),revision:p.revision,coordinatorAgentId:p.coordinatorAgentId,reviewerAgentId:p.reviewerAgentId,allowedStages:p.allowedStages,allowSharedSponsor:p.allowSharedSponsor,maxReviews:p.maxReviews,status:'paused',expiresAt:p.expiresAt};const paused=await call(policyPath(s.d.project.id),'PUT',body);assert.equal(paused.policy.status,'paused');assert.equal(paused.policy.reviewsStarted,1);await call(policyPath(s.d.project.id),'PUT',{...body,clientId:randomUUID(),revision:paused.policy.revision,maxReviews:3},'owner',409);await query("UPDATE agents SET status='active' WHERE id=$1",[agents.reviewer.id]);await call(`companies/${company}/agent-runs/${lease.run.id}/cancel`,'POST',{});});
  await t.test('committed terminal completion remains replayable after policy pause and expiry',async()=>{const s=await submitted();await approve(s.d.project.id);const {r,lease}=await reviewClaim(s);await decide(r,lease);const receipt={clientId:randomUUID(),leaseToken:lease.leaseToken,result:'The exact machine planning acceptance was recorded.'};const completed=await call(`agent/runs/${lease.run.id}/complete`,'POST',receipt,'reviewer');assert.equal(completed.run.status,'succeeded');await approve(s.d.project.id,{status:'paused'});await query("UPDATE studio_review_policies SET expires_at=clock_timestamp()-interval '1 second' WHERE company_id=$1 AND project_id=$2",[company,s.d.project.id]);assert.equal((await call(`agent/runs/${lease.run.id}/complete`,'POST',receipt,'reviewer')).replayed,true);await call(`agent/runs/${lease.run.id}/complete`,'POST',{...receipt,result:'Different outcome'},'reviewer',409);assert.equal((await call(policyPath(s.d.project.id))).policy.reviewsStarted,1);});
  await t.test('human ingest and DCC or media QC never enter the planning review policy',async()=>{const s=await submitted();await approve(s.d.project.id,{allowedStages:['estimate','breakdown','ingest']});for(const stage of ['ingest','compositing','qc']){const work=s.d.workItems.find((w:any)=>w.stage===stage);assert(work);assert.equal((await dispatch({...s,w:work},403)).code,'REVIEW_STAGE_REQUIRED');}assert.equal((await call(policyPath(s.d.project.id))).policy.reviewsStarted,0);});
  await t.test('a changed brief cannot inherit an old read attestation even with the same task revision',async()=>{const s=await submitted();await approve(s.d.project.id);const {r,lease}=await reviewClaim(s);await tool('studio_review_read',{reviewId:r.reviewId},'reviewer',lease);await query("UPDATE studio_projects SET brief=brief||' Changed approved synthetic scope.' WHERE company_id=$1 AND id=$2",[company,s.d.project.id]);assert.equal((await decide(r,lease,'approve',409)).code,'REVIEW_SUBMISSION_CHANGED');await finish(lease);});
  await t.test('large Unicode history stays under32KB with resumable filtered agent pages and unchanged human notes',async()=>{
   const d=await project(),works=d.workItems.filter((w:any)=>['estimate','breakdown'].includes(w.stage));await approve(d.project.id,{maxReviews:100});const conversation=(await query('SELECT conversation_id FROM agent_runs WHERE id=$1',[parent.run.id])).rows[0].conversation_id,note='🧪'.repeat(1900),reviewIds:string[]=[];
   // Seed immutable historical receipts rather than paying for60 model runs.
   // Actual live submission and decision semantics are exercised above.
   for(let index=0;index<60;index++){const source=randomUUID(),reviewerRun=randomUUID(),reviewId=randomUUID(),work=works[index%2];reviewIds.push(reviewId);for(const [runId,agentId]of [[source,agents.producer.id],[reviewerRun,agents.reviewer.id]])await query("INSERT INTO agent_runs(id,company_id,agent_id,requested_by,conversation_id,client_id,payload_hash,prompt,capabilities,status,max_attempts) VALUES($1,$2,$3,$4,$5,$6,$7,'Synthetic sealed history','[]','succeeded',1)",[runId,company,agentId,owner,conversation,randomUUID(),'a'.repeat(64)]);await query('INSERT INTO studio_planning_reviews(id,company_id,project_id,work_item_id,task_id,task_revision,policy_revision,parent_run_id,reviewer_run_id,reviewer_agent_id,producer_agent_id,producer_run_id,submission,submission_sha256,brief_sha256) VALUES($1,$2,$3,$4,$5,$6,1,$7,$8,$9,$10,$11,$12,$13,$13)',[reviewId,company,d.project.id,work.id,work.taskId,index+1,parent.run.id,reviewerRun,agents.reviewer.id,agents.producer.id,source,JSON.stringify({summary:'Private long snapshot excluded from the model overview.'}),'a'.repeat(64)]);await query("INSERT INTO studio_planning_review_decisions(company_id,review_id,decision,note,task_revision) VALUES($1,$2,'reject',$3,$4)",[company,reviewId,note,index+2]);}
   await query('UPDATE studio_review_policies SET reviews_started=60 WHERE company_id=$1 AND project_id=$2',[company,d.project.id]);const human=await call(policyPath(d.project.id));assert.equal(human.reviews.length,60);assert.equal(human.reviews[0].decision.note,note);assert(Buffer.byteLength(JSON.stringify(human))>32000);
   const projection=async(input:Record<string,unknown>)=>{const client=await database().connect();try{return await studioReviewAgentSnapshot(client,company,d.project.id,{projectId:d.project.id,...input});}finally{client.release();}};
   for(const workId of [undefined,works[0].id]){let after:string|undefined;const seen=new Set<string>();let byteLimited=false;do{const page=await projection({limit:50,...workId?{workItemId:workId}:{},...after?{after}:{}});assert(Buffer.byteLength(JSON.stringify(page))<=32000);byteLimited ||=page.projection.byteLimitApplied;for(const review of page.reviews){assert(!seen.has(review.id));seen.add(review.id);assert.equal(review.noteTruncated,true);assert.equal(Array.from(review.decision!.note).length,160);assert(!('submission' in review));if(workId)assert.equal(review.workItemId,workId);}assert.equal(page.page.hasMore,Boolean(page.page.nextAfter));after=page.page.nextAfter??undefined;}while(after);assert.equal(seen.size,workId?30:60);if(!workId)assert.equal(byteLimited,true);}
   const wrongCursor=human.reviews.find((review:any)=>review.workItemId===works[1].id).id;await assert.rejects(()=>projection({workItemId:works[0].id,after:wrongCursor}),/cursor not found/);await assert.rejects(()=>projection({after:randomUUID()}),/cursor not found/);await assert.rejects(()=>projection({workItemId:randomUUID()}),/work item not found/);const normal=await projection({});assert.equal(normal.page.limit,10);assert.equal(normal.reviews.length,10);assert.equal(normal.page.hasMore,true);
   const actual=(await tool('studio_review_policy_get',{projectId:d.project.id,limit:50})).result;assert(Buffer.byteLength(JSON.stringify(actual))<=32000);assert.equal(actual.projection.kind,'compact_agent_reviews');
  });
  async function interleave(projectId:string,releaseAt:'conversation-acquired'|'policy-update-attempt',first:()=>Promise<any>,second:()=>Promise<any>){
   const pool=database(),originals=new Map<any,any>();let reached!:()=>void,release!:()=>void;const authorityLocked=new Promise<void>(resolve=>{reached=resolve;}),otherReady=new Promise<void>(resolve=>{release=resolve;});let intercepted=false;
   const acquire=(client:any)=>{const original=client.query;originals.set(client,original);client.query=async function(...args:any[]){const sql=typeof args[0]==='string'?args[0]:'',params=args[1]??[];
    if(releaseAt==='policy-update-attempt'&&intercepted&&sql.includes('FROM studio_review_policies')&&sql.endsWith(' FOR UPDATE')&&params.includes(projectId))release();
    const result=await original.apply(client,args);
    if(!intercepted&&sql.includes('FROM studio_review_policies')&&sql.endsWith(' FOR SHARE')&&params.includes(projectId)){intercepted=true;reached();await otherReady;}
    else if(releaseAt==='conversation-acquired'&&intercepted&&sql.includes('FROM conversations')&&sql.endsWith(' FOR SHARE'))release();return result;};};
   const released=(_error:any,client:any)=>{const original=originals.get(client);if(original){client.query=original;originals.delete(client);}};pool.on('acquire',acquire);pool.on('release',released);let timeout:ReturnType<typeof setTimeout>|undefined;const timer=new Promise<never>((_,reject)=>{timeout=setTimeout(()=>{release();reject(Error('The controlled review-policy PostgreSQL lock race timed out.'));},20000);});let a:Promise<any>|undefined,b:Promise<any>|undefined;
   try{a=first();await Promise.race([authorityLocked,a.then(()=>{throw Error('Missing planning review authority lock.');}),timer]);b=second();return await Promise.race([Promise.all([a,b]),timer]);}finally{release();await Promise.allSettled([a,b].filter(Boolean));clearTimeout(timeout);pool.off('acquire',acquire);pool.off('release',released);for(const [client,original]of originals)client.query=original;}
  }
  await t.test('real PostgreSQL review completion and manual dispatch avoid conversation/project lock inversion',{skip:emulate},async()=>{const s=await submitted();await approve(s.d.project.id);const {r,lease}=await reviewClaim(s);await decide(r,lease);const d=await call(`${base}/projects/${s.d.project.id}`),work=d.workItems.find((w:any)=>w.stage==='breakdown');const [completed,manual]=await interleave(s.d.project.id,'conversation-acquired',()=>finish(lease),()=>call(`${base}/projects/${d.project.id}/dispatch`,'POST',{clientId:randomUUID(),revision:d.project.revision,workItemId:work.id},'owner',201));assert.equal(completed.run.status,'succeeded');assert.equal(manual.run.status,'queued');await call(`companies/${company}/agent-runs/${manual.run.id}/cancel`,'POST',{});});
  await t.test('real PostgreSQL exact decision serializes with policy pause without lock upgrade',{skip:emulate},async()=>{const s=await submitted();await approve(s.d.project.id);const {r,lease}=await reviewClaim(s),read=(await tool('studio_review_read',{reviewId:r.reviewId},'reviewer',lease)).result,p=(await call(policyPath(s.d.project.id))).policy,pause={clientId:randomUUID(),revision:p.revision,coordinatorAgentId:p.coordinatorAgentId,reviewerAgentId:p.reviewerAgentId,allowedStages:p.allowedStages,allowSharedSponsor:p.allowSharedSponsor,maxReviews:p.maxReviews,status:'paused',expiresAt:p.expiresAt};const [decided,paused]=await interleave(s.d.project.id,'policy-update-attempt',()=>tool('studio_review_decide',{reviewId:r.reviewId,policyRevision:read.policyRevision,submissionSha256:read.submissionSha256,decision:'approve',note},'reviewer',lease),()=>call(policyPath(s.d.project.id),'PUT',pause));assert.equal(decided.result.task.status,'done');assert.equal(paused.policy.status,'paused');assert.equal((await call(`agent/runs/${lease.run.id}/heartbeat`,'POST',{leaseToken:lease.leaseToken},'reviewer',409)).code,'STUDIO_REVIEW_AUTHORITY_ENDED');await call(`companies/${company}/agent-runs/${lease.run.id}/cancel`,'POST',{});});
  await t.test('real PostgreSQL distinct parent leases consume one review reservation for one exact submission',{skip:emulate},async()=>{const s=await submitted();await approve(s.d.project.id,{maxReviews:1});const other=(await call(`companies/${company}/conversations/commons/runs`,'POST',{clientId:randomUUID(),agentId:agents.coordinator.id,prompt:'Synthetic second parent to test the shared review budget.'},'owner',201)).run,leaseToken=randomUUID()+randomUUID();await query("UPDATE agent_runs SET status='running',attempts=1,worker_id='second-review-coordinator',lease_token_hash=$2,lease_expires_at=clock_timestamp()+interval '1 minute',started_at=clock_timestamp() WHERE id=$1",[other.id,hashToken(leaseToken)]);const results=await Promise.all([parent,{run:other,leaseToken}].map(lease=>tool('studio_review_dispatch',{projectId:s.d.project.id,workItemId:s.w.id,taskRevision:s.w.revision,policyRevision:1},'coordinator',lease)));assert.equal(results[0].result.reviewerRunId,results[1].result.reviewerRunId);assert.equal((await call(policyPath(s.d.project.id))).policy.reviewsStarted,1);assert.equal(Number((await query('SELECT count(*) FROM studio_planning_reviews WHERE company_id=$1 AND project_id=$2',[company,s.d.project.id])).rows[0].count),1);await call(`companies/${company}/agent-runs/${results[0].result.reviewerRunId}/cancel`,'POST',{});await call(`companies/${company}/agent-runs/${other.id}/cancel`,'POST',{});});
 }finally{try{await query('DELETE FROM companies WHERE id=ANY($1::uuid[])',[[company,foreign]]);await query('DELETE FROM users WHERE id=ANY($1::uuid[])',[[owner,admin,member,outsider]]);}finally{await database().end();delete(globalThis as any).coatriaPool;await stop?.();for(const [key,value]of Object.entries(prior)){if(value===undefined)delete process.env[key];else process.env[key]=value;}}}
});
