import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {Pool} from 'pg';
import {database,query,transaction} from '../src/lib/db';
import {hashToken} from '../src/lib/security';
import {handleApi} from '../src/lib/api';
import {missionCreateInput} from '../src/lib/agent-missions';
import {studioCoordinatorObjective,STUDIO_GENERATED_COORDINATOR_OBJECTIVE_VERSION} from '../src/lib/studio-coordinator-objective';
import {studioGeneratedRevisionSnapshotInput} from '../src/lib/studio-generated-revision-protocol';
import {generatedClientSpecs,seedGeneratedClientSource} from './fixtures/generated-client-delivery';
import {createProviderExecutor} from '../public/downloads/provider-adapter.mjs';
import {dropFixtureDatabase} from './fixtures/postgres-teardown';

test('stock coordinator objectives fit the real mission contract without raising its limit',()=>{
 assert.equal(hashToken(studioCoordinatorObjective({id:'00000000-0000-4000-8000-000000000001'})),'546edbf7be4e97cbb42738337826b931d4474897f539c78137264f4e95b59591','Legacy coordinator text remains byte-identical.');
 for(const contractVersion of [1,2] as const){const id=randomUUID(),objective=studioCoordinatorObjective({id,contractVersion});assert(missionCreateInput.safeParse({clientId:randomUUID(),agentId:randomUUID(),name:'Studio coordinator',objective}).success);assert(objective.length<=3000);assert(objective.includes(id));if(contractVersion===2){assert.match(objective,new RegExp('Generated coordinator v'+STUDIO_GENERATED_COORDINATOR_OBJECTIVE_VERSION));assert(objective.indexOf('studio_generated_revision_draft')<objective.indexOf('no ready work'));}else{assert(!objective.includes('studio_generated_revision'));assert(!objective.includes('contractVersion:2'));}}
});

type Row=Record<string,any>;
const emulate=process.env.COATRIA_TEST_EMULATOR==='1',integration=process.env.COATRIA_INTEGRATION_DATABASE_URL;
const local=(()=>{try{return !!integration&&['localhost','127.0.0.1'].includes(new URL(integration).hostname);}catch{return false;}})();
test('stock generated coordinator cycles draft and select exact paged feedback without applying work or spending',{skip:!emulate&&!local,timeout:120000},async t=>{
 const environment={...process.env},dbName='coatria_coordinator_'+randomUUID().replaceAll('-','');let stop:(()=>Promise<void>)|undefined,control:Pool|undefined;
 process.env.DATABASE_POOL_MAX=emulate?'1':'4';process.env.COATRIA_STORAGE_GATEWAY_ENABLED='true';process.env.COATRIA_STORAGE_GATEWAY_URL='https://gateway.example.invalid';
 const files=(await readdir('database')).filter(file=>/^\d.*\.sql$/.test(file)).sort();
 if(emulate){const {PGlite}=await import('@electric-sql/pglite'),{PGLiteSocketServer}=await import('@electric-sql/pglite-socket'),db=await PGlite.create();for(const file of files)await db.exec(await readFile('database/'+file,'utf8'));const server=new PGLiteSocketServer({db,host:'127.0.0.1',port:0,maxConnections:1});await server.start();process.env.DATABASE_URL=['postgresql',':','//postgres',':','postgres@',server.getServerConn(),'/postgres'].join('');stop=async()=>{await server.stop();await db.close();};}
 else{control=new Pool({connectionString:integration,max:1});await control.query('CREATE DATABASE '+dbName);const url=new URL(integration!);url.pathname='/'+dbName;process.env.DATABASE_URL=url.href;for(const file of files)await query(await readFile('database/'+file,'utf8'));}
 const company=randomUUID(),users={owner:randomUUID(),registrar:randomUUID(),reviewer:randomUUID(),client:randomUUID()},sessions=Object.fromEntries(Object.keys(users).map(name=>[name,randomUUID()])),origin='http://localhost:4180';let token='',agentId='';
 async function call(path:string,method='GET',payload?:unknown,actor='owner',expected=200):Promise<Row>{const response=await handleApi(new Request(origin+'/api/'+path,{method,headers:{Origin:origin,...actor==='agent'?{Authorization:'Bearer '+token}:{Cookie:'coatria_session='+sessions[actor]},...payload===undefined?{}:{'Content-Type':'application/json'}},...payload===undefined?{}:{body:JSON.stringify(payload)}}),path.split('?')[0].split('/')),result=await response.json();assert.equal(response.status,expected,`${method} ${path}: ${JSON.stringify(result)}`);return result;}
 const prefix=(id:string)=>`companies/${company}/studio/projects/${id}`,missions=`companies/${company}/autonomy/missions`;
 async function feedback(){
  const made=await call(`companies/${company}/studio/projects`,'POST',{clientId:randomUUID(),contractVersion:2,productionPath:'higgsfield',name:'Coordinator revision fixture',clientName:'Synthetic client',brief:'Two images under the same approved technical contract.',aiPolicy:'allowed',spec:generatedClientSpecs.image,shots:['MEDIA010','MEDIA020'].map(code=>({kind:'image',code,description:'Synthetic '+code}))},'owner',201),projectId=made.project.id;
  const work=(await query("SELECT w.id,w.task_id,s.code FROM studio_work_items w JOIN studio_shots s ON s.id=w.shot_id WHERE w.project_id=$1 AND w.stage='generation' ORDER BY s.code",[projectId])).rows;let revision=made.project.revision;const artifacts:string[]=[];let storage:{storageId:string;bindingId:string}|undefined;
  await query("UPDATE tasks SET status='done' WHERE id IN(SELECT task_id FROM studio_work_items WHERE project_id=$1 AND stage IN('estimate','breakdown','references'))",[projectId]);await query('UPDATE studio_projects SET gates=$2 WHERE id=$1',[projectId,JSON.stringify({brief:{decision:'approved'},estimate:{decision:'approved'},production:{decision:'approved'}})]);
  for(const item of work){const source=await transaction(db=>seedGeneratedClientSource(db,{companyId:company,projectId,workItemId:item.id,taskId:item.task_id,producerId:users.owner,approverId:users.owner,kind:'image',storage}));storage={storageId:source.storageId,bindingId:source.bindingId};const registered=await call(prefix(projectId)+'/generated-artifacts','POST',{clientId:randomUUID(),revision,workItemId:item.id,archiveId:source.archiveId,name:item.code,notes:'Synthetic verified source'},'registrar',201),reviewed=await call(prefix(projectId)+'/reviews','POST',{clientId:randomUUID(),revision:registered.project.revision,artifactId:registered.artifact.id,decision:'approved',note:'Independent synthetic approval',technicalQc:true},'reviewer',201);revision=reviewed.project.revision;artifacts.push(registered.artifact.id);}
  await query("UPDATE tasks SET status='done' WHERE id IN(SELECT task_id FROM studio_work_items WHERE project_id=$1)",[projectId]);const prepared=await call(prefix(projectId)+'/deliveries','POST',{clientId:randomUUID(),revision,name:'Original package',artifactIds:artifacts,note:'Exact two-image package'},'owner',201),share=(await call(prefix(projectId)+'/client-deliveries','POST',{clientId:randomUUID(),revision:prepared.project.revision,deliveryId:prepared.delivery.id,recipientUserId:users.client,identityConfirmation:'confirmed_out_of_band',expiresAt:new Date(Date.now()+3600000).toISOString()},'owner',201)).share;
  const response=await call('client-deliveries/'+share.id+'/responses','POST',{clientId:randomUUID(),revision:share.revision,decision:'changes_requested',note:'Regenerate MEDIA010 with a warmer palette; retain MEDIA020 exactly. This changes neither format nor deliverable count.'},'client',201);return {projectId,share,response};
 }
 async function mission(projectId:string){const objective=studioCoordinatorObjective({id:projectId,contractVersion:2}),saved=await call(missions,'POST',{clientId:randomUUID(),agentId,name:'Stock generated coordinator',objective,status:'paused',maxCycles:5,intervalMinutes:60},'owner',201);assert.equal(saved.mission.objective,objective);await call(missions+'/'+saved.mission.id,'PATCH',{revision:saved.mission.revision,status:'active'});return saved.mission.id as string;}
 async function claim(missionId:string){const queued=await call(missions+'/'+missionId+'/run-now','POST',{clientId:randomUUID()},'owner',201),lease=await call('agent/runs/claim','POST',{workerId:'synthetic-coordinator',claimId:randomUUID()},'agent');assert.equal(lease.run.id,queued.runId);return lease;}
 async function context(lease:Row){const parts=['agent','runs',lease.run.id,'context'],response=await handleApi(new Request(origin+'/api/'+parts.join('/'),{headers:{Authorization:'Bearer '+token,'X-Coatria-Run-Lease':lease.leaseToken}}),parts);assert.equal(response.status,200);return response.json();}
 async function tool(lease:Row,name:string,args:unknown,requestId:string=randomUUID(),expected=200){return call('agent/tools/'+name,'POST',{runId:lease.run.id,leaseToken:lease.leaseToken,requestId,arguments:args},'agent',expected);}
 // The model responses are deterministic fixtures. The mission, context,
 // complete catalog, leased tools, immutable plans and receipts are real APIs.
 async function cycle(projectId:string,lease:Row,options:{beforeDraft?:()=>Promise<void>;beforeRefresh?:()=>Promise<void>;sourceItemLimit?:number;planItemLimit?:number}={}){
  const sourceItemLimit=options.sourceItemLimit??1,planItemLimit=options.planItemLimit??1;
  const runtime=await context(lease),effects:Array<{name:string;args:Row;requestId:string;result:Row;phase:string}>=[],pages:Row[]=[],summaries:Row[]=[],refreshedSummaries:Row[]=[];let step=0,phase='project',pinned:Row|undefined,selected:Row|undefined,refreshStarted=false;
  const matches=(plan:Row)=>!plan.appliedRoundId&&plan.projectRevision===pinned!.revision&&plan.source.receiptId===pinned!.source.receiptId&&plan.source.shareId===pinned!.source.shareId&&plan.source.packageSha256===pinned!.source.packageSha256&&plan.source.roundId===pinned!.source.roundId;
  const execute=createProviderExecutor({settings:{NODE_ENV:'test',RUNPOD_API_KEY:'fixture-key',COATRIA_RUNPOD_ENDPOINT_ID:'fixture-endpoint'},fetch:(async(_url,init)=>{
   const request=JSON.parse(String(init?.body)).input.openai_input;assert(Buffer.byteLength(JSON.stringify(request))+step*150+2048+1024<=80000);const initial=JSON.parse(request.messages[1].content);assert.match(initial.verifiedRequest.prompt,/Generated coordinator v2/);assert.match(initial.verifiedRequest.prompt,/human application/);assert(request.tools.some((entry:Row)=>entry.function.name==='studio_generated_revision_draft'));
   let name:string|undefined,args:Row={};const last=effects.at(-1)?.result;
   if(phase==='project'){name='studio_get';args={projectId,contractVersion:2,limit:1};phase='source';}
   else if(phase==='source'){name='studio_generated_revisions_get';args={projectId,limit:1,itemLimit:sourceItemLimit};phase='source-pages';}
   else if(['source-pages','items'].includes(phase)){
    assert(last?.source);if(!pinned)pinned={revision:last.projectRevision,source:last.source.source};assert.deepEqual(last.source.source,pinned.source);assert.equal(last.projectRevision,pinned.revision);if(phase==='source-pages')summaries.push(...last.plans);if(phase==='source-pages'&&last.page.hasMore){name='studio_generated_revisions_get';args={projectId,limit:1,itemLimit:sourceItemLimit,after:last.page.nextAfter};}else{pages.push(...last.source.items);
    if(last.itemPage.hasMore){name='studio_generated_revisions_get';args={projectId,limit:1,itemLimit:sourceItemLimit,itemAfter:last.itemPage.nextAfter};phase='items';}
    else{assert.equal(pages.length,last.itemPage.total);selected=summaries.find(matches);name='studio_generated_revisions_get';args={projectId,...selected?{planId:selected.id,itemLimit:planItemLimit}:{limit:1,itemLimit:sourceItemLimit}};phase=selected?'plan-pages':'refresh';}}
   }else if(phase==='plan-pages'){assert.equal(last?.plan.id,selected!.id);assert.equal(last?.plan.planSha256,selected!.planSha256);if(last?.itemPage.hasMore){name='studio_generated_revisions_get';args={projectId,planId:selected!.id,itemLimit:planItemLimit,itemAfter:last.itemPage.nextAfter};}else phase='done';}
   else if(phase==='refresh'){
    assert.deepEqual(last?.source.source,pinned!.source);assert.equal(last?.projectRevision,pinned!.revision);refreshedSummaries.push(...last!.plans);
    if(last!.page.hasMore){name='studio_generated_revisions_get';args={projectId,limit:1,itemLimit:sourceItemLimit,after:last!.page.nextAfter};}
    else if((selected=refreshedSummaries.find(matches))){name='studio_generated_revisions_get';args={projectId,planId:selected.id,itemLimit:planItemLimit};phase='plan-pages';}
    else{name='studio_generated_revision_draft';args={projectId,projectRevision:pinned!.revision,shareId:pinned!.source.shareId,receiptId:pinned!.source.receiptId,packageSha256:pinned!.source.packageSha256,summary:'One creative correction; retain the exact other approved image.',items:pages.map(item=>item.code==='MEDIA010'?{unitId:item.unitId,action:'regenerate',instructions:'Use a warmer palette, preserving the approved image specification.'}:{unitId:item.unitId,action:'carry'})};phase='done';}
   }
   const output={usage:{prompt_tokens:100,completion_tokens:50},choices:[{finish_reason:name?'tool_calls':'stop',message:{role:'assistant',content:name?null:'Revision plan '+(selected?.id??last?.planId)+' is awaiting human application. No new production is authorized.',...name?{tool_calls:[{id:'coordinator_'+step,type:'function',function:{name,arguments:JSON.stringify(args)}}]}:{}}}]};step++;return new Response(JSON.stringify({id:'fixture-'+step,status:'COMPLETED',output:[output]}),{headers:{'Content-Type':'application/json'}});
  }) as typeof fetch});
  const result=await execute({run:lease.run,context:runtime,signal:new AbortController().signal,tools:{key:()=>randomUUID(),list:()=>call('agent/tools','GET',undefined,'agent'),call:async(name:string,args:Row,metadata:{requestId:string})=>{if(phase==='refresh'&&!refreshStarted){refreshStarted=true;await options.beforeRefresh?.();}if(name==='studio_generated_revision_draft')await options.beforeDraft?.();const response=await tool(lease,name,args,metadata.requestId);effects.push({name,args,requestId:metadata.requestId,result:response.result,phase});return response.result;}}});return {result,effects,pages,selected};
 }
 try{
  for(const [name,userId]of Object.entries(users)){await query('INSERT INTO users(id,name,email,password_hash) VALUES($1,$2,$3,$4)',[userId,name,userId+'@example.invalid','synthetic-not-login']);await query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,clock_timestamp()+interval '1 hour')",[hashToken(sessions[name]),userId]);}
  await query("INSERT INTO companies(id,name,slug,template) VALUES($1,'Coordinator fixture',$2,'blank')",[company,company]);for(const [name,role]of [['owner','owner'],['registrar','admin'],['reviewer','admin']] as const)await query('INSERT INTO memberships(company_id,user_id,role) VALUES($1,$2,$3)',[company,users[name],role]);
  const installed=await call(`companies/${company}/plugin-installations`,'POST',{clientId:randomUUID(),pluginId:'runpod',manifestVersion:'1.0.0',name:'Coordinator',invocationAccess:'admins',capabilities:['studio.read','studio.write','tasks.write'],runtimeConfig:{providerId:'runpod',modelId:'Qwen/Qwen3.8-27B-FP8',maxSteps:8,maxOutputTokens:2048,maxTotalTokens:80000,timeoutSeconds:180}},'owner',201);agentId=installed.installation.agentId;token=installed.token;
  await call(`companies/${company}/studio/setup`,'POST',{clientId:randomUUID(),templateId:'ai-production',templateVersion:1,revision:0,assignments:[{roleKey:'coordinator',agentId},{roleKey:'comp',humanId:users.owner},{roleKey:'qc',humanId:users.reviewer}]},'owner',201);
  const priorMission=(await call(missions,'POST',{clientId:randomUUID(),agentId,name:'Earlier reviewed mission',objective:'Preserve this earlier reviewed objective.',status:'paused',maxCycles:1},'owner',201)).mission;
  await t.test('a real saved mission drafts once across item pages then a later cycle selects the same draft',async()=>{
   const f=await feedback(),snapshot=await call(prefix(f.projectId)+'/generated-revisions');const obsolete=await call(prefix(f.projectId)+'/generated-revisions','POST',{clientId:randomUUID(),projectRevision:snapshot.projectRevision,shareId:f.share.id,receiptId:f.response.receipt.id,packageSha256:f.share.packageSha256,summary:'Older draft before a project update',items:snapshot.source.items.map((item:Row)=>({unitId:item.unitId,action:'regenerate',instructions:'Older creative draft.'}))},'owner',201);await query('UPDATE studio_projects SET revision=revision+1 WHERE id=$1',[f.projectId]);const missionId=await mission(f.projectId),first=await claim(missionId),ran=await cycle(f.projectId,first);assert.equal(ran.pages.length,2);assert.equal(new Set(ran.pages.map(item=>item.unitId)).size,2);const writes=ran.effects.filter(effect=>effect.name==='studio_generated_revision_draft');assert.equal(writes.length,1);const draft=writes[0];assert.equal(draft.result.changedCount,1);assert.equal(draft.result.carryCount,1);
   assert.equal((await tool(first,draft.name,draft.args,draft.requestId)).replayed,true);assert.equal((await tool(first,draft.name,{...draft.args,receiptId:randomUUID()},randomUUID(),409)).code,'STUDIO_REVISION_SOURCE_INVALID');
   await call(`agent/runs/${first.run.id}/complete`,'POST',{clientId:randomUUID(),leaseToken:first.leaseToken,result:ran.result.result},'agent');const second=await claim(missionId),selected=await cycle(f.projectId,second);assert.equal(selected.selected!.id,draft.result.planId);assert.notEqual(selected.selected!.id,obsolete.plan.id);assert(selected.effects.some(effect=>effect.args.after));assert(!selected.effects.some(effect=>effect.name==='studio_generated_revision_draft'));assert.equal(selected.effects.filter(effect=>effect.args.planId).length,2);
   await call(`agent/runs/${second.run.id}/complete`,'POST',{clientId:randomUUID(),leaseToken:second.leaseToken,result:selected.result.result},'agent');
   assert.equal((await query('SELECT count(*)::int n FROM studio_generated_revision_plans WHERE project_id=$1',[f.projectId])).rows[0].n,2);assert.equal((await query('SELECT count(*)::int n FROM studio_generated_revision_rounds WHERE project_id=$1',[f.projectId])).rows[0].n,0);assert.equal((await query('SELECT count(*)::int n FROM higgsfield_requests WHERE project_id=$1',[f.projectId])).rows[0].n,2);assert.equal((await query('SELECT count(*)::int n FROM studio_client_deliveries WHERE project_id=$1',[f.projectId])).rows[0].n,1);
   assert.deepEqual((await call(missions+'/'+priorMission.id)).mission,priorMission);
  });
  await t.test('a matching draft appearing on a later refresh page is read and selected without a second draft',async()=>{
   const f=await feedback(),snapshot=await call(prefix(f.projectId)+'/generated-revisions');
   // A valid append-only old plan sorts before any randomly generated v4 ID.
   // Only its fixture ID is chosen; database source/pin/hash checks still apply.
   const obsoleteId='00000000-0000-4000-8000-000000000000',obsolete=studioGeneratedRevisionSnapshotInput.parse({schemaVersion:1,projectId:f.projectId,projectRevision:snapshot.projectRevision,source:snapshot.source.source,summary:'Earlier draft before the project update',items:snapshot.source.items.map((item:Row)=>({...item,action:'regenerate',instructions:'Earlier creative correction.'}))});
   await query("INSERT INTO studio_generated_revision_plans(id,company_id,project_id,source_share_id,source_receipt_id,source_delivery_id,package_sha256,snapshot,plan_sha256,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,encode(sha256(convert_to(studio_generated_canonical($8::jsonb),'UTF8')),'hex'),$9)",[obsoleteId,company,f.projectId,f.share.id,f.response.receipt.id,obsolete.source.deliveryId,f.share.packageSha256,JSON.stringify(obsolete),users.owner]);
   await query('UPDATE studio_projects SET revision=revision+1 WHERE id=$1',[f.projectId]);
   const missionId=await mission(f.projectId),lease=await claim(missionId);let refreshes=0,matching:Row|undefined;
   const ran=await cycle(f.projectId,lease,{sourceItemLimit:20,planItemLimit:20,beforeRefresh:async()=>{
    refreshes++;const current=await call(prefix(f.projectId)+'/generated-revisions');matching=(await call(prefix(f.projectId)+'/generated-revisions','POST',{clientId:randomUUID(),projectRevision:current.projectRevision,shareId:f.share.id,receiptId:f.response.receipt.id,packageSha256:f.share.packageSha256,summary:'Human draft saved while the coordinator was reading',items:current.source.items.map((item:Row)=>item.code==='MEDIA010'?{unitId:item.unitId,action:'regenerate',instructions:'Use a warmer palette within the approved specification.'}:{unitId:item.unitId,action:'carry'})},'owner',201)).plan;
   }});
   assert.equal(refreshes,1);assert(matching);assert.equal(ran.selected!.id,matching.id);assert.equal(ran.selected!.planSha256,matching.planSha256);assert.equal(ran.pages.length,2);
   const initial=ran.effects.filter(effect=>effect.phase==='source-pages'),refreshed=ran.effects.filter(effect=>effect.phase==='refresh');assert.equal(initial.length,1);assert.deepEqual(initial[0].result.plans.map((plan:Row)=>plan.id),[obsoleteId]);assert.equal(initial[0].result.page.hasMore,false);
   assert.equal(refreshed.length,2);assert.equal(refreshed[0].result.page.hasMore,true);assert.deepEqual(refreshed[0].result.plans.map((plan:Row)=>plan.id),[obsoleteId]);assert.equal(refreshed[1].args.after,refreshed[0].result.page.nextAfter);assert.equal(refreshed[1].result.page.hasMore,false);assert.equal(refreshed[1].result.plans[0].id,matching.id);
   for(const page of refreshed){assert.deepEqual(page.result.source.source,initial[0].result.source.source);assert.equal(page.result.projectRevision,initial[0].result.projectRevision);}
   assert.equal(ran.effects.filter(effect=>effect.args.planId===matching!.id).length,1);assert(!ran.effects.some(effect=>effect.name==='studio_generated_revision_draft'));
   await call(`agent/runs/${lease.run.id}/complete`,'POST',{clientId:randomUUID(),leaseToken:lease.leaseToken,result:ran.result.result},'agent');
   assert.equal((await query('SELECT count(*)::int n FROM studio_generated_revision_plans WHERE project_id=$1',[f.projectId])).rows[0].n,2);assert.equal((await query('SELECT count(*)::int n FROM studio_generated_revision_plans WHERE project_id=$1 AND created_agent_id IS NOT NULL',[f.projectId])).rows[0].n,0);assert.equal((await query('SELECT count(*)::int n FROM studio_generated_revision_rounds WHERE project_id=$1',[f.projectId])).rows[0].n,0);assert.equal((await query('SELECT count(*)::int n FROM higgsfield_requests WHERE project_id=$1',[f.projectId])).rows[0].n,2);
  });
  await t.test('a project change after refresh denies the write and a failed cycle requires human reconciliation',async()=>{
   const f=await feedback(),missionId=await mission(f.projectId),lease=await claim(missionId);let attempts=0;
   await assert.rejects(()=>cycle(f.projectId,lease,{beforeDraft:async()=>{attempts++;await query('UPDATE studio_projects SET revision=revision+1 WHERE id=$1',[f.projectId]);}}),/tool was denied or failed/);assert.equal(attempts,1);assert.equal((await query('SELECT count(*)::int n FROM studio_generated_revision_plans WHERE project_id=$1',[f.projectId])).rows[0].n,0);
   await call(`agent/runs/${lease.run.id}/fail`,'POST',{clientId:randomUUID(),leaseToken:lease.leaseToken,error:'Synthetic changed-source failure; inspect saved effects.'},'agent');assert.equal((await call(missions+'/'+missionId+'/run-now','POST',{clientId:randomUUID()},'owner',409)).code,'MISSION_REVIEW_REQUIRED');
  });
 }finally{
  try{await database().end();}finally{
   delete(globalThis as {coatriaPool?:Pool}).coatriaPool;
   try{await stop?.();}finally{
    try{if(control){try{await dropFixtureDatabase(control,dbName);}finally{await control.end();}}}
    finally{for(const key of Object.keys(process.env))if(!(key in environment))delete process.env[key];Object.assign(process.env,environment);}
   }
  }
 }
});
