import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {database,query} from '../src/lib/db';
import {hashToken,errorResponse} from '../src/lib/security';
import {studioMediaRoute,type StudioMediaProvider} from '../src/lib/studio-media';
import {EXECUTION_BUILTIN_PROFILES} from '../src/lib/studio-execution-protocol';
import {agentRuntimeOpenApi} from '../src/lib/agent-runtime-openapi';
import {studioWorkDispatchInput} from '../src/lib/studio-coordination-protocol';

test('post-render dispatch accepts an exact job reference, never caller-picked artifact, specialist or grant',()=>{
 const input={projectId:randomUUID(),workItemId:randomUUID(),executionJobId:randomUUID(),policyRevision:1,projectRevision:1};assert(studioWorkDispatchInput.safeParse(input).success);
 const spec:any=agentRuntimeOpenApi;assert(spec.components.schemas.StudioCoordinationSnapshot.properties.renderFollowups);assert(spec.paths['/api/agent/tools/studio_work_dispatch'].post.requestBody.content['application/json'].schema.properties.arguments.properties.executionJobId);
 for(const patch of [{artifactId:randomUUID()},{agentId:randomUUID()},{retry:true},{capabilities:['studio.execute']},{executionJobId:'foreign'}])assert(!studioWorkDispatchInput.safeParse({...input,...patch}).success);
});
const emulate=process.env.COATRIA_TEST_EMULATOR==='1',connection=process.env.COATRIA_INTEGRATION_DATABASE_URL;
test('coordinator resumes only its successful, privately verified and human-promoted render once',{skip:!emulate&&!connection,timeout:180000},async t=>{
 const {handleApi}=await import('../src/lib/api'),before={DATABASE_URL:process.env.DATABASE_URL,DATABASE_POOL_MAX:process.env.DATABASE_POOL_MAX};process.env.DATABASE_URL=connection;process.env.DATABASE_POOL_MAX=emulate?'1':'10';let stop:(()=>Promise<void>)|undefined;
 if(emulate){const {PGlite}=await import('@electric-sql/pglite'),{PGLiteSocketServer}=await import('@electric-sql/pglite-socket'),db=await PGlite.create();for(const f of(await readdir('database')).filter(f=>/^\d.*\.sql$/.test(f)).sort())await db.exec(await readFile('database/'+f,'utf8'));const socket=new PGLiteSocketServer({db,host:'127.0.0.1',port:0,maxConnections:1});await socket.start();const url=new URL('postgresql://'+socket.getServerConn()+'/postgres');url.username='postgres';url.password='postgres';process.env.DATABASE_URL=url.href;stop=async()=>{await socket.stop();await db.close();};}
 const origin='http://localhost:4180',companies:string[]=[],users:string[]=[],profile=EXECUTION_BUILTIN_PROFILES[0];
 async function fixture({promote=true,budget=2,concurrency=1,twoShots=false}={}){
  const company=randomUUID(),owner=randomUUID(),reviewer=randomUUID(),sessions={owner:randomUUID(),reviewer:randomUUID()},agents:Record<string,any>={},blobs=new Map<string,Uint8Array>();companies.push(company);users.push(owner,reviewer);
  for(const[name,user]of [['owner',owner],['reviewer',reviewer]]){await query('INSERT INTO users(id,name,email,password_hash) VALUES($1,$2,$3,$4)',[user,'Follow-up '+name,user+'@example.invalid','fixture']);await query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,clock_timestamp()+interval '1 hour')",[hashToken(sessions[name as keyof typeof sessions]),user]);}
  await query("INSERT INTO companies(id,name,slug,template) VALUES($1,'Follow-up fixture',$2,'blank')",[company,company]);await query("INSERT INTO memberships(company_id,user_id,role) VALUES($1,$2,'owner'),($1,$3,'admin')",[company,owner,reviewer]);
  let connectorToken='';const provider:StudioMediaProvider={signUpload:async()=> 'https://fixture.invalid/scoped-upload',signRead:async()=> 'https://fixture.invalid/scoped-read',read:async path=>{const bytes=blobs.get(path);return bytes?{bytes:bytes.length,etag:hashToken(Buffer.from(bytes).toString()),stream:new ReadableStream({start(controller){controller.enqueue(bytes);controller.close();}})}:null;}};
  async function call(path:string,method='GET',payload?:unknown,actor='owner',expected=200){const headers:Record<string,string>={Origin:origin};if(actor==='renderer')headers.Authorization='Bearer '+connectorToken;else if(agents[actor])headers.Authorization='Bearer '+agents[actor].token;else headers.Cookie='coatria_session='+sessions[actor as keyof typeof sessions];if(payload!==undefined)headers['Content-Type']='application/json';const request=new Request(origin+'/api/'+path,{method,headers,...payload===undefined?{}:{body:JSON.stringify(payload)}});let response:Response;try{response=await studioMediaRoute(request,path.split('/'),method,provider)??await handleApi(request,path.split('/'));}catch(error){response=errorResponse(error);}const result=await response.json();assert.equal(response.status,expected,`${method} ${path}: ${JSON.stringify(result)}`);return result;}
  const base=`companies/${company}/studio`;
  for(const name of ['coordinator','comp']){const installed=await call(`companies/${company}/plugin-installations`,'POST',{clientId:randomUUID(),pluginId:'runpod',manifestVersion:'1.0.0',name,invocationAccess:'admins',capabilities:['studio.read','studio.write','tasks.write',...(name==='comp'?['studio.execute']:[])],runtimeConfig:{providerId:'runpod',modelId:'Qwen/Qwen3.8-27B-FP8',maxSteps:8,maxOutputTokens:2048,maxTotalTokens:24000,timeoutSeconds:180}},'owner',201);agents[name]={id:installed.installation.agentId,token:installed.token,installationId:installed.installation.id};}
  await call(base+'/setup','POST',{clientId:randomUUID(),templateId:'vfx-boutique',templateVersion:1,revision:0,assignments:[{roleKey:'coordinator',agentId:agents.coordinator.id},{roleKey:'comp',agentId:agents.comp.id},{roleKey:'qc',humanId:reviewer}]},'owner',201);
  const spec={width:128,height:128,fpsNumerator:24,fpsDenominator:1,format:'exr',colorSpace:'Linear Rec.709'},project=(await call(base+'/projects','POST',{clientId:randomUUID(),name:'Synthetic completed render',clientName:'Fixture',brief:'Synthetic private render continuation fixture.',aiPolicy:'allowed',spec,shots:[{code:'SH010',description:'Synthetic output',frameStart:1,frameEnd:2,handles:0,disciplines:['compositing']},...twoShots?[{code:'SH020',description:'Second synthetic output',frameStart:1,frameEnd:2,handles:0,disciplines:['compositing']}]:[]]},'owner',201)).project;
  // Fixture prerequisites model accepted planning work; production gates still use real human APIs.
  await query("UPDATE tasks SET status='done' WHERE company_id=$1 AND id IN(SELECT task_id FROM studio_work_items WHERE company_id=$1 AND project_id=$2 AND stage IN('estimate','breakdown','ingest'))",[company,project.id]);
  const detail=()=>call(`${base}/projects/${project.id}`),policy=()=>call(`${base}/projects/${project.id}/coordination`);
  for(const gate of ['brief','estimate','production'])await call(`${base}/projects/${project.id}/gates`,'POST',{clientId:randomUUID(),revision:(await detail()).project.revision,gate,decision:'approved',note:'Synthetic human approval.'},'owner',201);
  await call(`${base}/projects/${project.id}/coordination`,'PUT',{clientId:randomUUID(),revision:0,coordinatorAgentId:agents.coordinator.id,allowedRoleKeys:['comp'],status:'active',maxRuns:budget,maxConcurrentRuns:concurrency,expiresAt:new Date(Date.now()+3600000).toISOString()});
  const parentRun=(await call(`companies/${company}/conversations/commons/runs`,'POST',{clientId:randomUUID(),agentId:agents.coordinator.id,prompt:'Coordinate this synthetic reviewed render.'},'owner',201)).run,parent=await call('agent/runs/claim','POST',{workerId:'follow-up-coordinator',claimId:randomUUID()},'coordinator');assert.equal(parent.run.id,parentRun.id);
  const work=(await detail()).workItems.find((w:any)=>w.stage==='compositing');
  const dispatch=async(jobId?:string,expected=200,patch:Record<string,unknown>={})=>call('agent/tools/studio_work_dispatch','POST',{runId:parent.run.id,leaseToken:parent.leaseToken,requestId:randomUUID(),arguments:{projectId:project.id,workItemId:work.id,projectRevision:(await detail()).project.revision,policyRevision:(await policy()).policy.revision,...jobId?{executionJobId:jobId}:{},...patch}},'coordinator',expected);
  const initial=(await dispatch()).result,child=await call('agent/runs/claim','POST',{workerId:'follow-up-comp',claimId:randomUUID()},'comp');assert.equal(child.run.id,initial.childRunId);
  const tool=(lease:any,name:string,args:unknown,expected=200)=>call('agent/tools/'+name,'POST',{runId:lease.run.id,leaseToken:lease.leaseToken,requestId:randomUUID(),arguments:args},'comp',expected);
  await tool(child,'tasks_claim',{taskId:work.taskId,revision:work.revision});
  const connector=await call(base+'/execution/connectors','POST',{clientId:randomUUID(),name:'Synthetic renderer',profiles:[profile]},'owner',201);connectorToken=connector.token;
  const submitted=await tool(child,'studio_execution_submit',{projectId:project.id,revision:(await detail()).project.revision,workItemId:work.id,connectorId:connector.connector.id,profileKey:profile.key,profileVersion:profile.version,inputIds:[],frameStart:1,frameEnd:2,outputKind:'image_sequence'}),job=submitted.result.job;
  assert.equal(job.status,'awaiting_approval');await call(`agent/runs/${child.run.id}/complete`,'POST',{clientId:randomUUID(),leaseToken:child.leaseToken,result:'Render proposal recorded; waiting for human approval and renderer.'},'comp');
  await call(base+'/execution/jobs/'+job.id+'/approve','POST',{clientId:randomUUID(),revision:job.revision});const renderLease=await call('execution/jobs/claim','POST',{claimId:randomUUID(),workerId:'synthetic-renderer'},'renderer');assert.equal(renderLease.job.id,job.id);
  const source=new Map([['frames/0001.exr',Buffer.from('fixture frame one')],['frames/0002.exr',Buffer.from('fixture frame two')],['scene.blend',Buffer.from('fixture native scene')]]),files=[...source].map(([path,bytes],index)=>({path,kind:index<2?'image':'scene',...(index<2?{frame:index+1}:{}),sha256:hashToken(bytes.toString()),bytes:bytes.length}));
  const manifest={schemaVersion:1,files,spec,engineVersion:'synthetic-no-renderer-process',verification:{fileHashes:true,fileSizes:true,frameCoverage:true,imageMetadata:true}};
  await call(`execution/jobs/${job.id}/complete`,'POST',{clientId:randomUUID(),leaseToken:renderLease.leaseToken,manifest},'renderer');
  for(const file of files){const prepared=await call(`execution/jobs/${job.id}/media/upload`,'POST',{clientId:randomUUID(),path:file.path},'renderer'),stored=(await query('SELECT blob_pathname FROM studio_media_files WHERE company_id=$1 AND id=$2',[company,prepared.file.id])).rows[0];blobs.set(stored.blob_pathname,source.get(file.path)!);await call(`execution/jobs/${job.id}/media/verify`,'POST',{clientId:randomUUID(),fileId:prepared.file.id},'renderer');}
  const promoteMedia=async()=>call(`${base}/execution/jobs/${job.id}/media/promote`,'POST',{clientId:randomUUID(),revision:(await detail()).project.revision,name:'Human-selected verified render'});
  const promoted=promote?await promoteMedia():null;
  return{company,owner,reviewer,agents,project,work,job,child,parent,call,tool,detail,policy,dispatch,promoteMedia,promoted,initial,base};
 }
 try{
  await t.test('real render job, verified publishing and human promotion lead to one scoped child and independent task review',async()=>{
   const f=await fixture({promote:false});assert.deepEqual((await f.policy()).renderFollowups,[]);assert.equal((await f.dispatch(f.job.id,409)).code,'COORDINATION_RENDER_NOT_READY');const promoted=await f.promoteMedia();
   const snapshot=await f.policy();assert.equal(snapshot.renderFollowups.length,1);const candidate=snapshot.renderFollowups[0];assert.equal(candidate.executionJobId,f.job.id);assert.equal(candidate.artifactId,promoted.artifact.id);
   const follow=(await f.dispatch(f.job.id)).result;assert.notEqual(follow.childRunId,f.initial.childRunId);assert.equal(follow.policy.runsStarted,2);assert.equal((await f.dispatch(f.job.id)).result.childRunId,follow.childRunId);assert.equal((await f.dispatch()).result.childRunId,f.initial.childRunId);assert.deepEqual((await f.policy()).renderFollowups,[]);
   const runRow=(await query('SELECT prompt,capabilities,max_attempts FROM agent_runs WHERE id=$1',[follow.childRunId])).rows[0];assert.equal(runRow.max_attempts,1);assert.deepEqual(runRow.capabilities,['studio.read','studio.write','tasks.write']);assert(runRow.prompt.includes(promoted.artifact.id));assert(runRow.prompt.includes('do not register a duplicate'));
   const lease=await f.call('agent/runs/claim','POST',{workerId:'follow-up-comp',claimId:randomUUID()},'comp');assert.equal(lease.run.id,follow.childRunId);
   await f.tool(lease,'studio_get',{projectId:f.project.id,workItemId:f.work.id});await f.tool(lease,'studio_get',{projectId:f.project.id,artifactId:promoted.artifact.id});await f.tool(lease,'studio_execution_get',{jobId:f.job.id});
   assert.equal((await f.tool(lease,'tasks_create',{title:'Unrelated duplicate'},403)).code,'COORDINATION_FOLLOWUP_SCOPE');
   await f.tool(lease,'studio_artifact_register',{projectId:f.project.id,revision:(await f.detail()).project.revision,workItemId:f.work.id,name:'Duplicate',url:'https://example.invalid/duplicate.exr',sha256:'a'.repeat(64),frameStart:1,frameEnd:2,width:128,height:128,fpsNumerator:24,fpsDenominator:1,format:'exr',colorSpace:'Linear Rec.709',notes:''},403);
   const work=(await f.detail()).workItems.find((w:any)=>w.id===f.work.id),claimed=(await f.tool(lease,'tasks_claim',{taskId:work.taskId,revision:work.revision})).result;const submitted=(await f.tool(lease,'tasks_submit',{taskId:work.taskId,revision:claimed.revision,summary:`Verified render ${f.job.id}; existing artifact ${promoted.artifact.id} awaits independent human QC.`})).result;assert.equal(submitted.status,'review');assert.equal(submitted.approvedBy,null);
   const completion={clientId:randomUUID(),leaseToken:lease.leaseToken,result:'Existing promoted render submitted for independent human review.'};await f.call(`agent/runs/${lease.run.id}/complete`,'POST',completion,'comp');await query("UPDATE studio_coordination_policies SET status='paused' WHERE company_id=$1 AND project_id=$2",[f.company,f.project.id]);assert.equal((await f.call(`agent/runs/${lease.run.id}/complete`,'POST',completion,'comp')).replayed,true);
   assert.equal(Number((await query('SELECT count(*) FROM studio_artifacts WHERE company_id=$1',[f.company])).rows[0].count),1);assert.equal(Number((await query('SELECT count(*) FROM studio_execution_jobs WHERE company_id=$1',[f.company])).rows[0].count),1);assert.equal(Number((await query('SELECT count(*) FROM studio_coordination_followups WHERE company_id=$1',[f.company])).rows[0].count),1);
  });
  await t.test('failed source, wrong provenance, incomplete verification and stale project cannot create a follow-up',async()=>{
   const f=await fixture();await query("UPDATE agent_runs SET status='failed' WHERE id=$1",[f.child.run.id]);await f.dispatch(f.job.id,409);await query("UPDATE agent_runs SET status='succeeded' WHERE id=$1",[f.child.run.id]);
   await query('UPDATE studio_execution_jobs SET requested_run_id=$2 WHERE id=$1',[f.job.id,f.parent.run.id]);await f.dispatch(f.job.id,409);await query('UPDATE studio_execution_jobs SET requested_run_id=$2 WHERE id=$1',[f.job.id,f.child.run.id]);
   const file=(await query("SELECT f.id FROM studio_media_files f WHERE f.company_id=$1 AND f.kind='scene'",[f.company])).rows[0],verification=(await query('DELETE FROM studio_media_verifications WHERE company_id=$1 AND file_id=$2 RETURNING *',[f.company,file.id])).rows[0];assert.equal((await f.dispatch(f.job.id,409)).code,'COORDINATION_MEDIA_UNVERIFIED');await query('INSERT INTO studio_media_verifications(company_id,file_id,etag,sha256,bytes) VALUES($1,$2,$3,$4,$5)',[f.company,file.id,verification.etag,verification.sha256,verification.bytes]);
   await f.dispatch(randomUUID(),409);await f.dispatch(f.job.id,409,{projectRevision:1});assert.equal((await f.policy()).policy.runsStarted,1);assert.equal(Number((await query('SELECT count(*) FROM studio_coordination_followups WHERE company_id=$1',[f.company])).rows[0].count),0);
  });
  await t.test('budget, pause and plugin changes reject before a new run; failed continuation never repeats',async()=>{
   const exhausted=await fixture({budget:1});assert.equal((await exhausted.dispatch(exhausted.job.id,409)).code,'COORDINATION_RUN_BUDGET');
   const f=await fixture();await query('UPDATE plugin_installations SET revision=revision+1 WHERE company_id=$1 AND agent_id=$2',[f.company,f.agents.comp.id]);await f.dispatch(f.job.id,409);await query('UPDATE plugin_installations SET revision=revision-1 WHERE company_id=$1 AND agent_id=$2',[f.company,f.agents.comp.id]);
   const dispatched=(await f.dispatch(f.job.id)).result,lease=await f.call('agent/runs/claim','POST',{workerId:'follow-up-comp',claimId:randomUUID()},'comp');assert.equal(lease.run.id,dispatched.childRunId);await f.call(`agent/runs/${lease.run.id}/fail`,'POST',{clientId:randomUUID(),leaseToken:lease.leaseToken,error:'Synthetic uncertain follow-up result.'},'comp');assert.equal((await f.dispatch(f.job.id)).result.childRunId,lease.run.id);assert.equal((await f.policy()).policy.runsStarted,2);assert.equal((await f.call('agent/runs/claim','POST',{workerId:'follow-up-comp',claimId:randomUUID()},'comp')).run,null);
   await query("UPDATE studio_coordination_policies SET status='paused' WHERE company_id=$1 AND project_id=$2",[f.company,f.project.id]);await f.dispatch(f.job.id,409);
  });
  await t.test('a newer media version invalidates queued continuation and submission cannot drift from its exact promoted artifact',async()=>{
   const f=await fixture(),follow=(await f.dispatch(f.job.id)).result,lease=await f.call('agent/runs/claim','POST',{workerId:'follow-up-comp',claimId:randomUUID()},'comp');assert.equal(lease.run.id,follow.childRunId);
   const artifact=(await query('SELECT * FROM studio_artifacts WHERE company_id=$1 AND id=$2',[f.company,f.promoted!.artifact.id])).rows[0];await query('INSERT INTO studio_artifacts(company_id,project_id,work_item_id,name,version,url,sha256,metadata,produced_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[f.company,f.project.id,f.work.id,'Superseding fixture reference',2,artifact.url,artifact.sha256,JSON.stringify(artifact.metadata),f.owner]);
   assert.equal((await f.tool(lease,'tasks_claim',{taskId:f.work.taskId,revision:2},409)).code,'COORDINATION_AUTHORITY_ENDED');assert.equal((await query('SELECT status FROM tasks WHERE id=$1',[f.work.taskId])).rows[0].status,'doing');
  });
  await t.test('a queued continuation shares the original concurrency limit and a foreign job cannot be adopted',async()=>{
   const f=await fixture({budget:3,twoShots:true}),other=await fixture();await other.dispatch(f.job.id,409);await f.dispatch(f.job.id);const second=(await f.detail()).workItems.find((w:any)=>w.stage==='compositing'&&w.id!==f.work.id);assert(second);assert.equal((await f.dispatch(undefined,409,{workItemId:second.id})).code,'COORDINATION_CONCURRENCY');assert.equal((await f.policy()).policy.runsStarted,2);
  });
  await t.test('isolated PostgreSQL concurrent parent runs create one continuation and consume one shared reservation',{skip:emulate||!connection||!['127.0.0.1','localhost','[::1]'].includes(new URL(connection).hostname)},async()=>{
   const f=await fixture(),secondRun=(await f.call(`companies/${f.company}/conversations/commons/runs`,'POST',{clientId:randomUUID(),agentId:f.agents.coordinator.id,prompt:'Second synthetic parent for the post-render race.'},'owner',201)).run,leaseToken=randomUUID()+randomUUID();
   // Seed a second valid parent lease to prove that policy locking, not the
   // normal one-worker-per-agent behavior, protects this shared allowance.
   await query("UPDATE agent_runs SET status='running',attempts=1,worker_id='follow-up-race',lease_token_hash=$2,lease_expires_at=clock_timestamp()+interval '1 minute',started_at=clock_timestamp() WHERE id=$1",[secondRun.id,hashToken(leaseToken)]);
   const revision=(await f.detail()).project.revision,policyRevision=(await f.policy()).policy.revision;
   const results=await Promise.all([f.parent,{run:secondRun,leaseToken}].map(lease=>f.call('agent/tools/studio_work_dispatch','POST',{runId:lease.run.id,leaseToken:lease.leaseToken,requestId:randomUUID(),arguments:{projectId:f.project.id,workItemId:f.work.id,executionJobId:f.job.id,projectRevision:revision,policyRevision}},'coordinator')));
   assert.equal(results[0].result.childRunId,results[1].result.childRunId);assert.equal(results.filter(result=>result.result.replayed===false).length,1);assert.equal((await f.policy()).policy.runsStarted,2);assert.equal(Number((await query('SELECT count(*) FROM studio_coordination_followups WHERE company_id=$1',[f.company])).rows[0].count),1);
  });
 }finally{for(const company of companies)await query('DELETE FROM companies WHERE id=$1',[company]);for(const user of users)await query('DELETE FROM users WHERE id=$1',[user]);await database().end();delete (globalThis as any).coatriaPool;await stop?.();for(const[key,value]of Object.entries(before))if(value===undefined)delete process.env[key];else process.env[key]=value;}
});
