'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Activity, ArrowLeft, ArrowRight, Bot, BriefcaseBusiness, Building2, CheckSquare, ChevronDown, CircleHelp, Compass, DoorOpen, LayoutDashboard, LockKeyhole, LogOut, Menu, MessageSquare, Plus, Search, Server, Settings2, Users, X} from 'lucide-react';
import {api,type Company,type Session,type User,type Workspace} from '@/lib/client';
import {Avatar,Badge,Brand,Empty,Loading,Modal} from '@/components/ui';
import {Auth,CompanySetup,JoinCompany,DeploymentPending} from '@/components/Auth';
import {OfficeView,RoomsView,ChatView,PeopleView,ActivityView,LayoutView,ProfileView} from '@/components/Workplace';
import {TasksView,VaultView} from '@/components/Work';
import {AgentsView,InfrastructureView,OpportunitiesView,HiringView} from '@/components/Operations';

export type WorkspaceProps={user:User;company:Company;workspace:Workspace;refresh:()=>Promise<void>;refreshMemberships:()=>Promise<void>;notify:(message:string)=>void};
const sections=[{label:'YOUR WORKPLACE',items:[['office','The office',LayoutDashboard],['rooms','Rooms',DoorOpen],['chat','Conversations',MessageSquare],['tasks','Work board',CheckSquare],['people','People',Users]]},{label:'BUILD TOGETHER',items:[['agents','Your agents',Bot],['infrastructure','Infrastructure',Server],['hiring','Hiring',BriefcaseBusiness],['activity','Activity',Activity]]},{label:'YOUR OWN CHAPTER',items:[['vault','My skill vault',LockKeyhole],['opportunities','Opportunities',Compass]]}] as const;
const titles:Record<string,string>={office:'The office',rooms:'Rooms',chat:'Conversations',tasks:'Work board',people:'People',agents:'Your agents',infrastructure:'Infrastructure',hiring:'Hiring',activity:'Activity',vault:'My skill vault',opportunities:'Opportunities',layout:'Space editor',profile:'Your profile',create:'Create a workplace',join:'Join a workplace'};
export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[sessionError,setSessionError]=useState(''),[companyId,setCompanyId]=useState(''),[workspace,setWorkspace]=useState<Workspace|null>(null),[workspaceError,setWorkspaceError]=useState(''),[view,setView]=useState('office'),[mobile,setMobile]=useState(false),[toast,setToast]=useState(''),[switcher,setSwitcher]=useState(false),[invite,setInvite]=useState(''),[roomId,setRoomId]=useState<string|null>(null),[chatRoomId,setChatRoomId]=useState<string|null>(null),[status,setStatus]=useState('available'),[search,setSearch]=useState(false);
 const position=useRef({x:0,z:3}),generation=useRef(0),heartbeatState=useRef({roomId,status}),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);heartbeatState.current={roomId,status};
 const sessionCompany=session?.companies.find(c=>c.id===companyId)||null;
 const company=sessionCompany?{...sessionCompany,role:workspace?.company.id===companyId?workspace.company.role:sessionCompany.role}:null;
 const notify=useCallback((message:string)=>{setToast(message);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4500);},[]);
 const navigate=useCallback((next:string)=>{setView(next);setMobile(false);window.history.replaceState(null,'','#'+next);window.scrollTo({top:0,behavior:'auto'});},[]);
 const loadSession=useCallback(async()=>{setSessionError('');try{const s=await api<Session>('/api/session');setSession(s);setCompanyId(id=>s.companies.some(c=>c.id===id)?id:s.companies[0]?.id||'');}catch(e){setSessionError((e as Error).message);}},[]);
 useEffect(()=>{const token=new URLSearchParams(location.search).get('invite');if(token){setInvite(token);setView('join');}else{const requested=location.hash.slice(1);if(titles[requested])setView(requested);}void loadSession();const hash=()=>{const v=location.hash.slice(1);if(titles[v])setView(v);};window.addEventListener('hashchange',hash);return()=>window.removeEventListener('hashchange',hash);},[loadSession]);
 useEffect(()=>{const shortcut=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(v=>!v);}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut);},[]);
 const refresh=useCallback(async()=>{if(!companyId)return;const g=generation.current;try{const w=await api<Workspace>(`/api/companies/${companyId}/workspace`);if(g===generation.current){setWorkspace(w);setWorkspaceError('');}}catch(e){if(g===generation.current){setWorkspaceError((e as Error).message);if([401,403,404].includes((e as Error&{status:number}).status)){setWorkspace(null);void loadSession();}}}},[companyId,loadSession]);
 useEffect(()=>{generation.current++;setWorkspace(null);setWorkspaceError('');setRoomId(null);setChatRoomId(null);position.current={x:0,z:3};if(companyId)void refresh();},[companyId,refresh]);
 useEffect(()=>{if(!companyId||!session?.user)return;const poll=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},5000);const beat=async()=>{if(document.visibilityState!=='visible')return;try{await api(`/api/companies/${companyId}/presence`,'POST',{...position.current,...heartbeatState.current});}catch{/* Workspace refresh presents connection errors. */}};void beat();const pulse=setInterval(beat,15000);const visible=()=>{if(document.visibilityState==='visible'){void refresh();void beat();}};document.addEventListener('visibilitychange',visible);return()=>{clearInterval(poll);clearInterval(pulse);document.removeEventListener('visibilitychange',visible);};},[companyId,session?.user,refresh]);
 async function accepted(c:Company){await loadSession();setCompanyId(c.id);setInvite('');window.history.replaceState(null,'',location.pathname+'#office');setView('office');notify('Welcome in. Your workplace is ready.');}
 function authenticated(s:Session){setSession(s);setCompanyId(s.companies[0]?.id||'');if(invite)navigate('join');else if(!s.companies.length)navigate('create');else navigate('office');}
 async function updatePresence(next:{roomId?:string|null;status?:string;x?:number;z?:number}){if(next.roomId!==undefined)setRoomId(next.roomId);if(next.status)setStatus(next.status);if(next.x!==undefined&&next.z!==undefined)position.current={x:next.x,z:next.z};if(companyId)try{await api(`/api/companies/${companyId}/presence`,'POST',{...position.current,...heartbeatState.current,...next});await refresh();}catch(e){notify((e as Error).message);}}
 if(!session)return <div className="boot"><Brand/>{sessionError?<><p className="error-message" role="alert">{sessionError}</p><button className="button primary" onClick={loadSession}>Try again</button></>:<Loading label="Opening Coatria"/>}</div>;
 if(session.configured===false)return <DeploymentPending onRefresh={loadSession}/>;
 if(!session.user&&view!=='opportunities')return <Auth onSession={authenticated} onExplore={()=>navigate('opportunities')} invite={invite}/>;
 if(!session.user)return <div className="public-page"><header><Brand/><button className="button primary" onClick={()=>navigate('office')}>Sign in <ArrowRight size={16}/></button></header><main id="main"><OpportunitiesView user={null} companies={[]} notify={notify} onSignIn={()=>navigate('office')}/></main></div>;
 const user=session.user,admin=['owner','admin'].includes(company?.role||'');
 const props=company&&workspace?{user,company,workspace,refresh,refreshMemberships:loadSession,notify}:null;
 return <div className="app-shell"><aside className="workspace-rail"><button className="rail-brand" aria-label="Coatria office" onClick={()=>navigate('office')}><Brand small/></button><div className="company-tiles">{session.companies.map(c=><button key={c.id} title={c.name} aria-label={'Switch to '+c.name} aria-pressed={c.id===companyId} className={'workspace-tile '+(c.id===companyId?'selected':'')} onClick={()=>{setCompanyId(c.id);navigate('office');}}>{c.name.slice(0,2).toUpperCase()}</button>)}<button className="workspace-tile add" title="Create or join a workplace" aria-label="Create or join a workplace" onClick={()=>setSwitcher(true)}><Plus size={20}/></button></div><button className="rail-profile" aria-label="Your profile" onClick={()=>navigate('profile')}><Avatar name={user.name} color={user.avatarColor} size="small"/></button></aside>
 {mobile&&<button className="sidebar-scrim" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
 <aside className={'sidebar '+(mobile?'mobile-open':'')}><button className="company-switch" onClick={()=>setSwitcher(true)}><span className="company-logo">{company?.name[0]||'C'}</span><span><strong>{company?.name||'Your workplaces'}</strong><small>{company?company.role+' workspace':'Find your people'}</small></span><ChevronDown size={15}/></button><button className="search-trigger" onClick={()=>setSearch(true)}><Search size={15}/><span>Find your way</span><kbd>⌘ K</kbd></button><nav aria-label="Main navigation">{sections.map(s=><div className="nav-section" key={s.label}><span>{s.label}</span>{s.items.map(([id,label,Icon])=><button key={id} className={'nav-item '+(view===id?'active':'')} onClick={()=>navigate(id)}><Icon size={17}/>{label}{id==='tasks'&&!!workspace?.tasks.filter(t=>t.status==='review').length&&<span className="nav-count">{workspace.tasks.filter(t=>t.status==='review').length}</span>}{id==='vault'&&<span className="private-dot" title="Private to you"/>}</button>)}</div>)}</nav><div className="sidebar-bottom"><div className="row"><span className={'status-dot '+(workspaceError?'warning':'')}/><span>{workspaceError?'Reconnecting to your workplace':company?'Your shared workplace':'Make room for what’s next'}</span></div><p>Good work happens together.</p></div></aside>
 <div className="main-shell"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(v=>!v)}><Menu size={20}/></button><div className="breadcrumbs"><span>{company?.name||'Your Coatria'}</span><i>/</i><strong>{titles[view]||'The office'}</strong></div><div className="topbar-right">{company&&<span className="live-label"><span className="status-dot"/>{workspace?.presence.length||0} here now</span>}<button className="icon-button" aria-label="Search navigation" onClick={()=>setSearch(true)}><Search size={18}/></button><button className="avatar-button" aria-label="Your profile" onClick={()=>navigate('profile')}><Avatar name={user.name} color={user.avatarColor} size="small"/></button></div></header>
 <main id="main" className={'main-content view-'+view}>{workspaceError&&<div className="connection-error" role="status">{workspaceError} <button onClick={refresh}>Reconnect</button></div>}
 {view==='create'?<CompanySetup onCreated={accepted} onBack={()=>navigate(company?'office':'opportunities')}/>:view==='join'?<JoinCompany initialToken={invite} onJoined={accepted}/>:view==='profile'?<ProfileView user={user} onUpdated={loadSession} notify={notify} onLogout={async()=>{try{await api('/api/auth/logout','POST',{});setSession({user:null,companies:[]});setWorkspace(null);setCompanyId('');navigate('office');}catch(e){notify((e as Error).message);}}}/>:view==='vault'?<VaultView notify={notify}/>:view==='opportunities'?<OpportunitiesView user={user} companies={session.companies} notify={notify}/>:!company?<Empty icon={Building2} title="Find your people. Make a place." description="Create a workplace for your company, or join one with an invitation." action={<div className="row"><button className="button primary" onClick={()=>navigate('create')}><Plus size={16}/> Create a workplace</button><button className="button secondary" onClick={()=>navigate('join')}>Join with an invitation</button></div>}/>:!props?<Loading/>:view==='office'?<OfficeView {...props} roomId={roomId} status={status} onStatus={s=>void updatePresence({status:s})} onMove={p=>void updatePresence(p)} onRoom={id=>{setRoomId(id);void updatePresence({roomId:id});navigate('rooms');}} navigate={navigate}/>:view==='rooms'?<RoomsView {...props} roomId={roomId} onRoom={id=>void updatePresence({roomId:id})}/>:view==='chat'?<ChatView {...props} roomId={chatRoomId} onRoom={id=>setChatRoomId(id)}/>:view==='tasks'?<TasksView {...props}/>:view==='people'?<PeopleView {...props}/>:view==='agents'?<AgentsView {...props}/>:view==='infrastructure'?<InfrastructureView {...props}/>:view==='hiring'?<HiringView {...props}/>:view==='activity'?<ActivityView {...props}/>:view==='layout'?(admin?<LayoutView {...props} onDone={()=>navigate('office')}/>:<Empty icon={LockKeyhole} title="The space editor is for administrators" description="Ask your company owner for access to change this floor."/>):<Empty icon={CircleHelp} title="Let’s find your way back" description="This area is not available." action={<button className="button primary" onClick={()=>navigate('office')}>Back to the office</button>}/>}
 </main><footer className="app-footer"><span><Brand small/> A place to work, together.</span><button onClick={()=>navigate('vault')}><LockKeyhole size={12}/> Your skills stay yours <ArrowRight size={12}/></button></footer></div>
 {switcher&&<Modal title="Your workplaces" description="One personal identity. A place in every company you belong to." onClose={()=>setSwitcher(false)}><div className="stack">{session.companies.map(c=><button className="company-option" key={c.id} onClick={()=>{setCompanyId(c.id);setSwitcher(false);navigate('office');}}><span className="company-logo">{c.name[0]}</span><span><strong>{c.name}</strong><small>{c.role}</small></span><ArrowRight size={17}/></button>)}<div className="grid two"><button className="choice" onClick={()=>{setSwitcher(false);navigate('create');}}><Plus size={22}/><strong>Create a workplace</strong><p>Make room for your team.</p></button><button className="choice" onClick={()=>{setSwitcher(false);navigate('join');}}><Users size={22}/><strong>Join a workplace</strong><p>Use your invitation link.</p></button></div></div></Modal>}
 {search&&<SearchModal onClose={()=>setSearch(false)} onNavigate={v=>{navigate(v);setSearch(false);}}/>}
 {toast&&<div className="toast" role="status"><span>{toast}</span><button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
 </div>;
}
function SearchModal({onClose,onNavigate}:{onClose:()=>void;onNavigate:(v:string)=>void}){const [query,setQuery]=useState('');return <Modal title="Find your way" onClose={onClose}><input className="search-input" placeholder="Search Coatria navigation…" aria-label="Search navigation" autoFocus value={query} onChange={e=>setQuery(e.target.value)}/><div className="search-results">{Object.entries(titles).filter(([,name])=>name.toLowerCase().includes(query.toLowerCase())).map(([id,name])=><button key={id} className="list-row" onClick={()=>onNavigate(id)}><span>{name}</span><ArrowRight size={16}/></button>)}</div></Modal>;}
