'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Activity, ArrowLeft, ArrowRight, Bot, BriefcaseBusiness, Building2, CheckSquare, ChevronDown, CircleHelp, FlaskConical, Compass, DoorOpen, LayoutDashboard, LockKeyhole, LogOut, Menu, MessageSquare, Plus, Search, Server, Settings2, Users, X} from 'lucide-react';
import {api,setClientIdentity,type Company,type Session,type User,type Workspace,type Presence} from '@/lib/client';
import {startPolling,latestWriter} from '@/lib/polling';
import {mergePresence} from '@/lib/presence-sync';
import {Avatar,Badge,Brand,Empty,Loading,Modal} from '@/components/ui';
import {Auth,CompanySetup,JoinCompany,DeploymentPending} from '@/components/Auth';
import {OfficeView,RoomsView,ChatView,PeopleView,ActivityView,LayoutView,ProfileView} from '@/components/Workplace';
import {TasksView,VaultView} from '@/components/Work';
import TesterView from '@/components/TesterView';
import {AgentsView,InfrastructureView,OpportunitiesView,HiringView} from '@/components/Operations';

export type WorkspaceProps={user:User;company:Company;workspace:Workspace;refresh:()=>Promise<void>;refreshMemberships:()=>Promise<void>;notify:(message:string)=>void};
const sections=[{label:'YOUR WORKPLACE',items:[['office','The office',LayoutDashboard],['rooms','Rooms',DoorOpen],['chat','Conversations',MessageSquare],['tasks','Work board',CheckSquare],['people','People',Users]]},{label:'COMPANY OPERATIONS',items:[['agents','Your agents',Bot],['infrastructure','Infrastructure',Server],['hiring','Hiring',BriefcaseBusiness],['activity','Activity',Activity],['tester','Test lab',FlaskConical]]},{label:'PERSONAL',items:[['vault','My skill vault',LockKeyhole],['opportunities','Opportunities',Compass]]}] as const;
const titles:Record<string,string>={office:'The office',rooms:'Rooms',chat:'Conversations',tasks:'Work board',people:'People',agents:'Your agents',infrastructure:'Infrastructure',hiring:'Hiring',activity:'Activity',vault:'My skill vault',opportunities:'Opportunities',layout:'Space editor',tester:'Test lab',profile:'Your profile',create:'Create a workplace',join:'Join a workplace'};
export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[sessionError,setSessionError]=useState(''),[companyId,setCompanyId]=useState(''),[workspaceState,setWorkspace]=useState<Workspace|null>(null),[workspaceError,setWorkspaceError]=useState(''),[view,setView]=useState('office'),[mobile,setMobile]=useState(false),[toast,setToast]=useState(''),[switcher,setSwitcher]=useState(false),[invite,setInvite]=useState(''),[roomId,setRoomId]=useState<string|null>(null),[chatRoomId,setChatRoomId]=useState<string|null>(null),[status,setStatus]=useState('available'),[search,setSearch]=useState(false);
 const workspace=workspaceState?.company.id===companyId?workspaceState:null;
 const activeCompany=useRef(companyId);activeCompany.current=companyId;const currentView=useRef(view);currentView.current=view;
 const activeIdentity=useRef<string|null>(null),sessionEpoch=useRef(0);
 const presenceSequence=useRef(0),latestPresenceSequence=useRef(0),refreshFlight=useRef<{key:string;promise:Promise<void>}|null>(null),presenceWriter=useRef<ReturnType<typeof latestWriter<{roomId:string|null;status:string;x:number;z:number}>>|null>(null);
 const position=useRef({x:0,z:3}),generation=useRef(0),heartbeatState=useRef({roomId,status}),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);heartbeatState.current={roomId,status};
 const sessionCompany=session?.companies.find(c=>c.id===companyId)||null;
 const company=sessionCompany?{...sessionCompany,role:workspace?.company.id===companyId?workspace.company.role:sessionCompany.role}:null;
 const notify=useCallback((message:string)=>{setToast(message);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4500);},[]);
 const navigate=useCallback((next:string,skipGuard=false)=>{if(!titles[next]||(!skipGuard&&next!==currentView.current&&!document.dispatchEvent(new Event('coatria:before-navigate',{cancelable:true}))))return;setView(next);setMobile(false);if(location.hash!=='#'+next)window.history.pushState(null,'','#'+next);window.scrollTo({top:0,behavior:'auto'});requestAnimationFrame(()=>document.getElementById('main')?.focus({preventScroll:true}));},[]);
 const loadSession=useCallback(async()=>{const epoch=++sessionEpoch.current;setSessionError('');try{const s=await api<Session>('/api/session');if(epoch!==sessionEpoch.current)return;const identity=s.user?.id||null;if(identity!==activeIdentity.current){activeIdentity.current=identity;generation.current++;setWorkspace(null);setMobile(false);setSwitcher(false);setSearch(false);setToast('');}setClientIdentity(identity);setSession(s);setCompanyId(id=>s.companies.some(c=>c.id===id)?id:s.companies[0]?.id||'');}catch(e){if(epoch===sessionEpoch.current)setSessionError((e as Error).message);}},[]);
 useEffect(()=>{const token=new URLSearchParams(location.search).get('invite');if(token){setInvite(token);setView('join');}else{const requested=location.hash.slice(1);if(titles[requested])setView(requested);}void loadSession();const hash=()=>{const v=location.hash.slice(1);if(v==='main'){window.history.replaceState(null,'','#'+currentView.current);return;}if(v!==currentView.current&&!document.dispatchEvent(new Event('coatria:before-navigate',{cancelable:true}))){window.history.pushState(null,'','#'+currentView.current);return;}setView(titles[v]?v:'office');setMobile(false);};window.addEventListener('hashchange',hash);return()=>window.removeEventListener('hashchange',hash);},[loadSession]);
 useEffect(()=>{const link=document.querySelector<HTMLAnchorElement>('.skip-link');const skip=(event:MouseEvent)=>{const main=document.getElementById('main');if(!main)return;event.preventDefault();if(!main.hasAttribute('tabindex'))main.setAttribute('tabindex','-1');main.focus({preventScroll:true});main.scrollIntoView({block:'start'});};link?.addEventListener('click',skip);return()=>link?.removeEventListener('click',skip);},[]);
 useEffect(()=>{const shortcut=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(v=>!v);}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut);},[]);
 useEffect(()=>{const reconcile=()=>{if(document.visibilityState==='visible')void loadSession();};window.addEventListener('focus',reconcile);window.addEventListener('coatria:session-changed',reconcile);document.addEventListener('visibilitychange',reconcile);const timer=setInterval(reconcile,15000);return()=>{window.removeEventListener('focus',reconcile);window.removeEventListener('coatria:session-changed',reconcile);document.removeEventListener('visibilitychange',reconcile);clearInterval(timer);};},[loadSession]);
 useEffect(()=>{const wide=window.matchMedia('(min-width:821px)');const close=()=>{if(wide.matches)setMobile(false);};wide.addEventListener('change',close);return()=>wide.removeEventListener('change',close);},[]);
 useEffect(()=>{document.title=(titles[view]||'Workplace')+' · Coatria';},[view]);
 useEffect(()=>{if(!mobile)return;const trigger=document.activeElement as HTMLElement|null;const sidebar=document.getElementById('workspace-navigation');sidebar?.querySelector<HTMLElement>('button')?.focus();const keys=(e:KeyboardEvent)=>{if(document.querySelector('dialog[open]'))return;if(e.key==='Escape'){e.preventDefault();setMobile(false);return;}if(e.key==='Tab'){const items=Array.from(sidebar?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled)')||[]);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};window.addEventListener('keydown',keys);return()=>{window.removeEventListener('keydown',keys);if(trigger?.isConnected)trigger.focus();};},[mobile]);
 useEffect(()=>()=>{if(toastTimer.current)clearTimeout(toastTimer.current);},[]);
 const refresh=useCallback(async(signal?:AbortSignal)=>{if(!companyId||companyId!==activeCompany.current)return;const g=generation.current,key=companyId+':'+g;if(refreshFlight.current?.key===key)return refreshFlight.current.promise;const ticket=++presenceSequence.current;const promise=(async()=>{try{const w=await api<Workspace>(`/api/companies/${companyId}/workspace`, 'GET',undefined,{signal});if(g===generation.current&&companyId===activeCompany.current){const newest=ticket>=latestPresenceSequence.current;if(newest)latestPresenceSequence.current=ticket;setWorkspace(previous=>({...w,presence:previous?.company.id===companyId?mergePresence(previous.presence,w.presence,newest):w.presence}));setWorkspaceError('');}}catch(e){if(signal?.aborted)return;if(g===generation.current&&companyId===activeCompany.current){setWorkspaceError((e as Error).message);if([401,403,404].includes((e as Error&{status:number}).status)){generation.current++;setWorkspace(null);void loadSession();}}if(signal)throw e;}})();refreshFlight.current={key,promise};try{await promise;}finally{if(refreshFlight.current?.promise===promise)refreshFlight.current=null;}},[companyId,loadSession]);
 useEffect(()=>{generation.current++;setWorkspace(null);setWorkspaceError('');setRoomId(null);setChatRoomId(null);position.current={x:0,z:3};if(companyId)void refresh();},[companyId,refresh]);

 useEffect(()=>{if(!companyId||!session?.user)return;const g=generation.current,visible=()=>document.visibilityState==='visible';
   const receive=(presence:Presence[],ticket:number)=>{if(!Array.isArray(presence))return;if(g!==generation.current||companyId!==activeCompany.current)return;const newest=ticket>=latestPresenceSequence.current;if(newest)latestPresenceSequence.current=ticket;setWorkspace(previous=>previous?.company.id===companyId?{...previous,presence:mergePresence(previous.presence,presence,newest)}:previous);};
   const failed=(e:unknown)=>{if(g!==generation.current||companyId!==activeCompany.current)return;setWorkspaceError((e as Error).message);if([401,403,404].includes((e as Error&{status:number}).status)){generation.current++;setWorkspace(null);void loadSession();}};
   const writer=latestWriter<{roomId:string|null;status:string;x:number;z:number}>(async(payload,signal)=>{const ticket=++presenceSequence.current;const response=await api<{presence:Presence[]}>(`/api/companies/${companyId}/presence`,'POST',payload,{signal});receive(response.presence,ticket);},failed);
   presenceWriter.current=writer;
   const stopWorkspace=startPolling(signal=>refresh(signal),{intervalMs:5000,immediate:false,active:visible});
   const stopPresence=startPolling(async signal=>{const ticket=++presenceSequence.current;const response=await api<{presence:Presence[]}>(`/api/companies/${companyId}/presence`,'GET',undefined,{signal});receive(response.presence,ticket);},{intervalMs:2000,immediate:false,active:()=>visible()&&['office','people','rooms'].includes(currentView.current),onError:failed});
   const beat=()=>{if(visible())writer.write({...position.current,...heartbeatState.current});};beat();const pulse=setInterval(beat,15000);
   const wake=()=>{if(visible()){void refresh();beat();}};document.addEventListener('visibilitychange',wake);
   return()=>{stopWorkspace();stopPresence();clearInterval(pulse);writer.close();if(presenceWriter.current===writer)presenceWriter.current=null;document.removeEventListener('visibilitychange',wake);};
 },[companyId,session?.user?.id,refresh,loadSession]);

 function switchCompany(id:string){if(!document.dispatchEvent(new Event('coatria:before-navigate',{cancelable:true})))return;setCompanyId(id);setSwitcher(false);navigate('office',true);}
 async function accepted(c:Company){await loadSession();setCompanyId(c.id);setInvite('');window.history.replaceState(null,'',location.pathname+'#office');setView('office');notify('Welcome in. Your workplace is ready.');}
 function authenticated(s:Session){sessionEpoch.current++;generation.current++;activeIdentity.current=s.user?.id||null;setClientIdentity(activeIdentity.current);setWorkspace(null);setSession(s);setCompanyId(s.companies[0]?.id||'');if(invite)navigate('join');else if(!s.companies.length)navigate('create');else navigate('office');}
 function updatePresence(next:{roomId?:string|null;status?:string;x?:number;z?:number}){if(next.roomId!==undefined){setRoomId(next.roomId);heartbeatState.current.roomId=next.roomId;}if(next.status){setStatus(next.status);heartbeatState.current.status=next.status;}if(next.x!==undefined&&next.z!==undefined)position.current={x:next.x,z:next.z};presenceWriter.current?.write({...position.current,...heartbeatState.current});}
 if(!session)return <div className="boot"><Brand/>{sessionError?<><p className="error-message" role="alert">{sessionError}</p><button className="button primary" onClick={loadSession}>Try again</button></>:<Loading label="Opening Coatria"/>}</div>;
 if(session.configured===false)return <DeploymentPending onRefresh={loadSession}/>;
 if(!session.user&&view!=='opportunities')return <Auth onSession={authenticated} onExplore={()=>navigate('opportunities')} invite={invite}/>;
 if(!session.user)return <div className="public-page"><header><Brand/><button className="button primary" onClick={()=>navigate('office')}>Sign in <ArrowRight size={16}/></button></header><main id="main"><OpportunitiesView user={null} companies={[]} notify={notify} onSignIn={()=>navigate('office')}/></main></div>;
 const user=session.user,admin=['owner','admin'].includes(company?.role||'');
 const props=company&&workspace?{user,company,workspace,refresh,refreshMemberships:loadSession,notify}:null;
 return <div className="app-shell" key={user.id}><aside aria-label="Workplaces" className="workspace-rail" inert={mobile||undefined}><button className="rail-brand" aria-label="Coatria office" onClick={()=>navigate('office')}><Brand small/></button><div className="company-tiles">{session.companies.map(c=><button key={c.id} title={c.name} aria-label={'Switch to '+c.name} aria-pressed={c.id===companyId} className={'workspace-tile '+(c.id===companyId?'selected':'')} onClick={()=>switchCompany(c.id)}>{c.name.slice(0,2).toUpperCase()}</button>)}<button className="workspace-tile add" title="Create or join a workplace" aria-label="Create or join a workplace" onClick={()=>setSwitcher(true)}><Plus size={20}/></button></div><button className="rail-profile" aria-label="Your profile" onClick={()=>navigate('profile')}><Avatar name={user.name} color={user.avatarColor} size="small"/></button></aside>
 {mobile&&<button className="sidebar-scrim" tabIndex={-1} aria-label="Close navigation overlay" onClick={()=>setMobile(false)}/>}
 <aside id="workspace-navigation" aria-label="Workplace navigation" className={'sidebar '+(mobile?'mobile-open':'')}><button className="company-switch" aria-haspopup="dialog" aria-expanded={switcher} onClick={()=>setSwitcher(true)}><span className="company-logo">{company?.name[0]||'C'}</span><span><strong>{company?.name||'Your workplaces'}</strong><small>{company?company.role+' workspace':'Find your people'}</small></span><ChevronDown size={15}/></button><button className="search-trigger" onClick={()=>setSearch(true)}><Search size={15}/><span>Find your way</span><kbd>Ctrl / ⌘ K</kbd></button><button className="icon-button sidebar-close" aria-label="Close navigation" onClick={()=>setMobile(false)}><X size={20}/></button><nav aria-label="Main navigation">{sections.map(s=><div className="nav-section" key={s.label}><span>{s.label}</span>{s.items.filter(([id])=>id!=='tester'||admin).map(([id,label,Icon])=><button key={id} aria-label={label} className={'nav-item '+(view===id?'active':'')} aria-current={view===id?'page':undefined} onClick={()=>navigate(id)}><Icon size={17}/>{label}{id==='tasks'&&!!workspace?.tasks.filter(t=>t.status==='review').length&&<span className="nav-count">{workspace.tasks.filter(t=>t.status==='review').length}</span>}{id==='vault'&&<span className="private-dot" title="Private to you"/>}</button>)}</div>)}</nav><div className="sidebar-bottom"><div className="row"><span className={'status-dot '+(workspaceError?'warning':'')}/><span>{workspaceError?'Reconnecting to your workplace':company?'Your shared workplace':'Make room for what’s next'}</span></div><p>Good work happens together.</p></div></aside>
 <div className="main-shell" inert={mobile||undefined}><header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" aria-controls="workspace-navigation" aria-expanded={mobile} onClick={()=>setMobile(v=>!v)}><Menu size={20}/></button><div className="breadcrumbs"><span>{['vault','profile','opportunities','create','join'].includes(view)?'Your Coatria':company?.name||'Your Coatria'}</span><i>/</i><strong>{titles[view]||'The office'}</strong></div><div className="topbar-right">{company&&<span className="live-label"><span className="status-dot"/>{workspace?.presence.length||0} here now</span>}<button className="icon-button" aria-label="Search navigation" onClick={()=>setSearch(true)}><Search size={18}/></button><button className="avatar-button" aria-label="Your profile" onClick={()=>navigate('profile')}><Avatar name={user.name} color={user.avatarColor} size="small"/></button></div></header>
 <main id="main" tabIndex={-1} aria-label={titles[view]||'Coatria'} className={'main-content view-'+view}>{workspaceError&&<div className="connection-error" role="status">{workspaceError} <button onClick={()=>void refresh()}>Reconnect</button></div>}
 {view==='create'?<CompanySetup onCreated={accepted} onBack={()=>navigate(company?'office':'opportunities')}/>:view==='join'?<JoinCompany initialToken={invite} onJoined={accepted}/>:view==='profile'?<ProfileView user={user} onUpdated={loadSession} notify={notify} onLogout={async()=>{try{await api('/api/auth/logout','POST',{});sessionEpoch.current++;generation.current++;activeIdentity.current=null;setMobile(false);setClientIdentity(null);setSession({user:null,companies:[]});setWorkspace(null);setCompanyId('');navigate('office');}catch(e){notify((e as Error).message);}}}/>:view==='vault'?<VaultView notify={notify}/>:view==='opportunities'?<OpportunitiesView user={user} companies={session.companies} notify={notify}/>:!company?<Empty icon={Building2} title="Find your people. Make a place." description="Create a workplace for your company, or join one with an invitation." action={<div className="row"><button className="button primary" onClick={()=>navigate('create')}><Plus size={16}/> Create a workplace</button><button className="button secondary" onClick={()=>navigate('join')}>Join with an invitation</button></div>}/>:!props?<Loading/>:view==='office'?<OfficeView {...props} roomId={roomId} status={status} onStatus={s=>void updatePresence({status:s})} onMove={p=>void updatePresence(p)} onRoom={id=>{setRoomId(id);void updatePresence({roomId:id});navigate('rooms');}} navigate={navigate}/>:view==='rooms'?<RoomsView {...props} roomId={roomId} onRoom={id=>void updatePresence({roomId:id})}/>:view==='chat'?<ChatView {...props} roomId={chatRoomId} onRoom={id=>setChatRoomId(id)}/>:view==='tasks'?<TasksView {...props}/>:view==='people'?<PeopleView {...props}/>:view==='agents'?<AgentsView {...props}/>:view==='infrastructure'?<InfrastructureView {...props}/>:view==='hiring'?<HiringView {...props}/>:view==='activity'?<ActivityView {...props}/>:view==='tester'?(admin?<TesterView {...props} onBack={()=>navigate('office')} onEdit={()=>navigate('layout')}/>:<Empty icon={LockKeyhole} title="The test lab is for administrators" description="Ask your company owner to open the test lab."/>):view==='layout'?(admin?<LayoutView {...props} onDone={()=>navigate('office')}/>:<Empty icon={LockKeyhole} title="The space editor is for administrators" description="Ask your company owner for access to change this floor."/>):<Empty icon={CircleHelp} title="Let’s find your way back" description="This area is not available." action={<button className="button primary" onClick={()=>navigate('office')}>Back to the office</button>}/>}
 </main><footer className="app-footer"><span><Brand small/> A place to work, together.</span><button onClick={()=>navigate('vault')}><LockKeyhole size={12}/> Your skills stay yours <ArrowRight size={12}/></button></footer></div>
 {switcher&&<Modal title="Your workplaces" description="One personal identity. A place in every company you belong to." onClose={()=>setSwitcher(false)}><div className="stack">{session.companies.map(c=><button className="company-option" key={c.id} onClick={()=>switchCompany(c.id)}><span className="company-logo">{c.name[0]}</span><span><strong>{c.name}</strong><small>{c.role}</small></span><ArrowRight size={17}/></button>)}<div className="grid two"><button className="choice" onClick={()=>{setSwitcher(false);navigate('create');}}><Plus size={22}/><strong>Create a workplace</strong><p>Make room for your team.</p></button><button className="choice" onClick={()=>{setSwitcher(false);navigate('join');}}><Users size={22}/><strong>Join a workplace</strong><p>Use your invitation link.</p></button></div></div></Modal>}
 {search&&<SearchModal admin={admin} hasCompany={!!company} onClose={()=>setSearch(false)} onNavigate={v=>{navigate(v);setSearch(false);}}/>}
 {toast&&<div className="toast" role="status"><span>{toast}</span><button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
 </div>;
}
const pageDescriptions:Record<string,string>={office:'See who is here and move around the office',rooms:'Find a meeting, focus, or social space',chat:'Read and send company messages',tasks:'Assign work, submit results, and review contributions',people:'Find teammates and manage membership',agents:'Connect an agent harness and manage its access',infrastructure:'Connect shared storage and browse its file index',hiring:'Manage openings and review applications',activity:'See recent company changes',vault:'Your private skills and reusable knowledge',opportunities:'Discover work and track your applications',layout:'Arrange desks, rooms, and furniture',tester:'Try a 50-person office and inspect performance tests',profile:'Your name, character, and account settings',create:'Start a new company workspace',join:'Accept a workplace invitation'};
function SearchModal({onClose,onNavigate,admin,hasCompany}:{onClose:()=>void;onNavigate:(v:string)=>void;admin:boolean;hasCompany:boolean}){
 const [query,setQuery]=useState(''),[active,setActive]=useState(0),inputRef=useRef<HTMLInputElement>(null);
 const matches=Object.entries(titles).filter(([id,name])=>(!['layout','tester'].includes(id)||admin)&&(hasCompany||['profile','vault','opportunities','create','join'].includes(id))&&(name+' '+pageDescriptions[id]).toLowerCase().includes(query.trim().toLowerCase()));
 const selected=Math.min(active,Math.max(0,matches.length-1));
 useEffect(()=>{document.getElementById('quick-nav-'+selected)?.scrollIntoView({block:'nearest'});},[selected]);
 return <Modal title="Find your way" description="Jump to a page. Search people, work, and files inside their pages." onClose={onClose}><div className="quick-search"><Search size={19}/><input ref={inputRef} className="search-input" placeholder="Where would you like to go?" aria-label="Search navigation" role="combobox" aria-autocomplete="list" aria-expanded="true" aria-controls="quick-nav-results" aria-activedescendant={matches.length?'quick-nav-'+selected:undefined} autoComplete="off" autoFocus value={query} onChange={e=>{setQuery(e.target.value);setActive(0);}} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setActive(current=>Math.max(0,Math.min(matches.length-1,current+(e.key==='ArrowDown'?1:-1))));}if(e.key==='Enter'&&matches[selected]){e.preventDefault();onNavigate(matches[selected][0]);}}}/></div><div className="search-results" id="quick-nav-results" role="listbox" aria-label="Pages">{matches.map(([id,name],index)=><button type="button" key={id} id={'quick-nav-'+index} role="option" aria-selected={selected===index} tabIndex={-1} className="list-row quick-nav-option" onMouseMove={()=>setActive(index)} onClick={()=>onNavigate(id)}><span><strong>{name}</strong><small>{pageDescriptions[id]}</small></span><ArrowRight size={17}/></button>)}</div>{!matches.length&&<div className="search-empty" role="status"><strong>No pages match “{query}”</strong><p>Try a page name such as People, Work board, or Your profile.</p><button type="button" className="button secondary small" onClick={()=>{setQuery('');setActive(0);inputRef.current?.focus();}}>Clear search</button></div>}<div className="search-key-hints" aria-hidden="true"><span><kbd>↑</kbd><kbd>↓</kbd> to choose</span><span><kbd>Enter</kbd> to open</span><span><kbd>Esc</kbd> to close</span></div></Modal>;
}
