'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {api,type User} from '@/lib/client';
import styles from './AgentRunProposals.module.css';

type Proposal={id:string;agentName:string;runId:string;kind:'layout'|'room'|'opening';data:Record<string,any>;status:'pending'|'applied'|'rejected';expiresAt:string;createdAt:string;result:unknown};
export function AgentRunProposals({companyId,runId,user,role}:{companyId:string;runId:string;user:User;role:string}){
 const admin=['owner','admin'].includes(role),[items,setItems]=useState<Proposal[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState<string|null>(null),[confirmation,setConfirmation]=useState<string|null>(null),[loaded,setLoaded]=useState(false),generation=useRef(0);
 const refresh=useCallback(async(signal?:AbortSignal)=>{const scope=generation.current;const data=await api<{items:Proposal[]}>(`/api/companies/${companyId}/agent-proposals?runId=${runId}&limit=100`,'GET',undefined,{signal});signal?.throwIfAborted();if(scope!==generation.current)return;setItems(data.items);setLoaded(true);},[companyId,runId]);
 useEffect(()=>{generation.current++;setItems([]);setError('');setLoaded(false);setBusy(null);setConfirmation(null);if(!admin)return;const controller=new AbortController();refresh(AbortSignal.any([controller.signal,AbortSignal.timeout(20000)])).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{generation.current++;controller.abort();};},[admin,refresh,user.id]);
 async function review(item:Proposal,action:'approve'|'reject'){if(busy)return;const scope=generation.current;setBusy(item.id);setError('');try{await api(`/api/companies/${companyId}/agent-proposals/${item.id}/${action}`,'POST',{}, {signal:AbortSignal.timeout(20000)});if(scope!==generation.current)return;setConfirmation(null);await refresh(AbortSignal.timeout(20000));}catch(e){if(scope===generation.current)setError(e instanceof Error?e.message:'The proposal could not be reviewed.');}finally{if(scope===generation.current)setBusy(null);}}
 if(!admin)return <p className={styles.note}>An administrator reviews any proposed office or hiring changes before they are applied.</p>;
 return <section className={styles.section} aria-label="Proposed workspace changes"><div className={styles.heading}><h3>Proposed changes</h3><button className="button" onClick={()=>{setError('');refresh(AbortSignal.timeout(20000)).catch(e=>setError(e.message));}}>Refresh proposals</button></div><p className={styles.note}>Review the exact change below. Applying a hiring proposal creates an unpublished draft.</p>{error&&<p role="alert" className={styles.error}>{error}</p>}{!loaded&&!error&&<p role="status">Loading proposals…</p>}{loaded&&!items.length&&<p className={styles.note}>No workspace changes proposed for this request.</p>}{items.map(item=>{const expired=new Date(item.expiresAt).getTime()<=Date.now(),layout=item.kind==='layout',data=item.data;return <article key={item.id} className={styles.card}><div className={styles.heading}><strong>{layout?'Office floor':item.kind==='room'?'New room':'Draft opening'}</strong><span>{item.status==='pending'&&expired?'Expired':item.status}</span></div>{layout?<><p>{data.floor.width} × {data.floor.depth} metres · {data.layout.length} objects · based on revision {data.revision}</p><svg className={styles.floor} viewBox="0 0 100 100" role="img" aria-label={`Proposed floor with ${data.layout.length} objects`}><rect width="100" height="100" fill="#f3f3e9"/>{data.layout.map((v:any)=><rect key={v.id} x={v.x} y={v.y} width={v.w} height={v.h} fill={v.type==='plant'?'#a5bd78':'#bac9ae'} stroke="#526b4a" strokeWidth=".3"><title>{v.label} · rotation {v.rotation||0}°</title></rect>)}</svg><details><summary>Review exact floor objects</summary><ul>{data.layout.map((v:any)=><li key={v.id}>{v.label}: {v.type}{v.assetId?` (${v.assetId})`:''}, position {v.x}, {v.y}; size {v.w} × {v.h}; rotation {v.rotation||0}°</li>)}</ul></details></>:<><h4>{data.title||data.name}</h4>{item.kind==='room'?<p>{data.kind} · capacity {data.capacity}</p>:<><p className={styles.body}>{data.description}</p><p>{data.type} · {data.compensation}{data.budget?` · ${data.budget}`:''}</p></>}</>}{item.status==='pending'&&!expired&&<div className={styles.actions}>{confirmation===item.id?<><span>Apply this exact change?</span><button className="button primary" disabled={Boolean(busy)} onClick={()=>review(item,'approve')}>{busy===item.id?'Applying…':'Confirm and apply'}</button><button className="button" disabled={Boolean(busy)} onClick={()=>setConfirmation(null)}>Keep reviewing</button></>:<><button className="button" disabled={Boolean(busy)} onClick={()=>setConfirmation(item.id)}>Review and apply</button><button className="button" disabled={Boolean(busy)} onClick={()=>review(item,'reject')}>Reject proposal</button></>}</div>}</article>;})}</section>;
}
