'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {ArrowRight,Bot,CheckCircle2,Clock3,GitBranch,LoaderCircle,Pause,Play,Plus,RefreshCw,ShieldCheck,Target,XCircle} from 'lucide-react';
import type {WorkspaceProps} from '@/app/page';
import {api,when} from '@/lib/client';
import {Badge,Empty,Field,Loading,Modal,PageHead} from './ui';
import s from './CompanyAutopilot.module.css';

type Mission={id:string;agentId:string;name:string;objective:string;intervalMinutes:number;maxCycles:number;cyclesStarted:number;status:'active'|'paused'|'completed';revision:number;nextRunAt:string|null;lastRunId:string|null;lastRunStatus:string|null;pauseReason:string;createdAt:string};
type Cycle={ordinal:number;trigger:string;createdAt:string;run:{id:string;agentName:string;status:string;result:string;error:string;createdAt:string}};
type Draft={name:string;agentId:string;objective:string;intervalMinutes:number;maxCycles:number;status:'active'|'paused'};
const templates=[
 {name:'Company operations',role:'Operations lead',description:'Turn goals into clear priorities, ownership, and next steps.',objective:'Inspect our current company tasks and recent activity. Identify the most important blocked or unowned work. Propose a practical company structure and a small set of priorities aligned with our current work. Create or update useful tasks when permitted, avoiding duplicates. Report what changed, evidence of progress, and decisions that need human review.'},
 {name:'Product & delivery',role:'Delivery lead',description:'Move a focused piece of work toward a reviewable result.',objective:'Inspect current tasks and recent company updates. Select one actionable priority within your capabilities. Make useful progress, record a concrete result in its task, and submit for independent review when appropriate. Do not mark your own contribution approved. If missing access or information, document a specific blocker rather than inventing progress.'},
 {name:'Quality & review',role:'Quality analyst',description:'Check evidence, spot risks, and prepare independent findings.',objective:'Inspect current company tasks and recent results. Check whether claimed progress is supported by evidence. Prepare clear review findings and practical follow-up tasks where permitted, avoiding duplicate reports. Distinguish what you verified from what requires additional access. Approval of contributions remains with an independent authorized human.'},
];
const err=(error:unknown)=>error instanceof Error?error.message:'The request could not be completed.';
function badge(status:string){return status==='succeeded'||status==='completed'?'good':status==='failed'||status==='cancelled'?'danger':status==='paused'?'warning':'';}
function Notice({children}:{children:React.ReactNode}){return <div className={s.notice}><ShieldCheck size={18}/><p>{children}</p></div>;}
export function CompanyAutopilot(p:WorkspaceProps){return <Autopilot key={`${p.user.id}:${p.company.id}:${p.company.role}`} {...p}/>;}
function Autopilot(p:WorkspaceProps){
 const [missions,setMissions]=useState<Mission[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState<{mission?:Mission;template?:typeof templates[number]}|null>(null),[selected,setSelected]=useState<Mission|null>(null),[more,setMore]=useState(false);
 const active=useRef(true),sequence=useRef(0),controller=useRef<AbortController|null>(null),runKeys=useRef(new Map<string,string>());
 const admin=['owner','admin'].includes(p.company.role);
 const load=useCallback(async()=>{if(controller.current)return;const ticket=++sequence.current;const abort=new AbortController();controller.current=abort;const timer=setTimeout(()=>abort.abort(),20000);try{const result=await api<{missions:Mission[];hasMore:boolean}>(`/api/companies/${p.company.id}/autonomy/missions?limit=100`,'GET',undefined,{signal:abort.signal});if(active.current&&ticket===sequence.current){setMissions(result.missions);setMore(result.hasMore);setError('');}}catch(error){if(active.current&&ticket===sequence.current)setError(err(error));}finally{clearTimeout(timer);if(controller.current===abort)controller.current=null;if(active.current&&ticket===sequence.current)setLoading(false);}},[p.company.id]);
 useEffect(()=>{active.current=true;void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},5000);return()=>{active.current=false;sequence.current++;controller.current?.abort();controller.current=null;clearInterval(timer);};},[load]);
 const liveMission=missions.find(m=>m.id===selected?.id)||selected;
 return <div className={s.view}><PageHead eyebrow="COMPANY AUTOPILOT" title="Give your company direction." description="Turn an objective into recurring, accountable work. Watch your agents make progress, one bounded cycle at a time." action={admin&&<button className="button primary" onClick={()=>setEditor({})}><Plus size={16}/> New mission</button>}/>
  <section className={s.hero} aria-label="Company operating cycle"><div><span className="eyebrow">PURPOSE → PEOPLE → PROGRESS</span><h2>A company that<br/>keeps work moving.</h2><p>You set the destination. Your agents inspect the work, take the next permitted step, and leave a record your team can review.</p><a href="#plugins" className="button secondary">Build your agent team <ArrowRight size={15}/></a></div><div className={s.cycle}>{[{Icon:Target,name:'Set an objective',sub:'A clear outcome and cycle limit'},{Icon:Bot,name:'Assign a company role',sub:'Your model, character, and permissions'},{Icon:GitBranch,name:'Execute & report',sub:'Tasks, results, and reviewable decisions'}].map(({Icon,name,sub},i)=><div key={name}><span><Icon size={19}/></span><section><strong>{name}</strong><small>{sub}</small></section><b>0{i+1}</b></div>)}</div></section>
  <div className={s.stats} aria-label="Autopilot summary"><div><span>Active missions</span><strong>{missions.filter(m=>m.status==='active').length}</strong></div><div><span>Cycles started</span><strong>{missions.reduce((sum,m)=>sum+m.cyclesStarted,0)}</strong></div><div><span>Paused for your review</span><strong>{missions.filter(m=>m.status==='paused'&&m.pauseReason).length}</strong></div></div>
  <div className={s.heading}><div><h2>Your operating rhythm</h2><p>Start with a few focused roles. Expand once their results are dependable.</p></div><button className="button secondary small" onClick={()=>void load()}><RefreshCw size={14}/> Refresh</button></div>
  {error&&<p role="alert" className="error-message">{error} Previously loaded information may be out of date.</p>}
  {loading?<Loading label="Loading company missions"/>:missions.length?<div className={s.missions}>{missions.map(m=>{const agent=p.workspace.agents.find(a=>a.id===m.agentId);return <button key={m.id} className={s.mission} onClick={()=>setSelected(m)}><div className={s.missionTop}><span className={s.symbol}><Target size={18}/></span><Badge tone={badge(m.status)}>{m.status}</Badge></div><h3>{m.name}</h3><p className={s.agent}><Bot size={13}/>{agent?.name||'Company agent'} · AI</p><p className={s.objective}>{m.objective}</p><div className={s.progress} aria-label={`${m.cyclesStarted} of ${m.maxCycles} cycles started`}><span style={{width:`${Math.min(100,m.cyclesStarted/m.maxCycles*100)}%`}}/></div><div className={s.missionMeta}><span>{m.cyclesStarted} / {m.maxCycles} cycles</span><span>Every {m.intervalMinutes<60?`${m.intervalMinutes}m`:`${m.intervalMinutes/60}h`}</span></div><footer>{m.pauseReason?<span className={s.attention}>Review needed</span>:m.lastRunStatus?<span>Latest cycle: {m.lastRunStatus}</span>:<span>Awaiting first cycle</span>}<ArrowRight size={16}/></footer></button>;})}</div>:<div className="panel"><Empty icon={Target} title="Give the team its first mission." description="Create an objective, assign an agent, and choose its cadence. Missions start paused until you choose to activate them." action={admin?<button className="button primary" onClick={()=>setEditor({})}>Create a mission <ArrowRight size={15}/></button>:<p>An owner or administrator can set up company missions.</p>}/></div>}
  {more&&<Notice>The newest 100 missions are shown. The paginated API provides the complete history.</Notice>}
  <div className={s.heading}><div><h2>A starting structure for your company</h2><p>Adapt these responsibilities to your business. Each mission has one accountable agent.</p></div></div>
  <div className={s.templates}>{templates.map(template=><article key={template.name}><span className="eyebrow">{template.role}</span><h3>{template.name}</h3><p>{template.description}</p><button className="button secondary small" disabled={!admin} onClick={()=>setEditor({template})}>Use this mission <ArrowRight size={14}/></button></article>)}</div>
  <Notice>A connected worker must stay online to dispatch and execute cycles. Active missions can incur model usage charges; cycle limits bound the number of requests, not their dollar cost. Agents retain their permissions and human review requirements.</Notice>
  {editor&&<MissionEditor key={editor.mission?.id||'new'} p={p} mission={editor.mission} template={editor.template} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);void load();}}/>}
  {liveMission&&!editor&&<MissionDetail key={liveMission.id} p={p} mission={liveMission} admin={admin} runKeys={runKeys.current} onClose={()=>setSelected(null)} onEdit={()=>{setEditor({mission:liveMission});setSelected(null);}} onChanged={load}/>}
 </div>;
}
function MissionEditor({p,mission,template,onClose,onSaved}:{p:WorkspaceProps;mission?:Mission;template?:typeof templates[number];onClose:()=>void;onSaved:()=>void}){
 const eligible=p.workspace.agents.filter(a=>a.status==='active'&&p.workspace.members.some(member=>member.userId===a.createdBy&&['owner','admin'].includes(member.role))&&a.invocationAccess!=='none'&&a.invocationAccess!==undefined&&(!a.expiresAt||Date.parse(a.expiresAt)>Date.now()));
 const [draft,setDraft]=useState<Draft>({name:mission?.name||template?.name||'',agentId:mission?.agentId||eligible[0]?.id||'',objective:mission?.objective||template?.objective||'',intervalMinutes:mission?.intervalMinutes||60,maxCycles:mission?.maxCycles||3,status:mission?.status==='active'?'active':'paused'}),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const live=useRef(true),controller=useRef<AbortController|null>(null),attempt=useRef({signature:'',id:''});useEffect(()=>{live.current=true;return()=>{live.current=false;controller.current?.abort();};},[]);
 async function save(event:FormEvent){event.preventDefault();if(busy||draft.status==='active'&&!consent)return;setBusy(true);setError('');const abort=new AbortController();controller.current=abort;const timer=setTimeout(()=>abort.abort(),20000);const payload=mission?{revision:mission.revision,name:draft.name,objective:draft.objective,intervalMinutes:draft.intervalMinutes,maxCycles:draft.maxCycles,status:draft.status}:draft;const signature=JSON.stringify(payload);if(signature!==attempt.current.signature)attempt.current={signature,id:crypto.randomUUID()};try{await api(`/api/companies/${p.company.id}/autonomy/missions${mission?'/'+mission.id:''}`,mission?'PATCH':'POST',mission?payload:{...payload,clientId:attempt.current.id},{signal:abort.signal});if(live.current){p.notify('Company mission saved.');onSaved();}}catch(error){if(live.current)setError(err(error));}finally{clearTimeout(timer);if(live.current)setBusy(false);}}
 return <Modal title={mission?'Edit company mission':'Create a company mission'} description="Choose a clear outcome and a bounded operating rhythm." onClose={()=>{if(!busy)onClose();}} wide><form className={s.form} onSubmit={save}><fieldset disabled={busy}>
  <Field label="Mission name"><input required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field>
  <Field label="Responsible agent" hint="Company role and character are configured in Plugins."><select required disabled={!!mission} value={draft.agentId} onChange={e=>setDraft({...draft,agentId:e.target.value})}><option value="">Choose an active agent</option>{eligible.map(a=><option key={a.id} value={a.id}>{a.name} · {a.harness}</option>)}{mission&&!eligible.some(a=>a.id===mission.agentId)&&<option value={mission.agentId}>Assigned agent is unavailable</option>}</select></Field>
  {!eligible.length&&!mission&&<Notice>Install an agent and enable administrator requests in Plugins before assigning a mission.</Notice>}
  <Field label="Business objective" hint="Describe the outcome, how to measure progress, and what the agent should do when blocked."><textarea required maxLength={3000} rows={6} value={draft.objective} onChange={e=>setDraft({...draft,objective:e.target.value})}/></Field>
  <div className={s.formGrid}><Field label="Minutes between cycles"><input required type="number" min={15} max={1440} step={1} value={draft.intervalMinutes} onChange={e=>setDraft({...draft,intervalMinutes:Number(e.target.value)})}/></Field><Field label="Maximum total cycles" hint={mission?`${mission.cyclesStarted} already started. This is a lifetime limit.`:'Every dispatched request counts toward this limit.'}><input required type="number" min={Math.max(1,mission?.cyclesStarted||0)} max={100} step={1} value={draft.maxCycles} onChange={e=>setDraft({...draft,maxCycles:Number(e.target.value)})}/></Field></div>
  <Field label="Mission state"><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Draft['status']})}><option value="paused">Paused — prepare without running</option><option value="active">Active — allow recurring work</option></select></Field>
  {draft.status==='active'&&<label className={s.consent}><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I authorize these recurring requests within the agent’s permissions and understand that model usage may be billed by my provider.{mission?.pauseReason?' I reviewed the previous cycle before resuming.':''}</span></label>}
  {mission&&<Notice>Changing this mission cancels its queued or running cycle. Review committed work before resuming; cancellation does not undo earlier actions.</Notice>}
 </fieldset>{error&&<p role="alert" className="error-message">{error}</p>}<button className="button primary" disabled={busy||!draft.agentId||draft.status==='active'&&!consent}>{busy?'Saving…':mission?'Save mission':'Create mission'} <ArrowRight size={15}/></button></form></Modal>;
}
function MissionDetail({p,mission,admin,runKeys,onClose,onEdit,onChanged}:{p:WorkspaceProps;mission:Mission;admin:boolean;runKeys:Map<string,string>;onClose:()=>void;onEdit:()=>void;onChanged:()=>Promise<void>}){
 const [cycles,setCycles]=useState<Cycle[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[historyError,setHistoryError]=useState('');
 const live=useRef(true),request=useRef<AbortController|null>(null),historyRequest=useRef<AbortController|null>(null),generation=useRef(0);
 const load=useCallback(async()=>{if(historyRequest.current)return;const ticket=++generation.current,abort=new AbortController();historyRequest.current=abort;const timer=setTimeout(()=>abort.abort(),20000);try{const data=await api<{cycles:Cycle[]}>(`/api/companies/${p.company.id}/autonomy/missions/${mission.id}/runs?limit=20`,'GET',undefined,{signal:abort.signal});if(live.current&&ticket===generation.current){setCycles(data.cycles);setHistoryError('');}}catch(error){if(live.current&&ticket===generation.current)setHistoryError(err(error));}finally{clearTimeout(timer);if(historyRequest.current===abort)historyRequest.current=null;if(live.current&&ticket===generation.current)setLoading(false);}},[mission.id,p.company.id]);
 useEffect(()=>{live.current=true;void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},5000);return()=>{live.current=false;generation.current++;request.current?.abort();historyRequest.current?.abort();historyRequest.current=null;clearInterval(timer);};},[load]);
 async function action(kind:'pause'|'run'){if(busy)return;setBusy(true);setError('');const abort=new AbortController();request.current=abort;const timer=setTimeout(()=>abort.abort(),20000);try{if(kind==='pause')await api(`/api/companies/${p.company.id}/autonomy/missions/${mission.id}`,'PATCH',{revision:mission.revision,status:'paused'},{signal:abort.signal});else{if(!runKeys.has(mission.id))runKeys.set(mission.id,crypto.randomUUID());await api(`/api/companies/${p.company.id}/autonomy/missions/${mission.id}/run-now`,'POST',{clientId:runKeys.get(mission.id)},{signal:abort.signal});runKeys.delete(mission.id);}if(live.current){await onChanged();await load();}}catch(error){if(live.current)setError(err(error));}finally{clearTimeout(timer);if(live.current)setBusy(false);}}
 const pending=mission.lastRunStatus==='queued'||mission.lastRunStatus==='running';
 return <Modal title={mission.name} description="Actual requests and results from this company mission." onClose={()=>{if(!busy)onClose();}} wide><div className={s.detail}><div className={s.detailTop}><Badge tone={badge(mission.status)}>{mission.status}</Badge><span>{mission.cyclesStarted} of {mission.maxCycles} cycles started</span></div><p>{mission.objective}</p><div className={s.schedule}><Clock3 size={16}/><span>Every {mission.intervalMinutes} minutes · {mission.status==='active'?`Next eligible: ${when(mission.nextRunAt)}`:'Scheduling paused or completed'}</span></div>{mission.pauseReason&&<p role="status" className={s.reason}>{mission.pauseReason} Review the last result and committed actions before enabling another cycle.</p>}
 {admin&&<div className={s.actions}><button className="button secondary" disabled={busy} onClick={onEdit}>Edit mission</button>{mission.status==='active'&&<><button className="button secondary" disabled={busy} onClick={()=>void action('pause')}><Pause size={15}/> Pause mission</button><button className="button primary" disabled={busy||pending||mission.cyclesStarted>=mission.maxCycles} onClick={()=>void action('run')}><Play size={15}/>{runKeys.has(mission.id)?'Retry original cycle':'Run next cycle now'}</button></>}</div>}{error&&<p role="alert" className="error-message">{error}</p>}
 <div className={s.heading}><h3>Cycle history</h3><span>Most recent 20</span></div>{historyError&&<p role="alert" className="error-message">{historyError}</p>}{loading?<Loading label="Loading cycle history"/>:!cycles.length?<p className={s.muted}>No work has been dispatched yet. A connected worker schedules active missions when they are due.</p>:<ol className={s.history}>{cycles.map(c=><li key={c.run.id}><header><span>{c.run.status==='succeeded'?<CheckCircle2 size={16}/>:c.run.status==='failed'||c.run.status==='cancelled'?<XCircle size={16}/>:c.run.status==='running'?<LoaderCircle size={16}/>:<Clock3 size={16}/>} Cycle {c.ordinal}</span><Badge tone={badge(c.run.status)}>{c.run.status}</Badge></header><small>{when(c.createdAt)} · {c.trigger}</small>{c.run.result?<pre>{c.run.result}</pre>:c.run.error?<p>{c.run.error}</p>:<p>{c.run.status==='queued'?'Waiting for an available worker.':c.run.status==='running'?'The agent is working on this cycle.':'No result was delivered.'}</p>}<a href="#agents">Inspect agent requests and committed actions <ArrowRight size={13}/></a></li>)}</ol>}
 <Notice>Successful execution means the agent returned a result. Business outcomes and contributions still need independent verification.</Notice></div></Modal>;
}
