'use client';

import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowLeft,ArrowRight,Bot,BriefcaseBusiness,Check,ChevronRight,Download,File,FolderOpen,Globe2,HardDrive,Pause,Play,Plus,RefreshCw,Search,Server,ShieldCheck,Unplug,Users,X} from 'lucide-react';
import type {WorkspaceProps} from '@/app/page';
import {api,type Agent,type Application,type Company,type Drive,type Opening,type User,type Workspace,values,when} from '@/lib/client';
import {Avatar,Badge,CopyButton,Empty,Field,Form,Loading,Modal,PageHead,Secret} from './ui';
import s from './Operations.module.css';

const harnessNames:Record<string,string>={hermes:'Hermes','claude-code':'Claude Code',codex:'Codex',custom:'Custom API harness'};
const stages=[{id:'applied',name:'New'},{id:'shortlisted',name:'Shortlisted'},{id:'accepted',name:'Accepted'},{id:'declined',name:'Declined'}];
const canManage=(role:string)=>role==='owner'||role==='admin';
const applicantName=(a:Application)=>a.applicantName||a.name||'Applicant';
const stageName=(status:string)=>stages.find(s=>s.id===status)?.name||status;
const audience=(type:string)=>type==='either'?'People or agents':type==='agent'?'Sponsored agents':'People';
const tone=(status:string)=>status==='accepted'||status==='published'?'good':status==='shortlisted'?'warning':'';
const errorMessage=(e:unknown)=>e instanceof Error?e.message:'Something went wrong. Please try again.';
function useClock(){const [tick,setTick]=useState(0);useEffect(()=>{setTick(Date.now());const timer=setInterval(()=>setTick(Date.now()),30000);return()=>clearInterval(timer);},[]);/* New contacts may arrive between ticks. Sample each client render; the timer only expires old activity. */return tick===0?0:Date.now();}
function recent(lastSeen:string|null|undefined,now:number){const age=lastSeen?now-Date.parse(lastSeen):Infinity;return Number.isFinite(age)&&age>=0&&age<90000;}
function useOrigin(){const [origin,setOrigin]=useState('');useEffect(()=>setOrigin(location.origin),[]);return origin;}
function Summary({items}:{items:{label:string;value:ReactNode;hint:string}[]}){return <dl className={s.summary}>{items.map(item=><div key={item.label}><dt>{item.label}</dt><dd>{item.value}<small>{item.hint}</small></dd></div>)}</dl>;}
function Notice({children}:{children:ReactNode}){return <div className={s.notice}><ShieldCheck size={18}/><div>{children}</div></div>;}
function SearchField({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string}){return <label className={s.search}><Search size={17} aria-hidden="true"/><span className="sr-only">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button type="button" aria-label={'Clear '+label.toLowerCase()} onClick={()=>onChange('')}><X size={15}/></button>}</label>;}
function Guide({kind,origin}:{kind:'agent'|'drive';origin:string}){
 const agent=kind==='agent',command=agent?`node agent-client.mjs --url ${origin}`:`node connector.mjs --url ${origin} --root "/approved/project-folder"`;
 return <div className={s.setup}><ol className={s.steps}>
  <li><strong>Download the {agent?'adapter':'connector'}</strong><p>Use Node.js 22 or later on {agent?'the machine running your harness':'the server that can read your approved folder'}.</p><a className="button secondary small" href={agent?'/downloads/agent-client.mjs':'/downloads/connector.mjs'} download><Download size={14}/> Download {agent?'adapter':'connector'}</a></li>
  <li><strong>Set your saved token</strong><p>Store it as <code>{agent?'COATRIA_AGENT_TOKEN':'COATRIA_CONNECTOR_TOKEN'}</code> in that process’s private environment. Keep it out of commands and shared documents.</p></li>
  <li><strong>{agent?'Make the first request':'Start the folder index'}</strong><p>{agent?'This command fetches eligible work. Your harness runs and supervises the work separately.':'Replace the example path with one approved project folder. Keep the connector running to refresh metadata every 30 seconds.'}</p><pre>{command}</pre><CopyButton text={command} label="Copy command"/></li>
 </ol><a className="text-button" href="/downloads/CONNECTIONS.md" download>Full connection guide <ArrowRight size={14}/></a></div>;
}
function ConnectionWizard({kind,p,onClose}:{kind:'agent'|'drive';p:WorkspaceProps;onClose:()=>void}){
 const [created,setCreated]=useState<{id:string;token:string}|null>(null),[saved,setSaved]=useState(false),[discard,setDiscard]=useState(false),[busy,setBusy]=useState(false);
 const origin=useOrigin(),agent=kind==='agent',record=created?(agent?p.workspace.agents:p.workspace.drives).find(a=>a.id===created.id):undefined;
 function close(){if(busy)return;if(created&&!saved){setDiscard(true);return;}onClose();}
 return <Modal title={created?agent?'Connect your agent':'Start your connector':agent?'Connect an agent':'Connect an existing server'} description={created?'Save the token, configure your process, then verify its first contact.':`Create a company-scoped connection for ${p.company.name}.`} onClose={close} wide>
  <div className={s.progress} aria-label="Connection setup progress"><span aria-current={!created?'step':undefined}>{created?<Check size={13}/>:1} Identity</span><span aria-current={created&&!record?.lastSeenAt?'step':undefined}>2. Configure</span><span aria-current={record?.lastSeenAt?'step':undefined}>3. Verify contact</span></div>
  {created?<><Secret token={created.token} title={agent?'Save your agent token':'Save your connector token'}><label className={s.check}><input type="checkbox" checked={saved} onChange={e=>{setSaved(e.target.checked);setDiscard(false);}}/> I saved this token in a private location.</label></Secret><Guide kind={kind} origin={origin}/><div className={s.verification} role="status"><Badge tone={record?.lastSeenAt?'good':'warning'}>{record?.lastSeenAt?'First contact received':'Waiting for first contact'}</Badge><p>{record?.lastSeenAt?`Last API contact: ${when(record.lastSeenAt)}.`:agent?'Run the adapter to verify access. This page updates as the workspace refreshes.':'Keep the connector running. Its first successful index will appear here.'}</p><button className="button secondary small" onClick={()=>void p.refresh()}><RefreshCw size={14}/> Check connection</button></div>{discard&&<div className={s.confirm} role="alert"><strong>This token cannot be shown again.</strong><p>Save it before leaving. If you discard it, revoke this connection and create a new one to get another token.</p><div className="row"><button className="button secondary small" onClick={()=>setDiscard(false)}>Keep setting up</button><button className="button danger small" onClick={onClose}>Close and discard token</button></div></div>}<button className="button primary" onClick={close}>Done <ArrowRight size={16}/></button></>:<Form submit={agent?'Create agent identity':'Create server connection'} onSubmit={async form=>{setBusy(true);try{const data=values(form),result=await api<{agent?:Agent;drive?:Drive;token:string}>(`/api/companies/${p.company.id}/${agent?'agents':'drives'}`,'POST',agent?data:{...data,kind:'byo'});setCreated({id:(result.agent||result.drive)!.id,token:result.token});await p.refresh();}finally{setBusy(false);}}}>
   <Field label={agent?'Agent name':'Connection name'}><input name="name" required maxLength={agent?80:100} placeholder={agent?'e.g. Atlas':'e.g. London studio NAS'}/></Field>
   {agent&&<Field label="Your harness" hint="This records the harness identity. It does not install or run it."><select name="harness">{Object.entries(harnessNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></Field>}
   <Field label={agent?'What should this agent contribute?':'What material lives here?'}><textarea name="description" maxLength={4000} rows={3} placeholder={agent?'Describe the work this agent will help prepare.':'Describe the approved project folder your team will discover.'}/></Field>
   <Notice><strong>{agent?'Review the access you are granting':'Review what your company can see'}</strong><p>{agent?'The token can fetch eligible unassigned tasks and submit contribution reports. It cannot read personal skill vaults or approve contributions.':'Relative file paths, sizes and modification dates will be visible to company members. Originals remain on your server. The supplied connector indexes up to 1,000 files.'}</p><p className={s.caption}>Sponsored by {p.user.name} · {p.company.name}</p></Notice>
  </Form>}
 </Modal>;
}

// Scope all in-flight form state (including one-time credentials) to its identity and tenant.
export function AgentsView(p:WorkspaceProps){return <AgentsPanel key={`${p.company.id}:${p.user.id}:${p.company.role}`} {...p}/>;}
function AgentsPanel(p:WorkspaceProps){
 const [creating,setCreating]=useState(false),[selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revoke,setRevoke]=useState(false);
 const admin=canManage(p.company.role),now=useClock(),origin=useOrigin(),agent=p.workspace.agents.find(a=>a.id===selected);
 const sponsorActive=(a:Agent)=>canManage(p.workspace.members.find(m=>m.userId===a.createdBy)?.role||'');
 const state=(a:Agent)=>a.status==='revoked'?{label:'Revoked',tone:'danger'}:!sponsorActive(a)?{label:'Sponsor access ended',tone:'warning'}:a.status==='paused'?{label:'Paused',tone:'warning'}:!a.lastSeenAt?{label:'Needs setup',tone:'warning'}:recent(a.lastSeenAt,now)?{label:'Recent API activity',tone:'good'}:{label:'No recent API activity',tone:''};
 const filtered=p.workspace.agents.filter(a=>(filter==='all'||(filter==='setup'?a.status==='active'&&sponsorActive(a)&&!a.lastSeenAt:filter==='active'?a.status==='active'&&sponsorActive(a):a.status===filter))&&[a.name,a.description,harnessNames[a.harness]].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 useEffect(()=>{setCreating(false);setSelected(null);setError('');setRevoke(false);},[p.company.id,p.user.id]);
 async function update(a:Agent,next:string){setBusy(true);setError('');try{await api(`/api/companies/${p.company.id}/agents/${a.id}`,'PATCH',{status:next});setRevoke(false);await p.refresh();p.notify(next==='revoked'?'Agent token permanently revoked.':next==='paused'?'Agent API access paused.':'Agent API access resumed.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <div className={s.view}>
  <PageHead eyebrow={p.company.name} title="Agents" description="Manage the agents that can contribute to this workplace." action={admin?<button className="button primary" onClick={()=>setCreating(true)}><Plus size={16}/> Connect an agent</button>:undefined}/>
  <Summary items={[{label:'Access enabled',value:p.workspace.agents.filter(a=>a.status==='active'&&sponsorActive(a)).length,hint:'Company-scoped identities'},{label:'Needs setup',value:p.workspace.agents.filter(a=>a.status==='active'&&sponsorActive(a)&&!a.lastSeenAt).length,hint:'No API contact yet'},{label:'Awaiting review',value:p.workspace.tasks.filter(t=>t.status==='review'&&t.submittedAgentId).length,hint:'Agent contributions on the work board'}]}/>
  {!admin&&<Notice><p>Owners and administrators connect agents and manage their access. You can inspect the identities working in this company.</p></Notice>}
  <div className={s.toolbar}><SearchField label="Search agents" value={query} onChange={setQuery} placeholder="Search name or harness…"/><Field label="Agent access"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All agents</option><option value="setup">Needs setup</option><option value="active">Access enabled</option><option value="paused">Paused</option><option value="revoked">Revoked</option></select></Field></div>
  <div className={s.sectionHead}><h2>Company agents <span>{filtered.length}</span></h2><a className="text-button" href="#tasks">Review work <ArrowRight size={14}/></a></div>
  {filtered.length?<div className={s.cards}>{filtered.map(a=><button className={s.card} key={a.id} onClick={()=>{setSelected(a.id);setError('');setRevoke(false);}}><div className="row between"><span className={s.identity}><Bot size={24}/><b>AI</b></span><Badge tone={state(a).tone}>{state(a).label}</Badge></div><h3>{a.name}</h3><p className={s.clamp}>{a.description||'No contribution focus added.'}</p><dl className={s.facts}><div><dt>Harness</dt><dd>{harnessNames[a.harness]||a.harness}</dd></div><div><dt>Sponsor</dt><dd>{p.workspace.members.find(m=>m.userId===a.createdBy)?.name||'Former administrator'}</dd></div></dl><footer>{a.status==='revoked'?'View revoked identity':!a.lastSeenAt?'Continue setup':'View access & activity'}<ArrowRight size={16}/></footer></button>)}</div>:<div className="panel"><Empty icon={Bot} title={p.workspace.agents.length?'No agents match these filters':'Connect your first agent'} description={p.workspace.agents.length?'Try another name or clear the filters.':'Create an identity, save its token, then connect the harness running on your own machine.'} action={p.workspace.agents.length?<button className="button secondary" onClick={()=>{setQuery('');setFilter('all');}}>Clear filters</button>:admin?<button className="button primary" onClick={()=>setCreating(true)}>Connect your first agent</button>:undefined}/></div>}
  <Notice><strong>Company work, with a clear boundary.</strong><p>Your harness runs on your infrastructure. Private skills stay in their owner’s vault; submitted work goes to the company for an independent review. A recent API request does not mean the agent is continuously running.</p></Notice>
  {admin&&creating&&<ConnectionWizard key={p.company.id+p.user.id} kind="agent" p={p} onClose={()=>setCreating(false)}/>}
  {agent&&<Modal title={agent.name} description={harnessNames[agent.harness]||agent.harness} onClose={()=>{if(!busy)setSelected(null);}} wide><div className="stack"><div className="row"><Badge tone={state(agent).tone}>{state(agent).label}</Badge><Badge>AI identity</Badge></div><p>{agent.description||'No contribution focus added.'}</p><dl className={s.facts}><div><dt>Company scope</dt><dd>{p.company.name}</dd></div><div><dt>Sponsor</dt><dd>{p.workspace.members.find(m=>m.userId===agent.createdBy)?.name||'Former administrator'}</dd></div><div><dt>Last API contact</dt><dd>{agent.lastSeenAt?when(agent.lastSeenAt):'Not received yet'}</dd></div><div><dt>Personal vault access</dt><dd>None</dd></div></dl>
   {!sponsorActive(agent)&&agent.status!=='revoked'&&<Notice><p>The sponsor no longer has administrator access. This identity cannot authenticate. An administrator can revoke it and create a new sponsored identity.</p></Notice>}{error&&<p className="error-message" role="alert">{error}</p>}
   {admin&&agent.status!=='revoked'&&<div className="row"><button className="button secondary" disabled={busy||!sponsorActive(agent)} onClick={()=>void update(agent,agent.status==='paused'?'active':'paused')}>{agent.status==='paused'?<Play size={16}/>:<Pause size={16}/>} {agent.status==='paused'?'Resume access':'Pause access'}</button><button className="button danger" disabled={busy} onClick={()=>setRevoke(true)}><Unplug size={16}/> Revoke token</button></div>}
   {admin&&revoke&&<div className={s.confirm}><strong>Permanently revoke {agent.name}?</strong><p>This token will stop working and cannot be restored. Existing contributions remain available for review.</p><div className="row"><button className="button secondary small" disabled={busy} onClick={()=>setRevoke(false)}>Cancel</button><button className="button danger small" disabled={busy} onClick={()=>void update(agent,'revoked')}>{busy?'Revoking…':'Revoke access permanently'}</button></div></div>}
   {agent.status==='revoked'?<Notice><p>This identity is retained for its contribution history. Connect a new agent to issue a new token.</p></Notice>:<details className={s.disclosure} open={!agent.lastSeenAt}><summary>Connection instructions</summary><p className={s.caption}>Use the token you saved during creation. Coatria cannot display it again.</p><Guide kind="agent" origin={origin}/></details>}
  </div></Modal>}
 </div>;
}

type IndexedFile={path:string;size:number;modifiedAt:string};
const filesize=(size:number)=>size>=1e9?(size/1e9).toFixed(1)+' GB':size>=1e6?(size/1e6).toFixed(1)+' MB':size>=1e3?(size/1e3).toFixed(1)+' KB':size+' B';
function DriveDetails({drive,p,onClose}:{drive:Drive;p:WorkspaceProps;onClose:()=>void}){
 const [files,setFiles]=useState<IndexedFile[]|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[sort,setSort]=useState('path'),[page,setPage]=useState(0),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[revoke,setRevoke]=useState(false);
 const now=useClock(),origin=useOrigin(),admin=canManage(p.company.role),revoked=drive.status==='revoked';
 useEffect(()=>{let active=true;setError('');setFiles(null);api<{files:IndexedFile[]}>(`/api/companies/${p.company.id}/drives/${drive.id}/files`).then(r=>{if(active)setFiles(r.files);}).catch(e=>{if(active)setError(errorMessage(e));});return()=>{active=false;};},[p.company.id,drive.id,drive.lastSeenAt,revision]);
 useEffect(()=>setPage(0),[query,sort]);
 const filtered=(files||[]).filter(f=>f.path.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==='size'?b.size-a.size:sort==='modified'?Date.parse(b.modifiedAt)-Date.parse(a.modifiedAt):a.path.localeCompare(b.path)),currentPage=Math.min(page,Math.max(0,Math.ceil(filtered.length/50)-1)),shown=filtered.slice(currentPage*50,currentPage*50+50);
 return <Modal title={drive.name} description="Shared metadata index" onClose={()=>{if(!busy)onClose();}} wide><div className="stack"><div className="row between"><Badge tone={revoked?'danger':recent(drive.lastSeenAt,now)?'good':'warning'}>{revoked?'Revoked':recent(drive.lastSeenAt,now)?'Recent connector contact':drive.lastSeenAt?'Connector not recently seen':'Awaiting first index'}</Badge><span className={s.caption}>{drive.lastSeenAt?'Last contact '+when(drive.lastSeenAt):'No index received yet'}</span></div><p>{drive.description||'No folder description added.'}</p><Notice><p>{revoked?'This token can no longer refresh the index. The last received metadata remains visible to members.':'Only paths, sizes and dates are shared. Open the original files through your existing storage tools.'}</p></Notice><div className={s.toolbar}><SearchField label="Search indexed files" value={query} onChange={setQuery} placeholder="Find a relative path…"/><Field label="Sort files"><select value={sort} onChange={e=>setSort(e.target.value)}><option value="path">Path A–Z</option><option value="size">Largest first</option><option value="modified">Recently modified</option></select></Field></div>
  {error?<div className="error-message" role="alert">{error}<button className="text-button" onClick={()=>setRevision(v=>v+1)}>Retry loading index</button></div>:!files?<Loading label="Loading the file index"/>:!files.length?<Empty icon={FolderOpen} title={drive.lastSeenAt?'No files in the latest index':'Waiting for your first index'} description={drive.lastSeenAt?'The connector reported an empty folder. Check its approved root on your server.':'Run the connector using the setup instructions below. The index appears after a successful scan.'}/>:!filtered.length?<Empty icon={Search} title="No paths match your search" description="Search part of the filename or folder, or clear your search." action={<button className="button secondary small" onClick={()=>setQuery('')}>Clear file search</button>}/>:<><div className={s.tableWrap}><table className={s.fileTable}><caption className="sr-only">Indexed file metadata</caption><thead><tr><th scope="col">Relative path</th><th scope="col">Size</th><th scope="col">Modified</th></tr></thead><tbody>{shown.map(f=><tr key={f.path}><td><span><File size={15}/>{f.path}</span></td><td>{filesize(f.size)}</td><td>{when(f.modifiedAt)}</td></tr>)}</tbody></table></div><div className={s.pagination}><span>Showing {currentPage*50+1}–{Math.min((currentPage+1)*50,filtered.length)} of {filtered.length} files</span>{filtered.length>50&&<div className="row"><button className="button secondary small" disabled={!currentPage} onClick={()=>setPage(currentPage-1)}>Previous</button><button className="button secondary small" disabled={(currentPage+1)*50>=filtered.length} onClick={()=>setPage(currentPage+1)}>Next</button></div>}</div></>}
  <div className="row"><button className="button secondary" onClick={()=>setRevision(v=>v+1)}><RefreshCw size={15}/> Refresh index</button>{admin&&!revoked&&<button className="button danger" disabled={busy} onClick={()=>setRevoke(true)}><Unplug size={15}/> Revoke connector</button>}</div>
  {admin&&revoke&&!revoked&&<div className={s.confirm}><strong>Revoke {drive.name}?</strong><p>The connector loses permission to send updates. This does not erase originals or the last received index.</p><div className="row"><button className="button secondary small" disabled={busy} onClick={()=>setRevoke(false)}>Cancel</button><button className="button danger small" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api(`/api/companies/${p.company.id}/drives/${drive.id}`,'PATCH',{status:'revoked'});setRevoke(false);await p.refresh();p.notify('Connector token permanently revoked.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>{busy?'Revoking…':'Revoke access permanently'}</button></div></div>}
  {!revoked&&<details className={s.disclosure} open={!drive.lastSeenAt}><summary>Connector setup & troubleshooting</summary><Guide kind="drive" origin={origin}/><p className={s.caption}>If contact stops, confirm the process is running, the approved folder is readable and the token is still active. Use the saved token; lost tokens must be revoked and replaced with a new connection.</p></details>}
 </div></Modal>;
}
export function InfrastructureView(p:WorkspaceProps){return <InfrastructurePanel key={`${p.company.id}:${p.user.id}:${p.company.role}`} {...p}/>;}
function InfrastructurePanel(p:WorkspaceProps){
 const [creating,setCreating]=useState(false),[selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 const admin=canManage(p.company.role),now=useClock(),drive=p.workspace.drives.find(d=>d.id===selected),active=p.workspace.drives.filter(d=>d.status!=='revoked');
 const filtered=p.workspace.drives.filter(d=>(filter==='all'||(filter==='active'?d.status!=='revoked':d.status==='revoked'))&&[d.name,d.description].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 useEffect(()=>{setCreating(false);setSelected(null);},[p.company.id,p.user.id]);
 return <div className={s.view}><PageHead eyebrow={p.company.name} title="Infrastructure" description="Find shared material while your originals stay on your own servers." action={admin?<button className="button primary" onClick={()=>setCreating(true)}><Plus size={16}/> Connect your server</button>:undefined}/>
  <Summary items={[{label:'Saved connections',value:p.workspace.drives.length,hint:'Configured in this company'},{label:'Recent contact',value:active.filter(d=>recent(d.lastSeenAt,now)).length,hint:'Connector seen within 90 seconds'},{label:'Indexed files',value:active.reduce((total,d)=>total+(d.fileCount||0),0).toLocaleString(),hint:'File metadata, not uploaded originals'}]}/>
  <div className={s.capability}><span className={s.identity}><Server size={26}/></span><div><h2>Shared file discovery</h2><p>Browse names, sizes and dates from an approved folder. Use your existing tools to open the files.</p><div className="row"><Badge>Metadata only</Badge><Badge>Outbound connection</Badge><Badge>1,000 files per supplied connector</Badge></div></div></div>
  {!admin&&<Notice><p>Owners and administrators connect servers. Company members can browse the shared metadata index.</p></Notice>}
  <div className={s.toolbar}><SearchField label="Search infrastructure" value={query} onChange={setQuery} placeholder="Search connections…"/><Field label="Connection access"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All connections</option><option value="active">Active</option><option value="revoked">Revoked</option></select></Field></div><div className={s.sectionHead}><h2>Server connections <span>{filtered.length}</span></h2></div>
  {filtered.length?<div className={s.cards}>{filtered.map(d=><button className={s.card} key={d.id} onClick={()=>setSelected(d.id)}><div className="row between"><Server size={23}/><Badge tone={d.status==='revoked'?'danger':recent(d.lastSeenAt,now)?'good':'warning'}>{d.status==='revoked'?'Revoked':recent(d.lastSeenAt,now)?'Recent contact':d.lastSeenAt?'No recent contact':'Needs setup'}</Badge></div><h3>{d.name}</h3><p className={s.clamp}>{d.description||'An approved folder on your infrastructure.'}</p><dl className={s.facts}><div><dt>Indexed files</dt><dd>{(d.fileCount||0).toLocaleString()}</dd></div><div><dt>Last contact</dt><dd>{d.lastSeenAt?when(d.lastSeenAt):'Not received yet'}</dd></div></dl><footer>{d.lastSeenAt?'Browse file index':'Continue setup'}<ArrowRight size={16}/></footer></button>)}</div>:<div className="panel"><Empty icon={HardDrive} title={p.workspace.drives.length?'No matching connections':'Connect your first project folder'} description={p.workspace.drives.length?'Clear the filters to see all server connections.':'An administrator creates a connection, then runs the connector on the server that can read the approved folder.'} action={p.workspace.drives.length?<button className="button secondary" onClick={()=>{setQuery('');setFilter('all');}}>Clear filters</button>:admin?<button className="button primary" onClick={()=>setCreating(true)}>Connect your first folder</button>:undefined}/></div>}
  <Notice><strong>Available in this release</strong><p>Bring-your-own-server metadata indexing. File downloads, streaming, mounted drives and managed paid servers are not available yet.</p></Notice>
  {admin&&creating&&<ConnectionWizard key={p.company.id+p.user.id} kind="drive" p={p} onClose={()=>setCreating(false)}/>}{drive&&<DriveDetails key={p.company.id+drive.id} drive={drive} p={p} onClose={()=>setSelected(null)}/>}
 </div>;
}

type OpportunitiesProps={user:User|null;companies:Company[];notify:(s:string)=>void;onSignIn?:()=>void};
export function OpportunitiesView(p:OpportunitiesProps){return <OpportunitiesPanel key={p.user?.id||'public'} {...p}/>;}
function OpportunitiesPanel({user,companies,notify,onSignIn}:OpportunitiesProps){
 const mineRequest=useRef(0);
 const [openings,setOpenings]=useState<Opening[]|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[mine,setMine]=useState<{owner:string;items:Application[]}|null>(null),[mineError,setMineError]=useState(''),[mineRevision,setMineRevision]=useState(0),[selected,setSelected]=useState<Opening|null>(null),[application,setApplication]=useState<Application|null>(null),[query,setQuery]=useState(''),[type,setType]=useState('all'),[pay,setPay]=useState('all'),[sort,setSort]=useState('newest'),[view,setView]=useState('browse');
 useEffect(()=>{let active=true;setError('');api<{openings:Opening[]}>('/api/opportunities').then(r=>{if(active)setOpenings(r.openings);}).catch(e=>{if(active)setError(errorMessage(e));});return()=>{active=false;};},[revision]);
 useEffect(()=>{let active=true;const request=++mineRequest.current;setMine(null);setMineError('');if(user)api<{applications:Application[]}>('/api/applications').then(r=>{if(active&&request===mineRequest.current)setMine({owner:user.id,items:r.applications});}).catch(e=>{if(active&&request===mineRequest.current)setMineError(errorMessage(e));});return()=>{active=false;};},[user?.id,mineRevision]);
 useEffect(()=>{setSelected(null);setApplication(null);setView('browse');},[user?.id]);
 const applications=mine?.owner===user?.id?mine?.items||[]:[],filtered=(openings||[]).filter(o=>(type==='all'||o.type===type||o.type==='either')&&(pay==='all'||o.compensation===pay)&&[o.title,o.companyName,o.description].join(' ').toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==='company'?(a.companyName||'').localeCompare(b.companyName||''):Date.parse(b.createdAt)-Date.parse(a.createdAt));
 const reset=()=>{setQuery('');setType('all');setPay('all');setSort('newest');};
 return <div className={s.view}><PageHead eyebrow="Explore the community" title="Opportunities" description="Find a company looking for the contribution you can make."/>
  <div className={s.switcher} aria-label="Opportunity view"><button aria-pressed={view==='browse'} onClick={()=>setView('browse')}>Browse openings {openings&&<span>{openings.length}</span>}</button>{user&&<button aria-pressed={view==='applications'} onClick={()=>setView('applications')}>My applications {mine&&<span>{applications.length}</span>}</button>}</div>
  {view==='browse'?<><div className={s.toolbar}><SearchField label="Search opportunities" value={query} onChange={setQuery} placeholder="Role, company or skill…"/><Field label="Who can apply"><select value={type} onChange={e=>setType(e.target.value)}><option value="all">People & agents</option><option value="human">For people</option><option value="agent">For agents</option></select></Field><Field label="Compensation"><select value={pay} onChange={e=>setPay(e.target.value)}><option value="all">Any compensation</option><option value="paid">Paid</option><option value="volunteer">Volunteer / unpaid</option></select></Field><Field label="Sort opportunities"><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="company">Company A–Z</option></select></Field></div><div className={s.sectionHead}><p role="status">{openings?`${filtered.length} ${filtered.length===1?'opportunity':'opportunities'}`:'Loading openings…'}{openings&&openings.length>=200?' · Latest 200 published openings':''}</p>{(query||type!=='all'||pay!=='all')&&<button className="text-button" onClick={reset}>Clear filters</button>}</div>
   {error?<div className="error-message" role="alert">{error}<button className="text-button" onClick={()=>setRevision(v=>v+1)}>Try again</button></div>:!openings?<Loading label="Loading published opportunities"/>:filtered.length?<div className={s.openingGrid}>{filtered.map(o=><button className={s.openingCard} key={o.id} onClick={()=>setSelected(o)}><div className="row between"><span className={s.companyName}>{o.companyName||'Company'}</span><Badge tone={o.compensation==='paid'?'good':''}>{o.compensation==='paid'?'Paid':'Volunteer / unpaid'}</Badge></div><h2>{o.title}</h2><p className={s.clamp}>{o.description}</p><div className={s.compensation}>{o.budget||'Scope and terms agreed directly'}</div><footer><Badge>{audience(o.type)}</Badge>{applications.some(a=>a.openingId===o.id)?<span className={s.applied}><Check size={14}/> Applied</span>:<span>View opening <ArrowRight size={15}/></span>}</footer><small>Posted {when(o.createdAt)}</small></button>)}</div>:<div className="panel"><Empty icon={BriefcaseBusiness} title={openings.length?'No openings match your filters':'No published openings yet'} description={openings.length?'Try a broader search, a different applicant type or any compensation.':'Companies will publish roles and projects here when they are ready to receive applications.'} action={openings.length?<button className="button secondary" onClick={reset}>Clear filters</button>:<button className="button secondary" onClick={()=>setRevision(v=>v+1)}><RefreshCw size={14}/> Refresh openings</button>}/></div>}
   <Notice><p>Paid and volunteer opportunities are labeled by the company. Agree scope and compensation directly; Coatria does not process payments or guarantee an engagement.</p></Notice>
  </>:<><div className={s.sectionHead}><h2>Your application history</h2><button className="text-button" onClick={()=>setMineRevision(v=>v+1)}><RefreshCw size={14}/> Refresh status</button></div>{mineError?<div className="error-message" role="alert">{mineError}<button className="text-button" onClick={()=>setMineRevision(v=>v+1)}>Retry applications</button></div>:!mine?<Loading label="Loading your applications"/>:applications.length?<div className={s.list}>{applications.map(a=><button className={s.applicationRow} key={a.id} onClick={()=>setApplication(a)}><span className={s.identity}>{a.agentId?<Bot size={21}/>:<BriefcaseBusiness size={21}/>}</span><span className={s.rowBody}><strong>{a.openingTitle||'Your application'}</strong><small>{a.companyName} · {when(a.createdAt)}</small></span><Badge tone={tone(a.status)}>{stageName(a.status)}</Badge><ChevronRight size={17}/></button>)}</div>:<div className="panel"><Empty icon={BriefcaseBusiness} title="Your next introduction starts here" description="Apply to a published opening to track its review status in this list." action={<button className="button primary" onClick={()=>setView('browse')}>Browse openings</button>}/></div>}<Notice><p>Acceptance is followed by a company invitation. It does not automatically add you or your agent to a workplace.</p></Notice></>}
  {selected&&<ApplyModal key={selected.id+(user?.id||'public')} opening={selected} user={user} companies={companies} notify={notify} existing={applications.find(a=>a.openingId===selected.id)} onClose={()=>setSelected(null)} onSignIn={onSignIn} onApplied={a=>{mineRequest.current++;setMineError('');if(user)setMine(current=>({owner:user.id,items:[{...a,openingTitle:selected.title,companyName:selected.companyName},...(current?.owner===user.id?current.items:[]).filter(v=>v.openingId!==a.openingId)]}));}}/>}
  {application&&applications.some(a=>a.id===application.id)&&<Modal title={application.openingTitle||'Your application'} description={application.companyName} onClose={()=>setApplication(null)}><div className="stack"><Badge tone={tone(application.status)}>{stageName(application.status)}</Badge><p className={s.caption}>Submitted {when(application.createdAt)} · {application.agentId?'Sponsored agent':'Applied as yourself'}</p><p className={s.fullText}>{application.message}</p><Notice><p>{application.status==='accepted'?'The company accepted your application. Its administrator must share a workplace invitation with you. No automatic email or payment was sent.':application.status==='declined'?'The company chose not to progress this application. You can explore other published opportunities.':'The company can review your introduction and update its status here.'}</p></Notice></div></Modal>}
 </div>;
}
function ApplyModal({opening:o,user,companies,notify,onClose,onSignIn,existing,onApplied}:OpportunitiesProps&{opening:Opening;onClose:()=>void;existing?:Application;onApplied:(a:Application)=>void}){
 const [sent,setSent]=useState(false),[asAgent,setAsAgent]=useState(o.type==='agent'),[companyId,setCompanyId]=useState(''),[agentResult,setAgentResult]=useState<{companyId:string;items:Agent[]}|null>(null),[agentId,setAgentId]=useState(''),[agentError,setAgentError]=useState('');
 const sponsors=companies.filter(c=>canManage(c.role)),sponsorIds=sponsors.map(c=>c.id).sort().join('|'),agents=agentResult?.companyId===companyId?agentResult.items:null;
 useEffect(()=>{let active=true;setAgentResult(null);setAgentId('');setAgentError('');if(companyId&&user&&sponsors.some(c=>c.id===companyId))api<Workspace>(`/api/companies/${companyId}/workspace`).then(w=>{if(active)setAgentResult({companyId,items:canManage(w.company.role)?w.agents.filter(a=>a.createdBy===user.id&&a.status==='active'):[]});}).catch(e=>{if(active){setAgentResult({companyId,items:[]});setAgentError(errorMessage(e));}});return()=>{active=false;};},[companyId,user?.id,sponsorIds]);
 const validAgent=sponsors.some(c=>c.id===companyId)&&!!agentId&&!!agents?.some(a=>a.id===agentId);
 return <Modal title={sent?'Application submitted':o.title} description={o.companyName} onClose={onClose} wide><div className="stack">
  {sent?<><Badge tone="good"><Check size={13}/> Introduction received</Badge><p>The company can review your application. Follow its status in My applications. If selected, an administrator shares an invitation with you.</p><button className="button primary" onClick={onClose}>Done <ArrowRight size={16}/></button></>:<><div className="row"><Badge>{audience(o.type)}</Badge><Badge tone={o.compensation==='paid'?'good':''}>{o.compensation==='paid'?'Paid engagement':'Volunteer / unpaid'}</Badge>{o.budget&&<Badge>{o.budget}</Badge>}</div><p className={s.fullText}>{o.description}</p>{existing?<Notice><strong>You already applied · {stageName(existing.status)}</strong><p>Your introduction is saved. See My applications for its status; each account can apply once to an opening.</p></Notice>:user?<Form submit="Send application" submitDisabled={asAgent&&!validAgent} onSubmit={async f=>{if(asAgent&&!validAgent)throw new Error('Select an active agent you sponsor.');const result=await api<{application:Application}>(`/api/opportunities/${o.id}/apply`,'POST',{message:values(f).message,...(asAgent?{agentId}:{})});onApplied(result.application);setSent(true);notify('Your application has been submitted.');}}>
   {o.type==='either'&&<Field label="Apply as"><select value={asAgent?'agent':'human'} onChange={e=>setAsAgent(e.target.value==='agent')}><option value="human">Myself · {user.name}</option><option value="agent">An agent I sponsor</option></select></Field>}
   {asAgent&&<><Field label="Agent’s current company"><select value={companyId} onChange={e=>setCompanyId(e.target.value)} required><option value="">Choose a company you administer</option>{sponsors.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>{companyId&&<Field label="Agent identity"><select value={agentId} onChange={e=>setAgentId(e.target.value)} required disabled={!agents}><option value="">{agents?'Select your active agent':'Loading agents…'}</option>{agents?.map(a=><option key={a.id} value={a.id}>{a.name} · {harnessNames[a.harness]||a.harness}</option>)}</select></Field>}{agentError&&<p className="error-message" role="alert">{agentError}</p>}{!sponsors.length?<Notice><p>You need an owner or administrator role in a company to sponsor an agent. Create an agent identity in that company before applying.</p></Notice>:companyId&&agents?.length===0?<Notice><p>No active agents sponsored by you were found in this company. Connect an agent or resume its access from the company’s Agents page.</p></Notice>:<p className={s.caption}>Only active agents you created in a company you administer can be represented. An application does not transfer its private skills or company credentials.</p>}</>}
   <Field label="Your introduction" hint="Explain your approach, relevant work and availability. 20–6,000 characters."><textarea name="message" required minLength={20} maxLength={6000} rows={5} placeholder="What can you contribute, and how would you approach this work?"/></Field><Notice><p>Your introduction and account details are shared with the company’s administrators. Agree scope and compensation directly; no payment or workplace access is created by applying.</p></Notice>
  </Form>:<button className="button primary" onClick={onSignIn}>Sign in to apply <ArrowRight size={16}/></button>}</>}
 </div></Modal>;
}

export function HiringView(p:WorkspaceProps){return <HiringPanel key={`${p.company.id}:${p.user.id}:${p.company.role}`} {...p}/>;}
function HiringPanel(p:WorkspaceProps){
 const [creating,setCreating]=useState(false),[selected,setSelected]=useState<string|null>(null),[candidate,setCandidate]=useState<Application|null>(null),[invite,setInvite]=useState(''),[inviteSaved,setInviteSaved]=useState(false),[inviteDiscard,setInviteDiscard]=useState(false),[query,setQuery]=useState(''),[openingFilter,setOpeningFilter]=useState('all'),[stage,setStage]=useState('all'),[candidateQuery,setCandidateQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[transition,setTransition]=useState<{opening:Opening;status:string}|null>(null);
 const admin=canManage(p.company.role),opening=p.workspace.openings.find(o=>o.id===selected),applications=selected?p.workspace.applications.filter(a=>a.openingId===selected):p.workspace.applications;
 const filtered=p.workspace.openings.filter(o=>(openingFilter==='all'||o.status===openingFilter)&&[o.title,o.description].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 const candidates=applications.filter(a=>(stage==='all'||a.status===stage)&&[applicantName(a),a.applicantEmail,p.workspace.openings.find(o=>o.id===a.openingId)?.title].join(' ').toLowerCase().includes(candidateQuery.trim().toLowerCase()));
 useEffect(()=>{setCreating(false);setSelected(null);setCandidate(null);setInvite('');setTransition(null);setError('');},[p.company.id,p.user.id]);
 useEffect(()=>{if(!admin){setCandidate(null);setInvite('');setCreating(false);setTransition(null);}},[admin]);
 function chooseOpening(id:string|null){setSelected(id);setStage('all');setCandidateQuery('');setError('');}
 function closeCandidate(){if(busy)return;if(invite&&!inviteSaved){setInviteDiscard(true);return;}setCandidate(null);setInvite('');}
 return <div className={s.view}><PageHead eyebrow={p.company.name} title={opening?opening.title:'Hiring'} description={opening?'Review this opening and the introductions it receives.':'Publish a clear opening and move applicants through a considered review.'} action={opening?<button className="button secondary" onClick={()=>chooseOpening(null)}><ArrowLeft size={16}/> All openings</button>:admin?<button className="button primary" onClick={()=>setCreating(true)}><Plus size={16}/> Create an opening</button>:undefined}/>
  {!opening&&<Summary items={[{label:'Published',value:p.workspace.openings.filter(o=>o.status==='published').length,hint:'Visible in public opportunities'},{label:'Drafts',value:p.workspace.openings.filter(o=>o.status==='draft').length,hint:'Private to this company'},{label:admin?'New applications':'Your access',value:admin?p.workspace.applications.filter(a=>a.status==='applied').length:'View openings',hint:admin?'Ready for an administrator’s review':'Applicant details are administrator-only'}]}/>}
  {error&&!transition&&<p className="error-message" role="alert">{error}</p>}
  {opening?<section className={s.openingDetail}><div className="row"><Badge tone={tone(opening.status)}>{opening.status==='published'?'Public · accepting applications':opening.status==='draft'?'Private draft':'Closed to applications'}</Badge><Badge>{audience(opening.type)}</Badge><Badge>{opening.compensation==='paid'?'Paid':'Volunteer / unpaid'}</Badge></div><p className={s.fullText}>{opening.description}</p>{opening.budget&&<p><strong>Compensation details:</strong> {opening.budget}</p>}{admin&&<div className="row">{opening.status!=='published'&&<button className="button primary" onClick={()=>{setError('');setTransition({opening,status:'published'});}}><Globe2 size={15}/> {opening.status==='closed'?'Reopen applications':'Publish opening'}</button>}{opening.status==='published'&&<button className="button secondary" onClick={()=>{setError('');setTransition({opening,status:'draft'});}}>Unpublish</button>}{opening.status!=='closed'&&<button className="button secondary" onClick={()=>{setError('');setTransition({opening,status:'closed'});}}>Close applications</button>}</div>}<p className={s.caption}>{opening.status==='published'?'The title, company, description and compensation details are publicly visible.':'This opening is not listed in public opportunities.'} Existing applications stay in the company’s review history.</p></section>:<><div className={s.toolbar}><SearchField label="Search company openings" value={query} onChange={setQuery} placeholder="Find an opening…"/><Field label="Opening status"><select value={openingFilter} onChange={e=>setOpeningFilter(e.target.value)}><option value="all">All statuses</option><option value="draft">Drafts</option><option value="published">Published</option><option value="closed">Closed</option></select></Field></div>{filtered.length?<div className={s.openingGrid}>{filtered.map(o=><button className={s.openingCard} key={o.id} onClick={()=>chooseOpening(o.id)}><div className="row between"><Badge tone={tone(o.status)}>{o.status==='draft'?'Private draft':o.status==='published'?'Published':'Closed'}</Badge>{admin&&<small>{p.workspace.applications.filter(a=>a.openingId===o.id).length} applications</small>}</div><h2>{o.title}</h2><p className={s.clamp}>{o.description}</p><footer><Badge>{audience(o.type)}</Badge><span>{admin?'Review opening':'View opening'} <ArrowRight size={15}/></span></footer></button>)}</div>:<div className="panel"><Empty icon={BriefcaseBusiness} title={p.workspace.openings.length?'No matching openings':'Create your first opening'} description={p.workspace.openings.length?'Try another search or show all statuses.':'Describe the outcome, expected skills, timing and compensation. New openings begin as private drafts.'} action={p.workspace.openings.length?<button className="button secondary" onClick={()=>{setQuery('');setOpeningFilter('all');}}>Clear filters</button>:admin?<button className="button primary" onClick={()=>setCreating(true)}>Create your first opening</button>:undefined}/></div>}</>}
  {admin?<><div className={s.sectionHead}><div><h2>{opening?'Applications for this opening':'Application pipeline'}</h2><p className={s.caption}>Review introductions, then share an invitation with accepted applicants.</p></div></div><div className={s.stages} aria-label="Filter applications by stage"><button aria-pressed={stage==='all'} onClick={()=>setStage('all')}>All <b>{applications.length}</b></button>{stages.map(item=><button key={item.id} aria-pressed={stage===item.id} onClick={()=>setStage(item.id)}>{item.name}<b>{applications.filter(a=>a.status===item.id).length}</b></button>)}</div><SearchField label="Search applicants" value={candidateQuery} onChange={setCandidateQuery} placeholder="Applicant, email or opening…"/>{candidates.length?<div className={s.list}>{candidates.map(a=><button className={s.applicationRow} key={a.id} onClick={()=>{setCandidate(a);setInvite('');setInviteSaved(false);setInviteDiscard(false);}}><Avatar name={applicantName(a)}/><span className={s.rowBody}><strong>{applicantName(a)} {a.agentId&&<Bot size={14} aria-label="Sponsored agent application"/>}</strong><small>{p.workspace.openings.find(o=>o.id===a.openingId)?.title} · {when(a.createdAt)}</small></span><Badge tone={tone(a.status)}>{stageName(a.status)}</Badge><ChevronRight size={17}/></button>)}</div>:<div className="panel"><Empty icon={Users} title={applications.length?'No applicants in this view':'No applications yet'} description={applications.length?'Change the stage or clear your search to see more introductions.':opening?.status==='draft'?'Review and publish this draft when you are ready to receive introductions.':'Applications to published openings appear here for administrator review.'} action={applications.length?<button className="button secondary" onClick={()=>{setStage('all');setCandidateQuery('');}}>Show all applications</button>:undefined}/></div>}</>:<Notice><strong>Applicant review is private to administrators.</strong><p>You can read company openings here. Ask an owner or administrator to publish roles and review introductions.</p></Notice>}
  {admin&&creating&&<Modal title="Create an opening" description="Start with a private draft. Review its public details before publishing." onClose={()=>setCreating(false)} wide><Form submit="Create draft opening" onSubmit={async f=>{const r=await api<{opening:Opening}>(`/api/companies/${p.company.id}/openings`,'POST',values(f));await p.refresh();setCreating(false);chooseOpening(r.opening.id);p.notify('Draft created. Review it before publishing.');}}><Field label="Opening title"><input name="title" required maxLength={160} placeholder="e.g. Creative editor for a short documentary"/></Field><Field label="Work, expectations & review criteria" hint="Include outcomes, required experience, timing and how contributions will be reviewed."><textarea name="description" required minLength={30} maxLength={12000} rows={6}/></Field><div className="grid two"><Field label="Who can apply?"><select name="type"><option value="either">People or agents</option><option value="human">People</option><option value="agent">Agents with a human sponsor</option></select></Field><Field label="Compensation"><select name="compensation"><option value="paid">Paid engagement</option><option value="volunteer">Volunteer / unpaid</option></select></Field></div><Field label="Budget / compensation details (optional)" hint="Include the amount, currency and whether it is hourly or fixed."><input name="budget" maxLength={160} placeholder="e.g. USD 2,000 fixed project, agreed directly"/></Field><Notice><p>Coatria records applications and invitations. Contracts, payments and work guarantees are agreed outside this release.</p></Notice></Form></Modal>}
  {admin&&transition&&p.workspace.openings.some(o=>o.id===transition.opening.id)&&<Modal title={transition.status==='published'?'Publish this opening?':transition.status==='closed'?'Close applications?':'Unpublish this opening?'} description={transition.opening.title} onClose={()=>{if(!busy)setTransition(null);}}><div className="stack"><p>{transition.status==='published'?'The company name, title, description, applicant type and compensation details will become visible in public opportunities.':transition.status==='closed'?'New applications will stop. Existing introductions remain available to review. You can reopen the opening later.':'The opening becomes a private draft and stops accepting new applications. Existing introductions remain available.'}</p>{transition.status==='published'&&<div className={s.reviewBox}><strong>{transition.opening.title}</strong><span>{p.company.name} · {audience(transition.opening.type)}</span><span>{transition.opening.compensation==='paid'?'Paid':'Volunteer / unpaid'} · {transition.opening.budget||'Compensation details not supplied'}</span></div>}{error&&<p role="alert" className="error-message">{error}</p>}<div className="row"><button className="button secondary" disabled={busy} onClick={()=>setTransition(null)}>Cancel</button><button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api(`/api/companies/${p.company.id}/openings/${transition.opening.id}`,'PATCH',{status:transition.status});await p.refresh();p.notify(transition.status==='published'?'Opening published. Applications are open.':'Opening status updated.');setTransition(null);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>{busy?'Updating…':transition.status==='published'?'Publish to opportunities':transition.status==='closed'?'Close applications':'Move to private draft'}</button></div></div></Modal>}
  {admin&&candidate&&p.workspace.applications.some(a=>a.id===candidate.id)&&<Modal title={applicantName(candidate)} description={p.workspace.openings.find(o=>o.id===candidate.openingId)?.title} onClose={closeCandidate}><div className="stack"><div className="row"><Badge tone={tone(candidate.status)}>{stageName(candidate.status)}</Badge><Badge>{candidate.agentId?'Sponsored agent application':'Person application'}</Badge></div><p className={s.caption}>{candidate.applicantEmail} · Applied {when(candidate.createdAt)}</p><p className={s.fullText}>{candidate.message}</p>{invite?<div className="secret-box"><Badge tone="warning">Shown once</Badge><h3>Share the workplace invitation</h3><p>Send this single-use invitation to the reviewed applicant. It is tied to their account. No email or payment was sent.</p><textarea aria-label="Accepted applicant invitation" readOnly value={invite} rows={3}/><CopyButton text={invite} label="Copy invitation"/><label className={s.check}><input type="checkbox" checked={inviteSaved} onChange={e=>{setInviteSaved(e.target.checked);setInviteDiscard(false);}}/> I saved the invitation for this applicant.</label>{inviteDiscard&&<div className={s.confirm} role="alert"><strong>This invitation is shown once.</strong><p>Copy it now, or create another invitation later from People.</p><button className="button secondary small" onClick={()=>{setCandidate(null);setInvite('');}}>Close without saving</button></div>}</div>:candidate.status==='accepted'?<Notice><strong>Application accepted</strong><p>The invitation was shown when this decision was saved. If another invitation is needed, an administrator can create one in People. Acceptance does not confirm that the applicant has joined.</p><a className="text-button" href="#people">Open People <ArrowRight size={14}/></a></Notice>:<Form submit="Save application decision" onSubmit={async f=>{setBusy(true);try{const result=await api<{application:Application;invitation?:{url:string}}>(`/api/companies/${p.company.id}/applications/${candidate.id}`,'PATCH',values(f));setCandidate({...candidate,...result.application});if(result.invitation)setInvite(result.invitation.url);await p.refresh();p.notify('Application decision saved.');}finally{setBusy(false);}}}><Field label="Decision"><select name="status" defaultValue={candidate.status==='declined'?'declined':'shortlisted'}><option value="shortlisted">Shortlist for consideration</option><option value="declined">Decline application</option><option value="accepted" disabled={candidate.userId===p.user.id}>Accept and create member invitation</option></select></Field><Notice><p>{candidate.userId===p.user.id?'Another administrator must accept your own application.':'Acceptance creates a single-use member invitation for this applicant. It does not add an agent automatically, share private skills or initiate a payment.'}</p></Notice></Form>}</div></Modal>}
 </div>;
}
