'use client';

import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {ArrowLeft,ArrowRight,Check,ChevronRight,Cloud,Download,File,FileImage,FileVideo,Folder,FolderOpen,FolderPlus,HardDrive,LockKeyhole,MoveRight,Pencil,RefreshCw,Search,Upload} from 'lucide-react';
import {api,when} from '@/lib/client';
import {canStreamStorageDownload,cancelStorageUpload,chooseStorageDownloadTarget,downloadStorageFile,readStorageUpload,STORAGE_BROWSER_BLOB_LIMIT,uploadStorageFile,type StorageDownloadAccess,type StorageUploadTicket,type StorageUploadStatus} from '@/lib/project-storage-client';
import {RUNPOD_STORAGE_REGIONS,type ProjectStorageConnection,type ProjectStorageFile,type ProjectStorageFolder,type ProjectStorageFolderPlan,type ProjectStorageListing} from '@/lib/project-storage-protocol';
import {Badge,Field,Loading,Modal} from './ui';
import s from './ProjectFilesPanel.module.css';

type Props={companyId:string;projectId:string;isAdmin:boolean};
type Entry=ProjectStorageFolder|ProjectStorageFile;
type Dialog={kind:'connect'}|{kind:'bind'}|{kind:'folder'}|{kind:'rename'|'move';item:Entry}|{kind:'plan'}|{kind:'upload';item?:ProjectStorageFile};
type UploadReservation={clientId:string;revision:number;parentId:string|null;name:string;fileId?:string;bytes:number;contentType:string};
type Upload={ticket:StorageUploadTicket;reservation:UploadReservation;file:globalThis.File;gatewayOrigin:string;sent:number;phase:string};
const layouts={
 'AI production':['01_Brief','02_References/Brand','02_References/Visual direction','03_Generations/Images','03_Generations/Video','03_Generations/Audio','04_Review','05_Delivery'],
 'VFX production':['01_Brief','02_References','03_Source/Footage','03_Source/Audio','04_Work/Compositing','04_Work/3D','05_Review','06_Delivery/Finals','06_Delivery/Manifests'],
};
const bytes=(value:number)=>{if(value<1024)return value+' B';const level=Math.min(Math.floor(Math.log(value)/Math.log(1024)),4);return (value/1024**level).toLocaleString(undefined,{maximumFractionDigits:1})+' '+['B','KiB','MiB','GiB','TiB'][level];};
function EntryIcon({item}:{item:Entry}){if(item.kind==='folder')return <Folder size={20}/>;return /\.(mp4|mov|webm|mxf)$/i.test(item.name)?<FileVideo size={20}/>:/\.(png|jpe?g|webp|exr|tiff?)$/i.test(item.name)?<FileImage size={20}/>:<File size={20}/>;}

/** Company changes remount the browser so stale responses cannot cross projects. */
export function ProjectFilesPanel(props:Props){return <ProjectFiles key={`${props.companyId}:${props.projectId}:${props.isAdmin}`} {...props}/>;}
function ProjectFiles({companyId,projectId,isAdmin}:Props){
 const base=`/api/companies/${companyId}/studio/projects/${projectId}/files`,connectionsPath=`/api/companies/${companyId}/storage-connections`;
 const [listing,setListing]=useState<ProjectStorageListing|null>(null),[connections,setConnections]=useState<ProjectStorageConnection[]>([]),[parentId,setParentId]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[notice,setNotice]=useState(''),[filter,setFilter]=useState(''),[dialog,setDialog]=useState<Dialog|null>(null),[connectionId,setConnectionId]=useState('');
 const [name,setName]=useState(''),[destination,setDestination]=useState<ProjectStorageListing|null>(null),[destinationId,setDestinationId]=useState<string|null>(null),[destinationLoading,setDestinationLoading]=useState(false);
 const [layout,setLayout]=useState<keyof typeof layouts|'Custom'>('AI production'),[paths,setPaths]=useState(layouts['AI production'].join('\n')),[plan,setPlan]=useState<ProjectStorageFolderPlan|null>(null);
 const [plans,setPlans]=useState<Omit<ProjectStorageFolderPlan,'folders'>[]>([]),[plansAfter,setPlansAfter]=useState<string|null>(null),[selectedFile,setSelectedFile]=useState<globalThis.File|null>(null),[upload,setUpload]=useState<Upload|null>(null),[downloadProgress,setDownloadProgress]=useState<{name:string;bytes:number;total:number}|null>(null);
 const transferController=useRef<AbortController|null>(null),uploadClientId=useRef(crypto.randomUUID()),reservationDraft=useRef<UploadReservation|null>(null),currentUpload=useRef<Upload|null>(null);
 currentUpload.current=upload;
 const alive=useRef(true),pending=useRef(false),ticket=useRef(0),destinationTicket=useRef(0),requests=useRef(new Map<string,string>()),connectionRequestId=useRef(crypto.randomUUID());
 const requestId=(operation:string,data:unknown)=>{const signature=operation+JSON.stringify(data);let value=requests.current.get(signature);if(!value){value=crypto.randomUUID();requests.current.set(signature,value);}return value;};
 const listPath=(folder:string|null,after?:string)=>base+'?'+new URLSearchParams({...folder?{parentId:folder}:{},...after?{after}:{}}).toString();
 const load=useCallback(async(folder:string|null,signal?:AbortSignal)=>{
  const seq=++ticket.current;setLoading(true);
  try{const [next,available]=await Promise.all([api<ProjectStorageListing>(base+(folder?'?parentId='+folder:''),'GET',undefined,{signal}),isAdmin?api<{connections:ProjectStorageConnection[]}>(connectionsPath,'GET',undefined,{signal}):Promise.resolve({connections:[]})]);const pendingPlans=next.binding&&isAdmin?await api<{plans:Omit<ProjectStorageFolderPlan,'folders'>[];page:{nextAfter:string|null}}>(base+'/folder-plans?limit=20','GET',undefined,{signal}):{plans:[],page:{nextAfter:null}};if(alive.current&&seq===ticket.current){setListing(next);setConnections(available.connections);setPlans(pendingPlans.plans);setPlansAfter(pendingPlans.page.nextAfter);setParentId(folder);setFilter('');}}
  finally{if(alive.current&&seq===ticket.current)setLoading(false);}
 },[base,connectionsPath,isAdmin]);
 useEffect(()=>{alive.current=true;const controller=new AbortController();void load(null,controller.signal).catch(e=>{if(!controller.signal.aborted&&alive.current)setError(e instanceof Error?e.message:'Project files could not be loaded.');});return()=>{alive.current=false;ticket.current++;destinationTicket.current++;controller.abort();transferController.current?.abort();currentUpload.current=null;reservationDraft.current=null;};},[load]);
 async function act(action:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');setConflict(false);try{await action();}catch(e){if(alive.current){setError(e instanceof Error?e.message:'This change could not be saved. Try again.');setConflict((e as {status?:number}).status===409);}}finally{pending.current=false;if(alive.current)setBusy(false);}}
 function freshPlan(){for(const key of requests.current.keys())if(key.startsWith('plan{'))requests.current.delete(key);setPlan(null);}
 function close(){if(busy)return;setDialog(null);setError('');setConflict(false);setPlan(null);destinationTicket.current++;setDestination(null);}
 function open(value:Dialog){setError('');setConflict(false);setNotice('');setDialog(value);if(value.kind==='folder')setName('');if(value.kind==='rename')setName(value.item.name);if(value.kind==='bind')setConnectionId(listing?.binding?.connectionId??connections.find(item=>item.status==='configured')?.id??'');if(value.kind==='connect')connectionRequestId.current=crypto.randomUUID();if(value.kind==='plan')freshPlan();if(value.kind==='upload'){setSelectedFile(null);uploadClientId.current=crypto.randomUUID();reservationDraft.current=null;}if(value.kind==='move'){setDestinationId(value.item.parentId);void loadDestination(value.item.parentId);}}
 async function navigate(folder:string|null){await act(async()=>{await load(folder);setNotice('');});}
 async function loadDestination(folder:string|null){const seq=++destinationTicket.current;setDestinationLoading(true);try{const next=await api<ProjectStorageListing>(listPath(folder));if(alive.current&&seq===destinationTicket.current){setDestination(next);setDestinationId(folder);}}catch(e){if(alive.current&&seq===destinationTicket.current)setError(e instanceof Error?e.message:'Destination folders could not be loaded.');}finally{if(alive.current&&seq===destinationTicket.current)setDestinationLoading(false);}}
 async function refresh(){await act(async()=>{await load(parentId);setNotice('Project files refreshed.');});}
 const binding=listing?.binding,canOrganize=isAdmin&&binding?.connection.status==='configured',items=listing?.items.filter(item=>item.name.toLocaleLowerCase().includes(filter.toLocaleLowerCase()))??[];
 const transferReason=listing?.transfers.available===false?listing.transfers.message:listing?.transfers.available===true?'Files transfer through the authenticated storage service.':'Connect project storage to check file transfer availability.';
 const dialogError=error&&<div className={s.error} role="alert"><p>{error}</p>{conflict&&<p>Another change may have been saved. Refresh project files, then review your change again. Your form is kept open.</p>}</div>;
 async function connect(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);await act(async()=>{await api(connectionsPath,'POST',{clientId:connectionRequestId.current,name:String(data.get('name')),region:String(data.get('region')),volumeId:String(data.get('volumeId')),accessKeyId:String(data.get('accessKeyId')),secretAccessKey:String(data.get('secretAccessKey'))});form.reset();await load(parentId);setDialog({kind:'bind'});setNotice('Connection saved. Choose it below to organize this project.');});}
 async function bind(){if(!connectionId)return;await act(async()=>{const input={revision:binding?.revision??0,connectionId};await api(base.slice(0,-6)+'/storage','PUT',{...input,clientId:requestId('bind',input)});await load(null);setDialog(null);setNotice('This project is linked to its storage connection.');});}
 async function saveFolder(){if(!binding||!dialog)return;await act(async()=>{const editing=dialog.kind==='rename'?dialog.item:null,input={revision:binding.revision,parentId:editing?editing.parentId:parentId,name};await api(editing?base+'/'+(editing.kind==='folder'?'folders':'items')+'/'+editing.id:base+'/folders',editing?'PATCH':'POST',{...input,clientId:requestId(editing?'rename:'+editing.id:'folder',input)});await load(parentId);setDialog(null);setNotice(editing?'Name updated. File contents and versions are unchanged.':'Folder created.');});}
 async function move(){if(!binding||dialog?.kind!=='move')return;await act(async()=>{const item=dialog.item,input={revision:binding.revision,parentId:destinationId,name:item.name};await api(base+'/'+(item.kind==='folder'?'folders':'items')+'/'+item.id,'PATCH',{...input,clientId:requestId('move:'+item.id,input)});await load(parentId);setDialog(null);setNotice('Moved in the project library. Stored file contents and versions are unchanged.');});}
 async function preview(){if(!binding)return;await act(async()=>{const input={revision:binding.revision,paths:paths.split('\n').map(value=>value.trim()).filter(Boolean)};const result=await api<{plan:ProjectStorageFolderPlan}>(base+'/folder-plans','POST',{...input,clientId:requestId('plan',input)});setPlan(result.plan);});}
 async function applyPlan(){if(!plan)return;await act(async()=>{const input={revision:plan.bindingRevision,planHash:plan.planHash};await api(base+'/folder-plans/'+plan.id+'/apply','POST',{...input,clientId:requestId('apply:'+plan.id,input)});await load(parentId);setDialog(null);setPlan(null);setNotice('The reviewed folder plan is now in your project library.');});}
 function acceptStatus(status:StorageUploadStatus){setUpload(current=>current?{...current,sent:status.upload.uploadedBytes,phase:status.upload.status}:null);if(status.upload.status==='ready')setNotice('Your file is stored and its complete bytes have been verified.');}
 function uploadContext(value:Upload,signal?:AbortSignal){return {gatewayOrigin:value.gatewayOrigin,signal,renew:async()=>{const renewed=await api<{upload:StorageUploadTicket}>(base+'/uploads','POST',value.reservation,{signal});return renewed.upload;},onRenew:(renewed:StorageUploadTicket)=>{if(!alive.current)return;if(currentUpload.current?.ticket.id===value.ticket.id)currentUpload.current={...currentUpload.current,ticket:renewed};setUpload(current=>current?.ticket.id===value.ticket.id?{...current,ticket:renewed}:current);}};}
 async function continueUpload(value:Upload){const controller=new AbortController();transferController.current=controller;try{const status=await uploadStorageFile(value.file,value.ticket,{...uploadContext(value,controller.signal),onProgress:(sent,phase)=>{if(alive.current)setUpload(current=>current?{...current,sent,phase}:null);}});if(alive.current){acceptStatus(status);await load(parentId);}}catch(e){if(alive.current)setUpload(current=>current?{...current,phase:'needs_check'}:null);if(e instanceof Error&&e.name==='AbortError')throw Error('Local upload stopped. Check status before resuming; already stored parts are retained.');throw e;}finally{if(transferController.current===controller)transferController.current=null;}}
 async function startUpload(){if(!binding||!listing?.transfers.available||!selectedFile||dialog?.kind!=='upload')return;const file=selectedFile,availability=listing.transfers,item=dialog.item;if(file.size<1||file.size>availability.maxFileBytes){setError('Choose a non-empty file up to '+bytes(availability.maxFileBytes)+'.');return;}await act(async()=>{const reservation=reservationDraft.current??{clientId:uploadClientId.current,revision:binding.revision,parentId:item?.parentId??parentId,name:item?.name??file.name,...item?{fileId:item.id}:{},bytes:file.size,contentType:/^[a-z0-9][a-z0-9.+-]*\/[a-z0-9][a-z0-9.+-]*$/.test(file.type)?file.type:'application/octet-stream'};reservationDraft.current=reservation;const result=await api<{upload:StorageUploadTicket}>(base+'/uploads','POST',reservation);const next={ticket:result.upload,reservation,file,gatewayOrigin:availability.gatewayOrigin,sent:0,phase:'starting'};setUpload(next);currentUpload.current=next;setDialog(null);await continueUpload(next);});}
 async function inspectUpload(){if(!upload)return;await act(async()=>{const current=await readStorageUpload(upload.ticket,uploadContext(upload));acceptStatus(current);await load(parentId);});}
 async function download(item:ProjectStorageFile){if(!item.latestVersion?.verified||!listing?.transfers.available)return;if(!canStreamStorageDownload()&&item.latestVersion.bytes>STORAGE_BROWSER_BLOB_LIMIT){setError('This file is too large for this browser’s in-memory download. Use a browser with a file save picker, or the authenticated storage API described below.');return;}const destination=chooseStorageDownloadTarget(item.name);await act(async()=>{const target=await destination,controller=new AbortController();transferController.current=controller;try{const result=await api<{access:StorageDownloadAccess}>(base+'/versions/'+item.latestVersion!.id+'/access','POST',{clientId:crypto.randomUUID(),disposition:'attachment'});setDownloadProgress({name:item.name,bytes:0,total:result.access.bytes});const finished=await downloadStorageFile(result.access,target,{gatewayOrigin:listing.transfers.available?listing.transfers.gatewayOrigin:'',signal:controller.signal,onProgress:received=>{if(alive.current)setDownloadProgress({name:item.name,bytes:received,total:result.access.bytes});}});if(finished.blob){const url=URL.createObjectURL(finished.blob),link=document.createElement('a');link.href=url;link.download=item.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}setNotice(target?'File saved to your chosen location.':'Your browser download is ready.');}catch(e){await target?.abort(e).catch(()=>{});throw e;}finally{setDownloadProgress(null);if(transferController.current===controller)transferController.current=null;}});}
 useEffect(()=>{if(upload?.phase!=='verifying')return;const current=upload,controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const active=currentUpload.current?.ticket.id===current.ticket.id?currentUpload.current:current;const value=await readStorageUpload(active.ticket,uploadContext(active,controller.signal));if(controller.signal.aborted||!alive.current)return;acceptStatus(value);if(value.upload.status==='verifying')timer=setTimeout(()=>void poll(),5000);else await load(parentId);}catch(e){if(!controller.signal.aborted&&alive.current){setError(e instanceof Error?e.message:'Verification status could not be checked.');setUpload(value=>value?{...value,phase:'needs_check'}:null);}}};timer=setTimeout(()=>void poll(),3000);return()=>{clearTimeout(timer);controller.abort();};},[upload?.ticket.id,upload?.phase,load,parentId]);
 const activeUpload=upload&&!['ready','cancelled','failed'].includes(upload.phase),canTransfer=!!listing?.transfers.available&&binding?.connection.status==='configured';
 const pendingPlans=plans.filter(value=>!value.applied&&value.bindingRevision===binding?.revision&&Date.parse(value.expiresAt)>Date.now());
 return <section className={s.panel} aria-label="Project files">
  <header className={s.header}><div><span className="eyebrow">YOUR PRODUCTION LIBRARY</span><h2>A place for every project file.</h2><p>Keep briefs, references, working files and delivery versions together.</p></div><button className="button secondary small" disabled={busy||loading} onClick={()=>void refresh()}><RefreshCw size={15}/>Refresh files</button></header>
  {!dialog&&dialogError}{notice&&<p className={s.notice} role="status"><Check size={16}/>{notice}</p>}
  {upload&&<div className={s.transfer} aria-label="File upload status"><div className={s.transferHeading}><div><strong>{upload.file.name}</strong><p>{upload.phase==='ready'?'Stored and verified':upload.phase==='verifying'?'All parts sent · Verifying the complete stored file':upload.phase==='needs_check'?'Transfer paused · Check status before resuming':upload.phase==='cancelled'?'Upload cancelled':upload.phase==='failed'?'Upload failed':upload.phase==='uncertain'?'Transfer outcome needs review':'Uploading file parts'} · {bytes(upload.sent)} / {bytes(upload.file.size)}</p></div><Badge tone={upload.phase==='ready'?'good':upload.phase==='needs_check'||upload.phase==='uncertain'?'warning':''}>{upload.phase==='ready'?'Verified':upload.phase.replaceAll('_',' ')}</Badge></div><progress max={upload.file.size} value={upload.sent} aria-label="File bytes sent"/>{upload.phase==='verifying'&&<p className={s.small}>The library will mark this version ready after the transfer service reads back and verifies every byte. Keep this page open to follow its status.</p>}<div className={s.actions}>{busy&&transferController.current?<button className="button secondary small" onClick={()=>transferController.current?.abort()}>Pause local transfer</button>:<>{activeUpload&&<button className="button secondary small" disabled={busy} onClick={()=>void inspectUpload()}>Check status</button>}{['uploading','needs_check','allocated'].includes(upload.phase)&&<button className="button secondary small" disabled={busy} onClick={()=>void act(()=>continueUpload(upload))}>Resume this file</button>}{activeUpload&&<button className="button secondary small" disabled={busy} onClick={()=>void act(async()=>{await cancelStorageUpload(upload.ticket,uploadContext(upload));setUpload(value=>value?{...value,phase:'cancelled'}:null);await load(parentId);})}>Cancel upload</button>}{!activeUpload&&<button className="button secondary small" disabled={busy} onClick={()=>setUpload(null)}>Dismiss</button>}</>}</div><p className={s.small}>This page holds the transfer access in memory. Closing it stops browser uploads; no transfer key or original file is saved in browser storage.</p></div>}
  {downloadProgress&&<div className={s.transfer} role="status"><strong>Saving {downloadProgress.name}</strong><progress max={downloadProgress.total} value={downloadProgress.bytes} aria-label="File bytes received"/><span>{bytes(downloadProgress.bytes)} / {bytes(downloadProgress.total)}</span><button className="button secondary small" onClick={()=>transferController.current?.abort()}>Cancel download</button></div>}
  {loading&&!listing?<Loading label="Opening project files"/>:listing&&<>
   <div className={s.connectionStrip}><span className={s.storageIcon}><HardDrive size={22}/></span><div><strong>{binding?binding.connection.name:'Connect a home for this project'}</strong><p>{binding?`Runpod · ${binding.connection.region} · Volume ${binding.connection.volumeId}`:'Use an existing Runpod network volume. Folder organization and file transfers have separate status.'}</p></div><Badge tone={binding?.connection.status==='revoked'?'warning':''}>{binding?(binding.connection.status==='revoked'?'Connection revoked':'Connection saved'):'Storage not linked'}</Badge>{isAdmin&&<button className="button secondary small" disabled={busy} onClick={()=>open(connections.some(item=>item.status==='configured')?{kind:'bind'}:{kind:'connect'})}>{binding?'Manage connection':'Connect storage'}<ChevronRight size={14}/></button>}</div>
   {!binding?<div className={s.empty}><span><Cloud size={29}/></span><h3>Your project library starts here</h3><p>{isAdmin?'Connect storage, then choose a folder structure for your production. Existing files on the volume are not automatically imported.':'An administrator can link a storage volume to this project.'}</p>{isAdmin&&<button className="button primary" disabled={busy} onClick={()=>open(connections.some(item=>item.status==='configured')?{kind:'bind'}:{kind:'connect'})}>Set up project storage<ArrowRight size={16}/></button>}</div>:<>
    {!!pendingPlans.length&&<div className={s.pendingPlans}><div><FolderPlus size={18}/><strong>Folder plans ready for review</strong><span>Prepared by your team or agents</span></div>{pendingPlans.map(value=><button className="button secondary small" key={value.id} disabled={busy} onClick={()=>void act(async()=>{const result=await api<{plan:ProjectStorageFolderPlan}>(base+'/folder-plans/'+value.id);setPlan(result.plan);setPaths(result.plan.folders.map(folder=>folder.path).join('\n'));setLayout('Custom');setDialog({kind:'plan'});})}>Review {value.createsFolderCount} folders · {when(value.createdAt)}</button>)}</div>}
    <>{plansAfter&&<button className="button secondary small" disabled={busy} onClick={()=>void act(async()=>{const next=await api<{plans:Omit<ProjectStorageFolderPlan,'folders'>[];page:{nextAfter:string|null}}>(base+'/folder-plans?limit=20&after='+plansAfter);setPlans(current=>[...current,...next.plans.filter(item=>!current.some(existing=>existing.id===item.id))]);setPlansAfter(next.page.nextAfter);})}>Load more folder plans</button>}</><div className={s.toolbar}><nav aria-label="Project folder breadcrumb" className={s.breadcrumbs}><button disabled={busy||loading} onClick={()=>void navigate(null)} aria-current={!parentId?'page':undefined}><FolderOpen size={16}/>Project files</button>{listing.breadcrumbs.map((crumb,index)=><span key={crumb.id}><ChevronRight size={13}/><button disabled={busy||loading} onClick={()=>void navigate(crumb.id)} aria-current={index===listing.breadcrumbs.length-1?'page':undefined}>{crumb.name}</button></span>)}</nav><div className={s.actions}><button className="button secondary small" disabled={busy||!canOrganize} onClick={()=>open({kind:'plan'})}>Plan folders</button><button className="button secondary small" disabled={busy||!canOrganize} onClick={()=>open({kind:'folder'})}><FolderPlus size={15}/>New folder</button><button className="button primary small" disabled={busy||!isAdmin||!canTransfer||!!activeUpload} title={transferReason} aria-describedby="project-transfer-status" onClick={()=>open({kind:'upload'})}><Upload size={15}/>Upload files</button></div></div>
    <p id="project-transfer-status" className={s.transferStatus}><LockKeyhole size={15}/><span>{transferReason} Folder changes organize this library; they do not move or upload source bytes.</span></p>
    <div className={s.findBar}><label className={s.search}><Search size={15}/><span className="sr-only">Search loaded files and folders</span><input type="search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Find in loaded items…"/></label><span>{listing.items.length} loaded item{listing.items.length===1?'':'s'}{listing.page.hasMore?' · More available':''}</span></div>
    <div className={s.fileList} aria-busy={loading}><div className={s.listHead}><span>Name</span><span>Version & size</span><span>Created</span><span className="sr-only">Actions</span></div>{items.map(item=><article className={s.row} key={item.id} aria-label={`${item.kind==='folder'?'Folder':'File'} ${item.name}`}><div className={s.entry}><span className={item.kind==='folder'?s.folderIcon:s.fileIcon}><EntryIcon item={item}/></span>{item.kind==='folder'?<button className={s.folderName} disabled={busy||loading} onClick={()=>void navigate(item.id)}>{item.name}<ChevronRight size={14}/></button>:<div><strong>{item.name}</strong><small>{item.latestVersion?.verified?'Verified file version':'Awaiting a verified upload'}</small></div>}</div><div className={s.version}>{item.kind==='folder'?<span>Folder</span>:item.latestVersion?<><span>v{item.latestVersion.version} · {bytes(item.latestVersion.bytes)}</span><small>{item.latestVersion.verified?'Verified':'Not verified'}</small></>:<span>No version yet</span>}</div><time className={s.date} dateTime={item.createdAt}>{when(item.createdAt)}</time><div className={s.rowActions}>{item.kind==='file'&&<><button className="icon-button" disabled={busy||!canTransfer||!item.latestVersion?.verified} title={transferReason} aria-label={'Download '+item.name} onClick={()=>void download(item)}><Download size={16}/></button>{isAdmin&&<button className="icon-button" disabled={busy||!canTransfer||!!activeUpload} title="Upload a new version" aria-label={'Upload new version of '+item.name} onClick={()=>open({kind:'upload',item})}><Upload size={15}/></button>}</>}{isAdmin&&<><button className="icon-button" disabled={busy||!canOrganize} title="Rename" aria-label={'Rename '+item.name} onClick={()=>open({kind:'rename',item})}><Pencil size={15}/></button><button className="icon-button" disabled={busy||!canOrganize} title="Move" aria-label={'Move '+item.name} onClick={()=>open({kind:'move',item})}><MoveRight size={16}/></button></>}</div></article>)}{!items.length&&<div className={s.folderEmpty}><FolderOpen size={27}/><strong>{filter?'No loaded items match':'Make room for the work ahead'}</strong><p>{filter?'Try another name or load the next page.':'Create a folder here, or preview a production folder plan.'}</p></div>}</div>
    {listing.page.hasMore&&<button className="button secondary small" disabled={busy||loading} onClick={()=>void act(async()=>{const next=await api<ProjectStorageListing>(listPath(parentId,listing.page.nextAfter!));if(next.binding?.revision!==listing.binding?.revision){await load(parentId);setNotice('The library changed. Its latest contents are shown.');return;}setListing({...next,items:[...listing.items,...next.items.filter(item=>!listing.items.some(existing=>existing.id===item.id))]});})}>Load more items</button>}
    {canTransfer&&<details className={s.apiHelp}><summary>Large file downloads and agent access</summary><p>Use a browser with a file save picker to stream large files directly to disk. Other browsers can download files up to 128 MiB here.</p><p>Authenticated company sessions use <code>POST {base}/versions/:versionId/access</code> to request a short-lived file address and Authorization header. Stream that authenticated response directly to a destination file; keep the returned access private.</p><a href="/api/agent/openapi" target="_blank" rel="noreferrer">View the storage API contract<ArrowRight size={13}/></a></details>}
   </>}
  </>}
  {error&&!listing&&<button className="button secondary" disabled={busy||loading} onClick={()=>void refresh()}>Try loading files again</button>}
  {dialog&&<Modal title={dialog.kind==='connect'?'Connect Runpod storage':dialog.kind==='bind'?'Choose project storage':dialog.kind==='folder'?'Create a folder':dialog.kind==='rename'?'Rename '+dialog.item.name:dialog.kind==='move'?'Move '+dialog.item.name:dialog.kind==='upload'?dialog.item?'Upload a new file version':'Upload a project file':plan?'Review your folder plan':'Plan the project library'} description={dialog.kind==='connect'?'Link an existing network volume with its Runpod S3 credentials.':dialog.kind==='plan'?'See every folder before applying the structure.':undefined} onClose={close} wide={dialog.kind==='plan'}>
   {dialogError}{conflict&&<button className="button secondary small" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={14}/>Refresh project files</button>}
   {dialog.kind==='connect'&&<form className={s.form} onSubmit={event=>void connect(event)} autoComplete="off" onChange={()=>{connectionRequestId.current=crypto.randomUUID();}}><Field label="Connection name"><input name="name" required maxLength={160} placeholder="Studio production storage"/></Field><div className={s.formGrid}><Field label="Runpod volume ID"><input name="volumeId" required minLength={3} maxLength={80} placeholder="Existing network volume ID" spellCheck={false}/></Field><Field label="Storage region"><select name="region" required defaultValue="US-NC-2">{RUNPOD_STORAGE_REGIONS.map(region=><option key={region}>{region}</option>)}</select></Field></div><Field label="S3 access key ID" hint="Use the Runpod S3 key that starts with user_. Your general Runpod API key is different."><input name="accessKeyId" type="password" autoComplete="new-password" required minLength={6} maxLength={256} placeholder="user_…" spellCheck={false}/></Field><Field label="S3 secret access key"><input name="secretAccessKey" type="password" autoComplete="new-password" required minLength={5} maxLength={512} placeholder="rps_…" spellCheck={false}/></Field><p className={s.info}><LockKeyhole size={17}/>Credentials are sent to Coatria’s server and stored encrypted. They are never added to this browser’s local storage. Saving a connection does not create paid storage or prove a file transfer works.</p><div className={s.actions}><button className="button primary" disabled={busy}>{busy?'Saving connection…':'Save connection'}</button><button className="button secondary" type="button" disabled={busy} onClick={close}>Cancel</button></div></form>}
   {dialog.kind==='bind'&&<div className={s.form}><Field label="Company storage connection"><select value={connectionId} onChange={e=>setConnectionId(e.target.value)}><option value="">Choose a saved connection</option>{connections.filter(item=>item.status==='configured').map(item=><option key={item.id} value={item.id}>{item.name} · {item.region}</option>)}</select></Field><p className={s.info}>The project uses its own library inside this volume. Existing files elsewhere on the volume stay outside the library.</p><div className={s.actions}><button className="button primary" disabled={busy||!connectionId} onClick={()=>void bind()}>Use this connection</button><button className="button secondary" disabled={busy} onClick={()=>open({kind:'connect'})}>Add a connection</button></div></div>}
   {dialog.kind==='upload'&&<form className={s.form} onSubmit={e=>{e.preventDefault();void startUpload();}}>{dialog.item&&<p className={s.info}>Add a new version of <strong>{dialog.item.name}</strong>. Earlier versions remain stored.</p>}<Field label="File to upload" hint={listing?.transfers.available?`Up to ${bytes(listing.transfers.maxFileBytes)}. The browser sends bounded parts directly to the transfer service.`:transferReason}><input type="file" required disabled={busy||!canTransfer} onChange={e=>{setSelectedFile(e.target.files?.[0]??null);uploadClientId.current=crypto.randomUUID();reservationDraft.current=null;}}/></Field>{selectedFile&&<p className={s.small}>{selectedFile.name} · {bytes(selectedFile.size)}</p>}<p className={s.info}>Keep this page open while uploading. The complete stored bytes are verified before the version becomes downloadable. Uploading does not approve the file for production or client delivery.</p><div className={s.actions}><button className="button primary" disabled={busy||!canTransfer||!selectedFile}>Upload this file</button><button className="button secondary" type="button" disabled={busy} onClick={close}>Cancel</button></div></form>}
   {(dialog.kind==='folder'||dialog.kind==='rename')&&<form className={s.form} onSubmit={e=>{e.preventDefault();void saveFolder();}}><Field label={dialog.kind==='folder'?'Folder name':'New name'} hint="Use a name without / or \\ separators."><input required autoFocus maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></Field>{dialog.kind==='rename'&&<p className={s.info}>Renaming changes its place in the library. Stored contents and version history are preserved.</p>}<div className={s.actions}><button className="button primary" disabled={busy||!name.trim()}>{dialog.kind==='folder'?'Create folder':'Save name'}</button><button type="button" className="button secondary" disabled={busy} onClick={close}>Cancel</button></div></form>}
   {dialog.kind==='move'&&<div className={s.form}><p className={s.info}>Choose the destination for <strong>{dialog.item.name}</strong>. This changes the library location without copying file bytes.</p><nav className={s.breadcrumbs} aria-label="Move destination breadcrumb"><button disabled={destinationLoading||busy} onClick={()=>void loadDestination(null)}>Project files</button>{destination?.breadcrumbs.map(crumb=><span key={crumb.id}><ChevronRight size={13}/><button disabled={destinationLoading||busy} onClick={()=>void loadDestination(crumb.id)}>{crumb.name}</button></span>)}</nav><div className={s.destinations} aria-busy={destinationLoading}>{destinationLoading?<Loading label="Loading folders"/>:destination?.items.filter(item=>item.kind==='folder'&&item.id!==dialog.item.id).map(item=><button key={item.id} disabled={busy} onClick={()=>void loadDestination(item.id)}><Folder size={18}/>{item.name}<ChevronRight size={15}/></button>)}{!destinationLoading&&!destination?.items.some(item=>item.kind==='folder'&&item.id!==dialog.item.id)&&<p>No subfolders here. You can move this item into the current folder.</p>}</div>{destination?.page.hasMore&&<button className="button secondary small" disabled={busy||destinationLoading} onClick={()=>void act(async()=>{const next=await api<ProjectStorageListing>(listPath(destinationId,destination.page.nextAfter!));setDestination({...next,items:[...destination.items,...next.items]});})}>Load more destination folders</button>}<div className={s.actions}><button className="button primary" disabled={busy||destinationLoading||!destination||destinationId===dialog.item.parentId} onClick={()=>void move()}>Move here</button><button className="button secondary" disabled={busy} onClick={close}>Cancel</button></div></div>}
   {dialog.kind==='plan'&&<div className={s.form}>{!plan?<><Field label="Folder structure"><select value={layout} onChange={e=>{const next=e.target.value as keyof typeof layouts|'Custom';setLayout(next);if(next!=='Custom')setPaths(layouts[next].join('\n'));}}>{Object.keys(layouts).map(value=><option key={value}>{value}</option>)}<option>Custom</option></select></Field><Field label="Folder paths" hint="One relative path per line. A / creates a nested folder. You can edit the proposed structure."><textarea rows={9} spellCheck={false} value={paths} maxLength={24000} onChange={e=>{setPaths(e.target.value);setLayout('Custom');}}/></Field><button className="button primary" disabled={busy||!paths.trim()} onClick={()=>void preview()}>Preview folder plan<ArrowRight size={15}/></button></>:<><div className={s.planSummary}><FolderPlus size={23}/><div><strong>{plan.createsFolderCount} new folder{plan.createsFolderCount===1?'':'s'}</strong><p>Existing folders are kept. This plan creates library folders; it does not upload files or create provider storage.</p></div></div><ul className={s.planTree}>{plan.folders.map(folder=><li key={folder.path}><Folder size={15}/><span>{folder.path}</span><Badge>{folder.exists?'Already exists':'Create'}</Badge></li>)}</ul><p className={s.small}>Review expires {when(plan.expiresAt)}. A change to this library requires a fresh plan.</p>{plan.bindingRevision!==binding?.revision&&<p className={s.error} role="status">The library changed after this preview. Choose Edit structure, then preview again before applying.</p>}<div className={s.actions}><button className="button primary" disabled={busy||plan.applied||plan.bindingRevision!==binding?.revision||Date.parse(plan.expiresAt)<=Date.now()} onClick={()=>void applyPlan()}>{plan.applied?'Already applied':'Apply this folder plan'}</button><button className="button secondary" disabled={busy} onClick={()=>{freshPlan();setError('');setConflict(false);}}><ArrowLeft size={14}/>Edit structure</button></div></>}</div>}
  </Modal>}
 </section>;
}
