'use client';

import {useState,type FormEvent} from 'react';
import {Bot,Check,GitBranch,Pause,RefreshCw,Settings2,ShieldCheck} from 'lucide-react';
import type {WorkspaceProps} from '@/app/page';
import type {StudioReadableProjectDetail} from '@/lib/studio-protocol';
import type {StudioCoordinationPolicy as Policy,StudioCoordinationSnapshot as Coordination} from '@/lib/studio-coordination-protocol';
import {Field,Loading,Modal} from './ui';
import {useStudioMutation,useStudioResource} from './studio-hooks';
import s from './StudioWorkspace.module.css';

type Props={p:WorkspaceProps;detail:StudioReadableProjectDetail;onSchedule:()=>void};

export function StudioCoordinationPanel({p,detail,onSchedule}:Props){
 const path=`/api/companies/${p.company.id}/studio/projects/${detail.project.id}/coordination`;
 const resource=useStudioResource<Coordination>(path),mutation=useStudioMutation(),[editing,setEditing]=useState(false);
 const admin=['owner','admin'].includes(p.company.role),policy=resource.data?.policy;
 const coordinator=detail.roles.find(role=>role.agentId===policy?.coordinatorAgentId);
 const status=policy?.effectiveStatus||policy?.status||'not configured';
 const correctionBlock=!policy?.mediaRework?'Internal QC corrections are off. Review the delegation policy to enable them.':policy.effectiveStatus!=='active'?policy.blocker||'The delegation policy must be active before the coordinator can request a correction.':policy.remainingRuns<1?'The existing specialist run allowance is exhausted.':null;
 return <>
  <div className={s.heading}><div><h2>Let the coordinator bring the team together.</h2><p>Ready work goes to its assigned specialist. Every handoff keeps its task, run history, and review requirements.</p></div><button className="icon-button" aria-label="Refresh coordination" onClick={()=>void resource.reload()}><RefreshCw size={16}/></button></div>
  {resource.loading?<Loading label="Loading project coordination"/>:resource.data&&<>
   <div className={s.metrics}>
    <div className={s.metric}><span>Coordination</span><strong style={{fontSize:20,textTransform:'capitalize'}}>{status.replaceAll('_',' ')}</strong><small>{coordinator?.agentName||'Choose a production coordinator'}</small></div>
    <div className={s.metric}><span>Specialist runs remaining</span><strong>{policy?.remainingRuns??'—'}</strong><small>Within this project’s approved run allowance</small></div>
    <div className={s.metric}><span>Runs already started</span><strong>{policy?.runsStarted??0}</strong><small>Failed and cancelled runs still count</small></div>
    <div className={s.metric}><span>Concurrent specialist runs</span><strong>{policy?.maxConcurrentRuns??'—'}</strong><small>The connected host may have a lower limit</small></div>
   </div>
   <section className={s.section}>
    <div className={s.heading}><div><h3>Project delegation policy</h3><p>{policy?`Expires ${new Date(policy.expiresAt).toLocaleString()}. The allowance survives policy edits.`:'Review who can delegate, which roles can receive work, and how many runs the project can start.'}</p></div>{admin&&detail.project.status!=='delivered'&&<button className="button primary small" onClick={()=>setEditing(true)}><Settings2 size={14}/>{policy?'Review policy':'Set delegation policy'}</button>}</div>
    {policy?.blocker&&<p className={s.notice}>{policy.blocker}</p>}
    {admin&&policy?.status==='active'&&<button className="button secondary small" style={{marginTop:14}} disabled={mutation.busy} onClick={()=>void mutation.mutate(path,{revision:policy.revision,coordinatorAgentId:policy.coordinatorAgentId,allowedRoleKeys:policy.allowedRoleKeys,status:'paused',maxRuns:policy.maxRuns,maxConcurrentRuns:policy.maxConcurrentRuns,expiresAt:policy.expiresAt,...policy.planningRework!==undefined?{planningRework:policy.planningRework}:{},...policy.mediaRework!==undefined?{mediaRework:policy.mediaRework}:{},...policy.referencePreparationProfile?{referencePreparationProfile:policy.referencePreparationProfile}:{},...policy.generatedContinuations!==undefined?{generatedContinuations:policy.generatedContinuations}:{},...policy.coordinatorGeneration!==undefined?{coordinatorGeneration:policy.coordinatorGeneration}:{}},async()=>{await resource.reload();p.notify('Delegation paused. Delegated requests lose authority on their next API or lease check.');},'PUT')}><Pause size={14}/>{mutation.busy?'Pausing…':'Pause delegation'}</button>}
    {policy&&<ul className={s.skills} style={{marginTop:16}}>{policy.allowedRoleKeys.map(key=><li key={key}>{detail.roles.find(role=>role.key===key)?.title||key}</li>)}</ul>}
    <p className={s.muted}>Planning corrections: <strong>{policy?.planningRework?'Opted in':'Off'}</strong>. A completed changes-requested review can queue one new estimate or breakdown pass within the same run allowance. A new review is required; this permits no generation retry.</p>
    {detail.project.contractVersion===2&&<p className={s.muted}>Internal QC corrections: <strong>{policy?.mediaRework?'Opted in':'Off'}</strong>. One correction per rejected output version uses the same specialist run allowance and expiry. A new review of the same rejected version does not grant another attempt. Every new Higgsfield request still needs separate human credit approval.</p>}
    {detail.project.contractVersion===2&&<p className={s.muted}>Coordinator-owned generation: <strong>{policy?.coordinatorGeneration?'Opted in':'Off'}</strong>. A separate generation request waits for the coordinator’s current cycle to finish successfully and uses the existing specialist run limits. Provider spending still requires approval.</p>}
    {detail.project.contractVersion===2&&<p className={s.muted}>Verified generated output continuations: <strong>{policy?.generatedContinuations?'Opted in':'Off'}</strong>. Each continuation uses the existing specialist run allowance; an active policy and verified source are still required. It adds no generation, file transfer, or review authority.</p>}
    {detail.project.contractVersion===2&&<p className={s.muted}>Prepared image reference selection: <strong>{policy?.referencePreparationProfile?'Opted in':'Off'}</strong>. A separate specialist selects existing verified images. Inspection remains subject to this exact active policy, even after the task finishes. This does not resize, strip metadata, approve sharing or generate media.</p>}
    <p className={s.muted}>The coordinator can request existing work only after its dependencies and approval gates are satisfied. Changes to reviewed agents or assignments require a new policy review.</p>
    <div className={s.notice}><ShieldCheck size={17}/><p>This allowance counts specialist requests created by the coordinator. Coordinator cycles and manually queued requests have separate limits. It is not a dollar spending cap.</p></div>
   </section>
   {detail.project.contractVersion===2&&<section className={s.section} aria-label="Internal QC corrections">
    <div className={s.heading}><div><h3>Act on internal QC feedback</h3><p>Keep the approved brief, specification and current production round. Rejected outputs and review history remain preserved.</p></div>{admin&&detail.project.status!=='delivered'&&<button className="button secondary small" onClick={()=>setEditing(true)}><Settings2 size={14}/> Review correction setup</button>}</div>
    {!resource.data.mediaReworks?.length?<p className={s.muted}>No current rejected version is eligible for a new correction. Earlier attempts remain in specialist handoffs below.</p>:<ol className={s.history}>{resource.data.mediaReworks.map(candidate=>{
     const work=detail.workItems.find(item=>item.id===candidate.workItemId),artifact=detail.artifacts.find(item=>item.id===candidate.artifactId),reviewer=p.workspace.members.find(member=>member.userId===candidate.reviewedBy),role=detail.roles.find(item=>item.key===work?.roleKey);
     let blocked=correctionBlock;
     if(!blocked&&(!work||!policy?.allowedRoleKeys.includes(work.roleKey)))blocked='This specialist role is outside the reviewed delegation policy.';
     if(!blocked&&candidate.specialistAgentId===policy?.coordinatorAgentId&&!policy?.coordinatorGeneration)blocked='Coordinator-owned generation needs its separate policy opt-in.';
     return <li key={candidate.artifactId}>
      <strong>{artifact?.name??work?.title??'Generated output'} · version {candidate.artifactVersion}</strong><small>Changes requested · {reviewer?.name??candidate.reviewedBy} · {new Date(candidate.reviewedAt).toLocaleString()}</small>
      <p className={s.prose}>{candidate.reviewNote}</p><small>{work?.title??'Generation work'} · {role?.agentName??'Assigned generation specialist'} · {candidate.roundId?'Current revision round':'Original production round'}</small>
      <p role="status">{blocked||'Eligible for one correction. Waiting for the coordinator to request the assigned specialist.'}</p><p className={s.muted}>The specialist prepares a new proposal. Sending it to Higgsfield still requires review of the exact arguments, references and credit charge.</p>
      <details><summary>Exact QC correction source</summary><p>Independent review: {candidate.reviewId}<br/>Rejected artifact: {candidate.artifactId}<br/>Generation work: {candidate.workItemId}<br/>Task: {candidate.taskId} · revision {candidate.taskRevision}<br/>Source specialist request: {candidate.sourceChildRunId}<br/>Round: {candidate.roundId??'Original production'}</p><p style={{overflowWrap:'anywhere'}}>Manifest SHA-256: {candidate.manifestSha256}<br/>Specification SHA-256: {candidate.specSha256}</p></details>
     </li>;
    })}</ol>}
   </section>}
   <section className={s.section}><div className={s.heading}><div><h3>Keep the project moving</h3><p>A connected worker and an activated coordinator mission are needed for recurring progress. Saving a delegation policy starts neither.</p></div>{admin&&<button className="button secondary small" onClick={onSchedule}><Bot size={14}/> Schedule coordinator</button>}</div></section>
   <section className={s.section}><h3><GitBranch size={16}/> Specialist handoffs</h3>{!resource.data.dispatches.length?<p className={s.muted}>No specialist handoffs yet. Accepted dependencies and a live coordinator determine the next permitted action.</p>:<ol className={s.history}>{resource.data.dispatches.map(receipt=><li key={receipt.childRunId}><strong>{detail.workItems.find(work=>work.id===receipt.workItemId)?.title||'Production work'}</strong>{receipt.coordinatorAgentId===receipt.specialistAgentId&&<small>{receipt.archiveId?'Coordinator-owned continuation':'Coordinator-owned generation'} · separate request</small>}{receipt.planningReviewId&&<small>Planning correction</small>}{receipt.mediaReviewId&&<><small>Internal QC correction · rejected version {receipt.artifactVersion}</small><small>One attempt recorded for this version. New media requires a fresh independent review.</small></>}{receipt.archiveId&&<small>Verified generated output continuation</small>}<small>{receipt.status||'Request recorded'}{receipt.createdAt?` · ${new Date(receipt.createdAt).toLocaleString()}`:''}</small><details><summary>Request provenance</summary><p>Coordinator request: {receipt.parentRunId}<br/>Specialist request: {receipt.childRunId}{receipt.planningReviewId&&<><br/>Review decision: {receipt.planningReviewId}{receipt.sourceChildRunId&&<><br/>Original specialist request: {receipt.sourceChildRunId}</>}</>}{receipt.mediaReviewId&&<><br/>Independent QC review: {receipt.mediaReviewId}<br/>Rejected artifact: {receipt.artifactId}<br/>Source task revision: {receipt.taskRevision}<br/>Round: {receipt.roundId??'Original production'}{receipt.sourceChildRunId&&<><br/>Original specialist request: {receipt.sourceChildRunId}</>}</>}{receipt.archiveId&&<><br/>Verified archive: {receipt.archiveId}{receipt.sourceChildRunId&&<><br/>Original specialist request: {receipt.sourceChildRunId}</>}{receipt.artifactId&&<><br/>Registered artifact: {receipt.artifactId}</>}</>}</p></details></li>)}</ol>}</section>
  </>}
  {(resource.error||mutation.error)&&<p className="error-message" role="alert">{resource.error||mutation.error}</p>}
  {editing&&resource.data&&<PolicyEditor key={detail.project.id} p={p} detail={detail} initial={resource.data.policy} path={path} onClose={()=>setEditing(false)} onSaved={async()=>{setEditing(false);await resource.reload();p.notify('Project delegation policy saved. Worker and mission controls remain separate.');}}/>}
 </>;
}

function PolicyEditor({p,detail,initial:loadedPolicy,path,onClose,onSaved}:{p:WorkspaceProps;detail:StudioReadableProjectDetail;initial:Policy|null;path:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const mutation=useStudioMutation();
 // Background polling must not change the reviewed revision or an exact retry.
 const [initial]=useState(loadedPolicy);
 const candidates=p.workspace.agents.filter(agent=>agent.status==='active'&&!!agent.pluginInstallationId&&['studio.read','studio.write','tasks.write'].every(cap=>agent.capabilities?.includes(cap))&&detail.roles.some(role=>['producer','coordinator'].includes(role.key)&&role.agentId===agent.id));
 const [coordinatorAgentId,setCoordinatorAgentId]=useState(initial?.coordinatorAgentId||candidates[0]?.id||'');
 const [allowedRoleKeys,setAllowedRoleKeys]=useState<string[]>(initial?.allowedRoleKeys||[]),[maxRuns,setMaxRuns]=useState(initial?.maxRuns||5),[maxConcurrentRuns,setMaxConcurrentRuns]=useState(initial?.maxConcurrentRuns||1),[status,setStatus]=useState<'active'|'paused'>(initial?.status||'paused');
 const [expiresAt,setExpiresAt]=useState(initial?.expiresAt||new Date(Date.now()+3600000).toISOString()),[duration,setDuration]=useState(''),[reviewed,setReviewed]=useState(false);
 const [generatedContinuations,setGeneratedContinuations]=useState(initial?.generatedContinuations??false),[continuationsChanged,setContinuationsChanged]=useState(false);
 const [coordinatorGeneration,setCoordinatorGeneration]=useState(initial?.coordinatorGeneration??false),[generationChanged,setGenerationChanged]=useState(false);
 const [planningRework,setPlanningRework]=useState(initial?.planningRework??false),[reworkChanged,setReworkChanged]=useState(false);
 const [mediaRework,setMediaRework]=useState(initial?.mediaRework??false),[mediaReworkChanged,setMediaReworkChanged]=useState(false);
 const [referencePreparation,setReferencePreparation]=useState(initial?.referencePreparationProfile==='prepared_image_v1');
 const roles=detail.roles.filter(role=>role.agentId&&role.key!=='qc'&&detail.workItems.some(work=>work.roleKey===role.key&&work.execution!=='human'&&(role.agentId!==coordinatorAgentId||(detail.project.contractVersion===2&&coordinatorGeneration&&role.key==='comp'&&work.stage==='generation'&&work.execution==='creative'))));
 const invalidRoles=allowedRoleKeys.some(key=>!roles.some(role=>role.key===key));
 const referenceRoles=roles.filter(role=>allowedRoleKeys.includes(role.key)&&detail.workItems.some(work=>work.roleKey===role.key&&work.stage==='references'&&work.execution==='agent'));
 const invalidReference=referencePreparation&&(!referenceRoles.length||referenceRoles.some(role=>role.agentId===coordinatorAgentId||!['creative.read','studio.read','studio.write','tasks.write','storage.read'].every(cap=>p.workspace.agents.find(agent=>agent.id===role.agentId)?.capabilities?.includes(cap))));
 const changed=()=>setReviewed(false);
 async function submit(event:FormEvent){event.preventDefault();await mutation.mutate(path,{revision:initial?.revision||0,coordinatorAgentId,allowedRoleKeys,maxRuns,maxConcurrentRuns,status,expiresAt,...initial?.planningRework!==undefined||reworkChanged?{planningRework}:{},...initial?.mediaRework!==undefined||mediaReworkChanged?{mediaRework}:{},...referencePreparation?{referencePreparationProfile:'prepared_image_v1'}:{},...initial?.generatedContinuations!==undefined||continuationsChanged?{generatedContinuations}:{},...initial?.coordinatorGeneration!==undefined||generationChanged?{coordinatorGeneration}:{}},onSaved,'PUT');}
 return <Modal title="Review project delegation" description="Give one coordinator a bounded ability to request work from reviewed specialists." onClose={()=>{if(!mutation.busy)onClose();}} wide><form className="form" onSubmit={submit}><fieldset disabled={mutation.busy}>
  <Field label="Project coordinator"><select required value={coordinatorAgentId} onChange={event=>{setCoordinatorAgentId(event.target.value);setAllowedRoleKeys([]);changed();}}><option value="">Choose an active producer or coordinator</option>{candidates.map(agent=><option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></Field>
  {detail.project.contractVersion===2&&<div><label className={s.checkbox}><input type="checkbox" checked={coordinatorGeneration} aria-describedby="coordinator-generation-help" onChange={event=>{setCoordinatorGeneration(event.target.checked);setGenerationChanged(true);if(!event.target.checked)setAllowedRoleKeys(keys=>keys.filter(key=>detail.roles.find(role=>role.key===key)?.agentId!==coordinatorAgentId));changed();}}/>Let the coordinator also handle generation</label><p id="coordinator-generation-help" className={s.muted}>Off by default. Select the coordinator’s assigned generation role below to queue a separate bounded request. It can start only after the coordinator’s current cycle finishes successfully and counts toward the existing specialist run and concurrency limits. This grants no spending approval, independent review, or extra permissions. Verified output continuation has its own opt-in below.</p></div>}
  <fieldset className={s.disciplines}><legend>Specialist roles this coordinator may request</legend>{roles.map(role=><label key={role.key}><input type="checkbox" checked={allowedRoleKeys.includes(role.key)} onChange={event=>{setAllowedRoleKeys(event.target.checked?[...allowedRoleKeys,role.key]:allowedRoleKeys.filter(key=>key!==role.key));changed();}}/>{role.title} · {role.agentName||'Assigned agent'}{role.agentId===coordinatorAgentId?' · separate generation request':''}</label>)}{!roles.length&&<p>{detail.project.contractVersion===2?'Assign an eligible specialist, or enable coordinator-owned generation if the coordinator also holds the generation role.':'Assign a different specialist to an agent or DCC production step first.'}</p>}</fieldset>
  {detail.project.contractVersion===2&&<div><label className={s.checkbox}><input type="checkbox" checked={referencePreparation} aria-describedby="reference-preparation-help" onChange={event=>{setReferencePreparation(event.target.checked);changed();}}/>Allow prepared image reference selection</label><p id="reference-preparation-help" className={s.muted}>Off by default. Select a separate reference specialist with existing creative-read, studio, task and storage-read permissions. Its finite request can propose exact verified images and submit a factual plan while inspection is pending. Inspection requires this same policy and its expiry, even after successful task completion. Images are not resized or stripped of metadata; human sharing approval stays separate.</p></div>}
  <div><label className={s.checkbox}><input type="checkbox" checked={planningRework} aria-describedby="planning-rework-help" onChange={event=>{setPlanningRework(event.target.checked);setReworkChanged(true);changed();}}/>Allow reviewed planning corrections</label><p id="planning-rework-help" className={s.muted}>Off by default. After a separate reviewer completes a changes-requested decision, the assigned specialist may make one correction for that exact decision. Estimates and breakdowns only. Every pass counts toward the same lifetime and concurrency limits and needs a new review. Failed or uncertain runs are not retried; no generation, spending, or business approval is added.</p></div>
  {detail.project.contractVersion===2&&<div><label className={s.checkbox}><input type="checkbox" checked={mediaRework} aria-describedby="media-rework-help" onChange={event=>{setMediaRework(event.target.checked);setMediaReworkChanged(true);changed();}}/>Allow one correction per rejected media version</label><p id="media-rework-help" className={s.muted}>Off by default. An independent human QC change request lets the coordinator request one new generation proposal for that exact rejected version, within the same brief, specification and production round. Each correction counts toward the existing lifetime and concurrency limits and expires with this policy. Another review of the same version does not reset its attempt. Failed or uncertain attempts are not retried. Every new Higgsfield request still requires separate human approval of its exact arguments, reference sharing and credit charge; independent QC remains required afterward.</p></div>}
  <div className={s.formGrid} style={{marginTop:18}}><Field label="Total specialist run allowance" hint={`${initial?.runsStarted||0} already started. Existing usage is never reset.`}><input required type="number" min={Math.max(1,initial?.runsStarted||0)} max={100} value={maxRuns} onChange={event=>{setMaxRuns(Number(event.target.value));changed();}}/></Field><Field label="Maximum concurrent specialist runs"><input required type="number" min={1} max={3} value={maxConcurrentRuns} onChange={event=>{setMaxConcurrentRuns(Number(event.target.value));changed();}}/></Field></div>
  {detail.project.contractVersion===2&&<div><label className={s.checkbox}><input type="checkbox" checked={generatedContinuations} aria-describedby="generated-continuations-help" onChange={event=>{setGeneratedContinuations(event.target.checked);setContinuationsChanged(true);changed();}}/>Allow verified generated output continuations</label><p id="generated-continuations-help" className={s.muted}>Off by default. Resume an assigned specialist from its exact verified generated output within the existing run allowance. This permits registration and task submission only; it adds no generation, file transfer, or review authority. Independent QC and delivery approvals remain required.</p></div>}
  <div className={s.formGrid}><Field label="Policy state"><select value={status} onChange={event=>{setStatus(event.target.value as 'active'|'paused');changed();}}><option value="paused">Paused</option><option value="active">Allow reviewed delegation</option></select></Field><Field label="Set a new expiry"><select value={duration} onChange={event=>{setDuration(event.target.value);if(event.target.value)setExpiresAt(new Date(Date.now()+Number(event.target.value)*60000).toISOString());changed();}}><option value="">Keep the displayed expiry</option>{[20,60,120,240,480,1440].map(minutes=><option key={minutes} value={minutes}>{minutes<60?`${minutes} minutes`:`${minutes/60} hours`}</option>)}</select></Field></div>
  <p className={s.notice}>Exact expiry: {new Date(expiresAt).toLocaleString()}. Complete enrollment and wait for the supervisor’s first connection before this review. Initial connection and supervisor takeover rotate the reviewed agent configuration.</p>
  <p className={s.muted}>The coordinator cannot hire agents, increase their permissions, approve media, or send client deliveries. Each specialist keeps its existing model and per-request limits. Pausing, expiry, or changing this policy ends delegated authority at the next API or lease check, including for work already queued or running. Use request cancellation and host controls when an operational stop is needed.</p>
  <label className={s.checkbox}><input required type="checkbox" checked={reviewed} onChange={event=>setReviewed(event.target.checked)}/>I reviewed the coordinator, selected roles, request allowance, concurrency, planning corrections, state, and exact expiry{detail.project.contractVersion===2?', including internal QC corrections, prepared image selection, coordinator-owned generation and generated output continuation options':''}.</label>
 </fieldset>{invalidReference&&<p className="error-message" role="alert">Select a separate reference specialist with the five existing reference preparation permissions. This policy does not add permissions.</p>}{invalidRoles&&<p className="error-message" role="alert">A reviewed role is no longer available. Re-select the coordinator and review its current specialists.</p>}{mutation.error&&<p className="error-message" role="alert">{mutation.error}</p>}<div className={s.actions}><button className="button secondary" type="button" disabled={mutation.busy} onClick={onClose}>Cancel</button><button className="button primary" disabled={mutation.busy||!reviewed||!coordinatorAgentId||!allowedRoleKeys.length||invalidRoles||invalidReference}>{mutation.busy?'Saving policy…':'Save reviewed policy'} <Check size={15}/></button></div></form></Modal>;
}
