'use client';
import {useState,type FormEvent} from 'react';
import {ArrowLeft,ArrowRight,Bot,Check,RefreshCw,Users} from 'lucide-react';
import type {WorkspaceProps} from '@/app/page';
import type {PluginCatalogEntry} from '@/lib/plugin-catalog';
import type {StudioStaffingProposal} from '@/lib/studio-staffing-protocol';
import {STUDIO_DISCIPLINES,STUDIO_TEMPLATES} from '@/lib/studio-protocol';
import {Field,Loading,Modal} from './ui';
import {useStudioMutation,useStudioResource} from './studio-hooks';
import s from './StudioWorkspace.module.css';

const title=(key:string)=>STUDIO_TEMPLATES[0].roles.find(role=>role.key===key)?.title||key;
export function StudioStaffingPlanner({p,onClose,onSaved}:{p:WorkspaceProps;onClose:()=>void;onSaved:()=>Promise<void>}){
 const base=`/api/companies/${p.company.id}/studio/staffing/proposals`;
 const catalog=useStudioResource<{plugins:PluginCatalogEntry[]}>('/api/plugins/catalog'),proposals=useStudioResource<{proposals:StudioStaffingProposal[]}>(base),mutation=useStudioMutation();
 const [selected,setSelected]=useState<StudioStaffingProposal|null>(null),[brief,setBrief]=useState('An AI production studio using Higgsfield for approved references and generations. Coordinate client briefs, reference rights, generation requests, human output review and delivery. Keep original footage, EXRs and heavy renders on connected local or cloud storage. Workstation and render-server execution are deferred.');
 const [teamSize,setTeamSize]=useState(4),[disciplines,setDisciplines]=useState<string[]>(['compositing']),[reviewer,setReviewer]=useState(''),[pluginId,setPluginId]=useState('runpod'),[modelId,setModelId]=useState(''),[applied,setApplied]=useState(false);
 const [includePlanningReviewer,setIncludePlanningReviewer]=useState(false),[planningReviewerName,setPlanningReviewerName]=useState('Planning reviewer'),[planningReviewerPersona,setPlanningReviewerPersona]=useState('Careful, specific and evidence-led. Explain what is missing and what would make the planning contribution acceptable.');
 const plugin=catalog.data?.plugins.find(item=>item.id===pluginId),provider=plugin?.providers[0],model=modelId||provider?.models[0]?.id||'';
 const reviewers=p.workspace.members.filter(member=>['owner','admin'].includes(member.role)&&member.userId!==p.user.id);
 async function propose(event:FormEvent){event.preventDefault();if(!plugin||!provider)return;const limits=provider.id==='runpod'?{maxSteps:8,maxOutputTokens:8192,maxTotalTokens:80000,timeoutSeconds:600}:{maxSteps:8,maxOutputTokens:2048,maxTotalTokens:24000,timeoutSeconds:180};await mutation.mutate<{proposal:StudioStaffingProposal}>(base,{brief,teamSize,disciplines,reviewerHumanId:reviewer||null,...includePlanningReviewer?{planningReviewer:{name:planningReviewerName,...planningReviewerPersona.trim()?{persona:planningReviewerPersona.trim()}:{}}}:{},provider:{pluginId,manifestVersion:plugin.version,runtimeConfig:{providerId:provider.id,modelId:model,...limits}}},async result=>{setSelected(result.proposal);await proposals.reload();});}
 async function apply(){if(!selected)return;await mutation.mutate<{proposal:StudioStaffingProposal}>(`${base}/${selected.id}/apply`,{revision:selected.revision,planHash:selected.planHash,profileRevision:selected.plan.profileRevision},async result=>{setSelected(result.proposal);setApplied(true);await Promise.all([onSaved(),p.refresh(),proposals.reload()]);p.notify('Studio team created. Review host enrollment and project policies before activating work.');});}
 return <Modal title="Build your studio team" description="Describe the company. Review the team and its responsibilities before applying." onClose={()=>{if(!mutation.busy)onClose();}} wide>
  {catalog.loading?<Loading label="Loading available agent bridges"/>:catalog.error?<p role="alert" className="error-message">{catalog.error}</p>:selected?<div className={s.formSection}>
   <div className={s.heading}><div><span className="eyebrow">{applied||selected.status==='applied'?'STUDIO TEAM CREATED':'REVIEW YOUR PROPOSED TEAM'}</span><h3>{selected.plan.actualAgentCount} AI team members.</h3><p>{selected.plan.brief}</p></div><button className="button secondary small" disabled={mutation.busy} onClick={()=>{setSelected(null);setApplied(false);}}><ArrowLeft size={14}/> Back</button></div>
   <div className={s.teamGrid}>{[...selected.plan.specialists,...selected.plan.planningReviewer?[selected.plan.planningReviewer]:[]].map(person=><article className={s.role} key={person.key}><small>{person.key==='planning-reviewer'?'SEPARATE PLANNING REVIEWER':person.mode==='bind'?'EXISTING COMPANY AGENT':'NEW AI SPECIALIST'}</small><h3><Bot size={16}/> {person.name}</h3><p>{person.roleKeys.length?person.roleKeys.map(title).join(' · '):person.character.roleTitle}</p><ul className={s.skills}>{person.skills.map(skill=><li key={skill.key}>{skill.title}{person.key==='planning-reviewer'?` · v${skill.version}`:''}</li>)}</ul>{person.key==='planning-reviewer'&&<p className={s.notice}>Planning-only authority. No producing or human QC role. These versioned instructions are saved in this agent’s installation. Review policy and worker enrollment require separate approval; shared sponsorship must be explicitly allowed by that policy.</p>}<details><summary>Role instructions and permissions</summary><p className={s.prose}>{person.character.persona}</p><p><strong>Capabilities:</strong> {person.capabilities.join(', ')}</p><p><strong>Model:</strong> {person.provider.runtimeConfig.modelId}</p><p>Up to {person.provider.runtimeConfig.maxSteps} steps, {person.provider.runtimeConfig.maxOutputTokens.toLocaleString()} output tokens per step, and {person.provider.runtimeConfig.maxTotalTokens.toLocaleString()} total tokens per request; {person.provider.runtimeConfig.timeoutSeconds} seconds maximum. These are configured execution limits, not a spending guarantee.</p><p>Who can request work: {person.invocationAccess}. Conversation access: {person.conversationAccess}.</p>{person.existing&&<p>Existing installation revision {person.existing.installationRevision}; its reviewed grants remain in place.</p>}</details></article>)}</div>
   <div className={s.notice}><Users size={17}/><div><strong>Independent quality reviewer</strong><p>{selected.plan.reviewer?selected.plan.reviewer.name:'Unassigned. Add an independent administrator before accepting production outputs.'}</p></div></div>
   {selected.plan.warnings.map(warning=><p className={s.notice} key={warning}>{warning}</p>)}
   {selected.status==='pending'&&!applied?<><p>Applying creates {selected.plan.newAgentCount} paused agent identities with reviewed role instructions. Enroll workers and approve project policies separately.</p><button className="button primary" disabled={mutation.busy} onClick={()=>void apply()}>{mutation.busy?'Creating specialists…':'Apply this team'} <Check size={15}/></button></>:<div className={s.notice}><Check size={18}/><div><strong>{selected.status==='rejected'?'This proposal was rejected.':'Your team structure is saved.'}</strong><p>Return to the studio and open Agent hosts to enroll this team, then review any project policies. The studio retains its client, production, review, and delivery gates.</p><button type="button" className="button primary" onClick={onClose}>Back to studio <ArrowRight size={14}/></button></div></div>}
  </div>:<form className="form" onSubmit={propose}><fieldset disabled={mutation.busy}>
   <p className={s.notice}>Current production flow: brief → references → Higgsfield generation → review → delivery. These agents plan and coordinate the company. Applying this team does not install a generation connection, grant media access, or start a workstation or render server.</p>
   <Field label="What will your studio produce?" hint="Include clients, desired deliverables, approved reference sources and review responsibilities."><textarea required minLength={1} maxLength={6000} rows={4} value={brief} onChange={event=>setBrief(event.target.value)}/></Field>
   <div className={s.formGrid}><Field label="AI team size" hint="Total identities, including the optional planning reviewer. Related production responsibilities can share one specialist."><input required type="number" min={includePlanningReviewer?2:1} max={11} value={teamSize} onChange={event=>setTeamSize(Number(event.target.value))}/></Field><Field label="Independent quality reviewer"><select value={reviewer} onChange={event=>setReviewer(event.target.value)}><option value="">Assign later</option>{reviewers.map(member=><option key={member.userId} value={member.userId}>{member.name}</option>)}</select></Field></div>
   <section className={s.section}><label className={s.checkbox}><input type="checkbox" checked={includePlanningReviewer} onChange={event=>{setIncludePlanningReviewer(event.target.checked);if(event.target.checked)setTeamSize(value=>Math.max(2,value));}}/>Include a separate AI planning reviewer</label><p className={s.muted}>Uses one team slot. Reviews exact planning submissions under a separately approved policy; never replaces human media QC, business approval or client acceptance.</p>{includePlanningReviewer&&<><Field label="Planning reviewer name"><input required maxLength={80} value={planningReviewerName} onChange={event=>setPlanningReviewerName(event.target.value)}/></Field><Field label="Planning reviewer working style" hint="Style instructions are subordinate to the fixed planning-only permissions."><textarea maxLength={500} rows={3} value={planningReviewerPersona} onChange={event=>setPlanningReviewerPersona(event.target.value)}/></Field><p className={s.notice}>Starts paused with studio.read and studio.review only. It shares your sponsorship with the new production agents; a project policy must separately allow shared-sponsor machine review. No policy, worker or compute starts when you apply this team.</p></>}</section>
   <fieldset><legend>Production responsibilities</legend><p className={s.muted}>These existing studio disciplines assign planning and handoff responsibilities. They do not certify a Higgsfield model capability or enable DCC execution.</p><div className={s.skills}>{STUDIO_DISCIPLINES.map(discipline=><label key={discipline}><input type="checkbox" checked={disciplines.includes(discipline)} onChange={event=>setDisciplines(event.target.checked?[...disciplines,discipline]:disciplines.filter(item=>item!==discipline))}/>{discipline.replace(/^./,letter=>letter.toUpperCase())}</label>)}</div></fieldset>
   <div className={s.formGrid}><Field label="Agent bridge"><select value={pluginId} onChange={event=>{setPluginId(event.target.value);setModelId('');}}>{catalog.data?.plugins.map(plugin=><option key={plugin.id} value={plugin.id}>{plugin.name}</option>)}</select></Field><Field label="Model"><select required value={model} onChange={event=>setModelId(event.target.value)}>{provider?.models.map(model=><option key={model.id} value={model.id}>{model.label}</option>)}</select></Field></div>
   <p className={s.notice}>This model powers the company agents’ reasoning; Higgsfield generation is a separate connection. Producer, coordinator, supervision and delivery responsibilities are included with the existing shared studio instructions. Personal skill vaults stay private, and saved plans and installed identities remain unchanged.</p>
  </fieldset><button className="button primary" disabled={mutation.busy||!disciplines.length||!plugin||!model}>{mutation.busy?'Preparing structure…':'Design my studio team'} <ArrowRight size={15}/></button>
  {proposals.data?.proposals.length?<section className={s.formSection}><div className={s.heading}><h3>Saved team proposals</h3><button type="button" className="icon-button" aria-label="Refresh team proposals" onClick={()=>void proposals.reload()}><RefreshCw size={15}/></button></div>{proposals.data.proposals.map(proposal=><button type="button" className="button secondary" key={proposal.id} onClick={()=>setSelected(proposal)}>{proposal.plan.actualAgentCount} specialists · {proposal.status} · {new Date(proposal.createdAt).toLocaleDateString()} <ArrowRight size={13}/></button>)}</section>:null}
  </form>}
  {(mutation.error||proposals.error)&&<p role="alert" className="error-message">{mutation.error||proposals.error} {selected&&<button className="text-button" onClick={()=>{setSelected(null);setApplied(false);void proposals.reload();}}>Reload saved proposals</button>}</p>}
 </Modal>;
}
