'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,Copy,Download,FileCheck2,LockKeyhole,RefreshCw,ShieldCheck} from 'lucide-react';
import {api,setClientIdentity,type Session} from '@/lib/client';
import type {StudioDelivery} from '@/lib/studio-protocol';
import type {StudioClientDeliveryDetail,StudioClientDeliveryList,StudioClientDeliveryShare,StudioClientDeliveryFile,StudioGeneratedClientDeliveryFile,StudioGeneratedClientAccess} from '@/lib/studio-client-delivery-protocol';
import {chooseStorageDownloadTarget,canStreamStorageDownload,STORAGE_BROWSER_BLOB_LIMIT,type StorageSaveTarget} from '@/lib/project-storage-client';
import {downloadGeneratedClientFile} from '@/lib/generated-client-download';
import {generatedBytes} from '@/lib/generated-media-ui';
import {Auth} from './Auth';
import {Brand} from './ui';
import styles from './StudioClientDeliveries.module.css';

const stamp=(value:string)=>new Date(value).toLocaleString();
function ErrorNote({error}:{error:string}){return error?<p role="alert" className={styles.error}>{error}</p>:null;}
function useRequests(){const requests=useRef(new Map<string,string>());return (operation:string,data:unknown)=>{const key=operation+JSON.stringify(data);let id=requests.current.get(key);if(!id){id=crypto.randomUUID();requests.current.set(key,id);}return id;};}
function useClientOperations(scope:string){
 const epoch=useRef(0),controllers=useRef(new Set<AbortController>());
 const cancel=useCallback(()=>{epoch.current++;for(const controller of controllers.current)controller.abort();controllers.current.clear();},[]);
 useEffect(()=>cancel,[scope,cancel]);
 return {cancel,start(){const controller=new AbortController(),ticket=epoch.current;controllers.current.add(controller);return {signal:controller.signal,current:()=>!controller.signal.aborted&&ticket===epoch.current,finish:()=>controllers.current.delete(controller),cancel:()=>controller.abort()};}};
}
export function StudioClientDeliveries({companyId,projectId,projectRevision,deliveries,currentRoundId,admin,onChanged,creationBlocked}:{companyId:string;projectId:string;projectRevision:number;deliveries:StudioDelivery[];currentRoundId?:string|null;admin:boolean;onChanged?:()=>void|Promise<void>;creationBlocked?:string|null}){
 const [list,setList]=useState<StudioClientDeliveryList|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState(false),[review,setReview]=useState(false),[recipient,setRecipient]=useState(''),[deliveryId,setDeliveryId]=useState(''),[days,setDays]=useState(7),[confirmed,setConfirmed]=useState(false),[copied,setCopied]=useState('');
 const requestId=useRequests(),path=`/api/companies/${companyId}/studio/projects/${projectId}/client-deliveries`,generation=useRef(0);
 const earlierShare=(share:StudioClientDeliveryShare)=>currentRoundId!==undefined&&(deliveries.find(item=>item.id===share.deliveryId)?.roundId??null)!==currentRoundId;
 const eligible=deliveries.filter(item=>item.status==='prepared'&&(currentRoundId===undefined||(item.roundId??null)===currentRoundId));
 const operations=useClientOperations(path+':'+admin+':'+(currentRoundId??'')),[attempt,setAttempt]=useState<{name:string;data:{revision:number;deliveryId:string;recipientUserId:string;identityConfirmation:'confirmed_out_of_band';expiresAt:string}}|null>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{const ticket=++generation.current,operation=operations.start(),combined=signal?AbortSignal.any([signal,operation.signal]):operation.signal;try{const result=await api<StudioClientDeliveryList>(path,'GET',undefined,{signal:combined});if(!combined.aborted&&ticket===generation.current){setList(result);setError('');}}catch(e){if(!combined.aborted&&ticket===generation.current)setError((e as Error).message);}finally{operation.finish();}},[path]);
 useEffect(()=>{setList(null);setForm(false);setReview(false);setAttempt(null);const changed=()=>{operations.cancel();generation.current++;setList(null);setForm(false);setReview(false);setAttempt(null);setBusy(false);};window.addEventListener('coatria:session-changed',changed);return()=>window.removeEventListener('coatria:session-changed',changed);},[path,admin,currentRoundId,operations.cancel]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>{generation.current++;controller.abort();};},[load,projectRevision]);
 async function copy(share:StudioClientDeliveryShare){const operation=operations.start();try{await navigator.clipboard.writeText(new URL(share.invitationPath,location.origin).href);if(operation.current())setCopied(share.id);}catch{if(operation.current())setError('Copy the invitation address from the link below.');}finally{operation.finish();}}
 async function revoke(share:StudioClientDeliveryShare){const operation=operations.start();setBusy(true);setError('');try{const data={revision:share.revision};await api(path+'/'+share.id+'/revoke','POST',{...data,clientId:requestId('revoke:'+share.id,data)},{signal:operation.signal});if(operation.current())await load(operation.signal);}catch(e){if(operation.current())setError((e as Error).message);}finally{if(operation.current())setBusy(false);operation.finish();}}
 const expiry=useRef<{key:string;value:string}|null>(null);
 function reviewInvitation(){if(creationBlocked||!eligible.some(item=>item.id===deliveryId))return;const key=JSON.stringify({recipient,deliveryId,days});if(expiry.current?.key!==key)expiry.current={key,value:new Date(Date.now()+days*86400000).toISOString()};setAttempt({name:deliveries.find(item=>item.id===deliveryId)?.name??'Prepared package',data:{revision:projectRevision,deliveryId,recipientUserId:recipient.trim(),identityConfirmation:'confirmed_out_of_band',expiresAt:expiry.current.value}});setReview(true);}
 async function create(){if(!attempt||busy)return;const operation=operations.start();setBusy(true);setError('');try{const data=attempt.data;await api(path,'POST',{...data,clientId:requestId('create',data)},{signal:operation.signal});if(operation.current()){setForm(false);setReview(false);setConfirmed(false);setAttempt(null);await load(operation.signal);if(operation.current())await onChanged?.();}}catch(e){if(operation.current())setError((e as Error).message);}finally{if(operation.current())setBusy(false);operation.finish();}}

 return <section className={styles.panel} aria-label="Client delivery portal"><div className={styles.heading}><div><span className={styles.eyebrow}>THE CLIENT HANDOFF</span><h3>Share the approved package.</h3><p>Private files, one named client account, and a clear record of their response.</p></div>{admin&&<button className="button primary small" disabled={busy||!!creationBlocked||!eligible.length} onClick={()=>{setForm(!form);setReview(false);setDeliveryId(eligible[0]?.id??'');}}>Create client invitation <ArrowUpRight size={15}/></button>}</div>
 {creationBlocked&&<p className={styles.note}>{creationBlocked}</p>}
 <p className={styles.note}><LockKeyhole size={16}/> Only verified private files from approved versions can be shared. Independent delivery-handoff review must be complete. Creating an invitation sends no message.</p><ErrorNote error={error}/>
 {form&&<form className={styles.form} onSubmit={event=>{event.preventDefault();if(review)void create();else reviewInvitation();}}><h4>{review?'Review this invitation':'Choose the client and package'}</h4>{!review?<><label>Prepared package<select required value={deliveryId} onChange={e=>setDeliveryId(e.target.value)}>{eligible.map(item=><option key={item.id} value={item.id}>{item.name}{item.roundNumber?' · Revision '+item.roundNumber:''}</option>)}</select></label><label>Client’s Coatria account ID<input required value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" pattern="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"/></label><p className={styles.note}>Ask your client to sign in at <a href="/delivery" target="_blank" rel="noreferrer">the delivery portal</a> and give you their account ID through your existing trusted contact. They do not need to join your company. Email verification is not enabled.</p><label>Access expires after<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>1 day</option><option value={7}>7 days</option><option value={14}>14 days</option><option value={30}>30 days</option></select></label><label className={styles.check}><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I confirmed this exact account ID directly with the intended external client.</span></label></>:<div className={styles.review}><strong>{attempt?.name}</strong><span>Recipient account</span><code>{attempt?.data.recipientUserId}</code><span>Exact expiry: {attempt?stamp(attempt.data.expiresAt):''}</span><span>Expires in {days} day{days===1?'':'s'} · Read and respond to this package only</span><p>The account confirmation is your attestation. The invitation does not verify a legal identity or send an email.</p></div>}<div className={styles.actions}><button className="button primary" disabled={busy||!confirmed}>{busy?'Creating…':review?'Create invitation':'Review invitation'}</button><button className="button secondary" type="button" disabled={busy} onClick={()=>review?setReview(false):setForm(false)}>{review?'Back':'Cancel'}</button></div></form>}
 {!list&&!error?<p role="status">Loading client access…</p>:list?.shares.length===0?<div className={styles.empty}><FileCheck2 size={24}/><strong>No client invitation yet</strong><p>Prepare and independently approve your delivery handoff, then grant access to the exact client account.</p></div>:list?.shares.map(share=><article className={styles.share} key={share.id}><div className={styles.heading}><div><strong>{deliveries.find(item=>item.id===share.deliveryId)?.name??'Approved package'}</strong><p>{share.recipientName} · {share.response.replaceAll('_',' ')}</p>{currentRoundId!==undefined&&<p>{deliveries.find(item=>item.id===share.deliveryId)?.roundNumber?'Revision '+deliveries.find(item=>item.id===share.deliveryId)?.roundNumber:'Original package'}{(deliveries.find(item=>item.id===share.deliveryId)?.roundId??null)!==currentRoundId?' · Earlier invitation preserved':''}</p>}</div><span className={styles.badge}>{earlierShare(share)?'Earlier package · history only':share.status==='revoked'?'Revoked':share.expired?'Expired':'Access active'}</span></div><dl className={styles.facts}><div><dt>Files</dt><dd>{share.fileCount}</dd></div><div><dt>Portal opens</dt><dd>{share.receiptSummary.portalOpened}</dd></div><div><dt>Download links issued</dt><dd>{share.receiptSummary.downloadAccessIssued}</dd></div><div><dt>Expires</dt><dd>{stamp(share.expiresAt)}</dd></div></dl><p className={styles.note}>File receipt is not observed. Client acknowledgement is a separate authenticated attestation.</p>{currentRoundId!==undefined&&share.response==='changes_requested'&&<button type="button" className="button secondary small" onClick={()=>{const panel=document.getElementById('generated-revision-planning');panel?.scrollIntoView({behavior:'smooth',block:'start'});panel?.focus({preventScroll:true});}}>View feedback & revision plans</button>}<details><summary>Account and package identity</summary><p>Account: <code>{share.recipientUserId}</code></p><p>Package SHA-256: <code>{share.packageSha256}</code></p><p>Identity confirmed out of band · Email {share.emailVerifiedAtCreation?'verified at creation':'not verified at creation'}</p></details>{admin&&<div className={styles.actions}><button className="button secondary small" disabled={share.status==='revoked'||share.expired} onClick={()=>void copy(share)}>{copied===share.id?<Check size={14}/>:<Copy size={14}/>} {copied===share.id?'Copied':'Copy invitation'}</button><a href={share.invitationPath} target="_blank" rel="noreferrer" className="text-button">Invitation address <ArrowUpRight size={13}/></a>{share.status==='active'&&<button className="button secondary small" disabled={busy} onClick={()=>void revoke(share)}>Revoke access</button>}</div>}</article>)}
 {list?.page.hasMore&&<button className="button secondary small" disabled={busy} onClick={async()=>{const operation=operations.start();setBusy(true);try{const next=await api<StudioClientDeliveryList>(path+'?after='+list.page.nextAfter,'GET',undefined,{signal:operation.signal});if(operation.current())setList({...next,shares:[...list.shares,...next.shares]});}catch(e){if(operation.current())setError((e as Error).message);}finally{if(operation.current())setBusy(false);operation.finish();}}}>Load more invitations</button>}
 </section>;
}

export function StudioClientPortal({shareId}:{shareId?:string}){
 const [session,setSession]=useState<Session|null>(null),[identity,setIdentity]=useState<{id:string;name:string;email:string;emailVerified:boolean}|null>(null),[data,setData]=useState<StudioClientDeliveryDetail|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false),[decision,setDecision]=useState<'acknowledged'|'changes_requested'>('acknowledged'),[filter,setFilter]=useState(''),[page,setPage]=useState(0),[access,setAccess]=useState<Record<string,{url:string;expiresAt:string}>>({});
 const requestId=useRequests(),generation=useRef(0),path=shareId?'/api/client-deliveries/'+shareId:null;
 const operations=useClientOperations(`${shareId??''}:${session?.user?.id??''}`),downloadActive=useRef<(()=>void)|null>(null),[downloading,setDownloading]=useState(''),[progress,setProgress]=useState('');
 const sessionLoad=useCallback(async()=>{const operation=operations.start();setError('');try{const result=await api<Session>('/api/session','GET',undefined,{signal:operation.signal});if(operation.current()){setClientIdentity(result.user?.id??null);setSession(result);}}catch(e){if(operation.current())setError((e as Error).message);}finally{operation.finish();}},[]);
 useEffect(()=>{void sessionLoad();const changed=()=>{operations.cancel();generation.current++;setData(null);setIdentity(null);setAccess({});setNotice('');setBusy(false);setDownloading('');setProgress('');downloadActive.current=null;void sessionLoad();};window.addEventListener('coatria:session-changed',changed);return()=>window.removeEventListener('coatria:session-changed',changed);},[sessionLoad,operations.cancel]);
 const reload=useCallback(async(signal?:AbortSignal)=>{if(!path)return;const ticket=++generation.current,operation=operations.start(),combined=signal?AbortSignal.any([signal,operation.signal]):operation.signal;try{const result=await api<StudioClientDeliveryDetail>(path,'GET',undefined,{signal:combined});if(!combined.aborted&&ticket===generation.current){setData(result);setError('');}}catch(e){if(!combined.aborted&&ticket===generation.current){setData(null);setAccess({});setError((e as Error).message);}}finally{operation.finish();}},[path]);
 useEffect(()=>{setData(null);setAccess({});setIdentity(null);setNotice('');setError('');if(!session?.user)return;const controller=new AbortController(),operation=operations.start(),signal=AbortSignal.any([controller.signal,operation.signal]),userId=session.user.id;let alive=true;void(async()=>{try{const who=await api<{user:NonNullable<typeof identity>}>('/api/client-deliveries/identity','GET',undefined,{signal});if(!alive||signal.aborted)return;setIdentity(who.user);await reload(signal);if(path&&!signal.aborted){await api(path+'/open','POST',{clientId:requestId('open:'+userId+':'+path,{})},{signal});}}catch(e){if(!signal.aborted)setError((e as Error).message);}finally{operation.finish();}})();return()=>{alive=false;generation.current++;controller.abort();};},[session?.user?.id,path,reload]); // Request IDs intentionally persist through an uncertain-response retry.
 useEffect(()=>{const timer=setInterval(()=>setAccess(current=>Object.fromEntries(Object.entries(current).filter(([,value])=>Date.parse(value.expiresAt)>Date.now()))),1000);return()=>clearInterval(timer);},[]);
 function fileAccess(file:StudioClientDeliveryFile){
  if(!path||busy||downloadActive.current)return;
  if(data?.package.schemaVersion===2){
   const generated=file as StudioGeneratedClientDeliveryFile;
   if(!canStreamStorageDownload()&&file.bytes>STORAGE_BROWSER_BLOB_LIMIT){setError('This file needs a browser with a file save picker. Use desktop Chrome or Edge to save it without loading the complete file into memory.');return;}
   const operation=operations.start(),logicalId=crypto.randomUUID();downloadActive.current=operation.cancel;setBusy(true);setDownloading(file.fileId);setProgress('Choose where to save this exact version…');setError('');setNotice('');
   const destination=chooseStorageDownloadTarget(file.path);
   void(async()=>{let target:StorageSaveTarget|null=null;const timeout=setTimeout(operation.cancel,60*60_000);
    try{
     target=await destination;operation.signal.throwIfAborted();
     const renew=async()=>{operation.signal.throwIfAborted();const result=await api<{access:StudioGeneratedClientAccess}>(path+'/files/'+file.fileId+'/access','POST',{clientId:logicalId},{signal:operation.signal});operation.signal.throwIfAborted();return result.access;};
     const initial=await renew(),result=await downloadGeneratedClientFile(initial,generated,target,{signal:operation.signal,renew,onProgress:bytes=>{if(operation.current())setProgress(`${generatedBytes(bytes)} of ${generatedBytes(file.bytes)}`);}});operation.signal.throwIfAborted();
     if(operation.current()){if(result.blob){const url=URL.createObjectURL(result.blob),link=document.createElement('a');link.href=url;link.download=file.path;link.click();setTimeout(()=>URL.revokeObjectURL(url),30_000);}setNotice((result.blob?'The exact file checksum is verified and the browser download has started.':'This browser verified the exact file checksum and completed the save.')+' This local result does not acknowledge the package or create a server download receipt.');await reload(operation.signal);}
    }catch(e){await target?.abort(e).catch(()=>{});if(operation.current())setError((e as Error).message);}
    finally{clearTimeout(timeout);if(downloadActive.current===operation.cancel){downloadActive.current=null;setBusy(false);setDownloading('');setProgress('');}operation.finish();}
   })();return;
  }
  const operation=operations.start();setBusy(true);setError('');void(async()=>{try{const result=await api<{access:{url:string;expiresAt:string}}>(path+'/files/'+file.fileId+'/access','POST',{clientId:crypto.randomUUID()},{signal:operation.signal});if(operation.current()){setAccess(current=>({...current,[file.fileId]:result.access}));setNotice('Your private download link is ready for up to 60 seconds. Opening it does not automatically acknowledge this package.');await reload(operation.signal);}}catch(e){if(operation.current())setError((e as Error).message);}finally{if(operation.current())setBusy(false);operation.finish();}})();
 }
 async function respond(){if(!path||!data||busy)return;const operation=operations.start();setBusy(true);setError('');try{const payload={revision:data.share.revision,decision,note:note.trim()};await api(path+'/responses','POST',{...payload,clientId:requestId('respond:'+session?.user?.id+':'+path,payload)},{signal:operation.signal});if(operation.current()){setNotice(decision==='acknowledged'?'Your acknowledgement of this exact package is recorded.':'Your change request is recorded. The studio can now plan follow-up work.');await reload(operation.signal);}}catch(e){if(operation.current())setError((e as Error).message);}finally{if(operation.current())setBusy(false);operation.finish();}}
 async function signOut(){operations.cancel();downloadActive.current=null;setDownloading('');setProgress('');const operation=operations.start();setBusy(true);try{await api('/api/auth/logout','POST',{},{signal:operation.signal});if(operation.current()){generation.current++;setClientIdentity(null);setSession({user:null,companies:[]});setIdentity(null);setData(null);setAccess({});setError('');}}catch(e){if(operation.current())setError((e as Error).message);}finally{if(operation.current())setBusy(false);operation.finish();}}
 if(!session)return <main id="main" className={styles.portal}><Brand/><p role="status">Opening your private delivery portal…</p><ErrorNote error={error}/>{error&&<button className="button primary" onClick={()=>void sessionLoad()}>Try again</button>}</main>;
 if(!session.user)return <div><div className={styles.authBanner}><LockKeyhole size={17}/><span>Client delivery portal · Sign in with the exact account you gave the studio. You do not need a company workspace.</span></div><Auth invite="" onSession={result=>{setClientIdentity(result.user?.id??null);setSession(result);}} onExplore={()=>{location.href='/';}}/></div>;
 const files=data?.package.files.filter(file=>file.path.toLowerCase().includes(filter.toLowerCase()))??[],shown=files.slice(page*50,(page+1)*50);
 return <div className={styles.portal}><header className={styles.top}><a href="/delivery" aria-label="Coatria client delivery home"><Brand/></a><div className={styles.actions}><span>{session.user.name}</span><button className="button secondary small" disabled={busy} onClick={()=>void signOut()}>Sign out</button></div></header><main id="main"><div className={styles.hero}><span className={styles.eyebrow}>COATRIA · CLIENT DELIVERY</span><h1>{data?data.package.delivery.name:shareId?'Your private project handoff.':'Your account. Your project handoff.'}</h1><p>{data?`${data.package.project.name} · ${data.package.project.clientName}`:shareId?'Access belongs to the exact client account selected by the studio.':'Give your studio this account ID through your existing trusted communication channel. You can receive a private package without joining their company.'}</p></div><ErrorNote error={error}/>{notice&&<p className={styles.notice} role="status">{notice}</p>}
 {identity&&<section className={styles.identity}><ShieldCheck size={22}/><div><strong>Signed in as {identity.name}</strong><p>Coatria account <code>{identity.id}</code></p><small>{identity.emailVerified?'Email verified':'Email ownership is not verified. The studio must confirm this account directly with you.'}</small></div><button className="button secondary small" onClick={async()=>{try{await navigator.clipboard.writeText(identity.id);setCopied(true);}catch{setError('Select and copy the account ID shown here.');}}}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy account ID'}</button></section>}
 {shareId&&!data&&<button className="button secondary" onClick={()=>void reload()}><RefreshCw size={16}/> Check access again</button>}
 {data&&<><section className={styles.summary}><div><span className={styles.badge}>{data.share.response.replaceAll('_',' ')}</span><h2>One approved package, preserved.</h2>{data.package.schemaVersion===2&&data.package.revisionRound&&<p><strong>Revision round {data.package.revisionRound.number}</strong> · This is a new exact package with its own response. Earlier packages and responses remain unchanged.</p>}<p>{data.package.files.length} verified private files · Access expires {stamp(data.share.expiresAt)}</p><p className={styles.note}>The studio independently approved these versions. Download links are temporary; access issuance does not prove that you received a file. Your response below is a separate acknowledgement.</p></div><a className="button secondary" href={path+'/manifest'}><Download size={16}/> Download manifest</a></section><details className={styles.checksum}><summary>Package checksum and included versions</summary><p>SHA-256 <code>{data.share.packageSha256}</code></p>{data.package.artifacts.map(artifact=><p key={artifact.id}>{artifact.name} · Version {artifact.version} · <code>{artifact.sha256}</code></p>)}</details>
 <section className={styles.files} aria-label="Package files"><div className={styles.heading}><h2>Your files</h2><label className={styles.search}>Find a file<input type="search" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}} placeholder="Filter by filename"/></label></div>{data.package.schemaVersion===2&&<p className={styles.note}>Each download checks the complete file checksum before saving. Access is rechecked as the file arrives; keep this portal open. Your response remains a separate decision.</p>}<div className={styles.fileList}>{shown.map(file=><article key={file.fileId} className={styles.file}><FileCheck2 size={19}/><div><strong>{file.path}</strong><span>{'mediaKind' in file?String(file.mediaKind):file.frame===null?'File':'Frame '+file.frame} · {generatedBytes(file.bytes)}</span><details><summary>SHA-256{data.package.schemaVersion===2?' & stored version':''}</summary><code>{file.sha256}</code>{'storageVersionId' in file&&<p>Storage version <code>{String(file.storageVersionId)}</code></p>}</details>{downloading===file.fileId&&<><p role="status">{progress}</p><button type="button" className="button secondary small" onClick={()=>{downloadActive.current?.();setNotice('Download cancelled. No acknowledgement was recorded.');}}>Cancel download</button></>}</div>{data.package.schemaVersion!==2&&access[file.fileId]?<a className="button primary small" href={access[file.fileId].url} target="_blank" rel="noopener noreferrer">Open file <ArrowUpRight size={14}/></a>:<button className="button secondary small" disabled={busy} onClick={()=>fileAccess(file)}>{downloading===file.fileId?'Downloading…':data.package.schemaVersion===2?'Download verified file':'Get download link'} <Download size={14}/></button>}</article>)}</div>{!shown.length&&<p>No files match your search.</p>}<div className={styles.actions}><button className="button secondary small" disabled={page===0} onClick={()=>setPage(value=>value-1)}>Previous</button><span>{files.length?`${page*50+1}–${Math.min(files.length,(page+1)*50)} of ${files.length}`:'0 files'}</span><button className="button secondary small" disabled={(page+1)*50>=files.length} onClick={()=>setPage(value=>value+1)}>Next</button></div></section>
 <section className={styles.response}><span className={styles.eyebrow}>YOUR RESPONSE</span><h2>{data.canRespond?'Tell the studio where this stands.':data.share.response==='awaiting_response'?'The studio is preparing this handoff.':'Your response is on record.'}</h2>{data.canRespond?<form onSubmit={event=>{event.preventDefault();void respond();}}><div className={styles.choices}><label><input type="radio" name="decision" checked={decision==='acknowledged'} onChange={()=>setDecision('acknowledged')}/> Acknowledge this package</label><label><input type="radio" name="decision" checked={decision==='changes_requested'} onChange={()=>setDecision('changes_requested')}/> Request changes</label></div><label>Note to the studio<textarea required minLength={1} maxLength={4000} value={note} onChange={e=>setNote(e.target.value)} placeholder={decision==='acknowledged'?'Confirm your review of this exact package.':data.package.schemaVersion===2?'Name the file and describe the changes. Include a timestamp for video or audio when helpful.':'Describe the changes you need, including frame numbers where relevant.'}/></label><label className={styles.check}><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I am responding as the intended client to this exact package. This records my account and preserves my response.</span></label><button className="button primary" disabled={busy||!confirmed||!note.trim()}>{busy?'Recording…':decision==='acknowledged'?'Record acknowledgement':'Send change request'}</button></form>:<p>{data.responseBlockedReason}</p>}</section>
 <section className={styles.receipts}><h2>Access and response record</h2>{data.receipts.map(event=><p key={event.id}><strong>{event.kind.replaceAll('_',' ')}</strong> · {stamp(event.createdAt)}{event.note&&<span className={styles.receiptNote}>{event.note}</span>}</p>)}{!data.receipts.length&&<p>Your first portal-open receipt will appear when you refresh.</p>}{data.receiptPage.hasMore&&<button className="button secondary small" disabled={busy} onClick={async()=>{const operation=operations.start();setBusy(true);try{const more=await api<StudioClientDeliveryDetail>(path+'?after='+data.receiptPage.nextAfter,'GET',undefined,{signal:operation.signal});if(operation.current())setData({...more,receipts:[...data.receipts,...more.receipts]});}catch(e){if(operation.current())setError((e as Error).message);}finally{if(operation.current())setBusy(false);operation.finish();}}}>Load more receipts</button>}</section></>}
 </main><footer className={styles.footer}>Private by invitation. Account-bound access. No company membership required.</footer></div>;
}
