'use client';
import {useState,type FormEvent} from 'react';
import {ArrowRight,Check,Download,Film,Layers3,Plus,RefreshCw,Server,ShieldCheck,Square} from 'lucide-react';
import type {WorkspaceProps} from '@/app/page';
import type {StudioProjectDetail} from '@/lib/studio-protocol';
import {EXECUTION_BUILTIN_PROFILES,type ExecutionProfile,type ExecutionManifest,type ExecutionStatus} from '@/lib/studio-execution-protocol';
import {when} from '@/lib/client';
import {Field,Loading,Modal,Secret} from './ui';
import {useStudioMutation,useStudioResource} from './studio-hooks';
import {StudioMediaPanel} from './StudioMediaPanel';
import s from './StudioWorkspace.module.css';

type Connector={id:string;name:string;profiles:ExecutionProfile[];status:string;revision:number;expiresAt:string;lastSeenAt:string|null};
type InputRef={id:string;projectId:string;name:string;kind:string;storageKey:string;sha256:string;bytes:number};
type Job={id:string;projectId:string;workItemId:string;connectorId:string;status:ExecutionStatus;revision:number;profile:ExecutionProfile;spec:StudioProjectDetail['project']['spec'];inputReferences:InputRef[];frameStart:number;frameEnd:number;createdAt:string;failureReason:string|null;outputKind:string;effectiveStatus?:ExecutionStatus;output?:{manifest:ExecutionManifest;manifestHash:string;verificationSource:string}|null};
type Snapshot={connectors:Connector[];inputs:InputRef[];jobs:Job[];page:{hasMore:boolean;nextAfter:string|null}};
const label=(value:string)=>value.replaceAll('_',' ');
const bytes=(value:number)=>value>=1024*1024?`${(value/1024/1024).toFixed(1)} MB`:`${Math.ceil(value/1024)} KB`;
function Status({value}:{value:string}){return <span className={s.status} data-state={value}>{label(value)}</span>;}
function saveManifest(job:Job){const url=URL.createObjectURL(new Blob([JSON.stringify({jobId:job.id,profile:job.profile,spec:job.spec,inputs:job.inputReferences,output:job.output},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`coatria-execution-${job.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function StudioExecutionPanel({p,detail,onRefresh}:{p:WorkspaceProps;detail:StudioProjectDetail;onRefresh:()=>Promise<void>}){
 const [after,setAfter]=useState<string|null>(null),[history,setHistory]=useState<Array<string|null>>([]),[inputAfter,setInputAfter]=useState<string|null>(null);
 const base=`/api/companies/${p.company.id}/studio/execution`,resource=useStudioResource<Snapshot>(`${base}?projectId=${detail.project.id}&kind=jobs&limit=25${after?'&after='+after:''}`),connections=useStudioResource<Snapshot>(`${base}?kind=connectors&limit=100`),inputs=useStudioResource<Snapshot>(`${base}?projectId=${detail.project.id}&kind=inputs&limit=100${inputAfter?'&after='+inputAfter:''}`),admin=['owner','admin'].includes(p.company.role);
 const [connect,setConnect]=useState(false),[propose,setPropose]=useState(false),[input,setInput]=useState(false),[jobId,setJobId]=useState<string|null>(null);
 const data=resource.data?{...resource.data,connectors:connections.data?.connectors||[],inputs:inputs.data?.inputs||[]}:null;
 const refresh=async()=>{await Promise.all([resource.reload(),connections.reload(),inputs.reload(),onRefresh()]);};
 return <><div className={s.heading}><div><h2>Production, with evidence.</h2><p>Approved jobs run on a connected renderer. Every result keeps its inputs, profile, and file checks.</p></div><div className={s.actions}><button className="button secondary small" onClick={()=>void refresh()}><RefreshCw size={14}/> Refresh</button>{admin&&<button className="button primary small" disabled={!data?.connectors.some(connector=>connector.status==='active')} onClick={()=>setPropose(true)}><Plus size={15}/> Propose render</button>}</div></div>
  {(resource.error||connections.error||inputs.error)&&<p className="error-message" role="alert">{resource.error||connections.error||inputs.error}</p>}{resource.loading?<Loading label="Loading production jobs"/>:data&&<>
   <div className={s.metrics}><div className={s.metric}><span>Awaiting approval</span><strong>{data.jobs.filter(job=>job.status==='awaiting_approval').length}</strong><small>Review exact jobs before execution</small></div><div className={s.metric}><span>Queued or running</span><strong>{data.jobs.filter(job=>['queued','running'].includes(job.status)).length}</strong><small>Durable jobs with worker leases</small></div><div className={s.metric}><span>Rendered</span><strong>{data.jobs.filter(job=>job.status==='succeeded').length}</strong><small>Connector-reported file evidence</small></div><div className={s.metric}><span>Needs attention</span><strong>{data.jobs.filter(job=>['failed','failed_uncertain'].includes(job.status)).length}</strong><small>Reconcile before a new attempt</small></div></div>
   <section className={s.section}><div className={s.heading}><div><h3>Render connections</h3><p>A registered connection needs a running worker to process jobs.</p></div>{admin&&<button className="button secondary small" onClick={()=>setConnect(true)}><Server size={14}/> Add connection</button>}</div>{!data.connectors.length?<p>No renderer connected. Start with the controlled Blender product turntable profile.</p>:data.connectors.map(connector=><ConnectorRow key={connector.id} connector={connector} base={base} admin={admin} onSaved={refresh}/>)}</section>
   <div className={s.heading}><h3>Render jobs</h3><span className={s.count}>{data.jobs.length} loaded</span></div>{!data.jobs.length?<div className={s.emptyInline}><Film size={24}/><h3>The queue is ready for your first render.</h3><p>Approve the project’s production gates and finish upstream work, then propose a job for a CG or VFX task.</p></div>:<div className={s.projectGrid}>{data.jobs.map(job=><button className={s.projectCard} key={job.id} onClick={()=>setJobId(job.id)}><div className={s.projectTop}><Layers3 size={19}/><Status value={job.effectiveStatus||job.status}/></div><h3>{detail.workItems.find(work=>work.id===job.workItemId)?.title||'Production job'}</h3><p>{job.profile.key} · v{job.profile.version}</p><p>Frames {job.frameStart}–{job.frameEnd} · {job.spec.width} × {job.spec.height}</p><footer><span>{when(job.createdAt)}</span><ArrowRight size={15}/></footer></button>)}</div>}
   {(data.page.hasMore||history.length>0)&&<div className={s.heading}><span>Job page {history.length+1}</span><div className={s.actions}><button className="button secondary small" disabled={!history.length} onClick={()=>{setAfter(history.at(-1)??null);setHistory(history.slice(0,-1));}}>Previous</button><button className="button secondary small" disabled={!data.page.hasMore} onClick={()=>{setHistory([...history,after]);setAfter(data.page.nextAfter);}}>Next</button></div></div>}
   <section className={s.section}><div className={s.heading}><div><h3>Approved input references</h3><p>Inputs identify files on the worker’s approved storage by path, size, and SHA-256 hash.</p></div>{admin&&<button className="button secondary small" onClick={()=>setInput(true)}><Plus size={14}/> Register input</button>}</div>{!data.inputs.length?<p>No external inputs registered. The built-in procedural turntable creates its own original scene.</p>:data.inputs.map(reference=><div key={reference.id} className={s.assignment}><div><h4>{reference.name}</h4><p>{reference.kind} · {bytes(reference.bytes)}</p><code style={{overflowWrap:'anywhere'}}>{reference.storageKey}</code></div></div>)}</section>
   {(inputs.data?.page.hasMore||inputAfter)&&<div className={s.actions}><button className="button secondary small" disabled={!inputAfter} onClick={()=>setInputAfter(null)}>First input page</button><button className="button secondary small" disabled={!inputs.data?.page.hasMore} onClick={()=>setInputAfter(inputs.data?.page.nextAfter||null)}>Next input page</button></div>}
   <div className={s.notice}><ShieldCheck size={18}/><p>Successful execution records the connector’s file checks. Independent media review and the final delivery decision remain separate production steps.</p></div>
  </>}
  {connect&&<ConnectRenderer base={base} onClose={()=>setConnect(false)} onSaved={refresh}/>}
  {propose&&data&&<ProposeRender base={base} detail={detail} data={data} onClose={()=>setPropose(false)} onSaved={async job=>{setPropose(false);setJobId(job.id);await refresh();}}/>}
  {input&&<RegisterInput base={base} projectId={detail.project.id} onClose={()=>setInput(false)} onSaved={async()=>{setInput(false);await refresh();}}/>}
  {jobId&&<ExecutionDetail key={jobId} base={base} jobId={jobId} companyId={p.company.id} revision={detail.project.revision} admin={admin} onClose={()=>setJobId(null)} onSaved={refresh}/>}
 </>;
}

function ConnectorRow({connector,base,admin,onSaved}:{connector:Connector;base:string;admin:boolean;onSaved:()=>Promise<void>}){
 const mutation=useStudioMutation();
 return <div className={s.assignment}><div><h4>{connector.name} <Status value={connector.status}/></h4><p>{connector.profiles.map(profile=>profile.key+' v'+profile.version).join(', ')}</p><p>{connector.lastSeenAt?`Last worker contact ${when(connector.lastSeenAt)}`:'Worker has not connected'} · Expires {new Date(connector.expiresAt).toLocaleDateString()}</p>{mutation.error&&<p role="alert" className="error-message">{mutation.error}</p>}</div>{admin&&connector.status!=='revoked'&&<button className="button secondary small" disabled={mutation.busy} onClick={()=>void mutation.mutate(`${base}/connectors/${connector.id}`,{revision:connector.revision,status:connector.status==='active'?'paused':'active'},onSaved,'PATCH')}>{connector.status==='active'?'Pause connection':'Resume connection'}</button>}</div>;
}
function ConnectRenderer({base,onClose,onSaved}:{base:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const mutation=useStudioMutation(),[name,setName]=useState('Studio Blender renderer'),[token,setToken]=useState<string|null>(null),[registered,setRegistered]=useState(false),profile=EXECUTION_BUILTIN_PROFILES[0];
 async function submit(event:FormEvent){event.preventDefault();await mutation.mutate<{token:string|null}>(`${base}/connectors`,{name,profiles:[profile],expiresInDays:30},async result=>{setToken(result.token);setRegistered(true);await onSaved();});}
 return <Modal title="Connect a Blender renderer" description="Register a scoped worker for a reviewed production profile." onClose={()=>{if(!mutation.busy)onClose();}}>{registered?<>{token?<Secret token={token} title="Save the renderer credential"/>:<p className={s.notice}>This connection was already registered. Its credential is shown only on the first successful response.</p>}<p>Install the reviewed VFX worker on your render host, configure its private output directory and Blender executable, then set this credential as COATRIA_EXECUTION_TOKEN.</p><p>Registration creates a connection record. It does not start a server or incur rendering charges.</p><button className="button primary" onClick={onClose}>Connection saved <Check size={15}/></button></>:<form className="form" onSubmit={submit}><fieldset disabled={mutation.busy}><Field label="Connection name"><input required maxLength={160} value={name} onChange={event=>setName(event.target.value)}/></Field><div className={s.reviewSummary}><h3>Original product turntable · Blender</h3><p>Creates a controlled scene, linear EXR sequence, review image, and verified file manifest.</p><p>Up to {profile.maxFrames} frames · {profile.maxWidth} × {profile.maxHeight} · {profile.timeoutSeconds} seconds per job</p><p>Profile {profile.key}, version {profile.version}. This profile creates its own scene and accepts no uploaded Blender scripts.</p></div></fieldset>{mutation.error&&<p role="alert" className="error-message">{mutation.error}</p>}<button className="button primary" disabled={mutation.busy}>{mutation.busy?'Registering…':'Register render connection'} <ArrowRight size={15}/></button></form>}</Modal>;
}
function ProposeRender({base,detail,data,onClose,onSaved}:{base:string;detail:StudioProjectDetail;data:Snapshot;onClose:()=>void;onSaved:(job:Job)=>Promise<void>}){
 const mutation=useStudioMutation(),works=detail.workItems.filter(work=>work.execution==='dcc'&&!['done','review'].includes(work.status));
 const [workId,setWorkId]=useState(works.find(work=>!work.blockedReason)?.id||works[0]?.id||''),[connectorId,setConnectorId]=useState(data.connectors.find(item=>item.status==='active')?.id||''),[profileIndex,setProfileIndex]=useState(0),[inputIds,setInputIds]=useState<string[]>([]);
 const work=works.find(item=>item.id===workId),shot=detail.shots.find(shot=>shot.id===work?.shotId),connector=data.connectors.find(item=>item.id===connectorId),profile=connector?.profiles[profileIndex];
 const [customStart,setCustomStart]=useState<number|null>(null),[customEnd,setCustomEnd]=useState<number|null>(null),start=customStart??Math.max(0,(shot?.frameStart||0)-(shot?.handles||0)),end=customEnd??(shot?.frameEnd||0)+(shot?.handles||0);
 async function submit(event:FormEvent){event.preventDefault();if(!profile)return;await mutation.mutate<{job:Job}>(`${base}/jobs`,{projectId:detail.project.id,revision:detail.project.revision,workItemId:workId,connectorId,profileKey:profile.key,profileVersion:profile.version,inputIds,frameStart:start,frameEnd:end,outputKind:'image_sequence'},result=>onSaved(result.job));}
 return <Modal title="Propose a production render" description="Pin the work, profile, and inputs. Review the resulting job before approving execution." onClose={()=>{if(!mutation.busy)onClose();}}><form className="form" onSubmit={submit}><fieldset disabled={mutation.busy}>
  <Field label="Production work"><select required value={workId} onChange={event=>{setWorkId(event.target.value);setCustomStart(null);setCustomEnd(null);}}>{!works.length&&<option value="">No available DCC tasks</option>}{works.map(work=><option key={work.id} value={work.id}>{work.title}{work.blockedReason?' · blocked':''}</option>)}</select></Field>
  <Field label="Render connection"><select required value={connectorId} onChange={event=>{setConnectorId(event.target.value);setProfileIndex(0);setInputIds([]);}}>{data.connectors.filter(item=>item.status==='active').map(connector=><option key={connector.id} value={connector.id}>{connector.name}</option>)}</select></Field>
  <Field label="Approved profile"><select value={profileIndex} onChange={event=>{setProfileIndex(Number(event.target.value));setInputIds([]);}}>{connector?.profiles.map((profile,index)=><option key={profile.key+profile.version} value={index}>{profile.key} · v{profile.version}</option>)}</select></Field>
  <div className={s.formGrid}><Field label="First frame"><input required type="number" min={0} value={start} onChange={event=>setCustomStart(Number(event.target.value))}/></Field><Field label="Last frame"><input required type="number" min={start} value={end} onChange={event=>setCustomEnd(Number(event.target.value))}/></Field></div>
  {profile&&profile.inputKinds.length>0&&<fieldset><legend>Pinned inputs</legend>{data.inputs.filter(item=>(profile.inputKinds as string[]).includes(item.kind)).map(item=><label key={item.id}><input type="checkbox" checked={inputIds.includes(item.id)} onChange={event=>setInputIds(event.target.checked?[...inputIds,item.id]:inputIds.filter(id=>id!==item.id))}/>{item.name} · {bytes(item.bytes)}</label>)}</fieldset>}
  <p className={s.notice}>{detail.project.spec.width} × {detail.project.spec.height} · {detail.project.spec.fpsNumerator}/{detail.project.spec.fpsDenominator} fps · {detail.project.spec.colorSpace}. The worker must support this exact specification.</p>
  {work?.blockedReason&&<p role="status" className="error-message">{work.blockedReason}</p>}
 </fieldset>{mutation.error&&<p role="alert" className="error-message">{mutation.error}</p>}<button className="button primary" disabled={mutation.busy||!profile||!work||Boolean(work.blockedReason)}>{mutation.busy?'Preparing job…':'Prepare job for approval'} <ArrowRight size={15}/></button></form></Modal>;
}
function RegisterInput({base,projectId,onClose,onSaved}:{base:string;projectId:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const mutation=useStudioMutation();
 return <Modal title="Register a production input" description="Reference an existing file on approved storage. This form does not upload the file." onClose={()=>{if(!mutation.busy)onClose();}}><form className="form" onSubmit={event=>{event.preventDefault();const values=new FormData(event.currentTarget);void mutation.mutate(`${base}/inputs`,{projectId,name:values.get('name'),kind:values.get('kind'),storageKey:values.get('storageKey'),sha256:values.get('sha256'),bytes:Number(values.get('bytes'))},onSaved);}}><fieldset disabled={mutation.busy}><Field label="Input name"><input name="name" required maxLength={160}/></Field><Field label="File kind"><select name="kind">{['scene','cache','image_sequence','media'].map(value=><option key={value} value={value}>{label(value)}</option>)}</select></Field><Field label="Approved relative storage path" hint="Relative to the worker’s configured input root."><input name="storageKey" required placeholder="project/plates/shot-010.exr" maxLength={512}/></Field><Field label="SHA-256"><input name="sha256" required pattern="[a-f0-9]{64}" maxLength={64}/></Field><Field label="File size in bytes"><input name="bytes" required type="number" min={1} max={100000000000}/></Field></fieldset>{mutation.error&&<p role="alert" className="error-message">{mutation.error}</p>}<button className="button primary" disabled={mutation.busy}>Register pinned input <Check size={15}/></button></form></Modal>;
}
function ExecutionDetail({base,jobId,companyId,revision,admin,onClose,onSaved}:{base:string;jobId:string;companyId:string;revision:number;admin:boolean;onClose:()=>void;onSaved:()=>Promise<void>}){
 const resource=useStudioResource<{job:Job}>(`${base}/jobs/${jobId}`),mutation=useStudioMutation(),job=resource.data?.job;
 async function action(name:'approve'|'cancel'){if(!job)return;await mutation.mutate(`${base}/jobs/${jobId}/${name}`,{revision:job.revision},async()=>{await Promise.all([resource.reload(),onSaved()]);});}
 return <Modal title="Production job" description="Review the exact work order and the evidence returned by its connector." onClose={()=>{if(!mutation.busy)onClose();}} wide>{resource.loading?<Loading label="Loading job details"/>:job&&<div className={s.formSection}>
  <div className={s.heading}><div><h3>{job.profile.key} · v{job.profile.version}</h3><code>{job.id}</code></div><Status value={job.effectiveStatus||job.status}/></div>
  <dl className={s.summaryRows}><div><dt>Frames</dt><dd>{job.frameStart}–{job.frameEnd}</dd></div><div><dt>Resolution</dt><dd>{job.spec.width} × {job.spec.height}</dd></div><div><dt>Frame rate</dt><dd>{job.spec.fpsNumerator}/{job.spec.fpsDenominator}</dd></div><div><dt>Working color space</dt><dd>{job.spec.colorSpace}</dd></div><div><dt>Time limit</dt><dd>{job.profile.timeoutSeconds} seconds</dd></div><div><dt>Output size limit</dt><dd>{bytes(job.profile.maxOutputBytes)}</dd></div><div><dt>Inputs</dt><dd>{job.inputReferences.length} pinned references</dd></div></dl>
  {job.inputReferences.length>0&&<details><summary>Inspect pinned inputs</summary>{job.inputReferences.map(input=><div key={input.id}><strong>{input.name}</strong><p>{input.storageKey} · {bytes(input.bytes)}</p><code style={{overflowWrap:'anywhere'}}>{input.sha256}</code></div>)}</details>}
  {job.failureReason&&<p role="status" className="error-message">{label(job.failureReason)}. Check the worker’s preserved outputs before proposing another job.</p>}
  {job.output&&<><div className={s.notice}><ShieldCheck size={18}/><div><strong>File checks reported by the connector</strong><p>{job.output.manifest.engineVersion} · {job.output.manifest.files.length} files. Review the actual media before accepting this work.</p></div></div><div className={s.heading}><h3>Output manifest</h3><button className="button secondary small" onClick={()=>saveManifest(job)}><Download size={14}/> Download evidence</button></div><details><summary>Inspect the full output manifest</summary><div style={{maxHeight:300,overflow:'auto'}}>{job.output.manifest.files.map(file=><div className={s.assignment} key={file.path}><div><h4 style={{overflowWrap:'anywhere'}}>{file.path}</h4><p>{file.kind} · {bytes(file.bytes)}{file.frame!==undefined?` · Frame ${file.frame}`:''}</p><code style={{overflowWrap:'anywhere'}}>{file.sha256}</code></div></div>)}</div></details></>}
  {job.output&&<StudioMediaPanel companyId={companyId} jobId={jobId} revision={revision} admin={admin} frameCount={job.frameEnd-job.frameStart+1} onSaved={onSaved}/>}
  {admin&&job.status==='awaiting_approval'&&<><p>Approval queues this exact job on the connected renderer. It may use your provisioned compute. The server rechecks the project’s gates and dependencies.</p><button className="button primary" disabled={mutation.busy} onClick={()=>void action('approve')}><Check size={15}/>{mutation.busy?'Saving…':'Approve this render job'}</button></>}
  {admin&&['awaiting_approval','queued','running'].includes(job.status)&&<button className="button secondary" disabled={mutation.busy} onClick={()=>void action('cancel')}><Square size={14}/> Cancel job</button>}
 </div>}{(resource.error||mutation.error)&&<p role="alert" className="error-message">{resource.error||mutation.error} <button className="text-button" onClick={()=>void resource.reload()}>Reload job</button></p>}</Modal>;
}
