'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowLeft,ArrowRight,CheckCircle2,Download,FlaskConical,Layers3,Pause,Play,RotateCcw,Upload,Users,Wifi,AlertCircle} from 'lucide-react';
import type {WorkspaceProps} from '@/app/page';
import {OFFICE_50_PRESET} from '@/lib/office-presets';
import {readConnectionReport,simulationMembers,simulationPresence,type ConnectionReport,type SimulationScenario} from '@/lib/office-simulation';
import OfficeScene,{type OfficeDiagnostics} from './OfficeScene';
import OfficePresetPreview from './OfficePresetPreview';
import {Badge,CopyButton,Field,PageHead} from './ui';
import s from './TesterView.module.css';

type Sample={second:number;fps:number;p95:number;drawCalls:number;triangles:number};
type ReferenceSource={sourceCommit:string;ciUrl:string};
const reportLimit=1024*1024;
async function readReferenceResponse(response:Response){
  const tooLarge=()=>new Error('The reference report exceeds the 1 MB limit.');
  if(Number(response.headers.get('content-length'))>reportLimit)throw tooLarge();
  if(!response.body)throw new Error('The reference run contains no report.');
  const reader=response.body.getReader(),decoder=new TextDecoder();let bytes=0,text='';
  try{while(true){const chunk=await reader.read();if(chunk.done)break;bytes+=chunk.value.byteLength;if(bytes>reportLimit){await reader.cancel();throw tooLarge();}text+=decoder.decode(chunk.value,{stream:true});}text+=decoder.decode();}finally{reader.releaseLock();}
  const value=JSON.parse(text),report=readConnectionReport(value),reference=value.reference;
  if(!reference||typeof reference.sourceCommit!=='string'||!/^[0-9a-f]{40}$/i.test(reference.sourceCommit)||typeof reference.ciUrl!=='string'||!/^https:\/\/github\.com\/stratostormstudios\/coatria\/actions\/runs\/\d+$/.test(reference.ciUrl))throw new Error('The reference run is missing valid source and CI details.');
  return{report,reference:{sourceCommit:reference.sourceCommit,ciUrl:reference.ciUrl} as ReferenceSource};
}
const noAction=()=>{};
const fmt=(value:number|undefined,digits=0)=>value===undefined||!Number.isFinite(value)?'—':value.toLocaleString(undefined,{maximumFractionDigits:digits});
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function TesterView(p:WorkspaceProps&{onBack:()=>void;onEdit:()=>void}){
  const [tab,setTab]=useState<'visual'|'plan'|'connections'>('visual'),[count,setCount]=useState(50),[scenario,setScenario]=useState<SimulationScenario>('working'),[duration,setDuration]=useState(60),[running,setRunning]=useState(false),[elapsed,setElapsed]=useState(0),[epoch,setEpoch]=useState(0),[diagnostics,setDiagnostics]=useState<OfficeDiagnostics>({}),[samples,setSamples]=useState<Sample[]>([]),[selection,setSelection]=useState(''),[report,setReport]=useState<ConnectionReport|null>(null),[error,setError]=useState(''),[hiddenPause,setHiddenPause]=useState(false);
  const [heartbeat,setHeartbeat]=useState(0),[peopleQuery,setPeopleQuery]=useState(''),[selectionRequest,setSelectionRequest]=useState<{id:string;sequence:number}>();
  const [referenceSource,setReferenceSource]=useState<ReferenceSource|null>(null),[loadingReference,setLoadingReference]=useState(false),reportOperation=useRef(0),referenceRequest=useRef<AbortController|null>(null);
  useEffect(()=>()=>{reportOperation.current++;referenceRequest.current?.abort();},[]);
  useEffect(()=>{const timer=setInterval(()=>setHeartbeat(v=>v+1),15000);return()=>clearInterval(timer);},[]);
  const sceneAnchor=useRef<HTMLDivElement>(null);
  const members=useMemo(()=>simulationMembers(p.user,count),[p.user.id,count]),observer=useRef(OFFICE_50_PRESET.spawn),clock=useRef({elapsed:0,started:0}),latest=useRef({running,elapsed});latest.current={running,elapsed};
  const presence=useMemo(()=>simulationPresence(members,elapsed,scenario,observer.current),[members,Math.floor(elapsed/2),scenario,epoch,heartbeat]);
  const company=useMemo(()=>({id:'coatria-test-lab',name:'Coatria Studio · 50',template:'blank'}),[]);
  const user=useMemo(()=>({...p.user,name:'You · test observer',avatarId:members[0].avatarId}),[p.user,members]);
  const sample=useCallback((value:OfficeDiagnostics)=>{setDiagnostics(value);const perf=value.performance,state=latest.current;if(state.running&&state.elapsed>=10&&perf?.sampleCount&&perf.state!=='suspended'&&perf.state!=='idle'){setSamples(previous=>[...previous.slice(-119),{second:Math.round(state.elapsed),fps:perf.fps,p95:perf.frameMs.p95,drawCalls:perf.drawCalls,triangles:perf.triangles}]);}},[]);
  useEffect(()=>{if(!running)return;clock.current={elapsed:latest.current.elapsed,started:performance.now()};const tick=setInterval(()=>{const next=Math.min(duration,clock.current.elapsed+(performance.now()-clock.current.started)/1000);setElapsed(next);if(next>=duration)setRunning(false);},500);const visibility=()=>{if(document.hidden){setRunning(false);setHiddenPause(true);}};document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(tick);document.removeEventListener('visibilitychange',visibility);};},[running,duration]);
  useEffect(()=>{if(tab!=='visual')setRunning(false);},[tab]);
  function reset(){setRunning(false);setElapsed(0);setSamples([]);setDiagnostics({});setSelection('');setHiddenPause(false);observer.current=OFFICE_50_PRESET.spawn;setEpoch(v=>v+1);}
  function start(){sceneAnchor.current?.scrollIntoView({block:'start',behavior:'smooth'});if(elapsed>=duration){setElapsed(0);setSamples([]);setEpoch(v=>v+1);}setHiddenPause(false);setRunning(true);}
  const perf=diagnostics.performance,loaded=diagnostics.resources?.loadedCharacterModels,average=samples.length?samples.reduce((n,v)=>n+v.fps,0)/samples.length:undefined,worst=samples.length?Math.max(...samples.map(v=>v.p95)):undefined;
  const loadedFurniture=Array.isArray(diagnostics.officeAssets)?diagnostics.officeAssets.filter((asset:{status?:string})=>asset.status==='ready').length:0,assetsComplete=(loaded??0)>=presence.length&&loadedFurniture===OFFICE_50_PRESET.layout.length;
  const complete=elapsed>=duration,measured=samples.length>=5,comfortable=assetsComplete&&measured&&average!>=30&&worst!<=50;
  function beginReportOperation(){referenceRequest.current?.abort();referenceRequest.current=null;setLoadingReference(false);setError('');return ++reportOperation.current;}
  async function importReport(file?:File){if(!file)return;const operation=beginReportOperation();if(file.size>reportLimit){setError('Choose a JSON report smaller than 1 MB.');return;}try{const imported=readConnectionReport(JSON.parse(await file.text()));if(operation===reportOperation.current){setReport(imported);setReferenceSource(null);}}catch(e){if(operation===reportOperation.current)setError((e as Error).message);}}
  async function loadReference(){
    const operation=beginReportOperation(),controller=new AbortController();referenceRequest.current=controller;setLoadingReference(true);const timeout=setTimeout(()=>controller.abort(),15000);
    try{const response=await fetch('/benchmarks/connections-reference.json',{cache:'no-store',signal:controller.signal,redirect:'error'});if(response.status===404)throw new Error('Reference run is not available yet');if(!response.ok)throw new Error('The reference run could not be loaded. Try again.');const result=await readReferenceResponse(response);if(operation===reportOperation.current){setReport(result.report);setReferenceSource(result.reference);}}
    catch(e){if(operation===reportOperation.current)setError(controller.signal.aborted?'Loading the reference run timed out. Try again.':(e as Error).message);}
    finally{clearTimeout(timeout);controller.abort();if(operation===reportOperation.current){setLoadingReference(false);referenceRequest.current=null;}}
  }
  function clearReport(){beginReportOperation();setReport(null);setReferenceSource(null);}
  const summaryText=running?(elapsed<10?'Warming up models and animations':'Recording this browser’s performance'):complete?'Run complete':elapsed>0?'Run paused':'Ready when you are';
  return <div className={s.lab}>
    <PageHead eyebrow="WORKPLACE TEST LAB" title="Make room for fifty." description="Walk through a full office. Measure the experience before your team moves in." action={<button className="button secondary" onClick={p.onBack}><ArrowLeft size={16}/> Back to the office</button>}/>
    <div className={s.banner}><span className={s.labIcon}><FlaskConical size={23}/></span><div><strong>A separate space to experiment.</strong><p>Test people stay in this browser. Your company’s people, messages and floor plan are untouched.</p></div><Badge>Local simulation</Badge></div>
    <div className={s.tabs} role="tablist" aria-label="Test lab views">{([['visual','Visual test',Activity],['plan','The 50-person plan',Layers3],['connections','Connection results',Wifi]] as const).map(([id,label,Icon])=><button key={id} id={'lab-tab-'+id} role="tab" aria-selected={tab===id} aria-controls={'lab-panel-'+id} onClick={()=>setTab(id)} onKeyDown={event=>{const order=['visual','plan','connections'] as const;const current=order.indexOf(tab);const next=event.key==='ArrowRight'?order[(current+1)%3]:event.key==='ArrowLeft'?order[(current+2)%3]:event.key==='Home'?order[0]:event.key==='End'?order[2]:null;if(next){event.preventDefault();setTab(next);document.getElementById('lab-tab-'+next)?.focus();}}}><Icon size={16}/>{label}</button>)}</div>
    {tab==='visual'&&<section role="tabpanel" id="lab-panel-visual" aria-labelledby="lab-tab-visual">
      <div className={s.controlBar}><div className={s.controls}><Field label="Test people"><select value={count} disabled={running} onChange={e=>{reset();setCount(Number(e.target.value));}}>{[10,25,50].map(n=><option key={n} value={n}>{n} people</option>)}</select></Field><Field label="Scenario"><select value={scenario} disabled={running} onChange={e=>{reset();setScenario(e.target.value as SimulationScenario);}}><option value="working">A normal working day</option><option value="moving">Everyone moving</option><option value="reconnect">Disconnect & return</option></select></Field><Field label="Run length"><select value={duration} disabled={running} onChange={e=>{reset();setDuration(Number(e.target.value));}}>{[30,60,120].map(n=><option key={n} value={n}>{n} seconds</option>)}</select></Field></div><div className={s.runActions}><button className="button secondary" aria-label="Reset visual test" onClick={reset}><RotateCcw size={16}/></button><button className="button primary" onClick={()=>running?setRunning(false):start()}>{running?<Pause size={16}/>:<Play size={16}/>} {running?'Pause test':complete?'Run again':elapsed>0?'Resume test':'Start visual test'}</button></div></div>
      <div className={s.metrics}><Metric label="People in the scene" value={String(presence.length)} detail={`${count} simulated identities`}/><Metric label="Frames per second" value={perf?.state==='suspended'?'Paused':perf?.state==='idle'?'Idle':fmt(perf?.fps)} detail="This browser · live"/><Metric label="Frame time · p95" value={fmt(perf?.frameMs.p95,1)} suffix="ms" detail="95% of recent frames below this"/><Metric label="3D draw calls" value={fmt(perf?.drawCalls)} detail={`${fmt(perf?.triangles)} triangles per frame`}/></div>
      <div className={s.visualGrid}><div ref={sceneAnchor} className={s.scenePanel}><header><div><span className={running?s.pulse:s.dot}/><strong>Coatria Studio</strong><Badge>{count} places</Badge></div><span>{OFFICE_50_PRESET.floor.width} × {OFFICE_50_PRESET.floor.depth} m</span></header><OfficeScene key={p.user.id+':'+count+':'+epoch} user={user} company={company} members={members} presence={presence} agents={[]} rooms={[]} layout={OFFICE_50_PRESET.layout} floor={OFFICE_50_PRESET.floor} onMove={position=>{observer.current=position;}} onOpenRoom={noAction} onOpenAgent={noAction} onOpenPerson={id=>setSelection(members.find(m=>m.userId===id)?.name||'')} onDiagnostics={sample} performanceResetKey={epoch} selectionRequest={selectionRequest}/><footer><Users size={15}/>{selection?selection+' selected · simulated teammate':'Click to walk. Drag to orbit. Select a teammate to check picking.'}</footer><details className={s.roster}><summary>Test people · accessible list ({members.length})</summary><Field label="Find a test teammate"><input type="search" value={peopleQuery} onChange={e=>setPeopleQuery(e.target.value)} placeholder="Name or team…"/></Field><div>{members.filter(m=>(m.name+' '+m.roleTitle).toLowerCase().includes(peopleQuery.toLowerCase().trim())).map(m=><button type="button" key={m.userId} disabled={!presence.some(v=>v.userId===m.userId)} onClick={()=>{setSelection(m.name);setSelectionRequest(v=>({id:m.userId,sequence:(v?.sequence||0)+1}));}}><span>{m.name}<small>{m.roleTitle}</small></span><ArrowRight size={14}/></button>)}</div></details></div>
      <aside className={s.runPanel}><span className="eyebrow">THIS RUN</span><h2>{summaryText}</h2><div className={s.progressText}><strong>{Math.floor(elapsed)}<small> / {duration}s</small></strong><Badge>{running?'Running':complete?'Complete':elapsed?'Paused':'Idle'}</Badge></div><progress value={elapsed} max={duration} aria-label="Visual test progress"/><p>The first 10 seconds warm up the scene. Keep this tab visible while measuring.</p>{hiddenPause&&<p className={s.notice}>Paused when the tab was hidden. Resume to continue measuring visible frames.</p>}<FrameChart samples={samples}/><div className={s.resultRows}><span>Average FPS<strong>{fmt(average)}</strong></span><span>Worst sampled p95<strong>{fmt(worst,1)} ms</strong></span><span>Loaded characters<strong>{fmt(loaded)} / {count}</strong></span><span>Full-rate animations<strong>{fmt(diagnostics.animation?.fullRateHumans)}</strong></span></div>{complete&&<div className={s.verdict}>{!assetsComplete?<><AlertCircle size={18}/> Some character or furniture models did not load. This run is incomplete.</>:!measured?<><AlertCircle size={18}/> Not enough frame samples to judge.</>:comfortable?<><CheckCircle2 size={18}/> Meets the visual target on this device.</>:<><AlertCircle size={18}/> This device needs closer performance review. Try the scene’s Low graphics setting.</>}</div>}<button className="button secondary" disabled={!samples.length} onClick={()=>download({schemaVersion:1,kind:'coatria-visual',generatedAt:new Date().toISOString(),environment:{userAgent:navigator.userAgent,width:innerWidth,height:innerHeight,devicePixelRatio},scenario,people:count,elapsedSeconds:elapsed,complete,warmupSeconds:10,summary:{averageFps:average,worstSampledP95Ms:worst,samples:samples.length,assetsComplete,meetsVisualTarget:complete&&comfortable,loadedCharacters:loaded,expectedCharacters:presence.length,loadedFurniture,expectedFurniture:OFFICE_50_PRESET.layout.length},samples,diagnostics,limitations:['Local simulated identities; no server load or network latency measurement.','Recent frame intervals and CPU wall time; not GPU timings.','Graphics driver, viewport, device and background workload affect results.']},'coatria-visual-test.json')}><Download size={15}/> Export visual report</button></aside></div>
      <div className={s.note}><Wifi size={19}/><div><strong>50 animated people is only one half of the test.</strong><p>This view measures local rendering and interactions. Use Connection results for independent authenticated sessions, synchronization, permissions and API latency. Audio calls still support up to six participants per room.</p></div></div>
    </section>}
    {tab==='plan'&&<section role="tabpanel" id="lab-panel-plan" aria-labelledby="lab-tab-plan" className={s.planGrid}><div className={s.planArt}><OfficePresetPreview/><div><span>50 dedicated workstations</span><span>{OFFICE_50_PRESET.floor.width*OFFICE_50_PRESET.floor.depth} m² · {OFFICE_50_PRESET.layout.length} objects</span></div></div><div className={s.planCopy}><span className="eyebrow">A COMPANY, NOT A CROWD</span><h2>Five teams.<br/>One shared workplace.</h2><p>Ten places per team keep people easy to find. Open circulation connects the desk neighborhoods to a project lounge and shared commons.</p><ul><li>50 separate desk and chair pairs</li><li>Clearly spaced walkways and approach points</li><li>Shared lounge furniture, storage and planting</li><li>Every object remains editable</li></ul><button className="button primary" onClick={p.onEdit}>Open the space editor <ArrowRight size={16}/></button><small>Choose “50-person studio” in Office templates. It opens as an editable draft; saving replaces your shared plan. Furniture does not automatically create audio rooms or assign seats.</small></div></section>}
    {tab==='connections'&&<section role="tabpanel" id="lab-panel-connections" aria-labelledby="lab-tab-connections"><div className={s.connectionIntro}><div><span className="eyebrow">REAL SESSIONS · REAL REQUESTS</span><h2>Test the company behind the scene.</h2><p>Load a published CI reference run, or import your own connection report. Each report measures independent test sessions in its stated environment.</p></div><div className={s.runActions} style={{flexWrap:'wrap',maxWidth:'100%'}}><button className="button secondary" onClick={()=>void loadReference()} disabled={loadingReference}><Download size={17}/>{loadingReference?'Loading reference…':'Load reference run'}</button><label className={s.importButton}><Upload size={17}/> Import connection report<input type="file" accept=".json,application/json" aria-label="Import connection report" onChange={e=>{void importReport(e.target.files?.[0]);e.target.value='';}}/></label></div></div>{error&&<p className="error-message" role="alert">{error}</p>}
      {report?<><div className={s.imported}><Badge>{report.summary.passed?'Checks passed':'Review required'}</Badge><span>{referenceSource?'Published reference run':'Imported local report'} · {new Date(report.generatedAt).toLocaleString()}</span><button className="text-button" onClick={clearReport}>Clear report</button></div>{referenceSource&&<div className={s.note}><div><strong>Reference run · measured in CI</strong><p>Tested source <code style={{overflowWrap:'anywhere'}}>{referenceSource.sourceCommit}</code> · <a href={referenceSource.ciUrl} target="_blank" rel="noopener noreferrer">View CI run</a></p></div></div>}<div className={s.metrics}><Metric label="Authenticated sessions" value={fmt(report.summary.clients)} detail={`${fmt(report.summary.durationSeconds)} seconds measured`}/><Metric label="Requests completed" value={fmt(report.summary.requests)} detail={`${fmt(report.summary.requestsPerSecond,1)} requests / second`}/><Metric label="Request latency · p95" value={fmt(report.summary.p95Ms,1)} suffix="ms" detail={`Median ${fmt(report.summary.p50Ms,1)} ms`}/><Metric label="Unexpected errors" value={fmt(report.summary.unexpectedErrors)} detail={`${fmt(report.summary.errorRate*100,2)}% error rate`}/></div><div className={s.connectionGrid}><div className={s.checks}>{report.checks.map((check,i)=><div key={check.id+':'+i}>{check.passed?<CheckCircle2 size={19}/>:<AlertCircle size={19}/>}<span><strong>{check.label}</strong><p>{check.detail}</p></span><Badge>{check.passed?'Pass':'Review'}</Badge></div>)}</div><aside className={s.runPanel}><h2>What this run establishes</h2><p>{report.environment.applicationMode} application · {report.environment.database} · pool {report.environment.databasePoolMax}</p><ul>{report.environment.limitations.map((line,i)=><li key={i}>{line}</li>)}</ul><p>Fixture cleanup: {report.cleanup.verified?'verified':'requires attention'}.</p><p>{referenceSource?'This reference describes its tested source and CI environment; it is not a measurement of current live capacity.':'Imported results are supplied by the report file; they are not a certification of Coatria’s live deployment.'}</p></aside></div></>:<div className={s.connectionEmpty}><span className={s.labIcon}><Wifi size={28}/></span><h3>No connection run imported yet.</h3><p>Load the reference run to inspect published measurements, or run the local connection harness and import its JSON output. A visual test does not generate a connection report.</p></div>}
      <details className={s.runner}><summary>Run the connection test locally</summary><p>From your licensed Coatria checkout, use the project’s Node environment:</p><pre>npm run test:load -- --clients 50 --duration 60 --report ../output/coatria-50-connections.json</pre><CopyButton text="npm run test:load -- --clients 50 --duration 60 --report ../output/coatria-50-connections.json" label="Copy test command"/><p>The runner owns an isolated local database and server. It refuses remote targets and removes its test identities. The report states which database engine and application mode were measured. Global latency, a production-sized database and 50-person media calls need separate testing.</p></details>
    </section>}
  </div>;
}
function Metric({label,value,detail,suffix}:{label:string;value:string;detail:string;suffix?:string}){return <div><span>{label}</span><strong>{value}{suffix&&<small>{suffix}</small>}</strong><p>{detail}</p></div>;}
function FrameChart({samples}:{samples:Sample[]}){const path=samples.map((s,i)=>`${i?'L':'M'}${samples.length===1?0:i/(samples.length-1)*260},${70-Math.min(70,s.fps)}`).join(' ');return <div className={s.chart}><svg viewBox="0 0 260 80" role="img" aria-label={samples.length?'Frames per second across the current run':'Frame graph appears after the warmup'}><path d="M0 40H260" stroke="#b2c1a3" strokeDasharray="4 4"/><text x="2" y="35" fill="#5e7053" fontSize="9">30 FPS target</text>{path&&<path d={path} fill="none" stroke="#4f7944" strokeWidth="2"/>}</svg></div>;}
