'use client';
import {useEffect,useRef,useState, type ReactNode, type FormEvent} from 'react';
import {ArrowRight, Check, Copy, LoaderCircle, X, type LucideIcon} from 'lucide-react';
import {initials} from '@/lib/client';

export function Brand({small=false}:{small?:boolean}) { return <span className={'brand '+(small?'brand-small':'')}><span className="brand-symbol" aria-hidden="true"><i/><i/><i/></span>{!small && 'coatria'}<span className="sr-only">{small?'Coatria':''}</span></span>; }
export function Avatar({name,color,size='normal'}:{name:string;color?:string;size?:string}) { return <span className={'avatar '+size} style={color && /^#[0-9a-f]{6}$/i.test(color)?{background:color}:undefined}>{initials(name)}</span>; }
export function Badge({children,tone=''}:{children:ReactNode;tone?:string}) { return <span className={'badge '+tone}>{children}</span>; }
export function PageHead({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:ReactNode}) { return <div className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<div className="head-action">{action}</div>}</div>; }
export function Empty({icon:Icon,title,description,action}:{icon:LucideIcon;title:string;description:string;action?:ReactNode}) { return <div className="empty"><span className="empty-icon"><Icon size={24}/></span><h3>{title}</h3><p>{description}</p>{action}</div>; }
export function Loading({label='Loading your workspace'}:{label?:string}) { return <div className="loading" role="status"><LoaderCircle className="spin" size={23}/><span>{label}…</span></div>; }
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}) { return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>; }
export function Form({onSubmit,children,submit='Save changes',className='',disabled=false}:{onSubmit:(form:HTMLFormElement)=>Promise<void>;children:ReactNode;submit?:string;className?:string;disabled?:boolean}) { const [busy,setBusy]=useState(false),[error,setError]=useState(''); async function handle(e:FormEvent<HTMLFormElement>) {e.preventDefault();if(busy)return;const form=e.currentTarget;setError('');setBusy(true);try{await onSubmit(form);}catch(err){setError(err instanceof Error?err.message:'Something went wrong. Please try again.');}finally{setBusy(false);}} return <form onSubmit={handle} className={'form '+className}><fieldset disabled={busy||disabled}>{children}</fieldset>{error&&<p role="alert" className="error-message">{error}</p>}<button className="button primary" disabled={busy||disabled} type="submit">{busy?<LoaderCircle size={16} className="spin"/>:<ArrowRight size={16}/>} {busy?'Saving…':submit}</button></form>; }
export function Modal({title,description,onClose,children,wide=false}:{title:string;description?:string;onClose:()=>void;children:ReactNode;wide?:boolean}) { const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;const active=document.activeElement as HTMLElement|null;d?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{d?.close();document.body.style.overflow=previous;active?.focus();};},[]);return <dialog ref={ref} className={'modal '+(wide?'wide':'')} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}><header><div><h2>{title}</h2>{description&&<p>{description}</p>}</div><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></header><div className="modal-body">{children}</div></dialog>; }
export function CopyButton({text,label='Copy'}:{text:string;label?:string}) {const [copied,setCopied]=useState(false),[error,setError]=useState(false);return <><button type="button" className="button secondary small" onClick={async()=>{try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{setError(true);}}}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':label}</button>{error&&<small role="alert">Select and copy the text manually.</small>}</>;}
export function Secret({token,title='Save your connection token',children}:{token:string;title?:string;children?:ReactNode}) {return <div className="secret-box"><Badge tone="warning">Shown only once</Badge><h3>{title}</h3><p>Keep this token in your local environment or secret manager. It gives access to this company integration.</p><textarea readOnly aria-label="Connection token" value={token} rows={3}/><CopyButton text={token} label="Copy token"/>{children}</div>;}
