'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {api} from '@/lib/client';
import {startPolling} from '@/lib/polling';
import type {AgentRun} from '@/lib/agent-run-protocol';
export type RunDraft={agentId:string;prompt:string;busy:boolean;error:string;attempt?:{clientId:string;agentId:string;prompt:string;parentId:string|null;uncertain?:boolean}};
type CommittedAction={requestId:string;tool:string;createdAt:string};
type Query={loaded:boolean;loading:boolean;error:string;ids:string[];actions?:CommittedAction[]};
type State={runs:Map<string,AgentRun>;queries:Map<string,Query>;drafts:Map<string,RunDraft>};
export const emptyRunDraft:RunDraft={agentId:'',prompt:'',busy:false,error:''};
export const runDraftKey=(channel:string,parentId:string|null)=>channel+':'+(parentId||'root');
const isTerminal=(run:AgentRun)=>['succeeded','failed','cancelled'].includes(run.status);
export function useAgentRunClient(){
 const [state,setState]=useState<State>(()=>({runs:new Map(),queries:new Map(),drafts:new Map()}));
 const latest=useRef(state),scope=useRef(new AbortController()),alive=useRef(true),company=useRef(''),watchers=useRef(new Map<string,number>()),flights=useRef(new Map<string,Promise<unknown>>()),cooldown=useRef(0),running=useRef(false),wake=useRef(()=>{});
 const change=useCallback((fn:(value:State)=>State)=>{if(alive.current){latest.current=fn(latest.current);setState(latest.current);}},[]);
 function bind(companyId:string){if(company.current&&company.current!==companyId)throw new Error('Agent request scope changed.');company.current=companyId;}
 const patchDraft=useCallback((key:string,fn:(draft:RunDraft)=>RunDraft)=>change(value=>{const drafts=new Map(value.drafts);drafts.set(key,fn(drafts.get(key)||emptyRunDraft));return{...value,drafts};}),[change]);
 function merge(values:AgentRun[]){change(state=>{const runs=new Map(state.runs);for(const value of values){const old=runs.get(value.id);if(!old||(!isTerminal(old)||isTerminal(value))&&Date.parse(value.updatedAt)>=Date.parse(old.updatedAt))runs.set(value.id,value);}return{...state,runs};});}
 function single<T>(key:string,task:()=>Promise<T>):Promise<T>{const existing=flights.current.get(key);if(existing)return existing as Promise<T>;const promise=task().finally(()=>{if(flights.current.get(key)===promise)flights.current.delete(key);});flights.current.set(key,promise);return promise;}
 async function request<T>(path:string,method='GET',body?:unknown){const lifetime=scope.current.signal,deadline=new AbortController();let timedOut=false;const abort=()=>deadline.abort();lifetime.addEventListener('abort',abort,{once:true});if(lifetime.aborted)abort();const timer=setTimeout(()=>{timedOut=true;deadline.abort();},20000);try{return await api<T>(path,method,body,{signal:deadline.signal});}catch(error){if(!lifetime.aborted){const value=error as {status?:number;retryAfter?:number};if(value.status===429)cooldown.current=Math.max(cooldown.current,Date.now()+(value.retryAfter||30)*1000);if(timedOut)throw new Error('The request timed out. Retry the original request to confirm whether it was queued.');}throw error;}finally{clearTimeout(timer);lifetime.removeEventListener('abort',abort);}}
 const path=(query:string)=>'/api/companies/'+company.current+(query.startsWith('channel:')?'/conversations/'+encodeURIComponent(query.slice(8))+'/runs?limit=50':query.startsWith('agent:')?'/agent-runs?agentId='+encodeURIComponent(query.slice(6))+'&limit=50':'/agent-runs/'+encodeURIComponent(query.slice(4)));
 async function load(query:string){const lifetime=scope.current.signal;if(!company.current||Date.now()<cooldown.current)return;return single('get:'+query,async()=>{change(value=>{const queries=new Map(value.queries);queries.set(query,{...(queries.get(query)||{loaded:false,ids:[],error:''}),loading:true});return{...value,queries};});try{const result=await request<{runs?:AgentRun[];run?:AgentRun;actions?:CommittedAction[]}>(path(query));if(!alive.current||lifetime.aborted||scope.current.signal!==lifetime)return;const runs=result.runs||(result.run?[result.run]:[]);merge(runs);change(value=>{const queries=new Map(value.queries);queries.set(query,{loaded:true,loading:false,error:'',ids:runs.map(run=>run.id),...(query.startsWith('run:')?{actions:(result.actions||[]).slice(0,200)}:{})});return{...value,queries};});}catch(error){if(alive.current&&!lifetime.aborted&&scope.current.signal===lifetime)change(value=>{const queries=new Map(value.queries);queries.set(query,{...(queries.get(query)||{loaded:false,ids:[]}),loading:false,error:error instanceof Error?error.message:'Agent requests could not be loaded.'});return{...value,queries};});throw error;}});}
 async function poll(){if(running.current||document.hidden||!alive.current||!watchers.current.size||Date.now()<cooldown.current)return;running.current=true;try{for(const query of watchers.current.keys()){await load(query);if(Date.now()<cooldown.current||!alive.current)return;}}finally{running.current=false;}}
 wake.current=()=>{void poll().catch(()=>{});};
 useEffect(()=>{alive.current=true;if(scope.current.signal.aborted)scope.current=new AbortController();const stop=startPolling(()=>poll(),{intervalMs:3000,active:()=>!document.hidden});const resume=()=>wake.current();window.addEventListener('online',resume);document.addEventListener('visibilitychange',resume);return()=>{alive.current=false;scope.current.abort();stop();watchers.current.clear();flights.current.clear();window.removeEventListener('online',resume);document.removeEventListener('visibilitychange',resume);};},[]);
 const watch=useCallback((companyId:string,query:string)=>{bind(companyId);watchers.current.set(query,(watchers.current.get(query)||0)+1);queueMicrotask(()=>wake.current());return()=>{const count=(watchers.current.get(query)||1)-1;if(count)watchers.current.set(query,count);else watchers.current.delete(query);};},[]);
 const setDraft=useCallback((key:string,patch:Partial<RunDraft>)=>patchDraft(key,old=>({...old,...patch})),[patchDraft]);
 async function create(companyId:string,channel:string,parentId:string|null,retry=false){const lifetime=scope.current.signal;bind(companyId);const key=runDraftKey(channel,parentId),draft=latest.current.drafts.get(key)||emptyRunDraft;if(draft.busy)return;const attempt=draft.attempt||{clientId:crypto.randomUUID(),agentId:draft.agentId,prompt:draft.prompt.trim(),parentId};if(!attempt.agentId||!attempt.prompt)return;if(draft.attempt&&!retry&&(draft.agentId!==attempt.agentId||draft.prompt.trim()!==attempt.prompt)){patchDraft(key,old=>({...old,error:'Retry the original request first. Your edited prompt is kept.'}));return;}if(Date.now()<cooldown.current){patchDraft(key,old=>({...old,error:'Please wait '+Math.ceil((cooldown.current-Date.now())/1000)+' seconds before retrying.'}));return;}
  patchDraft(key,old=>({...old,busy:true,error:'',attempt}));return single('create:'+key,async()=>{try{const result=await request<{run:AgentRun;replayed:boolean}>('/api/companies/'+companyId+'/conversations/'+encodeURIComponent(channel)+'/runs','POST',{clientId:attempt.clientId,agentId:attempt.agentId,prompt:attempt.prompt,...(parentId?{parentId}:{})});if(!alive.current||lifetime.aborted||scope.current.signal!==lifetime)return;merge([result.run]);patchDraft(key,old=>({...old,attempt:undefined,error:'',prompt:old.prompt.trim()===attempt.prompt?'':old.prompt}));change(value=>{const queries=new Map(value.queries),query='channel:'+channel,old=queries.get(query);if(old)queries.set(query,{...old,ids:[result.run.id,...old.ids.filter(id=>id!==result.run.id)]});return{...value,queries};});wake.current();return result.run;}catch(error){if(alive.current&&!lifetime.aborted&&scope.current.signal===lifetime){const status=(error as {status?:number}).status;const rejected=!attempt.uncertain&&[400,401,403,404,409,413,415,429].includes(status||0);patchDraft(key,old=>({...old,attempt:rejected?undefined:{...attempt,uncertain:true},error:error instanceof Error?error.message:'The request could not be confirmed.'}));}}finally{if(alive.current&&!lifetime.aborted&&scope.current.signal===lifetime)patchDraft(key,old=>({...old,busy:false}));}});
 }
 async function cancel(companyId:string,runId:string){const lifetime=scope.current.signal;bind(companyId);return single('cancel:'+runId,async()=>{const result=await request<{run:AgentRun}>('/api/companies/'+companyId+'/agent-runs/'+runId+'/cancel','POST',{});if(alive.current&&!lifetime.aborted&&scope.current.signal===lifetime)merge([result.run]);return result.run;});}
 return{state,watch,setDraft,create,cancel,reload:(query:string)=>load(query).catch(()=>{})};
}
