'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,BookOpen,Check,CheckCheck,CircleDashed,Clock3,Download,ExternalLink,FileCheck2,LayoutGrid,List,LockKeyhole,Pencil,Plus,Search,ShieldCheck,UserRound,X} from 'lucide-react';
import type {WorkspaceProps} from '@/app/page';
import {api,type Skill,type Task,safeUrl,values,when} from '@/lib/client';
import {Avatar,Badge,CopyButton,Empty,Field,Form,Loading,Modal,PageHead} from './ui';
import styles from './Work.module.css';

const columns=[{id:'todo',name:'Up next',icon:CircleDashed},{id:'doing',name:'In progress',icon:Clock3},{id:'review',name:'In review',icon:FileCheck2},{id:'done',name:'Accepted',icon:CheckCheck}];
type TaskFilter='all'|'mine'|'review'|'unassigned';
const taskReference=(task:Task)=>'WORK / '+task.id.slice(0,6).toUpperCase();
const statusName=(status:string)=>columns.find(column=>column.id===status)?.name||status;
function canReview(task:Task,p:WorkspaceProps){return ['owner','admin'].includes(p.company.role)&&!task.authorIds?.includes(p.user.id)&&task.assigneeId!==p.user.id&&task.submittedBy!==p.user.id&&(!task.submittedAgentId||p.workspace.agents.find(agent=>agent.id===task.submittedAgentId)?.createdBy!==p.user.id);}
function matchesView(task:Task,view:TaskFilter,userId:string){return view==='mine'?task.assigneeId===userId:view==='review'?task.status==='review':view==='unassigned'?!task.assigneeId&&task.status!=='done':true;}
function useDraftNavigationGuard(dirty:boolean,message:string){useEffect(()=>{if(!dirty)return;const navigate=(event:Event)=>{if(!window.confirm(message))event.preventDefault();};const unload=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};document.addEventListener('coatria:before-navigate',navigate);window.addEventListener('beforeunload',unload);return()=>{document.removeEventListener('coatria:before-navigate',navigate);window.removeEventListener('beforeunload',unload);};},[dirty,message]);}

export function TasksView(p:WorkspaceProps){
 const [creating,setCreating]=useState(false),[selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState<TaskFilter>('all');
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState('updated'),[layout,setLayout]=useState<'board'|'list'>(()=>typeof window!=='undefined'&&window.matchMedia('(max-width:700px)').matches?'list':'board');
 const tasks=useMemo(()=>{const search=query.trim().toLowerCase();return p.workspace.tasks.filter(task=>matchesView(task,filter,p.user.id)&&(status==='all'||task.status===status)&&[task.title,task.description,task.id,p.workspace.members.find(member=>member.userId===task.assigneeId)?.name||''].join(' ').toLowerCase().includes(search)).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):sort==='created'?Date.parse(b.createdAt)-Date.parse(a.createdAt):Date.parse(b.updatedAt)-Date.parse(a.updatedAt));},[p.workspace.tasks,p.workspace.members,p.user.id,query,filter,status,sort]);
 const task=p.workspace.tasks.find(item=>item.id===selected),filtered=Boolean(query.trim()||filter!=='all'||status!=='all');
 const clearFilters=()=>{setQuery('');setFilter('all');setStatus('all');};
 const views:Array<{id:TaskFilter;name:string}>=[{id:'all',name:'All company work'},{id:'mine',name:'Assigned to me'},{id:'review',name:'Needs review'},{id:'unassigned',name:'Unassigned'}];
 function taskCard(item:Task,list=false){const assignee=p.workspace.members.find(member=>member.userId===item.assigneeId);return <button key={item.id} className={list?styles.taskRow:styles.taskCard} onClick={()=>setSelected(item.id)} aria-label={'Open task: '+item.title}>
  <div className={styles.taskMain}><span className={styles.reference}>{taskReference(item)}</span><h3>{item.title}</h3>{!list&&<p>{item.description||'Add context and acceptance criteria to guide the work.'}</p>}</div>
  {list&&<span className={styles.status} data-status={item.status}>{statusName(item.status)}</span>}
  <span className={styles.owner}>{assignee?<><Avatar name={assignee.name} color={assignee.avatarColor} size="tiny"/><span>{assignee.name}{assignee.userId===p.user.id&&<small>You</small>}</span></>:<><UserRound size={15}/><span>{item.assigneeId?'Former teammate':'Unassigned'}</span></>}</span>
  <span className={styles.cardMeta}>{item.submissionUrl?<span><ExternalLink size={12}/> Outcome linked</span>:item.submissionSummary?<span><FileCheck2 size={12}/> Report submitted</span>:<time dateTime={item.updatedAt}>Updated {when(item.updatedAt)}</time>}</span>
 </button>;}
 return <>
  <PageHead eyebrow="COMPANY WORK" title="Work board" description="Give each task an owner, a clear outcome, and a considered review." action={<button className="button primary" onClick={()=>setCreating(true)}><Plus size={16}/> Create a task</button>}/>
  <section className={styles.workspaceTools} aria-label="Task views and filters"><div className={styles.viewTabs} aria-label="Task views">{views.map(view=><button key={view.id} aria-pressed={filter===view.id} className={filter===view.id?styles.activeView:''} onClick={()=>{setFilter(view.id);setStatus('all');}}>{view.name}<span>{p.workspace.tasks.filter(item=>matchesView(item,view.id,p.user.id)).length}</span></button>)}</div>
   <div className={styles.toolbar}><div className={styles.search}><Search size={16}/><input aria-label="Search tasks" placeholder="Search tasks or owners…" value={query} onChange={event=>setQuery(event.target.value)}/>{query&&<button type="button" aria-label="Clear task search" onClick={()=>setQuery('')}><X size={15}/></button>}</div>
    <label className={styles.select}><span>Status</span><select aria-label="Filter task status" value={status} onChange={event=>{setStatus(event.target.value);if(filter==='review')setFilter('all');}}><option value="all">All statuses</option>{columns.map(column=><option key={column.id} value={column.id}>{column.name}</option>)}</select></label>
    <label className={styles.select}><span>Sort</span><select aria-label="Sort tasks" value={sort} onChange={event=>setSort(event.target.value)}><option value="updated">Recently updated</option><option value="created">Newest created</option><option value="title">Title A–Z</option></select></label>
    <div className={styles.layoutSwitch} aria-label="Task layout"><button aria-label="Board view" aria-pressed={layout==='board'} onClick={()=>setLayout('board')}><LayoutGrid size={17}/></button><button aria-label="List view" aria-pressed={layout==='list'} onClick={()=>setLayout('list')}><List size={18}/></button></div>
   </div>
  </section>
  <div className={styles.results}><span role="status">{tasks.length} {tasks.length===1?'task':'tasks'}{filtered?' of '+p.workspace.tasks.length:''}</span>{filtered&&<button className="text-button" onClick={clearFilters}><X size={13}/> Clear filters</button>}<span className={styles.resultHint}>Shared with {p.company.name}</span></div>
  {!p.workspace.tasks.length?<section className="panel"><Empty icon={CircleDashed} title="Make the next step clear." description="Create a task with an outcome and an owner. Your team can track it here from the first idea to an accepted contribution." action={<button className="button primary" onClick={()=>setCreating(true)}><Plus size={16}/> Create your first task</button>}/></section>:!tasks.length?<section className="panel"><Empty icon={Search} title="No tasks match this view." description="Try a different owner, status, or search. Your company’s work is still in All company work." action={<button className="button secondary" onClick={clearFilters}>Clear task filters</button>}/></section>:layout==='list'?<section className={styles.taskList} aria-label="Task list"><div className={styles.listHead} aria-hidden="true"><span>Task</span><span>Status</span><span>Owner</span><span>Latest</span></div>{tasks.map(item=>taskCard(item,true))}</section>:<div className={styles.board}>{columns.map(column=>{const items=tasks.filter(item=>item.status===column.id);return <section className={styles.column} data-status={column.id} key={column.id}><header><column.icon size={16}/><h2>{column.name}</h2><span>{items.length}</span></header><div className={styles.cards}>{items.map(item=>taskCard(item))}{!items.length&&<div className={styles.columnEmpty}>{filtered?'No matching tasks.':column.id==='todo'?'New work starts here.':column.id==='doing'?'Tasks your team is working on.':column.id==='review'?'Submitted outcomes awaiting review.':'Independently accepted outcomes.'}</div>}</div>{column.id==='todo'&&<button className={styles.addTask} onClick={()=>setCreating(true)}><Plus size={14}/> Add a task</button>}</section>;})}</div>}
  <div className={styles.explainer}><ShieldCheck size={17}/><p><strong>Accepted means reviewed.</strong> An independent company administrator approves the contribution. Token usage measures cost, not the quality of the work.</p></div>
  {creating&&<Modal title="Give an idea its next step." description="A specific outcome helps your team know when the work is ready." onClose={()=>setCreating(false)}><Form submit="Create task" onSubmit={async form=>{const data=values(form);const result=await api<{task:Task}>(`/api/companies/${p.company.id}/tasks`,'POST',{...data,assigneeId:data.assigneeId||null});clearFilters();await p.refresh();setCreating(false);setSelected(result.task.id);p.notify('Your task is on the board.');}}><Field label="Task title" hint="Start with an action, such as Review the launch page."><input name="title" required maxLength={160} placeholder="What should be done?"/></Field><Field label="Description / acceptance criteria"><textarea name="description" maxLength={12000} rows={6} placeholder={'Outcome: What will be different?\nContext: What does the team need to know?\nReady when: What should a reviewer verify?'}/></Field><Field label="Assign to" hint="Choose one person to own the outcome, or leave it open."><select name="assigneeId"><option value="">Unassigned — available for the team or an agent</option>{p.workspace.members.map(member=><option key={member.userId} value={member.userId}>{member.name}{member.userId===p.user.id?' (you)':''}</option>)}</select></Field></Form></Modal>}
  {task&&<TaskDetail key={task.id} task={task} {...p} onClose={()=>setSelected(null)}/>}
 </>;
}

function TaskEditor(p:WorkspaceProps&{task:Task;onDirtyChange:(dirty:boolean)=>void}){
 const [base,setBase]=useState(p.task),[dirty,setDirty]=useState(false);
 const admin=['owner','admin'].includes(p.company.role),canAssign=admin||p.task.createdBy===p.user.id;
 const stale=dirty&&base.updatedAt!==p.task.updatedAt;
 useEffect(()=>{if(!dirty)setBase(p.task);},[p.task.updatedAt]); // Preserve unsaved edits during workspace polling.
 useEffect(()=>{p.onDirtyChange(dirty);return()=>p.onDirtyChange(false);},[dirty,p.onDirtyChange]);
 return <div onChange={()=>setDirty(true)}>
  {stale&&<div className={styles.changedNotice} role="status"><strong>This task changed while you were editing.</strong><p>Your edits are still here. Load the latest task before making another change.</p><button type="button" className="button secondary small" onClick={()=>{setBase(p.task);setDirty(false);}}>Discard edits and load latest</button></div>}
  <Form key={base.updatedAt} submit="Save task updates" disabled={stale} submitDisabled={!dirty} onSubmit={async form=>{
   const data=values(form),patch:Record<string,unknown>={};
   for(const key of ['title','description','status'] as const)if(data[key]!==base[key])patch[key]=data[key];
   if(canAssign&&(data.assigneeId||null)!==base.assigneeId)patch.assigneeId=data.assigneeId||null;
   if((data.submissionUrl||null)!==base.submissionUrl)patch.submissionUrl=data.submissionUrl||null;
   if(admin&&data.reviewNote!==(base.reviewNote||''))patch.reviewNote=data.reviewNote;
   if(!Object.keys(patch).length){setDirty(false);return;}
   const result=await api<{task:Task}>(`/api/companies/${p.company.id}/tasks/${p.task.id}`,'PATCH',patch);setDirty(false);setBase(result.task);await p.refresh();p.notify(result.task.status==='review'?'Contribution submitted for independent review.':'Task updated.');
  }}><Field label="Task title"><input name="title" required maxLength={160} defaultValue={base.title}/></Field><Field label="Description / acceptance criteria"><textarea name="description" rows={6} defaultValue={base.description} maxLength={12000}/></Field>
   <div className="grid two"><Field label="Status"><select name="status" defaultValue={base.status}><option value="todo">Up next</option><option value="doing">In progress</option><option value="review">Submit for review</option></select></Field><Field label="Assign to" hint={!canAssign?'The task creator or an administrator can change the owner.':undefined}><select name="assigneeId" defaultValue={base.assigneeId||''} disabled={!canAssign}><option value="">Unassigned / available to agents</option>{base.assigneeId&&!p.workspace.members.some(member=>member.userId===base.assigneeId)&&<option value={base.assigneeId}>Former teammate</option>}{p.workspace.members.map(member=><option key={member.userId} value={member.userId}>{member.name}</option>)}</select></Field></div>
   <Field label="Contribution link" hint="Link a code review, document, design, or another result the reviewer can inspect. Optional."><input type="url" name="submissionUrl" maxLength={2048} placeholder="https://…" defaultValue={base.submissionUrl||''}/></Field>
   {admin&&<Field label="Reviewer notes"><textarea name="reviewNote" maxLength={4000} rows={3} defaultValue={base.reviewNote||''} placeholder="Record useful context for the review."/></Field>}
   <p className={styles.formHint}>Submitting for review keeps the outcome fixed until it is accepted or returned to in progress.</p>
  </Form>
 </div>;
}

function TaskDetail(p:WorkspaceProps&{task:Task;onClose:()=>void}){
 const task=p.task,admin=['owner','admin'].includes(p.company.role),canEdit=admin||task.createdBy===p.user.id||task.assigneeId===p.user.id;
 const [decision,setDecision]=useState<'accept'|'changes'|null>(null),[moving,setMoving]=useState(false),[error,setError]=useState(''),[taskDirty,setTaskDirty]=useState(false),[reviewDirty,setReviewDirty]=useState(false);
 const dirty=taskDirty||reviewDirty,discardMessage='Discard your unsaved task changes?';useDraftNavigationGuard(dirty,discardMessage);
 const memberName=(id?:string|null)=>p.workspace.members.find(member=>member.userId===id)?.name;
 const assignee=p.workspace.members.find(member=>member.userId===task.assigneeId),submittedAgent=p.workspace.agents.find(agent=>agent.id===task.submittedAgentId);
 const locked=task.status==='review'||task.status==='done';
 return <Modal title={task.title} description={taskReference(task)} onClose={()=>{if(!dirty||window.confirm(discardMessage))p.onClose();}} wide><div className={styles.detail}>
  <div className={styles.detailMeta}><span className={styles.status} data-status={task.status}>{statusName(task.status)}</span><time dateTime={task.updatedAt}>Updated {when(task.updatedAt)}</time></div>
  <dl className={styles.peopleMetadata}><div><dt>Owner</dt><dd>{assignee?<><Avatar name={assignee.name} color={assignee.avatarColor} size="tiny"/>{assignee.name}</>:task.assigneeId?'Former teammate':'Unassigned'}</dd></div><div><dt>Created by</dt><dd>{memberName(task.createdBy)||'Former teammate'}</dd></div>{(task.submittedBy||task.submittedAgentId)&&<div><dt>Submitted by</dt><dd>{task.submittedAgentId?`${submittedAgent?.name||'Company agent'} · Agent`:memberName(task.submittedBy)||'Former teammate'}</dd></div>}{task.approvedBy&&<div><dt>Accepted by</dt><dd>{memberName(task.approvedBy)||'Former administrator'}</dd></div>}</dl>
  {!locked&&task.reviewNote&&<section className={styles.outcome}><h3>Review feedback</h3><p className={styles.prose}>{task.reviewNote}</p></section>}
  {(locked||!canEdit)?<section className={styles.detailSection}><h3>Outcome & acceptance criteria</h3><p className={styles.prose}>{task.description||'No additional context was added.'}</p></section>:<TaskEditor {...p} onDirtyChange={setTaskDirty}/>}
  {(locked||!canEdit)&&(task.submissionUrl||task.submissionSummary)&&<section className={styles.outcome}><div className="row"><FileCheck2 size={20}/><h3>Submitted contribution</h3></div>{task.submissionSummary&&<p className={styles.prose}>{task.submissionSummary}</p>}{safeUrl(task.submissionUrl)&&<a className="button secondary" href={safeUrl(task.submissionUrl)} target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/>{task.status==='done'?'View accepted contribution':'Open contribution link'}</a>}</section>}
  {!canEdit&&!locked&&<p className={styles.formHint}>You can read this task. Its creator, owner, or a company administrator can edit it.</p>}
  {task.status==='done'&&<section className={styles.accepted}><CheckCheck size={23}/><div><h3>Accepted by an independent reviewer</h3><p className={styles.prose}>{task.reviewNote||'The reviewer accepted this outcome.'}</p><small>This contribution is complete. Create a follow-up task for further work.</small></div></section>}
  {task.status==='review'&&<section className={styles.reviewZone}><div className="row"><ShieldCheck size={22}/><h3>Independent review</h3></div><p>{canReview(task,p)?'Check the submitted outcome against the acceptance criteria, then record your decision.':'An administrator who did not perform or sponsor this contribution must accept it.'}</p>{task.reviewNote&&<blockquote className={styles.reviewNote}>{task.reviewNote}</blockquote>}
   {canReview(task,p)?decision?<Form submit={decision==='accept'?'Accept contribution':'Return to in progress'} onSubmit={async form=>{await api(`/api/companies/${p.company.id}/tasks/${task.id}`,'PATCH',{status:decision==='accept'?'done':'doing',reviewNote:values(form).reviewNote});setReviewDirty(false);await p.refresh();setDecision(null);p.notify(decision==='accept'?'Contribution accepted and recorded.':'Changes requested. The task is back in progress.');}}><Field label="Review decision"><textarea name="reviewNote" required maxLength={4000} rows={4} onChange={()=>setReviewDirty(true)} placeholder={decision==='accept'?'What did you verify? Why is this ready to accept?':'Describe the changes needed before another review.'}/></Field><button type="button" className="text-button" onClick={()=>{if(!reviewDirty||window.confirm(discardMessage)){setDecision(null);setReviewDirty(false);}}}>Cancel review</button></Form>:<div className={styles.actions}><button className="button primary" onClick={()=>setDecision('accept')}><Check size={16}/> Review and accept</button><button className="button secondary" onClick={()=>setDecision('changes')}>Request changes</button></div>:null}
   {canEdit&&!canReview(task,p)&&<button className="button secondary" disabled={moving} onClick={async()=>{setMoving(true);setError('');try{await api(`/api/companies/${p.company.id}/tasks/${task.id}`,'PATCH',{status:'doing'});await p.refresh();p.notify('Task returned to in progress. You can edit the contribution again.');}catch(cause){setError((cause as Error).message);}finally{setMoving(false);}}}>{moving?'Updating…':'Continue working'}</button>}
   {error&&<p className="error-message" role="alert">{error}</p>}
  </section>}
 </div></Modal>;
}

export function VaultView({notify}:{notify:(message:string)=>void}){
 const [skills,setSkills]=useState<Skill[]|null>(null),[error,setError]=useState(''),[editing,setEditing]=useState<Skill|null>(null),[creating,setCreating]=useState(false),[viewing,setViewing]=useState<string|null>(null);
 const [query,setQuery]=useState(''),[sort,setSort]=useState('updated'),[exporting,setExporting]=useState(false);
 const active=useRef(true),requestVersion=useRef(0);
 async function refresh(){const version=++requestVersion.current;try{const result=await api<{skills:Skill[]}>('/api/vault');if(active.current&&version===requestVersion.current){setSkills(result.skills);setError('');}}catch(cause){if(active.current&&version===requestVersion.current)setError((cause as Error).message);}}
 useEffect(()=>{active.current=true;void refresh();return()=>{active.current=false;requestVersion.current++;};},[]);
 const visible=useMemo(()=>{const search=query.trim().toLowerCase();return (skills||[]).filter(skill=>[skill.title,skill.description,skill.content].join(' ').toLowerCase().includes(search)).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):sort==='version'?b.version-a.version:Date.parse(b.updatedAt)-Date.parse(a.updatedAt));},[skills,query,sort]);
 const viewed=skills?.find(skill=>skill.id===viewing);
 return <>
  <PageHead eyebrow="PERSONAL KNOWLEDGE" title="My skill vault" description="Your private prompts, processes, and working knowledge. Keep what helps you do your best work." action={<div className={styles.actions}><button className="button secondary" disabled={exporting} onClick={async()=>{setExporting(true);try{const exported=await api<unknown>('/api/vault/export');if(!active.current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(exported,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='coatria-personal-skills.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Your personal vault export is ready.');}catch(cause){if(active.current)notify((cause as Error).message);}finally{if(active.current)setExporting(false);}}}><Download size={16}/>{exporting?'Preparing export…':'Export my skills'}</button><button className="button primary" onClick={()=>{setEditing(null);setCreating(true);}}><Plus size={16}/> Add a skill</button></div>}/>
  <section className={styles.vaultSummary}><span className={styles.lockSymbol}><LockKeyhole size={24}/></span><div><h2>A collection that belongs to you.</h2><p>Only you can read these skills. Company work and files stay in their workspace.</p></div><div className={styles.vaultCount}><strong>{skills?skills.length:'—'}</strong><span>{skills?.length===1?'saved skill':'saved skills'}</span></div></section>
  <section className={styles.workspaceTools} aria-label="Skill collection controls"><div className={styles.toolbar}><div className={styles.search}><Search size={16}/><input aria-label="Search your skills" placeholder="Search titles, descriptions, or instructions…" value={query} onChange={event=>setQuery(event.target.value)}/>{query&&<button type="button" aria-label="Clear skill search" onClick={()=>setQuery('')}><X size={15}/></button>}</div><label className={styles.select}><span>Sort</span><select aria-label="Sort skills" value={sort} onChange={event=>setSort(event.target.value)}><option value="updated">Recently updated</option><option value="title">Title A–Z</option><option value="version">Most versions</option></select></label></div></section>
  {skills&&<div className={styles.results}><span role="status">{visible.length} {visible.length===1?'skill':'skills'}{query.trim()?' of '+skills.length:''}</span><span><LockKeyhole size={12}/> Visible only to you</span></div>}
  {error?<div className="error-message" role="alert">{error}<button className="text-button" onClick={()=>void refresh()}>Try again</button></div>:!skills?<Loading label="Opening your private vault"/>:!skills.length?<section className="panel"><Empty icon={BookOpen} title="Start with something you know well." description="A useful prompt, a repeatable process, or a lesson you have permission to keep. Give it a title and add the steps." action={<button className="button primary" onClick={()=>setCreating(true)}><Plus size={16}/> Capture your first skill</button>}/></section>:!visible.length?<section className="panel"><Empty icon={Search} title="No skills match your search." description="Search a phrase from the title, description, or instructions. Your saved collection is still here." action={<button className="button secondary" onClick={()=>setQuery('')}>Clear skill search</button>}/></section>:<div className={styles.skillGrid}>{visible.map(skill=><button className={styles.skillCard} key={skill.id} onClick={()=>setViewing(skill.id)} aria-label={'Open skill: '+skill.title}><div className={styles.skillTop}><span><BookOpen size={20}/></span><Badge>Version {skill.version}</Badge></div><h2>{skill.title}</h2><p>{skill.description||'Open this skill to read the instructions.'}</p><footer><time dateTime={skill.updatedAt}>Updated {when(skill.updatedAt)}</time><ArrowRight size={16}/></footer></button>)}</div>}
  <div className={styles.explainer}><ShieldCheck size={17}/><p><strong>Keep the knowledge you own.</strong> Each save adds an immutable version. Your export includes your personal skills and their history, without company data.</p></div>
  {(creating||editing)&&<SkillEditor key={editing?.id||'new'} skill={editing} onClose={()=>{setCreating(false);setEditing(null);}} onSaved={async saved=>{await refresh();if(!active.current)return;setCreating(false);setEditing(null);if(creating){setQuery('');setSort('updated');}notify(`Version ${saved.version} saved to your private vault.`);}}/>}
  {viewed&&<Modal title={viewed.title} description="YOUR PRIVATE SKILL" onClose={()=>setViewing(null)} wide><div className={styles.reader}><div className={styles.detailMeta}><Badge>Version {viewed.version}</Badge><span><LockKeyhole size={12}/> Only you · Updated {when(viewed.updatedAt)}</span></div>{viewed.description&&<p className={styles.readerDescription}>{viewed.description}</p>}<div className={styles.readerHeading}><h3>Instructions & knowledge</h3><CopyButton text={viewed.content} label="Copy instructions"/></div><pre className={styles.skillContent}>{viewed.content}</pre><div className={styles.readerFooter}><p>Saving an edit adds a version. Your vault export includes the version history.</p><button className="button primary" onClick={()=>{setEditing(viewed);setViewing(null);}}><Pencil size={16}/> Edit and save a new version</button></div></div></Modal>}
 </>;
}

function SkillEditor({skill,onClose,onSaved}:{skill:Skill|null;onClose:()=>void;onSaved:(skill:Skill)=>Promise<void>}){
 const [content,setContent]=useState(skill?.content||''),[dirty,setDirty]=useState(false);
 useDraftNavigationGuard(dirty,'Discard your unsaved skill changes?');
 const close=()=>{if(!dirty||window.confirm('Discard your unsaved skill changes?'))onClose();};
 return <Modal title={skill?'Refine your craft.':'Keep a little of what you’ve learned.'} description={skill?`You’re editing version ${skill.version}. Saving creates version ${skill.version+1}.`:'A personal skill is visible only to you, across every company you join.'} onClose={close} wide><div className={styles.editor} onChange={()=>setDirty(true)}><div className={styles.editorNote}><LockKeyhole size={16}/><span>Private to you</span><span>{dirty?'Unsaved changes':skill?'Saved version '+skill.version:'New skill'}</span></div><Form submit={skill?'Save new version':'Save to my vault'} onSubmit={async form=>{const result=await api<{skill:Skill}>(skill?`/api/vault/${skill.id}`:'/api/vault',skill?'PATCH':'POST',values(form));setDirty(false);await onSaved(result.skill);}}><Field label="Skill title" hint="Choose a name you’ll recognize when searching later."><input name="title" required maxLength={160} defaultValue={skill?.title} placeholder="e.g. Writing a useful creative brief"/></Field><Field label="Short description" hint="When is this useful, and what does it help you do?"><input name="description" maxLength={4000} defaultValue={skill?.description} placeholder="Use this when…"/></Field><Field label="Instructions, process or knowledge"><textarea name="content" required rows={13} maxLength={50000} value={content} onChange={event=>setContent(event.target.value)} placeholder="Start with the context, then add the steps. Include examples and how to check the result."/></Field><div className={styles.editorCounter}><span>Your own methods or material you’re authorized to retain.</span><span>{content.length.toLocaleString()} / 50,000</span></div></Form></div></Modal>;
}
