import assert from 'node:assert/strict';
import test from 'node:test';
import {spawnSync} from 'node:child_process';
import {chmod,copyFile,link,lstat,mkdir,mkdtemp,readFile,readdir,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {dirname,join,resolve} from 'node:path';
import {gunzipSync} from 'node:zlib';
import {pathToFileURL} from 'node:url';
import {ARCHIVE_HOST_PINS,ARCHIVE_RUNTIME_EMPTY_DIRECTORIES,archiveHostHash as hash,parseArchiveRuntime,createArchiveEmptyDirectories} from './archive-host-package.mjs';
import {ARCHIVE_HOST_SOURCE_FILES,buildArchiveHostBundle} from './build-archive-host-bundle.mjs';
import {REFERENCE_HOST_SOURCE_FILES} from './reference-host-package.mjs';
import {IMAGE_PREPARATION_HOST_SOURCE_FILES} from './image-preparation-host-package.mjs';
import {buildReferenceHostBundle} from './build-reference-host-bundle.mjs';
import {buildImagePreparationHostBundle} from './build-image-preparation-host-bundle.mjs';
import {CI_HOST_RELEASE_COMPONENTS as components,CI_HOST_OPERATOR_SOURCES as operatorSources,createCiHostReleaseArchive,inspectCiHostRelease,finalizeCiHostReleases,hostReleaseArchiveHash,retainCiHostRelease,publishCiHostRelease} from './export-host-release-ci.mjs';
const json=value=>Buffer.from(JSON.stringify(value,null,2)+'\n');
const git=(root,args)=>{const r=spawnSync('git',['-c','core.autocrlf=false','-c','user.name=Release Fixture','-c','user.email=fixture@example.invalid','-C',root,...args],{encoding:'utf8',timeout:15000});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};
const entries={'reference':'run-reference-worker.mts','reference-qualification':'qualify-reference-host.mts','image-preparation':'run-image-preparation-worker.mts','image-preparation-qualification':'qualify-image-preparation-host.mts','reference-registrar':'register-reference-host.mts','image-preparation-registrar':'register-image-preparation-host.mts','image-preparation-control':'control-image-preparation-host.mts'};
async function fixture(t){
 const temp=await mkdtemp(join(tmpdir(),'coatria-release-export-'));t.after(async()=>{assert.equal(dirname(resolve(temp)),resolve(tmpdir()));assert.match(temp.split(/[\\/]/).at(-1),/^coatria-release-export-/);await rm(temp,{recursive:true,force:true});});
 const repo=join(temp,'repo'),runtime=join(temp,'runtime'),output=join(repo,'releases'),evidence=join(repo,'evidence');for(const path of [repo,runtime,output,evidence])await mkdir(path);
 const source=new Map();for(const path of [...REFERENCE_HOST_SOURCE_FILES,...IMAGE_PREPARATION_HOST_SOURCE_FILES,...ARCHIVE_HOST_SOURCE_FILES.map(p=>'scripts/hosting/'+p),...operatorSources,...Object.values(entries).map(p=>'scripts/hosting/'+p),'scripts/higgsfield-archive-worker.ts','src/lib/fixture.ts'])source.set(path,Buffer.from('Original synthetic offline release fixture: '+path+'\n'));
 // Real reviewed operator modules allow an extracted-kit import/plan test; the
 // fixture Git repository still independently pins their exact bytes.
 for(const path of operatorSources)source.set(path,await readFile(new URL('../../'+path,import.meta.url)));
 source.set('package.json',Buffer.from('{"name":"release-fixture"}\n'));source.set('package-lock.json',Buffer.from(JSON.stringify({lockfileVersion:3,packages:{'node_modules/esbuild':{version:'0.28.2',integrity:'sha512-c3ludGhldGlj'}}})+'\n'));
 for(const[path,bytes]of source){await mkdir(dirname(join(repo,path)),{recursive:true});await writeFile(join(repo,path),bytes);}git(repo,['init','--quiet']);git(repo,['add','.']);git(repo,['commit','--quiet','-m','Synthetic transfer fixture']);const commit=git(repo,['rev-parse','HEAD']),tree=git(repo,['rev-parse','HEAD^{tree}']);
 const files=[];for(const path of ['node','media-sandbox-launch','media/real/bin/ffmpeg','media/real/bin/ffprobe','media/conformance/bin/ffmpeg','media/conformance/bin/ffprobe','node_modules/tsx/package.json','node_modules/pg/package.json','node_modules/undici/index.js']){const bytes=Buffer.from(path.includes('conformance')?'Original synthetic conformance bytes':path+' synthetic bytes'),mode=path.startsWith('node_modules/')?0o444:0o555;await mkdir(dirname(join(runtime,path)),{recursive:true});await writeFile(join(runtime,path),bytes);files.push({path,bytes:bytes.length,sha256:hash(bytes),mode});}
 await createArchiveEmptyDirectories(runtime,ARCHIVE_RUNTIME_EMPTY_DIRECTORIES);const rt=parseArchiveRuntime({version:1,platform:'linux-x64',pins:ARCHIVE_HOST_PINS,sourceHashes:{launcher:hash(source.get('scripts/hosting/media-sandbox-launch.c')),probe:hash(source.get('scripts/hosting/media-sandbox-probe.c'))},packageLockSha256:hash(source.get('package-lock.json')),bubblewrapSha256:'a'.repeat(64),files,emptyDirectories:ARCHIVE_RUNTIME_EMPTY_DIRECTORIES}),raw=Buffer.from(JSON.stringify(rt)+'\n');await writeFile(join(runtime,'runtime-manifest.json'),raw);
 const bundles={};for(const [service,entry]of Object.entries(entries)){const path=join(temp,service);await mkdir(path);const program=Buffer.from('export const synthetic = '+JSON.stringify(service)+';\n'),entryPath='scripts/hosting/'+entry,dependency=files.find(f=>f.path==='node_modules/undici/index.js'),manifest={version:1,kind:'coatria-trusted-service-bundle',service,sourceCommit:commit,sourceTree:tree,image:ARCHIVE_HOST_PINS.nodeImage,nodeVersion:ARCHIVE_HOST_PINS.nodeVersion,compiler:{name:'esbuild',version:'0.28.2',packageIntegrity:'sha512-c3ludGhldGlj'},packageLockSha256:rt.packageLockSha256,inputs:[{path:entryPath,bytes:source.get(entryPath).length,sha256:hash(source.get(entryPath)),kind:'source'},{path:dependency.path,bytes:dependency.bytes,sha256:dependency.sha256,kind:'dependency'}],runtime:{path:'runtime.mjs',bytes:program.length,sha256:hash(program)},deployable:true,qualified:false};await writeFile(join(path,'runtime.mjs'),program);await writeFile(join(path,'bundle.json'),json(manifest));bundles[service]={output:path,bundleSha256:hash(json(manifest)),runtime:manifest.runtime};}
 const common={sourceRoot:repo,commit,runtimeRoot:runtime,runtimeManifestSha256:hash(raw)};
 bundles['archive-host']=await buildArchiveHostBundle({...common,output:join(temp,'archive-host')});
 for(const [component,worker,qualifier,builder]of [['reference-host','reference','reference-qualification',buildReferenceHostBundle],['image-preparation-host','image-preparation','image-preparation-qualification',buildImagePreparationHostBundle]])bundles[component]=await builder({...common,workerBundlePath:bundles[worker].output,workerBundleSha256:bundles[worker].bundleSha256,qualifierBundlePath:bundles[qualifier].output,qualifierBundleSha256:bundles[qualifier].bundleSha256,output:join(temp,component)});
 return {temp,repo,runtime,output,evidence,source,commit,tree,bundles};
}
async function pack(f,component){const bundle=f.bundles[component];return createCiHostReleaseArchive({component,sourceDirectory:bundle.output,bundleSha256:bundle.bundleSha256,commit:f.commit,tree:f.tree,output:join(f.temp,'transfer-'+component)});}
function unpack(path,target){const r=spawnSync(process.platform==='win32'?'tar.exe':'/usr/bin/tar',['-xzf',path,'-C',target],{encoding:'utf8',timeout:30000});assert.equal(r.status,0,r.stderr);}
async function archiveHeaders(path){const bytes=gunzipSync(await readFile(path));assert.equal(bytes.includes(Buffer.from('SYNTHETIC_EXCLUDED_CREDENTIAL_SENTINEL')),false);for(let at=0;at+512<=bytes.length&&bytes[at]!==0;){const header=bytes.subarray(at,at+512),octal=(start,length)=>parseInt(header.subarray(start,start+length).toString().replace(/\0/g,'').trim(),8)||0;assert.equal(octal(108,8),0);assert.equal(octal(116,8),0);assert.ok(['0','5','x','\0'].includes(header.subarray(156,157).toString()));at+=512+Math.ceil(octal(124,12)/512)*512;}}
async function ready(f){
 for(const component of components){const retained=await pack(f,component);for(const name of [component+'.tar.gz',component+'.json'])await copyFile(join(retained.root,name),join(f.output,name));const host=component.endsWith('-host'),control=component==='image-preparation-control',path={'archive-host':'archive-host-bundle.json','reference-host':'reference-host-ci.json','image-preparation-host':'image-preparation-host-ci.json','reference-registrar':'reference-enrollment-ci.json','image-preparation-registrar':'image-preparation-enrollment-ci.json','image-preparation-control':'image-preparation-installed-flow-ci.json'}[component];await writeFile(join(f.evidence,path),json({[host?'qualified':'passed']:true,[host?'commit':'sourceCommit']:f.commit,[host?'tree':'sourceTree']:f.tree,[host?'bundleSha256':control?'controllerBundleSha256':'registrarBundleSha256']:retained.receipt.bundleSha256,...(!host?{[control?'controllerRuntimeSha256':'registrarRuntimeSha256']:retained.receipt.runtimeSha256}:{})}));}
}
const finalize=f=>finalizeCiHostReleases({sourceRoot:f.repo,commit:f.commit,output:f.output,evidenceDirectory:f.evidence});
test('all six real tar roundtrips preserve manifests, native empty directories, modes and credential-free boundaries',async t=>{
 const f=await fixture(t);await writeFile(join(f.repo,'.env.private'),'SYNTHETIC_EXCLUDED_CREDENTIAL_SENTINEL');await mkdir(join(f.temp,'installed-config'));await writeFile(join(f.temp,'installed-config','worker.env'),'SYNTHETIC_EXCLUDED_CREDENTIAL_SENTINEL');
 for(const component of components){const retained=await pack(f,component),target=join(f.temp,'roundtrip-'+component);await mkdir(target);const archive=join(retained.root,retained.receipt.archive.path);await archiveHeaders(archive);unpack(archive,target);const parsed=await inspectCiHostRelease(component,target,retained.receipt.bundleSha256,f.commit,f.tree);assert.equal(retained.receipt.qualified,false);assert.equal(retained.receipt.activationAuthorized,false);for(const entry of parsed.emptyDirectories){assert.deepEqual(await readdir(join(target,entry.path)),[]);if(process.platform!=='win32')assert.equal((await lstat(join(target,entry.path))).mode&0o777,entry.mode);}for(const entry of parsed.files){assert.equal(hash(await readFile(join(target,entry.path))),entry.sha256);if(process.platform!=='win32')assert.equal((await lstat(join(target,entry.path))).mode&0o777,entry.mode);}assert.equal((await readFile(join(target,'bundle.json'),'utf8')).includes('SYNTHETIC_EXCLUDED_CREDENTIAL_SENTINEL'),false);assert.equal(parsed.files.some(e=>/worker\.env|\.env\.private|qualified\.json|service-token/.test(e.path)),false);}
});
test('unexpected private file, hardlink, wrong source and output containment reject before a receipt exists',async t=>{
 const f=await fixture(t),b=f.bundles['reference-registrar'];await writeFile(join(b.output,'worker.env'),'SYNTHETIC_UNEXPECTED_PRIVATE_FILE');await assert.rejects(pack(f,'reference-registrar'));await rm(join(b.output,'worker.env'));await link(join(b.output,'runtime.mjs'),join(f.temp,'linked-runtime'));await assert.rejects(pack(f,'reference-registrar'));await rm(join(f.temp,'linked-runtime'));
 for(const extra of [{commit:'0'.repeat(40)},{bundleSha256:'0'.repeat(64)},{output:join(b.output,'nested')}])await assert.rejects(createCiHostReleaseArchive({component:'reference-registrar',sourceDirectory:b.output,bundleSha256:b.bundleSha256,commit:f.commit,tree:f.tree,output:join(f.temp,'rejected'),...extra}));
 await assert.rejects(readFile(join(f.temp,'rejected','reference-registrar.json')));
});
test('final index binds every archive and actual tested operator digest plus only seven exact Git source files',async t=>{
 const f=await fixture(t);await ready(f);await writeFile(join(f.repo,operatorSources[0]),'Uncommitted source must not enter operator kit');await writeFile(join(f.output,'../.env.private'),'SYNTHETIC_EXCLUDED_CREDENTIAL_SENTINEL');const index=await finalize(f);assert.equal(index.components.length,6);assert.equal(index.qualified,false);assert.equal(index.productionQualified,false);assert.equal(index.activationAuthorized,false);assert.deepEqual(index.operatorSource.files.map(f=>f.path),operatorSources);
 const target=join(f.temp,'operator-roundtrip');await mkdir(target);await archiveHeaders(join(f.output,index.operatorSource.path));unpack(join(f.output,index.operatorSource.path),target);for(const file of index.operatorSource.files)assert.deepEqual(await readFile(join(target,file.path)),f.source.get(file.path));assert.equal((await readFile(join(f.output,'SHA256SUMS'),'utf8')).trim().split('\n').length,7);for(const c of index.components)assert.equal((await hostReleaseArchiveHash(join(f.output,c.archive.path))).sha256,c.archive.sha256);
 const imported=new Map();for(const path of operatorSources)imported.set(path,await import(pathToFileURL(join(target,path)).href));
 const image=imported.get('scripts/hosting/image-preparation-host-package.mjs'),bundle=JSON.parse(await readFile(join(f.bundles['image-preparation-host'].output,'bundle.json'))),scope=image.parseImagePreparationHostScope({version:1,serviceId:'10000000-0000-4000-8000-000000000001',companyId:'20000000-0000-4000-8000-000000000001',projectIds:['30000000-0000-4000-8000-000000000001'],origin:'https://coatria.example',expiresAt:new Date(Date.now()+3000000).toISOString(),location:'Offline package plan only',gateways:[{projectId:'30000000-0000-4000-8000-000000000001',origin:'https://gateway.example.invalid'}]});const plan=image.imagePreparationHostInstallPlan(bundle,f.bundles['image-preparation-host'].bundleSha256,scope);assert.equal(plan.qualified,false);assert.equal(plan.credentialsIncluded,false);assert.equal(typeof imported.get('scripts/hosting/prepare-media-apparmor-ci.mjs').assertReviewedProfile,'function');
 await assert.rejects(finalize(f));
});
test('incomplete releases retain prior artifacts and cannot acquire a complete index',async t=>{
 const f=await fixture(t);const retained=await pack(f,'reference-registrar');for(const name of ['reference-registrar.tar.gz','reference-registrar.json'])await copyFile(join(retained.root,name),join(f.output,name));const before=await readFile(join(f.output,'reference-registrar.tar.gz'));await assert.rejects(finalize(f));await assert.rejects(readFile(join(f.output,'release-index.json')));assert.deepEqual(await readFile(join(f.output,'reference-registrar.tar.gz')),before);await assert.rejects(pack(f,'reference-registrar'));
});
test('tampered archive, false successful report, wrong source or mismatched exercised runtime cannot finalize',async t=>{
 const f=await fixture(t);await ready(f);const path=join(f.evidence,'image-preparation-installed-flow-ci.json'),original=await readFile(path);for(const change of [{passed:false},{controllerRuntimeSha256:'0'.repeat(64)},{sourceTree:'0'.repeat(40)},{controllerBundleSha256:'0'.repeat(64)},{cleanupFailed:true}]){await writeFile(path,json({...JSON.parse(original),...change}));await assert.rejects(finalize(f));await assert.rejects(readFile(join(f.output,'release-index.json')));}await writeFile(path,original);const archive=join(f.output,'reference-registrar.tar.gz');await chmod(archive,0o600);await writeFile(archive,'tampered archive');await assert.rejects(finalize(f));await assert.rejects(readFile(join(f.output,'release-index.json')));
});
test('an existing operator-kit stage leaves immutable receipts intact and never writes the complete index',async t=>{
 const f=await fixture(t);await ready(f);const before=await readFile(join(f.output,'reference-registrar.json'));await mkdir(join(f.output,'operator-source'));await assert.rejects(finalize(f));await assert.rejects(readFile(join(f.output,'release-index.json')));assert.deepEqual(await readFile(join(f.output,'reference-registrar.json')),before);
});
test('privileged retention and publishing wrappers reject an ordinary non-CI invocation without filesystem effects',async t=>{
 const f=await fixture(t);if(process.env.CI==='true'&&process.platform==='linux')return t.skip('CI wrapper process identity differs; portable primitives above remain exercised');await assert.rejects(retainCiHostRelease({component:'reference-registrar',sourceDirectory:f.bundles['reference-registrar'].output,bundleSha256:f.bundles['reference-registrar'].bundleSha256,commit:f.commit,tree:f.tree,base:f.temp}));await assert.rejects(publishCiHostRelease({root:f.temp,receipt:{}}));assert.deepEqual(await readdir(f.output),[]);
});
