/** Synthetic observations prove durable control semantics, not installed native
 * qualification. Root-only tests exercise actual protected files and flock. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {mkdtemp,mkdir,readFile,readdir,rm,writeFile,link,symlink,rename,lstat,chmod,unlink} from 'node:fs/promises';
import {join,dirname,basename,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn,spawnSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {createImagePreparationHostControlStore,withImagePreparationHostControlLock,assertImagePreparationHostControlIdentity,executeImagePreparationHostControl} from './image-preparation-host-control.mjs';
import {deriveImagePreparationRunnerConfiguration,imagePreparationRunnerConfigurationHash} from './image-preparation-runner-configuration.mjs';
import {IMAGE_PREPARATION_HOST_RECIPE_SHA256} from './image-preparation-host-package.mjs';
const hash=v=>createHash('sha256').update(v).digest('hex'),json=v=>Buffer.from(JSON.stringify(v,null,2)+'\n');
function fixture(now=Date.now()){
 const serviceId=randomUUID(),companyId=randomUUID(),projectId=randomUUID(),bundleSha256='a'.repeat(64),release='/var/lib/coatria-image-preparation-releases/'+bundleSha256;
 const host={version:1,bundleSha256,commit:'b'.repeat(40),tree:'c'.repeat(40),release,closureSha256:'d'.repeat(64),recipeSha256:IMAGE_PREPARATION_HOST_RECIPE_SHA256,uid:65534,gid:65534,scope:{serviceId,companyId,projectIds:[projectId],origin:'https://coatria.example',location:'Synthetic finite control fixture',expiresAt:new Date(now+30*60*1000).toISOString(),gateways:[{projectId,origin:'https://gateway.example'}]},profiles:{real:{profilePath:`/etc/coatria-image-preparation/${serviceId}/real.json`,expectedProfileSha256:'e'.repeat(64)},conformance:{profilePath:`/etc/coatria-image-preparation/${serviceId}/conformance.json`,expectedProfileSha256:'f'.repeat(64)}},worker:{path:release+'/worker/runtime.mjs',sha256:'1'.repeat(64)},qualifier:{path:release+'/qualifier/runtime.mjs',sha256:'2'.repeat(64)},node:{path:release+'/runtime/node',sha256:'3'.repeat(64)},units:Object.fromEntries(['qualify','preflight','worker'].map(mode=>[mode,{name:`coatria-image-preparation-${serviceId}-${mode}.service`,sha256:hash(mode)}]))};
 const hostBytes=json(host),configuration=deriveImagePreparationRunnerConfiguration(host,hash(hostBytes),'0'.repeat(64)),configurationSha256=imagePreparationRunnerConfigurationHash(configuration);
 const receipt={version:1,kind:'coatria-image-preparation-qualification-v1',serviceId,companyId,projectIds:[projectId],sourceCommit:host.commit,sourceTree:host.tree,bundleSha256,releaseSha256:host.worker.sha256,closureSha256:host.closureSha256,recipeSha256:host.recipeSha256,qualifierSha256:host.qualifier.sha256,configurationSha256,hostConfigurationSha256:hash(hostBytes),profileSha256:host.profiles.real.expectedProfileSha256,conformanceProfileSha256:host.profiles.conformance.expectedProfileSha256,bootId:randomUUID(),uid:host.uid,gid:host.gid,expiresAt:host.scope.expiresAt,units:host.units,qualifierInvocationId:'4'.repeat(32),serviceRoot:'/sys/fs/cgroup/system.slice/'+host.units.qualify.name,evidenceSha256:'5'.repeat(64),reportSha256:'6'.repeat(64),acceptedAt:new Date(now-1000).toISOString(),qualified:true,checks:{isolation:true,resourceLimits:true,descendantCleanup:true,imagePreparation:true}};
 const receiptBytes=json(receipt);return {host,hostBytes,receipt,receiptBytes,qualificationSha256:hash(receiptBytes),configurationSha256,enrollmentIntentSha256:'7'.repeat(64),controllerBundleSha256:'8'.repeat(64)};
}
function observed(identity,mode='worker',changes={}){return {mode,unit:identity.host.units[mode].name,bootId:identity.receipt.bootId,activeState:'inactive',subState:'dead',invocationId:null,pid:0,result:null,runningReady:false,preflightPassed:false,processStopped:true,cgroupEmpty:true,cleanupConfirmed:false,...changes};}
function processFixture(identity){
 const calls={preflight:0,start:0,stop:0,local:0,authority:0},id='9'.repeat(32);let worker=observed(identity),preflight=observed(identity,'preflight');
 return {calls,id,get worker(){return worker;},set worker(v){worker=v;},units:{observe:async mode=>({...mode==='worker'?worker:preflight}),preflight:async()=>{calls.preflight++;preflight=observed(identity,'preflight',{invocationId:'a'.repeat(32),result:'success',preflightPassed:true,cleanupConfirmed:true});return preflight;},startWorker:async()=>{calls.start++;worker=observed(identity,'worker',{activeState:'active',subState:'running',invocationId:id,pid:123,runningReady:true,processStopped:false,cgroupEmpty:false});return worker;},stopWorker:async expected=>{calls.stop++;assert.equal(expected,id);worker=observed(identity,'worker',{invocationId:id,result:'success',cleanupConfirmed:true});return worker;}},verifyLocal:async()=>{calls.local++;},verifyAuthority:async()=>{calls.authority++;return {status:'committed',active:true,serviceId:identity.host.scope.serviceId};}};
}
async function setup(t,{old=false,identity=fixture(old?Date.now()-3600000:undefined),root,trusted=false}={}){root??=await mkdtemp(join(tmpdir(),'coatria-image-control-'));if(!trusted)t.after(async()=>{assert.equal(dirname(resolve(root)),resolve(tmpdir()));assert(basename(root).startsWith('coatria-image-control-'));await rm(resolve(root),{recursive:true,force:true});});const store=createImagePreparationHostControlStore(root,{trusted}),process=processFixture(identity);return {root,identity,store,...process,process};}
const run=(f,overrides={})=>executeImagePreparationHostControl({mode:'start',store:f.store,identity:f.identity,verifyLocal:f.verifyLocal,verifyAuthority:f.verifyAuthority,units:f.units,...overrides});
const absent=async path=>assert.rejects(readFile(path),error=>error.code==='ENOENT');

test('historical identity pins exact bytes, receipt, enrollment and controller hashes',()=>{
 const identity=fixture(Date.now()-3600000);assert.equal(assertImagePreparationHostControlIdentity(identity).serviceId,identity.host.scope.serviceId);
 for(const delta of [{receiptBytes:Buffer.concat([identity.receiptBytes,Buffer.from(' ')])},{hostBytes:Buffer.concat([identity.hostBytes,Buffer.from(' ')])},{configurationSha256:'0'.repeat(64)},{controllerBundleSha256:'invalid'},{unexpected:'private'}])assert.throws(()=>assertImagePreparationHostControlIdentity({...identity,...delta}),/IDENTITY_INVALID/);
});
test('start commits both fences before commands and marker exact five-field bytes before one start',async t=>{
 const f=await setup(t),normal=f.units.startWorker;f.units.preflight=async()=>{f.calls.preflight++;const s=await f.store.read(f.identity);assert(s.preflightStarted);assert(!s.startStarted);await absent(join(f.root,'worker-enabled'));return observed(f.identity,'preflight',{invocationId:'a'.repeat(32),result:'success',preflightPassed:true,cleanupConfirmed:true});};
 f.units.startWorker=async()=>{const s=await f.store.read(f.identity);assert(s.preflightStarted&&s.startStarted);assert.equal(s.workerInvocation,null);const expected={version:1,serviceId:f.identity.host.scope.serviceId,configurationSha256:f.identity.configurationSha256,qualificationSha256:f.identity.qualificationSha256,expiresAt:f.identity.host.scope.expiresAt};assert((await readFile(join(f.root,'worker-enabled'))).equals(json(expected)));return normal();};
 const result=await run(f);assert.equal(result.status,'running-ready');assert.equal(result.workerEnabled,true);assert.equal(result.cleanupConfirmed,false);assert.equal(f.calls.start,1);assert.equal(f.calls.preflight,1);assert(f.calls.authority>=6);assert.deepEqual((await f.store.read(f.identity)).workerInvocation,{bootId:f.identity.receipt.bootId,invocationId:f.id});
 const fresh=createImagePreparationHostControlStore(f.root,{trusted:false});await run(f,{store:fresh,verifyLocal:async()=>assert.fail(),verifyAuthority:async()=>assert.fail()});assert.equal(f.calls.start,1);assert.equal(f.calls.preflight,1);
});
test('systemctl acceptance is unready until later exact invocation readiness proof',async t=>{
 const f=await setup(t),normal=f.units.startWorker;f.units.startWorker=async()=>{await normal();f.process.worker={...f.process.worker,runningReady:false};return f.process.worker;};const first=await run(f);assert.equal(first.status,'running-unready');assert(!first.runningReady);
 f.process.worker={...f.process.worker,runningReady:true};const later=await run(f,{mode:'reconcile',verifyLocal:undefined,verifyAuthority:undefined});assert.equal(later.status,'running-ready');assert.equal(f.calls.start,1);
});
test('unknown start is fenced forever, unbound invocation is never adopted or stopped',async t=>{
 const f=await setup(t),normal=f.units.startWorker;f.units.startWorker=async()=>{await normal();throw Error('PRIVATE_SYSTEMCTL_REPLY');};await assert.rejects(run(f),/OUTCOME_UNKNOWN/);await absent(join(f.root,'worker-enabled'));assert.equal((await f.store.read(f.identity)).workerInvocation,null);
 const next=await run(f,{store:createImagePreparationHostControlStore(f.root,{trusted:false}),verifyLocal:undefined,verifyAuthority:undefined});assert.equal(next.status,'start-unknown');assert(!next.runningReady);assert.equal(next.invocationId,null);assert.equal(f.calls.start,1);
 await assert.rejects(run(f,{mode:'stop',verifyLocal:undefined,verifyAuthority:undefined}),/INVOCATION_UNBOUND/);assert.equal(f.calls.stop,0);assert((await f.store.read(f.identity)).stopRequested);assert(!JSON.stringify(await f.store.read(f.identity)).includes('PRIVATE_'));
});
test('actual killed child leaves the fixed start fence across process restart without another command',async t=>{
 const f=await setup(t),moduleUrl=pathToFileURL(resolve('scripts/hosting/image-preparation-host-control.mjs')).href,fixturePath=join(f.root,'synthetic-identity.json');await writeFile(fixturePath,json(f.identity));
 const script=`import {readFile} from 'node:fs/promises';import {${['createImagePreparationHostControlStore','executeImagePreparationHostControl'].join(',')}} from ${JSON.stringify(moduleUrl)};const i=JSON.parse(await readFile(process.argv[1]));i.hostBytes=Buffer.from(i.hostBytes.data);i.receiptBytes=Buffer.from(i.receiptBytes.data);const root=process.argv[2],obs=m=>({mode:m,unit:i.host.units[m].name,bootId:i.receipt.bootId,activeState:'inactive',subState:'dead',invocationId:null,pid:0,result:null,runningReady:false,preflightPassed:false,processStopped:true,cgroupEmpty:true,cleanupConfirmed:false});await executeImagePreparationHostControl({mode:'start',store:createImagePreparationHostControlStore(root,{trusted:false}),identity:i,verifyLocal:async()=>{},verifyAuthority:async()=>({status:'committed',active:true,serviceId:i.host.scope.serviceId}),units:{observe:async m=>obs(m),preflight:async()=>({...obs('preflight'),invocationId:'a'.repeat(32),result:'success',preflightPassed:true,cleanupConfirmed:true}),startWorker:async()=>{process.stdout.write('FENCED\\n');await new Promise(()=>{setInterval(()=>{},1000);});},stopWorker:async()=>{throw Error();}}});`;
 const child=spawn(process.execPath,['--import','tsx','--input-type=module','--eval',script,fixturePath,f.root],{stdio:['ignore','pipe','pipe'],windowsHide:true});let stderr='';child.stderr.on('data',b=>stderr+=b.toString());t.after(()=>{if(child.exitCode===null)child.kill('SIGKILL');});
 await new Promise((resolveReady,reject)=>{const timer=setTimeout(()=>reject(Error('Synthetic child did not reach fixed fence')),20000);child.once('exit',()=>{clearTimeout(timer);reject(Error('Synthetic child exited before fence: '+stderr));});child.stdout.on('data',b=>{if(b.toString().includes('FENCED')){clearTimeout(timer);resolveReady();}});});const exit=new Promise(resolveExit=>child.once('exit',resolveExit));child.kill('SIGKILL');await exit;
 const saved=await readFile(join(f.store.root,'start.json'));const result=await run(f,{store:createImagePreparationHostControlStore(f.root,{trusted:false}),verifyLocal:undefined,verifyAuthority:undefined});assert.equal(result.status,'start-unknown');assert.equal(f.calls.start,0);assert.equal(f.calls.preflight,0);assert((await readFile(join(f.store.root,'start.json'))).equals(saved));assert(await f.store.markerPresent(f.identity));
});
test('failed preflight cannot be repeated even when a later observation is inactive',async t=>{
 const f=await setup(t);f.units.preflight=async()=>{f.calls.preflight++;throw Error('PRIVATE_PREFLIGHT');};await assert.rejects(run(f),/OUTCOME_UNKNOWN/);const state=await f.store.read(f.identity);assert(state.preflightStarted&&!state.startStarted);const result=await run(f,{verifyAuthority:undefined,verifyLocal:undefined});assert.equal(result.status,'preflight-unknown');assert.equal(f.calls.preflight,1);assert.equal(f.calls.start,0);
});
test('authority changed during marker fsync withdraws only matching marker and retains start fence',async t=>{
 const f=await setup(t),publish=f.store.publishMarker;let published=false;f.store.publishMarker=async identity=>{await publish(identity);published=true;};await assert.rejects(run(f,{verifyAuthority:async()=>({status:'committed',active:!published,serviceId:f.identity.host.scope.serviceId})}),/AUTHORITY_INACTIVE/);assert.equal(f.calls.start,0);assert((await f.store.read(f.identity)).startStarted);await absent(join(f.root,'worker-enabled'));await run(f,{verifyLocal:undefined,verifyAuthority:undefined});assert.equal(f.calls.start,0);
});
test('failed current qualification or active baseline has no intent and cannot start',async t=>{
 for(const boundary of ['authority','local','unit']){const f=await setup(t);if(boundary==='unit')f.process.worker=observed(f.identity,'worker',{activeState:'active',subState:'running',invocationId:f.id,pid:5,processStopped:false,cgroupEmpty:false});await assert.rejects(run(f,{...(boundary==='authority'?{verifyAuthority:async()=>({status:'committed',active:false,serviceId:f.identity.host.scope.serviceId})}:{}),...(boundary==='local'?{verifyLocal:async()=>{throw Error('PRIVATE');}}:{})}));assert.equal(await f.store.read(f.identity),null);assert.equal(f.calls.start,0);}
});
test('stop before start is permanent and historical expired stop/reconcile require no authority',async t=>{
 const f=await setup(t,{old:true});await assert.rejects(run(f),/EXPIRED/);assert.equal(await f.store.read(f.identity),null);const stopped=await run(f,{mode:'stop',verifyLocal:undefined,verifyAuthority:undefined});assert.equal(stopped.status,'stopped');assert(stopped.processStopped&&!stopped.cleanupConfirmed);assert((await f.store.read(f.identity)).stopRequested);const again=await run(f,{verifyLocal:undefined,verifyAuthority:undefined});assert.equal(again.status,'stopped');assert.equal(f.calls.start,0);assert.equal(f.calls.preflight,0);
});
test('stop withdraws marker before waiting, exact stopped process is not cleanup proof',async t=>{
 const f=await setup(t);await run(f);f.units.stopWorker=async expected=>{f.calls.stop++;assert.equal(expected,f.id);await absent(join(f.root,'worker-enabled'));assert((await f.store.read(f.identity)).stopRequested);f.process.worker=observed(f.identity,'worker',{invocationId:f.id,result:'failure',cleanupConfirmed:false});return f.process.worker;};const result=await run(f,{mode:'stop',verifyLocal:undefined,verifyAuthority:undefined});assert.equal(result.status,'stopped');assert(result.processStopped&&!result.cleanupConfirmed);assert(!result.workerEnabled);assert.equal(f.calls.stop,1);
});
test('known invocation naturally exits without becoming an unknown start or fabricated cleanup',async t=>{
 const f=await setup(t);await run(f);f.process.worker=observed(f.identity,'worker',{invocationId:f.id,result:'failure'});const exited=await run(f,{mode:'reconcile',verifyLocal:undefined,verifyAuthority:undefined});assert.equal(exited.status,'stopped');assert(exited.processStopped&&!exited.cleanupConfirmed);assert.equal(exited.invocationId,f.id);assert.equal(f.calls.stop,0);assert.equal(f.calls.start,1);
 f.process.worker={...f.process.worker,result:'success',cleanupConfirmed:true};const drained=await run(f,{mode:'reconcile',verifyLocal:undefined,verifyAuthority:undefined});assert.equal(drained.status,'stopped');assert(drained.cleanupConfirmed);assert.equal(f.calls.stop,0);
});
test('expired finite authority does not block exact previously recorded invocation stop',async t=>{
 const now=Date.now();t.mock.timers.enable({apis:['Date'],now});const f=await setup(t);await run(f);t.mock.timers.tick(31*60*1000);const stopped=await run(f,{mode:'stop',verifyLocal:async()=>assert.fail('Stop must not need current qualification'),verifyAuthority:async()=>assert.fail('Stop must not need SQL')});assert.equal(stopped.status,'stopped');assert(stopped.processStopped&&stopped.cleanupConfirmed);assert.equal(f.calls.stop,1);assert.equal(f.calls.start,1);await absent(join(f.root,'worker-enabled'));
});
test('wrong invocation or reboot never sends stop to replacement worker',async t=>{
 for(const delta of [{invocationId:'b'.repeat(32)},{bootId:randomUUID()}]){const f=await setup(t);await run(f);f.process.worker={...f.process.worker,...delta};await assert.rejects(run(f,{mode:'stop',verifyLocal:undefined,verifyAuthority:undefined}),/INVOCATION_CHANGED/);assert.equal(f.calls.stop,0);await absent(join(f.root,'worker-enabled'));assert((await f.store.read(f.identity)).stopRequested);}
});
test('stop command uncertainty never becomes cleanup and cannot license another start',async t=>{
 const f=await setup(t);await run(f);f.units.stopWorker=async()=>{f.calls.stop++;throw Error('PRIVATE_STOP_TIMEOUT');};await assert.rejects(run(f,{mode:'stop',verifyLocal:undefined,verifyAuthority:undefined}),/OUTCOME_UNKNOWN/);await absent(join(f.root,'worker-enabled'));const result=await run(f,{verifyLocal:undefined,verifyAuthority:undefined});assert.equal(result.status,'stop-unknown');assert.equal(result.cleanupConfirmed,false);assert.equal(f.calls.start,1);
});
test('malformed observation, false cleanup and mutated identity cannot be projected as readiness',async t=>{
 for(const mutation of [{processStopped:true},{cleanupConfirmed:true},{unit:'other.service'},{token:'PRIVATE'}]){const f=await setup(t),normal=f.units.startWorker;f.units.startWorker=async()=>({...await normal(),...mutation});await assert.rejects(run(f),/OBSERVATION_INVALID/);assert.equal((await f.store.read(f.identity)).workerInvocation,null);}
 const f=await setup(t);await assert.rejects(run(f,{verifyLocal:async()=>{f.identity.controllerBundleSha256='a'.repeat(64);}}),/IDENTITY_CHANGED/);assert.equal(f.calls.start,0);
});
test('partial fences, hardlinks, symlinks and replaced private directories fail without repair',async t=>{
 for(const kind of ['partial','hardlink','symlink','directory']){const f=await setup(t);await run(f,{mode:'stop'});const path=join(f.store.root,'stop.json');if(kind==='partial')await writeFile(path,'{');if(kind==='hardlink')await link(path,join(f.root,'aliased'));if(kind==='symlink'){const saved=join(f.root,'saved');await rename(path,saved);try{await symlink(saved,path);}catch(error){if(process.platform==='win32'&&error.code==='EPERM'){await rename(saved,path);continue;}throw error;}}if(kind==='directory'){await rename(f.store.root,join(f.root,'old-control'));await mkdir(f.store.root);await writeFile(join(f.store.root,'intent.json'),json({}));}await assert.rejects(f.store.read(f.identity));assert.equal(f.calls.start,0);}
});
test('foreign marker is neither replaced nor removed and journal accepts bounded fixed fields only',async t=>{
 const f=await setup(t);await writeFile(join(f.root,'worker-enabled'),'PRIVATE_FOREIGN');await assert.rejects(run(f),/MARKER_CONFLICT/);assert.equal(await readFile(join(f.root,'worker-enabled'),'utf8'),'PRIVATE_FOREIGN');await unlink(join(f.root,'worker-enabled'));const result=await run(f,{mode:'stop'});await assert.rejects(f.store.recordOutcome(f.identity,{...result,secret:'PRIVATE'}));const names=(await readdir(f.store.root)).filter(n=>n.startsWith('event-')),bytes=await readFile(join(f.store.root,names[0]));for(let n=1;n<256;n++)await writeFile(join(f.store.root,'event-'+randomUUID()+'.json'),bytes,{mode:0o600});await assert.rejects(f.store.recordOutcome(f.identity,result),/JOURNAL_FULL/);assert.equal((await readdir(f.store.root)).filter(n=>n.startsWith('event-')).length,256);
});
test('simultaneous portable controllers cannot execute a second preflight while the first owns lock',async t=>{
 const f=await setup(t);let entered,release;const waiting=new Promise(r=>entered=r),block=new Promise(r=>release=r),normal=f.units.preflight;f.units.preflight=async()=>{entered();await block;return normal();};const first=run(f);await waiting;try{await assert.rejects(run(f,{store:createImagePreparationHostControlStore(f.root,{trusted:false})}),/BUSY/);}finally{release();}await first;assert.equal(f.calls.start,1);
});
test('root Linux actual flock, protected marker ownership and group read; no real units invoked',{skip:process.platform!=='linux'||process.getuid?.()!==0},async t=>{
 const identity=fixture(),parent='/etc/coatria-image-preparation',root=parent+'/'+identity.host.scope.serviceId;await mkdir(parent,{recursive:true,mode:0o755});await mkdir(root,{mode:0o755});t.after(async()=>{assert.equal(dirname(resolve(root)),parent);assert.equal(basename(root),identity.host.scope.serviceId);assert(/^[a-f0-9-]{36}$/.test(basename(root)));await rm(resolve(root),{recursive:true,force:true});});
 const f=await setup(t,{identity,root,trusted:true});await withImagePreparationHostControlLock(root,async()=>{await assert.rejects(withImagePreparationHostControlLock(root,async()=>assert.fail()),/BUSY/);});const lock=await lstat(join(root,'control.lock'));assert.equal(lock.uid,0);assert.equal(lock.mode&0o777,0o600);assert.equal(lock.size,0);
 await run(f);for(const name of await readdir(f.store.root)){const stat=await lstat(join(f.store.root,name));assert.equal(stat.uid,0);assert.equal(stat.mode&0o777,0o600);assert.equal(stat.nlink,1);}assert.equal((await lstat(f.store.root)).mode&0o777,0o700);const markerPath=join(root,'worker-enabled'),stat=await lstat(markerPath);assert.equal(stat.uid,0);assert.equal(stat.gid,identity.host.gid);assert.equal(stat.mode&0o777,0o640);
 const reader=spawnSync(process.execPath,['--input-type=module','--eval',"import{readFileSync}from'node:fs';process.setgroups([]);process.setgid(Number(process.argv[2]));process.setuid(Number(process.argv[3]));const m=JSON.parse(readFileSync(process.argv[1]));process.stdout.write(JSON.stringify({read:m.version===1&&Object.keys(m).length===5,uid:process.getuid(),gid:process.getgid()}));",markerPath,String(identity.host.gid),String(identity.host.uid)],{encoding:'utf8',shell:false,env:{PATH:'/usr/bin:/bin',LANG:'C'},timeout:5000,maxBuffer:1024});assert.equal(reader.status,0);assert.deepEqual(JSON.parse(reader.stdout),{read:true,uid:identity.host.uid,gid:identity.host.gid});
 await run(f,{mode:'stop',verifyLocal:undefined,verifyAuthority:undefined});await absent(markerPath);assert((await f.store.read(identity)).stopRequested);assert.equal((await lstat(join(root,'control.lock'))).ino,lock.ino);
});
test('root Linux writable files and substituted lock inode are rejected',{skip:process.platform!=='linux'||process.getuid?.()!==0},async t=>{
 const identity=fixture(),parent='/etc/coatria-image-preparation',root=parent+'/'+identity.host.scope.serviceId;await mkdir(parent,{recursive:true,mode:0o755});await mkdir(root,{mode:0o755});t.after(async()=>{assert.equal(dirname(resolve(root)),parent);assert.equal(basename(root),identity.host.scope.serviceId);await rm(resolve(root),{recursive:true,force:true});});const f=await setup(t,{identity,root,trusted:true});await run(f,{mode:'stop'});await chmod(join(f.store.root,'stop.json'),0o666);await assert.rejects(f.store.read(identity));const lockPath=join(root,'control.lock');await unlink(lockPath);await symlink(join(f.store.root,'intent.json'),lockPath);await assert.rejects(withImagePreparationHostControlLock(root,async()=>assert.fail()));
});
