/** Qualification-only entry. Never included in service presets or auto-started.
 * No database, company, gateway, grant or storage mutations are performed. */
import {createHash} from 'node:crypto';
import {open,readFile,lstat,realpath} from 'node:fs/promises';
import {resolve,dirname,posix} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {z} from 'zod';
import {assertRemoteArchiveImmutableFile,parseRemoteArchiveArguments} from '../../src/lib/higgsfield-remote-archive-config';
import {createVercelMediaSandbox,VERCEL_MEDIA_IMAGE,type VercelMediaSandboxOptions,type VercelMediaIntent} from '../../src/lib/higgsfield-vercel-media-sandbox';
import {inspectHiggsfieldArchiveMedia} from '../../src/lib/higgsfield-media-inspection';
const hash=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');
const BACKEND_SHA256='abd4b274c4a4fb9d46cbbd4dbb8d7caa3db9fb34a1205c17e15c247175af36b9';
const absolute=z.string().max(1024).refine(value=>value.startsWith('/')&&value!=='/'&&!value.startsWith('//')&&!value.includes('\\')&&!value.includes('\0')&&posix.normalize(value)===value);
const digest=z.string().regex(/^[a-f0-9]{64}$/),identifier=z.string().regex(/^[A-Za-z0-9_-]{1,100}$/),relative=z.string().regex(/^[A-Za-z0-9_.+-]+(?:\/[A-Za-z0-9_.+-]+)*$/).refine(value=>!value.split('/').some(part=>part==='.'||part==='..'));
const schema=z.object({version:z.literal(1),purpose:z.literal('qualification-only'),sourceCommit:z.string().regex(/^[a-f0-9]{40}$/),backendSha256:z.literal(BACKEND_SHA256),bundleManifestPath:absolute,bundleManifestSha256:digest,reservation:z.object({id:z.uuid(),globalMaximum:z.literal(64),ordinals:z.tuple([z.number().int().min(1).max(64),z.number().int().min(1).max(64),z.number().int().min(1).max(64)])}).strict(),expiresAt:z.iso.datetime(),teamId:identifier,projectId:identifier,region:z.literal('iad1'),limits:z.object({maxInputBytes:z.union([z.literal(1048576),z.literal(16777216)]),maxClosureBytes:z.literal(268435456),timeoutMs:z.literal(120000),maxOutputBytes:z.literal(2097152),maxStderrBytes:z.literal(65536)}).strict(),closure:z.object({root:absolute,files:z.array(z.object({path:relative,bytes:z.number().int().positive().max(268435456),sha256:digest}).strict()).min(2).max(64),loader:relative.optional(),libraryDirectories:z.array(relative).max(16).optional()}).strict(),qualification:z.object({receiptPath:absolute,sha256:digest}).strict(),input:z.object({path:absolute,bytes:z.number().int().positive(),sha256:digest}).strict(),outputDirectory:absolute}).strict();
export function parseMediaServiceQualification(value:unknown){
 const config=schema.parse(value),ordinals=config.reservation.ordinals;
 if(ordinals[1]!==ordinals[0]+1||ordinals[2]!==ordinals[1]+1||config.outputDirectory!=='/var/lib/coatria-media-qualification/'+config.reservation.id)throw Error('QUALIFICATION_CONFIGURATION_INVALID');
 const small=config.input.bytes===111&&config.input.sha256==='b6203732a9ba997cc892a1b15d1d8bc92eb4abea11166d09734e4e2deffa0c8f',large=config.input.bytes===12586943&&config.input.sha256==='49c5ff2929aecbf4d576b1986c1060605a6edb007fc08239c6e1cf7cdf34ab5a';
 if(!small&&!large||config.input.bytes>config.limits.maxInputBytes)throw Error('QUALIFICATION_CONFIGURATION_INVALID');const freeze=(value:any)=>{if(value&&typeof value==='object'){for(const item of Object.values(value))freeze(item);Object.freeze(value);}};freeze(config);return config;
}
type Config=ReturnType<typeof parseMediaServiceQualification>;
/** Root must reserve all three global ordinals before creating the trusted CPU
 * host. This journal cannot invent global authority or safely replay a host. */
export function mediaQualificationJournal(config:Config,append:(value:unknown)=>Promise<void>,signal:AbortSignal){
 let count=0,active:string|null=null;const sessions=new Map<string,string>(),intents=new Map<string,VercelMediaIntent>(),handles=new Map<string,string>();
 const authorize=async(intent:VercelMediaIntent)=>{signal.throwIfAborted();if(Date.now()>=Date.parse(config.expiresAt)||intents.get(intent.id)!==intent)throw Error('QUALIFICATION_AUTHORITY_ENDED');};
 const journal:VercelMediaSandboxOptions['journal']={reserve:async intent=>{signal.throwIfAborted();if(active!==null||count>=3||Date.now()+intent.ttlMs>=Date.parse(config.expiresAt)||intent.teamId!==config.teamId||intent.projectId!==config.projectId||intent.region!==config.region||intent.image!==VERCEL_MEDIA_IMAGE||intent.inputBytes!==config.input.bytes||intent.inputSha256!==config.input.sha256||intent.ttlMs!==120000||intent.vcpus!==2||intent.memoryMiB!==4096||intent.tool!==['ffprobe','ffmpeg','ffprobe'][count])throw Error('QUALIFICATION_RESERVATION_REJECTED');active=intent.id;intents.set(intent.id,intent);count++;await append({type:'reserve',reservationId:config.reservation.id,globalOrdinal:config.reservation.ordinals[count-1],intent});},authorize,record:async event=>{const saved=intents.get(event.intentId),handle=handles.get(event.intentId);if(!saved||saved.name!==event.name||active!==event.intentId||event.sessionId&&handle&&event.sessionId!==handle||event.type==='terminal'&&(!event.sessionId||!['stopped','failed','aborted'].includes(event.status??'')))throw Error('QUALIFICATION_JOURNAL_CONFLICT');if(event.sessionId)handles.set(event.intentId,event.sessionId);await append({type:'provider-event',event});if(event.type==='terminal'&&event.sessionId&&event.status){sessions.set(event.sessionId,event.status);active=null;}}};
 return {journal,snapshot:()=>({createsReserved:count,maximumCreates:3,unresolvedIntent:active,terminalSessions:[...sessions].map(([sessionId,status])=>({sessionId,status}))})};
}
async function immutableJson(path:string,sha256:string,max=1024*1024){await assertRemoteArchiveImmutableFile(path);if((await lstat(path)).size>max)throw Error('QUALIFICATION_CONFIGURATION_INVALID');const bytes=await readFile(path);if(hash(bytes)!==sha256)throw Error('QUALIFICATION_CONFIGURATION_INVALID');return JSON.parse(bytes.toString('utf8'));}
export async function runMediaServiceQualification(args:readonly string[]){
 const cli=parseRemoteArchiveArguments(args);if(cli.preflight)throw Error('QUALIFICATION_CONFIGURATION_INVALID');await assertRemoteArchiveImmutableFile(fileURLToPath(import.meta.url));
 const config=parseMediaServiceQualification(await immutableJson(cli.path,cli.sha256)),now=Date.now();if(Date.parse(config.expiresAt)<=now+360000||Date.parse(config.expiresAt)>now+3600000)throw Error('QUALIFICATION_CONFIGURATION_INVALID');
 const bundle=await immutableJson(config.bundleManifestPath,config.bundleManifestSha256);if(bundle.sourceCommit!==config.sourceCommit||bundle.service!=='media-qualification'||bundle.deployable!==true||bundle.inputs?.find((entry:{path:string})=>entry.path==='src/lib/higgsfield-vercel-media-sandbox.ts')?.sha256!==BACKEND_SHA256)throw Error('QUALIFICATION_SOURCE_CHANGED');
 const entry=fileURLToPath(import.meta.url);if(bundle.runtime?.path!=='runtime.mjs'||entry!==dirname(config.bundleManifestPath)+'/runtime.mjs'||!Number.isSafeInteger(bundle.runtime.bytes)||bundle.runtime.bytes<1||bundle.runtime.bytes>8*1024**2||(await lstat(entry)).size!==bundle.runtime.bytes||hash(await readFile(entry))!==bundle.runtime.sha256)throw Error('QUALIFICATION_SOURCE_CHANGED');
 await assertRemoteArchiveImmutableFile(config.input.path);if((await lstat(config.input.path)).size!==config.input.bytes)throw Error('QUALIFICATION_INPUT_CHANGED');const input=await readFile(config.input.path);if(input.length!==config.input.bytes||hash(input)!==config.input.sha256)throw Error('QUALIFICATION_INPUT_CHANGED');
 const directory=await lstat(config.outputDirectory);if(!directory.isDirectory()||directory.isSymbolicLink()||directory.uid!==process.getuid?.()||(directory.mode&0o077)||await realpath(config.outputDirectory)!==config.outputDirectory)throw Error('QUALIFICATION_OUTPUT_INVALID');
 const audit=await open(config.outputDirectory+'/journal.jsonl','wx',0o600),control=new AbortController(),stop=()=>control.abort(),timer=setTimeout(stop,Math.min(420000,Date.parse(config.expiresAt)-Date.now()));process.once('SIGTERM',stop);process.once('SIGINT',stop);
 const append=async(value:unknown)=>{const text=JSON.stringify({at:new Date().toISOString(),...value as object});await audit.write(text+'\n');await audit.sync();console.log(text);};
 const session=mediaQualificationJournal(config,append,control.signal);let completed=false,failureCode:string|null=null,observed:unknown=null;
 try{await append({type:'qualification-start',productionAccepted:false,reservation:config.reservation,backendSha256:BACKEND_SHA256,input:{bytes:input.length,sha256:hash(input)}});
  const sandbox=await createVercelMediaSandbox({teamId:config.teamId,projectId:config.projectId,region:config.region,limits:config.limits,closure:config.closure,journal:session.journal,token:async()=>{const value=process.env.COATRIA_VERCEL_MEDIA_TOKEN;if(!value||value.length<8||value.length>4096||/[\r\n]/.test(value))throw Error('QUALIFICATION_CREDENTIAL_UNAVAILABLE');return value;}},config.qualification);
  const descriptor=await inspectHiggsfieldArchiveMedia({path:config.input.path,expectedKind:'image',expectedBytes:config.input.bytes,expectedSha256:config.input.sha256,signal:control.signal},{sandbox,sandboxTimeoutMs:90000,limits:{timeoutMs:300000,maxBytes:config.limits.maxInputBytes,maxProbeBytes:config.limits.maxOutputBytes}});observed=descriptor;const dimension=config.input.bytes===111?16:2048;if(descriptor.kind!=='image'||descriptor.format!=='png'||descriptor.codec!=='png'||descriptor.width!==dimension||descriptor.height!==dimension||descriptor.verification!=='full_decode'||descriptor.bytes!==config.input.bytes||descriptor.sha256!==config.input.sha256)throw Error('QUALIFICATION_MEDIA_MISMATCH');
  const state=session.snapshot();if(state.createsReserved!==3||state.unresolvedIntent!==null||state.terminalSessions.length!==3)throw Error('QUALIFICATION_CLEANUP_UNCONFIRMED');completed=true;
 }catch(error){failureCode=typeof(error as {code?:unknown})?.code==='string'?(error as {code:string}).code:error instanceof Error&&/^QUALIFICATION_[A-Z_]+$/.test(error.message)?error.message:'QUALIFICATION_FAILED';await append({type:'qualification-failed',code:failureCode});}
 finally{clearTimeout(timer);process.removeListener('SIGTERM',stop);process.removeListener('SIGINT',stop);await audit.sync();await audit.close();}
 const report={version:1,purpose:'qualification-only',productionAccepted:false,completed,failureCode,sourceCommit:config.sourceCommit,backendSha256:BACKEND_SHA256,reservation:config.reservation,limits:config.limits,input:{bytes:config.input.bytes,sha256:config.input.sha256},observed,...session.snapshot()};const file=await open(config.outputDirectory+'/report.json','wx',0o600);try{await file.writeFile(JSON.stringify(report,null,2)+'\n');await file.sync();}finally{await file.close();}console.log(JSON.stringify({type:'qualification-result',...report}));return report;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){void runMediaServiceQualification(process.argv.slice(2)).then(report=>{if(!report.completed)process.exitCode=1;}).catch(()=>{console.error('QUALIFICATION_CONFIGURATION_INVALID');process.exitCode=1;});}
