import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createReferenceEnrollmentCiRegistrar,parseReferenceEnrollmentCiReply,referenceEnrollmentCiDatabaseProof} from './qualify-reference-enrollment-ci.mjs';
import {makeReferenceEnrollmentIntent,enrollmentBytesHash as hash} from './reference-host-enrollment.mjs';
import {deriveReferenceRunnerConfiguration,referenceRunnerConfigurationHash} from './reference-runner-identity.mjs';
import {referenceEnrollmentServiceIdentity,referenceEnrollmentProjectIdentity} from '../../src/lib/higgsfield-reference-enrollment-contract.mjs';

const json=v=>Buffer.from(JSON.stringify(v,null,2)+'\n');
function fixture(){
 const serviceId=randomUUID(),companyId=randomUUID(),projectId=randomUUID(),bundleSha256='a'.repeat(64),release='/var/lib/coatria-reference-releases/'+bundleSha256;
 const host={version:1,bundleSha256,commit:'b'.repeat(40),tree:'c'.repeat(40),release,uid:1234,gid:1234,scope:{serviceId,companyId,projectIds:[projectId],origin:'https://coatria.example',expiresAt:new Date(Date.now()+600000).toISOString(),uploadHosts:['upload.example']},profiles:{real:{profilePath:`/etc/coatria-reference/${serviceId}/real.json`,expectedProfileSha256:'d'.repeat(64)},conformance:{profilePath:`/etc/coatria-reference/${serviceId}/conformance.json`,expectedProfileSha256:'e'.repeat(64)}},worker:{path:release+'/worker/runtime.mjs',sha256:'f'.repeat(64)},qualifier:{path:release+'/qualifier/runtime.mjs',sha256:'1'.repeat(64)},units:Object.fromEntries(['qualify','preflight','worker'].map(mode=>[mode,{name:`coatria-reference-${serviceId}-${mode}.service`,sha256:hash(mode)}]))};
 const hostBytes=json(host),receipt={version:2,kind:'coatria-reference-worker-qualification',serviceId,companyId,projectIds:[projectId],sourceCommit:host.commit,sourceTree:host.tree,bundleSha256,releaseSha256:host.worker.sha256,qualifierSha256:host.qualifier.sha256,hostConfigurationSha256:hash(hostBytes),configurationSha256:referenceRunnerConfigurationHash(deriveReferenceRunnerConfiguration(host,'0'.repeat(64))),profileSha256:host.profiles.real.expectedProfileSha256,conformanceProfileSha256:host.profiles.conformance.expectedProfileSha256,bootId:randomUUID(),uid:host.uid,gid:host.gid,expiresAt:host.scope.expiresAt,units:host.units,qualifierInvocationId:'2'.repeat(32),serviceRoot:'/sys/fs/cgroup/system.slice/'+host.units.qualify.name,evidenceSha256:'3'.repeat(64),reportSha256:'4'.repeat(64),acceptedAt:new Date(Date.now()-1000).toISOString(),qualified:true,checks:{isolation:true,resourceLimits:true,descendantCleanup:true,preparedImages:true}};
 const receiptBytes=json(receipt),scope={version:1,enrolledBy:randomUUID(),provider:{connectionId:randomUUID(),connectionRevision:1,catalogSha256:'5'.repeat(64)},projects:[{projectId,projectRevision:1,storageBindingId:randomUUID(),storageBindingRevision:1,storageConnectionId:randomUUID(),storageConnectionRevision:1}]},registrarSha='6'.repeat(64),scopeSha=hash(json(scope)),scopePath='/var/lib/coatria-reference-enrollment-ci-'+randomUUID()+'/scope.json',token='rfs_'+'x'.repeat(43);
 const intent=makeReferenceEnrollmentIntent({host,hostBytes,receipt,receiptBytes,qualificationSha256:hash(receiptBytes)},scope,{requestId:randomUUID(),token,scopeSha256:scopeSha,registrarBundleSha256:registrarSha}),pending={intent,intentBytes:json(intent),token,hostBytes,receiptBytes},request=intent.request;
 const success={requestId:request.requestId,requestHash:intent.requestHash,serviceId,status:'committed',active:true,credentialReady:true,workerEnabled:false};
 const url=new URL('postgresql://127.0.0.1:5432/coatria_ref_host_ci_'+randomUUID().replaceAll('-',''));url.username='coatria_higgsfield_reference_registrar_v1';url.password='synthetic-stdin-only';
 return {host,scope,registrarSha,scopeSha,scopePath,pending,request,success,url,workerEnv:Buffer.from('COATRIA_REFERENCE_SERVICE_TOKEN='+token+'\n'),rows:{services:[{...referenceEnrollmentServiceIdentity(request),expires_at:request.expiresAt,upload_hosts:request.uploadHosts,revoked_at:null}],projects:referenceEnrollmentProjectIdentity(request),enrollments:[{service_id:serviceId,company_id:companyId,request_id:request.requestId,request_hash:intent.requestHash,identity:request}]}};
}
test('compiled registrar command is fixed and synthetic database credential reaches stdin only',()=>{
 const f=fixture(),calls=[],invoke=createReferenceEnrollmentCiRegistrar(f.host,f.registrarSha,f.scopePath,f.scopeSha,(file,args,options)=>{calls.push({file,args,options});return {status:0,stderr:'',stdout:JSON.stringify(f.success)};});
 assert.equal(invoke('enroll',f.url.href).ok,true);const call=calls[0];assert.equal(call.file,f.host.release+'/runtime/node');assert.equal(call.args[0],'/var/lib/coatria-reference-registrars/'+f.registrarSha+'/runtime.mjs');assert.equal(call.args[1],'enroll');assert.deepEqual(call.options.env,{PATH:'/usr/bin:/bin',LANG:'C',LC_ALL:'C'});assert.equal(call.options.shell,false);assert.deepEqual(JSON.parse(call.options.input),{connectionString:f.url.href});assert(!JSON.stringify({file:call.file,args:call.args,env:call.options.env}).includes(f.url.password));
 for(const mode of['--yes','start','preflight'])assert.throws(()=>invoke(mode,f.url.href));
 for(const mutate of[u=>u.hostname='other.example',u=>u.username='postgres',u=>u.search='options=unsafe',u=>u.pathname='/production']){const url=new URL(f.url);mutate(url);assert.throws(()=>invoke('enroll',url.href));}assert.equal(calls.length,1);
 assert.throws(()=>createReferenceEnrollmentCiRegistrar({...f.host,release:'/tmp/unchecked'},f.registrarSha,f.scopePath,f.scopeSha));assert.throws(()=>createReferenceEnrollmentCiRegistrar(f.host,f.registrarSha,'/tmp/scope.json',f.scopeSha));assert.throws(()=>createReferenceEnrollmentCiRegistrar(f.host,'wrong',f.scopePath,f.scopeSha));
});
test('child failures, extra output and unsafe response shapes never count as success or leak raw diagnostics',()=>{
 const f=fixture();for(const result of[{status:1,stdout:JSON.stringify(f.success),stderr:'secret diagnostics'},{status:0,stdout:JSON.stringify(f.success)+'\n{}',stderr:''},{status:0,stdout:'invalid',stderr:''},{status:0,stdout:JSON.stringify({...f.success,workerEnabled:true}),stderr:''},{status:0,stdout:JSON.stringify({...f.success,privateUrl:f.url.href}),stderr:''},{status:0,stdout:JSON.stringify(f.success),stderr:f.url.href},{status:0,error:Error(f.url.href),stdout:JSON.stringify(f.success)}])assert.throws(()=>parseReferenceEnrollmentCiReply('enroll',result),error=>error.message==='REFERENCE_ENROLLMENT_CI_REJECTED'&&!error.message.includes(f.url.password));
 const rejected=parseReferenceEnrollmentCiReply('enroll',{status:1,stdout:'',stderr:JSON.stringify({event:'reference-host-enrollment-stopped',code:'REFERENCE_HOST_ENROLLMENT_REJECTED',workerEnabled:false})});assert.deepEqual(rejected,{ok:false,code:'REFERENCE_HOST_ENROLLMENT_REJECTED'});
});
test('command rejects a success response for a different service',()=>{
 const f=fixture(),invoke=createReferenceEnrollmentCiRegistrar(f.host,f.registrarSha,f.scopePath,f.scopeSha,()=>({status:0,stderr:'',stdout:JSON.stringify({...f.success,serviceId:randomUUID()})}));assert.throws(()=>invoke('reconcile',f.url.href));
});
test('independent proof rejects success with a different SQL identity, source scope, credential or prior receipt',()=>{
 const f=fixture(),proof=referenceEnrollmentCiDatabaseProof(f.pending,f.rows,f.workerEnv);assert.equal(proof.tokenHashMatches,true);assert.equal(proof.requestHash,f.success.requestHash);assert(!JSON.stringify(proof).includes(f.pending.token));
 for(const change of[r=>r.services[0].token_hash='0'.repeat(64),r=>r.services[0].company_id=randomUUID(),r=>r.services[0].revoked_at=new Date(),r=>r.projects[0].storage_binding_revision++,r=>r.enrollments[0].request_hash='0'.repeat(64),r=>r.enrollments[0].identity.qualificationSha256='0'.repeat(64),r=>r.services.push(r.services[0])]){const rows=structuredClone(f.rows);change(rows);assert.throws(()=>referenceEnrollmentCiDatabaseProof(f.pending,rows,f.workerEnv));}
 assert.throws(()=>referenceEnrollmentCiDatabaseProof(f.pending,f.rows,Buffer.from('wrong')));assert.throws(()=>referenceEnrollmentCiDatabaseProof({...f.pending,receiptBytes:Buffer.concat([f.pending.receiptBytes,Buffer.from(' ')])},f.rows,f.workerEnv));
});
